### ISSUE TITLE
Backend integration documentation?

### ISSUE THREAD

**Issue by tgaudin** [epam/ketcher#1]
Currently I'm using ketcher on my own backend as I use it mainly as an input source.

It would be really nice to know what indigo service's quieries and answers look like to be able to integrate it correctly in my application. 

Do you have any documentation on that?

**Comment by michal-husak** [comment]
would this help you?
http://lifescience.opensource.epam.com/indigo/service/index.html

**Comment by MichelML** [comment]
@michal-husak a full tutorial to actually deploy the indigo service would be appreciated.

On my side I need the full features of ketcher. I know docker and can't get my way to deploy the backend with the link you posted.

**Comment by MichelML** [comment]
@AlexanderSavelyev anyways we can have more details on how to set the indigo service up?

Sorry for the generic ping, I need to set this up quickly.

**Comment by AlexanderSavelyev** [comment]
@MichelML  

Easiest way is run the following command (no need to download images)
```
docker run --restart=always -d -p 8002:8002 -e "INDIGO_UWSGI_RUN_PARAMETERS=--plugin python3 --py-autoreload=1"
-e "PYTHONPATH=/srv/indigo-python" -e "PYTHONDONTWRITEBYTECODE=1" --name=indigo_service
epmlsop/indigo_service:latest /bin/sh -c "supervisord -n"
```

and then configure nginx uwsgi according to 
https://lifescience.opensource.epam.com/indigo/service/index.html

**Comment by AlexanderSavelyev** [comment]
if you have different web server (e.g. apache), please use the following instructions to setup the uwsgi

https://uwsgi-docs.readthedocs.io/en/latest/WebServers.html

**Comment by MichelML** [comment]
@AlexanderSavelyev I'm supposed to setup nginx seperately? e.g. have a docker container running for it or set it up on my remote instance? This is the part that's not clear. I see nginx no where in the docker image `epmlsop/indigo_service`

**Comment by AlexanderSavelyev** [comment]
yes, nginx should be run separately. The reason for the environment with separate web server is that ketcher static files and indigo-service should be hosted on the same server and port. Otherwise REST API will not work because of [CORS ](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)

One can install nginx as a docker image or separate installation. There many [instructions ](http://nginx.org/en/docs/install.html) with many examples for different OS

Could you please inform, where do you plan to host the ketcher and what web server to use? Because if you create an nginx server (e.g. port 8080) and ketcher  (e.g. on port 443) you still will need to port forward to your server, so please take a look at uwsgi possibilities for your web server

**Comment by AlexanderSavelyev** [comment]
Yes, this might be one of possible installations, but usually nginx is used as a standalone server (which hosts not only Ketcher and indigo service) and it is better to use system network for it (not from docker). But thanks for providing docker compose config. This solution might work for some simple scenarios. I will include it into the repo as an example.

**Comment by MichelML** [comment]
Thanks @AlexanderSavelyev and I understand your point - and agree with you 👍 . I guess once you added the example you could close this.

**Comment by jaohbib** [comment]
Iam currently running an apache (outside of Docker) which deploys ketcher and the rest of my application.  is it possible to  use my already existing apache to access the container ?

**Comment by AlexanderSavelyev** [comment]
Hi @jaohbib  
I haven't test it but according to this [document ](https://uwsgi-docs.readthedocs.io/en/latest/Apache.html) it can be possible to use apache with mod_proxy_uwsgi
It seems that after creating a docker instance on localhost:8002 the apache config can just include 
```
ProxyPass / uwsgi://127.0.0.1:8002/
```
or include some other path (and change api-path in Ketcher). 
Please inform if it helps

Thanks
Aleksandr
