### ISSUE TITLE
Error when apply 3D to empty canvas

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1003]
**Steps to Reproduce**
1. Open Ketcher in any browser
2. Do not place any on the canvas
3. Select 3D
4. Click Apply

**Expected behavior**
 No error message is shown

**Actual behavior**
  Error modal is shown

**Screenshots**

![null](https://user-images.githubusercontent.com/93334478/143014997-e9bca5dc-d49c-49e6-883e-5fe2cb38783e.png)

 **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by Alex-Work-Account** [comment]
It's not a Firefox problem. There shouldn't be an error if a user clicked on apply

**Comment by AllaZhbanova** [comment]
Fixed, tested on v. 2.4
