### ISSUE TITLE
Incorrect bond rendering on Benzene ring after dearomatize

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/ketcher#1005]
**Steps to Reproduce**
1. Open Ketcher demo (remote or standalone), add Benzene ring
2. Press "aromatize"
3. Press "dearomatize"

**Expected behavior**
The same Benzene ring as after step 1.

**Actual behavior**
One double bond rendered incorrectly

**Screenshots**
![image](https://user-images.githubusercontent.com/4228185/143036540-b3d561d9-64a6-4f9a-a07e-e998558667bb.png)

**Comment by ElenaOdnoshivkina** [comment]
This issue was fixed as part of https://github.com/epam/ketcher/issues/517

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
