### ISSUE TITLE
IndigoException: element: can not calculate valence on C, charge 0, connectivity 6 on saving chain with triple bond

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1008]
**Steps to Reproduce**
1. Add chain
2. Add triple bond to canvas  
[errorsindigo.zip](https://github.com/epam/ketcher/files/7588954/errorsindigo.zip)

3. Click Save button

**Expected behavior**
The structures are saved without errors

**Actual behavior**
IndigoException: element: can not calculate valence on C, charge 0, connectivity 6 error is shown 

**Screenshots**

![error](https://user-images.githubusercontent.com/93334478/143048308-84989c3e-d6dd-4fb3-a13d-ab09a668e1a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
https://github.com/epam/ketcher/issues/1008

**Comment by ElenaOdnoshivkina** [comment]
Related issue: https://github.com/epam/Indigo/issues/538

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
