### ISSUE TITLE
npm run build only generates dist directory

### ISSUE THREAD

**Issue by jaohbib** [epam/ketcher#102]
Hi 

I used npm run build to build the current version. the build directory is missing the dist directory misses the index.html which i currently use to integrate ketcher. I just want to test the fix for https://github.com/epam/ketcher/issues/83 

Is the Master even considred stable in this Project ?

jaoh@pubpharm:~/git/ketcher_bleeding/ketcher$ npm run build --api-path=/v2

> @ketcher/react@2.0.0-RC build /home/jaoh/git/ketcher_bleeding/ketcher
> rollup -c -m true

src/index.tsx → dist/index.js, dist/index.modern.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
query-string (imported by src/script/index.js)
@babel/runtime/helpers/interopRequireDefault (imported by @babel/runtime/helpers/interopRequireDefault?commonjs-external)
url (imported by url?commonjs-external)
remark-parse (imported by remark-parse?commonjs-external)
unified (imported by unified?commonjs-external)
@babel/runtime/helpers/interopRequireWildcard (imported by @babel/runtime/helpers/interopRequireWildcard?commonjs-external)
@babel/runtime/helpers/extends (imported by @babel/runtime/helpers/extends?commonjs-external)
@babel/runtime/helpers/objectWithoutPropertiesLoose (imported by @babel/runtime/helpers/objectWithoutPropertiesLoose?commonjs-external)
xtend (imported by xtend?commonjs-external)
unist-util-visit (imported by unist-util-visit?commonjs-external)
unist-util-visit-parents (imported by unist-util-visit-parents?commonjs-external)
object-assign (imported by object-assign?commonjs-external)
asap (imported by asap?commonjs-external)
created dist/index.js, dist/index.modern.js in 32.6s
jaoh@pubpharm:~/git/ketcher_bleeding/ketcher$ cd
dist/         example/      .git/         node_modules/ src/          test/         .vscode/
jaoh@pubpharm:~/git/ketcher_bleeding/ketcher$ cd dist/
jaoh@pubpharm:~/git/ketcher_bleeding/ketcher/dist$ ls
contexts  hooks  icons  index.css  index.d.ts  index.js  index.js.map  index.modern.js  index.modern.js.map  index.test.d.ts  overlay.svg  script
jaoh@pubpharm:~/git/ketcher_bleeding/ketcher/dist$

**Comment by AndreiMazol** [comment]
Dear @jaohbib ,

please have a look at DEVNOTES.md: the latest version of Ketcher has been splitted into two packages: component library (see /src folder) and React Ready-to-run application (see /example folder) so you need to start example application  to test changes after building component library.

Best regards,
Ketcher team
