### ISSUE TITLE
Redesign the floating windows - Functional groups window

### ISSUE THREAD

**Issue by AnaMoskvina** [epam/ketcher#1021]
Change the visual representation of the Functional groups window.

GIVEN Ketcher user WHEN clicking on Functional groups icon THEN I see the window with Functional groups  AND
there is a search input on the top used for searching functional groups AND
I can type abbreviation (or fragments of abbreviation) of functional groups AND I will get filtered out functional groups (all items having requested pattern in their abbreviations) AND
If there's no corresponding items, I will see 'Noting is found' message AND
I can close the window by clicking on the cross icon or by using Esc hotkey AND
I can save my chosen functional group to the file

Use the designs for template library window as references (there will be no groupings, and 'open', 'view similar', 'create new' buttons):
![extended_table_1](https://user-images.githubusercontent.com/77681522/143402308-d93855c9-5dbb-441f-8a17-94e6b57f4c76.png)

![extended_table_2](https://user-images.githubusercontent.com/77681522/143402321-c0d99486-dfc3-4109-bac7-aa01e81ba678.png)

**Comment by AndreiMazol** [comment]
Waiting for prototypes for FGs modal window.
cc: @Alena-Guznischeva

**Comment by AndreiMazol** [comment]
Rejection reason: design has been reworked https://github.com/epam/ketcher/issues/1341
