### ISSUE TITLE
Redesign the floating windows - Save structure

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1025]
Change the visual representation of the window for saving the file from Ketcher. 
Rules for suggesting the available formats should stay the same, along with warnings identifying logic. 

![image](https://user-images.githubusercontent.com/90251323/143415053-499594f4-7289-4589-bd0d-143dd5e75bac.png)

**Comment by AllaZhbanova** [comment]
Implemented, tested v.2.5
