### ISSUE TITLE
Structure shouldn't flipped when a part structure is selected

### ISSUE THREAD

**Issue by ElenaOdnoshivkina** [epam/ketcher#1029]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create any structure 
3. Select a part of the structure and choose the 'Horizontal Flip' or 'Vertical Flip' tool.

**Expected behavior**
Structure isn't flipped when a part structure is selected.

**Actual behavior**
Structure is flipped when a part structure is selected.

https://user-images.githubusercontent.com/89905163/143539827-c246966a-2f75-4249-bd46-bea9b4c6cc0c.mp4

**Comment by AllaZhbanova** [comment]
Fixed, tested v. 2.4
