### ISSUE TITLE
Roadmap and future releases

### ISSUE THREAD

**Issue by DanielBogenrieder** [epam/ketcher#103]
Hi,

I have seen, that the last release candidate is from 2018. So I was wondering if there is a plan to release a stable release version in the near future? Furthermore, it would be interesting to know if there is some sort of roadmap for this project?

Greetings,
Daniel

**Comment by AndreiMazol** [comment]
Dear @DanielBogenrieder ,

Ketcher team is working towards new release. That release will be mostly dedicated to increase usability of Ketcher and moving it to modern rails.
Regarding to the second part of your question: sure, the roadmap exists and we are going to publish it to Wiki.

Best regards,
Ketcher team

**Comment by DanielBogenrieder** [comment]
Thanks for the fast reply. That sounds great, is there any timeline on when we can expect that release?

**Comment by AndreiMazol** [comment]
The next release is planned in a few weeks based on results of regression testing.
