### ISSUE TITLE
IndigoException: molecule auto loader: Unsupported node for molecule for automapping action

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1039]
**Steps to Reproduce**
1. Open file with reaction or place some structures and add reaction arrow
[reaction_4.zip](https://github.com/epam/ketcher/files/7618865/reaction_4.zip)

2. Apply "Reaction auto mapping"
3. Select any option
4. Click OK

**Expected behavior**
The reaction is mapped

**Actual behavior**
Error is shown: IndigoException: molecule auto loader: Unsupported node for molecule for automapping action

**Screenshots**

https://user-images.githubusercontent.com/93334478/143887706-2365ed95-8917-45c1-a1bb-05439aa462f7.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10, Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by r1z3rISGOD** [comment]
https://github.com/epam/Indigo/issues/529

**Comment by AllaZhbanova** [comment]
fixed, tested 2.4
