### ISSUE TITLE
Text Tool: Add special symbols

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#1044]
It is necessary to extend  the list of existed controls by additional button that allows to insert special symbols. The list  of special symbols provided below:

'α,β,γ,δ,ε,ζ,η,θ,ι,κ,λ,μ,ν,ξ,ο,π,ρ,σ,τ,υ,φ,χ,ψ,ω,℃,℉,Å,°,ħ,±,‰,√,←,→,↚,↛,↔,⇌,∏,∑,∞,∂,∆,∫,≈,≠,≤,≥'

**Comment by AllaZhbanova** [comment]
Implemented, tested v.2.5
