### ISSUE TITLE
Arrow Tool: Elliptical Arrows

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#1045]
|As | I Want | That |
| ------ | ------ | ------ |
| User | I want to show the reaction mechanism to show charge distribution | I can draw some curly arrows and delta+/-

The following arrows should be added:
- Elliptical Arc Arrow (triangle, Bow, Open Angle, Open Half Angle)

**Comment by AllaZhbanova** [comment]
Implemented, tested v.2.5
