### ISSUE TITLE
Error message Convert error! IndigoException: inchi-wrapper: Indigo-InChI: InChI generation failed: Empty structure Code: 2.  InChi for empty canvas  

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1058]
**Steps to Reproduce**
1. Open Ketcher
2. Click the Save As button (for empty canvas).
3. Choose the 'InChi' format.

**Expected behavior**
The input field contains InChI=1S// string.

**Actual behavior**
Error message
Convert error! IndigoException: inchi-wrapper: Indigo-InChI: InChI generation failed: Empty structure. Code: 2.

**Screenshots**
![2021-12-03_16h26_07](https://user-images.githubusercontent.com/93334478/144610873-8b0d1bbc-f938-4117-895d-3996fdad6993.png)
I

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by ViktoriiaFedotkina** [comment]
Related issue https://github.com/epam/Indigo/issues/548

**Comment by AllaZhbanova** [comment]
Fixed, tested 2.4
