### ISSUE TITLE
Redesign the floating windows - Open structure

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1067]
Change the visual representation & flow for the Open structure abilities:

1. When clicking on Open open the window suggesting to open\drag files or open structure from the clipboard. 
2. When dragging or opening the picture file the form displaying the picture and suggesting to select IMAGO version should appear. 
3. When dragging or opening the text file the form with text displayed and the ability to edit it should be opened
4. When clicking on copy from Clipboard text form should be opened with empty text. The Open button should be available only if the text editor is not empty. 
5. Errors of the text file should be checked the same way they are checked right now. 
6. Use a new component of the 3 dots as a placeholder for the time the file is analyzed. 
7. Present Open from the picture part as disabled in Standalone mode with message "Ketcher supports recognition only in Remote mode". When a picture is dropped in the Standalone mode display the error message with the same text. 

Dec, 15th: see the comment below, replacing checkbox for open mode with 2 buttons.

**Comment by Alena-Guznischeva** [comment]
Please, change how the open mode is selected for the text editor window: 
1) Remove the checkbox on the bottom of Text editor window. 
2) Add button "Add to Canvas", rename Open button to "Open as New Project". Implement tooltip for the new button: "Structure will be loaded as fragment and added to Clipboard".  
The logic of the new button should be the one applying when we click Open with the Checkbox marked. 

![image](https://user-images.githubusercontent.com/90251323/146166307-8652bafd-ce34-4120-9804-e1ce0c95b21e.png)

**Comment by akolyakov42** [comment]
Tested, but error handling functionality is not yet implemented
<img width="619" alt="Screenshot 2022-01-21 at 13 35 01" src="https://user-images.githubusercontent.com/97884482/150512600-234537b0-fe38-4829-b073-c77ba282eab6.png">
