### ISSUE TITLE
Any Pseudoatom is replaced with A if save the structure with pseudoatom in Daylight SMILES

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1069]
**Steps to Reproduce**
1. Create chain structure
2. Replace any atom with pseudoatom  (Periodic table -> 'Generic Groups' table) ->Select any atom except A (for example XH)
3. Click Save
4. Select Daylight SMILES format
5. Save
6. Open saved file in Ketcher

**Expected behavior**
The structure generated from SMILE string is correct, pseudoatoms are rendered correctly 

**Actual behavior**
Any Pseudoatom is replaced with A 
**Screenshots**

https://user-images.githubusercontent.com/93334478/145225444-e4145a1c-3f64-40e3-a036-55a9a34d53dc.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by ElenaOdnoshivkina** [comment]
Daylight SMILES format doesn't support different types of pseudoatoms. Any pseudoatoms are identically saved to Daylight SMILES as *.  There is a warning when the saved structure contains pseudoatoms in the Daylight SMILES saying that they will not be saved the same way as they are represented on the canvas.
Approved by @Alena-Guznischeva and @AlexanderSavelyev
