### ISSUE TITLE
Refactor all Editor tools to classes and TS

### ISSUE THREAD

**Issue by ViktoriiaFedotkina** [epam/ketcher#1072]
All editor tools (like rotate, etc.) should be 
- switched to TS
- turned into Classes

**Comment by ElenaOdnoshivkina** [comment]
Changes related to this task resulted in the following issues:

1. https://github.com/epam/ketcher/issues/1096
2. https://github.com/epam/ketcher/issues/1102

For this reason, the changes were reverted as part of the pull request: https://github.com/epam/ketcher/pull/1114

It is necessary to analyze all factors and refactor them correctly.
