### ISSUE TITLE
Style leakage / Shadow root

### ISSUE THREAD

**Issue by dfelder** [epam/ketcher#1085]
Hi everyone, thanks for the awesome work!

When I embed Ketcher it seems to leak a few styles that conflict with bootstrap. Mainly from ketcher-react/dist/index.css. Would it make sense to encapsulate everything in a shadow root out of the box? 

Here's an example: 
```tsx
import { StandaloneStructServiceProvider } from "ketcher-standalone";
import { Editor, Ketcher } from "ketcher-react";
import root from 'react-shadow';
import raw from 'raw.macro';
const structServiceProvider = new StandaloneStructServiceProvider();

const ketchercss = raw('ketcher-react/dist/index.css');
const miewcss = raw('miew/dist/Miew.min.css');

const ChemicalPage = () => {
  return (
    <root.div>
      <Editor
        staticResourcesUrl={process.env.PUBLIC_URL}
        structServiceProvider={structServiceProvider}
      />
      <style type="text/css">{ketchercss}</style>
      <style type="text/css">{miewcss}</style>
    </root.div>
  );
}
```

**Comment by AndreiMazol** [comment]
Dear @dfelder ,

Thank you  for your interest to Ketcher.

I want to  inform  you  that this issue has been already  fixed in scope of https://github.com/epam/ketcher/issues/699. 
This changes will be delivered as a part of release 2.4.

Best regards,
Andrei

**Comment by dfelder** [comment]
Great, thanks!
