### ISSUE TITLE
Structure is not deleted by pressing "Delete" button

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1096]
**Steps to Reproduce**
1.Place any structure on the canvas
2. Select the structure
3. Press Delete button on the keyboard 

**Expected behavior**
The structure is deleted

**Actual behavior**
The structure is not deleted, easer tool is selected 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by ElenaOdnoshivkina** [comment]
The problem is related to refactoring of tools in the task: https://github.com/epam/ketcher/issues/1072
For this reason, it was necessary to revert changes made as a pull request: https://github.com/epam/ketcher/pull/1114
After reverting the changes, this bug is not reproduced

**Comment by AllaZhbanova** [comment]
fixed, tested v.2.4
