### ISSUE TITLE
Redesign Recognize Molecule floating window

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1097]
1. Remove Recognize molecule button from the top toolbar
2. Recognize should be able to initiate from the Open window. The Open structure modal window should allow the initiation of selecting the image file from the workstation. The list of file extensions that are displayed by default should be the same as they are now for Recognize -> Select file. 
When a file selection is confirmed the Recognize operation using Imago ver.2 should be initiated immediately with the opening of the Recognize window. 
2.1. Use the 3 dots placeholder to wait for Recognition results in the  right part of the window and display the structure view when they arrived. 
2.2. Use placeholder with text "Preview of the file selected is not supported" for the left part of the Recognize window if preview is not available. NB: would be great to explain the exact criteria when preview is not available. 
2.3. Imago version selected should be version 2, selection of version 1 should be disalbed. 
3. Same flow should be initiated if the image file was dropped to the Open Structure window
4. Recognize window should have buttons  "Change image", "Add to Canvas"  and "Open as New Project" with the last one as the main button marked by color (design is not like that, pay attention)  
5. File re-selection from Recognize window with clicking on "Change image" button should allow to select the file from workstation just like when initiating recognition from the Open menu. File selection confirmation should initiate recognize operation initiation with Imago Version 2 just like from the Open menu and displayed the same Import from the Image window with the same behaviour. 
6. Only the last recognized structure should be added to the canvas in the mode (adding of replacing) selected by the user. 

Use the following designs : 

![image](https://user-images.githubusercontent.com/90251323/161285729-d68f5578-6d01-4cb3-b5e0-9a4aa76e4462.png)

**Comment by AnaMoskvina** [comment]
On art. 2.3: Imago version selected should be version 2, and selection of version 1 should **NOT** be disalbed.

**Comment by ansivgit** [comment]
There is not all file types are supported.
![err_bmp_gif_tif](https://user-images.githubusercontent.com/56927722/163830261-2629b931-cddc-4fe6-adcb-9a537497959b.gif)
There is the error for *.bmp, *.gif, *.tif files

![err_svg_ico_as_image](https://user-images.githubusercontent.com/56927722/163830488-43229dad-58b6-43e3-be5a-02219072545b.gif)
There is the error for *.svg, *.ico files

![err_svg_as_image](https://user-images.githubusercontent.com/56927722/163830587-7654c498-e929-4585-8326-9e8a46f4f790.gif)
Another error for *.svg, *.webp, *.jxl as an image

Files that are created outside the application are not recognized correctly (png or jpg-format, other formats also doesn't work at all)
![err_png_from_outside](https://user-images.githubusercontent.com/56927722/163830166-2b6e6da2-d028-4216-a134-87acfe9c2ffa.gif)

**Comment by ZhannaNovikova** [comment]
The issues have been created:
https://github.com/epam/ketcher/issues/1455[](https://github.com/epam/ketcher/issues/1455)
https://github.com/epam/Indigo/issues/712[](https://github.com/epam/Indigo/issues/712)
https://github.com/epam/ketcher/issues/1488

**Comment by ZhannaNovikova** [comment]
The issues related to the default radio button appearance does not match the mockup and incorrect text font will be fixed in #1454

**Comment by ZhannaNovikova** [comment]
Verified in Release 2.5.0
