### ISSUE TITLE
Redesign the floating windows - Extended table

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1100]
Change the visual design of the Extended table panel using the designs below:
![image](https://user-images.githubusercontent.com/90251323/146159368-baa96010-76de-4554-bc35-4548ea49312a.png)

Use the existing approach with radio buttons for the selection type below.

**Comment by akolyakov42** [comment]
Visual representation of window accords to updated version of design, but bottom checkboxes are deprecated (they're still in design layout)
<img width="443" alt="Screenshot 2022-01-21 at 13 08 35" src="https://user-images.githubusercontent.com/97884482/150508473-d124c98e-8887-43fb-8f09-ab36a6808251.png">
