### ISSUE TITLE
Functional group atom can be edited by long click

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1103]
**Steps to Reproduce**
1. Expanded FG structure is placed on canvas. For example from [this file](https://github.com/epam/ketcher/files/7608676/ketcher.21.zip).
2. With Select tool click on one atom and hold until _Label Edit_ modal shows up.
3. Edit label, press OK

**Expected behavior**
Edit is not permitted without removing FG abbreviation. _Edit Abbreviation_ modal must be shown.

**Actual behavior**
Label is edited.

**Screencast**
![Запись экрана 2021-12-16 в 11 16 35](https://user-images.githubusercontent.com/18420141/146334523-15148118-976e-4780-a53f-ce9c767de0e3.gif)

**Desktop:**
 - OS: MacOS Monterrey
 - Browser Chrome

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
