### ISSUE TITLE
Some atoms and bonds are not detected as part of FG on doubleclick

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1109]
**Steps to Reproduce**
1. Expanded FG structure is placed on canvas. For example from [this file](https://github.com/epam/ketcher/files/7608676/ketcher.21.zip).
2. With Select tool double click on one atom or bond

**Expected behavior**
None of the atoms or bonds that are doubleclicked on can be edited. _Edit Abbreviation_ modal is shown

**Actual behavior**
Some atoms and bonds can be edited. I found that the atoms and bonds that can be edited are those with id of 0.

**Screencast**
![Запись экрана 2021-12-16 в 13 53 50](https://user-images.githubusercontent.com/18420141/146359939-fa89f782-b905-4d39-9211-17fca7e46cbb.gif)

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
