### ISSUE TITLE
Reaction arrow and plus are removed after Clean Up action

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1131]
**Steps to Reproduce**
1. Open Ketcher in Remote mode
2. Place some reaction 
3. Clean Up

**Expected behavior**
Reaction arrow and plus are not deleted

**Actual behavior**
Reaction arrow and plus  disappeared 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by ViktoriiaFedotkina** [comment]
Related issue https://github.com/epam/Indigo/issues/571

**Comment by AllaZhbanova** [comment]
Fixed, tested 2.4
