### ISSUE TITLE
ket file with no nodes cannot be deserialized

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1137]
**Steps to Reproduce**
1. Launch Ketcher
2. Click Open file
3. In Open Structure modal open empty *.ket file like this one: [empty.ket.zip](https://github.com/epam/ketcher/files/7762667/empty.ket.zip)
4. Click OK

**Expected behavior**
Modal is closed, empty canvas is shown

**Actual behavior**
Error message is shown:

![empty-ket-scrn](https://user-images.githubusercontent.com/18420141/147094812-48508cb3-7d08-4024-bc78-dd63eb5ac27b.png)

**Comment by AllaZhbanova** [comment]
Reopened as Expected result: Window is closed on clicking OK button , Empty canvas is shown
Actual result: Window is not closed

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
