### ISSUE TITLE
Error message Convert error! struct data not recognized as molecule, query, reaction or reaction query on opening structure with atoms that have (0,0) coordinates

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1156]
**Steps to Reproduce**
1.Open files with  structure with atoms that have (0,0) coordinates

[files.zip](https://github.com/epam/ketcher/files/7780202/files.zip)

**Expected behavior**
File is opened, Structure is placed to the canvas

**Actual behavior**
Error is shown

**Screenshots**
![2021-12-27_15h47_12](https://user-images.githubusercontent.com/93334478/147473114-c81a7b71-da4a-461c-8bfe-1df38151c4ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
Related issue: 
https://github.com/epam/Indigo/issues/581

**Comment by ZhannaNovikova** [comment]
After investigation from backend side: - "Attached mol-files are corrupted. Chemaxon is unable to load them as well." and re-checking from the front side the issue should be closed.

**Comment by evgeniiFrolov1** [comment]
waiting for indigo update
