### ISSUE TITLE
(R) and (S) stereo labels are in the wrong positions after calculate CIP action

### ISSUE THREAD

**Issue by Alex-Work-Account** [epam/ketcher#1159]
**Steps to Reproduce**
1. Open file with structures with stereo bonds  
[structure_with_stereo_bonds.zip](https://github.com/epam/ketcher/files/7780687/structure_with_stereo_bonds.zip)

**Expected behavior**
![image](https://user-images.githubusercontent.com/94836496/147483494-facf0535-3717-4345-8b01-57d67baea60c.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/94836496/147483512-53cb1245-7291-4643-a1dc-e41a2949ba47.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
Related https://github.com/epam/Indigo/issues/586

**Comment by AllaZhbanova** [comment]
Fixed tested in Standalone mode, v.2.4
