### ISSUE TITLE
"Cannot calculate properties for structures with query features!" error on COCO_preventhydrogen structure calculation

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#1160]
**Steps to Reproduce**
1. Open file in ketcher   
[25COCO_preventhydrogen.zip](https://github.com/epam/ketcher/files/7780727/25COCO_preventhydrogen.zip)
2. Click Calculate 

**Expected behavior**
exact mass: 58.005 

**Actual behavior**
"Cannot calculate properties for structures with query features!" error 

**Screenshots**

https://user-images.githubusercontent.com/93334478/147484314-12a723db-0936-417d-bf4e-a74d6960dda1.mp4

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser  Chrome Version 93.0.4577.63, Firefox Version 94.0.1, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
Need clarification from BA (@Alena-Guznischeva )
Looks like the file is incorrect as it contains information about H count = -1
![2021-12-28_10h50_30](https://user-images.githubusercontent.com/93334478/147542580-42ffddde-4717-42b5-8b49-27f4b0e96c28.png)
But we do not have this value in H count field for atom properties
![2021-12-28_10h52_47](https://user-images.githubusercontent.com/93334478/147542716-ce7e753d-29d7-4039-a76b-c68616973265.png)
So when we open the file the atom H count property is changed to 0
![2021-12-28_10h51_39](https://user-images.githubusercontent.com/93334478/147542793-6ef49194-1e6d-4619-8864-8d73bd12b092.png)
And calculation is not the same as expected

**Comment by AndreiMazol** [comment]
Moved to release 2.5
cc: @AllaZhbanova
