### ISSUE TITLE
Stereocenter labels color gradient does not work in Firefox

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1163]
**Steps to Reproduce**
1. Use Firefox browser. Open chain structure with multiple stereocenters in Ketcher
[color_stereocenters.ket.zip](https://github.com/epam/ketcher/files/7783767/color_stereocenters.ket.zip)
2. Open Settings -> Stereochemistry
3. Make sure following settings are set: 
- _Label display at stereogenic centers_ is set to `On`
- _Color stereogenic centers_ is set to `Labels Only`
- _Auto fade And/Or center labels_ is set to `On`
4. Press OK.

**Expected behavior**
Intensity of color of &-labels at top right structure is decreasing as number in label grows.
![image](https://user-images.githubusercontent.com/18420141/147548930-49dd18e4-9551-4dea-aa23-36bce694c1fe.png)

**Actual behavior**
Intensity of color is the same for all labels.
![image](https://user-images.githubusercontent.com/18420141/147549123-a82792a8-5a61-4ba5-8477-67d937f17988.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Monterey
 - Firefox Browser 95.0.2 (64-bit)

**Comment by AllaZhbanova** [comment]
fixed, tested 2.4
