### ISSUE TITLE
can not setMolecule in onInit

### ISSUE THREAD

**Issue by zspishere** [epam/ketcher#1174]
**Steps to Reproduce**
1. add codes as below after https://github.com/epam/ketcher/blob/master/example/src/App.tsx#L63
```
var mol = [
  '',
  '  Ketcher 02151213522D 1   1.00000     0.00000     0',
  '',
  '  6  6  0     0  0            999 V2000',
  '   -1.1750    1.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0',
  '   -0.3090    1.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0',
  '   -0.3090    0.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0',
  '   -1.1750   -0.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0',
  '   -2.0410    0.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0',
  '   -2.0410    1.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0',
  '  1  2  1  0     0  0',
  '  2  3  2  0     0  0',
  '  3  4  1  0     0  0',
  '  4  5  2  0     0  0',
  '  5  6  1  0     0  0',
  '  6  1  2  0     0  0',
  'M  END'
].join('\n')
ketcher.setMolecule(mol)
```
2. `yarn start:standalone`
3. Click `Aromatize` Button, then **the molecule disappeared**

**Expected behavior**
Expect the molecule change to another style, like below
![screenshot-20220111-212102](https://user-images.githubusercontent.com/19356426/148950028-df37f27b-a216-4ee8-9f15-9753a2fd186a.png)

**Actual behavior**
The molecule disappeared.

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Browser [Chrome]

**Additional context**
If the code added as below, the function of Button `Aromatize` is as expected.
```
const mol = 'C1=CC=CC=C1'
ketcher.setMolecule(mol)
```

**Comment by zspishere** [comment]
I think it might be a serious bug, and could be found in latest version **ketcher-react@2.4.0**

**Comment by zspishere** [comment]
Besides, if I invoke `ketcher.setMolecule` outside of `onInit`, the bug will remain.
So, I guess the function `ketcher.setMolecule` maybe could not be used in **ketcher-react@2.4.0**.
Is there any workaround to setMolecule in ketcher, and keep the Button `Aromatize` avaliable?
Thanks very much!

**Comment by AndreiMazol** [comment]
Dear @zspishere ,

thank you for your interest to Ketcher.

This issue will be fixed ASAP in scope of hotfix as a part of 2.4.1 release.

Best regards,
Andrei

**Comment by xiaojinchuan** [comment]
@AndreiMazol ，
in addition, the display of hydrogen is abnormal, when a molecule is inited by ketcher.setMolecule.

**Comment by karen-sarkisyan** [comment]
Hi @xiaojinchuan !

Thank you for pointing this out. We'll fix it along with the broken aromatize bug.

**Comment by AndreiMazol** [comment]
Dear @zspishere,

new versions of Ketcher packages have been published.

Please contact us if you find any other issues.

Best regards,
Ketcher team
