### ISSUE TITLE
Exception if insert a molecule past the Ketcher

### ISSUE THREAD

**Issue by EugenReentovich** [epam/ketcher#1175]
**Steps to Reproduce**
1. Copy some molecule into clipboard
2. Open new window with Ketcher
3. Do not move the mouse or place it anywhere other than over the Ketcher
4. Ctrl+V
5. Exception in console

**Expected behavior**
Molecule is inserted into Ketcher.

**Actual behavior**
There is no inserted molecule.
Exception in console.

**Screenshots**
![image](https://user-images.githubusercontent.com/86361520/149144905-d0141e9e-0b54-4c53-8715-19e007c2630c.png)

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit)

**Additional context**
If to click on Ketcher, the bug will not be reproducible, even if move the mouse out. But the focus element is always the same.

**Comment by AndreiMazol** [comment]
Dear @EugenReentovich ,

the issue has been solved in scope of release 2.4.1.

Please contact us if you find any other issue.

Best regards,
Ketcher team
