### ISSUE TITLE
Cannot Install 'ketcher-react' or 'ketcher-standalone' Using NPM

### ISSUE THREAD

**Issue by philc-d** [epam/ketcher#1182]
**Steps to Reproduce**
1. Run 'npm install ketcher-react' or 'npm install ketcher-standalone'
2. The following error is thrown: 
         npm ERR! code EUNSUPPORTEDPROTOCOL
         npm ERR! Unsupported URL Type "workspace:": workspace:*

**Expected behavior**
The packages should install without throwing an error.

**Actual behavior**
The above error message is thrown. (This error message is not thrown when installing previous versions of ketcher packages).

**Additional context**
- npm version: 8.3.0
- node version: 16.13.2

**Comment by AndreiMazol** [comment]
Dear @philc-d ,

thank you for informing us about broken packages. All required changes have been made and new packages versions have been published as a part of hotfix release 2.4.1.

Please contact us if you found any issues.

Best regards,
Ketcher team

**Comment by MariaDolotova** [comment]
Hi @AndreiMazol ! Getting the same issue when trying to install versions 2.7.2 of ketcher-react and ketcher-standalone.
