### ISSUE TITLE
Is there such event monitoring? As long as the structure in the canvas changes, the corresponding event can be triggered

### ISSUE THREAD

**Issue by niuzhenjiang** [epam/ketcher#1209]
Is there such event monitoring? As long as the structure in the canvas changes, the corresponding event can be triggered

**Comment by AndreiMazol** [comment]
Hi @niuzhenjiang ,

this functionality has been already implemented. you can use the following code for example:

`ketcher.editor.subscribe('change', (data) => console.log(data))`

Best regards,
Andrei

**Comment by niuzhenjiang** [comment]
thanks，it worked!
and i want to ask how can i use ketcher in vue? Is there any specific documentation?

**Comment by niuzhenjiang** [comment]
Could you please tell me how to use the VUE platform? Regarding the ketcher-core, is there any sample code or something? Thanks again

**Comment by AndreiMazol** [comment]
Hi @niuzhenjiang ,

this moment ketcher-core is not ready for use in Vue apps. It should be done in scope of the nearest releases. This  moment only injection as IFame is available for non-react projects.

Regards,
Andrei

**Comment by niuzhenjiang** [comment]
@AndreiMazol ok,thanks,I still have a question, how can iframe embedded standalone version of ketcher hide the specified button, thanks again

**Comment by AndreiMazol** [comment]
Hi @niuzhenjiang ,

controls can be hidden in both modes (remote and standalone) by passing 'hiddenControls' query parameter, for example to hide 'open' and 'save' buttons it is necessary to pass the following values:

`http://localhost:5000/?hiddenControls=open,clear`

unfortunately this functionality is not documented so the list of all  available options can be found in https://github.com/epam/ketcher/blob/master/packages/ketcher-react/src/script/ui/action/index.js (look at use of 'isHidden' function)

Regards,
Andrei
