### ISSUE TITLE
Add highlighting API to ketcher-react

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1242]
- An object on `ketcher` instance with ids of highlighted items on the canvas and highlight's color code
- Rendering of highlight on the canvas
- Method to set highlighting by atom and/or bond id with specified color
- Method to clear highlighting

**Comment by Svetlana-Asinovskaia** [comment]
Blank page and errors in console when switching 'Show bonds/atoms Ids' options
<img width="960" alt="2022-02-17_10h17_59" src="https://user-images.githubusercontent.com/80695128/154428110-7123f58d-f11e-4dc1-ba22-b4dae395837c.png">
.
