### ISSUE TITLE
Cannot insert simple object as fragment from .ket

### ISSUE THREAD

**Issue by JerdoAve** [epam/ketcher#125]
**Steps to reproduce:**
1. Create simple object(s)
2. Save as .ket
3. Open .ket as a fragment

**Expected result:**
Simple object(s) is(are) pasted with movement action switched on

**Actual result:**
Error occurred

**Comment by AndreiMazol** [comment]
Dear @JerdoAve ,

Thank you for interest in Ketcher.
This issue will be fixed in  the next release.

Best regards,
Ketcher team
