### ISSUE TITLE
Leakage body CSS style

### ISSUE THREAD

**Issue by dmoskalenko-datagrok** [epam/ketcher#1255]
We use Ketcher-react v2.4.1 in our Datagrok platform.

After opening Ketcher form, the style of the main window has been changing.
 <img src="https://user-images.githubusercontent.com/98885254/153957020-5433c6aa-318f-4094-8607-a743072fc958.png" width="500">

Problem in body CSS
![image](https://user-images.githubusercontent.com/98885254/153956537-21e642c6-eaa0-48f9-81e6-ec432476622f.png)

Is it posiible to avoid modification of the body CSS?

**Comment by AndreiMazol** [comment]
Dear @dmoskalenko-datagrok ,

it will be fixed as a part of release 2.4.2 (in should be done in  two  weeks).

Regards,
Andrei

**Comment by karen-sarkisyan** [comment]
Hi @dmoskalenko-datagrok ,

I'm trying to reproduce your ussue, but I'm going to need a little more information to track it down. A couple of questions:
1. `ketcher-react` package does not have a `ketcher.css` file. Are you sure it's imported from the package and not from somewhere else?
2. Some styles might leak indeed, we'll fix it. Are the ones on your screenshots the only ones you believe are leaking?

Feel free to provide any additional context, that will help. And thank you for using Ketcher!

**Comment by dmoskalenko-datagrok** [comment]
@karen-sarkisyan I after the cleaning folder and getting **ketcher-react** 2.4.2 again problem is solved. 
Perhaps it was the css-style file of the previous version. 
Thank you for your assistance and quick feedback.
