### ISSUE TITLE
Stereomarks and stereoflag are not displayed for templates with stereocenters

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1258]
**Steps to Reproduce**
1. Select any template with stereobonds from the Template library.
2. In the structure select any stereocenter.
3. Click the 'Stereochemistry button'.
4. Select the 'Create new AND group'/'Create new OR Group' option.
5. Close the 'Enhanced Stereochemistry' dialog.

**Expected behavior**
A stereomark '&1'/'or1' is displayed near the selected stereocenter.
'Mixed' stereoflag is shown near the structure.

**Actual behavior**
A stereomark and stereocenter are not displayed.

**Screenshots**
<img width="639" alt="2022-02-15_22h17_14" src="https://user-images.githubusercontent.com/80695128/154133433-3ecbdab5-26b2-4a01-b56c-1f7deba63cd4.png">
![2022-02-15_22h21_06](https://user-images.githubusercontent.com/80695128/154133571-e07f23bd-1de8-438e-a9be-4f9775c7a9fa.gif)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome, Version 98.0.4758.82

 Ketcher version: v2.4.1-99-g81423737

**Comment by akolyakov42** [comment]
Reopened, still **the same** incorrect behavior

**Comment by akolyakov42** [comment]
Reopened, cause the behaviour is the same
