### ISSUE TITLE
On change subscription in Editor

### ISSUE THREAD

**Issue by dmoskalenko-datagrok** [epam/ketcher#1261]
**Ketcher-React** contains member Editor.
According to examples, the **Editor** should support subscribing to events including onChange.
Version 2.4.2 of ketcher-react **Editor** contains only
```
export interface Editor {
    isDitrty: () => boolean;
    setOrigin: () => void;
    struct: (struct?: Struct) => Struct;
}

``` 
Please, let me know how I can subscribe on changing in Editor or it is bug ?

**Comment by AndreiMazol** [comment]
Dear @dmoskalenko-datagrok ,

'Editor' interface will be updated in scope of 2.4.2. 
Right now to  skip TS errors you  can cast ketcher.editor instance to any before adding subscription:

`(ketcher.editor as any).subscribe('change', () => console.log('test message'))`

Regards,
Andrei

**Comment by dmoskalenko-datagrok** [comment]
@AndreiMazol, Thank you, it works
