### ISSUE TITLE
Undo doesn't work for simple objects

### ISSUE THREAD

**Issue by JerdoAve** [epam/ketcher#129]
**Steps to reproduce**
1. Create several simple objects
2. Press Ctrl-Z (Cmd-Z) or 'Undo' button on the top toolbar

**Expected result**
The last created object is disappeared 

**Actual result**
Nothing happens

**Comment by AndreiMazol** [comment]
Dear @JerdoAve ,

thank for posting a new issue. 
It will be fixed in the nearest release.

Best regards,
Ketcher team
