### ISSUE TITLE
Structure check modal window causes error when closed right after update

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1291]
**Bug appears almost randomly on the same preconditions. Try to reproduce it more than once.**

**Steps to Reproduce**
1. Click "Structure Check" button
2. Remove two random checkboxes
3. Close "Structure check" modal window
4. See error or try again with different checkboxes

**Expected behavior**
Structure check state changed.

**Actual behavior**
Error message is shown in a bit after closing modal window.

**Screenshots**
![Screenshot 2022-02-25 at 19 29 07](https://user-images.githubusercontent.com/97884482/155751318-89bca1d5-8874-4687-ac2b-0a8593376876.png)

https://user-images.githubusercontent.com/97884482/155752265-58cccd21-5783-4022-8484-03a842f0a8d4.mp4

**Desktop:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/98.0.4758.109 Safari/537.36

**Comment by karen-sarkisyan** [comment]
Update after analysis:
Error is thrown when Check structure modal is closed **before** response from server was received.

To get consistent error reproduction, open Check structure and press `Esc` key right after modal appears, or right after click on any checkbox.
