### ISSUE TITLE
Sending structure to renderer in molfile format instead of ketcher format

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1300]
**Steps to Reproduce**
1. Launch Ketcher
2. Launch DevTools and switch to Network tab
3. Create or load structure to canvas
4. Launch "Copy as image" function (press hotkey or click "Copy as Image" button in "Copy..." dropdown)
5. Click on "render" request in Network tab and switch to Payload tab
6. Check "struct" string 

**Expected behavior**
Client sends structure in ketcher format

**Actual behavior**
Client sends structure in molfile format

**Screenshots**
<img width="627" alt="Screenshot 2022-03-02 at 17 13 58" src="https://user-images.githubusercontent.com/97884482/156378513-242a5aa0-5a0d-4159-a0a5-df5198afffe7.png">

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/98.0.4758.109 
Safari/537.36

**Comment by karen-sarkisyan** [comment]
2 tasks should be perform:
- [ ] Switch to ket serializer
- [ ] Refactor code responsible for copying structure as image
