### ISSUE TITLE
Incorrect vertical scrollbar when saving in Daylight SMILES format

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1307]
**Steps to Reproduce**
1. Launch Ketcher
2. Load structure or create structure on canvas
3. Press "Save" button in upper toolbar
4. Switch to Daylight SMILES format of file
5. See error

**Expected behavior**
Daylight SMILES string is in textarea, no scrollbars, cause this is one string with no carriage returns.

**Actual behavior**
Scrollbar in textarea with Daylight SMILES string

**Screenshots**
<img width="634" alt="Screenshot 2022-03-03 at 23 29 54" src="https://user-images.githubusercontent.com/97884482/156647688-86455ec9-c255-42eb-9de2-a9967337a8f8.png">

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/98.0.4758.109 
Safari/537.36

**Comment by Mariia-Katkova** [comment]
Cannot reproduce
