### ISSUE TITLE
Top panel changes - icons update and Zoom controls changes

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1309]
Change the icons used for the top Kether panel & Rework zoom control on the top panel to support better user experience:

1. Change icons and update the order for the following operations: Save, Open, Copy (there is no icon right now for the actions in drop down Copy as, use the old ones), Paste, separator, Undo, Redo, separator

![image](https://user-images.githubusercontent.com/90251323/156731528-831ff668-3602-4463-a553-20f37323900d.png)

2. Change the zoom controls on the top panel:
2.1 Use slider with Plus and Minus controls to provide ability to change canvas scale. Clicking on Plus and Minus should give +10% or -10% of the scale and slider indicator should be moved accordingly. 
Indicator on slider should be moving with 10% increment when it's moved manually by mouse. Clicking on the Plus, Minus or manual moving of the indicator should change the value presented in the zoom scale drop-down (2.2):
![image](https://user-images.githubusercontent.com/90251323/156731423-5d099134-6532-4fca-94c1-b6c2a132e407.png)

2.2. Update the drop-down control for the Zoom scale selection. The list of possible values should be the same. Changing the drop down value should change the location of indicator on the slider. 
![image](https://user-images.githubusercontent.com/90251323/156731610-3b6e1be5-7637-4833-ba5a-dcdde901c1c3.png)

--------Updates for March, 15th:
1. Add Clear canvas operation on the far left of the panel, use icon: 
![image](https://user-images.githubusercontent.com/90251323/158345267-3f766e2f-8380-48ec-8ffc-c4f06e2052d9.png)

2. Move all zoom elements to the right up to the service icons. 
3. Add new panel with server operations between Redo and Zoom: 7 server operations should be presented (use new icon when possible):
Layout, Clean Up, Aromatize (old icon), Dearomatize (old icon), Calculate CIP, Check Structure, Calculate Values. 
The panel should turn to the drop-down list if is not fit to the panel fully on the low size of Ketcher with Layout operations to be on the head of drop down.

**Comment by karen-sarkisyan** [comment]
Upd: We need to get updated icons for About button and clarify the look of 3d viewer switch.
