### ISSUE TITLE
Elements panel & Periodic table redesign

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1315]
Please, implement changes for the quick periodic elements panel & periodic table floating window:

Change design for the panel with default elements (same list as today) and ability to open the full periodic table. Panel should be aligned on the right part of the canvas and placed vertically. The low part of the panel should provide ability to open Periodic Table floating window. Right now it should contain 2 tabs - Periodic Table (should be 1st and opened by default) and Extended table. 
![image](https://user-images.githubusercontent.com/90251323/157402787-59298089-1dd7-4ae5-8441-b4e6c46e24c6.png)

Linked issue: https://github.com/epam/ketcher/issues/1340

**Comment by Svetlana-Asinovskaia** [comment]
Elements panel mockup in the task is obsolete. Implemented according to the redesign.  
<img width="28" alt="2022-04-18_22h08_29" src="https://user-images.githubusercontent.com/80695128/163862036-d8f81cad-5e12-4897-a3d5-f866b55906d3.png">
discussed with @Alena-Guznischeva
"Panel should be aligned on the right part of the canvas" will be implemented in https://github.com/epam/ketcher/issues/1340.
