### ISSUE TITLE
In the standalone mode, after packaging, chunks.js is placed in the static / JS folder JS file is a little large

### ISSUE THREAD

**Issue by newbtn** [epam/ketcher#1319]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreiMazol** [comment]
Dear @newbtn ,

please look  at the following discussion https://github.com/epam/ketcher/discussions/1248 that explains the reason of it.

Regards,
Andrei

**Comment by newbtn** [comment]
ok, thx u
