### ISSUE TITLE
Via ketcher The size of mol displayed in the editor is inconsistent between calling ketcher.setMolecule(）and direct copy and paste

### ISSUE THREAD

**Issue by newbtn** [epam/ketcher#1322]
**Steps to Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Ketcher version** [e.g. v2.4.2-115-gcf0c1394]. 
To determine it, hover over the header of the Ketcher tab in a browser. 

**Additional context**

**Comment by Svetlana-Asinovskaia** [comment]
Hi @newbtn, 
thanks for your interest in Ketcher. Could you provide more details about your case, e.g. screenshots of the created structures and preferably steps to reproduce the issue?

Best regards,
Sveta

**Comment by AndreiMazol** [comment]
Cannot reproduce.

**Comment by fedorseliankin** [comment]
Verified in Release 2.5
