### ISSUE TITLE
Exception when drawing reaction arrow after setting ketcher.editor.subscribe('change', (data) => console.log(data));

### ISSUE THREAD

**Issue by graphite-diamond** [epam/ketcher#1326]
**Steps to Reproduce**
1. Use ketcher v2.4.2 standalone/index.html
2. Execute ketcher.editor.subscribe('change', (data) => console.log(data));
3. Click on the reaction arrow button
<img width="347" alt="image" src="https://user-images.githubusercontent.com/101608359/158283585-980e9b79-5c55-4bf5-8d7d-76dd1a0d9a95.png">

4. Single left click on the ketcher canvas (exceptions thrown, see actual behavior below)

5. Reload page, click on reaction arrow button (step 3)

6. Hold left click on ketcher canvas, move mouse to right, release click (exceptions thrown, see actual behavior below)

**Expected behavior**
After steps 4 or 6 above, the reaction arrow should appear in the sketcher, which otherwise happens successfully when NOT subscribing the ketcher editor (NOT executing step 2, above).

The change data should appear in the console, which otherwise happens successfully when drawing atoms/bonds WITHOUT a reaction arrow.

**Actual behavior**
The reaction arrow does not appear in the sketcher, the sketcher remains blank.

**After step 4 in steps to reproduce (above), an exception is thrown:**
customOnChangeHandler.ts:126 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')
    at customOnChangeHandler.ts:126:31
    at Array.forEach (<anonymous>)
    at customOnChangeHandler.ts:40:31
    at B (Editor.ts:406:11)
    at r.dispatch (index.js:51:19)
    at U.value (Editor.ts:339:27)
    at mW.click (reactionarrow.js:129:17)
    at n.f (Editor.ts:546:20)
    at s.dispatch (index.js:93:21)
    
**After step 6 in steps to reproduce, exceptions are thrown:**
customOnChangeHandler.ts:126 Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')
    at customOnChangeHandler.ts:126:31
    at Array.forEach (<anonymous>)
    at customOnChangeHandler.ts:40:31
    at B (Editor.ts:406:11)
    at r.dispatch (index.js:51:19)
    at U.value (Editor.ts:339:27)
    at mW.mouseup (reactionarrow.js:118:17)
    at n.f (Editor.ts:546:20)
    at s.dispatch (index.js:93:21)
(anonymous) @ customOnChangeHandler.ts:126
(anonymous) @ customOnChangeHandler.ts:40
B @ Editor.ts:406
r.dispatch @ index.js:51
value @ Editor.ts:339
mW.mouseup @ reactionarrow.js:118
(anonymous) @ Editor.ts:546
s.dispatch @ index.js:93
RxnArrowResize.ts:76 Uncaught TypeError: Cannot read properties of undefined (reading 'pos')
    at Q.value (RxnArrowResize.ts:76:17)
    at Q.value (base.ts:41:10)
    at action.ts:49:43
    at Array.forEach (<anonymous>)
    at U.value (action.ts:48:22)
    at gJ (reaction.ts:36:17)
    at mW.mousemove (reactionarrow.js:91:29)
    at n.f (Editor.ts:546:20)
    at s.dispatch (index.js:93:21)
value @ RxnArrowResize.ts:76
value @ base.ts:41
(anonymous) @ action.ts:49
value @ action.ts:48
gJ @ reaction.ts:36
mW.mousemove @ reactionarrow.js:91
(anonymous) @ Editor.ts:546
s.dispatch @ index.js:93
435index.ts:91 Uncaught TypeError: Cannot read properties of undefined (reading 'pos')
    at Q.value (index.ts:91:26)
    at Q.value (base.ts:41:10)
    at action.ts:49:43
    at Array.forEach (<anonymous>)
    at U.value (action.ts:48:22)
    at mW.mousemove (reactionarrow.js:88:29)
    at n.f (Editor.ts:546:20)
    at s.dispatch (index.js:93:21)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser [chrome or edge]
 - Version [chrome 99.0.4844.51, edge 98.0.1108.43]

**Ketcher version** [v2.4.2]. 
Ketcher standalone v2.4.2, downloaded from https://github.com/epam/ketcher/releases/download/v2.4.2/ketcher-standalone-2.4.2.zip

**Comment by AndreiMazol** [comment]
Dear @graphite-diamond ,

thank you for your help in making Ketcher better.

The issue will be fixed on scope of the nearest release (2.5).

Best regards,
Andrei
