### ISSUE TITLE
Inconsistent "Copy as..." icons

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1348]
**Ketcher v2.4.2-132-gb2ba8289**

**Steps to Reproduce**
1. Launch Ketcher
2. Click on dropdown of "Copy as..." menu in upper toolbar
3. Overview icons: 
3.1. Copy as .mol
3.2. Copy as .ket
3.3. Copy as image

**Expected behavior**
Icons in dropdown match style of other icons in upper toolbar

**Actual behavior**
Icons in dropdown do not match style of other icons in upper toolbar

**Screenshots**
<img width="89" alt="Screenshot 2022-03-23 at 14 21 31" src="https://user-images.githubusercontent.com/97884482/159688358-ab5b5da3-8c59-444d-a6c0-714f5b49982f.png">

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/99.0.4844.74 
Safari/537.36

**Ketcher version** 
v2.4.2-132-gb2ba8289

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
