### ISSUE TITLE
Floating windows - add Cancel/Close button to the redesigned windows

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1353]
Add Cancel/Close button the floating windows that were redesigned. 

For the windows that allow to change something button Cancel should be added. Cancel button should be displayed on the right of the Save/Apply buttons in the form. 

1. OPEN STRUCTURE _(form with the text and ADD TO CANVAS button)_
2. Periodic Table
3. Stereochemistry
4. Atom Properties
5. Bond Properties
6. S-Group
7. Data S-Group
8. R-Group tool
9. R-Group Fragment tool
10. Attachment Points tool
11. Text Editor window
12. Settings
13. Structure Check: add Cancel and also Save (was missed during redesign). Save button should save structure check settings to the local settings and they should be used when Saving to the file operation is initiated to limit the warnings set checked and displayed. 

Example: 

![image](https://user-images.githubusercontent.com/90251323/159948896-9a3750ac-6cde-4701-a485-2abfa4404cb4.png)

For the windows that allow just View the content button Close should be added to the below right corner:
1. Calculated Values
2. About

Pay attention to the Recognize window - it's in work now.

**Comment by fedorseliankin** [comment]
Regression re-check, in build 2.5 - OK
