### ISSUE TITLE
Structure Check window - add placeholder & block checkboxes while waiting for server reply

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1356]
Improve the work of the Structure Check operation: 
As Ketcher User I want to Check Structure on the canvas to find the non-valid properties of the canvas content in several groups of properties SO THAT I can understand if the structure is valid and applicable for saving in the standard formats

AC 1: GIVEN Ketcher User WHEN clicking on the Check Structure operation command in the main Ketcher menu THEN Ketcher displays Check Structure window AND  immediately checks structure using the check settings saved AND displays 3 dots standard placeholder while the check structure operation is ongoing AND blocks the ability to change check settings and save the changes by clicking on Apply and request one more check by clicking on Check

AC 2: GIVEN Ketcher User WHEN check structure operation was initiated AND the response with operation results was received THEN Ketcher displays list of warnings received with the date and time of operation results receiving and provides the ability to change check settings by enabling or disabling the warning groups AND save the check settings by clicking on the Apply AND check the structure one more time by clicking on the Check

AC 3: GIVEN Ketcher User WHEN check settings were changed comparing to the previous state THEN Ketcher highlights the Check button with the main color 

AC 4: GIVEN Ketcher User WHEN clicking on the Check THEN Ketcher sends request to check structure AND displayes 3 dots placeholder and blocks the buttons just like it's done when the Check Structure window is opened with the initial check

AC 5: GIVEN Ketcher User WHEN clicking on the Apply THEN Ketcher closes the window AND saves check settings AND uses them for the next Check Structure operation initiation AND uses them for the checks when file is saved 

Use the following designs:
![image](https://user-images.githubusercontent.com/90251323/160807678-0b1077c5-4e2c-4730-ad53-e791bd49491f.png)

**Comment by ZhannaNovikova** [comment]
Doesn't fit the requirements, should be reopened:
- Incorrect the message: "No errors detected" positioning in the "Structure Check" window;

![image](https://user-images.githubusercontent.com/103422815/163799409-81049159-aba0-4672-85cc-5222b0d3600f.png)
![image](https://user-images.githubusercontent.com/103422815/163799457-7bbadf18-5ff0-4785-a9c7-5cc2b78e3212.png)

- Incorrect warnings list when only the "Valence" setting has been checked

![image](https://user-images.githubusercontent.com/103422815/163799531-8c0b1873-cec9-434c-a988-654f62939fd2.png)

- Incorrect warnings list when all setting has been unchecked

![image](https://user-images.githubusercontent.com/103422815/163799589-356c622b-0dce-441e-8f2a-d97c9619ab42.png)

**Comment by AnaMoskvina** [comment]
Logical issues to be investigated and fixed later (behavior is the same as in demo, most likely - external issue)

**Comment by ZhannaNovikova** [comment]
Verified in Release 2.5.0
