### ISSUE TITLE
Generated SMILES is incorrect

### ISSUE THREAD

**Issue by amalik01** [epam/ketcher#1360]
Hi,

ChEBI uses Ketcher for drawing chemical structures. One of our users has recently reported an issue with Ketcher in the way it generates SMILES for certain compounds (see https://github.com/ebi-chebi/ChEBI/issues/4109). Can this be fixed? Thanks

**Comment by AndreiMazol** [comment]
Dear @amalik01,

In order to proceed with your issue could you provide additional information:

1. steps to reproduce 
2. version of Ketcher you use
3. provide original mol file from the end user

Regards,
Ketcher team

**Comment by amalik01** [comment]
Ketcher version 1.1-beta

Here is the mol file:

ACD/Labs03252216163D
 32 36  0  0  1  0  0  0  0  0  2 V2000
   11.6797   -7.9720    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.6797   -9.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.5278   -7.3070    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.5278   -9.9670    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.3760   -7.9720    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.3760   -9.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1111   -7.5610    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.3294   -8.6370    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1110   -9.7130    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.8315   -7.3070    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
   12.8315   -9.9670    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.9833   -9.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.1224   -7.9793    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.1984   -9.8430    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.4233   -7.7028    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.0884   -8.8545    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.4111   -8.9935    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.4749  -11.1440    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.7398  -11.5550    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.7282  -10.6651    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.0163  -12.8560    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.9931  -11.0762    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.2812  -13.2670    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.2696  -12.3771    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.1449  -10.4113    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   21.1332  -11.3012    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.5924  -12.5161    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.0279  -13.7459    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
   14.7630  -13.3349    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.3044  -15.0469    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
   12.8026   -5.9773    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.2134   -6.9224    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  2  0  0  0  0
  2  4  2  0  0  0  0
  3  5  1  0  0  0  0
  4  6  1  0  0  0  0
  5  6  2  0  0  0  0
  5  7  1  0  0  0  0
  7  8  1  0  0  0  0
  6  9  1  0  0  0  0
  8  9  1  0  0  0  0
  1 10  1  0  0  0  0
  2 11  1  0  0  0  0
 12 11  1  6  0  0  0
 12 13  1  0  0  0  0
 12 14  1  0  0  0  0
 13 15  1  0  0  0  0
 14 16  1  0  0  0  0
 15 16  1  0  0  0  0
 16 17  2  0  0  0  0
 14 18  1  1  0  0  0
 18 19  1  0  0  0  0
 19 20  1  0  0  0  0
 19 21  2  0  0  0  0
 20 22  2  0  0  0  0
 21 23  1  0  0  0  0
 23 24  2  0  0  0  0
 22 25  1  0  0  0  0
 22 24  1  0  0  0  0
 25 26  1  0  0  0  0
 24 27  1  0  0  0  0
 26 27  1  0  0  0  0
 21 28  1  0  0  0  0
 28 29  2  0  0  0  0
 28 30  1  0  0  0  0
 10 31  2  0  0  0  0
 10 32  1  0  0  0  0
M  CHG  4  10   1  28   1  30  -1  32  -1
M  END

Try generating the Daylight SMILES  for the above mol file in ketcher. It seems to be missing the Hydrogens.

![image](https://user-images.githubusercontent.com/41328040/160359995-83589415-04a9-4f11-85c4-41d254a2b9d3.png)

**Comment by Alena-Guznischeva** [comment]
HI @amalik01 , 

Unfortunately we can't open the Mol file you've provided (even using the Ketcher 1.1. on the ChEBI). We receive the error about Molfile version 0.0.0. Could you, please, try to save and provide mol one more time? 
Thank you.

**Comment by amalik01** [comment]
please try this (you may need to leave a blank space at the top):

ACD/Labs03252216163D
 32 36  0  0  1  0  0  0  0  0  2 V2000
   11.6797   -7.9720    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.6797   -9.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.5278   -7.3070    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.5278   -9.9670    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.3760   -7.9720    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.3760   -9.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1111   -7.5610    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.3294   -8.6370    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1110   -9.7130    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   12.8315   -7.3070    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
   12.8315   -9.9670    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.9833   -9.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.1224   -7.9793    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.1984   -9.8430    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.4233   -7.7028    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.0884   -8.8545    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.4111   -8.9935    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.4749  -11.1440    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.7398  -11.5550    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.7282  -10.6651    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.0163  -12.8560    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.9931  -11.0762    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.2812  -13.2670    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.2696  -12.3771    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.1449  -10.4113    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   21.1332  -11.3012    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.5924  -12.5161    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.0279  -13.7459    0.0000 N   0  3  0  0  0  0  0  0  0  0  0  0
   14.7630  -13.3349    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.3044  -15.0469    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
   12.8026   -5.9773    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   14.2134   -6.9224    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  2  0  0  0  0
  2  4  2  0  0  0  0
  3  5  1  0  0  0  0
  4  6  1  0  0  0  0
  5  6  2  0  0  0  0
  5  7  1  0  0  0  0
  7  8  1  0  0  0  0
  6  9  1  0  0  0  0
  8  9  1  0  0  0  0
  1 10  1  0  0  0  0
  2 11  1  0  0  0  0
 12 11  1  6  0  0  0
 12 13  1  0  0  0  0
 12 14  1  0  0  0  0
 13 15  1  0  0  0  0
 14 16  1  0  0  0  0
 15 16  1  0  0  0  0
 16 17  2  0  0  0  0
 14 18  1  1  0  0  0
 18 19  1  0  0  0  0
 19 20  1  0  0  0  0
 19 21  2  0  0  0  0
 20 22  2  0  0  0  0
 21 23  1  0  0  0  0
 23 24  2  0  0  0  0
 22 25  1  0  0  0  0
 22 24  1  0  0  0  0
 25 26  1  0  0  0  0
 24 27  1  0  0  0  0
 26 27  1  0  0  0  0
 21 28  1  0  0  0  0
 28 29  2  0  0  0  0
 28 30  1  0  0  0  0
 10 31  2  0  0  0  0
 10 32  1  0  0  0  0
M  CHG  4  10   1  28   1  30  -1  32  -1
M  END

**Comment by amalik01** [comment]
[structure.zip](https://github.com/epam/ketcher/files/8361233/structure.zip)

**Comment by Alena-Guznischeva** [comment]
Hi @amalik01 , 

Thank you for providing the details. 
This issue is not reproduced in the latest version of Ketcher, it was fixed quite a time ago. In the 2.4 version of Ketcher the SMILES produced does not add radicals to the structure. 
Our suggestion would be to update your version of Ketcher to latest one to have this problem fixed.  The 2.4 demo version is available for you to explore it's abilities here: [Ketcher Demo](https://lifescience.opensource.epam.com/ketcher/demo.html)

2.4.2 Release resides here: [Ketcher 2.4.2](https://github.com/epam/ketcher/releases/tag/v2.4.2). 
You can refer to Discussion for the information on the deployment. 

Please, note that Ketcher now has 2 builds provided - **Standalone** and **Remote**. The difference would be in the need of having separate [Indigo server](https://github.com/epam/Indigo) deployed for some functions to work in Remote version. Standalone version has those functions packed together with Ketcher code. Please, note that Ketcher Remote 2.4.2 will need at least [Indigo 1.6](https://github.com/epam/Indigo/releases/tag/indigo-1.6.1) to be used with it, it will not work correctly with lower version. 
From user's perspective the only functional difference between Standalone and Remote will be function Recognize (turning picture to the molecule on the canvas): it is not supported in the Standalone version, but is supported in the Remote one. If you don't need it - Standalone build will be sufficient for your needs. 

We realize that Ketcher API from 2.4.2 will be dramatically different from the one you are using right now with 1.1.
We are planning to provide API description for the upcoming Ketcher version in April. Also, please, let us know if some specific questions will appear on the API and Ketcher functions.

**Comment by amalik01** [comment]
@Alena-Guznischeva Thanks for the info. Hopefully we will update to the latest ketcher version in the near future.

**Comment by AndreiMazol** [comment]
The issue has been closed as fixed in previous releases.
