### ISSUE TITLE
No waiting for server to respond between Structure Check checkboxes turning on/off

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1367]
**Steps to Reproduce**
1. Open Network tab of browser DevTools.
2. Set Throttling to 'Slow 3G'
3. Launch Ketcher Remote
4. Open Structure check window
5. Turn off several checkboxes 
6. Overview Network tab

**Expected behavior**
Application waits (e.g. some kind of loading animation or spinner appears) for server to respond the query and then turns checkbox on/off.

**Actual behavior**
Checkbox is turned on/off before server responds the query. 
It may cause errors in queries processing flow.

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/98.0.4758.109
Safari/537.36

**Ketcher version**
v2.4.2-137-g9fc6db1d

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
