### ISSUE TITLE
Loosing Structure Check state on reopening SC window or saving structure

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1368]
**Steps to Reproduce**
1. Launch Ketcher
2. Load or create structure with R-Groups on canvas
3. Open Structure Check window (Upper Toolbar)
4. See R-Groups warning in SC window
5. Turn off R-Groups warning checkbox
6. Reopen SC window or open Save As window

**Expected behavior**
R-Groups warnings are presented no more cause R-Groups warning is unchecked in SC window.

**Actual behavior**
R-Groups warnings are presented in SC window or in Save As window

**Screencast**
https://user-images.githubusercontent.com/97884482/160436458-21619c2d-237b-4eab-a72b-19518cd8974d.mov

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/98.0.4758.109
Safari/537.36

**Ketcher version**
v2.4.2-137-g9fc6db1d

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
R-Groups warnings are presented no more when R-Groups warning is unchecked in SC window.

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
