### ISSUE TITLE
Save Window redesign - iteration #2

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1376]
Apply new visual representation for the Save As modal window:

1. Use new colors and organize window to have header, content, bottom. 
2. File format drop down should contain 3 zones: saving to text formats that can be opened again, exporting to the number formats (InCH Key only?), export to pictures.
3. If there are warnings when saving the file then the second tab Warnings should appear. When clicking on it the list of warnings should be displayed with ability to copy the list and grouping just like today. 
4. There should be buttons Saved to Templates (opening Template Edit window), Cancel, Save, closing icon. Cancel and closing icon should work in the same way - closing the window without creating the file. 
5. Default values for the name and format should stay as they are now (ketcher, Mol V2000)
6. Warning should be represented in a separate tab from the Preview. Warnings tab should be available only if the warnings exist. 

Update from Alena, Apr, 13th: 
7. When selecting the SVG, PNG format the preview of the picture saved should be displayed. The preview generation should be initiated when the format is changed to the image one. 
8. Use the standard 3 dots placeholder for the server functions results waiting time. Display the placeholder on the Preview tab while the function. 
9. If the format was changed when Warnings tab was selected - it should be changed to Preview tab selected, placeholder should be displayed while waiting for text or image preview to be generated. 

Use the following designs:

![image](https://user-images.githubusercontent.com/90251323/161785108-91d5802a-6de4-4927-9347-8048769b7b9c.png)
![image](https://user-images.githubusercontent.com/90251323/161785166-d7a23e85-13e4-4f17-ad2a-a1eac329095c.png)
![image](https://user-images.githubusercontent.com/90251323/161785320-e68483f5-d6ff-4edb-8509-ed7e5d27afe0.png)
![image](https://user-images.githubusercontent.com/90251323/160588089-0919c796-1990-4eff-9be7-8bff107de878.png)

**Comment by Alena-Guznischeva** [comment]
Update from Alena, Apr, 13th: 
7. When selecting the SVG, PNG format the preview of the picture saved should be displayed. The preview generation should be initiated when the format is changed to the image one. 
8. Use the standard 3 dots placeholder for the server functions results waiting time. Display the placeholder on the Preview tab while the function. 
9. If the format was changed when Warnings tab was selected - it should be changed to Preview tab selected, placeholder should be displayed while waiting for text or image preview to be generated.

**Comment by ZhannaNovikova** [comment]
Doesn't fit the requirements, should be reopened:
- the selected file format in the Save Structure window doesn't match the mockup; 
- the text of the Warning tab in the Save Structure window doesn't match the mockup;
- the File format drop down in the Save dialog doesn't match the mockup.

**Comment by ZhannaNovikova** [comment]
Verified in Release 2.5
