### ISSUE TITLE
Incorrect behavior of Zoom Menu percentage field

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1378]
**Steps to Reproduce**
1. Launch Ketcher
2. Click on Zoom Menu dropdown
3. Remove data from Zoom Menu percentage field
4. Press Enter

**Expected behavior**
2. Focused on Zoom Menu percentage field
4. Data in percentage field is restored

**Actual behavior**
2. No focus on Zoom Menu percentage field
3. No ability to remove data from Zoom Menu percentage field (0 appears if data removed)
4.1. 20% appears in Zoom Menu
4.2. Canvas zoomed in

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/98.0.4758.109
Safari/537.36

**Ketcher version**  
v2.4.2-143-ge659ce4b

**Comment by akolyakov42** [comment]
IF Zoom Percentage field is selected (AND zoom percentage is changed) AND Esc button is pressed
THEN Zoom Dropdown should be closed (AND zoom percentage should be restored)

**Comment by ViktorMakarov-EPAM** [comment]
Checked. Bug hasn't reproduced

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
