### ISSUE TITLE
Periodic Table UI is broken in Safari

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1390]
**Steps to Reproduce**
1. Launch Ketcher
2. Click on Periodic Table button in Right Sidebar
3. See error

**Expected behavior**
Periodic table is usable and accords to mockup

**Actual behavior**
Periodic table layout is completely broken

**Screenshots**
<img width="757" alt="Screenshot 2022-04-01 at 11 27 44" src="https://user-images.githubusercontent.com/97884482/161228938-038a004f-2d82-4bd2-9177-1ddd1189eea7.png">

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/98.0.4758.109
Safari/537.36

**Ketcher version** 
v2.4.2-150-g311ed61a

**Comment by 05Pixel** [comment]
Safari. Версия 14.1 (16611.1.21.161.6)  - **Everything fine**
Chrome. Версия 99.0.4844.51 (Официальная сборка), (x86_64) - **Everything fine**

**Comment by AndreiMazol** [comment]
cannot reprouduce

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
