### ISSUE TITLE
Cannot deserialize input JSON if using Clean Up functionality on structure containing R-Groups

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1391]
**Steps to Reproduce**
1. Launch Ketcher
2. Add structure containing R-Groups on canvas
3. Clean Up canvas using button in Upper Toolbar

**Expected behavior**
Canvas Cleaned Up without any troubles

**Actual behavior**
'Error: Cannot deserialize input JSON.' error message appeared

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/99.0.4844.84 
Safari/537.36

**Ketcher version**
v2.4.2-150-g311ed61a

**Additional context**
Reproduced in Standalone and Remote modes

**Comment by akolyakov42** [comment]
**Attached issued in Indigo repository**
epam/indigo#699

**Comment by AndreiMazol** [comment]
There is no workaround on client side, the issue should be fixed on BE ('location' property is lost after 'clean up' function execution). Moved to milestone 'Release 2.6'

**Comment by fedorseliankin** [comment]
Verified in Release 2.5

**Comment by fedorseliankin** [comment]
Checked in build 227

**Comment by fedorseliankin** [comment]
Regression re-check, in build 2.5 - OK
