### ISSUE TITLE
Floating windows - S-Group windows redesign iteration #2

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1396]
Update the design of the 2 S-Group Properties windows (S-Group Tool, S-Group Properties Tool). 
Use the designs below. The changes should be the following:

1. Change color scheme & look and feel
2. Add Cancel button to forms
3. Change order of the Context & Field Name for the S-Group Propertries tool form. 
4. Validation and Default values should stay the same. 
![image](https://user-images.githubusercontent.com/90251323/161521957-58253d96-8ebf-4380-bf15-c8508da99e82.png)
![image](https://user-images.githubusercontent.com/90251323/161521905-6af71dbf-4baf-457e-9fc7-27002c5e64d6.png)
![image](https://user-images.githubusercontent.com/90251323/161521996-6fbd52de-672a-429e-9d2c-418f468ff18e.png)
![image](https://user-images.githubusercontent.com/90251323/161522021-a2dac62d-9467-437d-bc08-0b796c152bb9.png)
![image](https://user-images.githubusercontent.com/90251323/161522058-aea99c72-3e51-45e8-9593-6709c6fd798e.png)

**Comment by ZhannaNovikova** [comment]
Doesn't fit the requirements, should be reopened:

- Overlaping the text of the "Field name" on the arrow button to open the "Field name" drop down after selecting the MDLBG_FRAGMENT_COEFFICIENT field name;
- Incorrect radio buttons clickable area;
- Horisontal scroll when the "Field value" winwow is extended.

**Comment by fedorseliankin** [comment]
Regression re-check, in build 2.5 - OK

**Comment by fedorseliankin** [comment]
Regression re-check, in build 2.5 - OK
