### ISSUE TITLE
Incorrect Indigo Functions block hiding behaviour

### ISSUE THREAD

**Issue by akolyakov42** [epam/ketcher#1397]
**Steps to Reproduce**
1. Launch Ketcher in window with width more than 915px
2. Overview Indigo Functions block in Upper Toolbar
3. Change window width to less than 915px
4. See defect

**Expected behavior**
Indigo Functions block is hidden when Upper Toolbar is fully filled with buttons

**Actual behavior**
Indigo Functions block is hidden, when there is a huge gap between it and right-aligned block of Upper Toolbar

**Screencast**
https://user-images.githubusercontent.com/97884482/161564575-f34e0db6-305d-489c-9907-d54d3a65b31b.mov

**User agent**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/100.0.4896.60 
Safari/537.36

**Ketcher version**  
v2.4.2-150-g311ed61a

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
