### ISSUE TITLE
Floating windows - Text tool window redesign

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1401]
Implement the new design for the window of the Text Tool:

1. Change the color scheme of the form
2. Change the icons on the top and their order. The order should be Bold, Italic, Substript, Superscript, Symbols, Font Size. Change the tooltips for the buttons on the top panel - right now they start with lowercase letter. 
3. Change the drop down for the Font Size - should be standard one with the scroll. 
4. Change the view of the Symbols drop down - they should fit in like in design
5. Buttons below: add Cancel button, change OK label to Apply

View the designs: 

![image](https://user-images.githubusercontent.com/90251323/161963522-5a4d85c6-3770-491a-962c-140545ac75d8.png)
![image](https://user-images.githubusercontent.com/90251323/163352063-bd0e4ccc-3db2-4d7a-aae4-d220bd349746.png)

**Comment by ZhannaNovikova** [comment]
Doesn't fit the requirements:

- The format icons (The B/I/ X2 / X2) don't much the mockup;
- The arrow to open the Font Size drop down doesn't much the mockup;
- The Symbols don't much the mockup

The Issues related to the Text tool will be fixed in #1515
