### ISSUE TITLE
Extended table - Add button is unavailable even with the item selected

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1408]
**Steps to Reproduce**
1. Go to Ketcher, version [Version 2.4.2] Build at 2022-04-06; 07:36:44
2. Click on PT icon, navigate to the Extended Table tab
3. Select any item
4. Try clicking on the Add button

**Expected behavior**
Add button is available and can be clicked

**Actual behavior**
Add button is not available

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/90251323/162173129-a76a6112-dec4-40b1-9ee0-516599021c83.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.75 (Official Build) (64-bit)

Ketcher version [Version 2.4.2] Build at 2022-04-06; 07:36:44

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0. 
The Add button is available and can be clicked when an item is selected on the Extended Table tab.

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
