### ISSUE TITLE
It's possible to remove a value from the Chemical Formula field using the Delete button/Ctrl+X hotkey

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1417]
**Steps to Reproduce**
1. Create a structure on the canvas (e.g. chain);
2. Click the 'Calculated Values' button;
3. Select the value in the 'Chemical Formula' field;
4. Press the 'Delete' button (or press Ctrl+X hotkey).

**Expected behavior**
The 'Chemical Formula' field remains without changes.

**Actual behavior**
The value in the 'Chemical Formula' field is deleted.

**Screenshots**

https://user-images.githubusercontent.com/80695128/162820382-60526282-099d-42ae-822d-5396765dc704.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome
 - Version 100.0.4896.75

**Ketcher version** 
v2.4.2-157-ge13ae6cb

**Comment by Svetlana-Asinovskaia** [comment]
Verified in Release/2.5.0

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
