### ISSUE TITLE
Floating windows - Change design for Label Edit form

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1424]
Change the design of the Label Edit form. 
The changes should be the following:
1. Use color scheme, header, buttons & other components from the ones used in other forms
2. Apply the alignment & pixel amount rules for the components on the form using the rules for the standard forms. 
3. Change the button OK label to Apply
4. Validation and logic should stay the same. 

Old form: 
<img width="129" alt="image" src="https://user-images.githubusercontent.com/90251323/162981303-f77e3397-3b9b-43de-9e7c-08917f65d6f0.png">

**Comment by Mariia-Katkova** [comment]
Verified in Release 2.5
