### ISSUE TITLE
'Stereochemistry' icon doesn't match the mockup

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1425]
**Steps to Reproduce**
1. Launch Ketcher.
2. Check the 'Stereochemistry' icon on the right side toolbar.

**Expected behavior**
The icon matches the mockup.
![image](https://user-images.githubusercontent.com/72735611/163129507-97b11ca8-cee0-4b19-96e7-900efe709450.png)

**Actual behavior**
The icon is displayed in the following way
<img width="48" alt="2022-04-12_17h11_30" src="https://user-images.githubusercontent.com/80695128/162981855-9e243676-b0de-4606-ab97-6cceb2453e05.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chrome
 - Version 100.0.4896.75

**Ketcher version** 
 v2.4.2-157-gу13ae6cb

**Comment by Svetlana-Asinovskaia** [comment]
Verified in Release/2.5.0
<img width="27" alt="2022-04-13_21h59_31" src="https://user-images.githubusercontent.com/80695128/163251212-bce3f555-401f-428e-a871-2928de3d6c25.png">

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
