### ISSUE TITLE
Floating windows - Change Calculate Values form design

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1428]
Change the visual presentation of the Calculated Values form:
1. Change color scheme, components place
2. All elements except Decimal places drop downs should obviously look as disabled. 
3. Buttons: button Close should be added on the buttons section below. 
4. OUT OF SCOPE: Copy to Clipboard button and it's abilities (will be implemented separately in the future). 

Use the design below:

![image](https://user-images.githubusercontent.com/90251323/162984162-8c6be217-d4eb-4749-9cf9-aa9ab28da49b.png)

**Comment by ansivgit** [comment]
1. All elements except Decimal places drop downs look as disabled, but we still can put cursor "text" on this fields (but can't change that can be misleading).
2. Buttons: button Close wider than in mockup (see screen below).
3. Fonts family doesn't match mockup (specially in "Elemental Analysis" textfield).
4. Font size in all input-fields doesn't match mockup (12px instead 14px).
![Screenshot 2022-04-19 144450](https://user-images.githubusercontent.com/56927722/163998330-b11a2b41-9cc5-41b1-884a-180a9ef98268.gif)

**Comment by AndreiMazol** [comment]
1 -fixed,
2, 3 - ok,
4 - will be fixed in scope of separate issue (it should be fixed globally)

**Comment by fedorseliankin** [comment]
Verified in Release 2.5
