### ISSUE TITLE
Pasting into "Open Structure" box does not seem to work

### ISSUE THREAD

**Issue by josemduarte** [epam/ketcher#143]
I have tried pasting a SMILES string into the open structure box at the demo page in https://lifescience.opensource.epam.com/ketcher/demo.html but the application does not allow pasting. It does allow typing in the SMILES string.

Is that intended?

**Comment by AndreiMazol** [comment]
Dear @josemduarte ,

Thank you for your interest in Ketcher.

The issue described above looks like a bug so  we will fix it in the future releases.

Best regards,
Ketcher team

**Comment by josemduarte** [comment]
Thanks for the quick fix!
