### ISSUE TITLE
'Add' button and scroll in the 'Periodic Table' window don't match the mockup

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1430]
**Steps to Reproduce**
1. Launch Ketcher.
2. Click the 'Periodic Table' button.
3. Compare the size, shape and location of the 'Add button' on both 'Table' and 'Extended' tabs with the mockup. 
4. Compare scroll on the 'Extended' tab with the mockup.

**Expected behavior**
Both 'Table' and 'Extended' tabs match the mockup.
<img width="392" alt="2022-04-12_17h24_57" src="https://user-images.githubusercontent.com/80695128/162984865-f478886e-1abe-44f4-a250-1c7c8c4e474a.png">

**Actual behavior**
'Add' button size and shape don't match the mockup. The location of the 'Add' button differs between tabs.

**Screenshots**
<img width="357" alt="2022-04-12_17h27_52" src="https://user-images.githubusercontent.com/80695128/162985499-4c4cf2eb-a0d6-467d-aa41-94323336453f.png">
<img width="352" alt="2022-04-12_17h28_11" src="https://user-images.githubusercontent.com/80695128/162985505-2eace0a3-ea47-4393-a88d-e0da6d616613.png">

Desktop:
OS: Windows 10
Browser - Chrome
Version 100.0.4896.75

Ketcher version:
v2.4.2-157-gу13ae6cb

**Comment by Svetlana-Asinovskaia** [comment]
The 'Add' button position changes when switching between two tabs
![2022-04-14_22h58_29](https://user-images.githubusercontent.com/80695128/163466490-b8ba6027-0ed9-4f13-b9e0-94c5b8454120.gif)

Tested in v2.4.2-184-g23626b99

**Comment by Svetlana-Asinovskaia** [comment]
It's necessary to click on a specific area of ​​the 'Add' button on the 'Table' tab to select it.
![2022-04-18_11h03_27](https://user-images.githubusercontent.com/80695128/163778419-082a8288-b5d1-4760-b0e2-3a545a287dd2.gif)

**Comment by Mariia-Katkova** [comment]
Verified in Release 2.5
