### ISSUE TITLE
The 'Templates' window doesn't match the mockup

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1435]
**Steps to Reproduce**
1. Launch Ketcher.
2. Click the 'Custom Templates' button.
3. Compare the location of the close (x) button with the mockup.

**Expected behavior**
The location of the close (x) button matches the mockup
<img width="278" alt="2022-04-13_09h10_30" src="https://user-images.githubusercontent.com/80695128/163112650-7774e19e-2726-4480-bbd1-ef40388d2ee3.png">

**Actual behavior**
The location of the close (x) button doesn't match the mockup

**Screenshots**

<img width="309" alt="2022-04-13_09h23_27" src="https://user-images.githubusercontent.com/80695128/163117956-86dbe7c9-501e-4856-b687-da8529fc4394.png">

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.88 

**Ketcher version** 
- v2.4.2-165-g4695c206

**Comment by Svetlana-Asinovskaia** [comment]
Verified in Release/2.5.0
<img width="620" alt="2022-04-14_22h34_42" src="https://user-images.githubusercontent.com/80695128/163463535-59327b2e-234b-4bcb-9615-a4283af0ebd6.png">

**Comment by Mariia-Katkova** [comment]
Regression re-check, in build 2.5 - OK
