### ISSUE TITLE
Floating Windows - Redesign Enhanced Stereochemistry window

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1439]
Implement design changes for the Enhanced Stereochemistry window:
1. Change color scheme, use header, buttons & other components from other form. 
2. Use the alignment rules defined for the standard forms. 
3. Buttons: add Cancel button, change label from OK to Apply for the existing button. 
4. Logic and validation should stay the same. 

Current design of the form:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/90251323/163191183-6696ceca-1448-4e38-8470-3beeec6c7e09.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/90251323/163191353-650a0b14-1d56-4e3e-8652-6ff3595f29e9.png">

**Comment by ansivgit** [comment]
1. Header has no bottom border.
2. No Cancel button.
3. Doesn't change label from OK to Apply for the existing button.
4. The default radiobutton appearance does not match the mockup (default stroke should be gray, on hover it should be green).
5. Fonts family doesn't match mockup.
6. Existing button wider than in mockup (80px vs 53px).
7. Existing form wider than standart form in mockup (330px vs 260px).

Current form
![Screenshot 2022-04-19 170708](https://user-images.githubusercontent.com/56927722/164022866-53a3355b-3a6b-412b-ac7f-bf5ac828ba47.gif)

Standart form
![Frame 2054](https://user-images.githubusercontent.com/56927722/164023127-663985fd-868f-4033-8be3-303c47b6e7cf.png)

**Comment by AndreiMazol** [comment]
Button min-height should be 80px (approved by UX team).  all other comments have been addressed.

**Comment by ansivgit** [comment]
All checked and all issues fixed
