### ISSUE TITLE
Add possibility to add plain text on canvas

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#144]
**Background:** 
Add text objects to Ketcher. First include simple text support, later add more advanced features
**Acceptance Criteria:**
* New text icon "T" appears at the Ketcher menu
* If user clicks on the icon, a modal window with Text editing form is opened (with Ok, Cancel buttons)
* There is a possibility to type a text.
* User is able to change coordinates the for the text object by dragging it
* I user double-clicks on the text object, a modal windows is opened and user is able to modify existing text object 
* Text labels should be saved into .ket format (Save button -> Graph format)
* Text labels should be read from .ket (Open button)

**Comment by Svetlana-Asinovskaia** [comment]
Release/ 2.3 The issue is verified and closed.
