### ISSUE TITLE
Add multiple arrow support for the same canvas

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#145]
**Background:**
See comment
https://github.com/epam/ketcher/issues/66#issuecomment-729587224
**Acceptance criteria**:
* User opens the reaction menu and selects type of reaction arrow (different types will be added in a separate task)
* User can add several arrows on the same canvas
* The only format to support several arrows on save/load is "ket" format
* If user selects a different format, then a warning message should appear "The ${selected_format} does not support drawn elements: reaction arrows will be lost"
* If user saves a different format, only one reaction arrow should be saved (left top one) with default reaction saving
* For the "ket" format save/load should work correctly (including arrow length, direction, coordinate and type)

**Comment by softcat23** [comment]
Within this task will be added only one new reaction arrow type:
![image](https://user-images.githubusercontent.com/45556539/108380388-d8ad9180-7217-11eb-920b-bd8c2ad8db94.png)
Other types will be added in the separate tasks.

**Comment by AndreiMazol** [comment]
Reopened. The structure should be saved as Mol if more than 1 arrow has been added.
