### ISSUE TITLE
The "Open structure" window doesn't match the mockup

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1450]
**Steps to Reproduce**
1. Launch Ketcher
2. Click on "Open..." icon on the top menu
3. Select the "PASTE FROM CLIPBOARD" to open the "Open structure" window 
4. Observe the "Open structure" window

**Expected behavior**

The "Open structure" window matches the mockup
![image](https://user-images.githubusercontent.com/103422815/163405704-e58024c6-56d3-45df-863e-8d03c81a4e23.png)

**Actual behavior**
The "Open structure" window doesn't match the mockup
![image](https://user-images.githubusercontent.com/103422815/163405430-97a22796-68c4-4cca-ac04-4e1963f7f85a.png)

OS: [Microsoft Windows]
Browsers: Google Chrome: Version 100.0.4896.75/FireFox: Version 99.0 (64-bit
Ketcher v2.4.2-180-gf29e041f

**Comment by AnaMoskvina** [comment]
The mockup isn't relevant
Open structure window should contain textarea
