### ISSUE TITLE
An error message is displayed when server functions are applied to an R-group member with invalid stereocenters.

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1452]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create a structure (e.g. benzene).
3. Define it as R-Group member (e.g. R1).
4. Add two Single Up Bonds to one atom.
5. Apply any server function (e.g. Click the 'Check Structure' button).

**Expected behavior**
'Structure Check' dialog is opened. The list or errors is present in it.

**Actual behavior**
The following error is displayed: "Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'RXN loader: bad header {', 'RXN loader: bad header {', 'molecule json loader: stereo type specified for atom #4, but the bond directions does not say that it is a stereocenter', 'molecule json loader: stereo type specified for atom #4, but the bond directions does not say that it is a stereocenter"

**Screenshots**
<img width="243" alt="2022-04-14_17h43_11" src="https://user-images.githubusercontent.com/80695128/163414584-b91be8be-a455-4b64-aa93-2c8e356c64be.png">

**Desktop:**
 - OS: Windows 10
 - Browser: chrome
 - Version 100.0.4896.88

**Ketcher version** 
- v2.4.2-177-g6d6dbdbf

**Comment by fedorseliankin** [comment]
Verified in Release 2.5
