### ISSUE TITLE
Design issues 

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1454]
Case 1
**Steps to Reproduce**
1. Launch Ketcher
2. Click on the "TP" icon on the down menu to open Templates dialog
3. Open any Template Library sections by clicking on the arrow to extend drop down (e.x: alfa-D-Sugars)
4. Select any structure (e.x: α-D-Allopyranose)
5. Observe the clicble area of the α-D-Allopyranose structure  

**Expected behavior**
Clickable area of the selected structure matches the mockup 
![image](https://user-images.githubusercontent.com/103422815/163397650-dad74c9e-c0d9-4956-ab15-b2a1b5e67110.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/103422815/163397609-2e6e2312-2875-4c1f-91d3-d3e3516c457e.png)

Case 2
**Steps to Reproduce**

1. Launch Ketcher
2. Create structure
3. Select the "R-Group Label Tool" on the left menu
4. Click on the structure with the R-Group Label Tool
5. Observe the width between elements

**Expected behavior**
Width between elements in the R-Group window matches the mockup 
![image](https://user-images.githubusercontent.com/103422815/163397814-dae3c87d-949e-462c-a545-49e2f1009dab.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/103422815/163397880-fef559b6-682d-4c67-b0df-35e1ba727a09.png)

Case 3
**Steps to Reproduce**

1. Launch Ketcher
2. Create structure on the canvas
3. Click on the Atom with the Fragment Selection Tool on the left menu
4. Click on the Atom with the S-Group Tool on the left menu
5. Observe the "S-Group Properties" window

**Expected behavior**
The "S-Group Properties" window matches the mockup 
![image](https://user-images.githubusercontent.com/103422815/163408485-8b3da3cb-c2f0-4180-bdef-56abc812b7d1.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/103422815/163408416-4ffc173e-dff2-4083-9df2-4748b51d75be.png)

Case 4
**Steps to Reproduce**

1. Launch Ketcher
2. Create structure on the canvas
3. Select the R-Group Fragment Tool on the left menu
4. Click on the Atom with the R-Group Fragment Tool
5. Select any R-Group 
6. Apply the selected R-Group to the Atom
7. Double-click on the R-Group on the canvas
8. Observe the R-Group Logic Condition window

**Expected behavior**
The R-Group Logic Condition window matches the mockup 
![image](https://user-images.githubusercontent.com/103422815/163427655-45df98ca-1dc8-4236-83e2-b76214f39f4b.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/103422815/163427759-220712fd-6e04-405d-93c1-9dde93c04227.png)

Case 5
**Steps to Reproduce**

1. Launch Ketcher in the Google Chrome browser 
2. Launch Ketcher in the Safari browser 
3. Compare text icons on the right menu

**Expected behavior**
Text icons on the right menu matches the mockup 

**Actual behavior**
![image](https://user-images.githubusercontent.com/103422815/163436203-6173cbd9-2165-4a5a-bb23-24726172d2d6.png)

Case 6 (Redesign Enhanced Stereochemistry window #1097)

Steps to Reproduce
Launch Ketcher
Click on "Open..." icon on the top menu
Select the "OPEN FROM IMAGE" tab

Expected behavior
1. The default radiobutton appearance matches the mockup (default stroke should be gray, on hover it should be green)
2. The text font should be -> Inter

Actual behavior 
1. The default radiobutton appearance does not match the mockup
2. Incorrect text font -> Helvetica

OS: [Microsoft Windows]
Browsers: Google Chrome: Version 100.0.4896.75/FireFox: Version 99.0 (64-bit)
Ketcher v2.4.2-158-g2312c8e8

**Comment by AnaMoskvina** [comment]
Cases 1, 2 - fixed with issue #1500

**Comment by ZhannaNovikova** [comment]
Cases: 1, 2, 3, 4, 6 verified as fixed on Release 2.5.0.
