### ISSUE TITLE
Blur structure in the "Preview" tab when structure is saved in the PNG Image format 

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1472]
**Steps to Reproduce:**
1. Launch the Ketcher
2. Create structure
3. Open the "Save Structure" dialog by clicking on the "Save As" icon on the top menu
4. Select the PNG Image format in the "File format" drop down

**Expected behavior:**

When selecting the PNG format the preview of the picture saved should be displayed without blur.
![image](https://user-images.githubusercontent.com/103422815/163856567-89e386ea-fbdd-4e12-85bd-d4489a99beea.png)

**Actual behavior:**

The preview of the saving picture is displayed with blur
![image](https://user-images.githubusercontent.com/103422815/163856669-db6f606b-bcfc-4b4d-8ca5-106240a715ca.png)

![image](https://user-images.githubusercontent.com/103422815/163856247-a3c631c1-c584-4c14-9bcf-49ece87f9c4c.png)

Note: the issue is not reproducible in the Remote mode

OS: [Microsoft Windows]
Browsers: Google Chrome: Version 100.0.4896.88/FireFox: Version 99.0.1 (64-bit)
Ketcher v2.4.2-197-gf82f9a99

**Comment by AnaMoskvina** [comment]
blur caused by external issues: for small structures we get bigger images from indigo

**Comment by ZaimBeshich1** [comment]
Verified as fixed on Release 2.5.0.
