### ISSUE TITLE
Add icon into the 'Periodic table' and align the Single/List/Not List buttons

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1473]
**Steps to Reproduce**
1. Launch Ketcher.
2. Click the 'Periodic Table' button.
3. Check icon near the 'Periodic table' header.
4. Check the alignment of the Single/List/Not List buttons.

**Expected behavior**
The 'Periodic table' matches the mockup.
<img width="328" alt="2022-04-18_21h58_52" src="https://user-images.githubusercontent.com/80695128/163860771-203be73a-82e9-4503-82fe-6e564fb4a13a.png">

**Actual behavior**
Icon is absent. The buttons are not aligned with the 'Add' button.

**Screenshots**
<img width="394" alt="2022-04-18_22h01_00" src="https://user-images.githubusercontent.com/80695128/163860976-2fe0b671-9ef7-4ba7-b5b8-f115a973d083.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 100.0.4896.88

**Ketcher version** 
- v2.4.2-196-gc17c8d4b

**Comment by fedorseliankin** [comment]
It was agreed not to align type selectors with footer buttons

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.

The Icon of the Periodic table has been added. 
The align type selectors with footer buttons have been agreed not to align.
