### ISSUE TITLE
The error message is displayed in the Save Structure window after selecting file format

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1486]
**Steps to Reproduce**
1. Launch Ketcher
2. Create 2 structures
3. Add more than 1 reaction arrow between them using the "Arrow Open Angle Tool" on the left menu
4. Click on the "Save as..." icon on the top menu
5. Select the format (e.x: ) in the "File format" drop down

**Expected behavior**

The "Save Structure" dialog is converted the structure to all file format successfully, without any errors 
**Actual behavior**
The "ERROR MESSAGE Convert error! struct data not recognized as molecule, query, reaction or reaction query" is displayed in the Save Structure window 

![image](https://user-images.githubusercontent.com/103422815/164041309-260ea365-0b0b-490e-98b4-a47e0c55608d.png)

Note: 
- The issue is reproducible after selecting file formats: MDL Molfile V2000/MDL Molfile V3000/Extended SMILES/Daylight SMARTS/InChI/InChI AuxInfo/
CML

OS: [Microsoft Windows]
Browsers: Google Chrome: Version 100.0.4896.88/FireFox: Version 99.0.1 (64-bit)
Ketcher v2.4.2-200-g5533ff35

**Comment by even1024** [comment]
Not reproduced in 1.7.1
