### ISSUE TITLE
R-Group definition changes when server functions are applied

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1487]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create a structure (e.g. benzene).
3. Define it as R-Group member (e.g. R28).
4. Click the "Layout' button.

**Expected behavior**
R-Group definition remains without changes (e.g. R28).

**Actual behavior**
R-Group definition is turned to R1.

**Screenshots**

![2022-04-19_22h19_21](https://user-images.githubusercontent.com/80695128/164080662-15a01b9f-c97f-4865-a0cd-fd0f90da5d75.gif)

**Desktop :**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 100.0.4896.88

**Ketcher version** 
- v2.4.2-212-g4dee48be

**Additional context**
1. Reproduced with Occurrence, RestH settings
2. Reproduced with Clean Up, Aromatize, Dearomatize, Save, Structure Check functions.

**Comment by Svetlana-Asinovskaia** [comment]
Related issue: https://github.com/epam/Indigo/issues/711

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
