### ISSUE TITLE
Design implementation issues

### ISSUE THREAD

**Issue by AnaMoskvina** [epam/ketcher#1500]
**TO BE FIXED:**
- Atom properties: fix header and footer shadows in Atom properties (should be '0 2px 4px 0 #dee1e4' and  '0 -2px 4px 0 #dee1e4') respectively; fix margins: should be 8px for all labels except for the last ones in accordion details (16px);
- About: fix button styles;
- Periodic table: fix tab border;
- Zoom: fix border and outline styles on hover and active;
- R-group: row gaps after every 10th element should be 12px (in other cases - 8px);
- R-Group Logic Condition: fix checkbox label position; fix Condition options style (use MUI select);
- Save structure: fix height of inputs (both should be 24px), add hover styles for text input, fix issue with borders of image container (container should occupy 100% width), fix text area paddings (should be 12px); remove text selection in text area;
- Templates: 'add to canvas' min width should be 110px, change clickable area for templates (should be preview + text); reset template selection on tab change in template dialog;
  
Already fixed:
- S-group issues
- Open structure issues
- border color of top toolbar dropdowns
- PNG preview
- Miew: bottom margin in footer is already 12px (other Miew questions discussed with Alena, decided not to change behavior)
- Save structure: hover on text preview causes additional border

Out of scope:
- different fonts in forms (atom properties, calculated values): to be fixed in separate task
- implementation of text tool (separate task)
- work of paste button

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
