### ISSUE TITLE
In Safari in modal window cancel button has additional border

### ISSUE THREAD

**Issue by fedorseliankin** [epam/ketcher#1501]
**Steps to Reproduce**
1. Launch ketcher in safari
2. Open Miew
3. look at cancel button

Expected behaviour
The "Cancel" button matches the mockup

Actual behavior
<img width="498" alt="Screenshot 2022-04-21 at 11 16 50" src="https://user-images.githubusercontent.com/100577149/164411242-48f0b021-10a9-4df4-841f-03c5f03a5dcf.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Ketcher version** [e.g. v2.4.2-115-gcf0c1394]. 
To determine it, hover over the header of the Ketcher tab in a browser. 

**Additional context**

**Comment by ZaimBeshich1** [comment]
Verified as fixed on Release 2.5.0
