### ISSUE TITLE
Change the default values ​​in the fields with drop-down lists in the 'Atom Properties' window  

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1511]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create a structure.
3. Double-click any atom of the structure

**Expected behavior**
The fields 'Valence', 'Radical', 'Ring bond count', 'H count', 'Substitution count', 'Inversion' are blank by default.
The 'Valence' drop-down list contains the values from '0' to 'VIII'. Only one '0' value is present in each drop-down list.

**Actual behavior**
The fields 'Radical', 'Ring bond count', 'H count', 'Substitution count', 'Inversion' have '0' as a default value. The value '0' is doubled in these fields.
The field 'Valence' has '-1' as a default value.

**Screenshots**
<img width="126" alt="2022-04-21_22h37_22" src="https://user-images.githubusercontent.com/80695128/164539667-c5f54cc5-7f31-4386-a3dd-f8be46e30bf4.png">
<img width="126" alt="2022-04-21_22h37_31" src="https://user-images.githubusercontent.com/80695128/164539670-372aab1f-b678-4cd9-b4b4-dcfe2f8c9b6b.png">

**Ketcher version** 
Ketcher v2.4.2-219-g11bc5160

**Comment by ZhannaNovikova** [comment]
Checkboxes and labels in the 'Atom Properties' window should be aligned
![image](https://user-images.githubusercontent.com/103422815/165470517-35dfc07a-3edb-4e72-9d07-f44993931b66.png)

**Comment by ZhannaNovikova** [comment]
- Incorrect font size of the Accordion modules - 12 px (should be 14 px);
![image](https://user-images.githubusercontent.com/103422815/165715568-333f0706-f083-4ae8-8c9a-36c24bb5d805.png)

- The sliders in the drop downs of the Atom Properties doesn't much the mockup 
![image](https://user-images.githubusercontent.com/103422815/165715649-d3991e23-29a2-4b8f-9621-7c2cc63a17f1.png)
![image](https://user-images.githubusercontent.com/103422815/165716286-2577d2fa-2bb4-4af9-a5d5-d6bf63c7ea21.png)

- Overlapping the drop downs value
![image](https://user-images.githubusercontent.com/103422815/165719762-d5f4be8d-caed-4724-9442-6dfba610f03d.png)

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
