### ISSUE TITLE
Text Tool issues

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1512]
1. Selected formatting is reset after clicking the text editing field.
![2022-04-21_22h57_11](https://user-images.githubusercontent.com/80695128/164542552-a062702d-96b9-4126-93a1-af74769b0800.gif)

2. Previous formatting is activated after changing the font size.
Steps to reproduce:
1) In the 'Text Editor' window select 'Bold'
2) Type some symbols in the text editing field.
3) Unselect 'Bold'
4) Change the font size
![2022-04-21_23h03_46](https://user-images.githubusercontent.com/80695128/164543711-3b204474-93dd-4d43-8711-1988b8e15964.gif)

3. Not selected text changes it's position when 'Superscript' is applied to the selected part of the text.
![2022-04-21_23h11_53](https://user-images.githubusercontent.com/80695128/164544729-bc2d4e8f-dde8-4456-8559-45c4ec3cdf6a.gif)

4. Drop-down lists in the 'Font Size' and 'symbols' fields do not close when clicking on the text edit field.
5. There is a space between characters when the subscript/superscript is applied to the beginning of the text.

<img width="201" alt="2022-04-22_13h01_43" src="https://user-images.githubusercontent.com/80695128/164684844-8722db4a-e940-4e45-8745-799174e5f9fa.png">

**Ketcher version** 
Ketcher v2.4.2-212-g4dee48be

**Comment by ZhannaNovikova** [comment]
The cases: 1, 3, 5 - verified as fixed on Release 2.5.0
