### ISSUE TITLE
Floating windows - Change settings window design 

### ISSUE THREAD

**Issue by ViktorMakarov-EPAM** [epam/ketcher#1518]
What to change:

1. Use the color scheme, header, buttons, other standard components from the other forms

2. Apply alignment & pixel rules for the elements on the form.

3. Validation and logic should stay the same.

4. Redesign of the form is needed. Accordion solution to implement with the General section expanded by default when the form is opened. Use the designs below

5. Tab General should be opened when the form is opened. If other tabs were expanded on the form and it was closed and opened repeatedly - the General tab should be opened, not the previously expanded tab.

6. Scroll should be applied for the all content inside the form, just like it is on the Atom properties form.

7. Redesign Color picker.

8. Redesign Slider (Checkbox Switcher).

9. If changes have been made to the group fields, a marker should appear in the group header.

10. Line break in the label should not isolate one word in the next line (two or more)

<img width="444" alt="Снимок экрана 2022-04-25 в 09 34 06" src="https://user-images.githubusercontent.com/91740100/165033113-99465e9f-15f5-45ca-948d-bd810facbbc5.png">

**Comment by ZhannaNovikova** [comment]
Doesn't fit the requirements: 
- Overlapping the drop downs values
![image](https://user-images.githubusercontent.com/103422815/165536479-41e7bc53-0a2e-4ba7-b237-edac29cdb448.png)

**Comment by ViktorMakarov-EPAM** [comment]
Clickable area for slider was decided to be as it is. Changing leads to regression on lots of pages/windows.

**Comment by ZhannaNovikova** [comment]
Verified in Release 2.5.0
