### ISSUE TITLE
The valence of monovalent atoms is displayed incorrectly in the structure after the Copy/Paste actions

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1531]
**Steps to Reproduce**
1. Lauch Ketcher.
2. Create a structure (e.g. chain).
3. Change some carbon atoms located in the middle of the structure to a monovalent atom (e.g. 'F' and 'Br').

**Expected behavior** 
'F' and 'Br' atoms are underlined in red as atoms with an impossible number of bonds - correct behavior.

4. Select the structure. Copy - Paste it on the canvas.

**Expected behavior**
'F' and 'Br' atoms are underlined in red in the pasted structure.

**Actual behavior**
'F' and 'Br' atoms are not underlined and shown as atoms with correct number of bonds.

**Screenshots**
<img width="248" alt="2022-04-26_22h54_39" src="https://user-images.githubusercontent.com/80695128/165381405-6c6c0bf4-8922-46b9-a565-0d2bea2f5428.png">

 Desktop:

OS: Windows 10
Browser: chrome
Version 100.0.4896.127

Ketcher version
v2.4.2-212-g4dee48be

**Additional Information**
The issue is reproducible with the Cut-Paste actions and after opening the saved structure.

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
