### ISSUE TITLE
Drop down fields don't match the mockup

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1536]
Case 1
**Steps to Reproduce**
1. Launch Ketcher
2. Open the Atom Properties window

**Expected behavior**
All drop downs of the fields should be matched the mockup

**Actual behavior**
Doesn't fit the mockup:
- Color of the scrollbar track in the drop downs:
Valence drop down;
Substitution count drop down;

- Rounding the bottom corners of the border:
Valence drop down;
Radical drop down;
Substitution count drop down;

- Size of the drop down:
Radical drop down

Case 2
**Steps to Reproduce**
1. Launch Ketcher
2. Open the Settings window

**Expected behavior**

All drop downs of the fields should be matched the mockup

**Actual behavior**
Doesn't fit the mockup:
- Color of the scrollbar track in the Font drop down
- Rounding the bottom corners of the border in the Font drop down:
- Size of the Color stereogenic centers drop down
- Size of the Show hydrogen labels drop down

Case 3
**Steps to Reproduce**
1. Launch Ketcher
2. Open the S-Group Properties window

**Expected behavior**

All drop downs of the fields should be matched the mockup

**Actual behavior**
Doesn't fit the mockup:
- Color of the scrollbar track in the Field value drop down
- Rounding the bottom corners of the border in the Field value drop down:
![image](https://user-images.githubusercontent.com/103422815/165931240-ca291784-1cee-41b7-a798-909fdcdfa1a9.png)

OS: [Windows NT 10.0 Win64; x64]
Browsers: Google Chrome: Version 101.0.4951.41/FireFox: Version 99.0.1 (64-bit)
Ketcher v2.4.2-276-g718647ac

**Comment by ViktorMakarov-EPAM** [comment]
Size of labels drop down depends on content. MUI does not allow you to increase the size of the list. Their solution was not to crop the content.
