### ISSUE TITLE
Issues in the 'S-Group properties' window when the 'Multifragment'/'Fragment' context is selected

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1539]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create a structure (e.g. chain)
3. With 'Data S-Group' tool select a part of the structure.
4. Select the value in the 'Context' dropdown (e.g. 'Multifragment' ). 
5. Select any radiobutton (e.g. 'Relative' ). Apply settings.
6. Double click the descriptor (e.g. aerosol).

**Expected behavior**
The 'S-Group Properties' window is opened with the previously selected settings - 'Multifragment' value from the 'Context' dropdown, the 'Field name' field is filled. It's possible to select a value in the dropdown list of the 'Field value' field. 

**Actual behavior**
The 'S-Group Properties' window is opened with the following errors:
1) the 'Group' value is selected in the the 'Context' dropdown;
2) the font in the 'Field value' field doesn't match the mockup;
3) the drop-down list is absent in the 'Field value' field; it's possible to change the size of the field manually;
4) the 'Field name' field is empty.

**Screenshots**
<img width="177" alt="2022-04-27_22h39_45" src="https://user-images.githubusercontent.com/80695128/165611759-3fa0efb0-65c5-43cd-b1ee-5474f274200f.png">
<img width="162" alt="2022-04-28_11h09_41" src="https://user-images.githubusercontent.com/80695128/165707636-e2f7a541-d3d4-4291-8fd3-70b06b902a58.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 100.0.4896.127 

**Ketcher version** 
v2.4.2-212-g4dee48be

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
