### ISSUE TITLE
Update PT, TP, EP icons, fix summary in templates

### ISSUE THREAD

**Issue by AnaMoskvina** [epam/ketcher#1547]
- update PT, TP, EP icons
- order of icons in right toolbar should be as at markup

out of scope: order of template icons in bottom toolbar (should not be changed)
![toolbars](https://user-images.githubusercontent.com/77681522/165933682-516b1c9f-73ac-4904-a349-cd8ec1873deb.PNG)

**Issue with accordion summary:**

**Steps to Reproduce**
1. Launch Ketcher
2. Click the 'Custom Template' button

**Expected behavior**
The tree contains the template folders:
-α-D-Sugars
-β-D-Sugars

**Actual behavior**
The tree contains the incorrect template folders:

alpha-D-Sugars

beta-D-Sugars

**Comment by ZhannaNovikova** [comment]
Verified on Release 2.5.0.
