### ISSUE TITLE
Molecule not loading in embedded Ketcher windows in Safari

### ISSUE THREAD

**Issue by OBrink** [epam/ketcher#1549]
We have launched a web application on https://decimer.ai (https://github.com/OBrink/DECIMER_Web) where a user can upload a pdf document or chemical structure images and as a result, the structure images are segmented (only from pdf) and the SMILES representation is generated based on the images. The resulting chemical structures are then loaded into embedded Ketcher windows where the user can edit them before downloading the results. 

This works perfectly fine in Chrome, Firefox (there are different issues here but the result is loaded into the Ketcher windows), Opera and Edge. In Safari, the loadMol function fails

**Steps to Reproduce**
1. Go to https://decimer.ai
2. Click on the upload button and upload an image that contains a chemical structure
3. Wait until it is processed and the results are displayed

**Expected behavior**
In Edge, Firefox, Opera and Chrome, the resulting chemical structure is loaded in the Ketcher editor window.

**Actual behavior**
In Safari (tested with versions 11.1|12.1|13.1|14.1|15.3), no molecule appears in the editor window and the console output looks like this:
"TypeError: undefined is not an object (evaluating 'ketcher.setMolecule')"

**Desktop:**
 - OS: iOS
 - Browser: Safari
 - Tested with the following versions 11.1|12.1|13.1|14.1|15.3

**Ketcher version** 
v2.3.3-279-ga6f91d0d
Edit: It now uses v2.4.2 (latest release right now), but the issue remains

Ketcher is simply embedded in an iframe. Here is an example with an inserted smiles str:
`<iframe onload="loadMol('C[C@@]12C[C@H](C([C@]1(CC(=O)[C@@]34[C@]2(CC=C5[C@H]3C=C(C(=O)C5(C)C)O)COC4)C)[C@](C)(C(=O)/C=C/C(C)(C)O)O)O', '1')" id="1" name="1" src="ketcher_standalone/ketcher_index.html" width="100%" height="420px"></iframe>`

Could you maybe give me a hint about what is going wrong here? Thank you in advance! :)

**Comment by Mariia-Katkova** [comment]
Thank you for sharing feedback with us,

The error is pointing that ketcher instance is not ready while being called. To fix it, you can generate the src of iframe dynamically (using formula string in the path) instead of using ‘onload’ event. For example: 

`<iframe src="ketcher_standalone/ketcher_index.html?moll=ccc">`


If this solution is not suitable for you, please provide us full code for the loadMol function that you use to load ketcher in an iframe.

**Comment by OBrink** [comment]
Thank you for answering!

With the suggested solution, some SMILES are not read correctly. 
Example:
`
<iframe src="ketcher_standalone/ketcher_index.html?moll=C1C(=N[N+]#[C-])C=CC(=N[N+]#[C-])C1Cl">
`
--> molecule auto loader: SMILES loader: invalid character within atom description: ' ''

With your hint about what was going wrong, I have solved the issue by adapting my loadMol function.
Previously, the function looked like this:
`
function loadMol(smiles, frame_id)
      {  var ketcher = getKetcher(frame_id);
         ketcher.setMolecule(smiles);
      }
`
Now, it waits for 100 ms and tries again if the Ketcher window could not be loaded.
`
function loadMol(smiles, frame_id)
      {   try {
              var ketcher = getKetcher(frame_id);
      }   catch (e) {
              var ketcher = null;
      }   if (ketcher) {
              ketcher.setMolecule(smiles);
          } else {
              setTimeout(loadMol, 100, smiles, frame_id);
          }
      }
`

The getKetcher function used here comes from: https://github.com/ggasoftware/ketcher/blob/master/demo.html
