### ISSUE TITLE
Blank page after applying the 'Shift + f' hotkey

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1551]
**Steps to Reproduce**
1. Launch Ketcher.
2. Apply the 'Shift + f' hotkey

**Expected behavior**
The 'Functional Groups' library is opened.

**Actual behavior**
A blank page is displayed. Errors appear in the console.

**Screenshots**
<img width="959" alt="2022-05-02_15h05_23" src="https://user-images.githubusercontent.com/80695128/166230851-391de5cf-6d42-4817-936c-fb09c92cb9c8.png">

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 100.0.4896.127

**Ketcher version** 
- v2.4.2-219-g11bc5160

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
