### ISSUE TITLE
It's not possible to select parts of different structures using the 'Shift' key.

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1552]
**Steps to Reproduce**
1. Ketcher is launched.
2. Several structures are created on the canvas
3. Press the 'Shift' key and with any 'Select' tool select parts of the created structures.

**Expected behavior**
Parts of different structures are highlighted in green.

**Actual behavior**
The selection is reset when a part of the next structure is selected.

**Screenshots**
![2022-05-02_15h28_19](https://user-images.githubusercontent.com/80695128/166233644-ab01cac5-f370-4d5a-9bc5-7151dc76bb4d.gif)

**Desktop:**
- OS: Windows 10
- Browser: Chrome
- Version: 100.0.4896.127

**Ketcher version:**
- v2.4.2-219-g11bc5160

**Additional information:**
The issue is reproducible in 2.4. Behavior is as expected in 2.3.

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
