### ISSUE TITLE
It's possible to create a custom template with a duplicate name

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1553]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create a structure on the canvas.
3. Click the 'Save as' button.
4. Click the 'Save to Templates' button.
5. In the 'Molecule name' field enter any name <Name1>.
6. Click the 'Apply' button.

**Expected behavior** 
The user template with <Name1> is saved to the User Templates - correct behavior.

7. Repeat steps 3-6.
 
**Expected behavior**
An error 'Template must have a unique name...' is displayed. The 'Apply' button is disabled.

**Actual behavior**
A template with a duplicate name is saved to the User Templates.

**Screenshots**
<img width="283" alt="2022-05-02_15h49_27" src="https://user-images.githubusercontent.com/80695128/166236250-01832cf1-0ca3-4cf8-8154-051e3d4a054c.png">

**Desktop:**
- OS: Windows 10
- Browser: Chrome
- Version: 100.0.4896.127

**Ketcher version:**
- v2.4.2-219-g11bc5160

**Additional information:**
1. The error text ''Template must have a unique name...' overlaps the 'Molecule name' field. 
2. The behavior is as expected in 2.4.

**Comment by AnaMoskvina** [comment]
if creation of templates with the same name doesn't cause any difficulties in usage, decided not to change behavior
approved @Alena-Guznischeva

**Comment by ZhannaNovikova** [comment]
The issue related to the behavior when the error text ''Template must have a unique name...' overlaps the 'Molecule name' field will be fixed in the separate task: https://github.com/epam/ketcher/issues/1599

**Comment by ZhannaNovikova** [comment]
Verified that the "Molecule name" field сannot be created with greater than 128 characters on Release 2.5.0.
