### ISSUE TITLE
S-group textarea redesign

### ISSUE THREAD

**Issue by ViktorMakarov-EPAM** [epam/ketcher#1561]
1. Textarea scroll should appear if the content goes out of bounds
2. Textarea can only be stretched vertically (56 - 240px)
3. Field value validation error message must be "Please, specify field value"
4. Right margin must be exactly 12px

**Comment by ZhannaNovikova** [comment]
Doesn't fit the requirements.

Expected behabior:
Textarea can only be stretched vertically (56 - 240px)

Actual behavior:
Textarea can has stretched horizontal 
![image](https://user-images.githubusercontent.com/103422815/167107947-6ebd6ac9-1d64-4873-813d-7f7223979268.png)

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
