### ISSUE TITLE
Incorrect rendering of Data S-Group when it is applied to part of the cyclic structure

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1575]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create a cyclic structure on the canvas (e.g. use the 'benzene' template).
3. With Data S-Group tool select a part of the created structure.
4. Click the 'Apply' button.

**Expected behavior**
The 'cis' descriptor is located near the structure.

**Actual behavior**
The 'cis' descriptor is located far from the structure.

**Screenshots**
![2022-05-05_22h10_04](https://user-images.githubusercontent.com/80695128/167007114-a1bf3bc0-2d5b-4d50-be0e-5d69e0fe38a8.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 101.0.4951.41

**Ketcher version** 
- v2.4.2-212-g4dee48be

**Additional context**
The issue is reproducible in v 2.3

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
