### ISSUE TITLE
Wrong sign for specific types while ket-generation

### ISSUE THREAD

**Issue by even1024** [epam/ketcher#1600]
**Steps to Reproduce**
1. Draw any reaction
2. Draw a simple object
3. Generate ket

**Expected behavior**

y coordinates for simple objects, pluses and arrows are negative as atom's y-coordinates inside molecules.

**Actual behavior**

y coordinates for simple objects, pluses and arrows are positive.

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.

**Comment by AnaMoskvina** [comment]
also fixed: 
- atom list/not list sign (Y position)
- r-label sign (Y position)

**Comment by ZhannaNovikova** [comment]
Additional issues (atom list/not list sign (Y position) r-label sign (Y position) has been verified as fixed on Release 2.5.0.
