### ISSUE TITLE
Change the list of values in the 'Font Size' drop-down list in the 'Text Tool'

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1607]
**Steps to Reproduce**
1. Launch Ketcher
2. Click the 'T' icon
3. Click the canvas
4. Check the values in the 'Font Size' drop-down list

**Expected behavior**
The values from '4' to '144' are present in the drop-down list.

**Actual behavior**
The values from '4' to '60' are present in the drop-down list.

**Screenshots**
<img width="960" alt="2022-05-16_10h28_10" src="https://user-images.githubusercontent.com/80695128/168540920-700035ee-e62a-4393-b97d-fae844a6b645.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101.0.4951.54

**Ketcher version** 
Ketcher v2.4.2-325-g75abd1d4

**Comment by ZhannaNovikova** [comment]
Verified as fixed on Release 2.5.0.
