### ISSUE TITLE
The template behavior incorrectly when overlay structures by pasting or dragging-drop on the canvas

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1612]
Case 1
**Steps to Reproduce**
1. Launch the Ketcher
2. Select the template on the down toolbar or Template library (e.g. Benzene)
3. Create the Benzene template by clicking on the canvas
4. On the same place on the canvas create the selected template by clicking again

https://user-images.githubusercontent.com/103422815/168637167-e20cad2a-cdf0-4312-8392-b968fd5ae148.mp4

Case 2
**Steps to Reproduce**
1. Launch the Ketcher
2. Select the template on the down toolbar or Template library (e.g. Benzene)
3. Create two structures on the canvas by click on the canvas
4. Select the first structure by using any Selection tool
5. Dragging-drop first selected structure on the second structure so that they match perfectly

https://user-images.githubusercontent.com/103422815/168637638-9c0d4e5b-bffc-4c81-9440-892076fb38b1.mp4

**Expected behavior**
Action to overlap the template on the template using Paste or Dragging-drop cannot be abled

**Actual behavior**
Action of the overlaping templates are abled
The 3 molecules of the "H-Hydrogen" have been lost

Case 3
**Steps to Reproduce**
1. Launch the Ketcher
2. Select the template on the down toolbar or Template library (e.g. Cyclopentadiene)
3. Create the Cyclopentadiene template by clicking on the canvas
4. Click on the Cyclopentadiene atom in the existing structure to add the same template to the structure connected with a single bond
5. Repeat Step 4 -> 10-12 times

https://user-images.githubusercontent.com/103422815/168638216-484088d2-9887-4c6f-b60b-d72f6391dee8.mp4

**Expected behavior**
The behavior should be consistent

**Actual behavior**
After adding the template to the existing structure connected with a single bond the behavior is inconsistent
- Template is added to the atoms of existing structure connected with a single bond
- Template is added to the existing structure with connected with an atom

OS: [Windows NT 10.0 Win64; x64]
Browsers: Google Chrome: Version 100.0.4896.88/FireFox: Version 99.0.1 (64-bit)
Microsoft Edge: Version 101.0.1210.39 (Official build) (64-bit)

Ketcher v2.4.2-325-g75abd1d4

**Comment by KonstantinEpam23** [comment]
@Zhirnoff @AlexanderSavelyev looks like this is already resolved, I propose closing this task (should be fixed by previous @St-Permiakov PR)

**Comment by Zhirnoff** [comment]
> @Zhirnoff @AlexanderSavelyev looks like this is already resolved, I propose closing this task (should be fixed by previous @St-Permiakov PR)

Bug is fixed after PR @St-Permiakov https://github.com/epam/ketcher/issues/2047
