### ISSUE TITLE
Change the 'Version' link in the Info panel

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#1615]
**Steps to Reproduce**
1. Launch Ketcher.
2. Click the  'About' icon.
3. Click the 'Version 2.4.2' link.

**Expected behavior**
The user is redirected to the following page https://lifescience.opensource.epam.com/ketcher/index.html

**Actual behavior**
The user is redirected to the obsolete Help page - https://lifescience.opensource.epam.com/ketcher/help.html

**Screenshots**
<img width="960" alt="2022-05-17_17h35_25" src="https://user-images.githubusercontent.com/80695128/168837386-aaa06d17-8ce3-4e90-ae10-fd8ec42169fe.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101.0.4951.67

**Ketcher version** 
Ketcher v2.4.2-325-g75abd1d4

**Comment by AnaMoskvina** [comment]
Additional scope: 
update help link: should open the 'help' page according to latest tag (not according to the current branch)
