### ISSUE TITLE
The added Reaction Plus to the structure is lost after applying the Layout

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/ketcher#1616]
**Steps to Reproduce**
1. Launch Ketcher
2. Create 2 structures
3. Add the reaction plus between them using the "Reaction Plus Tool" on the left menu
4. Click on the "Layout" icon on the top menu
[structure with reaction plus.zip](https://github.com/epam/ketcher/files/8709482/structure.with.reaction.plus.zip)

*Expected behavior**
The Reaction Plus Tool after applying the Layout should be displayed correctly

![image](https://user-images.githubusercontent.com/103422815/168849962-2f6d3e2d-0762-4c7d-9f4d-638d3383331b.png)

**Actual behavior**
The added Reaction Plus to the structure is lost after applying the Layout
![image](https://user-images.githubusercontent.com/103422815/168847112-917c54e2-b7f2-42fc-9529-c193141eaa43.png)

**Note:** 
- the issue is reproducible with all server tools
- the issue is reprodusible in the releases 2.3. and 2.4.

OS: [Windows NT 10.0 Win64; x64]
Browsers: Google Chrome: Version 100.0.4896.88/FireFox: Version 99.0.1 (64-bit)
Microsoft Edge: Version 101.0.1210.39 (Official build) (64-bit)

Ketcher v2.4.2-330-g777924a1

**Comment by ZhannaNovikova** [comment]
Related issue in the Indigo: https://github.com/epam/Indigo/issues/733

**Comment by evgeniiFrolov1** [comment]
Waiting for indigo update

**Comment by flccrakers** [comment]
Hello all, this bug seems always to be occurring. Do you have any news from Indigo?
