### ISSUE TITLE
Change loading indicator for the server operations on the canvas content

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#1619]
Implement a new visual representation of the loading indicator for the operations applied for the entire canvas content. The loading indicator should have 3 dots representation (already used in other forms). 

AC1: GIVEN Ketcher User WHEN initiating the operations on the entire canvas content (Aromatize, Dearomatize, Calculate CIP, Layout, Clean up) THEN Ketcher disables the ability to manipulate with canvas content AND displays the loading indicator with 3 dots while the operation is performed

AC2: GIVEN Ketcher User WHEN the operations on the entire canvas content are fulfilled and server response is received THEN I can see the operation results on the canvas with the enabled canvas

AC3: GIVEN Ketcher User WHEN Initiating the operation on the entire canvas content and not receiving the response for 10 seconds THEN Ketcher displays the CANCEL button with message text along with the loading indicator and provides the ability to click on it

AC4: GIVEN Ketcher User WHEN initiating the operation on the entire canvas content and not receiving the response for 10 seconds and clicking on the CANCEL button THEN Ketcher displays enabled canvas with the unchanged content 

Use the design below (except for the message text, it should be: "Operation may take too long")

<img width="97" alt="image" src="https://user-images.githubusercontent.com/90251323/169261599-f003d1f5-94ea-4910-a328-e560e748add5.png">

![image](https://user-images.githubusercontent.com/90251323/169261656-dd9fb462-c1dd-4e6c-af7d-2ef655971ace.png)

**Comment by ZhannaNovikova** [comment]
The "AC4: GIVEN Ketcher User WHEN initiating the operation on the entire canvas content and not receiving the response for 10 seconds and clicking on the CANCEL button THEN Ketcher displays enabled canvas with the unchanged content" will be implemented in the separate task: https://github.com/epam/ketcher/issues/1629

**Comment by ZhannaNovikova** [comment]
Verified in Release 2.5.0
