### ISSUE TITLE
We need Ketcher 2 without React. 

### ISSUE THREAD

**Issue by rccc** [epam/ketcher#163]
Hello,

I do not understand you made the choice to use React for Ketcher 2. 

 React is a very heavy  library, all the code is interpreted at runtime. 

Ketcher is indeed a great tool, i do not undestand this choice.

Eric

**Comment by vanoprenko** [comment]
React replaced Preact framework which Ketcher was originally based on. Preact is a lite version of React but it is far less popular and React based apps had to keep both React and Preact libs. Now their life is simplified a little bit.

However we are going to keep Ketcher as lightweight as possible in the future and will soon enhance its architecture by splitting onto 2 modules: the core part (including editor) and the UI controls which are currently based on React but may further be implemented based on any other framework (e.g. Angular) or your own custom controls.

Sorry for temporary inconvenience. Hope you'll enjoy the new more modular architecture once it is implemented.
