### ISSUE TITLE
ketcher.getSmilesExt() method in JS - version 2.4.2 (standalone)

### ISSUE THREAD

**Issue by dboeglin** [epam/ketcher#1636]
Hi,

I am trying to export current structure as a extended SMILES (with stereochemistry) string in JS with version 2.4.2 (standalone).
Daylight SMILES (without stereochemistry) works well with the following command:
 ketcher.getSmiles().then(function(xyz) {....}

How should I proceed with extended SMILES ? (ketcher.getSmilesExt() method does not work).
Additionally, is there a way to get InChl and InChlkey with JS ?

Thanks for your help and congrats for the good job !

**Comment by edgeTurbo** [comment]
ketcher.getSmiles(true).then(...
it can be work

**Comment by dboeglin** [comment]
Thanks ! ketcher.getSmiles(true) is working.

**Comment by AndreiMazol** [comment]
@dboeglin @edgeTurbo  JFYI the documentation will be published on Wiki as the part of release 2.5.
