### ISSUE TITLE
Listener callback function for structure change ?

### ISSUE THREAD

**Issue by dboeglin** [epam/ketcher#1637]
Hi,

I would like to know if any Javascript function/method Listener callback function is available on Ketcher 2.4 (standalone). More specifically, I am looking for a listener that trigger an event each time the structure is changed within Ketcher.
Is this type of function already available on Ketcher ? if not, is it possible to implement such type of function in the near future ?
Thanks for your feedback,
Dam

**Comment by edgeTurbo** [comment]
#1209
