### ISSUE TITLE
add cdx support

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#1640]
### Discussed in https://github.com/epam/ketcher/discussions/1605

<div type='discussions-op-text'>

<sup>Originally posted by **CLLPCH** May 13, 2022</sup>
Dear Ketcher team,

Thanks for the excellent Ketcher editor :thumbsup:
I found this [https://github.com/epam/ketcher/issues/920](https://github.com/epam/ketcher/issues/920) so the cdxml file format is supported. Then, I would like to know, do you have a plan to support cdx file format?

 
</div>

cdx files can be found here: https://github.com/epam/Indigo/tree/master/api/tests/integration/tests/formats/molecules

**Comment by AndreiMazol** [comment]
Moved to  2.5.2: waiting for BE part.

**Comment by Nitvex** [comment]
Related indigo issue:
https://github.com/epam/Indigo/issues/885

**Comment by vanoprenko** [comment]
Please implement not displaying file content while opening CDX file in scope of this task.
