### ISSUE TITLE
Issues with stereochemistry in polymer chain

### ISSUE THREAD

**Issue by dboeglin** [epam/ketcher#1642]
**Steps to Reproduce**
1. Launch Ketcher ( Ketcher 2.4.2 standalone)
2. Draw a chemical structure with stereochemistry within its polymer chain (see example in pictures below)
3. Click save 'extended smiles' or get extended smile from ketcher.getSmiles(true) and generate svg image of the structure drawed from ketcher.generateImage

Issue:
The extended smiles generates this way is wrong: the first stereocenter of the polymer chain is inverted and all other stereocenters of the polymer chain are missing.

Picture:
![png1](https://user-images.githubusercontent.com/38424733/169973942-dd1c5b6a-211f-4774-b20b-450b31728635.png)

![png2](https://user-images.githubusercontent.com/38424733/169973984-61df343d-4b8c-45a7-864a-d396edfd0fd1.png)

![png3](https://user-images.githubusercontent.com/38424733/169974004-65d843d1-519b-4a30-be78-a519cef25c56.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 100.0.2 (64 bits)

**Ketcher version**     version2.4.2 build at 2022-02-21T15:06:53

**Comment by AndreiMazol** [comment]
Dear @dboeglin ,

thank  you for your issue. 
The issue will be reviewed and fixed in scope of the nearest releases.

Regards,
Ketcher team

**Comment by AlexanderSavelyev** [comment]
The problem here is that SMILES does not support Mul groups and expands the groups. But it can't be sure that keeping stereo information will be correct after an expansion therefore it removes all the stereo. If we change the behavior it can affect other molecule structures with stereo
