### ISSUE TITLE
ketcher.getSmiles() return error！

### ISSUE THREAD

**Issue by suzhouhu** [epam/ketcher#1645]
`ketcher.getSmiles() ` return [object Promise]！

![图片](https://user-images.githubusercontent.com/23079693/170262889-b4de0388-0bdb-40b2-b738-d7f97e2f61d9.png)

**Comment by AndreiMazol** [comment]
@suzhouhu ,

ketcher.get*() methods return Promise<Struct> as expected. If you  want to get SMILES string it is necessary to wait while promise is finished:

`ketcher.getSmiles().then(result => console.log(result))`

Regards,
Ketcher team

**Comment by suzhouhu** [comment]
Thank you very much



发自我的iPhone


------------------ Original ------------------
From: Andrei Mazol ***@***.***&gt;
Date: Wed,May 25,2022 8:38 PM
To: epam/ketcher ***@***.***&gt;
Cc: 刘鹄中 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [epam/ketcher] ketcher.getSmiles() return error！ (Issue #1645)





 
@suzhouhu ,
 
ketcher.get*() methods return Promise as expected. If you  want to get SMILES string it is necessary to wait while promise is finished:
 
ketcher.getSmiles().then(result =&gt; console.log(result))
 
Regards,
 Ketcher team
