### ISSUE TITLE
Disable/enable features

### ISSUE THREAD

**Issue by Doidel** [epam/ketcher#165]
Is it possible to specifically disable/enable features of Ketcher 2.0?

**Comment by AndreiMazol** [comment]
Hello @Doidel ,

At this moment Ketcher does not support disabling of any  features but in the future we plan to provide possibility to choose the list of features while building the app (or configuring <Editor> component if you use npm package). 

Could you provide the list of features that you  want to disable?

Best regards,
Ketcher team

**Comment by Doidel** [comment]
Hi @AndreiMazol and thanks for the instant reply.
No problem, thanks for letting me know.

Disabling features would probably be a temporary measure in our case. I can elaborate a bit:
The nginx reverse proxy in front of the Docker service is something we couldn't do yet because of missing prerequisites (nested virtualization, open deployment questions, etc..). So in order to demo the Ketcher editor within our application to the upper management, I reverse engineered the API in our existing C# service, but just the "layout" and "info" APIs (so we can convert SMILES to molfiles). As a result, the other functionalities of Ketcher are throwing errors, so we wanted to hide them before showing Ketcher to the management.

**Comment by AndreiMazol** [comment]
@Doidel , thank  you for  the explanation.

Anyway, adding this functionality is in our plans. 
Please contact us if you have any questions or suggestions about further Ketcher enhancements.  We will be happy to take care about all your isssues.

Best regards,
Ketcher team
