### ISSUE TITLE
use ket format to render pictures

### ISSUE THREAD

**Issue by edgeTurbo** [epam/ketcher#1662]
I would like to ask how to use ket format to render and export pictures through indigo service，
indigo which method in can read ket format
thanks !

**Comment by AndreiMazol** [comment]
Dear @edgeTurbo ,

indigo methods can work with all Ketcher supported formats. To generate images based on ket/mol/etc please use the following code:

`await ketcher.generateImage(ket)` - to generate png (Blob object)
or
`await ketcher.generateImage(ket, {outputFormat: 'svg})` - to generate svg (Blob object).

Regards,
Ketcher team
