### ISSUE TITLE
Update position of stereo flag while structure is moved

### ISSUE THREAD

**Issue by Aniuta907** [epam/ketcher#167]
Background:
If there is a label added while stereo-configuration calculation it should be selected if a structure is selected to be able to perform editing operations (e.g. move or delete)

Acceptance Criteria:
If a canvas contains stereo-related labels (e.g. Mixed, AND Enantiomer, ABS Chiral)
If user selects a whole structure (or connected component) then the label should also be selected
In this case if user moves the structure component - the label will also be moved
if user selects a structure only partially, then the label should stay unselected

**Comment by AlexanderSavelyev** [comment]
**Background:**
If there is a label added while stereo-configuration calculation it should be selected if a structure is selected to be able to perform editing operations (e.g. move or delete)

**Acceptance Criteria:**
If a canvas contains stereo-related labels (e.g. Mixed, AND Enantiomer, ABS Chiral)
If user selects a whole structure (or connected component) then the label should also be selected
In this case if user moves the structure component - the label will also be moved
if user selects a structure only partially, then the label should stay unselected

**Comment by Svetlana-Asinovskaia** [comment]
Not fully implemented ACs:
If user selects a whole structure (or connected component) then the label should also be selected
In this case if user moves the structure component - the label will also be moved

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is verified and closed. Currently if a user selects a part of the structure and the stereo flag gets into selection, it's also highlighted in green. The user cannot delete the stereo flag, but he can move it with the part of the structure. It's possible to deselect the stereo flag manually.
