### ISSUE TITLE
cannot properly set up example and demo 

### ISSUE THREAD

**Issue by Eason51** [epam/ketcher#1677]
I executed "yarn install" in both demo and example directory, it seems there are dependency conflicts in both projects.

In demo, when I execute "yarn install", it gives the following ouput:

`➤ YN0000: ┌ Resolution step
➤ YN0002: │ @yarn-tool/resolve-package@npm:1.0.46 doesn't provide @types/node (pa74b7), requested by upath2
➤ YN0002: │ demo@workspace:demo doesn't provide @testing-library/dom (p83643), requested by @testing-library/user-event
➤ YN0060: │ demo@workspace:demo provides react (pb521a) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0060: │ demo@workspace:demo provides react-dom (p33a85) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [9ccad] doesn't provide @babel/plugin-syntax-flow (p66202), 
requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [9ccad] doesn't provide @babel/plugin-transform-react-jsx (p61b31), requested by eslint-plugin-flowtype
➤ YN0002: │ ketcher-core@workspace:packages/ketcher-core doesn't provide ts-node (pb1d71), requested by ttypescript
➤ YN0002: │ ketcher-react-app@workspace:example doesn't provide @testing-library/dom (p6c8ef), requested by @testing-library/user-event
➤ YN0060: │ ketcher-react-app@workspace:example provides react (p02122) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0060: │ ketcher-react-app@workspace:example provides react-dom (p76e91) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0002: │ ketcher-react-app@workspace:example doesn't provide webpack (pee762), requested by source-map-loader
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react doesn't provide @testing-library/dom (pf42c0), 
requested by @testing-library/user-event
➤ YN0060: │ ketcher-react@workspace:packages/ketcher-react provides draft-js (p19ef9) with version 0.11.7, which doesn't satisfy what draft-js-custom-styles requests
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react doesn't provide immutable (pf4223), requested by draft-js-custom-styles
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react doesn't provide prop-types (pce33f), requested 
by react-contextmenu
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react [7ff15] doesn't provide @testing-library/dom (p41bf8), requested by @testing-library/user-event
➤ YN0060: │ ketcher-react@workspace:packages/ketcher-react [7ff15] provides draft-js (p6476a) with version 0.11.7, which doesn't satisfy what draft-js-custom-styles requests
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react [7ff15] doesn't provide immutable (p3b060), requested by draft-js-custom-styles
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react [7ff15] doesn't provide prop-types (pbd167), requested by react-contextmenu
➤ YN0002: │ react-dev-utils@npm:12.0.1 doesn't provide typescript (p38bfa), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:12.0.1 doesn't provide webpack (p24433), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-scripts@npm:5.0.1 [7ff15] doesn't provide autoprefixer (p26619), requested by tailwindcss
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p436c2), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p77829), requested by @typescript-eslint/parser
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p6fe28), requested by eslint-config-prettier
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p2230f), requested by eslint-config-standard
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p2c9ca), requested by eslint-plugin-import
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p020b9), requested by eslint-plugin-node
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (pfab9a), requested by eslint-plugin-promise
➤ YN0060: │ root-workspace-0b6124@workspace:. provides prettier (pc5128) with version 2.6.0, which doesn't satisfy what prettier-config-standard requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 314ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 523ms
➤ YN0000: ┌ Link step
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The win32-x64 architecture is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 1s 436ms
➤ YN0000: Done with warnings in 2s 394ms
`

In example folder, when I execute "yarn install",  it generates the following output:

`➤ YN0000: ┌ Resolution step
➤ YN0002: │ @yarn-tool/resolve-package@npm:1.0.46 doesn't provide @types/node (pa74b7), requested by upath2
➤ YN0002: │ demo@workspace:demo doesn't provide @testing-library/dom (p83643), requested by @testing-library/user-event
➤ YN0060: │ demo@workspace:demo provides react (pb521a) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0060: │ demo@workspace:demo provides react-dom (p33a85) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [9ccad] doesn't provide @babel/plugin-syntax-flow (p66202), 
requested by eslint-plugin-flowtype
➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [9ccad] doesn't provide @babel/plugin-transform-react-jsx (p61b31), requested by eslint-plugin-flowtype
➤ YN0002: │ ketcher-core@workspace:packages/ketcher-core doesn't provide ts-node (pb1d71), requested by ttypescript
➤ YN0002: │ ketcher-react-app@workspace:example doesn't provide @testing-library/dom (p6c8ef), requested by @testing-library/user-event
➤ YN0060: │ ketcher-react-app@workspace:example provides react (p02122) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0060: │ ketcher-react-app@workspace:example provides react-dom (p76e91) with version 17.0.2, which doesn't satisfy what ketcher-react and some of its descendants request
➤ YN0002: │ ketcher-react-app@workspace:example doesn't provide webpack (pee762), requested by source-map-loader
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react doesn't provide @testing-library/dom (pf42c0), 
requested by @testing-library/user-event
➤ YN0060: │ ketcher-react@workspace:packages/ketcher-react provides draft-js (p19ef9) with version 0.11.7, which doesn't satisfy what draft-js-custom-styles requests
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react doesn't provide immutable (pf4223), requested by draft-js-custom-styles
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react doesn't provide prop-types (pce33f), requested 
by react-contextmenu
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react [7ff15] doesn't provide @testing-library/dom (p41bf8), requested by @testing-library/user-event
➤ YN0060: │ ketcher-react@workspace:packages/ketcher-react [7ff15] provides draft-js (p6476a) with version 0.11.7, which doesn't satisfy what draft-js-custom-styles requests
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react [7ff15] doesn't provide immutable (p3b060), requested by draft-js-custom-styles
➤ YN0002: │ ketcher-react@workspace:packages/ketcher-react [7ff15] doesn't provide prop-types (pbd167), requested by react-contextmenu
➤ YN0002: │ react-dev-utils@npm:12.0.1 doesn't provide typescript (p38bfa), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:12.0.1 doesn't provide webpack (p24433), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-scripts@npm:5.0.1 [7ff15] doesn't provide autoprefixer (p26619), requested by tailwindcss
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p436c2), requested by @typescript-eslint/eslint-plugin
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p77829), requested by @typescript-eslint/parser
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p6fe28), requested by eslint-config-prettier
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p2230f), requested by eslint-config-standard
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p2c9ca), requested by eslint-plugin-import
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (p020b9), requested by eslint-plugin-node
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide eslint (pfab9a), requested by eslint-plugin-promise
➤ YN0060: │ root-workspace-0b6124@workspace:. provides prettier (pc5128) with version 2.6.0, which doesn't satisfy what prettier-config-standard requests
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 308ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 518ms
➤ YN0000: ┌ Link step
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The win32-x64 architecture is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 1s 472ms
➤ YN0000: Done with warnings in 2s 416ms`

**Comment by Mariia-Katkova** [comment]
Hello [Eason51](https://github.com/Eason51), 

can you please specify if you have any problems with starting the project? If so, what version of ketcher do you use?

**Comment by Eason51** [comment]
> Hello [Eason51](https://github.com/Eason51),
> 
> can you please specify if you have any problems with starting the project? If so, what version of ketcher do you use?

when I cd into the example/demo folder, 

type the following command "npm install --save ketcher-react", it outputs an error message "Unsupported URL Type "workspace:": workspace:*"

Then I tried "npm install --save ketcher-react -g npm@7" and "yarn add ketcher-react" respectively, there seems to be no errors, only regular warnings. But the package "ketcher-react" is still missing, I cannot import from it. Same scenario happens with "ketcher-core" and "ketcher-standalone"

**Comment by Yuting918** [comment]
@Mariia-Katkova 
Hello,
Same thing happen to me as well.

**Comment by Mariia-Katkova** [comment]
@Eason51, @Yuting918 can you please run `yarn build` in root folder and then notify if the problem remains?

**Comment by Yuting918** [comment]
@Mariia-Katkova 
Thank you for the reply, when I run `yarn build` from the root folder (ketcher) I got the following:
```
 yarn build
➤ YN0000: [ketcher-core]: Process started
➤ YN0000: [ketcher-polymer-editor-react]: Process started
➤ YN0000: [ketcher-core]: 
➤ YN0000: [ketcher-core]: src/index.ts → dist/index.js, dist/index.modern.js...
➤ YN0000: [ketcher-core]: (!) Circular dependencies
➤ YN0000: [ketcher-core]: src/application/editor/index.ts -> src/application/editor/actions/index.ts -> src/application/editor/actions/atom.ts -> src/application/editor/actions/sgroup.ts -> src/application/editor/index.ts
➤ YN0000: [ketcher-core]: src/application/editor/actions/atom.ts -> src/application/editor/actions/sgroup.ts -> src/application/editor/actions/atom.ts
➤ YN0000: [ketcher-core]: src/application/editor/actions/atom.ts -> src/application/editor/actions/bond.ts -> src/application/editor/actions/atom.ts
➤ YN0000: [ketcher-core]: created dist/index.js, dist/index.modern.js in 35.2s
➤ YN0000: [ketcher-core]: Process exited (exit code 0), completed in 37s 147ms
➤ YN0000: [ketcher-polymer-editor-react]: 
➤ YN0000: [ketcher-polymer-editor-react]: src/index.tsx → dist/index.js, dist/index.modern.js...
➤ YN0000: [ketcher-polymer-editor-react]: (!) Circular dependency
➤ YN0000: [ketcher-polymer-editor-react]: src/state/common/index.ts -> src/state/common/editorSaga.ts -> src/state/common/index.ts
➤ YN0000: [ketcher-polymer-editor-react]: created dist/index.js, dist/index.modern.js in 38.3s
➤ YN0000: [ketcher-polymer-editor-react]: Process exited (exit code 0), completed in 41s 919ms
➤ YN0000: [ketcher-react]: Process started
➤ YN0000: [ketcher-standalone]: Process started
➤ YN0000: [ketcher-standalone]: 
➤ YN0000: [ketcher-standalone]: src/index.ts → dist/index.js, dist/index.modern.js...
➤ YN0000: [ketcher-standalone]: created dist/index.js, dist/index.modern.js in 9.9s
➤ YN0000: [ketcher-standalone]: Process exited (exit code 0), completed in 11s 896ms
➤ YN0000: [ketcher-react]: 
➤ YN0000: [ketcher-react]: src/index.tsx → dist/index.js, dist/index.modern.js...
➤ YN0000: [ketcher-react]: (!) Plugin postcss: Autoplacement does not work without grid-template-rows property
➤ YN0000: [ketcher-react]: src/script/ui/App/App.module.less
➤ YN0000: [ketcher-react]: src/script/ui/dialog/template/TemplateTable.module.less
➤ YN0000: [ketcher-react]: src/script/ui/views/modal/components/process/Recognize/Recognize.module.less
➤ YN0000: [ketcher-react]: src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenericGroups.module.less
➤ YN0000: [ketcher-react]: src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenericGroups.module.less
➤ YN0000: [ketcher-react]: src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenGroup.module.less
➤ YN0000: [ketcher-react]: src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenGroup.module.less
➤ YN0000: [ketcher-react]: (!) Plugin postcss: grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
➤ YN0000: [ketcher-react]: src/script/ui/dialog/template/TemplateTable.module.less
➤ YN0000: [ketcher-react]: (!) Plugin postcss: grid-auto-rows is not supported by IE
➤ YN0000: [ketcher-react]: src/script/ui/dialog/template/TemplateTable.module.less
➤ YN0000: [ketcher-react]: src/script/ui/dialog/template/TemplateTable.module.less
➤ YN0000: [ketcher-react]: (!) Circular dependencies
➤ YN0000: [ketcher-react]: src/script/editor/tool/select.ts -> src/script/editor/tool/sgroup.ts -> src/script/editor/tool/select.ts
➤ YN0000: [ketcher-react]: src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/index.ts -> src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/GenericGroups.tsx -> src/script/ui/views/modal/components/ExtendedTable/components/GenericGroups/index.ts
➤ YN0000: [ketcher-react]: created dist/index.js, dist/index.modern.js in 52.1s
➤ YN0000: [ketcher-react]: Process exited (exit code 0), completed in 55s 957ms
➤ YN0000: [ketcher-react-app]: Process started

```
Is this as designed?

**Comment by Mariia-Katkova** [comment]
@Yuting918 please try `yarn start:remote` or `yarn start:standalone` in example folder

**Comment by Yuting918** [comment]
@Mariia-Katkova -- It is working now. Thank you! 
One more question, does the source code stored in the example folder or does the example folder actually trying to calling from the root ketcher folder?
I am trying to edit some portion of the source code but a little confused about the set up. Thanks!!

**Comment by evgeniiFrolov1** [comment]
Hello @Yuting918,

let me clarify a bit
The source code is stored in separate packages as `ketcher-core`, `ketcher-react` etc. 
The `example` folder is linked to the @ketcher/react package in the parent directory for development purposes.

More info  [here](https://github.com/epam/ketcher/blob/master/DEVNOTES.md)

Thanks :)
