### ISSUE TITLE
Upgrade to React 18 and replace react-contextmenu with react-contexify

### ISSUE THREAD

**Issue by 4-life** [epam/ketcher#1681]
**Is your feature request related to a problem? Please describe.**
I've got a message in console:

`react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17`

**Describe the solution you'd like**
Update ketcher to React 18

**Comment by luna215** [comment]
Is there a timeline for this?

**Comment by evgeniiFrolov1** [comment]
@luna215  Hello there :)
We are going to update Ketcher to React 18 next release.
Probably, in the end of December

**Comment by luna215** [comment]
@neo Are you trying to integrate Ketcher onto an existing React app?

**Comment by MichelML** [comment]
thanks for the update @evgeniiFrolov1 , our team would also need this :pray:

**Comment by neo** [comment]
> @neo Are you trying to integrate Ketcher onto an existing React app?

yes @luna215, is this not a designed use case? (cc @evgeniiFrolov1)

**Comment by luna215** [comment]
@neo not sure, I am not part of the contributors, but I did manage to setup Ketcher with an existing react 18 project. Happy to help here

**Comment by bearmit** [comment]
> @neo not sure, I am not part of the contributors, but I did manage to setup Ketcher with an existing react 18 project. Happy to help here

Hello @luna215, I am interested to know about your setup with an existing react 18 project. At work we have the same use case. Can you share a link to your code? Was it long to upgrade ? 
Thanks.
