### ISSUE TITLE
Elements styles are overwriting other styles

### ISSUE THREAD

**Issue by MariaDolotova** [epam/ketcher#1694]
Hi! My name is Maria and I'm working on integrating Ketcher into cheminformatcs package used on Datagrok analytical platform.
And the problem is the following: in Ketcher some styles are set on elements like 'input'. 
And when Ketcher is built in Datagrok UI those styles affect all input elements.
![image](https://user-images.githubusercontent.com/44060410/184816710-0264e9cb-e12f-4656-85ff-3509388c3607.png)
Is it possible to use styles not on the elements them selfs but using classes?

**Comment by skalkin** [comment]
@evgeniiFrolov1 , thanks for looking at it! Just FYI, this is the only issue that prevents us from using Ketcher as one of the supported sketchers for Datagrok

https://www.youtube.com/watch?v=k1NVdTRpYOM&ab_channel=Datagrok
