### ISSUE TITLE
Returning incorrect smarts

### ISSUE THREAD

**Issue by MariaDolotova** [epam/ketcher#1695]
**Steps to Reproduce**
1. Create Ketcher class
2. Set the following smarts `[!#6&!#7]1:[#6]:[#6]:[#6]:[#6]:[#6]:1` using setMolecule() method.
3. Get smarts using getSmarts() method

**Expected behavior**
Expect to get `[!#6&!#7]1:[#6]:[#6]:[#6]:[#6]:[#6]:1`

**Actual behavior**
Getting `[!#6,!#7]1:[#6]:[#6]:[#6]:[#6]:[#6]:1`(comma is OR operator while we need AND operator - &)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome version 104.0.5112.81

**Ketcher version**
"ketcher-core": "^1.5.0",
"ketcher-react": "^2.5.1",
"ketcher-standalone": "^1.4.0",

**Comment by MariaDolotova** [comment]
Hello!
I still get an error on the follwing versions of Ketcher:
Ketcher version
"ketcher-core": "^2.9.0",
"ketcher-react": "^2.9.0",
"ketcher-standalone": "^2.9.0"

But the returned structure ahs changed: I set `[!#6&!#7]1:[#6]:[#6]:[#6]:[#6]:[#6]:1` but get `[#6](-[#7]-[#6])(=[#8])-[#7]-[#6]`.
@evgeniiFrolov1 , @Nitvex , can you please take a look?

**Comment by skalkin** [comment]
@Nitvex , @evgeniiFrolov1 - just wondering if there's any update on it? Ketcher is a cool sketcher but silly issues like that prevent us from giving it to our users :(

**Comment by Zhirnoff** [comment]
@skalkin Hello! Thank you for using Ketcher and highlighting this problem for us. I checked this on https://lifescience.opensource.epam.com/KetcherDemoSA/index.html in version 2.15 and now SMARTS without comma is returned.
![2024-01-30_15h07_16](https://github.com/epam/ketcher/assets/62464241/c23887db-f18f-4f38-be03-906de2afcc48)

**Comment by Zhirnoff** [comment]
@skalkin Recently, we have put significant effort into SMARTS. If you notice any bugs, we would greatly appreciate your feedback.

**Comment by skalkin** [comment]
@Zhirnoff thanks a lot! We'll give Ketcher another try, and will surely share the feedback.
@MariaDolotova FYI

**Comment by Zhirnoff** [comment]
Bug is not reproduced in Prod Version 2.15.0

**Comment by MariaDolotova** [comment]
Hi @Zhirnoff ! thank you very much for the update. I'm now testing setting of smarts to Ketcher. But when I call setMolecule method with the following smarts: "[!#6&!#7]1:[#6]:[#6]:[#6]:[#6]:[#6]:1" I get an error:

**Comment by Zhirnoff** [comment]
@MariaDolotova I use command in DevTool Console: ketcher.setMolecule ('[!#6&!#7]1:[#6]:[#6]:[#6]:[#6]:[#6]:1')
![2024-01-30_19h49_06](https://github.com/epam/ketcher/assets/62464241/4fc2b4f1-f31f-41f6-8f67-434d4e6c0050)

**Comment by Zhirnoff** [comment]
@MariaDolotova We are providing some information about the API from our knowledge base:
[EPMLSOP-Ketcher'sAPI-300124-1810-2348.pdf](https://github.com/epam/ketcher/files/14102582/EPMLSOP-Ketcher.sAPI-300124-1810-2348.pdf)

**Comment by MariaDolotova** [comment]
@Zhirnoff , thank you, the problem was fixed.

**Comment by Zhirnoff** [comment]
@MariaDolotova You're welcome! I'm glad to hear that the problem has been resolved. If you have any further questions or issues, feel free to ask.
