### ISSUE TITLE
SVG file is not shown in Remote

### ISSUE THREAD

**Issue by dariasviridova** [epam/ketcher#1701]
**Steps to Reproduce**
1. Create molecule/reaction on canvas
2. Click on 'Save' button or use shortcut Ctr+C
3. Choose 'SVG' file format

**Expected behavior**
Preview picture of the molecule/reaction is shown in Preview tab.
User is able to save SVG picture.

**Actual behavior**
Preview picture of the molecule/reaction is not shown in Preview tab.
User cannot save SVG picture.

**Screenshots**

<img width="329" alt="2022-08-26_15h53_08" src="https://user-images.githubusercontent.com/110118107/186908934-31b330d9-2185-4aa2-ac24-6b8b629508a1.png">

**Desktop**
 - OS: Windows
 - Browser microsoft edge

**Ketcher version** 
v2.5.0 Remote

**Additional context**
Other features that require backend (such as aromatization/dearomatization) work correctly.

**Comment by LadaYudovina** [comment]
Hi! I check this on the last front version "2.5.2" and back indigo version "1.7.0.44-gd16d27b64-x86_64-linux-gnu-11.2.1" from the last "release 2.5" branch and it doesn't reproduce.

**Comment by porcelain11** [comment]
Checked through Postman:

**https://apin.test.lifescience.opensource.epam.com/**,
**https://api.lifescience.opensource.epam.com/** - works fine (result - 200 OK),

**https://lifescience.opensource.epam.com/** - result - error 500 (screenshot attached)
<img width="1440" alt="Screenshot 2022-09-05 at 16 56 23" src="https://user-images.githubusercontent.com/112183450/188446987-42fa61f4-33b9-478b-a8b0-1eedd093463c.png">

**Comment by porcelain11** [comment]
Postman collection attached
[Indigo_render_img.postman_collection.json.zip](https://github.com/epam/ketcher/files/9497358/Indigo_render_img.postman_collection.json.zip)
