### ISSUE TITLE
Support CDXML

### ISSUE THREAD

**Issue by dariasviridova** [epam/ketcher#1710]
AS A Ketcher User
I WANT TO have an ability to save/upload in CDXML format
SO THAT I can more easily communicate and work with other apps 

Acceptance criteria:
1. Ketcher shall support CDXML format.

| # | User         | Given                                                    | When                                                                                          | Then                                                                   |
|---|--------------|----------------------------------------------------------|-----------------------------------------------------------------------------------------------|------------------------------------------------------------------------|
| 1 | Ketcher User | Ketcher is opened<br>AND User added something on canvas  | User clicks 'Save' button or shortcut Ctr+C<br>AND opens file format dropdown                 | CDXML is present in file format dropdown                               |
| 2 |              |                                                          | no 1<br>AND User chooses CDXML                                                                | CDXML format is shown in Preview tab according to CDXML specification  |
| 3 |              |                                                          | no 2<br>AND User clicks 'Save' button                                                         | File in CDXML format is saved                                          |
| 4 | Ketcher User | User opened 'Open from structure' window                 | User clicks 'Paste from clipboard' button <br>AND pastes from clipboard file in  CDXML format | System show structures from CDXML on canvas according to specification |
| 5 | Ketcher User | User opened 'Open from structure' window                 | User clicks 'Open from file' button <br>AND chooses file in CDXML format                      | System show structures from CDXML on canvas according to specification |

   Features that shall be supported by CDXML: tbd

**Comment by Nitvex** [comment]
https://github.com/epam/Indigo/issues/862
