### ISSUE TITLE
ketcher/example doc (or code) is broken

### ISSUE THREAD

**Issue by scottschafer** [epam/ketcher#1717]
**Steps to Reproduce**
The README.md in ketcher/example says: "You can run `yarn install` and then `yarn start` to test your package."

But this doesn't work, because there is no `yarn start`.

I tried using `yarn start:standalone` instead, but this fails with runtime errors.

**Expected behavior**
Example project should work using the provided steps.

**Actual behavior**
Example project does not work using the provided steps.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Ketcher version** [e.g. v2.4.2-115-gcf0c1394]. 
To determine it, hover over the header of the Ketcher tab in a browser. 

**Additional context**

**Comment by evgeniiFrolov1** [comment]
@scottschafer thx for your input
