### ISSUE TITLE
addFragment() is not implemented

### ISSUE THREAD

**Issue by scottschafer** [epam/ketcher#1722]
**Steps to Reproduce**
Call ketcher.addFragment('c1ccccc1')

**Expected behavior**
Fragment is inserted.

**Actual behavior**
"not implemented yet" error is thrown.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Ketcher version** [e.g. v2.4.2-115-gcf0c1394]. 
To determine it, hover over the header of the Ketcher tab in a browser. 

**Additional context**

**Comment by MPatdugroup** [comment]
1. Currently it doesn’t work as existing code is using the `ketcher.addFragment()` method which is not implemented in Ketcher itself.
Error screenshot:

![image](https://user-images.githubusercontent.com/111969884/190392834-7bf4d613-58e5-4d4d-8ef3-95d5d163e196.png)
