### ISSUE TITLE
Can't save as a rxn file if reaction consists of two or more reaction arrows

### ISSUE THREAD

**Issue by MPatdugroup** [epam/ketcher#1736]
Steps to Reproduce
1. Open Ketcher v2.5.0
2. Add a reaction with multiple (more than one reaction arrow) as shown in the image
3. Try to save the file in rxn format

Expected behavior
The reaction must be saved in rxn file format even when there are multiple reaction arrows

Actual behavior
The option to save the reaction in rxn file format goes missing as soon as the second reaction arrow is added.

Screenshots
![image](https://user-images.githubusercontent.com/111969884/191951613-f130dc46-6494-45ce-bf3f-196eb2462d29.png)
![image](https://user-images.githubusercontent.com/111969884/191952025-03bcc33f-57e1-43d8-b5e0-9f62f07b98a5.png)

Desktop
OS: Windows 10
Browser Google Chrome
Version Version 104.0.5112.102 (Official Build) (64-bit)
Version: Ketcher v2.5.0

Additional context
The issue is not experienced when the chemical reaction consists of one reaction arrow.

**Comment by Zhirnoff** [comment]
(RXN files) One of the arrows and structure is missing when "Past from clipboard" or "Open from file" if reaction consists of two or more reaction arrows and structures. https://github.com/epam/Indigo/issues/870

**Comment by MPatdugroup** [comment]
@evgeniiFrolov1 Thank you for the fix. What is the tentative release date of Ketcher 2.6.0 ?
