### ISSUE TITLE
User can't copy/cut and paste part of structure or structure with SRU-polymer S-Group.

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#177]
**Preconditions:**

- Chain structure with head-to-head and either unknown patterns of SRU-polymer S-Groups is already created.

**Steps to Reproduce:**

1. With "Selection" tool select whole structure.
2. Press ctrl+C and then ctrl+v.
3. With "Selection" tool select part of structure with SRU-polymer S-Group.
4. Press ctrl+x.
5. Press crtl+v.

**Expected Result:**
p.2 - Whole structure is pasted and shows on canvas.
p.4 - Part of structure with SRU-polymer is cutted, p.5 - cut out part of structure is pasted and shows on canvas separately.

**Actual Result:**
Structures with SRU-polymers are not copied and cut out. User can't save it to the clipboard and then paste it.

**Comment by AndreiMazol** [comment]
Cannot reproduce any more

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed. Now when User try to copy or cut incorrect Structure with SRU-polymer group at the end of Structure - warning message appears.
