### ISSUE TITLE
When saving in PNG and SVG format molecules lose color (Ketcher Standalone)

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1795]
**Steps to Reproduce**
1. Launch Ketcher Standalone
2. Create any structure and add any text or use [ketcher (16).zip](https://github.com/epam/ketcher/files/9919414/ketcher.16.zip)
3. Save it in PNG and SVG format
4. Open saved files

**Expected behavior**
Molecules don't lose color

**Actual behavior**
Molecules lose color

**Screenshots**

![2022-10-27_22h33_35](https://user-images.githubusercontent.com/62464241/198382030-57db15da-21cb-4af1-9295-f02ae8bebf44.png)
![2022-10-27_22h33_45](https://user-images.githubusercontent.com/62464241/198382036-604fce6a-4293-4856-8337-32cfddd70685.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Ketcher version** [Version 2.6.0-rc.3]
Build at 2022-10-27; 18:01:49
Indigo related issue: https://github.com/epam/Indigo/issues/888

**Comment by AlexanderSavelyev** [comment]
use render-coloring = True for the rendering inside indigo

**Comment by Nitvex** [comment]
Indigo effort is not required. Issue will be fixed on Ketcher side
