### ISSUE TITLE
project still maintained?

### ISSUE THREAD

**Issue by MichelML** [epam/ketcher#18]
Planning on using this in a potentially commercial app, any insights before I proceed? 

Thanks in advance.

Last release was in 2018, so checking up.

**Comment by MichelML** [comment]
@Vesdet @johnmay quick reply would be appreciated, thanks!

**Comment by johnmay** [comment]
I don’t have any affiliation with the project so not sure why you looped me in. It works, it’s open source - if you want changes or fixes you can submit them or perhaps pay Epam some consultancy.

**Comment by AlexanderSavelyev** [comment]
Dear @MichelML, the Ketcher is maintained as open-source project. The current version is stable and the support is provided for security and infrastructure issues and bugs. But we have plans to improve the project and include new features in future
