### ISSUE TITLE
If User create simple molecule on canvas when it is minimum zoom value - molecule have increased distance between atoms.

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#180]
**Steps to Reproduce:**
1. Choose "N" (as example) from the right toolbar.
2. Click on canvas.
3. Minimize zoom to 20% value.
4. Click on canvas.
5. Maximize zoom to 100% value.

**Expected Result:**
Both molecules display identically.

**Actual Result:**
Molecule that was created in minimum zoom has larger distance between atoms.
![Screenshot 2020-12-16 162152](https://user-images.githubusercontent.com/75974465/102353935-dc742c00-3fba-11eb-9997-daa2a05597b1.jpg)

**Comment by vitalgerko** [comment]
All is well in Edge
![Edge](https://user-images.githubusercontent.com/90637536/133742495-b92c0360-1884-4587-a124-eefe9a5490a8.png)

The problem of overlap in IE 
![IE](https://user-images.githubusercontent.com/90637536/133742535-1a87a392-182f-46a4-aceb-ed571bf6e736.png)
 
There is a small difference in Chrome
![Chrome](https://user-images.githubusercontent.com/90637536/133743288-56fd1877-811a-4ee1-b20d-8301c723b5c6.png)

There is a small difference in Firefox
![Firefox](https://user-images.githubusercontent.com/90637536/133742914-9847b720-3a11-42a4-9747-7dccf0e399ae.png)

@AndreiMazol  but on Elena's @ElenaOdnoshivkina  computer in Chrome, there is no such distance difference. What are we doing with this bug?

**Comment by ElenaOdnoshivkina** [comment]
Changing the scale of display, which we set in the os, impact changes the font size in the browser. The font size impacts the margins from the element and the distance between the molecules. For this reason, I cannot tune this parameter for different zoom modes in the os.

**Comment by vitalgerko** [comment]
Decided not to spend a lot of time solving the problem.
It looks much better сompared to the previous version

Release/2.4 Closed as fixed.
