### ISSUE TITLE
Pasting Molfile with stereo creates AND group

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1805]
**Steps to Reproduce**
1. Launch Ketcher
2. Copy data from [cipbug.zip](https://github.com/epam/ketcher/files/9904164/cipbug.zip)
3. Press 'Open structure' button, click 'Paste from Clipboard' and paste data
4. Click 'Add to Canvas' button

**Expected behavior**
Labels the molecule as having absolute chirality.

**Actual behavior**
When Pasting the molfile, it creates a single "AND" group for the one stereocentre.

**Screenshots**
![2022-10-31_22h22_03](https://user-images.githubusercontent.com/62464241/199092221-17c1e538-fe9e-4458-ade5-217b9e056a39.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 107.0.5304.88 (Official Build) (64-bit)

**Ketcher version** [Version 2.6.0-rc.3]
Build at 2022-10-27; 18:01:49

**Additional context**
![2022-10-31_22h25_57](https://user-images.githubusercontent.com/62464241/199092795-9fd1ca8e-a521-4be8-8bbe-ad5ab212686e.png)

See attached Molfile: opening Ketcher and setting the molfile through the API function works normally, i.e. labels the molecule as having absolute chirality.

But when Pasting the molfile, it creates a single "AND" group for the one stereocentre. This is undesirable, as this extra functionally triggers logic to export the structure as a V3000 molfile, when it is a very simple molecule which can be easily represented using V2000.
Presumably it's a difference between Indigo and Ketcher.
![2022-10-31_22h27_03](https://user-images.githubusercontent.com/62464241/199092976-0d7823e2-89ed-419f-a1db-bb3fec72e5b1.png)
[cipbug2.zip](https://github.com/epam/ketcher/files/9904203/cipbug2.zip)
![2022-10-31_22h28_55](https://user-images.githubusercontent.com/62464241/199093375-813ac30e-7410-42fb-9b45-98e4749cb420.png)

**Comment by AlexanderSavelyev** [comment]
Issue can be closed, because input molfiles contains chiral flag = 0, which means that input structure is AND Enantiomer
