### ISSUE TITLE
Show underlying structure on mouse hover for functional groups and salts&solvents

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#1824]
**Is your feature request related to a problem? Please describe.**
Right now user need to expand structure to understand what is expanded view of the functional group

**Describe the solution you'd like**
User mouse over a functional group (salts and solvents in future) and ketcher shows a structure for the selected functional group. The structure should be displayed as a rectangle below the pointer with white background

![image](https://user-images.githubusercontent.com/7427808/200862858-325ce963-940d-4c2f-ac31-c03024e05cf8.png)

**Comment by vanoprenko** [comment]
Please use current design for displaying a functional group on hover:

![image](https://user-images.githubusercontent.com/18439849/204522613-33464025-b970-4725-87d9-b5ce3ad4f84e.png)

**Comment by KonstantinEpam23** [comment]
The hover effect should be delayed by 500ms
