### ISSUE TITLE
Support for V3000 and large structures

### ISSUE THREAD

**Issue by ValeryPolyakov** [epam/ketcher#183]
Do you have support for V3000 and structures larger then 999 atoms?

**Comment by vanoprenko** [comment]
We do have support for V3000. 
As for big molecules, it is on our road map. There are no restrictions on the number of atoms at the moment but big molecules won't work well enough.

**Comment by ValeryPolyakov** [comment]
Thanks, but how do I save a drawing in V3000 format?

**Comment by AlexanderSavelyev** [comment]
Yes, currently Ketcher supports only loading from V3000. We have added a task to add the V3000 to the save options #190 
indigo-service (backend) supports V3000, so the task should be straight forward to implement.
As for the format itself, there are several tasks in the road map: enhanced stereo support #56 and large molecules support which will require some updates for the rendering library.

**Comment by ValeryPolyakov** [comment]
Thanks. I am looking forward to seeing these new features.

**Comment by ValeryPolyakov** [comment]
Hi Andrei,

Your deme still does not allow me to save structures with over 999 atoms
and there is no V3000 in the pull down menu

https://lifescience.opensource.epam.com/ketcher/demo.html
