### ISSUE TITLE
RXN files: structure is missing when "Paste from clipboard" or "Open from file" if reaction consists of two or more reaction arrows and structures.

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1837]
**Steps to Reproduce**
1. Open Ketcher v2.5.2
2. Add a reaction with multiple (more than one reaction arrow) as shown in the image
3. Save file in MDL Rxnfile V2000 and MDL Rxnfile V3000
4. Paste files from clipboard or open saved files from saved directory.

**Expected behavior**
Structure is correctly opens from saved files. Keep only first reaction arrow and keep all structures (all intermediate structures should be products and the arrow is replaced by a plus)

**Actual behavior**
In MDL Rxnfile V2000 the arrow disappears, and when opening MDL Rxnfile V3000 the arrow and structure disappear

**Attachments**
![2022-10-07_14h54_14](https://user-images.githubusercontent.com/62464241/194911769-195438fa-36fe-46bb-95d2-cf00784415e5.png)

**Indigo/Bingo version**  
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.7.4.0-g86f1ef175-x86_64-linux-gnu-11.2.1

**Additional context**
Indigo issue: https://github.com/epam/Indigo/issues/870

**Comment by vitaepam** [comment]
While writing test in this task https://github.com/epam/ketcher/issues/3181 found out like it's reproducing again
At least for V2000 RXN files
<img width="1440" alt="Screenshot 2023-09-04 at 10 16 33" src="https://github.com/epam/ketcher/assets/109075831/3cd072e1-1d0f-47bc-ae9d-da8004266ec4">
