### ISSUE TITLE
Warning message is not shown when trying to save a reaction with R-group members as .rxn file

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/ketcher#185]
**Description:**
When a user saves a reaction with R-group members as rxn.file, the warning message "ERROR: Unable to save the structure - reactions with R-Groups are not supported at the moment" is not shown and the reaction is not saved.

**Steps to reproduce:**
1. Create a reaction.
2. Create a structure.
3. Define the structure as R-Group member (R1).
4. Click "Save As..." button.

**Actual result:**
When clicking "Save As..." button, the reaction is not saved. 
"ERROR: Unable to save the structure - reactions with R-Groups are not supported at the moment" message is not shown. 

![2020-12-17_01h10_48](https://user-images.githubusercontent.com/75974843/102412778-fcc8d880-4004-11eb-8198-376a737e4b15.gif)

**Expected result:**
"ERROR: Unable to save the structure - reactions with R-Groups are not supported at the moment" message is shown when clicking "Save As..." button.

**Comment by AndreiMazol** [comment]
It has been already fixed

**Comment by ElenaKlepova** [comment]
**Status:** _PASS_
**Build:** _Release 2.1_
**OS/Browser:** Win10/Chrome

**Actual result:**
'Reactions with r-groups are not supported at the moment' message is shown when clicking "Save As..." button.
![2020-12-30_16h15_48](https://user-images.githubusercontent.com/75974843/103353703-8b842d80-4aba-11eb-83f4-be787ffd63c2.png)
