### ISSUE TITLE
Warning message doesn't appears for InChi files

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#186]
**Steps to Reproduce:**
1. Put the benzene templates on the canvas. 
2. Add the reaction arrow between them.
3. Click the Save As button or Ctrl+S. 
4. Choose the InChi format for saving.

**Expected Result:**
Input field in "Save As..." modal window contains the ERROR: "core: <reaction> is not a molecule".

**Actual Result:**
If User clicks on InChi format dropdown list stays on MDL rxnfile, in console there is API error POST 400 (Bad Request).
In Network tab there is required message, but it is not displays for User.
![1](https://user-images.githubusercontent.com/75974465/102466585-40046500-4060-11eb-9822-9986803e1d39.jpg)
![2](https://user-images.githubusercontent.com/75974465/102466592-42ff5580-4060-11eb-8beb-a8793a8b030d.jpg)

**Comment by AndreiMazol** [comment]
It has been already fixed

**Comment by KseniiaSemenishcheva** [comment]
Issue is closed as fixed. 
![Screenshot 2020-12-31 110838](https://user-images.githubusercontent.com/75974465/103401062-8d9cc980-4b58-11eb-8b2c-c32628c2cfbd.jpg)
