### ISSUE TITLE
When User open .mol file with R-Group and then try to save it - blank page appears

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#187]
**Steps to Reproduce:**
1. Create structure with R-Groups like in example:
![Screenshot 2020-12-17 145336](https://user-images.githubusercontent.com/75974465/102484740-bc567280-4077-11eb-9396-5b494f897c45.jpg)
2. Click "Save As..." and save as .mol file "Rgroup.mol".
3. Clean canvas.
4. Open "Rgroup.mol" in Ketcher. [Rgroup.zip](https://github.com/epam/ketcher/files/5750666/Rgroup.zip)
5. Click "Save As..." button.

**Expected Result:**
"Save As.." modal window appears.

**Actual Result:**
Blank page and error in console appear:
![Screenshot 2020-12-17 134854](https://user-images.githubusercontent.com/75974465/102486793-a5fde600-407a-11eb-959a-9586593a027e.jpg)

**Comment by AndreiMazol** [comment]
@KseniiaSemenishcheva  I cannot reproduce the issue. 

[rgroup_187.zip](https://github.com/epam/ketcher/files/5747862/rgroup_187.zip) has been used for testing.

**Comment by KseniiaSemenishcheva** [comment]
Issue is closed as fixed.
