### ISSUE TITLE
Does the current core support vue

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [epam/ketcher#1876]
Does the current core support vue？please, help me

**Comment by asnipera** [comment]
you can use ketcher by iframe  in vue project

**Comment by wojiaoxiaomayun** [comment]
@asnipera thanks for you,if I want to get the saved data,What should I do?

**Comment by asnipera** [comment]
ketcherFrameDomObj.ketcher.getMolfile()

**Comment by wojiaoxiaomayun** [comment]
> 

谢谢，我试下，我看您这边苏州。。。我就不翻译英语了，哈哈

**Comment by wojiaoxiaomayun** [comment]
> ketcherFrameDomObj.ketcher.getMolfile()
谢谢，我先试下，我看您这边苏州的，我就不翻译了，哈哈

**Comment by wojiaoxiaomayun** [comment]
@asnipera 大佬，有没有那种稍微一丢丢的操作文档，比如我要把保存的数据再渲染出来，就是那api文档，或者指导小弟去哪个文件里面找api方便一点，跪拜大佬

**Comment by asnipera** [comment]
1:   [ketcher api](https://github.com/epam/ketcher/blob/master/packages/ketcher-core/src/application/ketcher.ts)
2:  `npm run serve:demo`

render canvas by `ketcherFrameDomObj.ketcher.setMolecule()`

**Comment by wojiaoxiaomayun** [comment]
多谢大哥

> 1：[凯彻 API](https://github.com/epam/ketcher/blob/master/packages/ketcher-core/src/application/ketcher.ts) 2：`npm run serve:demo`
> 
> 渲染画布`ketcherFrameDomObj.ketcher.setMolecule()`

**Comment by asnipera** [comment]
view `ketcher api` by console (https://lifescience.opensource.epam.com/KetcherDemo/index.html?api_path=/v2 )

![image](https://user-images.githubusercontent.com/111938122/204728238-4716ae6b-3676-4ddc-8e2c-59e5d569b6c9.png)

**Comment by wojiaoxiaomayun** [comment]
@asnipera 哥哥有没有汉化菜单的建议？

**Comment by asnipera** [comment]
修改title，然后build
![image](https://user-images.githubusercontent.com/111938122/204746675-451993eb-55bf-4d46-a105-13656f1d0dbf.png)

**Comment by wojiaoxiaomayun** [comment]
意思是我修改完源码然后重新build成静态页面然后iframe引用？

**Comment by asnipera** [comment]
是的

**Comment by wojiaoxiaomayun** [comment]
多谢大哥，看的出来大哥对这个研究的已经很透彻了 @asnipera

**Comment by Nitvex** [comment]
@wojiaoxiaomayun, is your question answered?
If so, I'll close the issue.
And for future, could you please English language?

**Comment by wojiaoxiaomayun** [comment]
@Nitvex  yes,my question is over.If I have the next question, I will use English，thank you

**Comment by wojiaoxiaomayun** [comment]
> > @Nitvex yes,my question is over.If I have the next question, I will use English，thank you是的，我的问题结束了。如果我有下一个问题，我会用英语，谢谢
> 
> > 意思是我修改完源码然后重新build成静态页面然后iframe引用？
> 
> Which package did you modify? ketcher-core?

I didn't make any modifications in the end.

**Comment by luyiyilll** [comment]
> > > @Nitvex yes,my question is over.If I have the next question, I will use English，thank you是的，我的问题结束了。如果我有下一个问题，我会用英语，谢谢
> > 
> > 
> > > 意思是我修改完源码然后重新build成静态页面然后iframe引用？
> > 
> > 
> > Which package did you modify? ketcher-core?
> 
> I didn't make any modifications in the end.

So...how did you solve the problem of sinicization?

**Comment by summerooo** [comment]
解决汉化问题了吗？兄弟们。
