### ISSUE TITLE
User can't save and then open structure that contains more than 900 atoms

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#188]
**Steps to Reproduce:**
1. Open "more900atoms.mol" from [Templates](https://onedrive.live.com/?authkey=%21AGLZjvMyyansQG0&cid=8838B4A49C9832E9&id=8838B4A49C9832E9%21190&parId=8838B4A49C9832E9%21127&o=OneUp) in Ketcher.
2. Click "Save As.." button.
3. Save as Ketcher.mol file.
4. Clean canvas.
5. Click "Open" button and try to open Ketcher.mol.

**Expected Result:**
Ketcher.mol file is opened, structure containing 900 atoms appears (like in more900atoms.mol).

**Actual Result:**
Ketcher.mol is displays in text field but after clicking on "Ok" button structure is not appeared on canvas.
![errors](https://user-images.githubusercontent.com/75974465/102493815-c7fc6600-4084-11eb-915f-2ee621c2109e.jpg)

**Comment by Zhirnoff** [comment]
Not reproduced in ver. 2.12.0-rc.1
![2023-06-30_16h25_31](https://github.com/epam/ketcher/assets/62464241/8d5e4707-123e-4908-88c8-0d666b533be1)
![2023-06-30_16h25_46](https://github.com/epam/ketcher/assets/62464241/df711f9f-7f18-4795-8968-c34faeebc497)
