### ISSUE TITLE
Blocked a frame with origin https://xxxxx from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by ixdi** [epam/ketcher#19]
Hi,

We have started using ketcher with indigo. We serve both from the same instance in a separate url from the main platform url where the user loads the page. Our server uses node.js and we have deployed indigo using nginx and certboot in docker-compose.

So, our platform and ketcher are served from different domains and these leads to the following error:
```
Blocked a frame with origin "xxxx" from accessing a cross-origin frame. 
```
But if ketcher is not served from the same domain than indigo there's CORS failures.

Any advise or solution? Using window.postMessage needs refactoring ketcher to reference our main domain.

Thanks

**Comment by AlexanderSavelyev** [comment]
Hi

Yes, if Ketcher is not hosted from the same domain as indigo-service - there will be CORS error. One need to update nginx on service side and include header
add_header 'Access-Control-Allow-Origin' '*' always;

Please see example config here
https://github.com/epam/Indigo/blob/master/utils/indigo-service/nginx/nginx.conf

**Comment by ixdi** [comment]
Hi,

Yes, we already have this on our nginx config, but the problem is not this, the problem is using an iframe that results in failures.
```
server {
    listen 80;
    server_name xxxxx.com;
    location / {
        return 301 https://$host$request_uri;

    }    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
  listen 443 ssl;
  keepalive_timeout 5;
  server_name xxxxx.com;

  ssl_certificate /etc/letsencrypt/live/xxxxx.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/xxxxx.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  # The following configuration are related to the indigo service
  # see here https://lifescience.opensource.epam.com/indigo/service/index.html
  location / {
    root /srv/www/ketcher;
    index ketcher.html;
    try_files $uri $uri/ @indigoservice;
  }

  location @indigoservice {
    # Should be set 'always' to transfer our lovely HTTP500 errors
    # Headers could be also set by Flasgger in service/config.py
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'POST, GET, PUT, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Accept' always;
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
    add_header 'Access-Control-Max-Age' '86400' always;
    include uwsgi_params;
    uwsgi_pass indigo_service:8002;
  }
}
```
Although ketcher and indigo are served from same domain, as it is not the domain from the platform where iframe is inserted then there's no way to get the ketcher iframe reference. At least as far as we know. 

One solutions would be window.postMessage but needs a ketcher refactor to insert our domain.

Is there any easy solution? Thanks
