### ISSUE TITLE
Save hotkey CTRL+S: An atom or structure copied to the clipboard is saved with coordinates

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1902]
**Steps to Reproduce**
1. Open Ketcher
2. Copy an atom(e.g. Nitrogen) or structure (e.g. Benzene) to the clipboard ( CTRL+C )
3. Press CTRL+V on canvas
4. Then without clicking on the canvas - press CTRL+S 

**Expected behavior**
In the save window that opens, in the preview section, the atom or structure has no coordinates because they were not added to the canvas

**Actual behavior**
In the save window that opens, in the preview section, the atom or structure has coordinates as if they were added to the canvas

**Screenshots**
Atom copied to clipboard (Nitrogen)
![2022-12-09_15h42_59](https://user-images.githubusercontent.com/62464241/206707187-abe89343-a2ec-43ca-97f2-f08c056b5e7d.png)
Structure copied to clipboard (Benzene)
![2022-12-09_15h44_56](https://user-images.githubusercontent.com/62464241/206707197-ba2d9bb4-0fb1-442b-8ff1-55a939779900.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 107.0.5304.108 (Official Build) (64-bit)

**Ketcher version** 
[2.6.4]
**Additional info**
If you select a different save format and then select v2000 again, then the coordinates disappear
https://user-images.githubusercontent.com/62464241/206707228-028782ac-4af1-4bb3-95a4-4bda2c7d6997.mp4

**Comment by porcelain11** [comment]
Discussed - not sure about structure. is there a way to get (= copy) structure without coordinates?
Going on with atoms.
