### ISSUE TITLE
Incorrect forest allocation of S-Groups in multigroups structures

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#191]
**Steps to Reproduce:**
1. Open Multi.rxn file in Ketcher.
2. Hover mouse over different S-Groups to check the forest selection of S-Groups and brackets displaying.

**Expected Result:**
S-Groups forests and brackets display correctly.

**Actual Result:**
Forest allocation of S-Groups in multigroups structures are displayed incorrectly. Brackets display as expected.
![multi](https://user-images.githubusercontent.com/75974465/102591666-76ef7f00-4123-11eb-927f-dfd121ba4d03.gif)

**Comment by AleksandrPokrovskii** [comment]
Actual result is displayed as expected
