### ISSUE TITLE
[version 2.1] - Is it possible to run without React?

### ISSUE THREAD

**Issue by ixdi** [epam/ketcher#192]
Hi,
We are using ketcher in our platform but we're not using React. 
Is it possible to use the new 2.1 version without using React?

Thanks

**Comment by AndreiMazol** [comment]
Hi @ixdi ,

React replaced Preact framework which Ketcher was originally based on. Preact is a lite version of React but it is far less popular and React based apps had to keep both React and Preact libs. Now their life is simplified a little bit.

However we are going to keep Ketcher as lightweight as possible in the future and will soon enhance its architecture by splitting onto 2 modules: the core part (including editor) and the UI controls which are currently based on React but may further be implemented based on any other framework (e.g. Angular) or your own custom controls.

This moment you can follow this [instruction](https://preactjs.com/guide/v8/switching-to-preact/) if you want switch back to Preact.

Sorry for temporary inconvenience. Hope you'll enjoy the new more modular architecture once it is implemented. 

Best regards,
Ketcher team

**Comment by ixdi** [comment]
Hi @AndreiMazol , 
Thanks for the answer!
In previous versions Preact was transparent for us but now Ketcher doesn't use an iframe so React must be loaded explicitly. We will wait for the split.
Best Regards

**Comment by AndreiMazol** [comment]
@ixdi , 

you can use approach that bases on Iframe too. For this goal you can download this [archive](https://www.epam.com/download?downloadParam=/content/dam/epam/library/open-source/ketcher/ketcher-2.1.0-beta.zip) or (if you  want to  work with  the latest code base) build your own package from example folder.
