### ISSUE TITLE
Reagents: When opening Daylight SMILES and Extended SMILES files with reagent the original structure is distorted

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1930]
**Steps to Reproduce**
1. Launch Ketcher
2. Create structure with arrow and reagent molecule above arrow
3. Save file as Daylight SMILES
4. Open saved file
5. Save file as Extended SMILES
6. Open saved file

**Expected behavior**
When opening Daylight SMILES and Extended SMILES files with reagent the original structure is NOT distorted

**Actual behavior**
When opening Daylight SMILES and Extended SMILES files with reagent the original structure is distorted

**Attachments**
![2022-12-14_19h20_48](https://user-images.githubusercontent.com/62464241/207834405-f29e1671-d84e-4894-a3a7-3aa6806ca5d8.png)
![2022-12-14_19h21_58](https://user-images.githubusercontent.com/62464241/207834417-2e9253c4-89ef-477a-a8dc-05dba35d09a9.png)

**Indigo/Bingo version**  
Version 1.8.3.0-gded13d6dc-x86_64-linux-gnu-11.2.1

**Additional context**
Ketcher requirements issue: https://github.com/epam/ketcher/issues/1703
Related Indigo issue: https://github.com/epam/Indigo/issues/932

**Comment by KonstantinEpam23** [comment]
@Zhirnoff can you please attach an example of the file that we can use to reproduce this?

**Comment by lorken24** [comment]
<img width="1512" alt="Screenshot 2023-02-13 at 13 18 13" src="https://user-images.githubusercontent.com/65543532/218455975-a9ccb9ea-1cac-4652-b1cb-b4a3b0d58c68.png">
Reproduced the issue about SMILES formats with reagents. 

[Reaction with Cl ext sml.cxsmi.zip](https://github.com/epam/ketcher/files/10722102/Reaction.with.Cl.ext.sml.cxsmi.zip)
[Reaction with Cl day sml.smi.zip](https://github.com/epam/ketcher/files/10722103/Reaction.with.Cl.day.sml.smi.zip)
[Reaction with Cl (1).rxn.zip](https://github.com/epam/ketcher/files/10722104/Reaction.with.Cl.1.rxn.zip)

**Comment by Zhirnoff** [comment]
Fixed by related Indigo issue: https://github.com/epam/Indigo/issues/932
