### ISSUE TITLE
Reagents: An error message appears when opening the file RXN v3000 with reagent

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1931]
**Steps to Reproduce**
1. Launch Ketcher
2. Create structure with arrow and reagent molecule above arrow [ketcher (32).zip](https://github.com/epam/ketcher/files/10315723/ketcher.32.zip)

3. Save file as RXN v3000
4. Open saved file

**Actual behavior**
An error message appears when opening the file RXN v3000 with reagent: 'line unrecognized: M V30 BEGIN AGENT'

**Expected behavior**
The file opens correctly with the reagents as it was saved

**Screenshots**

![2022-12-14_19h24_10](https://user-images.githubusercontent.com/62464241/207832795-b693b5a8-b7a4-4a6d-bbd1-390db163ad82.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.99 (Official Build) (64-bit)

**Ketcher version**
[v2.7.0]
Related requirements issue: https://github.com/epam/ketcher/issues/1698

**Comment by KonstantinEpam23** [comment]
@Zhirnoff can you please attach a file that we can use to reproduce this?

**Comment by Zhirnoff** [comment]
@KonstantinEpam23 i have attached the file
