### ISSUE TITLE
CSS file contains global styles 

### ISSUE THREAD

**Issue by 4-life** [epam/ketcher#1935]
**Steps to Reproduce**
1. Go to example page https://lifescience.opensource.epam.com/KetcherDemoSA/index.html
2. Open browser console and find main style file
3. In style file find "checkbox":

![image](https://user-images.githubusercontent.com/10114517/207850725-b752023b-fb96-4f50-a6ef-64b73dc49b89.png)

OR:
1. Open https://www.npmjs.com/package/ketcher-react?activeTab=explore
2. Open index.css file
3. Find "checkbox":

![image](https://user-images.githubusercontent.com/10114517/207849932-73f9e53d-1d9d-467b-8209-0fa3585bfca1.png)

**Actual behavior**
Global styles exported from npm build

**Expected behavior**
Compiled styles should not contain global styles. I tried to compile Ketcher locally and styles looks fine:
 
![image](https://user-images.githubusercontent.com/10114517/207851556-e1bb92a5-c6cd-40d8-ac5d-4c6a90b536f2.png)

**Ketcher version** [e.g. v2.4.2]. 
2.6.4

**Comment by Jackson-Hill** [comment]
Hello @Nitvex , I am experiencing an issue where I am unable to use ketcher-react in a Next JS project. Is there any plan to fix this issue?

**Comment by yuleicul** [comment]
Hi @Jackson-Hill, please checkout this comment https://github.com/epam/ketcher/issues/2197#issuecomment-1619776556

**Comment by yuleicul** [comment]
Thanks for your contribution @4-life 
This issue has been fixed by https://github.com/epam/ketcher/pull/1767
