### ISSUE TITLE
As soon as user changes the structure the stereoconfiguration should be re-calculated

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#195]
**Steps to reproduce**
### Scenario I
1. Open the attached file stereocenter.mol.
[stereocenter.zip](https://github.com/epam/ketcher/files/5723073/stereocenter.zip)
2. Click the 'Calculate CIP' button. - The R stereo label appears.
3. Change the Single Up Bond with the Single Down Bond.

**Actual result**
- The R stereo label is not changed to S label.
- User should click the 'Calculate CIP' button once again to re-calculate stereoconfiguration.
- 
### Scenario II
4. Delete the stereobond.

**Actual result**
The stereobond is removed. The stereolabel is present still.

**Expected result**
As soon as user changes the structure the stereoconfiguration should be re-calculated. It's a user-friendly behavior.

**Comment by Svetlana-Asinovskaia** [comment]
1) The attached file stereocenter.mol. is opened with wrong symbols.
![image](https://user-images.githubusercontent.com/80695128/113672657-b5a04980-96c0-11eb-96b3-7c456e33d58c.png)
It's also possible to reproduce this issue with the following steps:
1. Draw a structure, e.g. cyclohexane.
2. Add Single Up (Single Down, Single Up/Down) bond.
Or:
1. Choose a Custom template with stereobonds (e.g. one of α-D-Sugars).
2. Change a Single Down bond with a Single Up bond or vice versa. 

2)'Undo' (and 'Redo') option with deleted stereobond works in two steps. 1st click - Stereolabel is returned to the canvas. 2nd click - stereobond is returned to the canvas.

**Comment by irinatelnova** [comment]
When user changes the structure the stereoconfiguration will not be re-calculated automatically in order to avoid making server requests each time on structure changing.
Now **Expected Result**:
As soon as user changes the structure stereoconfiguration marks should be removed.
User should click the 'Calculate CIP' button once again to calculate the stereo configuration.

**Comment by AndreiMazol** [comment]
@Svetlana-Asinovskaia  please transform the following requirement to a separate enhancement:
"As soon as user changes the structure stereoconfiguration marks should be removed"

**Comment by Svetlana-Asinovskaia** [comment]
The enhancement
"As soon as user changes the structure stereoconfiguration marks should be removed" will be done within the task https://github.com/epam/ketcher/issues/539
