### ISSUE TITLE
Split Ketcher into Core and Presentations modules

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#196]
In order to  support different presentation layers (React/Angular/Vue & etc) it is necessary to move core functionality into  separate module. Every  module should be delivered as an independent npm package.

![Ketcher_Structure_Diagram](https://user-images.githubusercontent.com/72735611/102755414-6c312600-437f-11eb-8e26-f8a8bf4baa72.png)

Scope of this task:
1. Create core package
2. move shared interfaces into core package
3. add link to ketcher-react & ketscher-standalone
4. prepare ketcher-core for publishing to npm

**Comment by ElenaKlepova** [comment]
The issue is verified.
