### ISSUE TITLE
Attachment points should be within R-Group brackets

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/ketcher#197]
**Description:** 
When attachment points are attached to a structure that is a R-Group member,  the attachment points are beyond the R-Group brackets. 

**Steps to reproduce:**
1. Create a structure.
2. Make the structure a R-Group member using _R-Group Fragment Tool_.
3. Attach attachment points to the structure using _Attachment Point Tool_. 

**Actual result:**
Attachment points are beyond R-Group brackets.
![2020-12-21_17h17_11](https://user-images.githubusercontent.com/75974843/102787231-cc40c000-43b1-11eb-9211-7dd238ab4281.png)

**Expected result:**
Attachment points are within R-Group brackets.

**Comment by Zhirnoff** [comment]
Made only for R-Group Fragment, not for S-Group
![2023-07-07_11h38_06](https://github.com/epam/ketcher/assets/62464241/42fe3f47-35be-45f9-ab70-ead453cda584)
![2023-07-07_11h38_39](https://github.com/epam/ketcher/assets/62464241/3285b363-8095-46f3-8adc-d0dd0f9ed8ef)
