### ISSUE TITLE
Abbreviations: User can make changes to the abbreviations of Functional Groups and Salts and Solvents

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1988]
**Steps to Reproduce**
1. Launch Ketcher
2. Click on 'Templates'
3. Select any abbreviation from Functional Groups or Salts and Solvents
4. Paste it on canvas and expand abbreviation by mouse right click
5. Move the mouse cursor over any of the atoms of expanded abbreviation and press the hotkey (e.g. N)

**Actual behavior**
User can make changes to the abbreviations of Functional Groups and Salts and Solvents

**Expected behavior**
User can't make changes to the abbreviations of Functional Groups and Salts and Solvents. A warning window should appear: 
EDIT ABBREVIATION
A change was detected for the abbreviation. Do you want to remove the abbreviation information from the structure and continue work with separate atoms and bonds?

**Screenshots**

https://user-images.githubusercontent.com/62464241/209308869-ee86caab-fac6-4157-b7e8-10c6fa0676bc.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

**Comment by Nitvex** [comment]
Potentially fixed by https://github.com/epam/ketcher/pull/2010

**Comment by Nitvex** [comment]
Issue is NOT reproduced on v2.7.0-rc.9
