### ISSUE TITLE
Abbreviations: Sometimes expand is drawn on top of the abbreviated name

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1989]
**Steps to Reproduce**
1. Launch Ketcher
2. Select any 'Salt and Solvents' abbreviation (e.g. formic acid)
3. Place on canvas and expand abbreviation

**Actual behavior**
Sometimes expand is drawn on top of the abbreviated name

**Expected behavior**
Expand does not overlap abbreviation
![2022-12-23_12h50_19](https://user-images.githubusercontent.com/62464241/209313906-4a355b7c-0650-4f50-9585-621d1ef3abeb.png)

**Screenshots**

![2022-12-23_12h44_24](https://user-images.githubusercontent.com/62464241/209312711-d721eac8-f04a-4d00-bdf6-0eb700dcd093.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.99 (Official Build) (64-bit)

**Ketcher version**
[Version 2.7.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2022-12-22; 10:43:36

**Additional context**

**Comment by Nitvex** [comment]
Issue is reproduced in v2.7.0-rc.9, moving to v2.9.0-rc.1

**Comment by KonstantinEpam23** [comment]
This may be resolved by #2086 
@Zhirnoff can you please re-evaluate it?

**Comment by Zhirnoff** [comment]
Bug fixed. Tested in Version 2.8.0-rc.4
