### ISSUE TITLE
Warning about incorrect valence is absent if the Query Bonds are added to the atom

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#199]
**Steps to reproduce:**
1. Create, for example, benzene.
2. Add one Single bond to any benzene atom.
3. Add any Query Bond (except the Aromatic Bond) to the same atom.

**Expected Result:**
Carbon atom with 4 bonds should be underlined with red because has 4 valence (default).

**Actual result:**
The carbon atom with the default valence and more than 4 bonds isn't underlined with red.
![Screenshot 2020-12-23 163648](https://user-images.githubusercontent.com/75974465/103000945-12765a80-453d-11eb-814f-a3f527771d10.jpg)

**Comment by StartsevDS** [comment]
@AlexanderSavelyev expertise is requested.

**Comment by AlexanderSavelyev** [comment]
yes the atom with incorrect valence should be highlighted

**Comment by AlexanderSavelyev** [comment]
actually, the server does not validate valence for query bonds as a query feature. Therefore to be consistent, the query bonds should not validate a valence since a query molecule can contain "incorrect" valence as part of bigger structure

**Comment by AlexanderSavelyev** [comment]
@KseniiaSemenishcheva  I'm closing the bug
