### ISSUE TITLE
Functional group does not connect with another functional group on click&drag

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1990]
**Steps to Reproduce**
1. Launch Ketcher
2. Select any 'Functional Group' abbreviation (e.g. Bn)
3. Place on canvas (do not expand)
4. Select any 'Functional Group' abbreviation (e.g. Bn) with Template or Paste tools
5. Hover over 'Bn' on canvas, click and drag

**Actual behavior**
At the moment, a notification window appears:
EDIT ABBREVIATION
A change was detected for the abbreviation. Do you want to remove the abbreviation information from the structure and continue work with separate atoms and bonds?

**Expected behavior**
If existing functional group is not yet connected to another structure, the new one should be added and connected with existing one with single bond.
![2023-02-09_15h21_26](https://user-images.githubusercontent.com/62464241/217811824-5823834f-31ed-431e-9774-6c1f854e5863.png)

If existing functional group is already connected with another structure, 'Edit Abbreviation' dialog should be opened (current behavior).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.99 (Official Build) (64-bit)

**Ketcher version**
[Version 2.7.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2022-12-22; 10:43:36

**Additional context**

**Comment by Nitvex** [comment]
Issue is reproduced in v2.7.0-rc.9, moving to v2.9.0-rc.1

**Comment by yuleicul** [comment]
> **Expected behavior**
>
> ......
>
> If existing functional group is already connected with another structure, 'Edit Abbreviation' dialog should be opened (current behavior).

Hi @St-Permiakov , could you please check if the expected behavior above has been implemented? If I understand correctly, it hasn't 😔. The 'Edit Abbreviation' dialog doesn't pop up as expected.
