### ISSUE TITLE
Bond context menu: move non-query bonds to 1st level, add dots to Edit item

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#1995]
Update bond context (right-click) menu as follows:

1. Move all bonds except query ones (Any, Aromatic, Single/Double, Single Aromatic, Double Aromatic) to the main (1st-level) menu right below 'Edit' item.
2. Rename 'Bond type' menu to 'Query bonds' 
3. Add 3 dots to the end of 'Edit' label to indicate that an additional dialog will be shown: "Edit..."
4. Combine "Delete selected atom(s)" and "Delete selected bond(s)" into single menu item "Delete"

**Comment by yuleicul** [comment]
Needs to be discussed: batch operations

![image](https://user-images.githubusercontent.com/27288153/212021688-1c7371f7-bdaf-4cc0-bb82-467c4f048175.png)

Looks a bit long if move bond types to the first level (omitted some bond types here)

![image](https://user-images.githubusercontent.com/27288153/212024228-7a1a3919-2795-4aba-a6fc-af94a764a45e.png)
