### ISSUE TITLE
Bond context menu: add ability to attach or edit S-Group

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#1996]
Add ability to attach or edit S-Groups to bonds via context (right-click) menu. 

1. If no S-Group is attached to a bond, the context menu should include 'Attach S-Group...' item. The item should open S-Group attachment ('S-Group Properties') window the same way as if the bond is selected and 'S+' tool from left toolbar is applied on it.
2. If an S-Group is already attached to a bond, its context menu should include 'Edit S-Group...' item that opens the same S-Group properties window.
3. For nested s-groups (see screenshot) 'Edit S-Group...' or 'Attach S-Group...' menu item must be disabled.

S-Groups attachment/editing item should appear above Delete item. 

Screenshots:
![MicrosoftTeams-image (36)](https://user-images.githubusercontent.com/41272128/220117181-858e0f1c-4362-4a64-89f1-f03c52bc94e9.png)

**Comment by yuleicul** [comment]
For this feature, we need to add two items to the bond context menu. One is Attach S-Group... , the other is Edit S-Group... . **Here comes the question, one bond might be included in multiple groups**, for example
![image](https://user-images.githubusercontent.com/27288153/220254124-3242e53f-49f3-44bb-97ab-f3eee93e8035.png)


**Proposed solution** (by @Nitvex ):
Disable _Edit S-Group..._, if there are nested S-Groups. Will create a separate task for handling nested S-Groups.
