### ISSUE TITLE
RXN 2000 and 3000 import: When importing, the structure becomes unreadable

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#1997]
**Steps to Reproduce**
1. Launch Ketcher
2. Open [File](https://github.com/epam/ketcher/files/10295912/New.Text.Document.2.zip)
3. Look at canvas

**Actual behavior**
The structure is unreadable

**Expected behavior**
The structure is imported from the saved file as it was drawn without distortion
![2022-12-23_18h27_40](https://user-images.githubusercontent.com/62464241/209360125-fe9c8a76-3e3f-45d1-8e74-edb0879c5290.png)

**Screenshots**
![2022-12-23_18h21_37](https://user-images.githubusercontent.com/62464241/209360138-8edd20a4-3675-4656-bfb0-d8687a58c982.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.6](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2022-12-23; 13:33:39

**Comment by Nitvex** [comment]
Issue is reproduced in v2.7.0-rc.9, moving to v2.9.0-rc.1

**Comment by KonstantinEpam23** [comment]
Looks like Indigo bug @Zhirnoff

**Comment by Zhirnoff** [comment]
Bug moved to Indigo side https://github.com/epam/Indigo/issues/1113
