### ISSUE TITLE
js error when call getSmiles()

### ISSUE THREAD

**Issue by ForBurning** [epam/ketcher#2]
![qq 20180205182643](https://user-images.githubusercontent.com/28643492/35800167-237992e8-0aa3-11e8-984f-628757c2ba36.png)
hi，
    there is an error when I call getSmiles of ketcher , could you help to fix it?   thx again!
   (errro page: http://indigoweb.epm-lsop.projects.epam.com/ketcher/?api_path=/v2),

**Comment by AndreiMazol** [comment]
Cannot reproduce: tested on the last version (commit hash 38069eda171d4294d1c3d2b0dc7a439edbe95d1b). 
![image](https://user-images.githubusercontent.com/72735611/97434617-53346780-1930-11eb-86e2-454cc6f13a8b.png)
Please inform us if you get this error again.
