### ISSUE TITLE
Incorrect positioning of data s-group labels

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2009]
**Steps to Reproduce**
1. Launch Ketcher
2. Create chain structure or Benzene
3. Highlight all structure by Selection tool
4. Click on  'Data S-Group' button
5. In 'S-Group Properties' window select from drop-down menu: 'Context-Atom or Bond', 'Field name-A', 'Field value-2', 'Radio button-Absolute or Relative'
6. Click 'Apply' button
7. Look at structure

**Actual behavior**
Adding to Atom or Bond a Data S-Group the attachment point on the structure is incorrect

**Expected behavior**
Adding to Atom or Bond a Data S-Group the attachment point on the structure is correct: Atom value on atom, Bond value on bond
Mapping for Atoms:
![2022-12-27_14h51_44](https://user-images.githubusercontent.com/62464241/209663737-649a350b-4919-4436-be8b-f3af4a2b5b06.png)
Mapping for Bonds:
![2022-12-27_14h53_31](https://user-images.githubusercontent.com/62464241/209663745-6bc5a18a-d2b0-4da0-9616-95d43d1448e1.png)

**Screenshots**
![2022-12-27_15h00_11](https://user-images.githubusercontent.com/62464241/209663752-d0bbbc5c-164f-4c2a-8404-3ce9f91b6038.png)
![2022-12-27_15h02_09](https://user-images.githubusercontent.com/62464241/209664237-76bf19a2-e8cf-46dd-9a75-c6cbcd6b8f67.png)

https://user-images.githubusercontent.com/62464241/209664896-0f157d93-8b0e-4f75-b1db-744071486849.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.7](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Nitvex** [comment]
Issue is reproduced on 2.7.0-rc.9, moving to 2.9.0

**Comment by KonstantinEpam23** [comment]
Bond data labels should be drawn in the middle of the bond over it.
