### ISSUE TITLE
The Stereo labels and Attached Data keep their positions after the Flip action

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#201]
**Steps to reproduce:**
1. Open the attached file.
[data-flip.zip](https://github.com/epam/ketcher/files/5735536/data-flip.zip)
2. Click the 'Calculate CIP' button.
3. Select whole structure.
4. Click the Vertical Flip button.

**Expected Result:**
Whole structure was flipped.

**Actual result:**
The structure is flipped. The Stereo labels and Attached Data keep their positions.
![data-flip](https://user-images.githubusercontent.com/75974465/103002513-1788d900-4540-11eb-9b08-f94943d5aa52.PNG)

**Comment by MagomedGasanov** [comment]
fixed by https://github.com/epam/ketcher/issues/195

**Comment by AleksandrPokrovskii** [comment]
All works as Expected.
**Stereo labels have the following behavior:**

1. If absolute flag is selected, label don't flips.
2. If relative flag is selected, label flips.
3. If attached flag is selected, label binds to every atom

Problems with Attached Data are no longer observed.

**Comment by Svetlana-Asinovskaia** [comment]
The issue is still reproduced.

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is closed as fixed.
