### ISSUE TITLE
Erase tool: Hotkey (Del) can't delete arrows and plus sign

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2026]
**Steps to Reproduce**
1. Launch Ketcher
2. Draw arrow and plus sign
3. Hover mouse over arrow or plus and press hotkey (Del)

**Actual behavior**
Arrow and plus sign are not deleted

**Expected behavior**
Arrow and plus sign are deleted

**Screenshots**

https://user-images.githubusercontent.com/62464241/209928365-d1ac3f99-fd17-498a-8306-ff03d8ec5d12.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.8](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

**Comment by Nitvex** [comment]
Issue is reproduced in v2.7.0-rc.9, moving to v2.9.0-rc.1

**Comment by Zhirnoff** [comment]
The bug is reproducing. Arrows and plus sign are not removed by hotkey (DEL)
Note: Also, bonds are not deleted by hotkey. Only atoms are removed.

https://user-images.githubusercontent.com/62464241/216725439-4f90c574-6828-488a-939b-10feda933d1c.mp4

**Comment by St-Permiakov** [comment]
No it's not.
Latest `master`:

https://user-images.githubusercontent.com/24246336/216758648-c53a8415-2875-48f5-a20b-ad395922efaa.mov

Maybe it's not in the testing branch yet (whichever that is)?

**Comment by Zhirnoff** [comment]
I tested this in Ketcher 2.8.0-rc.2 on rc test platform.
