### ISSUE TITLE
hi,Image Recognition service is not available

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [epam/ketcher#2027]
**Steps to Reproduce**
hi,please help me.
1. Image Recognition service is not available in open structure ,I don't know how to configure.

**Expected behavior**
I think it can be used

**Screenshots**
![image](https://user-images.githubusercontent.com/30283623/209929962-848425fc-adbc-4397-a5a9-e685023d9b74.png)

**Ketcher version** 
2.6.4
indigo version 1.8.3

**Additional context**
Because the  Image Recognition service  cannot be used in the [standalone](https://github.com/epam/ketcher/tree/master/packages/ketcher-standalone) version, I converted the remote version, but it still cannot be used

**Comment by KonstantinEpam23** [comment]
Hi @wojiaoxiaomayun 
Yes, the service is currently disabled, but we are planning to enable it again in the remote version in the near future.

**Comment by wojiaoxiaomayun** [comment]
> 

Oh,Thanks for you,That's very good. Do you have any plans to start in recent months or this year?
