### ISSUE TITLE
Update all documentation throughout the project

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2030]
**Describe the solution you'd like**
Replace all documentation that mentions yarn with correct npm alternatives.
This includes all "readme" and .md files, wiki and any other places where yarn may be mentioned.
Make sure the documented npm commands work correctly.

Also, if applicable - update lifescience portal documentation: https://github.com/epam/lifescience

**Comment by epam-nikolai-iakushchenko** [comment]
Looks like this page needs to be updated
https://kb.epam.com/display/EPMLSOP/Ketcher+Release+Preparation#
