### ISSUE TITLE
Abbreviations: Atoms protrude beyond the expanded view for Functional Groups and Salts and Solvents

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2033]
**Steps to Reproduce**
1. Launch Ketcher
2. Press 'Custom Templates' button and click on 'Functional Groups' tab
3. Select for example 'CO2tBu' and add to canvas
4. Press 'Custom Templates' button and click on 'Salts and Solvents' tab
5. Select for example 'methane sulphonic acid' and add to canvas
6. Expand the abbreviations and look at appeared images

**Actual behavior**
Expand abbreviation for Functional Groups and Salts and Solvents works incorrectly - atoms protrude beyond the expanded view

**Expected behavior**
Expand abbreviation for Functional Groups and Salts and Solvents works correctly - atoms not protrude beyond the expanded view. The whole structure fits into an expand square.

**Screenshots**
![2022-12-29_14h51_14](https://user-images.githubusercontent.com/62464241/209948819-b103cd03-ea0d-413a-a1ad-95b709602fdb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.8](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

**Comment by Nitvex** [comment]
Issue is reproduced in v2.7.0-rc.9, moving to v2.9.0-rc.1
