### ISSUE TITLE
Thumbnail images are not readable in Template Dialog

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2043]
**Steps to Reproduce**
1. Open template dialog
2. Switch to "Functional Groups" tab
3. Observe some large structure

**Actual behavior**
Some structures are not fully readable due to small font size

**Expected behavior**
It is required to increase font size for elements to make structures readable

**Screenshots**
Example of unreadable structure:
![image](https://user-images.githubusercontent.com/41272128/210068069-302a353f-5a05-4c29-bb37-02967cb58b08.png)

**Comment by porcelain11** [comment]
Screenshots for different font sizes and bond thicknesses are in the attachment
[screenshots.zip](https://github.com/epam/ketcher/files/10360107/screenshots.zip)
