### ISSUE TITLE
Functional Groups: The functional group is not added to one of the H3C

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2045]
**Steps to Reproduce**
1. Launch Ketcher
2. Put 'Benzene' structure on canvas
3. Select 'Single bond' tool and add to all corners of 'Benzene' structure
4. Select any functional group (e.g. 'Ac') and attach to all bonds

**Actual behavior**
The functional group is not added to one of the H3C. Error message at browser console:'Uncaught TypeError: Cannot read properties of undefined (reading 'x')'

**Expected behavior**
The functional group is added to the H3C without errors

**Screenshots**

https://user-images.githubusercontent.com/62464241/210330526-e94741bb-cdb7-4ed6-a9d4-b419dbd63d0f.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.8](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

**Comment by Nitvex** [comment]
Issue is reproduced in v2.7.0-rc.9, moving to v2.9.0-rc.1
