### ISSUE TITLE
Stereo labels appears on not stereo structure after 'Aromatize' action.

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#206]
**Affected Versions:** Standalone

**Steps to Reproduce:**
1. Open 'non-aromatic-structures.mol' file.
2. Click 'Aromatize' button.

**Expected Result:**
Nothing should be changed on canvas when the non-aromatic structures are present on the canvas.

**Actual Result:**
Z labels appears on cyclooctane structure.
![Screenshot 2020-12-25 165320](https://user-images.githubusercontent.com/75974465/103136466-b6910a80-46d1-11eb-9199-f95e55c328ad.jpg)

**Comment by TomasLight** [comment]
Issue doesn't repeat anymore

**Comment by KseniiaSemenishcheva** [comment]
Bug was fixed in another issue. 
Closed as not reproduces.
