### ISSUE TITLE
Remove "Chiral" label from text of absolute flag

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2065]
**Is your feature request related to a problem? Please describe.**
it is required to remove not informative "Chiral" part of text for absolute flag.

**Additional context**
At the moment, text of absolute flag can be found in the settings:
<img
  height="340"
  width="250"
  src="https://user-images.githubusercontent.com/41272128/211028398-f962d471-4d07-4dd8-b042-60513570d06a.png"
/>
After the "Chiral" label is removed from text, then it is properly shown on canvas:
![Screenshot 2023-01-06 at 17 11 36](https://user-images.githubusercontent.com/41272128/211028985-8ac7e6b6-2dd3-429d-88e3-3b02a90e007e.png)

**Comment by KonstantinEpam23** [comment]
Looks like this may present an issue, since the "(Chiral)" label is stored in localStorage. Users who have dited editor settings before this update may still see the label. @Nitvex @Zhirnoff
