### ISSUE TITLE
Saving structure: Can't save file(e.g mol v3000, CML, CDXML) if selected S-Group Properties for all structure with Type-Multiple group

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2066]
**Steps to Reproduce**
1. Launch Ketcher
2. Create Chain structure or Benzene
3. Select all structure and press S-Group (CTRL+G)
4. At 'S-Group Properties' window select: Type = Multiple group, Repeat count = 1 and press 'Apply'
5. Press save button and from drop-down window select all formats in turn, look at the preview and save

Note: If you select part of structure preview render is working and you can save in many formats with missing brackets (e.g SMILES, SMARTS and etc.)

**Actual behavior**
The preview does not contain a file preview or image of the structure and when you click the save button, the image is not saved

**Expected behavior**
The preview contain a file preview or image of the structure and when you click the save button, the image is saved

**Screenshots**

https://user-images.githubusercontent.com/62464241/211026120-00c6dedb-78ec-419d-9c65-85f934fd8bea.mp4

https://user-images.githubusercontent.com/62464241/211026129-8d64e557-f20c-4345-a035-f4cdaa78807b.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.7.0-rc.8](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Nitvex** [comment]
Issue is reproduced in 2.7.0-rc.9, moving to 2.9.0

**Comment by Nitvex** [comment]
Note: following the steps mentioned in the bug description, I've got the following error (only standalone version):
![MicrosoftTeams-image (33)](https://user-images.githubusercontent.com/41272128/212712428-db0b8334-b99d-48fc-933f-14cfb7b441c3.png)

**Comment by KonstantinEpam23** [comment]
Seems like the issues occurs whenever the first or last atom is selected @Zhirnoff

**Comment by Zhirnoff** [comment]
Bug not reproduced in Version 2.13.0-rc.3 and Indigo Version 1.13.0-rc.1
https://github.com/epam/ketcher/assets/62464241/a2a2ca3d-1448-4943-aa1b-8d238966f2e3
