### ISSUE TITLE
Clean Up action for stereo structures not changes structure

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#207]
**Affected Version:** _Standalone_
**Steps to Reproduce:** 
1. Open 'structure_with_stereo_bonds.mol' file.
2. Click on the 'Calculate CIP' button of the main toolbar.
3. Click on the 'Clean Up' button of the main toolbar.

**Expected Result:**
Stereo labels should appear near stereo bonds after 'Calculate CIP' action.
Stereo labels should disappear after 'Layout' action; stereo bond should be replaced (Up -> Down, or vice versa).
Stereo labels should disappear after 'Clean Up' action.

**Actual Result:**
After 'Clean Up' action stereo labels not disappear and structure is not changed.

**Comment by AleksandraTitova** [comment]
1) Stereo labels disappear after Clean Up/Layout = ok

2) Layout behaves differently with different stereo structures. 
Some structures are rotated (example attached [StereochemComplexTester_Mixed.zip](https://github.com/epam/ketcher/files/6156858/StereochemComplexTester_Mixed.zip)) and some are not.
Research required to define and describe desired behavior and confirm/reject the bug.

**Comment by ensemenova** [comment]
@AlexanderSavelyev please clarify on question from @AleksandraTitova about StereochemComplexTester_Mixed.zip case

**Comment by AlexanderSavelyev** [comment]
all the stereo information is correct after layout (except one cis-trans update) so the issue can be closed
