### ISSUE TITLE
Center molecules after layout

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2078]
**Is your feature request related to a problem? Please describe.**
It is required to display structures and reactions in the middle of the screen, when user clicks layout button. 

#184100496

**Comment by luna215** [comment]
I'm currently trying to implement this. Would it be enough to be able to do this programmatically with
```typescript
ketcher.addFragment("...")
```
and we would just change the definition of the function to take in parameters?

```typescript
ketcher.addFragment("...", x=10, y=10)
```

and the users would be able to get the half of this structure based on the size of the editor?

Would love to help with this anyway I can!

**Comment by luna215** [comment]
I'm currently trying to implement this. Would it be enough to be able to do this programmatically with
```typescript
ketcher.addFragment("...")
```
and we would just change the definition of the function to take in parameters?

```typescript
ketcher.addFragment("...", x=10, y=10)
```

and the users would be able to get the half of this structure based on the size of the editor?

Would love to help with this anyway I can!

**Comment by Nitvex** [comment]
> I'm currently trying to implement this. Would it be enough to be able to do this programmatically with
> 
> ```ts
> ketcher.addFragment("...")
> ```
> 
> and we would just change the definition of the function to take in parameters?
> 
> ```ts
> ketcher.addFragment("...", x=10, y=10)
> ```
> 
> and the users would be able to get the half of this structure based on the size of the editor?
> 
> Would love to help with this anyway I can!

I think not. In my opinion, it is better to calculate the required coordinates in Ketcher itself, rather than on user's side.

**Comment by Zhirnoff** [comment]
Feature working as expected.
