### ISSUE TITLE
Stereo label (E) saves in .smi file

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#208]
**Affected Version:** _Standalone_
**Steps to Reproduce:**
1. Create any structure (for example, chain) with 2 sprouted stereo bonds and double bond between them. Or open 'aromatic_with_stereolabels.mol' file from templates.
2. Click 'Calculate CIP' button.
3. Click 'Save As...' button and save as .smi file. (ketcher.smi)
4. Clean canvas.
5. Open ketcher.smi file.

**Expected Result:**
Structure appears on canvas without stereo labels and stereo bonds.

**Actual Result:**
Structure appears without stereo bonds but with stereo label near double bond (E).
![stereo](https://user-images.githubusercontent.com/75974465/103196243-db18fc80-48f4-11eb-9170-7d3f6b92dda3.jpg)

**Comment by AndreiMazol** [comment]
Cannot reproduce

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is closed as non-reproducible.
