### ISSUE TITLE
Selection Tool: support rotation using in-place handle 

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#2090]
Improve structure rotation functionality, so that user could rotate selected structure or fragment using in-place tools instead of toolbar buttons.

For this purpose the following additional elements should be shown once structure/fragment eligible for rotation is selected: 

1. Dash-lined rounded rectangle surrounding the selection
2. Rotation handle on top of selection area
3. A small cross indicating the center of rotation 

<img width="303" alt="selected-structure" src="https://user-images.githubusercontent.com/18439849/230181468-31d8bef3-3bb4-45ea-8dca-5fae73160966.png">

Once user presses left mouse button on the rotation handle, the rotation mode is activated and the following changes should be applied (see below sketch):

1. Rotation handle changes its view (color/icon)
2. Center of rotation highlighted with blue color
3. Dashed line connecting the rotation handle with the center of rotation appears

<img width="292" alt="hover-handle" src="https://user-images.githubusercontent.com/18439849/230181647-8e2c1b0e-f701-4f4d-a1bf-b6fb1f1adba7.png">

User can further rotate the structure around the center using handle. All elements of the rotation tool rotate along with selected fragment. 

<img width="261" alt="rotation" src="https://user-images.githubusercontent.com/18439849/230181767-f97c9b65-286b-477e-a8ab-48e9b2c3501d.png">

Once user releases left mouse button, the rotation mode is deactivated, selected fragment stays in its new position (rotated) while elements of rotation tool (surrounding rectangle with handle) are redrawn at their initial position (zero rotation degree, handle on top). Note: all rotated atom labels should be redrawn so that symbols are aligned with horizontal axis. 

#184121704

**Comment by yuleicul** [comment]
> For this purpose the following additional elements should be shown once structure/fragment eligible for rotation is selected

Sorry I have a question. Could be more specific about 'structure/fragment eligible for rotation'? I know something like 
![rotation-object-06](https://user-images.githubusercontent.com/27288153/233930718-bc9c4edb-9f3c-4793-aaa4-f89492585a12.png)
![rotation-object-07](https://user-images.githubusercontent.com/27288153/233930732-0549685a-ffb6-483d-a28c-9d32014814a4.png)
are structures/fragments, but what about:

![rotation-object-01](https://user-images.githubusercontent.com/27288153/233930935-ef69654f-6272-4199-873e-233d37b7b4ac.png)

![rotation object-03](https://user-images.githubusercontent.com/27288153/233930969-fc386a18-edd4-41f1-abf6-b73af146fdf9.png)


![Screenshot 2023-04-24 154406](https://user-images.githubusercontent.com/27288153/233931556-2d1ae811-f6dc-4359-9983-e746595e5bc6.png)

![rotation-object-04](https://user-images.githubusercontent.com/27288153/233930998-8be0f6a5-f549-4333-8a83-3e295975ee0e.png)

![image](https://user-images.githubusercontent.com/27288153/233931665-e79993fe-0e97-407b-98d7-ae0609cba55c.png)

**Comment by yuleicul** [comment]
> User can further rotate the structure around the center using handle. All elements of the rotation tool rotate along with selected fragment. 
>
> <img width="261" alt="rotation" src="https://user-images.githubusercontent.com/18439849/230181767-f97c9b65-286b-477e-a8ab-48e9b2c3501d.png">

Another question is, in Figma we can see that, while rotating, labels are **horizontal** rather than rotating along with selected fragment.
![image](https://user-images.githubusercontent.com/27288153/233932282-bc188b3e-9082-4451-a86b-b41e33507e43.png)

**Comment by yuleicul** [comment]
> > User can further rotate the structure around the center using handle. All elements of the rotation tool rotate along with selected fragment.
> 
> 
> Another question is, in Figma we can see that, while rotating, labels are **horizontal** rather than rotating along with selected fragment. 

Keep labels **horizontal** when they're rotating
