### ISSUE TITLE
Using paste tool (or new template tool) - clearing the canvas causes console errors

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2091]
**Steps to Reproduce**
1. Open browser console
2. Paste a molecule
3. Click on "clear canvas"

**Actual behavior**
Multiple type errors appear in the console

**Expected behavior**
Errors should not appear in the console

**Screenshots**
![212008181-5f3116c8-be19-468e-907a-cc6cd95f8acd](https://user-images.githubusercontent.com/101649391/212273511-f710f6fb-e321-454b-9691-e152a7bc89c3.gif)

**Ketcher version** 
v2.8.0

**Additional context**

**Comment by Nitvex** [comment]
Issue is NOT reproduced in v2.7.0-rc.9
