### ISSUE TITLE
getMolfile in v3000 format

### ISSUE THREAD

**Issue by debboutr** [epam/ketcher#21]
It would be nice to have the ability to `getMolfile` from ketcher in v3000 format from this [line](https://github.com/epam/ketcher/blob/c9ee5d3b874e29961ab8d57c96dc3c7ad47942e3/src/script/index.js#L40). Wouldn't it be as simple as adding an arg which can be passed as an option to the `stringify` function?
```
function getMolfile(v3000) {
	return molfile.stringify(ketcher.editor.struct(),
		{ ignoreErrors: true,
                  v3000: v3000
                }
        );
}
```

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.
