### ISSUE TITLE
All structures on the canvas are cleaned up if Clean Up function is applied to a part of one structure 

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/ketcher#210]
**Affected Version:** Standalone

**Steps to Reproduce:**

### Scenario1

1. Create two benzene structures.
2. Attach single bonds to the left structure.
3. Attach single and double bonds to the right structure.
4. Distort the structures.
5. Select a part of one structure using Lasso Selection.
6. Click 'Clean Up' button.

### Scenario#2
1. Create several structures. 
2. Create R-Group labels in the different parts of the structures.
3. Distort the structures. 
4. Select a part of one structure sing Lasso Selection.
5. Click 'Clean Up' button.

### Scenario#3
1. Create several structures with different atom symbols. 
2. Set attachment points on different symbols.
3. Distort structures. 
4. Select a part with attachment point of one structure.
5. Click 'Clean Up' button.

### Scenario#4
1. Create a chain structure.
2. Distort the created structure.
3. Select a part of the structure.
4. Click 'Clean Up' button.

### Scenario#5
1. Create 3-5 structures.
2. Distort the structures.
3. Select a part of one structure.
4. Click 'Clean Up' button.

**Expected Result:**
Only the selected part of the structure is leaned up.

**Scenario#1**
![2020-12-28_10h50_07](https://user-images.githubusercontent.com/75974843/103198889-85dfe980-48fa-11eb-80b8-4683a1574a4f.gif)

**Scenario#2**
![2020-12-28_10h46_36](https://user-images.githubusercontent.com/75974843/103198812-5204c400-48fa-11eb-8526-9223c7dae0b1.gif)

**Scenario#3**
![2020-12-28_11h02_18](https://user-images.githubusercontent.com/75974843/103199575-31d60480-48fc-11eb-89dd-e094f9036f47.gif)

**Scenario#4**
![2020-12-28_11h28_52](https://user-images.githubusercontent.com/75974843/103201133-33093080-4900-11eb-9481-20ff0bfb6926.gif)

**Scenario#5**
![2020-12-28_11h55_10](https://user-images.githubusercontent.com/75974843/103206142-360a1e00-490c-11eb-8cc7-0e0b3179f3c7.gif)

**Actual Result:**
All structures on the canvas are cleaned up when Clean Up function is applied to the part of one structure.

**Comment by ElenaKlepova** [comment]
**Related issue:** [Indigo#275](https://github.com/epam/Indigo/issues/275)

**Comment by AlexanderSavelyev** [comment]
related to #224

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.
