### ISSUE TITLE
'Check Structure' tool not displays some of warnings in Standalone mode

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#211]
**Affected Version:** _Standalone_
**Steps to Reproduce:**
_Scenario 1._
1. Create structure with query bonds.
2. Click 'Check Structure' button.
**Expected Result:**
"Query warning: Structure contains query features" message appears.
**Actual Result:**
"No errors found" message appears.

_Scenario 2._
1. Open 'all_atom_properties.mol' file from Templates.
2. Click 'Check Structure' button.
**Expected Result:**
"Query warning: Structure contains query features", "Radical warning: Structure contains 3 atoms with radical electrons",
"Stereochemistry warning: Structure has stereochemistry errors" messages appears.
**Actual Result:**
"warning: Structure contains radicals" message appears.

**The following warnings were also found missing:**
- Query warning
- Radical warning
- Stereochemistry warning
- Chirality warning
- Pseudoatom warning
- R-Groups warning

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/293

**Comment by AndreiMazol** [comment]
Retested. The bug is still reproduced.

**Comment by AndreiMazol** [comment]
Fixed in release/2.2

**Comment by Svetlana-Asinovskaia** [comment]
The main problem has been fixed. 'Check Structure' tool displays warnings in Standalone mode now. 
The text of the warnings differs from what was mentioned in the steps of the bug report 
(Radical warning: Structure contains radicals,(13,15,17), Stereochemistry warning: Structure contains stereocenters with undefined stereo configuration).
The problem with incorrect stereochemistry warnings will be solved within the task https://github.com/epam/ketcher/issues/455. There will be also an additional enhancement concerning R-Group warnings.
