### ISSUE TITLE
Position newly added bond so that mouse cursor is over its atom

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#2111]
When user selects bond tool and clicks on empty space of canvas, the newly added bond is positioned so that its center appears under mouse cursor. 
![image](https://user-images.githubusercontent.com/18439849/213524378-9d53df82-86ea-48ac-a144-593c6e3cf4b5.png)
If user doesn't move mouse cursor and clicks again, the bond switches from single to double and from double to triple. 
![image](https://user-images.githubusercontent.com/18439849/213525337-96be3646-73ab-496f-b36d-b14bda5d2a61.png)

Instead the newly added bond should be positioned so that one of its ends (atoms) appears under mouse cursor.
![image](https://user-images.githubusercontent.com/18439849/213525136-4487ab5a-603f-43fb-8090-0cb5c075b6f0.png)
In such a case additional clicks will lead to adding new bonds to the same atom.
![image](https://user-images.githubusercontent.com/18439849/213525743-cbc92761-1766-4ccf-8d1d-69e4a77600af.png)
 

#184005652

**Comment by Zhirnoff** [comment]
Newly added bond is positioned so that its center appears not under mouse cursor

https://github.com/epam/ketcher/assets/62464241/979be922-20a2-48cf-aecc-a9d4c2d77d08
