### ISSUE TITLE
Numeric fields in 'Calculated Values' contains information only till 3 decimal places. 

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#212]
**Affected Version:** _Standalone_
**Steps to Reproduce:**
1. Create some structure, for example, benzene.
2. Click 'Calculated Values' button.
3. Click on drop down list at the right side of 'Molecular Weight' field and change value to '7 decimal places'.
4. Click on drop down list at the right side of 'Exact Mass' field and change value to '7 decimal places'.

**Expected Result:**
p.3,4 - in text field correct information appears with 7 decimal places.

**Actual Result:**
After 3 decimal place only zeros appear.
![calc](https://user-images.githubusercontent.com/75974465/103205467-a9129500-490a-11eb-9a80-860720e84183.jpg)

**Comment by SunFellow** [comment]
Rounding happens in the very UI dialog. 
See:
Ketcher\packages\ketcher-react\src\script\ui\dialog\mainmenu\analyse.jsx#114:
```
  render() {
    const { values, round, onAnalyse, onChangeRound, ...props } = this.props
    return (
...
                <FrozenInput
                  value={
                    values ? roundOff(values[item.key], round[item.round]) : 0
                  }
                />
```
where `roundOff` is at lines#136-140:
```
function roundOff(value, round) {
  if (typeof value === 'number') return value.toFixed(round)

  return value.replace(/[0-9]*\.[0-9]+/g, str => (+str).toFixed(round))
}
```
and `round` is defined at lines#145-148:
```
    round: {
      roundWeight: store.options.analyse.roundWeight,
      roundMass: store.options.analyse.roundMass
    }
``` 
and options are defined in Ketcher\packages\ketcher-react\src\script\ui\state\options\index.js#33-34:
```
export const initOptionsState = {
...
  analyse: {
    values: null,
    roundWeight: 3,
    roundMass: 3
  },
```
So, just change 3 to 7 here.

**Comment by SunFellow** [comment]
Or rather, the effect is caused by that the `value` is initially rounded to 3 digits and later even change to 7 digits by the controls on the right hand, the value is still rounded to 3 and is not recalculated (that's anyway is undesirable). So need to change the data structure to remember the values initially returned from calls to Indigo functions.

**Comment by TomasLight** [comment]
@SunFellow, No, it's not correct. Values already have only 3 decimal digits, before rounding.

**Comment by TomasLight** [comment]
We receve trimmed data from IndigoWorker here:
ketcher\packages\ketcher-standalone\src\infrastructure\services\struct\standaloneStructService.ts#509
```
const calculatedProperties = JSON.parse(msg.payload)
```

**Comment by SunFellow** [comment]
Found the root cause. Completely depends on epam/Indigo#296
