### ISSUE TITLE
Hover effect doesn't appear after clicking on bonds or atoms

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2123]
**Steps to Reproduce**
Scenario 1:
1. Select bond tool
2. Add bond to canvas
3. Don't move the cursor

Scenario 2:
1. Select bond tool and add a bond to canvas
2. Move the cursor slightly so the hover effect appears
3. Click on the bond again

**Actual behavior**
There is no hover effect on the bond, same applies to clicking on atoms

**Expected behavior**
Bond has hover effect without moving the cursor
![image](https://user-images.githubusercontent.com/41272128/214300161-a443d871-7c03-4e24-8179-ddfd4f34d3e6.png)

**Comment by KonstantinEpam23** [comment]
NOTE: this is relevant not only for bonds, but for atoms as well
Looks like the hover effect is always hidden after clicking on canvas. We would like to keep the hover effect w/o having to move the mouse after click.
