### ISSUE TITLE
Opening file with a superatom label saved in RXN v3000 format removes a custom s-group

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2143]
**Steps to Reproduce**
1. Open Ketcher
2. Create reaction or open from [ketcher (37).zip](https://github.com/epam/ketcher/files/10535196/ketcher.37.zip)
3. Press S-Group tool and select Na and Cl
4. In S-Group Properties window select Type->Superatom, Name->sodium chloride and press Apply
5. Save file in RXN v3000 format
6. Open saved file

**Actual behavior**
The custom s-group disappears in the opened file.

**Expected behavior**
File with the superatom label saved in RXN v3000 format opens without errors as saved, the custom s-group is present.

**Screenshots**

https://user-images.githubusercontent.com/101649391/216015685-2a7cd50b-7c52-47e8-b9c2-73b8f5441601.mov

**Ketcher version** 
[Version 2.7.0-rc.10](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

**Comment by Nitvex** [comment]
Will be done on Indigo side. So closing this issue as not planned.

**Comment by Zhirnoff** [comment]
Will be tested after the fix on the Indigo side. Approximately in build 1.11.0-rc.1
