### ISSUE TITLE
Incorrect atom label for selected atom

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#2159]
**Steps to Reproduce**
1. Paste structure "C=N"
2. Select only N atom (by selection tool)
3. Right click on N and press "Edit selected atoms..."

**Actual behavior**
Label is "C"

**Expected behavior**
Label should be "N" since only N was selected

**Desktop (please complete the following information):**
 - OS: Win
 - Chrome

**Ketcher version** 
2.8.0-rc.2

**Comment by KonstantinEpam23** [comment]
Double-clicking on atom has correct behaviour, only context-menu is affected
