### ISSUE TITLE
Always display enhanced stereo information for atoms

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#2160]
**Background**
If a user designates a stereocenter as "AND" or "OR", it is not always clear on canvas since the stereo label (e.g. "AND enantiomer") does not show which atom has enhanced stereo

**Solution**
if "ignore-chiral-flag"=true (see #2161)
Always display enhanced stereo information for atoms (&1, or1, etc).

**Examples**

* Paste structure ```CC[C@@H](C)CCCC```
* Change Enhanced stereochemistry for stereo atom to AND
* Ketcher should display the enhanced stereo &1

![image](https://user-images.githubusercontent.com/7427808/215844870-1f212cb9-74a8-4699-9be6-f55cd6ea9c83.png)

* Change Enhanced stereochemistry for stereo atom to OR
* Ketcher should display the enhanced stereo or1

![image](https://user-images.githubusercontent.com/7427808/215845111-676641c8-f2cb-4aa0-ace6-0d832bdf089a.png)

**Comment by ansivgit** [comment]
If "ignore-chiral-flag"=false (by default) we leave the current behavior
