### ISSUE TITLE
Add ignore-chiral-flag parameter to ketcher settings

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#2161]
**Background**
Chiral flag is a legacy property from MDL molfiles. It should not be used

**Solution**
* Add a parameter ```Ignore the chiral flag``` inside Settings/Stereochemistry. Check box, default off. Location after "Text of Mixed flag"
* Add help text for mouse hover "Ignore chiral flag while loading from molfiles. By default all the stereo will be ABS"
* Add API parameter ```ignoreChiralFlag``` (Boolean; default=false) which can be changed during loading Ketcher editor
* Update help documentation for the flag behavior using this document
[ignore_chiral_flag.pdf](https://github.com/epam/ketcher/files/10743177/ignore_chiral_flag.pdf)

[ignore_chiral_flag.docx](https://github.com/epam/ketcher/files/10743178/ignore_chiral_flag.docx)

* if   ```ignoreChiralFlag``` = true 
  * input structures are treated as ABS until any enhanced stereo is defined.
  * do not display any labels ( "ABS" or "AND Enantiomer" etc) 
  * all enhanced stereo should be displayed always (related to #2160)
  * saving into molfile v2000 should set chiral flag = 1 (see doc file)

**Comment by KonstantinEpam23** [comment]
As part of implementation for this task we made a change to `ketcher.setSettings()` api that allows you to set 'ignoreChiralFlag' property.
Example of usage: `ketcher.setSettings({ ignoreChiralFlag: true })`
