### ISSUE TITLE
Change attachment point visualization to IUPAC style

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#2165]
**Background**
Current attachment point visualization is different from IUPAC (e,g, from rendering to PNG) 

**Solution**
* Make visualization of attachment points the same as in rendering to PNG/SVG
* The visual representation is for the R-group attachment points (APO) see the screenshots below
* if there is 1 bond (single or double) attached then angle should be 120
* if there is 1 triple bond attached, then angle should be 180
* there are 2+ bonds attached then make bisector between bonds
* The following rules for the show/not show label
if all primary attachment points => do not display
if at least one attachment point is secondary => show labels 1,2 near the curve line (see screenshots)

**Additional context**
All examples can be found in [examples.zip](https://github.com/epam/ketcher/files/10558047/examples.zip)

* example1 (1 attachment point)
![image](https://user-images.githubusercontent.com/7427808/216068500-ae4804f3-c5c1-4bb5-bce2-82d1e5b69395.png)
* example2 (1 attachment point connected to single bond)
![image](https://github.com/epam/ketcher/assets/7427808/7f4c961c-7608-4d06-9f06-1c916bc40c5b)dd01e0244dd2.png)
* example3 (2 attachment points)
![image](https://user-images.githubusercontent.com/7427808/216072227-87cf4835-2e74-447d-ba3d-5c6ee95ca298.png)
* example4 (1 triple bond attached)
![image](https://github.com/epam/ketcher/assets/7427808/87d95174-8323-475b-af01-51b1ee7c3637)

#184325922

**Comment by PetrKurkin** [comment]
Selection and visualization of the attachment point:
![Attachment point selection](https://user-images.githubusercontent.com/125649799/219609843-8e8e55b3-d459-48bd-8d54-98dde51787bd.png)
Attachment point in SVG
![Attachment point](https://user-images.githubusercontent.com/125649799/219609871-b83237a8-79e7-46d9-b667-b94dc2961bf5.svg)
![Attachment point selected](https://user-images.githubusercontent.com/125649799/219610632-9f0b8109-f2fe-4a32-b377-601472568e34.svg)
![Attachment point hover](https://user-images.githubusercontent.com/125649799/219610644-91684891-606a-4b12-a745-763f9f0ee4b7.svg)

**Comment by Nitvex** [comment]
It is required to check that structures rendered correctly in both canvas and templates modal.

**Comment by Nitvex** [comment]
Drawing numbers ("1" and "2" on the third screenshot) are out of scope of this issue.

**Comment by kaluginserg** [comment]
How we should render different attachment points? Primary and secondary?

Top attachment point - **Primary**
Left attachment point - **Secondary**

Old implementation:
![Screenshot 2023-06-03 at 13 38 10](https://github.com/epam/ketcher/assets/6398891/1c5d3cd5-fa78-4e22-9bd3-de016b494022)

New implementation (WIP):
![Screenshot 2023-06-03 at 13 41 45](https://github.com/epam/ketcher/assets/6398891/6892d6cc-f036-46e3-bf18-c50a4afd8760)

@Konstantin1996

**Comment by AlexanderSavelyev** [comment]
it should be done with numbers the same as PNG/SVG render

**Comment by kaluginserg** [comment]
### Result of the Pull request (The scope of the issue):
1) If there is only one Primary Attachment point on the canvas:

| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2023-06-06 at 08 07 42](https://github.com/epam/ketcher/assets/6398891/25fd6e61-859a-436a-b9c8-30668ad45eaa) | ![Screenshot 2023-06-06 at 08 07 16](https://github.com/epam/ketcher/assets/6398891/dc02cc6d-9d85-4191-8ee7-bf22b1a53f8a) |


2) If there is only one Secondary Attachment point on the canvas:

| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2023-06-06 at 08 13 23](https://github.com/epam/ketcher/assets/6398891/6e79549e-efed-4175-89e6-e6eb4ab20e87) | ![Screenshot 2023-06-06 at 08 07 16](https://github.com/epam/ketcher/assets/6398891/dc02cc6d-9d85-4191-8ee7-bf22b1a53f8a) |

3) If there are several Attachment points with different types on the canvas:

| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2023-06-06 at 08 16 41](https://github.com/epam/ketcher/assets/6398891/fc5eb968-fabb-4a86-8620-322c8cdbc46e) | ![Screenshot 2023-06-06 at 08 17 35](https://github.com/epam/ketcher/assets/6398891/f54371bc-1af0-475d-bf99-abc296ad07d4) |


4) If there are two Attachment points on the same atom (Primary and Secondary simultaneously) on the canvas:

| Before  | After |
| ------------- | ------------- |
| ![Screenshot 2023-06-06 at 08 21 30](https://github.com/epam/ketcher/assets/6398891/ae5068bf-08ff-4936-bce9-382dbe86b1e1) | ![Screenshot 2023-06-06 at 09 25 16](https://github.com/epam/ketcher/assets/6398891/93afef1c-f94f-421f-b9d1-eaf2a5ffc93f) |

 ### Out of Scope (What is not done and should be part of another issue):
- Hover state
- Ability to select Attachment point
- Ability to remove the Attachment point without using the tool "attachment point" and without a dialog box.

**Comment by kaluginserg** [comment]
Implemented additional condition:
In case of only one bond and only one attachment point connected
![Screenshot 2023-06-22 at 17 06 43](https://github.com/epam/ketcher/assets/6398891/27a9e64b-0a5d-494a-b259-9e28698052ac)
@Zhirnoff FYI
