### ISSUE TITLE
Add attachment points rendering to the functional group window

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#2167]
**Background**
Functional groups window does not show attachment points.

**Solution**
* Change the functional groups to include attachment point and change rendering. 
* Will require the #2165 to be implemented first
* Attachment point should be rendered for the atom which is currently used in SD file to attach to a molecule
* If add structure to the canvas - attachment point should be removed

#184325922

**Comment by Nitvex** [comment]
Incorporated by:
https://github.com/epam/ketcher/issues/2467
https://github.com/epam/ketcher/issues/2165
