### ISSUE TITLE
List atom of one structure is changed to Single atom after Clean Up is applied to another structure

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/ketcher#217]
**Affected Version:** _Standalone, Remote, release\2.1_

**Steps to reproduce:**

1. Create 2 structures. 
2. Attach List atom to one structure.
3. Distort the created structures.
4. Select one structure without the list atom.
5. Click 'Clean Up' function.

**Actual Result:**
The unselected List atom is changed to Single atom after Clean Up function.
![2020-12-28_13h47_09](https://user-images.githubusercontent.com/75974843/103209074-38bc4180-4913-11eb-8235-ba1b8fe6cf7c.gif)

**Expected Result:**
The unselected List atom is not changed after Clean Up function.

**Comment by ElenaKlepova** [comment]
Related issue [Indigo #278](https://github.com/epam/Indigo/issues/278)

**Comment by AllaZhbanova** [comment]
The issue is not reproducible on v.2.4

https://user-images.githubusercontent.com/93334478/141675057-f8fb30fd-f26e-474c-96a9-99482d2e21ff.mp4

**Comment by AllaZhbanova** [comment]
Fixed, tested 2.4
