### ISSUE TITLE
library.svg file for templates does not seem to be used

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2177]
**Background**
library.svg file seems to be storing pre-rendered svg templates from library.sdf
At the moment the templates sdf file includes bindings to library.svg file, but it does not seem like the prerendered elements are being used, meanwhile the file weighs around 2.5MB and slows down initial page loading.
<img width="743" alt="Screenshot 2023-02-06 at 11 31 31" src="https://user-images.githubusercontent.com/101649391/216948986-4661a7f0-94fc-4603-9353-7fedac855795.png">

**Solution**
Investigate if library.svg file is used, if it is - introduce gzip and caching on the infrastructure level for this file, if not - remove the file and do not request it from the client side.

**Comment by KonstantinEpam23** [comment]
Could relate to #2598

**Comment by rrodionov91** [comment]
library.svg usage was removed in https://github.com/epam/ketcher/issues/900
It needs to remove file.
