### ISSUE TITLE
When selected S-Group/Data S-Group right click on an atom or bond opens S-Group Properties window

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2180]
**Steps to Reproduce**
1. Open Ketcher
2. Create structure on canvas
3. Select S-Group and make right click on atom or bond
4. Select Data S-Group and make right click on atom or bond

**Actual behavior**
When selected S-Group/Data S-Group right click on an atom or bond opens S-Group Properties window

**Expected behavior**
When selected S-Group/Data S-Group right click on an atom or bond opens context menu for atom or bond

**Screenshots**

https://user-images.githubusercontent.com/62464241/216975222-1d5d316b-4d67-46a0-9673-5f64034355b8.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by yuleicul** [comment]
I guess this one will be fixed in the scope of #1996
