### ISSUE TITLE
The descriptor overlaps the structure after Layout

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/ketcher#219]
**Affected Version:** _Standalone, Remote, release\2.1_

**Steps to reproduce:**

1. Open the file 
[descriptors.zip](https://github.com/epam/ketcher/files/6561764/descriptors.zip)
2. Click 'Layout' button some times (5-6).

**Actual result:**
The descriptor moves to the center of the structure and overlaps it.
![2020-12-28_16h15_41](https://user-images.githubusercontent.com/75974843/103216839-17198500-4928-11eb-87fb-ac344ca008d4.png)

**Expected result:**
The descriptor does not overlap the structure.

**Comment by AleksandrPokrovskii** [comment]
Need to retest

**Comment by nseufulina** [comment]
Release/2.3 The issue is closed as fixed.
