### ISSUE TITLE
'Calculated Values' calculate values for all elements on canvas if they are located separately

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#220]
**Affected Version:** _Standalone_
**Steps to Reproduce:**
1. Click on 'Cl' atom and place it on canvas.
2. Repeat p.1 with 'N' and 'Br'.
3. Click 'Calculated Values' button.

**Expected Result:**
Information about HCl, NH4 and HBr displays separately using ;
![ClNBr](https://user-images.githubusercontent.com/75974465/103218157-5d241800-492b-11eb-8fa1-6d32480c336b.jpg)

**Actual Result:**
Information displays for all canvas without separation.
![ClNBr2](https://user-images.githubusercontent.com/75974465/103218187-7200ab80-492b-11eb-947b-f82d70852ead.jpg)

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/295

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.
