### ISSUE TITLE
SVG/PNG: Reaction arrows are not visible without structures at preview and in saved files

### ISSUE THREAD

**Issue by sqhl** [epam/ketcher#2237]
download this video，arrow not work。

https://user-images.githubusercontent.com/32098764/219602972-a07f1d78-1f21-46c5-981a-90776062bc1a.mp4

Reference file with all arrows: [All Arrows.zip](https://github.com/epam/ketcher/files/15365436/All.Arrows.zip)
Expected result: 
![image](https://github.com/epam/ketcher/assets/26869421/2eba82d9-424d-4287-a115-ef432903652e)

**Comment by Zhirnoff** [comment]
Hello! @sqhl 
Thanks for your feedback! We are very glad that you use Ketcher and leave comments. But unfortunately, we did not see the video on your link. If the problem still persists for you, record a new video and describe the steps to reproduce.

**Comment by sqhl** [comment]
Thanks for your reply! @Zhirnoff 

It looks like a bad video↑，but I still have some trouble using it：

1.One arrow exist，unable to export。
2.Different arrows cause export exceptions。

[](https://user-images.githubusercontent.com/32098764/220037482-96f69f88-de6d-4af3-a98f-32a4285faa2c.mov)

**Comment by Zhirnoff** [comment]
Related Indigo issue: https://github.com/epam/Indigo/issues/1044

**Comment by Zhirnoff** [comment]
Bug fixed by https://github.com/epam/Indigo/issues/1044
