### ISSUE TITLE
Clicking outside context menu applies currently selected tool

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2247]
**Steps to Reproduce**
1. Open Ketcher
2. Add 'Benzene' on canvas and select 'Phosphorus'
3. Make right-click on atom or bond for context menu
4. Click outside context menu on canvas 

**Actual behavior**
Click outside 'right-click menu' add current selected tool on canvas

**Expected behavior**
Click outside 'right-click menu' only close it.

**Screenshots**

https://user-images.githubusercontent.com/62464241/220131836-b9903456-fa3c-4f08-84c3-abe7e90cc892.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**

**Comment by yuleicul** [comment]
More examples:

- Erase
  ![ketcher-cm-at-bug-1](https://user-images.githubusercontent.com/27288153/220844670-a7cccdad-ea96-4a23-8fbd-49f9d7774135.gif)

- Single Bond  
  ![ketcher-cm-at-bug-2](https://user-images.githubusercontent.com/27288153/220844845-550f6178-c466-401b-8098-f0bac1f3c2d9.gif)

- Chain
  ![ketcher-cm-at-bug-3](https://user-images.githubusercontent.com/27288153/220844984-a54d2e13-b0e9-4e17-85b6-fd7b77d7d397.gif)

- Charge
  ![ketcher-cm-at-bug-6](https://user-images.githubusercontent.com/27288153/220845883-c56082af-7b73-4038-96ef-7cc82edcf93b.gif)

- Template
  ![ketcher-cm-at-bug-7](https://user-images.githubusercontent.com/27288153/220846761-2f26b347-f840-4040-bd80-e076de7a9e84.gif)
