### ISSUE TITLE
Add support for stereo CIP values in ket format

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#225]
**Background**
Internal ketcher format should contain information about CIP calculated values. The current model with S-groups should be replaced by the internal format

**Acceptance criteria**
- Don't show tooltip for CIP values
- CIP data must be moved from s-group properties to atom properties
- Ketcher must still show CIP labels
- Available CIP labels: bonds: [E,Z,M,P] atoms: [R,S,r,s]

**Comment by vanoprenko** [comment]
Indigo version should be updated in scope of this task
