### ISSUE TITLE
Unable to add a bond to a Functional Group by Bond Tool

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2257]
**Steps to Reproduce**
1. Open Ketcher
2. Add any Functional Group on canvas
3. Select 'Single Bond'
4. Attach to Functional Group
Note: also reproduce with 'Chain'

**Actual behavior**
Unable add a bond to a Function Group

**Expected behavior**
Able add a bond to a Function Group

**Screenshots**

https://user-images.githubusercontent.com/62464241/220338351-8f14035d-ac62-48af-881f-cfff0e189a96.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Additional context**
Related issue: https://github.com/epam/ketcher/issues/2229

**Comment by yuleicul** [comment]
Please take a look at this @St-Permiakov 

https://user-images.githubusercontent.com/27288153/223309861-59360b3f-d68d-4041-8499-d83a2af47b9d.mp4

**Comment by KonstantinEpam23** [comment]
The code that was merged seem to break the chain tool. We need to address this issue separately.

**Comment by yuleicul** [comment]
What's the right behavior when I'm trying to add a bond to a terminal functional group, like
![image](https://user-images.githubusercontent.com/27288153/224884392-fbfe29eb-2407-40fd-9d33-dbe587819b16.png)

**Comment by yuleicul** [comment]
> One clarification, what's the right behavior when I'm trying to add a bond to a terminal functional group, like ![image](https://user-images.githubusercontent.com/27288153/224884392-fbfe29eb-2407-40fd-9d33-dbe587819b16.png)

As discussed in the async meeting, the answer is to add a new bond that connects two functional groups.
