### ISSUE TITLE
When user selects and moves atom on Functional Group or Salt it doesn't replaces atom in the structure 

### ISSUE THREAD

**Issue by d-mrzv** [epam/ketcher#2273]
**Steps to Reproduce**
1. Open Ketcher
2. Add Functional Group or Salt to the canvas 
3. Add an atom to the canvas
4. Using selection tool select the atom and move it over FG or Salt

**Actual behavior**
Atom doesn't replace FG or Salt, it displayed on the canvas over the FG or Salt

**Expected behavior**
Atom replaces a FG or Salt

**Screenshots**

https://user-images.githubusercontent.com/124911723/221199332-941b5c81-9d18-4241-99ae-30e545c840d2.mov

**Desktop (please complete the following information):**
 - OS: MacOS 13.2 (22D49)
 - Browser: Chrome
 - Version: Version 110.0.5481.100 (Official Build) (x86_64)

**Ketcher version** [e.g. v2.4.2]. 
[Version 2.8.0-rc.4]

**Additional context**
Related discussion: https://github.com/epam/ketcher/discussions/2315

**Comment by Zhirnoff** [comment]
Bug reproduces in 2.10.0-rc.1
https://user-images.githubusercontent.com/62464241/234938521-6d59158a-9273-4c41-8781-aa8bcc6a8a0e.mp4
