### ISSUE TITLE
After replace tooltip from a previously 'Functional Groups' or 'Salts and Solvents' is displayed on hover

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2294]
**Steps to Reproduce**
1. Open Ketcher
2. Add to canvas 'Functional Groups' or 'Salts and Solvents'
3. Select any 'Functional Groups'
4. Click on 'Functional Groups' or 'Salts and Solvents' on canvas
5. Hover cursor over abbreviation

**Actual behavior**
After replace tooltip from a previously 'Functional Groups' or 'Salts and Solvents' is displayed on hover

**Expected behavior**
Tooltip should display an image corresponding to its abbreviation

**Screenshots**

https://user-images.githubusercontent.com/62464241/222482166-d1e397f3-94e9-4794-bde9-aa7fd531b614.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.8.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)

**Test case**
[EPMLSOPKET-10106] 
[EPMLSOPKET-10107]

**Additional context**

**Comment by KonstantinEpam23** [comment]
Reproduced in 2.7.2; moving to 2.9.0-rc.1
