### ISSUE TITLE
When user hovers cursor with any template selected near the border of the canvas scrollbars appear

### ISSUE THREAD

**Issue by d-mrzv** [epam/ketcher#2325]
**Steps to Reproduce**
1. Go to https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
2. Select any template from template palette or custom templates
3. Move mouse cursor to any border of the canvas

**Actual behavior**
Scrollbars appear when cursor with structure is near the border of the canvas

**Expected behavior**
Either not let user to move structure when it overlaps the canvas borders or automatically scroll the canvas

**Screenshots**
https://user-images.githubusercontent.com/124911723/224676562-3212bfff-4c76-4457-9bee-37ce86918a96.mov

**Desktop (please complete the following information):**
 - OS: macos 13.2.1 (22D68)
 - Browser Chrome
 - Version 110.0.5481.177 (Official Build) (x86_64)

**Ketcher version** [e.g. v2.4.2]. 
[Version 2.9.0-rc.3]

**Test case**
EPMLSOPKET-10120
Related issue: https://github.com/epam/ketcher/issues/2114

**Comment by Zhirnoff** [comment]
The structure shifts on the canvas when trying to select something from the toolbar when the template is selected

https://user-images.githubusercontent.com/62464241/224689622-4b46196d-3c70-4497-8653-7d8c44ed23f8.mp4
