### ISSUE TITLE
Add peptide monomers to canvas (by click)

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2332]
**Background**

This task covers adding peptide monomers to the canvas.
This is a _basic_ version (add by click), more advanced (drag and drop) version of adding peptide monomers to canvas will be described separately.

**Requirements**

1. User adds peptide monomers to canvas in the following way:

- User clicks on a peptide monomer in the peptide library
- Selected peptide monomer becomes highlighted
- When a user clicks at the canvas selected peptide monomer is added to the place of a click
- After selected peptide monomer is added to the canvas, the monomer remains selected in the library and can be added again

2. Peptide monomers are added to the canvas in a form of a regular hexagon
3. Peptide monomers are added to the canvas in a color that corresponds to the color in the peptide library

**Comment by PetrKurkin** [comment]
Adding monomers on canvas flow pictures

<img width="792" alt="1  Hover on peptide" src="https://user-images.githubusercontent.com/125649799/230160067-f319e556-a844-4c0a-baee-1c4c3451da61.png">
<img width="792" alt="2  Peptide selected" src="https://user-images.githubusercontent.com/125649799/230160073-6531ad90-7bc2-47d0-85d3-d28f83820b5f.png">
<img width="792" alt="3  Peptide added" src="https://user-images.githubusercontent.com/125649799/230160075-30250896-7818-488b-b550-e1c9da6e735f.png">
<img width="792" alt="4  Another peptide selected" src="https://user-images.githubusercontent.com/125649799/230160076-f7807527-1436-4267-ba4d-17b8a1d4f8fe.png">
<img width="792" alt="5  Another peptide added" src="https://user-images.githubusercontent.com/125649799/230160063-7746ca82-109d-4bfe-941f-d7cfbb32bb5b.png">

**Comment by PetrKurkin** [comment]
Updated view of monomers
<img width="792" alt="5  Another peptide added" src="https://user-images.githubusercontent.com/125649799/233052318-3bbc77de-68e3-4bd3-a10d-9124969dfcb2.png">

**Comment by MartaWilliams** [comment]
Tested 
![2023-10-24_12h48_07](https://github.com/epam/ketcher/assets/82752700/e919a4eb-b10a-4c14-8cbd-2be7a59a70e8)
