### ISSUE TITLE
Structure with S-Group data pasted with error

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2336]
**Steps to Reproduce**
1. Open Ketcher
2. Add Chain on canvas
3. Select S-Group and select whole Chain structure
4. In pop-up window add Field name and Field value
5. Press Apply
6. With 'Selection tool' select all structure and press CTRL+C
7. Press CTRL+V for paste structure

**Actual behavior**
Error Message
Cannot read properties of undefined (reading 'isExpanded')
Note: the same behavior when you apply data from sections: Data, Multiple group, SRU polymer, Superatom to the whole structure
**Expected behavior**
After the Paste action, all S-Group data appear without changes.

**Screenshots**

https://user-images.githubusercontent.com/62464241/224960831-6efa43ce-51a8-4adb-9e64-9a0563952734.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Test case**

**Additional context**

**Comment by KonstantinEpam23** [comment]
This should be fixed by: https://github.com/epam/ketcher/pull/2331
@Nitvex @Zhirnoff
