### ISSUE TITLE
Pasting contracted Functional Group abbreviation throw console error

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2337]
**Steps to Reproduce**
1. Open Ketcher
2. Select any Functional Group and add to canvas (not expand)
3. Select with 'Selection tool' whole FG abbreviation and press CTRL+C
4. Press CTRL+V

**Actual behavior**
A functional group appears under a cursor, but when you try to place on a canvas, it disappears and an error appears in the console
Note: expanded FG paste without errors
**Expected behavior**
Functional Group abbreviation paste on a canvas without errors

**Screenshots**

https://user-images.githubusercontent.com/62464241/224976151-a1468d0f-1ffe-40c4-b05f-1c2802added6.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Test case**
Add test case number (in EPMLSOPKET-* format) if bug was found during test case run.

**Additional context**

**Comment by KonstantinEpam23** [comment]
@Zhirnoff @Nitvex perhaps this is resolved by https://github.com/epam/ketcher/pull/2331 ?

**Comment by d-mrzv** [comment]
Behaviour is the same when user opens file with contracted FG and trying to add it on a canvas.

https://user-images.githubusercontent.com/124911723/225054194-e7893e92-11b4-47b7-a3a1-f3fb2be31084.mov
