### ISSUE TITLE
CTRL+SHIFT+0 hotkey not working for 'Zoom 100%'

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2353]
**Steps to Reproduce**
1. Open Ketcher
2. Add any structure on canvas
3. Zoom in CTRL+=
4. Press CTRL+SHIFT+0 for Zoom 100%

**Actual behavior**
Zoom level does not change to 100% when the CTRL+SHIFT+0 hotkey is pressed.
Note: Maybe it is only Windows issue. On Mac it is working.
**Expected behavior**
Zoom level should change to 100% when the CTRL+SHIFT+0 hotkey is pressed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Zhirnoff** [comment]
Reproduced in v2.9.0-rc.4

**Comment by Nitvex** [comment]
It is proposed to change shortcut to `CTRL+0` due to problems with Windows 10
