### ISSUE TITLE
"Select" tool for Macromolecules editor

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2360]
1. There is a “Select” button
2. "Select" tool allows to capture monomers displayed on the canvas: if a user clicks on "Select" button and then select specific area with monomers/monomer chains, all operations applied to this group should affect every item in this group, e.g. remove, moved around canvas
4. When items are selected, they become highlighted
5. "Select" is a tool that is selected by default (initially and after clicking esc)
6. Monomers enter hover or select states when a cursor or select box respectively touches their shape (hexagonal for peptides)
7. Bonds enter hover or select states when a cursor or select box respectively touches a select area around them (+5px from both sides of the bond)

**Comment by PetrKurkin** [comment]
Select tool interaction with monomers
<img width="1093" alt="Select" src="https://user-images.githubusercontent.com/125649799/233014031-91662766-21fa-41ea-9d29-76c9f448b8f5.png">

Select states for monomers and bonds 
<img width="920" alt="Hover and select" src="https://user-images.githubusercontent.com/125649799/233014043-efae6acd-84f9-4a62-a670-20637fbf5c1e.png">

**Comment by MartaWilliams** [comment]
Tested 
![2023-10-24_12h03_47](https://github.com/epam/ketcher/assets/82752700/eb4843af-0a31-4b34-9396-4d5b698b4e8e)
![2023-10-24_12h04_29](https://github.com/epam/ketcher/assets/82752700/4a299d9c-3684-4583-90aa-1b421adf534e)
![2023-10-24_12h05_25](https://github.com/epam/ketcher/assets/82752700/be34dad3-0b2f-437a-9a07-55cfd9ca6355)
