### ISSUE TITLE
Macro: "Zoom" tool

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2369]
1. There is a zoom button 
2. Zoom button has 3 options

- zoom in
- zoom out
- 100%

3. When user clicks to zoom in, system zooms in to the center of the current view (limits and step similar to ketcher)
4. When user clicks to zoom out, system zooms out of the center of the current view (limits and step similar to ketcher) 
5. When user clicks 100% the system returns to 100% scale

**Comment by Zhirnoff** [comment]
Manual tests added to the Automation table
