### ISSUE TITLE
"Erase" tool for macromolecules editor

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2370]
1. There is an “Erase” button
2. "Eraser" tool allows to remove monomers and bonds displayed on the canvas:

- If user has selected an item/items on the canvas and then clicks "Erase", this selected item/items disappear(s)
- If a user clicks on "Eraser" button and then click on a specific monomer, this monomer + all the bonds linked to it disappear from the canvas 
- If a user clicks on "Eraser" button and then click on a specific bond, this bond disappears from the canvas

**Comment by MartaWilliams** [comment]
Tested 

https://github.com/epam/ketcher/assets/82752700/9baa0440-676f-44d6-bc88-a6b9c71cfe87
