### ISSUE TITLE
Can't open v3000 mol file with assigned Alias

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2379]
**Steps to Reproduce**

1. Open Ketcher
2. Add Chain on canvas
3. Double-click any atom
4. Type any text in the 'Alias' field (for example, 'alias123')
5. Click 'Save as' button
6. Select MDL Molfile v3000 and save
7. Open saved file

**Actual behavior**
Error Message
Convert error! Cannot deserialize input JSON.

**Expected behavior**
Files opens. Alias is located on the atom to which we assigned it

**Screenshots**
![2023-03-16_23h43_26](https://user-images.githubusercontent.com/62464241/225748238-7e5faef1-f7c6-431e-bfd8-99f32e124c36.png)
![2023-03-16_23h46_02](https://user-images.githubusercontent.com/62464241/225748763-963cd470-92c6-43ec-af2b-b2a2a37b59bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by KonstantinEpam23** [comment]
Need to add "alias" field to Ketcher schema.
