### ISSUE TITLE
Bracket is missing when opening a file RXN v2000/v3000 files with 'S-Group Properties Type = Multiple group'

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2389]
**Steps to Reproduce**

**Scenario1**
1. Launch Ketcher
2. Open RXN v2000 file with 'S-Group Properties Type = Multiple group [Multi.zip](https://github.com/epam/ketcher/files/11001722/Multi.zip)

**Actual behavior**
Pop-up message:
WARNING!
Unsupported S-group type found. Would you like to import structure without it? And file opens without one of S-Group bracket.
![2023-03-17_16h20_26](https://user-images.githubusercontent.com/62464241/225916344-df0a92c0-de61-44e2-b945-62b2363264c2.png)
![2023-03-17_16h09_46](https://user-images.githubusercontent.com/62464241/225916743-3cdb38b5-c747-40dc-b270-0f83391d87c0.png)

**Expected behavior**
File opens without pop-up message. With all added S-Group Properties and brackets on its places
![2023-03-17_16h08_28](https://user-images.githubusercontent.com/62464241/225917418-6920d40d-27ea-4999-9eb7-6c445e1c4f76.png)

**Scenario2**
1. Launch Ketcher
2. Open RXN v3000 file with 'S-Group Properties Type = Multiple group [rxnV3000Multiple.zip](https://github.com/epam/ketcher/files/11001809/rxnV3000Multiple.zip)

Actual and Expected results same as for RXN v2000

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.3](https://lifescience.opensource.epam.com/ketcher/index.html)

**Test case**
[EPMLSOPKET-1903]

**Comment by KonstantinEpam23** [comment]
Check all supported sgroup types work correctly when opening from file.

**Comment by Zhirnoff** [comment]
Test cases already written. Its regression bug.

**Comment by Zhirnoff** [comment]
Pre-tested.
![2023-08-30_12h01_18](https://github.com/epam/ketcher/assets/62464241/70ea3b72-3858-42a6-bc45-fa4e76989f93)

**Comment by vitaepam** [comment]
Files now is opening, but looks like saving of such files does not work, @Zhirnoff do we need to create a new bug maybe?
<img width="1440" alt="Screenshot 2023-09-04 at 10 36 19" src="https://github.com/epam/ketcher/assets/109075831/6d26b933-00ab-4a37-a4a2-43830842d7ad">
