### ISSUE TITLE
Is there any implementation of bingo SQL Server on MySQL, such as Bingo MySQL

### ISSUE THREAD

**Issue by huanshiwushuang** [epam/ketcher#239]
I didn't find a good enough plug-in.

Is there any implementation of bingo SQL Server on MySQL, such as Bingo MySQL.

Or there are other open source free MySQL plug-ins that can be replaced, thank you

**Comment by AlexanderSavelyev** [comment]
Unfortunately, there is no Bingo for MySQL available. As far as I remember there was no support of custom indexes inside the database. But we verified it about 5 years ago, and it might be a case that the support was added. We will add to our todo list to test the index customization for MySQL
