### ISSUE TITLE
Add possibility to hide buttons on control panel

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#244]
Standalone mode does not support recognize functionality now. It necessary to have hide the following buttons to not confuse end users:

- recognize button (while wasm  module does not support it)
- 3D Miew viewer

Scope:
1. Hide buttons
2. Add configuration property to allow to hide any buttons (and exclude required dependencies from resulted bundle)

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.

**Comment by KseniiaSemenishcheva** [comment]
After disсussion issue is reopened.
Needs interface changes
