### ISSUE TITLE
"Bond" tool

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2452]
1. After user clicks on bond button in the tools panel, only bonds creation operations are possible to perform on the canvas
2. Bond tool should allow to link monomers by dragging a straight line from one monomer and dropping it to another
3. If there are no monomers on canvas and user clicks on canvas with bond tool selected, nothing happens (no line appears)
4. If there is only one monomer, user should be able to drag the bond from its center

**Comment by OlZhur** [comment]
No need to create a separate task for a bond. All requirements how to create connection points between monomers are described in the corresponding tasks:
[Create RNA chain using monomers on canvas #2547](https://github.com/epam/ketcher/issues/2547)
[Create peptide chain (HELM style) - Center-to-Center #2334](https://github.com/epam/ketcher/issues/2334)
[Choose connection points using visual representation (HELM Style) - Point to Point #2925](https://github.com/epam/ketcher/issues/2925)
[Support connection points selection by users #2883](https://github.com/epam/ketcher/issues/2883)
