### ISSUE TITLE
RNA Monomer library - draft

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2462]
1. RNA tab should consist of the monomers from the file attached where "Monomer Type" is "RNA"
2. Inside RNA tab there should be a split to 4 separate tabs: - UX tbd

- Combined Nucleotide **_-or RNA?_**
- Sugars
- Bases
- Phosphates

_Combined Nucleotide tab_
Has 5 nucleotides:
"Phosphate"-"Ribose"-"Adenine" (A)
"Phosphate"-"Ribose"-"Cytosine" (C)
"Phosphate"-"Ribose"-"Guanine" (G)
"Phosphate"-"Ribose"-"Thymine" (T)
"Phosphate"-"Ribose"-"Uracil" (U)
(These are real monomer names from 'Name' field)
and presets saved by user

_Sugars tab_
Sugars contains those monomers which 'MonomerNaturalAnalogCode' is 'R'

_Bases tab_

- Bases contains those monomers which 'MonomerNaturalAnalogCode' are {'A', 'C', 'G', 'T', 'U', 'X'}
- Each Base group has its own color

_Phosphates tab_

Phosphates contains those monomers which 'MonomerNaturalAnalogCode' is 'P'

3. Each RNA monomer in the library should be presented in the from of a square

[HELMMonomers.zip](https://github.com/epam/ketcher/files/11162956/HELMMonomers.zip)

**Comment by OlZhur** [comment]
Obsolete.
Requirements regarding the RNA library and builder are described in the following tasks:
[RNA builder. Collapsing panel with RNA components](https://github.com/epam/ketcher/issues/2751)
[RNA Builder. Accordion component](https://github.com/epam/ketcher/issues/2748)
[RNA builder. Edit RNA mode](https://github.com/epam/ketcher/issues/2759)

**Comment by MartaWilliams** [comment]
Tested

**Comment by Zhirnoff** [comment]
Autotests written
