### ISSUE TITLE
Rotation Tool: display predefined rotation angles and current angle

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#2463]
Enhance the rotation tool introduced in scope of #2090, so that user can see predefined rotation angles' marks as well as current rotation angle and can easier rotate the selection on needed angle. The rotation tool should work as follows:

1. Once user clicks the rotation handle and rotation mode is activated, the rounded rectangle should be replaced with a circle. Center of the circle should be in the center of rotation, circle diameter equal to the height of replaced rectangle. The rotation handle should not change its position while switching from selection to rotation mode and back.
2. The following predefined angles should be marked on the rotation circle: -90, -60, -45, -30, 0, 30, 45, 60, 90
3. Once user starts rotating the structure, the set of angles shown should always cover [-90 - +90] range relatively to the handle position, e.g. if the structure is rotated for 60 degrees, user should see -30, 0, 30, 45, 60, 90, 120, 135, 150
4. Current rotation angle should be displayed at starting position (0 degree). 
5. Once user releases left mouse button, the rotation mode is deactivated and selected fragment stays in its new position (rotated). Rotation circle should be replaced with rounded rectangle (handle on top). 

<p align="center">
<img width="300" alt="hover-handle" src="https://user-images.githubusercontent.com/18439849/230630688-c7ad3b27-71f6-4398-b7b8-4ae67b1fb72a.png"> 
</p>

<p align="center">
<img  width="500" alt="rotation-start" src="https://user-images.githubusercontent.com/18439849/230630912-91472746-fc34-4078-ab16-9763c70d7205.png"> 
</p>

<p align="center">
<img width="250" alt="rotation in progress" src="https://user-images.githubusercontent.com/18439849/230634356-4f2f350b-a6f6-40df-86a0-61fc19e93e5b.png">
</p>

#184121704

**Comment by yuleicul** [comment]
> 3. Once user starts rotating the structure, the set of angles shown should always cover [-90 - +90] range relatively to the handle position, e.g. if the structure is rotated for 60 degrees, user should see -30, 0, 30, 45, 60, 90, 120, 135, 150
> 
> <p align="center">
> <img width="250" alt="rotation in progress" src="https://user-images.githubusercontent.com/18439849/230634356-4f2f350b-a6f6-40df-86a0-61fc19e93e5b.png">
> </p>

One question here, according to ''_the set of angles shown should always cover [-90 - +90] range relatively to the handle position_", angles of the image above should be like

![rotation-angles](https://user-images.githubusercontent.com/27288153/234489584-da3ceb0f-001d-4622-a0ec-671db52812d1.png)

**Comment by yuleicul** [comment]
> > 3. Once user starts rotating the structure, the set of angles shown should always cover [-90 - +90] range relatively to the handle position, e.g. if the structure is rotated for 60 degrees, user should see -30, 0, 30, 45, 60, 90, 120, 135, 150
> > 
> > 
> > <img alt="rotation in progress" width="250" src="https://user-images.githubusercontent.com/18439849/230634356-4f2f350b-a6f6-40df-86a0-61fc19e93e5b.png">
> 
> One question here, according to ''_the set of angles shown should always cover [-90 - +90] range relatively to the handle position_", angles of the image above should be like
> 
> ![rotation-angles](https://user-images.githubusercontent.com/27288153/234489584-da3ceb0f-001d-4622-a0ec-671db52812d1.png)
> 
> This looks a bit wierd huh... Which one is correct?

It should show "nice" degrees between [currentDegree - 90, currentDegree + 90]
