### ISSUE TITLE
Ketcher needs to correctly parse and represent attachment point information for super atoms for mol v2000 format

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2467]
## Background
At the moment Ketcher does not parse "SAP" (Superatom Attachment Point) instructions for s-group attachment points.

## Solution

1. deserialization `M SAP` instruction for v2000 mol files should be supported (reading from file)
1. serialization `M SAP` instruction for v2000 mol files should be supported (saving to file)
1. Template Tool - all templates should have attachment point information. (Include SAP information into the functional groups SD files)
1. Implement ketcher behavior with attachment points: when connecting the sgroup to the existing structure (use information form `M SAP` to select attachment point).
1. Show the attachment point (the same way as RGoup #2165 ) only for tooltips and template windows (do not display this information for the expanded superatom)

Link to the CTFiles format explanation: http://c4.cabrillo.edu/404/ctfile.pdf (2005)
Section: "Superatom Attachment Point", page 33, 
#### Format
`M SAP sssnn6 iii ooo cc`

#### Example
`M  SAP   1  1   2   0   `

#### Full example of mol v2000 file
```

  MJ230800                      

  3  2  0  0  0  0  0  0  0  0999 V2000
   -4.3752    1.6736    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6607    1.2611    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9463    1.6736    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
M  STY  1   1 SUP
M  SAL   1  3   1   2   3
M  SMT   1 Ac
M  SAP   1  1   2   0   
M  SDS EXP  1   1
M  END
$$$$

```

#184325922

**Comment by AlexanderSavelyev** [comment]
> *.sdf files need to be updated in scope of this issue. @AlexanderSavelyev to provide an example @KonstantinEpam23, please provide detailed description for the issue

done

**Comment by kaluginserg** [comment]
Just link to the CTFiles format explanation: http://x3dna.bio.columbia.edu/data/ctfile.pdf (2013)

**Comment by kaluginserg** [comment]
What is done in the #2768 (visualisation):
| In toolbar  | In tempates |
| ------------- | ------------- |
| ![Screenshot 2023-06-21 at 12 30 07](https://github.com/epam/ketcher/assets/6398891/13291e56-dbcf-4835-a5ec-14f716de71c2) | ![Screenshot 2023-06-21 at 12 29 50](https://github.com/epam/ketcher/assets/6398891/19689133-6c28-4ae6-8593-01391603e68a)  |

Also replaced old logic to connect to the first atom in the sgroup - now it's based on the attachment point information inside sgroup.
