### ISSUE TITLE
When you try to add a structure to a canvas with an expanded functional group, an EDIT ABBREVIATION window appears

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2471]
**Steps to Reproduce**
1. Launch Ketcher
2. Open file [ketcher.zip](https://github.com/epam/ketcher/files/11190114/ketcher.37.zip)
3. Try put it on canvas

**Actual behavior**
The structure is under mouse cursor and when you try to put it on canvas, EDIT ABBREVIATION window appears.
Note: Perhaps this is due to the fact that the Oxygen atom is located close to the Carbon atom. The Oxygen atom is highlighted and, apparently, when clicked on canvas, editing of the abbreviation is triggered.
**Expected behavior**
A structure with an expanded Functional Group is added to the canvas

**Screenshots**
![2023-04-10_14h25_04](https://user-images.githubusercontent.com/62464241/230892822-98b99b74-17d4-42f7-acc1-1f3f2c8e1af6.png)
![2023-04-10_14h23_58](https://user-images.githubusercontent.com/62464241/230892851-a4ded299-c591-47b4-9cad-4df8c10bfa87.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by kaluginserg** [comment]
this bug is affected by changes https://github.com/epam/ketcher/issues/2110. Continue investigating.

**Comment by kaluginserg** [comment]
Found the details. 
I checked how Ketcher works now, for a couple of cases. 
Screenshot:
![Screenshot 2023-05-22 at 16 29 15](https://github.com/epam/ketcher/assets/6398891/e27cb4a2-979c-4438-815a-61ab014d5ec7)

A) Whole structure is from the clipboard (PASTE tool triggered). Oxygen and Carbon are not considered to be merged, as there is a space between them. 
So the 'Paste' functionality works fine.

B) Whole structure is from the clipboard (PASTE tool triggered). [Incorrect current implementation] Oxygen and Carbon are considered to be merged (there is a highlight for AttachmentPoint).
So the 'Paste' functionality doesn't work well for this case.

The decision, TODO:
We should allow users to put the structure with minor issues (possible attachment points between structures inside Clipboard) on Canvas. But if there is a conflict with the existing structure on Canvas - should be handled in the old way (it must be prevented).

**Comment by kaluginserg** [comment]
An additional issue found with **tool select** and moving:

https://github.com/epam/ketcher/assets/6398891/462ab6a2-4f3b-41a6-b078-d418048ff2e2

Video explanation:
_first case_: When we move the structure **without** potential attachment point (merge Oxygen and Carbon) - everything is going as expected, after finishing moving, the structure is the same as before.

_second case_: When we move the structure **with** a potential attachment point (merge Oxygen and Carbon) - after completing the move we can see that merge has triggered and the structure has changed.

Decision TODO:
Need to allow a user to move an existing structure with a potential attachment point without triggering a merge inside the structure that has been moving.

**Comment by kaluginserg** [comment]
An additional issue with the current implementation found with the tool Paste and SGroup:

https://github.com/epam/ketcher/assets/6398891/3600847d-2b1f-40b3-9efd-ca1fc4175fb5


Video explanation:
third case: has two scenarios - one when we open a file and paste SGroup from the file, and also it is valid for cases with simple copy/paste logic.

Decision TODO:
Methinks we should consider this as a bug also. 
@KonstantinEpam23 any suggestions?

**Comment by KonstantinEpam23** [comment]
@kaluginserg  Hmm, this is definitely a bug, I believe we might already have a task for this.

@Zhirnoff can you please double-check

**Comment by Zhirnoff** [comment]
I have looked at this behavior. The user should be able to copy a functional group and attach to a structure atom(CTRL+C then CTRL+V) or cut a functional group and attach to an atom(CTRL+X then CTRL+V)

https://github.com/epam/ketcher/assets/62464241/f9ef508f-007e-4097-836c-4445fccf2d9b
