### ISSUE TITLE
Create CHEM chain (HELM style) - Center-to-Center

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2475]
**Background**
This task covers creation of chains from chem monomers with 2+ connection points.
This task covers creation of a bond from center to center with opportunity for a user to choose connection points.
This task has HELM style naming for connection points (R1, R2, R3, etc). 

**Requirements**

_**Chem monomers**_
1. When user connects 2 chem monomers and one of this monomers has 2 free connection points, a window with suggested options for connection points choice appears
2. In this window user should have an opportunity to choose connection points for those monomers that have 2+ free connection points

**Comment by PetrKurkin** [comment]
Flow for choosing connection points via modal:

One or both monomers have a busy default connection point  
<img width="1311" alt="1  Dragging a bond" src="https://github.com/epam/ketcher/assets/125649799/824ba92d-df61-493e-9b7f-f73a845fb8e3">

Modal shows when the bond is dropped on the second monomer
<img width="1311" alt="2  Bond dropped" src="https://github.com/epam/ketcher/assets/125649799/b9ff55d5-9404-4276-a466-e3b282ac0189">

Modal should appear above or below the bond, depending on bond position.  Modal can be drugged around. Canvas also can be moved with a hand tool.
<img width="1460" alt="Modal position" src="https://github.com/epam/ketcher/assets/125649799/872d8731-086d-4f5d-8d66-3bb54fa62880">

Other examples of modal
3 connection points (most common case)
<img width="378" alt="3 connection points" src="https://github.com/epam/ketcher/assets/125649799/c4dc162d-9a0f-410c-965c-c8ffde48017b">

3 and 6 connection points with long titles
<img width="378" alt="3 and 6 connection points with long titles" src="https://github.com/epam/ketcher/assets/125649799/3aae473e-b4c3-4937-b49b-17ff223c595e">
