### ISSUE TITLE
Pressing Clear Canvas with Reaction Arrow under mouse cursor causes errors in DevTool console

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2483]
**Steps to Reproduce**
1. Open Ketcher and DevTool browser console
2. Select Reaction Arrow and place on canvas
3. With Selection Tool select Reaction Arrow and press CTRL+C
4. Press CTRL+V and with Reaction Arrow under mouse cursor press Clear Canvas button

**Actual behavior**
Uncaught TypeError in DevTool console

**Expected behavior**
Reaction Arrow under mouse cursor and on canvas dissapears

**Screenshots**

https://user-images.githubusercontent.com/62464241/231869861-bf4a9290-e230-4271-ba87-8499791bfe7d.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.6](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by KonstantinEpam23** [comment]
If this will turn out too complex for a quick fix - move to Refined backlog
