### ISSUE TITLE
Create nucleotides in the RNA library - draft

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2488]
**Background**
A nucleotide is one of the structural components (monomer), or building blocks, of DNA and RNA. A nucleotide consists of a base (one of four chemicals: adenine, thymine, guanine, and cytosine) plus a molecule of sugar and phosphoric acid

**Requirements**

- Nucleotide combination in "Combined Nucleotide tab" has the following structure:
Sugar(Base)Phosphate 
- Default combination is R(A)P (exact names from 'MonomerName' field)
- When user clicks on a base monomer in "Base" tab, this monomer becomes highlighted and its name ('MonomerName') appears in the nucleotide combination on the base place
- When user clicks on a sugar monomer in "Sugar" tab, this monomer becomes highlighted and its name ('MonomerName') appears in the nucleotide combination on the sugar place
- When user clicks on a phosphate monomer in "Phosphate" tab, this monomer becomes highlighted and its name ('MonomerName') appears in the nucleotide combination on the phosphate place
- After all 3 components are chosen, combination appears in presets? -  **UX tbd** 
- User should have an opportunity to save combined nucleotide: - **UX tbd**
 "Save" -> goes to presets?
- When user clicks on "Combined Nucleotide tab", saved nucleotides become available in presets **- ?**

**Comment by OlZhur** [comment]
Obsolete.
Requirements regarding the RNA library and builder are described in the following tasks:
[RNA builder. Collapsing panel with RNA components](https://github.com/epam/ketcher/issues/2751)
[RNA Builder. Accordion component](https://github.com/epam/ketcher/issues/2748)
[RNA builder. Edit RNA mode](https://github.com/epam/ketcher/issues/2759)

**Comment by MartaWilliams** [comment]
Tested with https://github.com/epam/ketcher/issues/2759
