### ISSUE TITLE
When atoms are selected, pressing atoms hotkey opens a modal window instead of an instant replacement

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2490]
**Steps to Reproduce**
1. Open Ketcher
2. Add few atoms on canvas (e.g. Nitrogen)
3. Select all atoms with 'Selection tool'
4. Press 'O' hotkey 

**Actual behavior**
Modal window 'Atom properties' appears.
If in 'Atom properties' modal window we enter atom symbol and click Apply, then this atom appears under the cursor, but it cannot be applied when clicking on canvas.

**Expected behavior**
Selected atoms are replaces with those assigned to the hotkey.
Selected tool remains active and the atom does not appear under mouse cursor.
**Screenshots**

https://user-images.githubusercontent.com/62464241/232770379-54c75122-2239-4256-92d3-f516b9928147.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.9.0-rc.6](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by gairon** [comment]
The problem with "Selected tool remains active and the atom does not appear under mouse cursor." will be done in https://github.com/epam/ketcher/issues/2428
