### ISSUE TITLE
Add RNA monomers to canvas (by click)

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2507]
**Background**
This task covers adding sugars, bases and  phosphates separately to canvas and full RNA monomers (combination of Sugar-Base-Phosphate)

**Requirements**
User should be able to add to canvas:

- Sugar monomers (separately)
- Base monomers (separately)
- Phosphate monomers (separately)
- Combinations: Sugar-Base, Sugar-Phosphate
- Full RNA monomers (combination of Sugar-Base-Phosphate)

User adds monomers to canvas in the following way:

1. User clicks on a monomer/RNA in the RNA library
2. Selected monomer/RNA becomes highlighted
3. When a user clicks at the canvas selected monomer/RNA is added to the place of a click
4. When a selected monomer is added to the canvas, the monomer remains selected in the library and can be added again

- Sugar monomers are added to the canvas in a form of a square with rounded edges
- Base monomers are added to the canvas in a form of a rhombus
- Phosphate monomers are added to the canvas in a form of a circle
- Monomers are added to the canvas in a color that corresponds to the color in the library

**Comment by nightnick** [comment]
![Basic](https://github.com/epam/ketcher/assets/27892118/03f0565e-9b63-4472-bc89-2c40301dfd19)
![Choice](https://github.com/epam/ketcher/assets/27892118/0a51860f-f8de-42f8-bc34-65b9b6428501)
![Error](https://github.com/epam/ketcher/assets/27892118/1e4352b2-392a-45ab-b85c-132a7dc7ae3c)

**Comment by MartaWilliams** [comment]
Tested 
![2023-10-24_12h18_56](https://github.com/epam/ketcher/assets/82752700/5d92adee-d2b6-4523-a754-8ce19f284bad)

**Comment by Zhirnoff** [comment]
Autotests written
