### ISSUE TITLE
Add a marker on UI which shows if current molecule is valid or not

### ISSUE THREAD

**Issue by ensemenova** [epam/ketcher#251]
**User Story**
As a | Ketcher' user
-- | --
I want to | see indicator on UI when structure on canvas is incorrect
So that | I can understand that structure is not valid and I can't perform different operations with it

**Acceptance Criteria:**
1. Indicator displays always when Ketcher is launched and opened.
2. Indicator is on the bottom right corner of Ketcher on toolbar.
3. Indicator always check is structure on canvas valid or not.
4. When structure on canvas has mistakes than indicator is red.
5. When Structure on canvas is correct and valid - indicator is green.
6. If User hover mouse over the indicator - tooltip appears 'Structure has errors' (If indicator is red) and 'Structure is valid' (If indicator is green).
![2](https://user-images.githubusercontent.com/75974465/108067855-68b1d680-7072-11eb-9856-5579d0ceea3a.jpg)

![1](https://user-images.githubusercontent.com/75974465/108067853-6780a980-7072-11eb-80d1-5ab41dde2e68.jpg)

**Comment by AlexanderSavelyev** [comment]
don't agree on that enhancement. The marker should only appear for appropriate formats. Or there should be highlighting of specific atoms (e.g. if incorrect valence) This marker will require validation for each action which will affect performance
