### ISSUE TITLE
Incorrect rendering of superatom with multiple connection points

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2517]
**Steps to Reproduce**
**Scenario 1**
1. Open Ketcher
2. Add file [Superatom.zip](https://github.com/epam/ketcher/files/11297085/Superatom.zip) on canvas
3. Look at Superatom
Fixed in 2.10.0-rc.2

**Scenario 2**
1. Open Ketcher
2. Add file [Superatom.zip](https://github.com/epam/ketcher/files/11297085/Superatom.zip) on canvas
3. Select 'S-group Tool' and rename Superatom
Will be fixed in 2.11.0-rc.1

**Actual behavior**
Part of the structure disappears
![2023-04-21_18h19_53](https://user-images.githubusercontent.com/62464241/233673870-d06f7a73-95cd-4aa5-a9fc-81c6290c37c4.png)

**Expected behavior**
File opens with Superaton name and brackets
![2023-04-21_18h19_38](https://user-images.githubusercontent.com/62464241/233673878-a50f6777-56e7-4e7b-951b-3eeee6617f0f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.10.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Test case**
[EPMLSOPKET-[12599]

**Comment by Nitvex** [comment]
Bug is reopened due to the case, when a user renames pasted Superatom.
