### ISSUE TITLE
Update project npm dependencies to remove vulnerabilities

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2518]
At the moment running npm audit shows 10 high severity vulnerabilities, these need to be fix in .

In general it is a good idea to keep dependencies updated for several reasons:
- It can address known security vulnerabilities.
- It can fix bugs and improve stability .
- New versions of dependencies often come with performance improvements.
- It can ensure that application remains compatible with other libraries and tools that we use.

**Current npm audit output:**
```
# npm audit report

minimatch  <3.0.5
Severity: high
minimatch ReDoS vulnerability - https://github.com/advisories/GHSA-f8q6-p94x-37v3
fix available via `npm audit fix --force`
Will install serve@14.2.0, which is a breaking change
node_modules/serve-handler/node_modules/minimatch
  serve-handler  1.1.0 - 6.1.3
  Depends on vulnerable versions of minimatch
  node_modules/serve-handler
    serve  7.0.0 - 14.0.1
    Depends on vulnerable versions of serve-handler
    node_modules/serve

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install @svgr/rollup@7.0.0, which is a breaking change
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/rollup  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/rollup
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          node_modules/react-scripts

10 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by AlonNavon** [comment]
Hey @KonstantinEpam23,

We're part of a startup called Seal Security that mitigates software vulnerabilities in older open source versions by backporting/creating standalone security patches - enabling more straightforward remediation in cases like this. We created an `nth-check 1.02-sp1` that's vulnerability-free. As with all of our patches, it's open-source and available for free.

If relevant, check out [our GitHub repo](https://github.com/seal-community/patches/tree/main/npm/nth-check/1.0.2/sp1) if you wish to learn more, or start using our [app](https://app.sealsecurity.io).

Please feel free to reach us at [info@seal.security](mailto:info@seal.security) if you have any requests/questions.

**Comment by Zhirnoff** [comment]
Not tested by QA.
