### ISSUE TITLE
getting a "Cannot read properties of null (reading 'struct')" when clicking on the ketcher-canvas

### ISSUE THREAD

**Issue by andreassteffen** [epam/ketcher#2538]
I am using ketcher-react 2.8.0 and an instantiate it in my create-react-app using 

```
import {RemoteStructServiceProvider} from 'ketcher-core'
import {ButtonsConfig, Editor} from 'ketcher-react'
import {Ketcher} from 'ketcher-core'
import 'ketcher-react/dist/index.css'
import styled from '@emotion/styled'
import {StandaloneStructServiceProvider} from "ketcher-standalone";

const GridWrapper = styled('div')`
  height: 100vh;
  width: 100%;
  max-height: 100vh;
  max-width: 100%;
  overflow: hidden;
  display: grid;
  grid-template-columns: 1fr 270px 320px;
  grid-template-rows: 1fr;
  gap: 0px 0px;
  grid-template-areas: 'Ketcher Panel Output';
  & > div {
    border: 1px solid grey;
  }
`

const KetcherBox = styled('div')`
  grid-area: Ketcher;
  height: 500px;
`
const structServiceProvider = new StandaloneStructServiceProvider();


const MoleculeSketcher = () => {
    return (
        <GridWrapper>
            <KetcherBox>
                <Editor
                    key={1}
                    staticResourcesUrl={process.env.PUBLIC_URL}
                    structServiceProvider={structServiceProvider}
                    errorHandler={(err) => console.log(err)}
                    onInit={(ketcher: Ketcher) => {
                        ;(global as any).ketcher = ketcher
                    }}
                />
            </KetcherBox>
        </GridWrapper>
    )
}
export {MoleculeSketcher};
```

when clicking on the canvas of catcher I getting this error:

Cannot read properties of null (reading 'struct')
TypeError: Cannot read properties of null (reading 'struct')
    at Handler.onElementEdit [as f] (http://localhost:3000/static/js/bundle.js:124200:40)
    at PipelineSubscription.dispatch (http://localhost:3000/static/js/bundle.js:229805:65)
    at propsDialog$1 (http://localhost:3000/static/js/bundle.js:112312:38)
    at RGroupAtomTool.click (http://localhost:3000/static/js/bundle.js:112292:9)
    at useToolIfNeeded (http://localhost:3000/static/js/bundle.js:115580:26)
    at Handler.f (http://localhost:3000/static/js/bundle.js:115626:24)
    at DOMSubscription.dispatch (http://localhost:3000/static/js/bundle.js:229827:61)

Any help/suggestions much appreciated!

**Comment by KonstantinEpam23** [comment]
Hello @andreassteffen , thanks for creating this issue, can you please describe the exact steps required to reproduce the issue. Do you select any particular tool when clicking on the canvas? Are you clicking on an empty canvas or on a structure? etc.
Thank you!
