### ISSUE TITLE
Create RNA chain using monomers on canvas

### ISSUE THREAD

**Issue by KsenMs** [epam/ketcher#2547]
**Background:**
usually RNA should connect phosphate to sugar monomers

**Requirements:**

User selects bond tool and start creating a connection using the following rules (if appropriate attachment points are free)
* connect phosphate(R1) to sugar(R2) 
* connect sugar(R2) to phosphate(R1) 

User can connect any type of RNA monomers if there are free attachment points (only one point left), e.g.
sugar to sugar, phosphate to phosphate, base to base, etc

if there is no attachment point exist, then create a message (UX TODO)
if there are more than 1 attachment point, then create a modal window with ability to select a point (UX TODO)

**Comment by nightnick** [comment]
**Designs**
Basically the same as with regular monomers:
![Basic](https://github.com/epam/ketcher/assets/27892118/cad97740-bd9e-4cd2-9f89-dc02b68ef6ff)
![Choice](https://github.com/epam/ketcher/assets/27892118/84afcd6c-3750-4f24-80e1-3f29ee22d859)
![Error](https://github.com/epam/ketcher/assets/27892118/c3e0013a-5ba4-48d6-ac00-93102a1a02ce)

**Comment by nightnick** [comment]
![Choice 2](https://github.com/epam/ketcher/assets/27892118/8fa4ab42-0840-4a8d-a595-a518a786cb63)

**Comment by isidoraotasevic** [comment]
1. When we hover over nucleobase (RNA base) on canvas "ears" should appear. The same goes for phosphate group as well as sugar.

Sugar has 3 functional groups: R1, R2, R3.
R1=H
R2=H
R3=OH
-R3 group is used to connect with a nucleobase (RNA bases such as A,U,C,G).
-R2 is used to connect with phosphate group.
-R1 stays unattached
*This is how one RNA nucleotide looks like with all its parts (sugar, base, phosphate)
In a scenario where a user wants to build an RNA chain from left-right, the phosphate group from the previous RNA nucleotide will connect with a free R1 group of the other RNA nucleotide. And that is the pathway of connecting RNA monomers.

RNA bases have R1 group
R1=H
-R1 group can be used to connect with R3 part of sugar

Phosphate group
R1=OH
R2=OH

2. "Known" CHEMs are all other molecules not classified as peptides and RNA. They contain both structure and APs.

**Comment by OlZhur** [comment]
redundant task
