### ISSUE TITLE
Add indicator to inform users about execution of 'heavy' operations

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#255]
It is necessary to  show loading indicator to inform users about execution of the following operations:
- clean up
- layout
- aromatize
- dearomatize
- calculate CIP

**Comment by KseniiaSemenishcheva** [comment]
- During the operation listed above buttons should be disabled.
- Canvas should be disabled and spinner should displays on the center of canvas.
Prototype:
![Loading](https://user-images.githubusercontent.com/75974465/106279512-8fd46f80-624d-11eb-9962-9c94f95b6bc7.jpg)

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.
