### ISSUE TITLE
Right click menu shown for highlighted Functional Group instead of clicked

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2576]
**Steps to Reproduce**

**Scenario1**
1. Open Ketcher
2. Add two Functional Groups on canvas ( one expand )
3. Select with Selection tool expanded Functional Group
4. Make right click on contracted Functional Group abbreviation

**Actual behavior**
The right click menu is shown for highlighted Functional Group instead of the clicked Functional Group.

**Expected behavior**
When right clicking on a Functional Group that is not currently highlighted, the right click menu should be shown for the clicked Functional Group.

**Screenshots**

https://user-images.githubusercontent.com/62464241/236462235-1cd49b85-6bc5-4275-abd4-3e1256a91d53.mp4

**Scenario2**
1. Open Ketcher
2. Add two atoms on canvas
3. Select with Selection tool one atom
4. Make right click on another atom

**Actual behavior**
Context menu is shown as if both atoms were selected and from right side menu for bonds
![2023-05-05_16h11_35](https://user-images.githubusercontent.com/62464241/236469239-a361d8e8-4cd5-4084-84d9-f259a46ed82d.png)

**Expected behavior**
When right clicking on an atom that is not currently highlighted, the right click menu should be shown for the clicked atom.
![2023-05-05_16h11_54](https://user-images.githubusercontent.com/62464241/236469421-e0a72793-c437-4360-b080-99cabffa1c35.png)

**Scenario3**
1. Open Ketcher
2. Add structure on canvas (e.g. Benzene)
3. Select with Selection tool all structure
4. Make right click on any place on canvas

**Actual behavior**
Context menu is shown and structure is highlight

**Expected behavior**
Context menu is not shown and structure is unhighlight

**Scenario4**
1. Open Ketcher
2. Add two structures on canvas (e.g. Benzene)
3. Select with Selection tool one of structure
4. Make right click on atom of not highlighted structure

**Actual behavior**
Context menu is shown for selected structure and structure is highlight

**Expected behavior**
Context menu is shown for clicked atom and selected structure is unhighlight

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.10.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Note: work in v2.8.0

**Comment by yuleicul** [comment]
Unfortunately, I thought there would be a small problem with PR #2587 .

### Steps to Reproduce

1. Add any structure to the canvas, such as benzene
2. Click Select Tool, and select some atoms/bonds of the structure
3. Right click on one of the selected atoms/bonds

### Actual behavior
Right-click menu for single bond/atom appears

### Expected behavior
Right-click menu for selection appears

![context-menu](https://github.com/epam/ketcher/assets/27288153/5a457746-e791-4b81-8634-de92becf94af)
