### ISSUE TITLE
Draw selection outline correctly for hovered structures

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2595]
**Actual behaviour**
After introducing the new selection in #2088 if the structure is in an expanded s-group or is selected with the "fragment selection" tool and is hovered over - the bond selections will be drawn over atoms.
<img width="295" alt="Screenshot 2023-05-12 at 06 49 36" src="https://github.com/epam/ketcher/assets/101649391/903e938a-ebbd-4571-9f40-694542204bfe">
<img width="269" alt="Screenshot 2023-05-12 at 06 49 56" src="https://github.com/epam/ketcher/assets/101649391/f1fd825a-3b50-48c9-a013-6de52830d4a6">

**Expected behaviour**
Atoms should always be drawn above the bonds and the bond contours should not intersect atom contours.

**Comment by nightnick** [comment]
Please update the current behavior so that atom outline would not overlap the whole bond, but only its outline.
Ideally we want one united outline, without intersection within it. Maybe in next phase?
![image](https://github.com/epam/ketcher/assets/27892118/fd00a776-a9fb-4143-8652-6cb7fbbaf422)

**Comment by y-holik** [comment]
test cases are created
