### ISSUE TITLE
How to programatically clear ketcher's drawing area ?

### ISSUE THREAD

**Issue by sfialok98** [epam/ketcher#26]
I want to clear the Ketcher's drawing area programatically .
I tried ```ketcher.setMolecule('')``` but it throws BAD Request Error. 
How can we achieve this ?

**Comment by Vesdet** [comment]
Hi @sfialok98 , you can clear drawing area with using `ketcher.editor.struct(null)`.

**Comment by sfialok98** [comment]
Yes, that worked.
Thanks !!
