### ISSUE TITLE
Preview peptide monomers in Library

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#2600]
**Requirements**
Once hover on a peptide in the Library, a dialog window appears with a monomer preview.

![image](https://github.com/epam/ketcher/assets/128700628/84b49696-4ca5-41b9-a4b5-52f4d7d7c2c7)

**Comment by MartaWilliams** [comment]
Tested 
![2023-10-24_13h25_55](https://github.com/epam/ketcher/assets/82752700/e6c68b40-ce51-4c0a-8cf5-444107f05354)
![2023-10-24_13h26_05](https://github.com/epam/ketcher/assets/82752700/38864064-4155-46f1-8d39-263089bc5609)
![2023-10-24_13h26_22](https://github.com/epam/ketcher/assets/82752700/16b737a7-751b-405b-a641-0b00ff5fc711)
