### ISSUE TITLE
Transform global css styles into css modules

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#262]
In order to provide portability of react components at a high-level, it is necessary to split global styles into smaller pieces. 

In this ticket scope, the following dialogs' styles should be transformed into CSS modules and these components should be moved into the new /views directory. 
On the screenshot, I've highlighted buttons that should open refactored dialogs:
![image](https://user-images.githubusercontent.com/45556539/106433433-453b3900-6481-11eb-9a6c-5d7efc8ec923.png)

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.
