### ISSUE TITLE
Two dividing line between 'Edit...' and 'Single' bond in Bond context menu

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2623]
**Steps to Reproduce**
1. Open Ketcher
2. Draw Chain on canvas
3. Make right click on chain bond
4. Look at dividing line between 'Edit...' and 'Single' bond in the context menu

**Actual behavior**
There are two dividing line between 'Edit...' and 'Single' bond instead of one and a clickable place between them. After clicking on it, the context menu disappears.
![2023-05-18_19h57_12](https://github.com/epam/ketcher/assets/62464241/559f18f7-f1b9-48f2-9f50-e2bd7e47119f)

**Expected behavior**
There is one dividing line between 'Edit...' and 'Single' bond instead of two and no any clickable place between.
![2023-05-18_19h57_53](https://github.com/epam/ketcher/assets/62464241/b350ce3c-fb6b-4644-9479-d484843b7032)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.10.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

<img width="950" alt="image" src="https://github.com/epam/ketcher/assets/139227567/42659f20-9580-4f57-a804-759feddeafe4">
