### ISSUE TITLE
Rotation tool: cancel rotation by pressing "Escape" key

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2625]
**Solution**
User should be able to cancel rotation by pressing "Escape" key.
If "Escape" key is pressed while a structure is being rotated:
- the rotation should be cancelled and the structure revert to the original position it was in when rotation was started
- the structure should stay selected

**Example**
During rotation:
<img width="269" alt="Screenshot 2023-05-19 at 07 56 32" src="https://github.com/epam/ketcher/assets/101649391/b2e4203e-c8c4-4e46-ab78-d6f8944f3405">

After Escape key is pressed:
<img width="232" alt="Screenshot 2023-05-19 at 07 56 58" src="https://github.com/epam/ketcher/assets/101649391/f439dfbe-949f-4287-b502-801c145b2ab7">

**Comment by yuleicul** [comment]
@KonstantinEpam23  I'm wondering if Rotate Tool needs this feature
![image](https://github.com/epam/ketcher/assets/27288153/7c5f9c03-bef9-4287-bba5-d6f62a913ce3)

**Comment by KonstantinEpam23** [comment]
@yuleicul we are planning to remove this menu from toolbar altogether, so I dont think we need to support this behaviour right now for the rotate tool.
