### ISSUE TITLE
Unable to save the structure after clicking 'Save', an error appears

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2657]
**Steps to Reproduce**
1. Launch Ketcher
2. Open file [ketcher-comu.zip](https://github.com/epam/ketcher/files/11544053/ketcher-comu.zip)
3. Press 'Save' button

**Actual behavior**
Unable to save the structure after clicking 'Save', an error appears

**Expected behavior**
Able to save the structure after clicking 'Save' in various supported formats.

**Screenshots**
![2023-05-23_15h38_16](https://github.com/epam/ketcher/assets/62464241/8ed7bf41-dbd8-4345-ab70-1e1bdcff5b8f)
![2023-05-23_15h38_50](https://github.com/epam/ketcher/assets/62464241/26b45641-781f-4ab5-ab12-f302815d7166)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.10.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by gairon** [comment]
Probably the problem on the Indigo side. Waiting for them to check

**Comment by Zhirnoff** [comment]
The bug has been moved to Indigo side https://github.com/epam/Indigo/issues/1144
