### ISSUE TITLE
Add ketcherWindow.ketcher.getSmilesExt() method

### ISSUE THREAD

**Issue by robtree** [epam/ketcher#266]
As well the the current `getSmiles()` method, it would be helpful for Ketcher to expose a `getSmilesExt()` method which exports the current structure as an **Extended SMILES** string, just like the one offered by Save Structure > Extended SMILES.

**Comment by AndreiMazol** [comment]
Dear @robtree ,

We plan to review Ketcher object API and provide updates in the future release. It make sense to provide possibility to save rendered structure as any formats that are available by clicking on save button on UI.  Detailed information will be available on Wiki pages.

Best regards,
Ketcher team

**Comment by TomasLight** [comment]
@robtree, We did changed ketcher api, and now you can get extended smiles like:
```js
await ketcther.getSmiles(true)
```

and just smiles like bellow:
```js
await ketcther.getSmiles()
```

We;re going to add this information in release notes

**Comment by robtree** [comment]
That sounds great. Thank you for the update!

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.
