### ISSUE TITLE
Support "favorites" functionality for the monomer library

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2664]
**Background**
We would like to support an ability to add selected monomers to the "favorites" tab in the monomer library.

**Acceptance criteria**
- when user hovers over a monomer in the library - a greyed out star appears
- when hovering over the star - it changes color to yellow
- when clicking on a star it should persist in yellow color on the monomer item in the library and should also be saved to the "Favorites" tab
- monomers on the "favorites" tab should be persisted in local storage, so they are still available after page reload

<img width="851" alt="Screenshot 2023-05-24 at 10 36 21" src="https://github.com/epam/ketcher/assets/101649391/d2bceca2-18d4-4749-81b3-b987abcdeba8">

**Comment by MartaWilliams** [comment]
Tested with https://github.com/epam/ketcher/issues/2447
