### ISSUE TITLE
Highlight colors for Simple Objects do not match the new design

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2679]
**Steps to Reproduce**
1. Open Ketcher
2. Add Simple objects on canvas (e.g. Shape Ellips, Shape Rectangle, Shape Line)
3. Add Benzene ring and any atoms
4. Select all and look at selection colors

**Actual behavior**
Highlight colors for Simple Objects do not match the new design

**Expected behavior**
Highlight colors for Simple Objects is match the new design

**Screenshots**
![2023-05-25_14h14_44](https://github.com/epam/ketcher/assets/62464241/0a519768-a817-40d3-a907-69575be52dca)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.11.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Zhirnoff** [comment]
1) The color is lighter than that of templates and atoms. 
![2023-05-30_18h51_08](https://github.com/epam/ketcher/assets/62464241/fd350eb6-6532-4d16-b15a-8bbf7b356f79)

2) When selecting and hovering over an Ellipse or Rectangle, the inner area is highlighted. 
![2023-05-30_19h08_59](https://github.com/epam/ketcher/assets/62464241/17f39f16-134b-4fe1-98b6-bf825f26bbd2)

3) Points for changing the scale are filled with highlights, which makes them less noticeable.
![2023-05-30_19h07_41](https://github.com/epam/ketcher/assets/62464241/f75ad11a-30fa-4272-876b-af8999148a1e)
![2023-05-30_19h09_32](https://github.com/epam/ketcher/assets/62464241/ab33af2f-eaa2-441f-9193-42438d5e49d0)

**Comment by ViktoriaTkacheva** [comment]
When selecting and hovering over a word, the word is completely filled and the text disappears
 
![656a5503-3db0-49b5-bddf-511964031cf6](https://github.com/epam/ketcher/assets/139227567/75584456-828f-4f5a-846f-ade4977405e5)

![3d37acbf-40a6-4ed6-96e8-b09d5816f548](https://github.com/epam/ketcher/assets/139227567/e4c06277-7547-4373-9f19-96fcf3257b4d)
