### ISSUE TITLE
Selection box does not frame expanded Functional Groups and Salts

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2685]
**Steps to Reproduce**
1. Open Ketcher
2. Add Functional Groups and Salts abbreviations on canvas
3. Select all and expand

**Actual behavior**
Selection box does not frame expanded Functional Groups and Salts

**Expected behavior**
Selection box frame expanded Functional Groups and Salts

**Screenshots**
![2023-05-25_20h31_37](https://github.com/epam/ketcher/assets/62464241/e79d1010-1483-44d8-baa5-37f99fdbf970)
![2023-05-25_20h32_50](https://github.com/epam/ketcher/assets/62464241/ef0e7b8b-57e7-4c93-a4c4-e98aa859529f)
![2023-05-25_20h33_13](https://github.com/epam/ketcher/assets/62464241/daf7aea7-0f74-4c8c-b9a2-cdf60920f0dc)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.11.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by yuleicul** [comment]
Looks like it can't be reproduced in version 2.11.0-rc.2 Build at 2023-05-30; 13:27:00

https://github.com/epam/ketcher/assets/27288153/c676a647-623a-4db3-9c3e-dbb9648bca99

Could you please check again? @Zhirnoff

**Comment by Zhirnoff** [comment]
Not reproduces in 2.11.0-rc.2
