### ISSUE TITLE
Update ketcher toolbar icons

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2687]
**Solution**
Update icons for the following toolbar items:
- Calculate CIP
- Calculate values
- Single down
- Single up down
- Single up
- Text
- Open
- Save as
- 3D viewer
- Templates/Structure library

<img width="475" alt="Screenshot 2023-05-26 at 08 47 47" src="https://github.com/epam/ketcher/assets/101649391/6713115a-b50b-4166-a2c8-f494f653a9f6">

**Comment by KonstantinEpam23** [comment]
@PetrKurkin please attach the icon SVG files

**Comment by PetrKurkin** [comment]
@KonstantinEpam23 icons in svg

![Structure Library](https://github.com/epam/ketcher/assets/125649799/9bf5fa4f-2e41-4f6a-863f-3939564129b4)
![3d_viewer](https://github.com/epam/ke
![Calculated_values](https://github.com/epam/ketcher/assets/125649799/55f7cbfe-dff0-4466-a931-f82ee59d7f1e)
![Calculate_CIP](https://github.com/epam/ketcher/assets/125649799/5622af2c-bab9-4675-86fb-637b9e15516b)
![Open](https://github.com/epam/ketcher/assets/125649799/0554d083-4f70-4f78-9f82-ab60e41b4920)
![Save as](https://github.com/epam/ketcher/assets/125649799/152b6d32-ab4d-4b89-a123-09bf84e458ce)
![single up](https://github.com/epam/ketcher/assets/125649799/cd24270d-7e27-4db3-907c-2e01e6e38403)
![single down](https://github.com/epam/ketcher/assets/125649799/85afa04f-1411-475c-90ec-f19213df9893)
![single up_down](https://github.com/epam/ketcher/assets/125649799/026f7d55-d141-49b1-9733-ecf79e2bb6a0)
![Text](https://github.com/epam/ketcher/assets/125649799/977aafd6-6d96-41d6-83dd-4115a8a20fed)
tcher/assets/125649799/fb8478d1-988e-4895-97ce-8b43c044634d)

**Comment by Nitvex** [comment]
Attached "Calculate CIP" icon seems to be broken. Attaching fixed one:
![Calculate_CIP](https://github.com/epam/ketcher/assets/41272128/d76353d4-4658-4a06-b429-f87805998cc4)
