### ISSUE TITLE
Add comments to different coordinate systems

### ISSUE THREAD

**Issue by yuleicul** [epam/ketcher#2697]
**Background**
After zooming in or out the whole canvas, the positions of the cursor-following atom and the functional-group preview are incorrect.

Incorrect position of the cursor-following atom:

https://github.com/epam/ketcher/assets/27288153/3f55e4e5-9454-41e2-8c7f-3d9b107ef6f8

Incorrect position of functional group preview:

https://github.com/epam/ketcher/assets/27288153/e8dc73a7-ff3f-4160-b42d-33c595e25c5a

These bugs are somehow related to the coordinate conversion among different coordinate systems.

As we can see in `packages/ketcher-core/src/application/render/raphaelRender.js`, some functions such as`obj2view`, `view2obj`, and `page2obj` must be related to the coordinate conversion, but what they do is not clear to us.

**Solution**

1. To figure out what these coordinate systems exactly are.
2. Add comments or rename coordinate conversion functions to make them readable and clear to developers. 
3. Write a document if necessary.
4. Fix incorrect positions of cursor-following atom and functional-group preview

**Comment by yuleicul** [comment]
Hi @Nitvex @KonstantinEpam23 ! Could you please review this issue? Please feel free to give any advice and your concern

**Comment by kaluginserg** [comment]
Additional is described here: https://github.com/epam/ketcher/issues/2730
