### ISSUE TITLE
Update ketcher toolbar UI styles

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#2707]
**Solution**
Update styles of ketcher toolbars and other visual elements so they fit the new design.
<img width="1512" alt="Screenshot 2023-05-30 at 10 06 43" src="https://github.com/epam/ketcher/assets/101649391/f45504a1-bf7e-431e-b572-0b533e6c7223">

- Update top, left and bottom toolbar styles
- Update Right toolbar atom icon styles and icon arrangement
- Update colors, including background color

*Note* keep in mind an ability to hide buttons via ketcher settings/api

**Comment by PetrKurkin** [comment]
Toolbars:
<img width="436" alt="Toolbars" src="https://github.com/epam/ketcher/assets/125649799/8d1e7191-4876-419f-a69b-9fb24810ebbb">

Colors and states:
<img width="947" alt="Colors and states" src="https://github.com/epam/ketcher/assets/125649799/85cf53e5-3dff-41b9-820b-c96731e6c4fa">

Canvas background: #FCFCFC;
Toolbars drop-shadow(0px 2px 5px rgba(103, 104, 132, 0.15));
Top bar drop-shadow(0px 2px 5px rgba(103, 104, 132, 0.1));

**Comment by PetrKurkin** [comment]
Toolbar margins: 12px from the sides of the canvas

**Comment by Zhirnoff** [comment]
Atoms are not greyed out on hover and on select

https://github.com/epam/ketcher/assets/62464241/1c3db7c3-68a8-4ed9-945e-d011a5ed908a

![2023-06-28_11h09_58](https://github.com/epam/ketcher/assets/62464241/2d4be5f3-a486-46f0-80dd-32c285992246)
