### ISSUE TITLE
Smiles file can't be opened

### ISSUE THREAD

**Issue by TomasLight** [epam/ketcher#273]
When you try to open files with extensions 'smi' and 'csmi' in Remote mode, molecules does not dispayed on canvas

**Steps:**
1. Choose 'Benzene' tool for drawing (at the left bottom)
![image](https://user-images.githubusercontent.com/20392714/106251809-7c61de00-6226-11eb-8a71-44215971ab9b.png)
2. Draw one 'Benzene' on canvas (one click on canvas)
3. Save to file
4. Reload page
5. Open saved file

**ER:**
'Benzene' did appear on canvas

**AR:**
'Benzene' didn't appear on canvas

The same flow for Standalone mode works correctly

**Comment by AndreiMazol** [comment]
Cannot reproduce. Please check if API_PATH is configured correctly.
