### ISSUE TITLE
Attachment point selection edition and deletion

### ISSUE THREAD

**Issue by kaluginserg** [epam/ketcher#2742]
### Background
Based on inputs from @AlexanderSavelyev.
Currently, we have the tool 'Attachment point', and each time when we need to remove an attachment point or edit it we have to use this tool. The attachment point on Canvas is not hoverable and is not selectable.

### Proposal
We have to introduce new behavior for editing and removing attachment points.
1) Attachment point should be hoverable
2) There should be the ability to select an attachment point (with a selection tool) and see the selected attachment point.
3) Should be the ability to remove attachment points (select and `Del` hotkey or with Erase tool)
4) Should be the ability to edit an attachment point by clicking on the Context menu item 'Edit' -> dialog with attachment point type should be displayed (Choosing Primary/Secondary or both).

### Visualisation details
> Selection and visualization of the attachment point: ![Attachment point selection](https://user-images.githubusercontent.com/125649799/219609843-8e8e55b3-d459-48bd-8d54-98dde51787bd.png) Attachment point in SVG ![Attachment point](https://user-images.githubusercontent.com/125649799/219609871-b83237a8-79e7-46d9-b667-b94dc2961bf5.svg) ![Attachment point selected](https://user-images.githubusercontent.com/125649799/219610632-9f0b8109-f2fe-4a32-b377-601472568e34.svg) ![Attachment point hover](https://user-images.githubusercontent.com/125649799/219610644-91684891-606a-4b12-a745-763f9f0ee4b7.svg)

_Originally posted by @PetrKurkin in https://github.com/epam/ketcher/issues/2165#issuecomment-1434393564_

### Additional acceptance criteria (in the scope of the task)
We have to fix these issues (it is supposed to be fixed as we will have Attachment points as interaction elements on Canvas):
> https://github.com/epam/ketcher/assets/27288153/e7925166-e3b9-4ff1-aa35-0752c534946e 
> 1. After clicking _Save To Templates_, the attachment point touches the bounding. (wrong paddings)
> 2. When opening the Templates Modal to check out the saved template, the attachment point doesn't display in the preview

_Originally posted by @yuleicul_

### Additional context
Connected #2165

**Comment by yuleicul** [comment]
> Should be the ability to edit an attachment point by clicking on the Context menu item 'Edit' -> dialog with attachment point type should be displayed (Choosing Primary/Secondary or both).

A question: what's the trigger object for the context menu? 
- If the trigger object is the R-Group attachment point
  if an atom has both primary and secondary attachment points, when one of them is clicked, what does the dialog look like?

- If the trigger object is the atom
  what does the name of the menu item? 'R-Group attachment point '?

**Comment by MartaWilliams** [comment]
Tests fail

ad. 3 - it's possible to remove the attachment point after selecting it and pressing Del hotkey or clicking the right mouse key, But after selecting the attachment and choosing Erase /scissors from the Top bar menu nothing is happening

ad.4  Editing existing attachments is not working - clicking the right mouse is giving only the "remove". According to AC  should be possible to adit a type of attachment point (Choosing Primary/Secondary or both)

**Comment by y-holik** [comment]
test cases are created
