### ISSUE TITLE
RNA builder. Collapsing panel with RNA components

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#2751]
**Background**
RNA tab should consist of the monomers from the file attached where "Monomer Type" is "RNA".
The implementation of the RNA builder is divided into several parts:

-	Collapsing panel with RNA components (Collapsed & Expanded states)
-	An accordion component for Sugars, Bases, Phosphates and Presets sections that allows the user to hide or reveal content
-	Edit RNA mode

**Requirements**
Collapsing panel with RNA components should have two states:

- 	**Collapsed state.** Consists of the following parts:
        -	Customized name of RNA created by user
        -	Composition of RNA (full formula of Sugar, Base and Phosphate)
        -	Icon for expansion

- 	**Expanded state**. Consists of the following parts:
        -      Customized name of RNA created by user
        -	Components of RNA: Sugar, Base, Phosphate with particular icons and formulas
        -	_Duplicate and edit_ and _Edit_ buttons
        -	Icon for collapsing

When users click on the RNA tab first time, they should see an empty state of the RNA builder, where they need to choose each component of RNA and name the RNA itself. There also should be an opportunity to save RNA (the details see in the _RNA builder. Edit RNA mode_ task).

In other cases, the system should display the last created RNA.

**Comment by PetrKurkin** [comment]
RNA builder collapsed
<img width="270" alt="Library" src="https://github.com/epam/ketcher/assets/125649799/eac6c979-0890-4b78-86d2-e0907920f8b4">

RNA builder expanded
<img width="270" alt="View" src="https://github.com/epam/ketcher/assets/125649799/c43b1866-7982-42de-86c7-575bc7b501bd">

Components states
<img width="1372" alt="Components States" src="https://github.com/epam/ketcher/assets/125649799/8159a6e7-9943-4602-96d0-0296180f3c90">

**Comment by Zhirnoff** [comment]
Autotests written

**Comment by MartaWilliams** [comment]
Tested with https://github.com/epam/ketcher/issues/2759
