### ISSUE TITLE
Snap arrows to horizontal and vertical orientation

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#2753]
When user positions an arrow on canvas by dragging one of its ends, it is hard to make it oriented strongly horizontally or vertically.

In order to facilitate horizontal and vertical orientation the arrow should snap to horizontal (0 degrees) position once the angle between the arrow and the horizontal line is 15 degrees or less.  Once the arrow is snapped and while user holds mouse button pressed, the arrow should be highlighted with blue color to indicate horizontal position.
No snapping should be applied if user holds Ctrl key pressed while dragging the arrow. The arrow should be highlighted though in this case if it is positioned exactly to 0 degrees.

Similar behavior should be introduced for vertical (90 degrees) snapping. 

#185260742

**Comment by PetrKurkin** [comment]
Blue highlight color is the same as for the rotation circle: #365CFF

A newly created arrow is being positioned:
<img width="500" alt="Arrow" src="https://github.com/epam/ketcher/assets/125649799/290a3ea2-77dd-485a-899e-5b918a16badd">


Selected and rotated arrow:
<img width="500" alt="Arrow selected" src="https://github.com/epam/ketcher/assets/125649799/4dbd6986-aba6-43e1-99a0-fcfe81dcc4fc">

**Comment by yuleicul** [comment]
In scope of this issue, we need to remove the rotation handle for one single arrow, 
![image](https://github.com/epam/ketcher/assets/27288153/5e60685f-44a6-48ee-bc3c-5972a3ae36cf)
because we already can rotate one single arrow by dragging its ends.

**Comment by yuleicul** [comment]
A bug caused by #2764 : Double-clicking on atoms or bonds can't open edit modals.
