### ISSUE TITLE
RNA builder. Edit RNA mode

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#2759]
### **Background**
RNA tab should consist of the monomers from the file attached where "Monomer Type" is "RNA".
The implementation of the RNA builder is divided into several parts:
•	Collapsing panel with RNA components (Collapsed & Expanded states)
•	An accordion component for Sugars, Bases, Phosphates and Presets sections that allows the user to hide or reveal content
•	Edit RNA mode
### Requirements
The collapsing panel with RNA components allows the users to create, save and edit RNA.
The collapsing panel in an expanded state composes the following parts:
- Customized name of RNA created by user
- Components of RNA: Sugar, Base, Phosphate with particular icons and formulas
- _Duplicate and edit_ and _Edit_ buttons
- Icon for collapsing

**An empty state of the RNA builder** 
When users click on the RNA tab first time, they should see an empty state of the RNA builder, where they need to choose each component of RNA and name the RNA itself. 

The empty form of RNA also can be opened when user clicks on the _New preset_ button in the Presets library below.

In the empty state the button “Add to presets” is blocked until any of the components is added. Sugars, Bases and Phosphates are added by choosing from the corresponding libraries below.

The view of Sugar, Base and Phosphate icons (filled or empty) depends on selected or not selected state of the RNA components.

 RNA can be saved to presets using _Add to Presets_ button.

**Edit mode**
Once the RNA is added to presets, it can be edited. Two options are available:
1.	_Edit_. Customized name of RNA and any of components might be changed within the current saved RNA. Available options are _Cancel_ and _Save_
2.	_Duplicate and Edit_. Customized name of RNA and any of components might be changed by creating the new RNA. The new RNA appears in the Presets library. Available options are _Cancel_ and _Save_

During editing, the button 'New preset' is blocked, choosing another preset from the Presets library also is blocked. 

Once hover on the collapsing panel in a collapsed state, a pencil icon appears allowing to click on it and edit the name of RNA. 

**RNA Name**
If preset is saved with partially selected components, then the following name should be used (R-sugar, B-base, P-phosphate):

* R, B, P -> R(B)P
* R, B -> R(B)
* B, P -> (B)P
* R, P -> R()P
* R->R
* B->B
* P->P

**Comment by PetrKurkin** [comment]
Empty state
<img width="1460" alt="Empty" src="https://github.com/epam/ketcher/assets/125649799/dcbad662-e89d-4674-a8b8-58aba732a3e5">

New preset creation
<img width="2652" alt="New preset flow" src="https://github.com/epam/ketcher/assets/125649799/af6412d0-df5e-4aca-9971-c3f476420db1">

Editing saved preset
<img width="2234" alt="Saved preset edit" src="https://github.com/epam/ketcher/assets/125649799/b91d59be-4f76-4630-ba90-99db2b73d6ff">

**Comment by MartaWilliams** [comment]
Tested
