### ISSUE TITLE
Snap partially selected structure to an attachment bond when rotated

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#2760]
**Background**
When user rotates part of a structure, alignment should be done due to a attachment bond(s) (bond which is connected to selected structure)

**Solution**
Create snap positions for a bond and highlight the snaps according to the following rules
* if there is 1 bond attached - then create 90, 120 and 180 angles snaps. Angle should appear when position is close to the predifined angle
* If there are 2+ bonds then create a snap which divides angle by two between any two bonds near the current position

See screenshots

**Comment by PetrKurkin** [comment]
Flow for the 1 bond scenario. We move the handle counterclockwise, see 90 degrees angle prompt first, snaps to 120 degrees, and move further to 180 degrees.
<img width="2835" alt="One bond flow" src="https://github.com/epam/ketcher/assets/125649799/8aea3881-1989-4ae2-9a68-8eec06f3b75f">

90 degrees snap. When highlighted in blue, the bond thickness multiplies by 1.5.
<img width="862" alt="90 degrees angle snap" src="https://github.com/epam/ketcher/assets/125649799/0c76b6bb-5f6f-4a8d-abbf-75d469524a39">

Flow for 2+ bonds scenario. Moving counterclockwise we see a prompt for the bisector, then snap to it. 
<img width="2115" alt="Two bonds flow" src="https://github.com/epam/ketcher/assets/125649799/f2d88870-136f-424f-83d4-a9662dc54d90">

Bisector snap
<img width="685" alt="Bisector" src="https://github.com/epam/ketcher/assets/125649799/46a8030f-23f6-4f6b-bdeb-0bfbe78b8a20">
