### ISSUE TITLE
Can not open .rxn files with S-Group properties

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2766]
**Steps to Reproduce**

**Scenario1**
1. Launch Ketcher
2. Open RXN v2000 file with 'S-Group Properties Type = Multiple group [Multi.zip](https://github.com/epam/ketcher/files/11001722/Multi.zip)

**Scenario2**
1. Launch Ketcher
2. Open RXN v3000 file with 'S-Group Properties Type = Multiple group [rxnV3000Multiple.zip](https://github.com/epam/ketcher/files/11001809/rxnV3000Multiple.zip)

**Actual behavior**
Error Message
Convert error! Cannot deserialize input JSON.
![2023-06-13_17h54_35](https://github.com/epam/ketcher/assets/62464241/2dca5a35-5610-4f65-951f-8e83c90c9f48)

**Expected behavior**
The files open with all added S-Group Properties and brackets on its places.

Related bug: https://github.com/epam/ketcher/issues/2389

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 109.0.5414.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.11.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Nitvex** [comment]
Actual pr
