### ISSUE TITLE
Selection tool: Incorrect selection view

### ISSUE THREAD

**Issue by AleksandraSmolianinova** [epam/ketcher#2793]
Steps to Reproduce
1. Open Ketcher
2. Create structures as in attachment
3. Select reactions with selection tool

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/130548475/8c10d796-a3d4-457d-b3b0-aa90d4c75300)

**Expected behavior**
Should be as per design - https://github.com/epam/ketcher/issues/2088
![image](https://github.com/epam/ketcher/assets/130548475/4ebfcfd3-82f5-4493-8f11-3e5e94504027)

**Ketcher version** 
[Version 2.11.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2023-06-01; 12:46:43

**Test case**
EPMLSOPKET-13795

**Comment by AleksandraSmolianinova** [comment]
Also incorrect selection of bonds.
AR:
![image](https://github.com/epam/ketcher/assets/130548475/dcfc2945-c9bc-4d88-861c-a82803ad1c1e)

ER:
![image](https://github.com/epam/ketcher/assets/130548475/72c0242f-ec8a-4c42-b8be-d417bac7f435)

And arrows:
AR:
![image](https://github.com/epam/ketcher/assets/130548475/b5a1d962-5858-41ed-b4ff-634f80475800)

ER:
![image](https://github.com/epam/ketcher/assets/130548475/0ac37868-c509-4626-ae46-2e3b8ff82fc5)

**Comment by aproskurnov** [comment]
arrow it's not a bonds. it corresponds to design
<img width="233" alt="Screenshot 2023-07-31 at 08 19 27" src="https://github.com/epam/ketcher/assets/4223805/7774ab02-0d5e-4c59-a4bf-68c94ac3897d">

**Comment by AleksandraSmolianinova** [comment]
Test cases are being created.
