### ISSUE TITLE
Bonds between atoms are not centered and not drawn symmetrically

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#2838]
**Steps to Reproduce**
1. Open Ketcher
2. Add bonds on canvas
3. Observe alignment of the bonds between atoms and symmetry in the bond drawings.

**Actual behavior**
Bonds between atoms are not centered and not drawn symmetrically

**Expected behavior**
Bonds between atoms are centered and drawn symmetrically

**Screenshots**
![2023-06-30_13h50_16](https://github.com/epam/ketcher/assets/62464241/3514483a-61e2-49e4-8433-c72fd0e0d1f0)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.12.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Inga-Vishnivetskaia** [comment]
Investigations on this bug:
1. drawn symmetrically: `plainBondTypes` ( `PATTERN TYPE`: `SINGLE`, `DOUBLE`, `TRIPLE`) (`bond.b.type` equals to 1, 2, 3)
2. not drawn symmetrically: type `HYDROGEN`, `DATIVE`, `DOUBLE_OR_AROMATIC`, `SINGLE_OR_AROMATIC`, `SINGLE_OR_DOUBLE`, `AROMATIC`, `any` (`bond.b.type` equals to 4, 5, 6, 7, 8, 9, 10 )

Object `hb1` (rebond.ts, `struct.halfBonds.get`) has `p` prop where `p.x` stores the `x` render coordinate of bond. This is related also to the bond selection (see hover_selection_2.png). Possible solution may be to change calculation of `p.x`

**Comment by Zhirnoff** [comment]
Test cases are written by me.

**Comment by MartaWilliams** [comment]
Tested 
Actual behaviour meets acceptance criteria
![image](https://github.com/epam/ketcher/assets/82752700/8cdfa035-47c2-4cba-a6d6-f1f036b36bd7)

**Comment by ViktoriaTkacheva** [comment]
In two bonds (Aromatic Bond, Single/Aromatic Bond) the pattern is not symmetrical - the right dash is shorter than the left

<img width="953" alt="image" src="https://github.com/epam/ketcher/assets/139227567/1ace5e44-9ef6-423f-9b9f-97746f5003c3">
