### ISSUE TITLE
[Macro] Preview of monomer structures on canvas

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#2869]
**Requirements**
Once hover on a monomer on canvas, a dialog window with a monomer preview appears.

Preview might also be displayed with choosing the following basic drawing operations:
1. Delete 
2. Select
3. Bond

**Comment by nightnick** [comment]
1. Preview is available only when mouse cursor is hovering over a structure on a canvas, regarding of selected instrument.
_Even if selected instrument (i.e. Move/Hand) does not have a possible interaction with a hovered structure — we show non-interactive hover styling for the sequence and a preview nearby it._
2. By default preview is show below structure with a `padding-top: 4px;` with no change for x-axis. `max-width: 232px;`
3. Areas where a preview can’t be shown are the same as for modal for bond choose.
4. Preview is shown regardless of canvas zoom scale, and does not scales by itself (in other words — the width of the preview does not change on page zoom).
5. Preview does not blink or re-render while a cursor is hovering and moving over a structure.
6. Preview can’t be show when a modal (f.e. for bond choose) is opened, or when there’s an overlay.
7. Preview can’t be shown while moving canvas.

Figma: https://epa.ms/ket-mm-preview

**Comment by nightnick** [comment]
Are there behavior for word-break of a structure name? 
![image](https://github.com/epam/ketcher/assets/27892118/6b9ef25c-2f6d-4281-bb20-d9e2f0e35ed8)

**Comment by y-holik** [comment]
this issue is tested 
bug https://github.com/epam/ketcher/issues/3595 was created
'Preview can’t be shown while mouse-down.'  currently is being worked on
