### ISSUE TITLE
The "double" Rgroup labels are replaced with R# when user saves the structure in CML-format.

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#29]
**Steps to reproduce:**
1. Create any structure.
2. With the R-Group Label Tool set any label for any structure atom, for example, R1.
3. Click the 'Save As' button. Choose the CML-format.

**Actual correct result**

The structure is saved and opened correctly.

4. With the R-Group Label Tool set any other label for the same structure atom. Now two labels present on the atom.
5. Click the 'Save As' button. Choose the CML-format.
6. Clear the canvas.
7. Click "Open..." button, open saved in 5th step structure.

**Actual result:**
The R-Labels are replaced with R#.

Steps to reproduce:
1. Create any structure.
2. With the R-Group Label Tool set any label for any structure atom, for example, R1.
3. Click the 'Save As' button. Choose the CML-format.

Actual correct result

The structure is saved and opened correctly.

4. With the R-Group Label Tool set any other label for the same structure atom. Now two labels present on the atom.
5. Click the 'Save As' button. Choose the CML-format.
6. Clear the canvas.
7. Click "Open..." button, open saved in 5th step structure.

Actual result:
The R-Labels are replaced with R#.
![image](https://user-images.githubusercontent.com/7427808/92364474-cae9d100-f0fb-11ea-9be0-ebc0d28ed3ff.png)

The check structure contains the message that RLabels present at the canvas:

Nevertheless when user wth R-Group Label Tool clicks this R# atom, no R-Labes are selected in the opened window:

Expected result:
The structure is opened in the same view that before saving - the both RLabels presents at the structure and when users clicks the atom with R-Group Label Tool, these rLabels are selected in the opened window.

The check structure contains the message that RLabels present at the canvas:
![image](https://user-images.githubusercontent.com/7427808/92364532-e359eb80-f0fb-11ea-9907-4db1f6d35f86.png)

Nevertheless when user wth R-Group Label Tool clicks this R# atom, no R-Labes are selected in the opened window:
![image](https://user-images.githubusercontent.com/7427808/92364553-eb199000-f0fb-11ea-924b-dd47b7b60e31.png)

**Expected result:**
The structure is opened in the same view that before saving - the both RLabels presents at the structure and when users clicks the atom with R-Group Label Tool, these rLabels are selected in the opened window.

**Comment by ensemenova** [comment]
CML format supports only positive integer values according to  http://www.uwosh.edu/faculty_staff/gutow/marvin.1/doc/user/cml-doc.html  `rgroupRef - R-group reference. Currently, only positive integer values are accepted.` So it's not possible for now to store multiple groups to one atom in CML files. Agreed on closing this issue with @AlexanderSavelyev
