### ISSUE TITLE
Add `all-scroll` cursor for selected structure

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2911]
**Background**
To make interface more clear it is proposed to change cursor to `all-scroll` for selected structure. It will allow user to understand that the structure is draggable.

**Solution**
If a user selects a structure, then cursor is supposed to be changed to `all-scroll`, when the structure is hovered. When cursor is not over the selected atom or bond, then it should be displayed as is.

**Comment by anchounio2** [comment]
How can I disable this?
