### ISSUE TITLE
Fix memory leak for Ketcher when it is opened inside modal

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2912]
**Steps to Reproduce**
1. Open Ketcher inside modal
2. Close the modal
3. Open Ketcher again
4. Repeat steps 1-3 multiple times

**Actual behavior**
User receives memory leak warning:
![MicrosoftTeams-image (41)](https://github.com/epam/ketcher/assets/41272128/0412c5c6-c1d8-4139-83fb-f7daa59ce476)

**Expected behavior**
Memory leak is eliminated. No warning message is shown.

**Comment by hellhorse123** [comment]
I still get error:
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 layout listeners added. Use emitter.setMaxListeners() to increase limit`
when open/close modal with ketcher at many times

**Comment by rrodionov91** [comment]
Hi @hellhorse123 
Thank you for notifying us. We will check
