### ISSUE TITLE
RNA Builder. Add default presets

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#2934]
Need to add presets by default into the Presets section in the RNA library. They are filled with the RNA with natural branch monomers (bases) are represented by capital letters A, C, G, T, U:

"Phosphate"-"Ribose"-"Adenine" (A)
"Phosphate"-"Ribose"-"Cytosine" (C)
"Phosphate"-"Ribose"-"Guanine" (G)
"Phosphate"-"Ribose"-"Thymine" (T)
"Phosphate"-"Ribose"-"Uracil" (U)

Ribose (r) uses as a sugar attached to a base. Phosphate (p) uses as a linker.

**Comment by SashaGraves** [comment]
Question:
How can I delete preset? For example if i added a lot of presets and want to clear some space.
Can I delete default presets?
Can I edit default presets?

**Comment by OlZhur** [comment]
> Question: How can I delete preset? For example if i added a lot of presets and want to clear some space. Can I delete default presets? Can I edit default presets?

At the current moment users can not delete a preset, only edit it. 
Default presets cannot be deleted or edited.

**Comment by Zhirnoff** [comment]
Autotests written
