### ISSUE TITLE
Merge preview of abbreviated structures

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2939]
Once abbreviated structure is hovered over an atom or bond, the text label (like benzene) should be hidden and user should be shown a preview of how the structure will be merged with the existing one if they click left mouse button.

Acceptance criteria:
– Show a preview of structure with opacity to make it visually distinguishable
– Hide structure label, when mouse is hovered over structure

#184895577

**Comment by yuleicul** [comment]
Dev notes for myself:
- [ ] extract related function in `mouseup`, refer it in `mousemove`
- [ ] nothing is pushed to `historystack`
- [ ] use `[map]Changed` to show opacity

**Comment by KonstantinEpam23** [comment]
Currently some structure can be merged "inside" each other. For example in case of benzene rings - we can merge two rings "on top of each other" .
If we have two benzene rings connected by one bond and hover with another benzene ring template over this connection bond:
<img width="405" alt="Screenshot 2023-08-02 at 11 56 43" src="https://github.com/epam/ketcher/assets/101649391/58137b58-e6b6-4e3e-b3e4-de1974860930">

If we now click on that position - the new benzene ring template will be merged inside the two rings:
<img width="212" alt="Screenshot 2023-08-02 at 11 59 35" src="https://github.com/epam/ketcher/assets/101649391/1c4a10d5-76a6-43d8-b6a5-2c6584c0a0ab">

What should be the correct behavior for showing the preview in this case? Should all the changed bonds and atoms be highlighted with reduced opacity in this case?

**Comment by Zhirnoff** [comment]
Test cases are being created.
