### ISSUE TITLE
Attachment points should be within S-Group brackets

### ISSUE THREAD

**Issue by AleksandraSmolianinova** [epam/ketcher#2949]
**Steps to Reproduce**
1. Go to Ketcher
2. Create structure with S-Group (Multi Group/SRU Polimer)
3. Add attachment point for the same atom

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/130548475/c913941e-bd84-4ad8-9f85-12e35854306b)

**Expected behavior**
Attachment points should be inside of S-Group

**Ketcher version** [e.g. v2.4.2]. 
Version 2.13.0-rc.1

**Comment by Nitvex** [comment]
Closing this issue as done in 2.13.0-rc.2. 
The case described by @AleksandraSmolianinova will be fixed in #2994

**Comment by Zhirnoff** [comment]
This bug will be fixed in https://github.com/epam/ketcher/issues/2994 and tested in v2.14

**Comment by Zhirnoff** [comment]
Tested. Bug is fixed.

![2023-08-04_17h54_27](https://github.com/epam/ketcher/assets/62464241/d6c7b64b-1283-4fbf-a2f5-77199c82df91)
