### ISSUE TITLE
Incorrect order of Hydrogen symbol in abbreviation of the atoms when adding them to the structure

### ISSUE THREAD

**Issue by Ustianskii** [epam/ketcher#2957]
Steps to Reproduce

1. Launch "Ketcher"
2. Create any Chain structure
3. With Shift key select some atoms in the structure and click the "Phosphorus (P)"  button on the Atom Palette bar.

**Expected behaviour**
Following abbreviation of atoms should be present in the Chain structure
"H2P" for the first atom of the structure
"PH2" for the last atom of the structure"
"PH" for all other atoms.

**Actual behaviour**
<img width="358" alt="image" src="https://github.com/epam/ketcher/assets/94541128/fd312601-940a-461f-a537-afa2666f1325">

Ketcher version [e.g. v2.4.2].
Version 2.13.0-rc.1

**Comment by AleksandraSmolianinova** [comment]
Test cases are being created.
