### ISSUE TITLE
Atom lable disappears after updating R-Group attachment point to none

### ISSUE THREAD

**Issue by yuleicul** [epam/ketcher#2958]
**Steps to Reproduce**
1. Activate tool 'R-Group Attachment Point'
2. Click on an atom to set attachment points
3. Click the same atom again to remove attachment points

**Actual behavior**
The label of the atom disappears

**Expected behavior**
The label of the atom appears

**Screenshots**

![rgroup-ap-label-bug](https://github.com/epam/ketcher/assets/27288153/d4a020a0-e212-43a0-a714-b823f16d9583)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 114.0.5735.199 (Official Build) (64-bit)

**Ketcher version** [e.g. v2.4.2]. 
Version 2.13.0-rc.1
Build at 2023-07-19; 13:44:23

**Comment by MartaWilliams** [comment]
Test result: passed
Check on branch: 2958-atom-lable-disappears-after-updating-r-group-attachment-point-to-none
![2023-08-02_14h19_38](https://github.com/epam/ketcher/assets/82752700/59e17d5c-7adb-475c-b3aa-ecbc8727fa8c)
