### ISSUE TITLE
Refactor request: rename `attpnt` add type annotation on it

### ISSUE THREAD

**Issue by yuleicul** [epam/ketcher#2962]
**Background**
- `atom.attpnt` means R-Group Attachment Point, but the naming is not clear. Not sure if it was named after some specification or just a random abbreviation of `rgroupAttachmentPoint`. 
- `atom.attpnt` has no type annotation

**Solution**
1. If `attpnt` is named after some specification, please comment it, otherwise, rename it to a clearer name.
2. Add type annotation on `attpnt` according to comments of #2958 

**Additional context**
#2958 
#2742 
(Notice: I'd suggest working on this issue after the above two issues get merged.)

**Comment by Nitvex** [comment]
Hello, @yuleicul! If you rename `atom.attpnt` to something else, then it will be breaking change, right? I propose to add some getter `attpnt` and mark it as deprecated for backward compatibility.
