### ISSUE TITLE
Copy/Cut/Paste + Undo/Redo makes objects appear randomly on the canvas, their initial amount increases

### ISSUE THREAD

**Issue by y-holik** [epam/ketcher#2963]
**Steps to Reproduce**
1. Add any 4 structures on the canvas (ex. Benzene)
2. Copy one structure 
3. Paste 4 times next to existing ones
4. Click 'Undo/Redo' multiple times

**Actual behavior**
Structures appear/disappear randomly on the canvas, initial amount is changed

**Expected behavior**
Structures appear/disappear where they were created, the actions undone/redone correctly

**Screenshots**

https://github.com/epam/ketcher/assets/139877378/5a80f464-caa5-4bc8-acb5-91966941d6d2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 114.0.5735.199 (Official Build) (64-bit)

**Ketcher version** 
2.13.0

**Test case**
EPMLSOPKET-16764

**Comment by nanoblit** [comment]
Fixed in scope of #3023

**Comment by nanoblit** [comment]
Fixed in scope of #3023
