### ISSUE TITLE
Error message is not displayed when incorrect inchi string opening

### ISSUE THREAD

**Issue by Ustianskii** [epam/ketcher#2975]
Steps to Reproduce

1. Launch Ketcher
2. Click the Open button.
3. In the 'Input' field put the incorrect InChi string, for example:
InChI=1S/C7H16O/c1-2-3-4-5-6-7-8$h8H,2-7H2,1H3 - special symbol, etc.
4. Click OK.

Actual behaviour
No error message is displayed

Expected behaviour:
Error message is displayed, stating that an unrecognised InChI String was encountered.

Ketcher version [e.g. v2.4.2].
Version 2.13.0-rc.1

**Comment by nanoblit** [comment]
This issue is related to Indigo. Indigo returns an empty structure given incorrect InChi string and doesn't throw an error.

**Comment by Zhirnoff** [comment]
Duplicate bug on Indigo side https://github.com/epam/Indigo/issues/1221
