### ISSUE TITLE
Ignore abbreviation lookup for repetitive keystrokes

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#2982]
**Background**
Abbreviation lookup is shown, when user tries to change currently active tool from a group. This happens, for example, for bond tool – you press "1" and want to change bond type, but this actually causes abbreviation lookup to appear.

**Solution**
Do not show abbreviation lookup for repetitive keys, which are assigned as shortcuts.

**Additional context**
Knows issues:
– Bond tool
– Template tool, when changing Benzene ring -> Cyclopentadiene -> Cyclohexane

**Comment by Zhirnoff** [comment]
Manual test cases will be written by me

**Comment by ViktoriaTkacheva** [comment]
When pressing shortcut 0 several times, the Abbreviation lookup appears (it is inconsistent with a similar case for 3 and 4 shortcuts where the Abbreviation lookup does not show up)
<img width="956" alt="image" src="https://github.com/epam/ketcher/assets/139227567/4966cf62-ca98-46d5-a03e-cc89f49bfa24">
