### ISSUE TITLE
Macro: Switcher between Micro and Macro modes

### ISSUE THREAD

**Issue by isidoraotasevic** [epam/ketcher#2987]
**Background**
The system shall enable switching between Ketcher mode and Ketcher macromolecule mode.

**Requirements**
1. Switch button for Ketcher macromolecule mode:
-Switch button shall be placed in the upper menu on Canvas.
-Switch button shall be clearly displayed in a form indicating structure of macromolecules.
-Switch button shall be in the shape of a **DNA**. (TBD with UX)

2) Switching from Ketcher mode to Ketcher macromolecule mode:
-When a user hovers over the switch button for macromolecule mode, a pop-up window appears displaying the following text: “Switch to Macromolecule mode”.
-When a user clicks on the switch button, user shall be redirected to Ketcher macromolecule mode.

3) Switch button for Ketcher mode:
-Switch button shall be placed in the upper menu on Canvas.
-Switch button shall be clearly displayed in a form indicating structure of molecules.
-Switch button shall be in the shape of a **molecule structure for HCl** (TBD with UX)

4) Switching back from Ketcher macromolecule mode to Ketcher mode:
-When a user hovers over the switch button for Ketcher mode, a pop-up window appears displaying the following text: “Switch to Ketcher mode”.
-When a user clicks on the switch button, user shall be redirected to Ketcher mode.

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/d7e4656d-b2cd-4e28-8b43-50bd3c86f83a)
![image](https://github.com/epam/ketcher/assets/141816460/ba5cd9c7-535d-4094-815b-c83b1d099c8f)

**Comment by AnastasiyaPiatrovaKlu** [comment]
Tested.

https://github.com/epam/ketcher/assets/72072840/32b77da4-ffe0-4cb9-9e9b-5034d8ca4a85
