### ISSUE TITLE
Attachment points should be within S-Group brackets

### ISSUE THREAD

**Issue by Ustianskii** [epam/ketcher#2994]
Steps to Reproduce

1. Go to Ketcher
2. Create structure with S-Group (Multi Group/SRU Polimer)
3. Add attachment point for the same atom

Actual behaviour
![image](https://github.com/epam/ketcher/assets/94541128/5970b9fc-f132-4b2d-b0d3-fa31026813d4)

Expected behaviour
Attachment points should be inside of S-Group

Ketcher version [e.g. v2.4.2].
Version 2.13.0-rc.2

**Comment by y-holik** [comment]
test cases are created

**Comment by ViktoriaTkacheva** [comment]
Preview. Bug is fixed

<img width="953" alt="image" src="https://github.com/epam/ketcher/assets/139227567/5969dfed-2e6b-4439-bda5-e96f328abd7e">
