### ISSUE TITLE
Is there any event that can be listen to when the user change the structure?

### ISSUE THREAD

**Issue by jumpingstone** [epam/ketcher#3]
I wonder if a user changed the structure, is there any event such as 'structureChanged' can be used to detect the change?

**Comment by michal-husak** [comment]
@jumpingstone I did a reverse engineering because I couldn't find any proper documentation.

You can try something like this:
```javascript
var ketcherFrame = document.getElementById('ifKetcher');
var ketcher = null;

if ('contentDocument' in ketcherFrame) {
    ketcher = ketcherFrame.contentWindow.ketcher;
}
ketcher.editor.on('change', function(){
    console.log('changeeeeed!')
});
```

**Comment by AndreiMazol** [comment]
This issue should be don in scope of #54
