### ISSUE TITLE
Add favorite monomers to canvas from favorite library

### ISSUE THREAD

**Issue by isidoraotasevic** [epam/ketcher#3004]
**Background**
This task covers adding favorite monomers by click from monomer library to the canvas.
**Requirements**
1.	User adds monomers to favorites library in the following way:
-User hovers over a monomer in the library - a greyed out star appears.
-When user hovers over the star - it changes color to yellow.
-When user clicks on a star it should persist in yellow color on the monomer item in the library and should also be saved to the "Favorites" library.
2.	User adds favorite monomers from favorite library to canvas in the following way:
-User clicks on a favorite monomer in a favorite library.
-Selected favorite monomer becomes highlighted.
-When a user clicks at the canvas selected favorite monomer is added to the place of a click.
-Once selected favorite monomer is added to the canvas, the monomer remains selected in the library and can be added again.
4.	Favorite monomers are added to the canvas in a color that corresponds to the color in the favorite library.
5.	Favorite monomers are added to the canvas in a structure that corresponds to the type of a monomer.

**Comment by MartaWilliams** [comment]
Tested 
![2023-10-24_11h24_13](https://github.com/epam/ketcher/assets/82752700/11d6374f-604c-4b0e-827d-2aceb64f1b5a)
