### ISSUE TITLE
Unable to 'undo' the paste action, if there is no reset to Select tool.

### ISSUE THREAD

**Issue by Vehemen** [epam/ketcher#3005]
**Steps to Reproduce**
1. open settings in the up-right corner
2. in the dropdown list for "reset to Select tool" choose "Off"
3. place a Benzene ring on the canvas
4. Use select tool to choose and CTRL+C placed ring.
5. Press CTRL+V and place the ring. There are now 2 rings on the canvas.
6. press CTRL+Z

**Actual behavior**
Preview of the third ring is vanished. It will return, if you move the cursor. You can only delete these previews, but you will never delete the second ring with undo.

https://github.com/epam/ketcher/assets/131955641/372acbd3-842f-4287-9cc7-14e1a193d0c7

**Expected behavior**
Second ring is deleted with the first press of undo.
**Screenshots**

 - OS: Windows10
 - Browser: Firefox
 - Ketcher: v2.13.0 rc2

**Comment by nanoblit** [comment]
Done in scope of #3050

**Comment by nanoblit** [comment]
> Pre-tested. By repeatedly pressing Undo/Redo, the structures move beyond the canvas. Should remain in same place.
> 
>  2023-09-05_15h09_00.mp4

Should be fixed now

**Comment by Zhirnoff** [comment]
Pre-tested. Fixed.

**Comment by MartaWilliams** [comment]
Test cases written

**Comment by ilya-asiyuk-epam** [comment]
Removed flag "Firefox only" as I reproduce it in Google Chrome as well

**Comment by ilya-asiyuk-epam** [comment]
Found exact commit which adds such behavior:
https://github.com/epam/ketcher/commit/3b34bc26a067728871562715256549ef217a5c08

Namely this lines:
```
        if (this._tool instanceof toolMap['paste']) {
		this.event.change.dispatch();
		return;
	}
```
