### ISSUE TITLE
The canvas view moves in the direction of the cursor

### ISSUE THREAD

**Issue by Ustianskii** [epam/ketcher#3006]
Steps to Reproduce

1. Launch Ketcher
2. Create any structure
3. Click the Ctrl+C buttons.
4. Click the Ctrl+V buttons.

Actual behaviour:
The canvas view moves in the direction of the cursor

https://github.com/epam/ketcher/assets/62464241/577bf6af-2ee9-4ef2-bf94-6f14cf8aa096

Expected behaviour:
The canvas view is staying in place

Ketcher version [e.g. v2.4.2].
Version 2.13.0-rc.2

**Comment by Zhirnoff** [comment]
Tested. Bug is fixed.
