### ISSUE TITLE
Using setMolecule with molfile does not rescale bond lengths

### ISSUE THREAD

**Issue by mliu49** [epam/ketcher#3017]
**Steps to Reproduce**

```

     RDKit          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
    1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7500   -1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7500    1.2990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  1  1  0
M  END
```

1. Using ketcher standalone, import the molfile above using ketcher.setMolecule
2. Import it again but using the Open... > Paste from clipboard option

**Actual behavior**
The two benzene rings are different sizes.

**Expected behavior**
I would expect `setMolecule` to scale the bond length in the same way as the Open... menu.

**Screenshots**
In the image below, first benzene was added with `setMolecule`, second benzene was added via Open... menu button, third benzene was drawn with benzene button.
<img width="611" alt="image" src="https://github.com/epam/ketcher/assets/10817103/0feca3fe-8766-4964-bc81-cc1facd5867c">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Ketcher version** [e.g. v2.4.2]. 
Tested in v2.6 and v2.11

**Comment by mliu49** [comment]
Hi, could you confirm whether this is a bug or if there's a workaround? We just want to be able to set a molfile programmatically and have the drawing be re-scaled. Thanks!

**Comment by Zhirnoff** [comment]
Tested. Fixed.
![2024-03-11_17h46_26](https://github.com/epam/ketcher/assets/62464241/73fe6f4c-81aa-4a29-9bf7-0628d71f75f4)
