### ISSUE TITLE
Some structures from Template library have incorrect chiral flag

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3022]
**Steps to Reproduce**
1. Open Templates modal
2. Choose some template from L-Amino Acids
3. Add it to canvas

**Actual behavior**
"And Enantiomer" label is added
![image](https://github.com/epam/ketcher/assets/41272128/abba0e88-216d-4716-90ff-ce45dab816d2)

**Expected behavior**
"And Enantiomer" label is not shown
![image](https://github.com/epam/ketcher/assets/41272128/23da043d-c3a2-429e-b2d0-4b8693c1a663)

**Test case**
Add test case number (in EPMLSOPKET-* format) if bug was found during test case run.

**Comment by Zhirnoff** [comment]
Manual test cases is written by me.
