### ISSUE TITLE
Provide additional logging

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3040]
**Background**
At the moment, Ketcher has a lot of try/catch blocks which catch errors (for example, when parsing files) and show appearing errors in modal. This errors sometimes neither informative for end-user nor developers.

**Solution**
1. It is required to add `console.error` to catch block in order to easy find the places, where error appeared
2. It is required to prevent non-informative errors to be shown to users (Example error: "cannot read property null of undefined")

**Comment by Zhirnoff** [comment]
Not tested by QA.
