### ISSUE TITLE
Macro: RNA Builder. Delete presets.

### ISSUE THREAD

**Issue by isidoraotasevic** [epam/ketcher#3041]
**Background:**
This task covers deleting RNA presets in RNA library.

**Requirements:**

User deletes RNA presets in the following way:
•	User hovers over chosen RNA preset in preset section in RNA library.
•	With a right click on a mouse, the collapsing panel appears displaying Delete option.
•	User clicks on Delete button. 
•	Once delete button is clicked, the warning message appears: “Are you sure you want to delete RNA preset?”. (TBD with UX)
•	Two following options appear: _Yes_ and _No_.
•	User confirms to delete RNA preset by clicking _“Yes”_.
•	RNA preset is removed from RNA library

User chooses not to delete presets from RNA library:
•	User confirms not to delete RNA preset by clicking _“No”_.
•	RNA preset stays in RNA library

**Inability to delete default RNA presets:**
•	If a user wants to delete default RNA presets, warning message shall be displayed: "You cannot delete default RNA presets".

**Displaying a star for adding presets to favorites**:

- A star for adding RNA presets to Favorite library shall appear in the upper left corner inside preset framework.

** Figma link
https://www.figma.com/file/MZ28kJRelnXvBodXu54UKh/Macromolecules-(Polymer-Editor)-Playground?type=design&node-id=5149-9013&mode=design&t=1YYvaoEyNpvgCShy-0

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/ce3aaccc-a75d-4959-8fa3-e8f68a1ec65a)
context menu positioning

**Comment by MartaWilliams** [comment]
Tested 
- I just couldn't add RNA presets to Favorite library 
![2023-10-24_14h07_13](https://github.com/epam/ketcher/assets/82752700/994cf31a-09b2-4492-9e1b-6056f45529e6)
![2023-10-24_14h04_03](https://github.com/epam/ketcher/assets/82752700/99d62204-b563-4c15-9654-3e9bfad924ba)
