### ISSUE TITLE
'Calculated Values' of R-Group-member shows incorrect message in Standalone mode

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#305]
**Affected Version:** _Standalone_
**Steps to Reproduce:**
1. Open file in Ketcher: [R-Member.zip](https://github.com/epam/ketcher/files/5951818/R-Member.zip)
2. Click 'Calculated Values' button.

**Expected Result:**
'Cannot calculate properties for RGroups' error message appears, 'Calculated Values' modal window is opened.

**Actual Result:**
'Calculated Values' modal window is opened, default browser message appears:
![4](https://user-images.githubusercontent.com/75974465/107374599-d2713400-6af8-11eb-9a09-1733ddc4d876.jpg)

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/323
