### ISSUE TITLE
Autotests: Create autotests for Settings -> Atom 

### ISSUE THREAD

**Issue by MartaWilliams** [epam/ketcher#3055]
Create autotests for Settings-> Atom 

5 tests
[EPMLSOPKET-10079] - Atoms settings - Defaul settings verification
[EPMLSOPKET-10076] - 'Terminal and Hetero' is set for default for 'Show hydrogen labels
[EPMLSOPKET-10080] - 'on' is set for 'Show hydrogen labels'
[EPMLSOPKET-10081] - Display Special nodes 'Deuterium', 'Tritium' when 'Show hydrogen labels' = 'Terminal and Hetero
[EPMLSOPKET-10083]- Non-terminal hetero atom when 'Show hydrogen labels' = 'Terminal and Hetero

https://jiraeu.epam.com/secure/TestManagementAction.jspa?viewTab=Work&testRunId=77827&folderId=2377916

**Comment by Zhirnoff** [comment]
Tests automated.
