### ISSUE TITLE
Incorrect warning when User try to save R-Group-member in Standalone mode

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#307]
**Affected Version:** _Standalone_
**Steps to Reproduce:**
1. Create chain structure.
2. Define it as R-Group member using 'R-Group Fragment tool'.
3. Click 'Save...' button.

**Expected Result:**
'Input structure is empty' warning is absent.

**Actual Result:**
'Input structure is empty' warning appears, but text field contains correct information and User can save structure and then open saved file.
![5](https://user-images.githubusercontent.com/75974465/107381176-a6a57c80-6aff-11eb-8acc-4e8f77485300.jpg)

**Comment by AndreiMazol** [comment]
Cannot reproduce

**Comment by KseniiaSemenishcheva** [comment]
Issue is closed as cannot reproduced.
