### ISSUE TITLE
Toolbars are not visible when browser zoomed in

### ISSUE THREAD

**Issue by vitaepam** [epam/ketcher#3094]
When a user Zooms their Browser to 110% or higher, a few oddities arise.

**Steps to Reproduce**
1. Open Ketcher in browser
2. Make window smaller, like if ketcher used as integrated iframe
3. Zoom in to 125% or 150%

**Actual behavior**
The bottom scroll bar and the bottom toolbar are off the screen such that the user has to scroll to the bottom of the page to see these tools.

The tool bar on the left side of the page does not fit all the tools into view so the user has to scroll to access a few of the tools that were pushed off of the page to the bottom.

**Expected behavior**
The toolbars shall be responsive so all tools are visible regardless of zoom and window size (within a reasonable range of course - no mobile support).

**Screenshots**
125%
<img width="778" alt="Screenshot 2023-08-11 at 17 54 24" src="https://github.com/epam/ketcher/assets/109075831/a9b56c37-c4e9-4f88-9101-d390828b8773">
150%
<img width="781" alt="Screenshot 2023-08-11 at 17 59 02" src="https://github.com/epam/ketcher/assets/109075831/2a3d0471-c8e5-418d-bd7b-f77c0bffb8c6">

**Desktop (please complete the following information):**
 - OS: all
 - Browser chrome at least

**Ketcher version** 
v2.13.0

#184068773

**Comment by MartaWilliams** [comment]
Tests passed  - after zooming in the browser to 125%/150% both toolbars are visible 
![image](https://github.com/epam/ketcher/assets/82752700/9c10a652-b414-4602-b9a6-7572f615c63a)
![image](https://github.com/epam/ketcher/assets/82752700/3994f55a-80ec-4be8-a652-a9fb05c94b65)
