### ISSUE TITLE
Selection processing doesn't work correctly

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#310]
**Affected Version:** _Remote_
**Steps to Reproduce:**
1. Open in Ketcher file [15Ritalin.zip](https://github.com/epam/ketcher/files/5956398/15Ritalin.zip).
2. With Selection tool select the ring containing the nitrogen and hydrogen.
3. Click 'Calculated Values' button.

**Expected Result:**
Molecular values dialog appears and displays the exact mass of the chosen fragment (C5H10N) Exact Mass: 84.081320

**Actual Result:**
Modal window appears with formula: C6H8 (according to Indigo response). When User select another part of big structure - response contains another random part of structure.
![2021-02-10_10h00_16](https://user-images.githubusercontent.com/75974465/107477101-3c84ea00-6b88-11eb-88e2-fd353a36d1f2.gif)

**Comment by AndreiMazol** [comment]
Calculate method still works incorrectly for reactions. It requires global refactoring so it should be fixed after implementing 'Internal Format' milestone
@KseniiaSemenishcheva

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed, another issue related with reactions will be opened with low priority.
