### ISSUE TITLE
Add support for exporting to InChiKey file format

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3114]
**Background**
We would like to support an ability to export to InchiKey format

**Solution**
The convertion will be happening on Indigo side, for Ketcher we need to:
 - Add a new item to save dialogue drop down: "InChiKey"
 - Send the correct mime-type to Indigo when this option is selected: "chemical/x-inchi-key"
 
#183545632

**Comment by Zhirnoff** [comment]
I also suggest renaming the 'generateInChIKey' method to 'getInChIKey' for better consistency
![MicrosoftTeams-image (4)](https://github.com/epam/ketcher/assets/62464241/671684ca-f509-4de2-a931-af5f34f546ac)

**Comment by Zhirnoff** [comment]
Pre-tested.
![2023-08-30_11h43_28](https://github.com/epam/ketcher/assets/62464241/7f158eef-97b9-4793-bc2f-c697f275eb65)
