### ISSUE TITLE
Remove dividers for items in the same group in bond context menu

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3124]
**Steps to Reproduce**
1. Draw any structure
2. Open right click menu for bond

**Actual behavior**
Divider is present

**Expected behavior**
There are no dividers between items in the same group

**Screenshots**
![Screenshot 2023-08-16 at 17 12 05](https://github.com/epam/ketcher/assets/41272128/eb4a0fed-b6e0-497b-a567-59450ed844a6)

**Test case**
Add test case number (in EPMLSOPKET-* format) if bug was found during test case run.

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

<img width="955" alt="image" src="https://github.com/epam/ketcher/assets/139227567/e0971e48-3a55-41b1-9d84-b7eb5d46c25b">
