### ISSUE TITLE
When dragging and dropping a Functional Group onto the structure, numerous errors appear in the console

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3128]
**Steps to Reproduce**
1. Open Ketcher
2. Open DevTool console
3. Add Benzene ring and contracted Functional Group on canvas
4. With Selection tool drag and drop Functional Group on any atom of Benzene ring
5. Look at DevTool console

**Actual behavior**
When dragging and dropping a Functional Group onto the structure, numerous errors appear in the console

**Expected behavior**
When a Functional Group is dragged and dropped onto the structure, no errors appear in the console.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/1d771ef4-8cdf-4ba1-942c-2b2552818de9

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.14.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

![2023-09-01_16h21_08](https://github.com/epam/ketcher/assets/139227567/1c0a9016-a4bf-4bed-8e41-fb6380775cf0)
