### ISSUE TITLE
Full template preview following mouse cursor

### ISSUE THREAD

**Issue by KonstantinEpam23** [epam/ketcher#3129]
**Background**
Currently when a template is selected - only its name is shown under cursor while the user is hovering over canvas, we would like to show the full preview of the template, similar how the "paste" tool works. Additionally a preview of how the template is going to be merged into other structures that are already present on canvas if applicable

**Solution**
- when a template is selected either from structure library or from the bottom tool bar (e.g. benzene ring) - a full preview of the template structure should be shown under the mouse cursor instead of just showing its name
- if a template will be merged with other structures on canvas after placement - a preview should also be shown for that
- paste tool should behave the same way as the template tool, including showing a correct preview of how the structure will be merged

**Comment by ViktoriaTkacheva** [comment]
1. When merging two Templates from the Template Library, the preview does not always appear, if hover the mouse over the side and not over the atom

![2023-09-13_15h06_38](https://github.com/epam/ketcher/assets/139227567/a55e6972-5095-4af4-abc4-baab49d9cb3e)

2. Bullet #3 from the Solution seems to be not implemented

![2023-09-13_14h51_35](https://github.com/epam/ketcher/assets/139227567/edb36925-7bad-45a3-9669-e9f32a30859c)

![2023-09-13_15h03_10](https://github.com/epam/ketcher/assets/139227567/74d77084-6eea-4b48-8d00-4317b2edcb90)

**Comment by Nitvex** [comment]
@ViktoriaTkacheva, discussed with @AlexanderSavelyev point 3 will be implemented in scope of other task. I will create it soon.
The bug about incorrect merge for some structures will be fixed.

**Comment by Zhirnoff** [comment]
Pre-tested. Bug is fixed. And fixed comments added by @rrodionov91 to https://github.com/epam/ketcher/pull/3252

**Comment by ViktoriaTkacheva** [comment]
1. Preview of Cycloheptane is displayed slightly rotated to the left, i.e. it doesn't quite match the Template in the Template Toolbar

<img width="651" alt="image" src="https://github.com/epam/ketcher/assets/139227567/6b5bd212-1be6-4671-8bc2-84117bd352db">

2. If you place a Template at the top of the canvas and try to add another Template to it from above, then the first Template begins to move down and it is difficult to attach another one to it

![2023-10-02_16h17_32](https://github.com/epam/ketcher/assets/139227567/d504a354-2b89-46c0-86ac-451a04009631)

3. If you add another Template from SL to the Template located at the top of the canvas, then the preview of the merge does not always match with what the real merge of 2 structures looks like

![2023-10-04_13h42_54](https://github.com/epam/ketcher/assets/139227567/7424ac12-be8b-4ece-bd58-a8f6fea8895c)

**Comment by ViktoriaTkacheva** [comment]
1. The bug has been moved to a separate ticket [#3437](https://github.com/epam/ketcher/issues/3437)
3. The bug has been moved to a separate ticket [#3438](https://github.com/epam/ketcher/issues/3438)
