### ISSUE TITLE
Unable to open the CDX file with an R-Group added to the entire structure

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3135]
**Steps to Reproduce**
1. Open Ketcher
2. Open file [R7.zip](https://github.com/epam/ketcher/files/12376735/R7.zip)
 or make Chain, add R-Group to whole structure and save it

**Actual behavior**
Unable to open the CDX file with an R-Group added to the entire structure

**Expected behavior**
File opens with an R-Group added to the entire structure

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.14.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by MartaWilliams** [comment]
Test failed - it's not possible to open the CDX file with an R-Group added to the entire structure

https://github.com/epam/ketcher/assets/82752700/d7167139-159c-4343-bab3-03e19e2c4ee0
