### ISSUE TITLE
Modify context menu when right-clicking on an atom and attachment point

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3143]
**Background**
At the moment, when we right-click on the attachment point itself, we only have the opportunity to 'Remove' it. Also, when clicking on an atom in the context menu, there is a mention of R-Groups ('Edit R-Group attachment point...'), which can confuse users, since the user associates the attachment point with the atom.

**Solution**
Include an "Edit..." option directly within the context menu of an attachment point. This would allow users to quickly access and modify attachment points
![2023-08-19_12h53_39](https://github.com/epam/ketcher/assets/62464241/ed2b0935-543f-4b12-ad33-391cb1f02de5)
Remove the mention of 'R-Group' from the context menu when clicking on an atom. The menu should look like this: "Edit attachment point... "
![2023-08-19_12h52_48](https://github.com/epam/ketcher/assets/62464241/808e3c01-24a8-4162-ab6b-d4cb16694262)

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

<img width="954" alt="image" src="https://github.com/epam/ketcher/assets/139227567/2b695c7b-9e58-4be4-83fe-c5a6b3e59f55">
<img width="950" alt="image" src="https://github.com/epam/ketcher/assets/139227567/8490a0b2-41ad-4d85-bc6a-1df18f6345d0">
