### ISSUE TITLE
The reaction shrinks if it is cut and pasted back on the canvas

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#3153]
**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Draw any reaction on the canvas
3.	Select, cut (Ctrl+X), and paste (Ctrl+V) the reaction on the canvas
4.	Verify what the reaction looks like
5.	Compare the result of 2 and 4 points

**Actual behavior**
The reaction is shrunk so that the molecules and symbols partially overlap each other

**Expected behavior**
The reaction looks the same, both before cutting and after pasting on the canvas

**Screenshots**
<img width="957" alt="image" src="https://github.com/epam/ketcher/assets/139227567/f925fbf1-0bb9-4c79-a7b2-46cc720ff2d0">

<img width="956" alt="image" src="https://github.com/epam/ketcher/assets/139227567/165f4b61-90be-479f-9f98-a6b8be295e68">

<img width="955" alt="image" src="https://github.com/epam/ketcher/assets/139227567/903b640d-abe1-4ae4-ab20-18a5841d940f">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (114.0.5735.199) x64

**Ketcher version** 2.14.0-rc.1

**Comment by urszula-gawlowska** [comment]
The same issue appears after saving the reaction as .ket or .rxn file and opening that file.

**Comment by ivanmaslow** [comment]
Issue is retested on RC env:
- Ketcher [Version 2.26.0-rc.5] Build at 2024-10-21; 15:27:55
- Version 1.25.0-rc.3.0-g795119115-wasm32-wasm-clang-19.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 130.0.6723.59 (Official Build) (64-bit)

It's not reproducible:
Reaction can be copied/cut and pasted correctly, also it can saved to ket and loaded with correct positions:
![image](https://github.com/user-attachments/assets/29109a0b-8305-466c-b2e0-b0aaa83c47df)
[ketcher (4).zip](https://github.com/user-attachments/files/17504895/ketcher.4.zip)
