### ISSUE TITLE
Drawing gets broken after dragging a Functional Group onto an atom

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3176]
**Steps to Reproduce**
1. Open Ketcher
2. Add Benzene ring to canvas
3. Add any Functional Group on canvas
4. With selection tool drag and drop Functional Group on any Benzene atom

**Actual behavior**
When dragging and dropping an abbreviation of Functional Group onto an atom in the structure, errors appear in the DevTools console.
Functional Group expands. After that, the user cannot continue to draw structures on the canvas. You can only click the clear canvas and continue to work.

**Expected behavior**
When dragging and dropping an abbreviation of Functional Group onto an atom in the structure, errors not appear in the DevTools console. 
Functional Group abbreviation not expands.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/f130ef8e-4216-4017-9a97-aef1191ff18b

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.14.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by ViktoriaTkacheva** [comment]
Issues that were not fixed within this task are moved to a separate ticket: https://github.com/epam/ketcher/issues/3241
