### ISSUE TITLE
Structure shifting to upper-left corner during zoom operations

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3203]
**Steps to Reproduce**
Scenario 1
1. Open Ketcher
2. Add Benzene ring at center of canvas
3. Zoom out using CTRL+mouse wheel
4. Zoom in using CTRL+mouse wheel

Scenario 2
1. Open Ketcher
2. Add Benzene ring at center of canvas
3. Zoom out using hotkeys CTRL-
4. Zoom in using hotkeys CTRL+

Scenario 3
1. Open Ketcher
2. Add Benzene ring at center of canvas
3. Zoom out using buttons on upper toolbar CTRL-
4. Zoom in using buttons on upper toolbar CTRL+

**Actual behavior**
Structure move to the upper-left edge of the canvas when Zoom out , and when Zoom in and Zoom out again, it consistently returns to that upper-left position.

**Expected behavior**
For the first scenario, zoom using the position of the mouse cursor as the zoom center on the canvas. For the second and third scenarios, use the visible area of the canvas as the zoom center.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/4f423b57-9003-4894-8348-ce5118676af1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.13.0-rc.5](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by MartaWilliams** [comment]
Test cases written
