### ISSUE TITLE
Error when User try to save structure in Daylight SMARTS format

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#322]
**Affected Version:** _Remote_
**Steps to Reproduce:**
1. Draw chain structure.
2. Click 'Save...' button.
3. Choose 'Daylight SMARTS' format from drop-down list.

**Expected Result:**
SMARTS string is generated.

**Actual Result:**
'Convert error. IndigoException: SMILES saver: SMARTS format availble for query only' error appears, SMARTS string is not generated.
![2021-02-12_14h33_02](https://user-images.githubusercontent.com/75974465/107764562-73523000-6d41-11eb-8a54-53af5d78b9f6.gif)

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified and closed.

**Comment by AllaZhbanova** [comment]
https://github.com/epam/Indigo/issues/525
