### ISSUE TITLE
Add shortcut [Shift+Tab] for switching selection mode

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3221]
**Background**
Esc behaviour was changed in scope of https://github.com/epam/ketcher/issues/2127

**Solution**
1) Esc should still reset current tool to Select tool

2) Add shortcut [Shift+Tab] for switching modes of selection tool (lasso, rectangle, structure selection)

**Alternatives**

**Additional context**

**Comment by MartaWilliams** [comment]
Test case written

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments
