### ISSUE TITLE
Macro: Enumeration of linear and branch chains.

### ISSUE THREAD

**Issue by isidoraotasevic** [epam/ketcher#3222]
### **Background**
This task covers enumeration of linear and branch chains.
AP - attachment point

Peptide linear chain - several (>=2) peptide monomers connected by bonds between R2 attachment point of one monomer and R1 attachment point of the next monomer. Several peptide chains could be connected to each other by the bonds that are distinct from R2-R1. 

RNA linear chain - several RNA monomers (phosphates and sugars), connected by bonds  between R2 attachment point of one monomer and R1 attachment point of the next monomer, AND bases, connected to sugars by bond established between R3 AP of sugar and R1 AP of base. 
Several RNA chains could be connected to each other by the R1-R1 bond between two phosphates or by the connections to additional AP on sugars, phosphates and bases. 

### **Requirements**

**For peptides:**

1. Enumeration of linear chain (all other connections except R2-R1 are ignored)
1.1 When at least two monomers are connected to each other, the system shall start with enumeration process.
1.2 The system shall start enumeration from the monomer, which has occupied R2 attachment point and:
- no R1 attachment point
- free R1 attachment point
- occupied R1 attachment point with the bond R1-Ri, i<>2
![image](https://github.com/epam/ketcher/assets/143799055/58d8d55b-e775-4e12-ac4a-2e1b3e2ec3c0)
![image](https://github.com/epam/ketcher/assets/143799055/cf828a12-cc5b-44d9-8d23-cc83c5a76755)

1.3 If there are no monomers mentioned in 1.2 enumeration shouldn't be performed.
1.4 If two monomers are connected through R2-R1 bond, then the number of next monomer should be n+1, where n is the number of previous monomer. The number of monomer should be displayed according to mockups (see comments). 
![image](https://github.com/epam/ketcher/assets/143799055/c67f489c-4431-4ef9-ad4e-98c19c94ba45)

2. Other connections
2.1 All connections except R2->R1 are considered as branch connections. Branch connections are ignored in enumeration process. 
2.2 The chains forming a branch should be enumerated independently. 
![image](https://github.com/epam/ketcher/assets/143799055/5c51e679-7638-42a6-9545-e265a751785f)
2.3 Two monomers connected with any bond except R2-R1 are considered as two chains made up from single monomer which are connected to each other. 

**For RNA:**
1. Linear chain
1.1 A set of RNA monomers (phosphates, sugars) with the bonds established between R2 and R1 attachment points are considered as **core** of RNA chain. 
1.2 Enumeration should be started from the phosphate or sugar, which has:
-no R1 attachment point
-free R1 attachment point
-occupied R1 attachment point with the bond R1-Ri, i<>2
 
1.3 If there are no monomers mentioned in 1.2 enumeration shouldn't be performed.
1.4 The system should walk along sugar-phosphate core from R2 to R1 until it meets the sugar with the base (attached to R3 AP via R3-R1 bond). Such base should be counted. It's number should be displayed according to mockups (see in comments).
![image](https://github.com/epam/ketcher/assets/143799055/0e0c9a23-ba0b-4a11-8458-4292a1770cc7)

2. Branch chain 
2.1 All connections except R2-R1 for core and R3-R1 for bases are considered as branch connections. Branch connections are ignored in enumeration process. 
2.2 The chains forming a branch should be enumerated independently.
![image](https://github.com/epam/ketcher/assets/143799055/6611a2b7-441b-482a-ae73-b421bb88a585)
 

### **Mixed chains**
1. When RNA chain is connected to peptide chain, each chain shall be counted separately.
2. If there is CHEM, connecting different monomers, then we should consider as different chains connected via chem. The chains are enumerated separately. Chem shouldn't be enumerated

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/f55e703e-abbc-47e9-9952-197aa7dd4ea9)
![image](https://github.com/epam/ketcher/assets/141816460/f8049201-2e09-4580-8283-8f75de085355)
![image](https://github.com/epam/ketcher/assets/141816460/45615ead-bd9d-45c0-bc8a-86ea6d9cd8d8)

**Comment by olganaz** [comment]
> ### **Background**
> This task covers enumeration of linear and branch chains. AP - attachment point
> 
> Peptide linear chain - several (>=2) peptide monomers connected by bonds between R2 attachment point of one monomer and R1 attachment point of the next monomer, all other connections are considered as branch.
> 
> RNA linear chain - several (>=2) RNA presets (phosphate-sugar-base ) connected by bonds between phosphate R2 attachment point of first preset and sugar R1 attachment point of the next preset, all other connections are considered as branch.
> 
> ### **Requirements**
> **For peptides:**
> 
> 1. Enumeration of linear chain (all other connections except R2-R1 are ignored)
>    1.1 When at least two monomers are connected to each other, the system shall start with enumeration process.
>    1.2 The system shall start enumeration from the monomer, which has occupied R2 attachment point and:
> 
> * no R1 attachment point
> * free R1 attachment point
> * occupied R1 attachment point with the bond R1-Ri, i<>2
>   ![image](https://user-images.githubusercontent.com/143799055/284893768-58d8d55b-e775-4e12-ac4a-2e1b3e2ec3c0.png)
>   ![image](https://user-images.githubusercontent.com/143799055/285512948-cf828a12-cc5b-44d9-8d23-cc83c5a76755.png)
> 
> 1.3 If there are no monomers mentioned in 2. enumeration shouldn't be performed. 1.4 If two monomers are connected through R2-R1 bond, then the number of next monomer should be n+1, where n is the number of previous monomer. The number of monomer should be displayed according to mockups (see comments). ![image](https://user-images.githubusercontent.com/143799055/284931379-c67f489c-4431-4ef9-ad4e-98c19c94ba45.png)
> 
> 2. Other connections
>    2.1 All connections except R2->R1 are considered as branch connections. Branch connections are ignored in enumeration process.
>    2.2 The chains forming a branch should be enumerated independently.
>    ![image](https://user-images.githubusercontent.com/143799055/285447166-5c51e679-7638-42a6-9545-e265a751785f.png)
>    2.3 Two monomers connected with any bond except R2-R1 are considered as two chains made up from single monomer which are connected to each other.
> 
> **For RNA:**
> 
> 1. Linear chain
>    1.1 A set of RNA monomers (phosphates, sugars) with the bonds established between R2 and R1 attachment points are considered as **core** of RNA chain.
>    1.2 Enumeration should be started from the phosphate or sugar, which has:
>    -no R1 attachment point
>    -free R1 attachment point
>    -occupied R1 attachment point with the bond R1-Ri, i<>2
>    1.3 If there are no monomers mentioned in 1.2 enumeration shouldn't be performed.
>    1.4 The system should walk along sugar-phosphate core from R2 to R1 until it meets the sugar with the base (attached to R3 AP via R3-R1 bond). Such base should be counted. It's number should be displayed according to mockups (see in comments).
>    ![image](https://user-images.githubusercontent.com/143799055/285444257-0e0c9a23-ba0b-4a11-8458-4292a1770cc7.png)
> 2. Branch chain
>    2.1 All connections except R2-R1 for core and R3-R1 for bases are considered as branch connections. Branch connections are ignored in enumeration process.
>    2.2 The chains forming a branch should be enumerated independently.
> 
> ### **Mixed chains**
> When RNA chain is connected to peptide chain, each chain shall be counted separately. 
> If there is CHEM, connecting different monomers, then we should consider this kind of structure as different chains connected via chem. The chains are enumerated separately. Chem shouldn't be enumerated

**Comment by AlexeyGirin** [comment]
![image](https://github.com/epam/ketcher/assets/26869421/efed97ef-a226-4783-a664-682f5b36d364)
