### ISSUE TITLE
Appearing label near the Template after choosing any option in the "Edit" or "Query properties" tab in the context menu disappears when clicking on the canvas

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#3224]
**_Case 1: An option in the "Query properties" tab_**

**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Draw any Template structure (like Benzene) on the canvas
3.	Hover the mouse cursor on any atom of this structure and right-click
4.	Click on the "Query properties" drop-down list in the context menu
5.	Choose the variant "2" in the "Ring bond count" drop-down list
6.	Click on the canvas and move the mouse cursor

**Actual behavior**
The label "rb2" near the Template disappears 

**Expected behavior**
The label "rb2" remains near the Template

**Screenshots**
![2023-08-30_17h53_02](https://github.com/epam/ketcher/assets/139227567/e44cbfcd-ee28-4c2f-ad1e-c7f73d7e17f5)

**_Case 2: An option in the "Edit" tab_**

**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Draw any Template structure (like Benzene) on the canvas
3.	Hover the mouse cursor on any atom of this structure and right-click
4.	Click on the "Edit" button in the context menu
5.	Choose the variant "III" in the "Valence" drop-down list inside "General"
6.	Click the "Apply" button
7.	Click on the canvas or move the mouse cursor

**Actual behavior**
The label "C(III)" near the Template disappears 

**Expected behavior**
The label "C(III)" remains near the Template

**Screenshots**
![2023-08-30_17h54_50](https://github.com/epam/ketcher/assets/139227567/e4b3da07-3ea0-4060-9deb-20531e118225)

**_Case 3: Adding another Template to the Template that is on the canvas_**
**NOTE** this behaviour is expected, not a bug

**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Draw any Template structure (like Benzene) on the canvas
3.	Hover the mouse cursor on any atom of this structure and right-click
4.	Click on the "Edit" button in the context menu
5.	Specify the label "V"
6.	Choose the variant "III" in the "Valence" drop-down list inside "General"
7.	Choose the variant "Diradical" in the "Radical" drop-down list inside "General"
8.	Click the "Apply" button
9.	Click on the canvas or move the mouse cursor
10.	Select another Template and merge it with the Template, that is on the canvas, near the atom where the properties are specified

**Actual behavior**
The label with properties disappears

**Expected behavior**
The label with properties remains near the Template

**Screenshots**
![Ketcher v2 14 0 - Google Chrome 2023-08-30 13-12-19](https://github.com/epam/ketcher/assets/139227567/bb42fec3-e188-49c5-b1dc-bea20deeff29)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (114.0.5735.199) x64

**Ketcher version** 2.14.0-rc.2

**Comment by ViktoriaTkacheva** [comment]
The first and second cases are fixed, but the third case is still reproduced

![2023-09-01_12h15_29](https://github.com/epam/ketcher/assets/139227567/531706e1-2b12-450e-9019-70d7ff938753)

**Comment by KonstantinEpam23** [comment]
@ViktoriaTkacheva @Nitvex I propose moving the third scenario into a separate ticket as it is not related to the preview feature. In the current fix moving mouse away from the atom hides the preview and persists the changes on the atom correctly.


https://github.com/epam/ketcher/assets/101649391/efdcbc5e-2032-4ce6-b02b-0ef6e7b68652

**Comment by Zhirnoff** [comment]
@KonstantinEpam23 @Nitvex @ViktoriaTkacheva  I would suggest fixing this bug in the same ticket. But if we make it separate, then it would also be worth fixing it in 2.15, since the client will carefully look at the implementation of this function.

**Comment by KonstantinEpam23** [comment]
@Zhirnoff @ViktoriaTkacheva discussed scenario 3 with @AlexanderSavelyev, according to him - this is expected behaviour as the new atom replaces the one which properties were modified
