### ISSUE TITLE
Macro: Rna monomer accordion library should open from top to bottom

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3250]
Currently rna monomer accordion library is on the bottom of page. It needs to place it directly below the rna builder and change arrow icons in opposite way:
<img width="1511" alt="image" src="https://github.com/epam/ketcher/assets/14859362/a4ee44a2-bd12-4d7a-a650-60c09f243e63">
<img width="219" alt="image" src="https://github.com/epam/ketcher/assets/14859362/5e47da44-62bb-40f2-a73b-a20d6194a264">

**Comment by MartaWilliams** [comment]
Tested 
![image](https://github.com/epam/ketcher/assets/82752700/9c3984f7-2856-43d0-a541-63fa9b5d152c)
