### ISSUE TITLE
Macro: Rna preset name should be autofilled when user selects rna parts

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3251]
Currently rna name is not autofilling when user selects rna parts.
It needs to autofill it in case if user didn't input the name manually:
<img width="756" alt="image" src="https://github.com/epam/ketcher/assets/14859362/2e09f638-2813-44cc-81c0-0554b6010619">

**Comment by MartaWilliams** [comment]
Tested
![2023-10-24_11h00_34](https://github.com/epam/ketcher/assets/82752700/08084cee-ab14-4d19-9c8d-8f135f1c05d9)
![2023-10-24_11h01_25](https://github.com/epam/ketcher/assets/82752700/8b1aec65-d9a9-43ab-b955-8d2b9ed6b196)
