### ISSUE TITLE
Inability to save a structure with R-Group in the SDF file format

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#3265]
**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Draw any structure on the canvas
3.	Click on the "R-Group Fragment Tool" button
4.	Click on the structure on the canvas
5.	Select any R-Group and click on the "Apply" button
6.	Click on the "Save as" button
7.	Select the "SDF V2000" or "SDF V3000" file format
8.	Click on the "Save" button
9.	Verify if the saved file is in the "Downloads"

**Actual behavior**
The structure with R-Group is not saved in the SDF file format

**Expected behavior**
The structure with R-Group is saved in the SDF file format

**Screenshots**
![2023-09-06_15h27_44](https://github.com/epam/ketcher/assets/139227567/9e35214d-bee9-4d8a-97a3-600ff29dfb32)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (114.0.5735.199) x64

**Ketcher version** 2.15.0-rc.1

**Comment by Nitvex** [comment]
It seems to be an Issue on Indigo side. When you select any of SDF format the structure is sent to Indigo:
![image](https://github.com/epam/ketcher/assets/41272128/a16c26b2-e52a-4c5d-b52a-b59c7a8828f8)

But as a response Ketcher receives an empty string:
![image](https://github.com/epam/ketcher/assets/41272128/998530a9-2d18-49d7-9b43-d4cdb57bad31)

**Comment by Zhirnoff** [comment]
Bug registered on Indigo side https://github.com/epam/Indigo/issues/1256
