### ISSUE TITLE
Remove 'Edit attachment point...' from right-click context menu 

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3276]
**Background**
At the moment, we have the 'Edit attachment point...' menu when right-clicking on both atoms with an attachment point and atoms without an attachment point

**Solution**
Remove the option 'Edit attachment point...' from the context menu when right-clicking on an atom

![2023-09-07_15h09_36](https://github.com/epam/ketcher/assets/62464241/947b1154-c4cc-4f30-aba2-0aad0eddbe1c)

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

<img width="953" alt="image" src="https://github.com/epam/ketcher/assets/139227567/deb91513-60d1-478e-818b-086f49bb6326">
