### ISSUE TITLE
RNA Phosphates are filtered wrong

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3277]
0. Macromolecule builder
1. Go to RNA library
2. Go to Phosphates
3. Scroll to P and dP 
![image](https://github.com/epam/ketcher/assets/143799055/35c3c687-d2e7-4bb8-a70e-6f4f4593fd00)
![image](https://github.com/epam/ketcher/assets/143799055/85c7aaca-7960-49be-a415-121d80a823b4)
![image](https://github.com/epam/ketcher/assets/143799055/ffb4bfc1-696b-418c-b8ff-f4c9c05f9748)

Observe:
These are Proline and D-Proline,  MonomerType: Peptide.

It looks like the same as https://github.com/epam/ketcher/issues/3174

**Comment by MartaWilliams** [comment]
Tested 
![2023-10-24_11h10_14](https://github.com/epam/ketcher/assets/82752700/630a3b93-2c43-43fb-9743-2d7ccc1023ca)
![2023-10-24_11h11_54](https://github.com/epam/ketcher/assets/82752700/addec7a8-8a41-4dc4-855f-95137a51856d)
