### ISSUE TITLE
Displaying a long peptide chain on a canvas. Snake-like layout 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3280]
Displaying a long peptide chain on a canvas. Snake-like layout

1. The user should be able to upload a long polypeptide chain onto the canvas.
2. Bonds between monomers are formed by default between R2 of the first monomer and R1 of the next monomer.
3. When the layout button is pressed, the monomers from the chain should be arranged on the screen in a snake-like pattern. And while this button is active - the "snake-like" mode is ON. 
4. Depending on the length of the chain, the algorithm should calculate the length of one row and the size of the monomers so that the entire chain fits on the canvas.
5. Monomers in each row are ordered from left to right.
6. The bond between the last monomer in a row and the next one should be shown as a broken line with smoothed corners.
7. After creating layout  new monomers can be added and existing monomers can be moved while the bonds remain rectangular and appropriately rebuilt.
8. If there are multiple chains of monomers on the canvas, each chain is arranged independently of the others, but they altogether should fit on the canvas.
     a. Each interconnected set of monomers (chain) is arranged into the left-to-right (snake) view separately. "Snakes" are arranged from top to bottom, every snake starts from a new row.
       b. Once the layout button is pressed, the top (first) chain is defined by the top left monomer on canvas, i.e. the chain it is part of will be the first one.
       c.  Similarly, second chain is the one that includes new top left monomer that is not part of the first chain, etc

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/7217c174-d501-4fbc-9796-c7f1159390b3)

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/0f068265-b86f-4d50-937f-a638c86356a1)
![image](https://github.com/epam/ketcher/assets/141816460/2fb19f92-fa2d-4aec-9f8a-a9bf632e32b2)

**Comment by MartaWilliams** [comment]
Tested 
![2023-10-24_10h12_15](https://github.com/epam/ketcher/assets/82752700/da474fa5-2478-44ca-87a9-2c9319bb283c)
![2023-10-24_10h06_43](https://github.com/epam/ketcher/assets/82752700/3879828b-0062-4235-9bd6-260a63c226bf)
![2023-10-24_10h19_58](https://github.com/epam/ketcher/assets/82752700/af7b803c-77d2-4d2b-b199-ed02fffa8db8)
![2023-10-24_10h26_26](https://github.com/epam/ketcher/assets/82752700/228035cc-19c7-4ba9-8ee4-471d1ce2c5cb)
