### ISSUE TITLE
Daylight SMARTS support

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#3294]
**Background**
In Ketcher not all the SMARTS features are supported

**Solution**
All the functions the normal Daylight SMARTS have to offer, mainly with the goal to do substructure searches, including but not limited to:
* Atom Features:
    * Atom Lists
    * Implicit H (h)
    * Explicity H (H)
    * Bond order (v)
    * Atomic Connections (X)
    * Explicit Connections (D)
    * Total Ring Connections (x)
    * Ring Count (R)
    * Smallest Ring Size (r)
    * Ring Bonds (rb)
    * Substitution Count (s)
    * Unsaturated (u)
    * Aromaticity (a/A)
    * Recursive SMARTS ( $() )
    * Atomic Element (#n)
    * Atomic Mass (nC)
    * Any Atom (*)
    * Any Heavy Atom (Q)
    * Any Halide (X).
* Bond Features:
    * Single (-)
    * Double (=)
    * Triple (#)
    * Aromatic (:)
    * Any (~)
    * Any Ring (@)
    * Directional Up (/)
    * Directional Down (\)
    * Directional Unspecified (/? or \?)
* Logical Operators:
    * NOT (!)
    * AND (&)
    * OR (,)
    * AND low precedence (;)
* Reaction Queries:
    * Reaction Separator (>>)
    * Atomic Mapping (C:number)
    * Component Level Grouping (i.e. (C).(C) )
* Wildcards
* Ability to import/export in the standard format including a *.smarts.
* The importing/exporting of SMARTS should also be possible via the Clipboard

**Comment by AlexeyGirin** [comment]
Done.
