### ISSUE TITLE
Support multiple AP

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#3296]
**Requirements**

The system should recognize multiple attachment points (R1...Rn) (structures from uploaded *.mol files or .sd file for Monomer Library) and represent them on canvas. Each AP should have a visual representation to be able to select a specific point.

**Comment by SashaGraves** [comment]
1) Multiple attachment points are possible
2) reading from .mol and .sd file
3) Ability to draw bond to specific attachment point - currently in is drawn from center to center

**Comment by SashaGraves** [comment]
The placements of unused attachment points:
                         top R3
            left top          right top
              corner             corner
                 R5                     R6
left R1.                                        right R2
                       bottom R4


Aproved by Aleksandr Savelev
