### ISSUE TITLE
Add simple atom query primitives to the query specific properties

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#3298]
**Background**
Current set of atom query features lacks certain attributes supported by SMARTS standard. Missing features should be supported in Ketcher per below specification

**Solution**

**1. Add following properties into the "Atom Properties/Query Specific" list of atom attributes.**

* Aromaticity (drop-down)
    * empty (default)
    * aromatic
    * aliphatic
* Degree (drop-down)
    * empty (default)
    * 0
    * 1
    * 2
    * 3
    * 4
    * 5
    * 6
* Implicit H count (drop-down)
    * empty (default)
    * 0
    * 1
    * 2
    * 3
    * 4
* Ring membership (drop-down)
    * empty (default)
    * 0
    * 1
    * 2
    * 3
    * 4
    * 5
* Ring size (drop-down)
    * empty (default)
    * 0
    * 1
    * 2
    * 3
    * 4
    * 5
* Connectivity (drop-down)
    * empty (default)
    * 0
    * 1
    * 2
    * 3
    * 4
    * 5
* Ring connectivity (drop-down)
    * empty (default)
    * 0
    * 1
    * 2
    * 3
    * 4
    * 5
* Chirality (drop-down)
    * empty (default)
    * anticlockwise
    * clockwise
* Atomic mass (input field)
    * empty (default)
    * any number (> 0, < 1000) 

**2. Add following properties into the right click menu for the atoms/Query Properties (take values from the table above)**

* Aromaticity 
* Degree 
* Implicit H count 
* Ring membership
* Ring size
* Connectivity 
* Ring connectivity

**3. Replace comma with semicolon between Atom properties:**  

![image](https://github.com/epam/ketcher/assets/16281184/cbf0fd65-edf4-400c-9005-99446bb801f2)

Atom query properties should be stored in and loaded from KET format per specification provided in https://github.com/epam/ketcher/issues/3323

**Comment by MartaWilliams** [comment]
Test cases written

**Comment by ViktoriaTkacheva** [comment]
1. When saving a structure with Atom Properties in .Ket format, in Preview the "hCount" indicator in different cases is constantly greater by 1 than it is displayed on the canvas

<img width="944" alt="image" src="https://github.com/epam/ketcher/assets/139227567/d97f370f-0f1a-43b8-b270-7aac178fbfe4">


2. If add Atom Properties to the structure (see the screenshot below) and click "Save as", an error is displayed, but this error can be closed, and save the file. The file opens correctly in .Ket format, but distorted in .mol format (not all Atom Properties are displayed)

<img width="953" alt="image" src="https://github.com/epam/ketcher/assets/139227567/4b68a5e6-d8b8-4fc6-89ef-595849c7bfd0">


3. If add slightly different Atom Properties to the structure (see the screenshot below) and save it in .Ket format, then when opening this file, an error appears and the file does not open

<img width="957" alt="image" src="https://github.com/epam/ketcher/assets/139227567/c7c08269-45b5-40b5-853a-6a7db2d363e9">

**Comment by AKZhuk** [comment]
> 1. When saving a structure with Atom Properties in .Ket format, in Preview the "hCount" indicator in different cases is constantly greater by 1 than it is displayed on the canvas
> 
> <img alt="image" width="944" src="https://user-images.githubusercontent.com/139227567/272626520-d97f370f-0f1a-43b8-b270-7aac178fbfe4.png">
> 2. If add Atom Properties to the structure (see the screenshot below) and click "Save as", an error is displayed, but this error can be closed, and save the file. The file opens correctly in .Ket format, but distorted in .mol format (not all Atom Properties are displayed)
> 
> <img alt="image" width="953" src="https://user-images.githubusercontent.com/139227567/272628154-4b68a5e6-d8b8-4fc6-89ef-595849c7bfd0.png">
> 3. If add slightly different Atom Properties to the structure (see the screenshot below) and save it in .Ket format, then when opening this file, an error appears and the file does not open
>  
> <img alt="image" width="957" src="https://user-images.githubusercontent.com/139227567/272629971-c7c08269-45b5-40b5-853a-6a7db2d363e9.png">  
1 - not  a bug, the same behaviour in version 2.13.0
2,3 - **_- fixed in https://github.com/epam/ketcher/pull/3398_**

**Comment by ViktoriaTkacheva** [comment]
2. The bug has been moved to a separate ticket https://github.com/epam/Indigo/issues/1311
3. The bug is fixed
