### ISSUE TITLE
Snake mode of peptide chain drawing

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3310]
1. There are two modes available: Snake and Graph
2. By default, in Graph mode all bonds are established center-to-center in a straight lines
3. When user switches switches to Snake mode:
 а) All monomers are arranged in rows
 b) All bonds are switched to "rectangular" mode, i.e. bonds are capable of turning 90 degrees, allowing the user to shift certain parts of a bond.
4. In Snake mode, new monomers can be added and existing monomers can be moved to any position while the bonds remain rectangular and appropriately rebuilt.
5. When switching back to Graph mode, all monomers remain in place and bonds revert to simple straight lines from center to center.

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/bf2a0b44-eb42-4054-a91e-144ce57cd790)
