### ISSUE TITLE
Update schema.json for atom query specific properties

### ISSUE THREAD

**Issue by AKZhuk** [epam/ketcher#3323]
**Background**
Some of the SMARTS features should be described in schema.json

**Solution**
Add following properties into schema.json: 

All properties should be added into new "queryProperties" group in Atom

- Aromaticity
    * name: aromaticity
    * type: string
    * enum: ["aromatic", "aliphatic"] 
- Degree
    * name: degree
    * type: integer
    * minimum: 0
    * maximum: 6
- Ring membership 
    * name: ringMembership
    * type: integer
    * minimum: 0
    * maximum: 5
- Ring size 
    * name: ringSize
    * type: integer
    * minimum: 0
    * maximum: 5
- Connectivity
    * name: connectivity
    * type: integer
    * minimum: 0
    * maximum: 5
- Ring connectivity 
    * name: ringConnectivity
    * type: integer
    * minimum: 0
    * maximum: 5
- Atomic mass 
    * name: atomicMass
    * type: integer
    * minimum: 0
    * maximum: 1000
- Chirality
    * name: chirality
    * type: string
    * enum: ["clockwise", "anticlockwise"]
- Custom Query
    * name: customQuery
    * type: string

**Comment by AliaksandrDziarkach** [comment]
implicitHCount already in schema.
