### ISSUE TITLE
Macro: Switching micromolecules mode to macromolecules(readonly)

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3330]
**Background**
Users want to switch between macro/micro modes to clearly see the structures on both levels.

**Solution**
This task is the first iteration. It includes only readonly mode of structures which were created in different mode. All entities should keep their positions on canvas in both modes.

Macromolecules in micromode will be represented as SGroups with bonds and ability to see preview of monomer structure.
<img width="525" alt="image" src="https://github.com/epam/ketcher/assets/14859362/effa1add-d766-46a7-967f-9beab487f3f8">

Micromolecules in macromode will be represented as CHEMs with generated name(F1, F2, ...Fn).

**Comment by y-holik** [comment]
tested and passed
