### ISSUE TITLE
Add empty options for atom charges and isotops

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#3339]
**Background**
Current charge and isotope default value is 0 which makes it incorrect when using inside a SMARTS query

**Solution**
* Add `empty` values for the charge and isotope (not specified)
* Validation for charge should be integer, minimum -1000, maximum 1000
* Validation for isotope: integer, minimum 0, maximum 1000
* isotope should be added for the SMARTS custom query only if atom is specified (not any atom or atom list)
* e.g. if charge is 0 then customQuery = `+0`
* atom = carbon and isotope=12 then customQuery = `12#6`
* atom = carbon, aromaticity=aliphatic and isotope=13 then customQuery = `13C`

**Comment by ViktoriaTkacheva** [comment]
The isotope is displayed before the element – based on the examples in Solution, the isotope should be displayed after the element   


https://github.com/epam/ketcher/assets/139227567/09c20361-4025-44c5-9ace-cd1788fb9ca5
