### ISSUE TITLE
Horizontal scroll appears after opening certain structures

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3347]
**Steps to Reproduce**
1. Open horizontally long structure
2. Horizontal scroll bar appears

**Actual behavior**
Horizontal scroll bar appears

**Expected behavior**
Horizontal scroll bar doesn't appear

**Comment by Zhirnoff** [comment]
Pre-tested. Bug is fixed.
![2023-09-22_13h56_14](https://github.com/epam/ketcher/assets/62464241/7798a5b7-e06b-40f2-b260-8aa38c266b9d)
