### ISSUE TITLE
Bugs while scrolling the canvas by dragging a structure

### ISSUE THREAD

**Issue by nanoblit** [epam/ketcher#3350]
**Steps to Reproduce**
Create 2 structures such as Benzene for comparison, select one of them and drag it.

**Actual behavior**
When the view is moved up or left and trying to move a structure up or left further, there is an area on the screen where the view will scroll backwards.

**Expected behavior**
The view should scroll in the desired direction.

**Video**

https://github.com/epam/ketcher/assets/7485739/a2eb818b-0217-48b2-875d-6f946eff761b

**Actual behavior**
When moving a structure down or right and scrolling then leaving the structure, the canvas will be resized unpredictably. If the user doesn't scroll back, the canvas will be resized. If they do, the canvas might not be resized.

**Expected behavior**
The canvas should always scale when placing a structure with a scrollbar.

**Video**

https://github.com/epam/ketcher/assets/7485739/ab5db075-08f0-4a18-ab7d-70f5d6895906

**Actual behavior**
When moving the structure down and then left or right / moving the structure right then up or down, the canvas position will reset. This doesn't happen for up and left.

**Expected behavior**
The canvas position shouldn't reset when changing directions while dragging a structure.

**Video**

https://github.com/epam/ketcher/assets/7485739/7adb27ac-cb36-42c3-ac1d-92e45c57e1ae

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 116

**Ketcher version**
v2.15.0

**Additional context**
Should be done after https://github.com/epam/ketcher/pull/3342 is merged.

**Comment by Zhirnoff** [comment]
The bug is not reproducible in version 2.17.0-rc.1
