### ISSUE TITLE
bug: A memory error is occurring in standalone mode.

### ISSUE THREAD

**Issue by HHongSeungWoo** [epam/ketcher#3355]
**Steps to Reproduce**
1. using standalone mode in react editor
2. When re-rendering the editor, the 'indioWorker' is re-initialized each time.

**Actual behavior**
```Runtimeerror: memory access out of bounds.```
It appears to be an error that occurs only in specific environments

**Expected behavior**
Errors should not occur.

**Screenshots**
![image](https://github.com/epam/ketcher/assets/34399997/81034c47-7a36-4805-8ad3-1ff8c924091a)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: 117

**Ketcher version** [e.g. v2.4.2]. 
```    
"ketcher-core": "^2.12.0",
"ketcher-react": "^2.12.0",
"ketcher-standalone": "^2.12.0"
```

**Comment by HHongSeungWoo** [comment]
We are using the 'ketcher-standalone' module with a patch. When it's initialized only once, the error disappears, and performance improves
```
var _init = null;

var StandaloneStructServiceProvider = function () {
    function StandaloneStructServiceProvider() {
        _classCallCheck(this, StandaloneStructServiceProvider);
        _defineProperty(this, "mode", 'standalone');
    }
    _createClass(StandaloneStructServiceProvider, [{
        key: "createStructService",
        value: function createStructService(options) {
            if (_init) {
                return _init;
            }

            _init = new IndigoService(options);

            return _init;
        }
    }]);
    return StandaloneStructServiceProvider;
}();
```

**Comment by elramus** [comment]
We are observing this same crash too on Macs using Chrome/Brave. Seemed to appear with v117 of Chromium.

**Comment by elramus** [comment]
FWIW we're no longer seeing this crash and suspect the issue was fixed in a later version of Chromium 🤞

**Comment by HHongSeungWoo** [comment]
I'm not getting any errors anymore either!~!
