### ISSUE TITLE
When you replace an atom with the selected one from Periodic table, additional symbols appear next to it.

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3362]
**Steps to Reproduce**
1. Open Ketcher
2. Make two atoms connected with bond
3. Select any element from Periodic table
4. Click to first atom on canvas

**Actual behavior**
When you replace an atom with the selected one, additional symbols appear next to it.

**Expected behavior**
When you replace an atom with the selected one, no additional symbols appear next to it.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/10efc814-4c0f-432d-8042-1d80a8afbdad

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.15.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

![2023-10-04_15h29_23](https://github.com/epam/ketcher/assets/139227567/d1cc6f6a-d6f3-4318-8264-12495223e707)
