### ISSUE TITLE
Merge ring bond count, degree and atomic mass atom properties

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#3371]
**Background**
Right now it there are duplicates for the following properties

isotope=atomic mass
ring bond count = ring connectivity
substitution count=degree

**Solution**
* Rename `Isotope` into `Isotope (atomic mass)`
* Remove `Atomic mass` from "Query specific" and use the `Isotope (atomic mass)` field to load/save and display the atomic mass
* Remove `Degree` from "Query specific" and use `Substitution count` to load/save and display the degree. Display should be s`n`
* Increase number of options for `Substitution count` up to 9
* Remove `Ring connectivity` from "Query specific" and use `Ring bond count` to load/save and display the rings count. Display should be rb`n` 
* Increase number of options for `Ring bond count` up to 9
* Increase all the "Query specific" properties which are drop-down up to 9. The same should be applied for right-click menu as well

**Comment by ViktoriaTkacheva** [comment]
The "H count" indicator in the "Query specific" section was increased only to 8, but it needs to be increased to 9 (as specified in the Solution section)

<img width="949" alt="image" src="https://github.com/epam/ketcher/assets/139227567/7eba876b-bcdc-4183-80ff-95c3b8cdd767">

**Comment by AKZhuk** [comment]
> The "H count" indicator in the "Query specific" section was increased only to 8, but it needs to be increased to 9 (as specified in the Solution section)
> 
> <img alt="image" width="949" src="https://user-images.githubusercontent.com/139227567/272619344-7eba876b-bcdc-4183-80ff-95c3b8cdd767.png">

fixed in https://github.com/epam/ketcher/pull/3398

**Comment by ViktoriaTkacheva** [comment]
The bug is fixed

<img width="626" alt="image" src="https://github.com/epam/ketcher/assets/139227567/773eebca-7d7f-4d69-aa6b-72db00d38457">
