### ISSUE TITLE
Update customQuery for bonds using topology

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#3372]
**Background**
Custom query for bonds do not take the topology correctly all the time

**Solution**
* If topology = "Either" then customQuery should be empty e.g. Type=Single, Topology=Either => customQuery=`-`
* If topology = "Ring" then customQuery should be `@`, e.g. Type=Double, Topology=Ring=>customQuery=`=;@`
* If topology = "Chain" then customQuery should be `!@`, e.g. Type=Triple, Topology=Chain=>customQuery=`=;!@`

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

<img width="954" alt="image" src="https://github.com/epam/ketcher/assets/139227567/ddb44ced-c04d-43bc-ad84-61d511986c10">
