### ISSUE TITLE
Macro: Rotate attachment point unused

### ISSUE THREAD

**Issue by SashaGraves** [epam/ketcher#3373]
## Background
Monomer connection point (CP) rotates around the center of the monomer if CP is connected to a bond and the bond changes its position relatively to the monomer. In certain cases rotated CP may partially or fully overlap with another CP. In order to minimize the amount of such cases free connection points should be rearranged around the monomer once such an overlap occurs.

Example of current behaviour:
<img width="152" alt="image" src="https://github.com/epam/ketcher/assets/60065704/430d8aff-6004-4bb1-9a79-dcc8bd688065">

Example of expected behaviour:
<img width="152" alt="image" src="https://github.com/epam/ketcher/assets/60065704/3deaea49-7b9e-481e-a130-853cedae08c6">

## Solution:

The rules for rearrangement are as follows:

1. Only free CPs should be rearranged, connected ones should keep their positions.
2. Free CPs should be rearranged only when CP rotation is finished, no rearrangements while user keeps dragging connected monomer. 
3. There are 8 predefined sectors with center axis at 0 (right), 45, 90 (top), 135, 180 (left), 225, 270 (down) and 315 degrees. Two CPs are considered overlapping if they appear in the same sector, i.e. they overlap or are close enough. 
4. Once rearrangement starts, first priority is to move each free CP to the center of its default sector: R1 - left, R2-right, R3-top, R4-bottom, R5-top-left, R6-top-right, R7-bottom-left, R8-bottom-right. 
5. Free CP can be moved to its default sector if there is no connected CP in this sector, other free CPs are not taken into consideration. If CP cannot be moved to its default connection, it is assigned to a sector on further steps (see below).
6. Once CPs assignment on default positions is finished, second priority is to keep free CPs at their old positions if no conflicts occurred on previous steps. 
7. Remaining free CPs are distributed across available sectors, where available sector is the one having neither connected nor free CP. The algorithm should search through sectors starting from the one at 0 degrees and moving clockwise.

<img width="400" alt="image" src="https://github.com/epam/ketcher/assets/18439849/c63d53ac-bddd-4b2c-8081-e660b5555aa1">

**Comment by MartaWilliams** [comment]
Tested - functionality works correctly, only attachment points are sometimes on different heights/ have different length
![image](https://github.com/epam/ketcher/assets/82752700/f26a5488-8af7-4171-826b-256a360eddef)
