### ISSUE TITLE
Templates in template library are shifted down when Ketcher have less than 855px width

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/ketcher#338]
**Affected Version:** _Remote, Standalone_
**Steps to Reproduce:**
1. Launch Ketcher.
2. Open Templates.
3. Resize window to 854px width and lower.

**Expected Result:**
User can see templates with different size of Ketcher.

**Actual Result:**
Templates are shifted down under list of templates groups.
![templates](https://user-images.githubusercontent.com/75974465/108495382-c7b55c80-72b9-11eb-8092-d6403ed27cde.jpg)

**Comment by AndreiMazol** [comment]
Reopened. Two scrolls are rendered:
![image](https://user-images.githubusercontent.com/72735611/110636045-dc03bf80-81bc-11eb-93d9-4679b7ced2fc.png)

**Comment by Svetlana-Asinovskaia** [comment]
Issue is closed as fixed
