### ISSUE TITLE
Save atom properties for atom list in ket format

### ISSUE THREAD

**Issue by AKZhuk** [epam/ketcher#3387]
**Background**
Atom properties are not saved with atom list

**Solution**
All the atom properties (general and query) should be saved/loaded in ket format

**Comment by ViktoriaTkacheva** [comment]
Preview. No comments

<img width="953" alt="image" src="https://github.com/epam/ketcher/assets/139227567/c9d34395-e7cd-4b86-89cf-565a9e48427e">
