### ISSUE TITLE
Extend Text tool by bold, italic, subscript and superscript support

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#339]
It is necessary to enhance current plain text editor tool by adding the following functionality:

* There is a possibility to change a style to bold and italic, make subscript and superscript
* User can change the styles while text typing or/and by select a substring and applying styles

**Comment by AndreiMazol** [comment]
Issue blocked by #144

**Comment by Svetlana-Asinovskaia** [comment]
Either subscript or superscript button should be selected at the same time.

Current behavior: 
![2021-05-18_17h35_33](https://user-images.githubusercontent.com/80695128/118670794-99371700-b7ff-11eb-8a2e-8b9823a02995.gif)
