### ISSUE TITLE
When you save atom in ket format with substitutionCount greater then 6 , it is impossible to open it

### ISSUE THREAD

**Issue by AKZhuk** [epam/ketcher#3397]
**Actual behavior**
If add slightly different Atom Properties to the structure (see the screenshot below) and save it in .Ket format, then when opening this file, an error appears and the file does not open'

![](https://user-images.githubusercontent.com/139227567/272629971-c7c08269-45b5-40b5-853a-6a7db2d363e9.png)

**Expected behavior**
Saved file should opened without error "Cannot deserialize input JSON"

**Comment by urszula-gawlowska** [comment]
Verified on branch 3397-when-you-save-atom-in-ket-format-with-substitutioncount-greater-then-6-it-is-impossible-to-open-it - bug fixed 

https://github.com/epam/ketcher/assets/145990256/da125769-563b-4b06-9ee2-c34bd118809f
