### ISSUE TITLE
Button Labels

### ISSUE THREAD

**Issue by hoefkens** [epam/ketcher#342]
In certain cases under specific screen resolutions, aspect ratio, and browser conditions, the Ketcher tool automatically displays text labels for the button controls even though this should not be the case. Below is a screenshot captured . 

![image](https://user-images.githubusercontent.com/26791342/108904556-a5d71500-75ec-11eb-8813-61bb5ae0227e.png)

**Comment by AndreiMazol** [comment]
Dear @hoefkens ,

Please provide the following information:
- screen resolutions
- browser version
- use mode: as IFrame or injected as React component
- commit hash ( or confirm that the latest master is used)

Best regards,
Ketcher Team

**Comment by AndreiMazol** [comment]
Cannot reproduce.
cc: @hoefkens
