### ISSUE TITLE
Macro: Monomer does not move on first click and drug

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3420]
**Steps to Reproduce**
1. Add monomer to canvas
2. Select 'Rectangle selection tool'
3. Drug monomer to new position

**Actual behavior**
Monomer does not move. It needs to click and then drug to move monomer.

**Expected behavior**
Monomer moves without additional click.

**Comment by MartaWilliams** [comment]
Tested 

https://github.com/epam/ketcher/assets/82752700/245e7583-4032-4b33-a8df-3ffcf9a69a8b
