### ISSUE TITLE
[Macro] Unused attachment points labels overlaps

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3442]
**Steps to Reproduce**
1. Add two monomers linked by bond
2. Move it to specific position where attachment points labels overlaps(screenshot below)
3. Hover on monomer or bond with bond tool

**Actual behavior**
Attachment points labels overlaps
<img width="282" alt="image" src="https://github.com/epam/ketcher/assets/14859362/8cd8e072-d469-4633-a2dd-caa1705467f1">

**Expected behavior**
**Unused** attachment points labels placed next to circle of attachment points and don't overlaps. 
<img width="387" alt="image" src="https://github.com/epam/ketcher/assets/14859362/690a2528-5195-4362-b361-736b9b00b679">

**Comment by y-holik** [comment]
this issue is tested
https://github.com/epam/ketcher/issues/3596 bug created
