### ISSUE TITLE
Aromatic atom list is not recognized when loaded from SMARTS file

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#3455]
When Ketcher loads a SMARTS query with a list atoms in aromatic format (lowercase atom symbols, e.g. "c,n"), the list is not recognized properly and is interpreted as a custom query.

For example, the following query results in a molecule with custom query "c,n" instead of atom list with carbon and nitrogen.
`c1-[#6]=[#6]-[#6]=[#6]-[c,n]=1`

**Comment by vanoprenko** [comment]
Caused by https://github.com/epam/Indigo/issues/1332

**Comment by AlexeyGirin** [comment]
Moved to Indigo
