### ISSUE TITLE
Macro: Support Import/Export Mol v3000

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3457]
It needs to fix ui of saving and opening mol v3000 files form macromolecules.
<img width="1061" alt="image" src="https://github.com/epam/ketcher/assets/14859362/8b75a5f0-8fec-4191-b94f-dfc69feb8760">

Design should be similar to micromolecules mode. Convertation of mol v3000 to ket should be done by indigo api call.

**Comment by MartaWilliams** [comment]
Back to do: 
- it's possible to save the structure in  mol v3000 format
- it's NOT possible to open saved earlier file 
![image](https://github.com/epam/ketcher/assets/82752700/d5a2556c-27c0-490a-999c-a00be3d74b5e)
