### ISSUE TITLE
Macro: Snake bonds should be displayed from/to attachment point for R1 and R2

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3469]
**Steps to Reproduce**
1. Turn on Bond tool and Snake mode
2.  Add 3 monomers to canvas
3. Connect 1 monomer to 2
<img width="1501" alt="image" src="https://github.com/epam/ketcher/assets/14859362/48461c4d-aa78-4a36-8b59-5fc95d19cfbe">

4. Connect 3 monomer to 2
<img width="1498" alt="image" src="https://github.com/epam/ketcher/assets/14859362/c5277be4-572e-4d9b-8920-c30f988a9372">

**Actual behavior**
Both snake bonds connected to the left side of monomer

**Expected behavior**
Both snake bonds connected to the default position of attachment point used for this bond

**Comment by MartaWilliams** [comment]
Tested 
![image](https://github.com/epam/ketcher/assets/82752700/48c699a8-d79d-41ac-911c-9d26194a8377)

**Comment by MartaWilliams** [comment]
To clarify: 

If we connect monomers in a snake chain (when each of them has one or more attachment points), and we do it according to the instruction ( 1 to 2, and then 3 to 2) the problem does not occur 
![2023-11-20_13h09_00](https://github.com/epam/ketcher/assets/82752700/37634a7c-c09a-4973-9b0f-d8ac667c8bec)
![image](https://github.com/epam/ketcher/assets/82752700/4dd3e68d-aaab-4bbb-8b9a-82c62f2164be)

But if one of the monomers has only one attachment point and we connect them in a different way (1 to 2 and  2 to 3) then both snake bonds are connected to the left side of the monomer. 
![image](https://github.com/epam/ketcher/assets/82752700/21434913-40aa-4c6b-bc64-54fa25cb34a2)
