### ISSUE TITLE
Macro: Change RNA-preset configuration

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3475]
**Background**
Change RNA-preset configuration according to biological rules

**Requirements**
RNA preset = sugar + phosphate + base

- R1 of sugar (oriented left) should be connected with R2 (oriented right) of phosphate
- R3 of sugar (oriented bottom) should be connected with R1 (oriented top) of base
- R1 of phosphate should be oriented left 
- R2 of sugar should be oriented right

Preset preview which is displayed near the arrow while hovering on canvas (after one of the presets is selected) should be also changed according to mockup

![image](https://github.com/epam/ketcher/assets/143799055/fcb5a346-d186-4a1b-82de-9cc4a994d37f)

**Comment by urszula-gawlowska** [comment]
One bug found during testing PR
Steps to reproduce:
1. Add moen phosphate to the canvas 
2. Add 25R sugar to the canvas 
3. Add eaA base to the canvas
4. Select single bond
5. Connect moen phosphate with sugar
6. Conncet sugar with eaA base
Expected result:
Sugar and base should be connected by R3-R1 attachment points
Actual result:
Sugar and base is connected by R3-R2 attachment points

![moen_25r_eaA](https://github.com/epam/ketcher/assets/145990256/699860d7-c071-4d43-afc2-7f074dc121ca)
