### ISSUE TITLE
Macro: Preview for monomer does not disappear and prevents you from selecting menu in RNA Builder

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3489]
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Click RNA tab
3. Click on 'Sugar' in RNA Builder
4. Select any Sugar

**Actual behavior**
Preview for monomer does not disappear and prevents you from selecting menu in RNA Builder

**Expected behavior**
Preview for monomer disappears and allow you selecting menu in RNA Builder

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/0df2bf8e-427c-4743-a241-3e6fb19fdac5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.15.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)
Macromolecule ver. 0.1.0

**Comment by Zhirnoff** [comment]
Autotests written

**Comment by y-holik** [comment]
this issue is tested
