### ISSUE TITLE
Macro: Chem monomer name is not fitting into a shape 

### ISSUE THREAD

**Issue by MartaWilliams** [epam/ketcher#3494]
**Steps to Reproduce**

- Go to Macromolecules mode
- Click the CHEM tab
- Click on "Test-6-Ch"
- Add it to the canvas

**Current behavior**
The name of the chem monomers is too long and starts going out of shape. 

**Expected behavior**
Long names of Chem monomers should fit into the shape by moving text to next line (right under the first one)
![2023-10-24_12h29_09](https://github.com/epam/ketcher/assets/82752700/ec2f38da-2d41-4c5e-b78c-5ba8db99401b)

Task related: https://github.com/epam/ketcher/issues/2497

**Comment by Zhirnoff** [comment]
This bug is no longer reproduced.

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by ilya-asiyuk-epam** [comment]
This bug is not relevant. It is fixed in #3902 ticket
