### ISSUE TITLE
Macro: Is not possible to add RNA presets  into the Favourite library

### ISSUE THREAD

**Issue by MartaWilliams** [epam/ketcher#3495]
**Steps to Reproduce**

- Go to Macromolecules mode
- Click the RNA tab
- Click on Presets 
- Hover over any of the RNA presets structure 

**Actual behaviour**
There is no star on RNA presets structures allowing them to be add into Favorite library.

**Expected behavior**
Displaying a star for adding presets to favorites: A star for adding RNA presets to Favorite library shall appear in the upper left corner inside presets framework.

![image](https://github.com/epam/ketcher/assets/82752700/e50f44f4-9c13-47c4-9fe6-dbddf69ba5bf)
![image](https://github.com/epam/ketcher/assets/82752700/49ce3783-7bcc-43d8-8e62-be656afcdc3c)

Task related: https://github.com/epam/ketcher/issues/3041

**Comment by Zhirnoff** [comment]
Manual tests added to the table.
