### ISSUE TITLE
Macro: the "Library" inscription and the "Hide" button are at different height

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#3497]
**Steps to Reproduce**
1.	Launch "Ketcher" and go to the Macromolecules module
2.	Verify if the "Library" inscription and the "Hide" button in the upper right corner are at the same height

**Actual behavior**
The "Library" inscription and the "Hide" button are at different heights

**Expected behavior**
According to the layout design, the "Library" inscription and the "Hide" button should be at the same height

**Screenshots**
<img width="371" alt="image" src="https://github.com/epam/ketcher/assets/139227567/cbc83b6f-7e08-4d35-8e54-ec37eb5ad1c6">

<img width="462" alt="image" src="https://github.com/epam/ketcher/assets/139227567/b1704bfc-d6e1-4162-a905-cb1fdc934cb1">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (117.0.5938.152) x64

**Ketcher version** 0.1.0

**Comment by Zhirnoff** [comment]
Manual tests added to the automation table.
