### ISSUE TITLE
Macro: When switching from the Macromolecules module to the Molecules module an application crashes

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#3498]
**Steps to Reproduce**
1.	Launch "Ketcher" and go to the Macromolecules module
2.	Open the Console
3.	Inside the "RNA" section in the "Sugars" subsection, select any sugar
4.	Inside the "RNA" section in the "Bases" subsection, select any base
5.	Inside the "RNA" section in the "Phosphates" subsection, select any phosphate
6.	In the "RNA Builder" subsection, click on the "Add to Presets" button
7.	In the "Presets" subsection, click on this added preset
8.	Click on any empty place on the canvas
9.	Go to the Molecules module

**Actual behavior**
When switching from the Macromolecules module to the Molecules module an application crashes

**Expected behavior**
Switching from the Macromolecules module to the Molecules module should not crash application

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/e08d96fd-c79a-492a-93b9-fc4416957a0e

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (117.0.5938.152) x64

**Ketcher version** 0.1.0

**Comment by Zhirnoff** [comment]
Autotest added.
