### ISSUE TITLE
Query bond properties can't be saved in Daylight SMARTS and SMILES (Daylight and Extended) formats

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#35]
**Steps to reproduce**

1. Draw any structure, for example, using a chain tool.
![image](https://user-images.githubusercontent.com/7427808/92366889-667c4100-f0fe-11ea-9dac-b6db7859cf00.png)
2. Apply all possible Bond properites.
3. Click the Save As button. Choose the 'Daylight SMARTS' format
4. Open the saved file in Ketcher and compare two structures.

**Actual result**
![image](https://user-images.githubusercontent.com/7427808/92367101-a93e1900-f0fe-11ea-9747-ff1960bdf5d6.png)

Query bond properties are lost after opening the saved file.

**Expected result**

Query bond properties should be saved in SMARTS format and correctly represented in Ketcher.

Note:
The same problem is with Daylight SMILES and Extended SMILE.

**Comment by MagomedGasanov** [comment]
SMILES does not support query attributes. Needs to add warning message. Issue: https://github.com/epam/ketcher/issues/712
