### ISSUE TITLE
3d mol files appear as 2D in Miew

### ISSUE THREAD

**Issue by dondaley** [epam/ketcher#3501]
**Steps to Reproduce**
1. import 3D mol file'
2. Click on 3D view
3. View structure 

**Actual behavior**
3d mol files appear as 2D in Miew
**Expected behavior**
#D appeared with 3D mol file in previous versions

**Screenshots**
![image](https://github.com/epam/ketcher/assets/26578852/b3e61cfa-795b-4ad4-bcc6-185d7263866c)

![image](https://github.com/epam/ketcher/assets/26578852/a32779db-1c19-415a-877f-ab519862b54f)
<img width="677" alt="image" src="https://github.com/epam/ketcher/assets/26578852/0e67668d-ef16-4297-976f-
533b500f385f">

squashes file into 2D and changes cooridinates
![image](https://github.com/epam/ketcher/assets/26578852/e9993df2-7112-40e5-b420-9ac1e794b757)

and V3000 does not work

**Desktop (please complete the following information):**
 - OS: Macos 14.0
 - Browser safari
 - Version 17.0

**Ketcher version** [e.g. v2.4.2]. 
2.11.0

**Test case**

**Additional context**

**Comment by mikaukora** [comment]
Based on my testing this happens at https://github.com/epam/ketcher/commit/d4981dc5384a5221e86a02d72a86f6077156a34c for the first time.
The commit is included in release/2.18.

Steps to reproduce:
- Open structure library
- Select 3D Templates
- Select fullerene C60 and place it on canvas
- Select 3D viewer
- The structure is rendered flat (2d) instead of 3d

**Comment by mtreinik** [comment]
The pull request above fixes this issue. The function `rotateCoordAxisBy180Degrees` was missing `z` coordinate, thus flattening the molecule to a two-dimensional figure.

**Comment by NataliaLoginova** [comment]
@mtreinik thank you a lot for for fixing the issue #3501!

**Comment by NadezhdaPeskun** [comment]
Verified as fixed for CI of Ketcher 2.22.rc1.
[ketcher (31).zip](https://github.com/epam/ketcher/files/15294357/ketcher.31.zip)
