### ISSUE TITLE
Macro: Expand RNA builder when clicking on New Preset button

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#3505]
**Steps to Reproduce**
1. Open RNA tab
2. Click on 'Cancel' button
3. Collapse RNA builder
4. Click on New Preset button

**Actual behavior**
RNA builder stays collapsed

**Expected behavior**
RNA builder expands

**Screenshots**
![image](https://github.com/epam/ketcher/assets/128700628/1d08c924-d7c3-4a60-b371-ff0a0e0549d0)

**Comment by Zhirnoff** [comment]
Manual test added to automation table for Macromolecules

**Comment by AnastasiyaPiatrovaKlu** [comment]
Tested.


https://github.com/epam/ketcher/assets/72072840/5f269684-6f4a-4da9-8f32-cb57a98c4110
