### ISSUE TITLE
Macro: RNA tab view while opening the RNA tab

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#3509]
Once RNA tab is opened by user for the first time, the RNA builder should be presented in a collapsed empty state and Presets shouldn't be blocked from utilizing 
![image](https://github.com/epam/ketcher/assets/128700628/27d78f5d-2060-4df8-9c36-b258ad63a77b)

**Comment by Zhirnoff** [comment]
Autotest written

**Comment by AnastasiyaPiatrovaKlu** [comment]
Tested.

https://github.com/epam/ketcher/assets/72072840/ebe2367e-0b1d-441f-bfda-f87ac8605587
