### ISSUE TITLE
Macro: Wrong usage of AP when establishing a bond between monomers (R1 and R2) -> (R2)

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#3525]
**Steps to Reproduce**
1. Add to canvas 2 monomers. One of them has R1 and R2, the second one has only R2
2. Drug the bond from the first one (with R1 and R2) to the second one.

**Actual behavior**
A bond is established between R2 and R2

**Expected behavior**
A bond is established between R1 and R2

**Screenshots**
![image](https://github.com/epam/ketcher/assets/128700628/f439526c-b0ce-4be7-b1cd-8e4b4fa7833e)

**Comment by MartaWilliams** [comment]
Tested 
![image](https://github.com/epam/ketcher/assets/82752700/3e3a9dc0-cb62-4457-bb19-ab3d3c708bbd)
