### ISSUE TITLE
Displaying side chain connections in snake-like mode

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3532]
**Background**

There are two major types of monomer sequences supported implicitly by Ketcher:
- **Backbone** chains forming the core of the macromolecule. Neighbor monomers in these chains are always connected via a bond from R2 attachment points **(APs)** of one monomer to R1 of another.
- **Side** chains -- "secondary" sequences aside the backbone chains. Side chains are connected to backbone chains via attachment points other than R2-R1 (e.g. R3-R3, R3-R4, R1-R1).

Bonds forming the backbone chain are **backbone connections**, bonds in side chains -- **side chain connections**.
Specific case of side chain connection is when the connection is established directly between two backbone monomers (e.g. connecting them via R3/R4), i.e. there are no monomers in the side chain.  In scope of this task we consider this type of side chain connection only. 

**Requirements**

Currently side-chain connection in snake (left-to-right) mode is displayed as a straight line connecting two monomers, with no respect to other monomers and bonds. This results in messy visualization and suboptimal user experience.  

Instead, side chain connections should be displayed as rounded elbow connectors aligned with existing monomers and other bonds (see wireframes below). The following rules should be applied:
1. If two monomers linked by side-chain connection are positioned in the same row of monomers, the connection should be drawn horizontally above these monomers.
2. If two side-chain connected monomers are from different rows, the connection curve should go from topmost monomer upside down and left to right (or right to left) using free space between monomers. The shortest path should be used when possible.
3. If R1-R1 connection is established between two monomers occupying first positions in different backbone chains, the connection should be drawn on the left from these monomers.
4. In case of R2-R2 bond connecting the last monomers of the chains the connection should be drawn on the right from these monomers. 
5. Side chain connections may intersect backbone and other side chain connections but should not overlap. If more than one  side connection is drawn horizontally between two monomer rows, they should be shifted vertically against each other. 
6. Similarly to point 5, vertically oriented connections should not overlap. If multiple connections run vertically in the space between two monomers, they should be shifted horizontally relative to each other.
7. Specific case for RNA monomers: the bond between R1 of base and R3 of sugar should not be considered side chain connection and should be displayed as a straight line (usual way). All other bonds connected to the base are considered side chain connections. 
8. Attachment points positions:
- R1 is always oriented left, R2 is always oriented right (excl. base monomers)
- R3, R4, ... APs are oriented towards bond formation 
- All the base APs are oriented towards bond formation. 

**Alternatives**
The same logic of connections is applied for CHEMs, unknown monomers and unsplit nucleotides.

**UI**
r1-r1
![image](https://github.com/epam/ketcher/assets/141816460/a4a8a857-768b-43c6-a540-74eef8161be3)

r3-r2
![image](https://github.com/epam/ketcher/assets/141816460/fd9e2681-981c-4031-8431-2184c83a46fb)

r2-r2
![image](https://github.com/epam/ketcher/assets/141816460/29afae3d-58c6-4a92-8668-efd1358d4046)

r1-r3
![image](https://github.com/epam/ketcher/assets/141816460/6a4fa235-d85c-46b4-8b76-a609fe73b639)

r3-r3
![image](https://github.com/epam/ketcher/assets/141816460/6abe5bbd-182f-4d6b-b221-bbaa1aef1dfe)

![image](https://github.com/epam/ketcher/assets/141816460/51c47bd9-d4bd-4797-98d2-dc1e70771bb9)

RNA
![image](https://github.com/epam/ketcher/assets/141816460/af0f67e8-93d9-43d9-89e1-f89fc5f98765)

**Comment by AlexeyGirin** [comment]
Question to @olganaz 

1. Multiple horizontal bonds are evenly distributed throughout the space between the chains. Is there the same logic for vertical bonds?
2. How are CHEMs displayed? Same as regular monomers?
3. How are unknown monomers displayed? Same as regular monomers?
4. For unknown monomers, connection with R4 are acceptable. Is the logic for them the same as for R3?

**Comment by olganaz** [comment]
1. Yes, the same logic for horizontal bonds, as for vertical. 
2. CHEMs, unknown monomers and unsplit nucleotides are displayed in the same way as peptides. The same logic of connections is applied.

**Comment by Zhirnoff** [comment]
Tested. We have plenty bugs (see attached bugs to the ticket)
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]

**Comment by AlexeyGirin** [comment]
p.8 is not implemented and will be moved to dedicated task by @rrodionov91
