### ISSUE TITLE
Macro: default presets do not appear back after cleaning search field

### ISSUE THREAD

**Issue by kavalapka** [epam/ketcher#3537]
**Steps to Reproduce**
1. Open macro for the first time. Go to 'Peptides'
2. Type smth in 'Search by name' field
3. Go to RNA tab
4. See nothing in Presets tab
5. Remove words from 'Search by name' field

**Actual behavior**
Still nothing in Presets
<img width="207" alt="image" src="https://github.com/epam/ketcher/assets/16915498/edea4a39-c449-4f5b-a739-c5e71203bf40">

**Expected behavior**
Default Presets present on tab
<img width="199" alt="image" src="https://github.com/epam/ketcher/assets/16915498/f8791467-fc98-4043-b9a7-bbb18a9f838f">

**Comment by Zhirnoff** [comment]
Manual tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested.
