### ISSUE TITLE
Macro: new created preset does not draw on canvas

### ISSUE THREAD

**Issue by kavalapka** [epam/ketcher#3538]
**Steps to Reproduce**
1. Go to 'RNA builder'
2. Create new preset. Save
3. Click to canvas to draw preset

**Actual behavior**
Draw last selected monomer
<img width="360" alt="image" src="https://github.com/epam/ketcher/assets/16915498/4e58bb94-3122-444e-98b9-dc09fc304427">

**Expected behavior**
Draw selected preset
<img width="372" alt="image" src="https://github.com/epam/ketcher/assets/16915498/32410ead-75af-4baf-92b2-a49fd62c1c64">

**Comment by Zhirnoff** [comment]
Manual tests added to the automation table.

**Comment by Zhirnoff** [comment]
Working not properly. We have open bug https://github.com/epam/ketcher/issues/3615

https://github.com/epam/ketcher/assets/62464241/ad6cf642-0260-4ea8-87e7-efae50f0a745
