### ISSUE TITLE
Macro: When pull bond away from monomer and press 'Escape', bond remains on canvas

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3539]
**Steps to Reproduce**
1. Switch to Macromolecule mode
2. Add any monomer on canvas
3. Select bond tool and start pull bond from monomer to any direction
4. Press 'Escape' button

**Actual behavior**
When pull bond away from monomer and press 'Escape', bond remains on canvas

**Expected behavior**
When pull bond away from monomer and press 'Escape', bond disappears

**Screenshots**
.

https://github.com/epam/ketcher/assets/62464241/ffe192fd-e419-405e-a9c0-01fa4d3073c5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.15.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Zhirnoff** [comment]
Autotest written

**Comment by AnastasiyaPiatrovaKlu** [comment]
Tested.

https://github.com/epam/ketcher/assets/72072840/d442eb02-910c-40b2-a591-17f8e60911c7
