### ISSUE TITLE
After hiding the Library panel, a residual strip remains, concealing content on the canvas

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3542]
**Steps to Reproduce**
1. Switch to Macromolecule mode
2. Add any monomer on canvas
3. Press 'Hide' button to hide Library panel
4. Select monomer and move to place where was Library panel

**Actual behavior**
After hiding the Library panel, a residual strip remains, concealing content on the canvas

**Expected behavior**
After the panel is hidden, structures can be placed in its place.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/865f09ec-6a40-4954-beb5-38c6ac868adf

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.15.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by urszula-gawlowska** [comment]
Tested locally on the branch 3542-after-hiding-the-library-panel-a-residual-strip-remains-concealing-content-on-the-canvas
https://github.com/epam/ketcher/assets/145990256/e83aa7c3-10e4-4500-89f3-cd6ce4ab736e

**Comment by MartaWilliams** [comment]
Tested 
![2023-11-20_12h26_53](https://github.com/epam/ketcher/assets/82752700/c0e6c3de-f098-4147-b9e3-cd03fe95c457)
![2023-11-20_12h27_07](https://github.com/epam/ketcher/assets/82752700/b48897bd-11d1-426d-ade1-fcf89ff9538c)
