### ISSUE TITLE
Macro: N- C-ends /5' - 3' - ends display in peptide /RNA chains

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3545]
**Background**
It is useful for chemists and biologists to see the beginning and the end of the chain. For peptide chain usually N/C designations are used, for RNA chains - 5'/3'. 
Ketcher will only display the beginnings of the chains so as not to overload the visual presentation.
"N- end" of the peptide chain should be marked.
"5' - end" of the RNA chain should be marked. 

**Requirements**

In addition to current rules for numbering monomers [#3222](https://github.com/epam/ketcher/issues/3222):
1. For the peptide chain (made from at list two monomers), the first monomer (numbered 1) should be marked as the N-terminus (Symbol 'N' at the left side of monomer - near the R1 AP).
2. For RNA chain, the sugar, connected to the base numbered 1, should be marked as 5' (Mark "5' " at the left side of monomer - near the R1 AP).
3. Single nucleotide (sugar+base+phosphate) should not be marked with 5'
4. If any monomer is connected to single nucleotide (for example, phosphate or CHEM), then this nucleotide should be marked with 5'. 
5. For mixed chains each monomer, numbered 1, should be marked as N for a peptide monomer, or as 5' for RNA according to the rules described in 1-3. 

**Screenshots**

![for development](https://github.com/epam/ketcher/assets/141816460/6196c137-90ae-499d-a66d-a732cb0b55c6)

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/ff4a01a9-2700-4e78-9954-3b55400405ad)

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/b1147515-0c87-41f8-9b3c-41ba0537b00f)

**Comment by Zhirnoff** [comment]
Tests added to automation table.

**Comment by Zhirnoff** [comment]
Pretested. No comments.

**Comment by Zhirnoff** [comment]
Tested.
