### ISSUE TITLE
Implicit hydrogens for aromatised structures containing Sulphur

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#3554]
**Steps to Reproduce**
1. Load structure `S1C=CN=C1`
2. Click aromatize

**Actual behavior**
Additional implicit hydrogen appears for Sulfur
![image](https://github.com/epam/ketcher/assets/7427808/98ea1721-90d1-49ea-956e-dced2f2cedd9)

**Expected behavior**
No implicit hydrogen should appear for Sulfur inside aromatized rings

**Comment by y-holik** [comment]
tested and approved
