### ISSUE TITLE
[Macro] Change the connection of monomers inside preset (phosphate on the right side)

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3558]
**Background**
A task describes the rules for monomer connection inside preset (HELM-like style, phosphate - on the right).
RNA preset = sugar+base+phosphate

**Requirements**

- R2 of sugar connected with R1 of phosphate
- R3 of sugar connected with R1 of base
- connection between presets is established between phosphate R2 group of the first preset  and sugar R1 group of the next preset. 
![image](https://github.com/epam/ketcher/assets/143799055/b6f4095a-8e80-4bbe-a179-667e3adf420e)

**Comment by urszula-gawlowska** [comment]
Tested locally on master branch [x] 
![preset-attachment-points](https://github.com/epam/ketcher/assets/145990256/4190a68e-ce79-4d1e-8a40-738cc3be645c)
![two_presets_connected](https://github.com/epam/ketcher/assets/145990256/e271172e-2365-4186-bd66-3f590985de88)

**Comment by MartaWilliams** [comment]
Tested 
![image](https://github.com/epam/ketcher/assets/82752700/65180f34-33e5-497f-9913-ee51dc8d226c)
![image](https://github.com/epam/ketcher/assets/82752700/3ececc21-4241-4d5f-9f09-d57655290bd8)
