### ISSUE TITLE
Macro: Can't delete preset from Presets section

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3561]
**Steps to Reproduce**
1. Switch to Macromolecule mode
2. Select RNA tab
3. Build custom preset in RNA Builder and add it to Presets section
4. Right-click (or click on three dots) on created presets and select 'Delete preset'

**Actual behavior**
Preset is not deleted and preserve in Presets section

**Expected behavior**
Preset is deleted

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/23c6f5b1-e350-4272-925a-a868150ee50d

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.15.0-rc.4](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Zhirnoff** [comment]
Manual tests added to the automation table.

**Comment by AlexeyGirin** [comment]
Verified.
