### ISSUE TITLE
Macro: AP are shown after closing modal

### ISSUE THREAD

**Issue by OlgaMazurina** [epam/ketcher#3582]
**Steps to Reproduce**
1. Add 2 monomers to canvas
2. Connect 1 monomer to 2
3. Cancel bond creation  

**Actual behavior**
AP are drawn on the second monomer

**Expected behavior**
AP should be deleted

**Screenshots**

<img width="443" alt="Снимок экрана 2023-11-16 в 12 51 02" src="https://github.com/epam/ketcher/assets/70894460/a4c4832c-e862-4d78-8a37-25ebbe91b7f7">

**Comment by Zhirnoff** [comment]
Manual tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested.
