### ISSUE TITLE
Macro: selected AP is duplicated while drawing the bond

### ISSUE THREAD

**Issue by OlgaMazurina** [epam/ketcher#3583]
**Steps to Reproduce**
1. Add monomer to canvas
2. Select AP and start to draw bond around the monomer with opened console

https://github.com/epam/ketcher/assets/70894460/d4aed55b-db3f-4f4e-9e09-6e0077d7edd4

**Actual behavior**
AP shouldn't be duplicated

**Comment by Zhirnoff** [comment]
Manual tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested.
