### ISSUE TITLE
Macro: APs are redrawn incorrectly after opening the modal window

### ISSUE THREAD

**Issue by OlgaMazurina** [epam/ketcher#3585]
**Steps to Reproduce**
1. Add 2 monomers to canvas
2. Connect 1st monomer from center to AP on the 2nd monomer

**Actual behavior**
When Modal Window is opened first monomer has wrong APs

**Screenshots**
<img width="216" alt="Снимок экрана 2023-11-16 в 18 35 42" src="https://github.com/epam/ketcher/assets/70894460/72bc7f1e-0474-483d-911b-d586497ea646">

https://github.com/epam/ketcher/assets/70894460/a2dce10a-2386-4b56-8bc4-15ef8ecce668

**Comment by Zhirnoff** [comment]
Manual tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested.

**Comment by Zhirnoff** [comment]
Automated.
