### ISSUE TITLE
Macro: It's imposible to save and then open file in Mol v3000 format 

### ISSUE THREAD

**Issue by MartaWilliams** [epam/ketcher#3599]
**Steps to Reproduce**
1. Open Ketcher Macromolecules.
2. Create chain structure of peptides on the canvas
3. Click the snake mode button
4. Save structure in a Mol v3000 format 
5. Clear canvas 
6. Open previously saved file 

**Actual behaviour**
A pop-up with a Convert Error appears. 

**Expected behaviour**
You can open and add to the canvas saved structure

**Screenshots**
![image](https://github.com/epam/ketcher/assets/82752700/6b357b4d-8363-4272-a8c8-e989ec22f28b)
![image](https://github.com/epam/ketcher/assets/82752700/bfbbfd34-cd1b-4ffd-a535-87929a7d12a9)
![image](https://github.com/epam/ketcher/assets/82752700/f6399917-b08b-45ec-92ef-4fbe2bb239b7)

**Test files**
[Test-files.zip](https://github.com/epam/ketcher/files/13425994/Test-files.zip)

**Test case**
https://github.com/epam/ketcher/issues/3457

**Comment by rrodionov91** [comment]
Bug on Indigo side. Ticket created: https://github.com/epam/Indigo/issues/1414

**Comment by Zhirnoff** [comment]
Pre-tested. Bug is reproduced.

https://github.com/epam/ketcher/assets/62464241/a9a437af-111b-4b9e-8f34-00e34ff1c663

The file is saved in the new version: 
[ketcher (18).zip](https://github.com/epam/ketcher/files/13660912/ketcher.18.zip)

**Comment by rrodionov91** [comment]
Done. @Zhirnoff please use newly created structures instead of files attached to ticket because files were saving incorrectly.

**Comment by Zhirnoff** [comment]
Tested.

**Comment by AlexeyGirin** [comment]
Fixed.
