### ISSUE TITLE
Macro: attachment points aren't disappearing in snake viewed chain of peptides when hovering them multiple times

### ISSUE THREAD

**Issue by y-holik** [epam/ketcher#3601]
**Steps to Reproduce**
1. Switch to macromolecules
2. Place multiple peptides on canvas and bond them
3. Click snake view 
4. Randomly hover mouse over peptide chain (bond tool must be selected)

**Actual behavior**
Attachment points are always shown for random peptides

**Expected behavior**
Attachment points should disappear if monomer is not hovered

**Screenshots**
=
<img width="1010" alt="Screenshot 2023-11-21 at 4 33 25 PM" src="https://github.com/epam/ketcher/assets/139877378/2641cb59-5b39-4592-b03c-8c5146f73f85">

=

**Comment by Zhirnoff** [comment]
Test added to the table.

**Comment by AlexeyGirin** [comment]
Verified.
