### ISSUE TITLE
Macro: preview window of macro structure changes size in micro mode

### ISSUE THREAD

**Issue by y-holik** [epam/ketcher#3603]
**Steps to Reproduce**
1. Switch to macromolecules
2. Place multiple peptides on canvas and bond them
3. Hit snake mode button
4. Switch to micro molecules and hover over peptide

**Actual behavior**
Preview window shrinks

**Expected behavior**
Preview window doesn't change its size after switching modes

**Screenshots**
<img width="754" alt="Screenshot 2023-11-21 at 7 30 06 PM" src="https://github.com/epam/ketcher/assets/139877378/f57457f1-8545-4fc0-a8c9-d1065ff47657">

**Comment by Zhirnoff** [comment]
Test added to automation table.
