### ISSUE TITLE
Macro: preview window of micro structure shows pieces of macro structures

### ISSUE THREAD

**Issue by y-holik** [epam/ketcher#3604]
**Steps to Reproduce**
1. Switch to macromolecules
2. Place multiple monomers on canvas and bond them
3. Switch to micro mode and place Benzene ring on canvas
4. Select bond tool and bond benzene ring to macro structure
5. Switch back to macro mode and hover mouse over micro structure to get preview window appeared

**Actual behavior**
preview window of micro structure shows pieces of macro structures

**Expected behavior**
preview window of micro structures in macro mode should only show preview of micro structure

**Screenshots**

https://github.com/epam/ketcher/assets/139877378/b03caaed-b98f-4752-9ab2-0693ba42b8d0

**Comment by OlZhur** [comment]
After fixing need to check the bug https://github.com/epam/ketcher/issues/3611
