### ISSUE TITLE
Macro: RNA preset icons are changed after saving and importing file as .mol

### ISSUE THREAD

**Issue by y-holik** [epam/ketcher#3609]
**Steps to Reproduce**
1. Switch to macromolecules mode
2. Place RNA preset on canvas
<img width="270" alt="Screenshot 2023-11-22 at 2 11 07 PM" src="https://github.com/epam/ketcher/assets/139877378/a230bc25-d0be-469e-8026-8cb983a82f87">

3. Save file as .mol
4. Clear canvas and import saved .mol file

**Actual behavior**
Sugar and Phosphate icons are changed and look like Base

**Expected behavior**
Icons doesn't change after importing files

**Screenshots**
<img width="444" alt="Screenshot 2023-11-22 at 2 13 56 PM" src="https://github.com/epam/ketcher/assets/139877378/af123bf7-9826-45ce-ae16-cbbe26376cca">

**Comment by rrodionov91** [comment]
Will be fixed on Indigo side with issue https://github.com/epam/ketcher/issues/3599
Indigo ticket: https://github.com/epam/Indigo/issues/1414

**Comment by Zhirnoff** [comment]
Pre-tested. After save file does not open.


https://github.com/epam/ketcher/assets/62464241/9fef72c4-9ade-4f81-9e68-d81e78814d87

**Comment by Zhirnoff** [comment]
Tested.

**Comment by AlexeyGirin** [comment]
Fixed,

**Comment by Zhirnoff** [comment]
Automated.
