### ISSUE TITLE
Macro: after switching from micro to macro mode dragging one monomer makes other monomer and its AP move

### ISSUE THREAD

**Issue by y-holik** [epam/ketcher#3611]
**Steps to Reproduce**
1. Switch to Macromolecules mode
2. Add multiple peptides on canvas and bond them
3. Click Snake mode and move some peptides up/down
4. Switch to Micromolecules mode and add a couple of Benzene rings to canvas
5. Bond Benzene rings to monomers
6. Switch to Macromolecules mode and back to Micromolecules mode
7. Move some monomers

**Actual behavior**
Dragging one monomer and its AP makes other monomer and its AP move

**Expected behavior**
Only selected structure moves

**Screenshots**

https://github.com/epam/ketcher/assets/139877378/cf166bb9-99b4-4e85-83ac-a3964cab110a

**Comment by OlZhur** [comment]
Related to fix for https://github.com/epam/ketcher/issues/3604
