### ISSUE TITLE
Macro: undo/redo does not toggle snake mode

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3633]
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Add peptide chain on canvas
3. Click on 'Snake mode' button on left tool panel
4. Click on 'Undo' button on left tool panel

**Actual behavior**
Chain position changed on previous one(before snake layout), however snake mode still turned on and bonds drawn as snake ones.

**Expected behavior**
Snake mode turned off and bonds drawn as straight lines.

**Comment by Zhirnoff** [comment]
Autotests added to the table.
