### ISSUE TITLE
Macro: Misalignment of monomers when imposing on top of each other

### ISSUE THREAD

**Issue by chgayane** [epam/ketcher#3635]
Steps to reproduce:

1. Select two monomers that need to be imposed on top of each other.
2. Position the first monomer above the second one.
3. Use the bond tool to aim for the attachment points of the underlying monomer.
4. Observe the resulting misalignment and scattering of the attachment points.

![MicrosoftTeams-image](https://github.com/epam/ketcher/assets/72468284/b993145e-9c67-483c-a072-46cf6c762035)

Actual behavior:
The attachment points of the underlying monomer become scattered, resulting in distorted monomers and misalignment.

Expected behavior:
The attachment points should remain intact, and the monomers should align correctly without scattering or distortion.

**Comment by Zhirnoff** [comment]
Autotest added to the table.
