### ISSUE TITLE
Macro: Displaying unmodified nucleotide chains in sequence representation

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3648]
**Background**
Representation of RNA-chains in a way of letter sequence. 
This task covers representation of **unmodified RNA** (created on canvas from **standard presets** or imported from file)
Representation of modified nucleotides will be covered by another issue
Nucleotide - sugar+base+phosphate, connected by the rules, defined in preset. 
Nucleoside - sugar+base, connected by the bond between R3 AP of sugar and R1 AP of base. 

**Requirements**

1. Dropdown for the button "snake" should be added. Available options:
    - Flex  (by default)
    - Snake 
    - Sequence (See mockups)
2. In sequence mode RNA fragment should be displayed as a sequence of letters, each letter corresponds to the natural analog of base that is a part of standard nucleotide. 
3. When two nucleotides are connected through R2-R1 bonds (with the bond formed between Phosphate R2 AP of the first nucleotide and the sugar R1 AP of the following nucleotide) these bonds are not visually represented. Instead, the two nucleotides are depicted as symbols that come together to form a word.  
4. All other bonds except R2-R1 should be displayed as straight line connecting two monomers.  
5. The last nucleotide in sequence mode is considered to lack a phosphate. The last nucleotide=nucleoside.
6. All the phosphates that are not part of nucleotides are displayed as 'p' symbol (including the last phosphate, which is connected to the last nucleoside). 
Image is given for better understanding:
![image](https://github.com/epam/ketcher/assets/143799055/32047a36-6f8d-43e4-9c4d-63928f2ec0a9)
7. Sequence is arranged in rows of text, the length of the row is 30 nucleotides.
8. In case of single chain, the position of the first symbol in sequence should be the same as position of the first monomer in flex/snake mode.
   - after switching from flex/snake mode to sequence visual frame should be moved to make the sequence visible. Sequence should be aligned in a frame in the upper-left corner with the 10% indent form the edge. 
10. In case of multiple chains the first chain is defined by the top left first monomer on canvas. The position of the first monomer of the first chain defines the position of the first symbol in sequence. Each new chain starts from the next row.
11. The sequence of letters should be divided into tens.
12. Nucleotide number is displayed only for every tenth symbol (if it is a nucleotide) and for the last nucleotide in a chain.
     - if the tenth symbol is 'p' or '@' then the number of the last nucleotide before this symbol is displayed.   
13. While hovering on a letter its number should be displayed. 

Sequence layout should not change the layout in flex/snake modes. 

**Alternatives**
If one fragment contains at least one modified RNA monomer ( Modified phosphate - any phosphate except 'P', modified sugar - any sugar except 'R', Modified base - any base except 'A', 'C', 'G', 'T', 'U'), then  all monomers from the fragment remain displayed as pictograms with all the bonds connecting them to each other.
In case of Peptide or CHEM monomers system should display them as '@', R2-R1 (R1-R2) bonds are not displayed, all other bonds are displayed as straight lines.  
Structures from micro-mode should be left on canvas where they are displayed as '@' symbol. 

**UX**
Icon for sequence view:
![image](https://github.com/epam/ketcher/assets/143799055/d88a7bd9-5a39-4e25-94e3-b96fcdf2780f)
Notation example (ignore nucleotide preview)
![image](https://github.com/epam/ketcher/assets/143799055/b6b65030-2481-4888-8822-1ba749e349ab)

**Comment by Andrey-Antonov** [comment]
![only unmodified nucl](https://github.com/epam/ketcher/assets/141816460/a60d5abe-44ae-44be-90ba-72a2249e12f6)

**Comment by Andrey-Antonov** [comment]
![Uploading only unmodified nucl.png…]()

**Comment by Andrey-Antonov** [comment]
![only unmodified nucl](https://github.com/epam/ketcher/assets/141816460/6b5e8786-e38c-43fa-9a13-4698b39959ea)

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/dc9192a5-4bcd-4139-9946-c5760aa0915f)
an icon for sequence mode (letter A)
(flex mode icon still under consideration)

**Comment by Andrey-Antonov** [comment]
![image](https://github.com/epam/ketcher/assets/141816460/978dd24b-252a-49f0-9277-913c3623d06f)

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested.
