### ISSUE TITLE
Macro: Different coordinate systems are used in Micro and Macro mode

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3651]
**Steps to Reproduce**
At the moment, coordinate systems are done differently in micro and macro mode. This results in structures being rotated by 180 degrees, when exporting to other molecule sketcher tools or sent to Indigo.

**Actual behavior**
The structure is rotated by 180 degrees, when exporting to other tools and when sending to Indigo (can be checked with, for example, `generateImage` API call)

**Expected behavior**
When pasting to other tools and sending to Indigo a structure is shown as it is drawn in Ketcher

**Additional context**
![image](https://github.com/epam/ketcher/assets/41272128/f597d3b4-23b1-47c5-bd41-d4868d6ebea4)

**Comment by Zhirnoff** [comment]
Tested.
