### ISSUE TITLE
Macro: Monomer colors and preview do not match library colors and preview after importing a file

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3668]
**Steps to Reproduce**
1. Switch to Macro mode
2. Open file [peptide_Bzl.zip](https://github.com/epam/ketcher/files/13602282/peptide_Bzl.zip)

**Actual behavior**
Monomer colors and preview do not match library colors and preview after opening file

**Expected behavior**
Monomer colors and preview match library colors and preview after opening file

**Screenshots**

![2023-12-07_19h18_18](https://github.com/epam/ketcher/assets/62464241/0d21b37d-ed3a-4e01-a391-d82aae591bd2)

![2023-12-07_19h23_49](https://github.com/epam/ketcher/assets/62464241/22c6b3b8-ef43-4a16-88a5-16da4d658997)
![2023-12-07_19h23_56](https://github.com/epam/ketcher/assets/62464241/410b00ae-0b6e-4437-a438-c7cfee363104)
![2023-12-07_19h24_06](https://github.com/epam/ketcher/assets/62464241/579da3c5-a950-4407-ae4e-cbc60a0ea30c)
![2023-12-07_19h24_13](https://github.com/epam/ketcher/assets/62464241/af5f92c6-a2dd-4a64-8dce-25023ada5c26)
![2023-12-07_19h24_26](https://github.com/epam/ketcher/assets/62464241/f871aaf1-2ea3-460f-aeeb-3c9d6e42c041)
![2023-12-07_19h24_32](https://github.com/epam/ketcher/assets/62464241/9dfd7f81-0572-4cdd-8ad5-b57999223baa)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.17.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by rrodionov91** [comment]
Fixed in indigo 1.17.0-rc.3
Please test with newly created files here https://polymer.test.lifescience.opensource.epam.com/KetcherDemoSA/master/index.html

**Comment by Zhirnoff** [comment]
Tested. No comments.
