### ISSUE TITLE
Allow select simple object by several points in selection area

### ISSUE THREAD

**Issue by ensemenova** [epam/ketcher#367]
**Steps to reproduce:**
1. Create different simple object
2. Try to select them with selection tool

**Current behaviour:**
They will be selected only when p0 point  will turn into selection
**Expected Behavior:**
When at least any 3 points turns into selection from rectangle or ellipse  it should be selected. For line any of it's point.

**Comment by Svetlana-Asinovskaia** [comment]
Issue is verified and closed.
