### ISSUE TITLE
Implement add/remove explicit hydrogens

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#3685]
**Background**
Need to convert all implicit hydrogens to explicit (and back)

**Solution**
* Create a button (after Calculate Values) 
* Label: "Add/Remove explicit hydrogens"
* Icon: "H" (UX TODO) 
![Hide hydrogens](https://github.com/epam/ketcher/assets/141816460/cf74462e-3701-4186-8c06-b0924472b68b)

* The backend function `convert_explicit_hydrogens(struct, auto)` should be called to add/remove hydrogens (TODO link to Indigo ticket)

**Comment by AlexeyGirin** [comment]
Temporary solution - execute Layout function to make layout perfect (currently - all H's has the same coordinates, so it looks bad)
