### ISSUE TITLE
Support pasting structures copied from ChemDraw OLE objects

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#3689]
**Background**
Chemical structures are often embedded into MS Office applications using ChemDraw OLE objects. In order to view and edit these structures in Ketcher users need to be able to copy a structure from ChemDraw OLE object to clipboard and paste it to Ketcher. 

**Solution**
When copying to clipboard is applied to a ChemDraw OLE object, it stores underlying chemical structure in 'Native' clipboard item in CDX (binary) format. Structure/CDX content starts with a 8-byte header:
`"VjCD0100" (56 6A 43 44 30 31 30 30)`

When user tries to paste clipboard content into Ketcher, the following algorithm should be applied:  
1. Check if 'Native' item is available in the clipboard and its content includes CDX header. 
2. If CDX content is detected, extract it from the item (***How to find the end of CDX is TBC***)
3. Convert resulting CDX content into structure and display it on canvas using regular approach for pasting CDX data from clipboard.

**Comment by AlexeyGirin** [comment]
Stopped for a while since not clear how to implement it

**Comment by vanoprenko** [comment]
It appeared that browser, due to its security limitations (?) doesn't allow reading binary data with CDX from the clipboard. Alternative options are:
- develop a desktop app that would monitor clipboard and repack CDX data into another field accessible from browser
- develop a desktop app that would extract and save on disk all CDX drawings (in batch mode)
- introduce a pptx browsing UI in Ketcher that would allow extracting CDX objects from pptx and adding them to canvas (i.e. avoid dealing with clipboard
Decided to proceed with the last option. Replaced with https://github.com/epam/ketcher/issues/3914

**Comment by vanoprenko** [comment]
Won't do
