### ISSUE TITLE
Calculated Values: does not work on simple part of structure that contains query features

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#369]
**Affected Versions**: Standalone

**Steps to Reproduce:**

1. Draw a structure 
2. Add any Query property or Query Bond.
2.  Select the part of structure without Query property/Query Bond.
3.  Click the 'Calculated Values' button.
4.  Verify data in the opened window.

**Expected result**: Calculated result on selected part

**Actual result**: Cannot calculate properties for structures with query features

![image](https://user-images.githubusercontent.com/79926367/109985315-ade23380-7d15-11eb-8741-3ff0b595e4e6.png)

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/344

**Comment by AndreiMazol** [comment]
Fixed in release/2.2

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.2 Issue is closed as fixed
