### ISSUE TITLE
Macro: Ket file does not include atom numbers associated with the leaving groups after saving

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3691]
**Steps to Reproduce**
1. Switch to Macro mode
2. Add any monomer on canvas
3. Save structure in Ket format.
4. Open saved Ket file and inspect the content of 'attachmentPoints'->'leavingGroup'->'atoms'

**Actual behavior**
When opening the Ket file, leaving groups information not correctly represented.
Leaving group atom numbers are missing.

![2023-12-12_23h02_44](https://github.com/epam/ketcher/assets/62464241/efc9e31a-51dd-481b-a2dc-1bf11292e6e4)

Also r-groups (rg-label) are indicated in the 'atoms' block
![2023-12-13_14h24_53](https://github.com/epam/ketcher/assets/62464241/3884940a-9825-467a-8ccd-2e658c244d9c)

**Expected behavior**
The Ket file should accurately represent leaving groups. 
The leaving group atom should be specified.

![2023-12-12_23h02_24](https://github.com/epam/ketcher/assets/62464241/e74745d7-96ff-4043-a42f-a4efc4180478)

In the 'atoms' block, all r-groups should be replaced with H or O atoms

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.17.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Zhirnoff** [comment]
Manual and autotest added

**Comment by AlexeyGirin** [comment]
Verified.
