### ISSUE TITLE
Macro: When loading Mol V3000, leaving groups are not displayed correctly

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3694]
**Steps to Reproduce**
1. Switch to Macro mode
2. Open file [acd-monomers.zip](https://github.com/epam/ketcher/files/13654332/acd-monomers.zip)
3. Hover over 'C' monomer

**Actual behavior**
Leaving groups are not displayed correctly in the preview

![2023-12-13_02h57_43](https://github.com/epam/ketcher/assets/62464241/e6832f87-0fe3-477f-bce2-20f7fa7a0328)

**Expected behavior**

![2023-12-13_03h03_41](https://github.com/epam/ketcher/assets/62464241/51acc6f1-53d8-4c8b-8f1c-a5fd6969f934)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.17.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Zhirnoff** [comment]
Tested.

**Comment by AlexeyGirin** [comment]
Verified.
