### ISSUE TITLE
Calculated Values: does not work on part of reaction

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#370]
**Affected Versions**: Standalone

**Steps to Reproduce**:

1. Draw a reaction
2. Select the part of reaction (e.g. one reactant/product)
3. Click the 'Calculated Values' button.
4. Verify data in the opened window.

**Expected result**: Calculated result on selected part

**Actual result**: Error "core: <reaction> is not a base molecule"

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/345

**Comment by AndreiMazol** [comment]
Fixed in release/2.2

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.2 Issue is closed as fixed
