### ISSUE TITLE
Macro: Selected monomer does not appear above the others

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3703]
**Steps to Reproduce**
1. Switch to Macro mode
2. Add multiple monomers on top of each other
3. Choose monomer that is under the others

**Actual behavior**
Selected monomer does not appear above the others

**Expected behavior**
Selected monomer appear above the others

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/c0f78d58-0b53-42ef-a21c-78c19d40b30e

Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.17.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Konstantin1996** [comment]
Hello, I tried to implement solution inside **BaseMonomerRenderer**.
/ketcher/packages/ketchercore/src/application/render/renderers/BaseMonomerRenderer.ts

This method does not do anything useful but it can help you to find the solution.

I think we should use -> **this.canvasWrapper.select('.rootElement').raise();** method. But we should trigger it only once. 
Seems we need to call it during click and not inside BaseMonomerRenderer.ts.

Here is the video how it works currently



`
private appendToTheEnd() {
    console.log(
      'drawn-structures',
      this.canvasWrapper.select('.drawn-structures'),
    );

    console.log(
      'g',
      this.canvasWrapper.select('.drawn-structures').selectAll('g'),
    );

    console.log(
      'g first',
      this.canvasWrapper.select('.drawn-structures').select('g'),
    );

    const gNodes = this.canvasWrapper
      .select('.drawn-structures')
      .selectAll('g')
      .nodes();

    const lastGNode = gNodes[gNodes.length - 1];
    console.log('g last', lastGNode);

    const copy = lastGNode.cloneNode(true);

    console.log('copy', copy);

    console.log(
      'node()',
      this.canvasWrapper.select('.drawn-structures').node(),
    );

    // inserts node to the bottom of the parent
    // this.canvasWrapper.select('.drawn-structures').node().appendChild(copy);

    // removes node
    // this.canvasWrapper.select('.drawn-structures').select('g').remove();

    // this method can help but we need to trigger it on click
    this.canvasWrapper.select('.rootElement').raise();

    // native dom operations do not work 
    // const parentDiv = document.querySelector('.drawn-structures'); // Select the parent
    // console.log('parentDiv', parentDiv);
    // const paragraphs = document.querySelectorAll('g'); // Get all 'p' elements
    // console.log('paragraphs', paragraphs);
    // const lastParagraph = paragraphs[paragraphs.length - 1]; // Get the last 'p' element
    // console.log('lastParagraph', lastParagraph);
    // parentDiv.appendChild(lastParagraph);
  }
`

**Comment by Zhirnoff** [comment]
Tests added to automation table.
