### ISSUE TITLE
Macro: Target macromolecula displayed (and put on layout) too far from mouse cursor on Firefox

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3706]
**Steps to Reproduce**
1. Switch to Macro mode
2. Click any peptide and move mouse cursor over canvas
Note that target peptide too far from mouse cursor - This is wrong
3. Click on canvas to add peptide on canvas

**Actual behavior**
1. Note that target peptide too far from mouse cursor
![image](https://github.com/epam/ketcher/assets/26869421/727bf2fe-995e-4b83-8131-17530fa0ab0b)
2. System put target peptide too far from mouse cursor
![image](https://github.com/epam/ketcher/assets/26869421/56719b0a-db5d-4bea-9fa4-76a3fa446d07)
UPDATE:
It seems that we have common problem - selection also works wrong
![image](https://github.com/epam/ketcher/assets/26869421/71cc3d88-96b7-4fdd-9780-3d88696487de)

**Expected behavior**
Should work as it works in Chrome (target macromolecula displayed near cursor and painted below mouse cursor)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser Firefox 120.0.1 (64-bit)

![image](https://github.com/epam/ketcher/assets/26869421/2490a42a-0f3f-4124-b53d-216da4eef93d)

**Comment by rrodionov91** [comment]
Ketcher is not compatible for firefox. Closing issue.
