### ISSUE TITLE
'generateImageAsync' method does not work in Remote mode

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#371]
**Steps to reproduce:**
1. Create any structure.
2. Call `ketcher.generateImageAsync` 

**Expected result:**
Blob is created

**Actual result:**
Error 'unhandled error' is thrown

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/347

**Comment by even1024** [comment]
Wrong request:

{"struct":"png","options":{"smart-layout":true,"ignore-stereochemistry-errors":true,"mass-skip-error-on-pseudoatoms":false,"gross-formula-add-rsites":true,"outputFormat":"png"}}

outputFormat should be changed to render-output-format.

**Comment by AndreiMazol** [comment]
Indigo/render endpoint should be updated (generation of png does not work - svg is always returned)

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/415

**Comment by AllaZhbanova** [comment]
The issue is reproducible for the following scenario: https://github.com/epam/ketcher/issues/1007

**Comment by Alex-Work-Account** [comment]
Everything is fine from our side, waiting for backend changes

**Comment by AllaZhbanova** [comment]
Not possible to open svg file - error is shown in browser

**Comment by AllaZhbanova** [comment]
fixed tested v.2.4
