### ISSUE TITLE
`@react-refresh` removes Ketcher from DOM

### ISSUE THREAD

**Issue by elramus** [epam/ketcher#3711]
**Steps to Reproduce**
1. Do a new, clean React install (issue observed in latest Vite and latest CRA)
2. Install Ketcher v2.14+
3. Try to render `Editor` from `ketcher-react`.

**Actual behavior**
On very first render, Ketcher appears as normal, but on the first pass of React re-rendering itself Ketcher disappears. It's containing `div` is suddenly empty. 

**Expected behavior**
It doesn't disappear. 

**Screenshots**

https://github.com/epam/ketcher/assets/24811404/87a7499b-22d7-4def-99ed-b332f3607526

Here's me going through debugger and seeing where(ish) the problem is happening. 
https://www.loom.com/share/0d0fc86a067b42ec83e237a907245be2

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2
 - Observed in latest Chromium (Brave, Chrome), Firefox, and Safari

**Ketcher version** [e.g. v2.4.2]. =
```
    "ketcher-core": "^2.15.1",
    "ketcher-react": "^2.15.1",
    "ketcher-standalone": "^2.15.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
```

**Additional context**
Bug is NOT observed on a production build. 
Bug seems to have been introduced in `2.14`. `2.13` runs fine. 

Here's my barebones test component, being used in a new Vite setup (same behavior can also be seen in new CRA setup).
```typescript
import 'ketcher-react/dist/index.css'

import { Editor } from 'ketcher-react'
import { StandaloneStructServiceProvider } from 'ketcher-standalone'

const structServiceProvider = new StandaloneStructServiceProvider()

export const KetcherEditor = () => {
  return (
    <div>
      <Editor
        staticResourcesUrl="http://localhost:5173"
        structServiceProvider={structServiceProvider}
        onInit={() => {
          debugger
          console.log('hello from init')
        }}
        errorHandler={() => {
          console.log('error!')
        }}
      />
    </div>
  )
}

```

**Comment by elramus** [comment]
Quick bump on this @Nitvex. Would be great if someone can take a look - unless I'm missing something, 2.14+ of `ketcher-react` is basically unusable because of this.

**Comment by Jivanam** [comment]
looks like the it goes away when you disable/don't use strict mode, which is not right though as strict mode is there to catch such errors.

**Comment by elramus** [comment]
Ah interesting. That tracks with it working okay in a prod React build.

**Comment by rrodionov91** [comment]
Fixed in https://github.com/epam/ketcher/pull/5013
