### ISSUE TITLE
Macro: Pressing Layout/Clean Up button cleanup all macromoleculas from canvas

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3712]
**Steps to Reproduce**
1. Switch to Macromolecules
2. Put any peptide on canvas (it was A in my case)
3. Switch to Molecules 
4. Press Layout button (or Clean Up button)

**Actual behavior**
Macromolecula disappeared from canvas

**Expected behavior**
Macromolecula remain on canvas

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
2.17.0-rc.2

**Comment by Zhirnoff** [comment]
Tests added to automation table.

**Comment by AlexeyGirin** [comment]
Fixed.

**Comment by Zhirnoff** [comment]
Automated.
