### ISSUE TITLE
Macro: Hot keys for toolbar buttons are not implemented in Macromoleculas view

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3713]
**Background**
At Molecular view we are able to use key bindings for every toolbar button - ctrl+z, ctrl+y and etc.
![image](https://github.com/epam/ketcher/assets/26869421/7c3af476-5f47-4c9a-961d-d02b2ed9300e)
Every button has hot key assigned and tooltip

**Solution**
We have to have the same on Macro view

Clear Canvas: Ctrl+Del, Ctrl+Backspace
Undo: Ctrl+Z
Redo: Ctrl+Shit+Z, Ctrl+Y
Erase: Del, Backspace
Select Rectangle: Shift+Tab, Esc
Zoom In: Ctrl+=
Zoom Out: Ctrl+_
Reset Zoom: Ctrl+0
"Select All" operation (not a button): Ctrl+A

**Comment by Zhirnoff** [comment]
Tests added to automation table.

**Comment by Zhirnoff** [comment]
Tested. Some hotkeys only work in micro mode or macro mode. We need consistency. An additional bug has been created.
https://github.com/epam/ketcher/issues/3917
