### ISSUE TITLE
Macro: Export of canvas to ket file cause app to crash

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3716]
**Steps to Reproduce**
1. Switch to Macromolecules view
2. Load this mol file [Chem.zip](https://github.com/epam/ketcher/files/13701616/Chem.zip) (unzip first)
3. Save canvas to ket file (name - doesn't matter)
4. Switch to Molecules view 
System throws exception: [localhost-1702890390888.log](https://github.com/epam/ketcher/files/13701652/localhost-1702890390888.log)
Since that moment - app behavior become unstable.
 5. Switch to Macromolecules view
 6. Switch to Molecules view 

**Actual behavior**
App crashes
![image](https://github.com/epam/ketcher/assets/26869421/b0b2ce6c-9a2b-4792-8de8-05db5be2508e)
![image](https://github.com/epam/ketcher/assets/26869421/eac7c0a1-55d3-42c6-945c-ca3db5e8a4a2)

**Expected behavior**
App works as intended.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/933565b7-df5d-4c9d-8e34-1d48f09072a0)

**Comment by rrodionov91** [comment]
There is a strange symbol "?x" instead of attachment point number.
It is not clear how to create such mol file:
<img width="689" alt="image" src="https://github.com/epam/ketcher/assets/14859362/c3202186-30e6-4813-9502-b55196d69a49">

@AlexeyGirin could you please clarify how to reproduce it?

**Comment by AlexeyGirin** [comment]
Unable to reproduce
