### ISSUE TITLE
Macro: Group selection using Shift+LClick is not implemented

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3728]
**Background**
It is unable to select/unselect macromolecules using Shift+LClick. The only way to select group of elements is area selection (by mouse).

**Solution**
Implement group selection using Shift+LClick in the same manner as it is done in Molecules view

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by Zhirnoff** [comment]
Test automated.
