### ISSUE TITLE
Macro: Displaying modified nucleotide chains in sequence representation

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3734]
**Background**
Modified nucleotide contains one or more synthetic modifications to its phosphate (P), ribose sugar (R), or base (A, T, C, G, U).
User should be able to view modified RNA monomers in sequence representation, where modified nucleotides are marked somehow to distinguish which part of nucleotide is modified (phosphate, sugar or base).
Nucleotide - sugar+base+phosphate, connected by the rules, defined in RNA preset.
Nucleoside - sugar+base, connected by the bond between R3 AP of sugar and R1 AP of base.

**Requirements**
In addition to the rules for display of unmodified nucleotides in sequence representation [#3648](https://github.com/epam/ketcher/issues/3648)
1. In sequence view nucleotide should be displayed as a letter which corresponds to the natural analog of base that is a part of nucleotide. If nucleotide has a modified component (phosphate, sugar, or base), then a letter should be marked by some unambiguous designation (see mockups in comments). 
- Modified phosphate - any phosphate except 'P'
- Modified sugar - any sugar except 'R'
- Modified base - any base except 'A', 'C', 'G', 'T', 'U'
2. The last  letter of chain in sequence view displays nucleotide that lacks a phosphate. If there is a phosphate connected to R2 AP of sugar, then in sequence view this phosphate is displayed as 'p' symbol. 
3. Any phosphate that is not a part of nucleotide is also displayed as 'p' symbol. 
4. Chems are displayed as '@' 
5. Sugars that are not a part of nucleotide or nucleoside are displayed as '@' 
6. If there is a linker that contains multiple sugars or some other combination of modified subunits (non-nucleotide), the entire block can be represented with a '@' symbol.
Image for better understanding:
<img width="400" src="https://github.com/epam/ketcher/assets/143799055/97da3f28-d642-478a-ab5a-5688b0722ddb">

**Alternatives**
Any connection, except R2-R1 (R1-R2) between sugar and phosphate AND R3-R1 between sugar and base correspondingly are considered as side chain connections and displayed as straight line connecting two monomers center-to-center.
Peptide monomers are displayed as natural analog symbols, R2-R1 bonds between peptide monomers are not displayed, all other bonds are displayed as straight lines. 

**UX**
![image](https://github.com/epam/ketcher/assets/143799055/d316a2e6-d4bd-42f5-9a1d-bf0adf0a3f84)

**Comment by Andrey-Antonov** [comment]
<img width="712" alt="image" src="https://github.com/epam/ketcher/assets/141816460/ae414227-942d-4b21-a72a-24af1df851b2">

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested on 2.21.0-rc.1 No comments.

![2024-04-17_15h04_20](https://github.com/epam/ketcher/assets/62464241/cb411145-68f6-4a71-b1c7-cb6b6fbca021)

![2024-04-17_15h03_32](https://github.com/epam/ketcher/assets/62464241/0ad9c387-b0e9-4d9d-9179-62f0d5aa1831)
