### ISSUE TITLE
Macro: System marks availiable connection point as unavaliable in Select Connection Point dialog

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3736]
Issue found in the context of testing #3580

**Steps to Reproduce**
1. Switch to Macromolecules view
2. Load this file: [ConnectionDialogTests.zip](https://github.com/epam/ketcher/files/13722339/ConnectionDialogTests.zip) (unzip first)
3. Connect R3 connection point of H peptide with center of M peptide
![image](https://github.com/epam/ketcher/assets/26869421/4d597309-1669-4d40-bdb9-ffc7a98a571d)
Select connection dialog appears - this is ok.
4. Click on R2 connection point for Histidine

**Actual behavior**
Note that system removes selection from R3 connection point on preview, but paint it as unavailable for connection (already connected)
![image](https://github.com/epam/ketcher/assets/26869421/d7d0145a-92f4-4fea-b174-c25b350f4532)
Same problem in expanded mode

**Expected behavior**
System removes selection from R3 connection point on preview and paint it as available for connection

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/a04bc8c1-4141-47c9-82df-73498321c4b0)

**Comment by AlexeyGirin** [comment]
No fixed.
![image](https://github.com/epam/ketcher/assets/26869421/da48220a-fd83-454a-98b1-e151e69355c7)

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. Fixed.
![2024-02-21_11h55_56](https://github.com/epam/ketcher/assets/62464241/6197bc2d-b7e0-42e8-b9e5-eb6d5eadc481)
