### ISSUE TITLE
Macro: System threats R-groups as connection points and ignores real connection points (rakes)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3743]
Issue found in the context of testing #3580

**Steps to Reproduce**
1. Switch to Macromolecules view
2. Load this file: [ConnectionPoints.zip](https://github.com/epam/ketcher/files/13722887/ConnectionPoints.zip) (unzip first)
3. Select Single Bound tool
![image](https://github.com/epam/ketcher/assets/26869421/09534b5c-6026-4ab0-89bf-da1336e1abea)
4. Start to connect F1 and F2 monomers
Select Connection Points dialog appears - this is ok, expand it to large mode

**Actual behavior**
Note that my custom monomer (F2) has many R-groups and two connection points (primary and secondary) in micro view
![image](https://github.com/epam/ketcher/assets/26869421/c327137c-c70c-495c-b468-a2d5bc82e946)
but in Select Connection Points dialog - it ignores real connection points (rakes) and threats R-groups as connection points
![image](https://github.com/epam/ketcher/assets/26869421/722dd9f0-6bca-45a3-bac3-5c09c47502e0)

**Expected behavior**
System should show two connection points for my custom monomer and ignore R-groups

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/a04bc8c1-4141-47c9-82df-73498321c4b0)

**Comment by rrodionov91** [comment]
Approved with @olganaz and @AlexanderSavelyev that we use rglabels as monomer attachment points in macro mode.
One thing which will be discussed further is to create requirements for rgroup attachment points in macro mode. We need to decide how we are going to display them.
Closing the issue.

**Comment by AlexeyGirin** [comment]
Ok
