### ISSUE TITLE
Micro/Macro: System replace connection points with R-groups if we remove abbreviation for monomer from macromolecule library

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3744]
**Steps to Reproduce**
1. Start from clear canvas
2. Switch to Macromolecules view
3. Put on the canvas Test-6-Ch monomer from CHEM tab from Library
4. Switch to Molecules view
5. Right click on Test-6-Ch label and click Remove Abbreviation
![image](https://github.com/epam/ketcher/assets/26869421/e322aedf-eec2-40dc-ace6-9678284400ee)

**Actual behavior**
System shows monomer where all connection points replaced with R-groups
![image](https://github.com/epam/ketcher/assets/26869421/a0d7404c-371e-4d98-b46a-1756a31cf72a)

**Expected behavior**
System shows correct monomer
![image](https://github.com/epam/ketcher/assets/26869421/8736c9da-c578-45c9-88df-76e1ae566e5d)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/a04bc8c1-4141-47c9-82df-73498321c4b0)
**Additional context**

**Comment by rrodionov91** [comment]
Restricted remove abbreviation

**Comment by AlexeyGirin** [comment]
Fixed.

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by Zhirnoff** [comment]
Automated.
