### ISSUE TITLE
Micro/Macro: Unable to bound Functional Group (from Structural Library at Molecules view) and CHEM monomer from Library (from Monomolecule view)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3745]
**Steps to Reproduce**
1. Start from clean canvas
2. Switch to Molecules view and put on the canvas any Functional group (Ac in my case) from Structure Library 
3. Switch to Macromolecules view and put on the canvas any monomer (Test-6-Ch in my case) from Library/CHEM
![image](https://github.com/epam/ketcher/assets/26869421/b2197f21-a884-4605-975d-e35b483d297b)
4. Select Single bound tool and try to connect those two blocks (use center-to-center way)

**Actual behavior**
It is impossible since functional group block (F1) has no connection points

**Expected behavior**
It is possible since functional group block (F1) has one connection point (rake)
![image](https://github.com/epam/ketcher/assets/26869421/b622b8f7-9ea5-4553-92e1-0fe6a03e533c)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/a04bc8c1-4141-47c9-82df-73498321c4b0)

**Comment by rrodionov91** [comment]
For mvp scope it was decided to block bonding between micro and macro structures.
