### ISSUE TITLE
Macro: Save to file and than Load it back eliminate monomer names from preview tooltip

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3757]
**Steps to Reproduce**
1. Switch to Macromolecules view
2. Load this file: [Alanine.zip](https://github.com/epam/ketcher/files/13741618/Alanine.zip) (unzip first)
System loads one monomer:
![image](https://github.com/epam/ketcher/assets/26869421/80b04e54-6080-4dc5-891b-70bdbba7e5e9)
4. Go to Library/Peptides and put Alanine to canvas (to have it two)
![image](https://github.com/epam/ketcher/assets/26869421/07cd477c-a5ec-4359-8499-22304adba2cc)
5. Hover mouse cursor over one monomer and than over added one

**Actual behavior**
From file:
![image](https://github.com/epam/ketcher/assets/26869421/b66f61bd-9b70-4486-9fe2-1758e5534dd2)
Added one:
![image](https://github.com/epam/ketcher/assets/26869421/e2873486-afb1-43b2-ad1b-6f6a91b80ccb)
Note that peptide loaded from file - name is missing
![image](https://github.com/epam/ketcher/assets/26869421/87d70182-bfeb-4a04-b3d6-236c4aee225e)
I tried ket and mol files - it works the same for any monomer type.

**Expected behavior**
It should not be any differences between instance loaded from the file and from Library

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/a04bc8c1-4141-47c9-82df-73498321c4b0)
**Additional context**

**Comment by Zhirnoff** [comment]
Test added to automation table.

**Comment by AlexeyGirin** [comment]
Fixed for ket format but not for mol. Mol doesn't support labels

**Comment by Zhirnoff** [comment]
Bug fixed for ket. files, but when saving in mol. and opening on tooltips there are no names. Apparently the format itself is mol. file does not support this.
