### ISSUE TITLE
Autotests: Macro: Monomers on the canvas, their connection points and preview tooltips

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3780]
**Description:**
These bunch of tests validates that system  correctly load every type of monomer (Peptide, Sugar, Base, Phosphates) from ket file, correctly show them on canvas (name, shape, color), shows correct number or connections and shows correct preview tooltip

### Test case:
**Preconditions:**
1. Switch to Macromolecules view
2. Clear canvas

**Test case:**
3. Open file
4. Center monomer on the screen
5. Press Single Bond button on toolbar
6. Hover mouse over monomer until Preview tooltip appears
7. Take a screenshot
8. Compare it with the template

Test case should be executed against every file in attached zip: [Monomers.zip](https://github.com/epam/ketcher/files/13772673/Monomers.zip)

**Comment by Zhirnoff** [comment]
Tests automated in 'import-saving-ket.spec.ts'
