### ISSUE TITLE
Macro: Connection works wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3786]
**Steps to Reproduce**
1. Switch to Macromolecules view
2. Load this file: [CanNotConnect.zip](https://github.com/epam/ketcher/files/13759750/CanNotConnect.zip) (unzip first)
3. Try to connect 5A6 sugar monomer with Rsp using center-to-center way

**Actual behavior**
System doesn't connect but rises Select Connection Points dialog with missing connection points labels
![image](https://github.com/epam/ketcher/assets/26869421/00ef0efc-53b0-4413-bc5b-69883dc57920)

**Expected behavior**
System establishes connection without rising Connection Points dialog (R1 to R2)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/a04bc8c1-4141-47c9-82df-73498321c4b0)

**Comment by Zhirnoff** [comment]
Test added to automation table.

**Comment by Zhirnoff** [comment]
Tested.
