### ISSUE TITLE
Macro: System opens Select Connection Points dialog in case of center-to-point connection when it shouldn't

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3799]
**Steps to Reproduce**
1. Switch to Macromolecules view
2. Put on the canvas two 5 or 6 connection point monomers
3. Switch to Single Bond mode by pressing Single Bond button
4. Drag center of one monomer and move cursor to exact connection point of another monomer (R3 in my case, not R1 and not R2!)

https://github.com/epam/ketcher/assets/26869421/e9bbbafd-638a-44d1-b63d-2dada454f1bd

**Actual behavior**
System opens Select Connection Points dialog

**Expected behavior**
System establishes connection R2-R3 as per [requirement](https://kb.epam.com/display/EPMLSOP/Types+of+connections) rule: 

> User drags a bond from the center of the first monomer to the specific AP of the second monomer.
> *By default, system should choose R2 of the first monomer, If available. If R2 is not available, then modal window appears, and user can choose other available APs.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.130 (Official Build) (64-bit)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/d9a461aa-f46a-48c3-8062-06bb52403c4b)

**Documentation**
https://kb.epam.com/display/EPMLSOP/Types+of+connections

**Comment by rrodionov91** [comment]
@olganaz please fix requirements

**Comment by olganaz** [comment]
@rrodionov91 requirements were adjusted. Issue is closed.
