### ISSUE TITLE
Rotation angle doesn't display after I change its value

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#380]
**Affected Version**: Standalone, Remote

**Steps to reproduce**:

1. Draw a structure on the canvas
2. Navigate to Display Settings and change Rotation Step value
3. Rotate the structure

**Expected result**: When I rotate, the rotation angle is displayed in a pop-up in upper right corner of the canvas:
![image](https://user-images.githubusercontent.com/79926367/110622315-60017b80-81ac-11eb-88e3-e8bb482b7637.png)

**Actual result:** The rotation angle is not displayed unless I reload the page after changing settings.

**Comment by Svetlana-Asinovskaia** [comment]
Issue is closed as fixed
