### ISSUE TITLE
Macro: Center-to-Center connection operation between phosphates should always open Select Connection Points dialog

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3801]
**Steps to Reproduce**
1. Switch to Macromolecules view
2. Load this file: [NoDialog.zip](https://github.com/epam/ketcher/files/13769672/NoDialog.zip) (unzip first)
3. Try to connect any phosphates with any - use center-to-center way

https://github.com/epam/ketcher/assets/26869421/b32b49c2-40e1-4213-b0af-928447fb2bcc

**Actual behavior**
System establishes connection

**Expected behavior**
System should always open Select Connection Points dialog as per [requirement](https://kb.epam.com/display/EPMLSOP/Types+of+connections) rule: 
> Phosphate could be connected with the phosphate through R2-R1 as well as R1-R1 or R2-R2.
>     User should be asked which attachment points should be used to establish a bond.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version** [e.g. v2.4.2]. 
![image](https://github.com/epam/ketcher/assets/26869421/532589c2-a3d9-464b-8cd9-ca061a79626e)

**Comment by rrodionov91** [comment]
@olganaz works as expected, please fix requirements

**Comment by olganaz** [comment]
@rrodionov91 requirements were adjusted. Issue is closed.
