### ISSUE TITLE
Page auto jump to top when ketcher editor inited

### ISSUE THREAD

**Issue by Valen-C12** [epam/ketcher#3813]
**Steps to Reproduce**
use ketcher editor in a dialog, in a long page. So the ketcher will not render when page loaded, but when user open the dialog

**Actual behavior**
The page will auto scroll to the page top

**Expected behavior**
The page keep the old position, no any jump

**Screenshots**
code source: https://github.com/epam/ketcher/blob/be6713092078019ed12b7e732bea4da2ac937696/packages/ketcher-react/src/script/ui/App/App.tsx#L67

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 120.0.6099.129

**Smartphone (please complete the following information):**

**Ketcher version** [e.g. v2.4.2]. 
    "ketcher-core": "2.11.0",
    "ketcher-react": "2.8.0",
    "ketcher-standalone": "2.11.0",

**Test case**
Add test case number (in EPMLSOPKET-* format) if bug was found during test case run.

**Additional context**

**Comment by flc** [comment]
I also ran into this and it is really annoying. 
The assumption that the editor would always appear at the top of the page (I guess that is the reason) is quite questionable.
In my case the editor should appear inside a large form somewhere in the middle of a page.
This behavior currently makes it impossible to load ketcher lazily which would be quite recommended due to its large bundle size.

**Comment by rrodionov91** [comment]
Hi @flc and @Valen-C12 
Thank you for highlighting the issue.
We will look into it and prioritize.

**Comment by rrodionov91** [comment]
Dear @flc 
We tried to reproduce the issue however we don't see behaviour which you described.
Could you please send us video demonstrating the problem or provide demo page(preferable) where we can reproduce it?

**Comment by flc** [comment]
Sure, I'll try to put together a demo soon.
Thanks for the investigation!

**Comment by flc** [comment]
I created a repo that demonstrated the problem:

https://github.com/flc/ketcher-scroll-issue

A demo video is also included in the readme.

What's strange is that the problem doesn't occur in Firefox, but it does in every other browser I've tried.

**Comment by rrodionov91** [comment]
Hi @flc 
Thank you, let us check. Will come back soon

**Comment by rrodionov91** [comment]
Dear @Valen-C12  and @flc 
We merged the fix. It will be available in ketcher v2.28.0. First release candidate will be available in npm next week. Public release will be published after stabilisation phase.

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10
