### ISSUE TITLE
Macro: Change the color of the occupied attachment points from orange to dark green

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3815]
**Steps to Reproduce**
1. Add two monomers at canvas
2. Connect them with bond
3. Hover on bond 

**Actual behavior**
Occupied attachment points are orange

**Expected behavior**
Occupied attachment points should be dark green (the same color as selected bond)
![image](https://github.com/epam/ketcher/assets/143799055/625c8170-9366-44e6-a783-3f1d7c764237)

**Screenshots**
![image](https://github.com/epam/ketcher/assets/143799055/65be72dc-abb5-4e24-9ecd-cc1c333b5ca1)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Chrome
 - Version 120.0.6099.110 (Official Build) (64-bit)
 
**Ketcher version** 
[Version 2.17.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Zhirnoff** [comment]
Autotests added.

**Comment by Zhirnoff** [comment]
Tested. Fixed.
