### ISSUE TITLE
Macro: LR sugar from the Ligrary is not possible to load from MOL file

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3818]
**Steps to Reproduce**
1. Switch to Macromolecules view
2. Put LR sugar on the canvas
![image](https://github.com/epam/ketcher/assets/26869421/9c52001e-abb7-447a-9e9c-fd3499389a8a)
3. Save to mol file
4. Load from mol file

**Actual behavior**
System throws exception:
Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'stereocenters: stereo types of the opposite bonds mismatch near atom 1', 'RXN loader: bad header ', 'RXN loader: bad header ', 'stereocenters: stereo types of the opposite bonds mismatch near atom 1'

Load from ket - works fine

**Expected behavior**
Load works fine

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version**
Version 2.17.0-rc.2
Build at 2023-12-27; 13:44:29

**Indigo Toolkit**
Version 1.17.0-rc.3.0-g1a7f60990-wasm32-wasm-clang-12.0.0

**Comment by rrodionov91** [comment]
Indigo issue: https://github.com/epam/Indigo/issues/1465

**Comment by Zhirnoff** [comment]
test added to automation table

**Comment by Zhirnoff** [comment]
Tested. Fixed.
