### ISSUE TITLE
Macro: Selection in sequence representation

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3819]
**Background**
User should be able to select both single nucleotide as well as multiple nucleotides in sequence using panel button and hot keys. 

**Requirements**
There are two ways of selection in sequence view depending on the mode (view mode, text-editing mode)

1. **View mode:**

- 'Select' tool should work in as usual, so user is able to select single nucleotide or group of nucleotides by clicking on corresponding symbol or by selecting the area on canvas (rectangular selection). 
- Selection of the symbol displaying nucleotide means that the group of monomers that make up the nucleotide together with the bonds between them are selected. 
- If at least two adjacent nucleotides are selected the bond between them should also be selected. 
- By Shift+Lclick user should be able to select multiple nucleotides 
- By Ctrl+Lclick user should be able to select entire chain (group of monomers connected by bonds)

2. **Text-editing mode:**

- By (LClick+drag), (Shift+ arrow button) user should be able to select nucleotides like text symbols. 
- In text editing mode only single selected monomer or one uninterrupted group of monomers selected could be replaced by other symbols, otherwise input from keyboard is ignored.

3. Selection should be removed if user switches from view mode to text-editing mode. 
4. Selection should be removed if user switches  between flex/sequence/snake modes.
5. Pressing 'Esc' button, outclick and selection of other tool (except 'Erase') removes selection. 

**UX**
Actual:
![Selecting and deselecting nucleotides](https://github.com/epam/ketcher/assets/141816460/df6b7881-fe01-447f-ac51-00ce605e6710)

**Comment by Andrey-Antonov** [comment]
![Section 17](https://github.com/epam/ketcher/assets/141816460/9a5532e4-c69c-45f1-9950-3b4f86765339)

**Comment by Andrey-Antonov** [comment]
![Section 17](https://github.com/epam/ketcher/assets/141816460/74e8a2c7-26e2-4ab6-ac0d-e52089b48b23)

**Comment by Andrey-Antonov** [comment]
![Section 17](https://github.com/epam/ketcher/assets/141816460/177db24b-374a-48f1-bd23-9ea203536a73)

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. Bug registered https://github.com/epam/ketcher/issues/4260

**Comment by Zhirnoff** [comment]
- https://github.com/epam/ketcher/issues/4349
