### ISSUE TITLE
Macro: System doesn't close Save dialog after Save button pressed

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3820]
**Steps to Reproduce**
1. Switch to Macromolecules view
2. Put any monomer on the canvas
3. Press Save as... button
Save dialog appears - this is ok
4. Press Save button

https://github.com/epam/ketcher/assets/26869421/ac805a70-8d08-4017-b97c-8f7136831454

**Actual behavior**
System saves canvas but Save dialog remain opened.

**Expected behavior**
System saves canvas and closes Save dialog.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 120.0.6099.110 (Официальная сборка), (64 бит)

**Ketcher version**
Version 2.17.0-rc.2
Build at 2023-12-27; 13:44:29

**Indigo Toolkit**
Version 1.17.0-rc.3.0-g1a7f60990-wasm32-wasm-clang-12.0.0

**Comment by Zhirnoff** [comment]
Test added to automation table

**Comment by AlexeyGirin** [comment]
Fixed.
