### ISSUE TITLE
Macro: Modify nucleotides from sequence in RNA builder 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3824]
**Background**
In sequence representation user should be able to replace any part of nucleotide (sugar, phosphate and base) with modified analog from library. 

**Requirements**
1. User should be able to modify single as well as multiple selected nucleotides on canvas in RNA-builder without saving them to library. 
2. To switch RNA builder to Edit mode, user should choose the option "Modify in RNA builder" in context menu which appears after Rclick on selected nucleotides. 
        - If at least one of selected symbols is not nucleotide then option "Modify in RNA builder" is not available.    
3.  Once option "Modify in RNA builder" is chosen, nucleotide components (sugar, phosphate and base) should be displayed in RNA builder.
4. If several nucleotides are selected and they have the same monomer (sugar, phosphate, or base) in their structure, then this monomer is displayed in the RNA-builder in appropriate field, and for monomers, that are not identical in the structure of the selected nucleotides, [multiple] is displayed in the corresponding field.
5. Instead of field 'name your structure'  indication of the number of selected nucleotides should be displayed
6. Instead of 'Save' button the 'Update' button should be displayed.
7. When user presses 'Update' button the structure of selected nucleotides should be updated according to changes, made in builder.
8. In case of bulk modification the modal window with Warning message "You are going to make multiple changes in your sequence. Are you sure?"  should appear following pressing 'Update' button.  
        - 'Yes' option will apply all the changes made in builder to the selected nucleotides
        - 'Cancel' option will discard all the changes. 
9. Do not allow an user to unselect nucleotides if a sequence in "Modify in RNA builder" mode, while an user in "Modify in RNA builder" mode.
10. Show selected nucleotides (with green background) in sequence while an user in "Modify in RNA builder" mode.
11. Disable "layout-mode" and "Switch to Micro/Macro mode" selectors in Top bar, as well as "Undo", "Redo" buttons, if a sequence in "Modify in RNA builder" mode. 
12. Disable all tabs except "RNA" tab  if a sequence in "Modify in RNA builder" mode.
13. Disable some "Sugars", "Bases", "Phosphates" in RNA builder relying on selected sequence nucleotides. Based on below rules:
        - Sugar: R3 - always, R2 - always, R1 - if not first
        - Phosphate: R1 - always, R2 -  always
        - Base: R1 - always

**Not in scope of the ticket:**
[1. Show selected nucleotides (with blue background) in sequence while an user in "Modify in RNA builder" mode.
2. Apply opacity to unselected nucleotides in sequence while an user in "Modify in RNA builder" mode.
3. Apply blue background to RNA Builder while an user in "Modify in RNA builder" mode.](https://github.com/epam/ketcher/issues/4374)
[4. Allow modifying Nucleosides of sequence in RNA Builder
5. Disable some "Sugars" and "Phosphates" in RNA builder relying on selected sequence nucleotides. Based on below rules:
        - Sugar: R2 - if not last
        - Phosphate: R2 -  if not last](https://github.com/epam/ketcher/issues/4388 )

**UX**

![Editing rna in rna builder - for dev](https://github.com/epam/ketcher/assets/141816460/a42e8b24-49b2-4fdc-a14f-cbbec2cd7359)

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested on build 2.21.0-rc.1 One minor bug registered.
