### ISSUE TITLE
Query specific feature blank values are inconsistent with None value in context menu

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3832]
**Steps to Reproduce**
Open Atom properties/Query specific
![image](https://github.com/epam/ketcher/assets/26869421/b88f7516-2d86-4634-8811-cd4dc94ce977)
Open context menu/Query properties for the same atom
![image](https://github.com/epam/ketcher/assets/26869421/f21adb7b-0c5a-4410-863b-af6b02abd345)

**Actual behavior**
Note, that None values in menu are equal to blank values in properties window

**Expected behavior**
It should be consistent across all UI (i.e. it should be None everywhere)

Issue found while testing https://github.com/epam/Indigo/issues/1446

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome Version 120.0.6099.130 (Official Build) (64-bit)

**Ketcher version** [e.g. v2.4.2]. 
Ketcher Version 2.15.0-rc.4 Build at 2023-10-25; 14:15:43
Indigo Toolkit Version 1.18.0-dev.2.0-g369c82f8c-x86_64-linux-gnu-11.4.0

**Comment by AlexeyGirin** [comment]
Question to UXer.

**Comment by captain2b** [comment]
On a meeting decided to not go through with it - didn't find a better solution

**Comment by AlexeyGirin** [comment]
Not a bug
