### ISSUE TITLE
Error 'xBonds is not defined' for S-Group

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#384]
**Affected versions**: standalone, remote

**Steps to reproduce**:

1. Draw a chain structure in Demo version
2. Add an S-Group
3. Try to use Layout/Clean Up/Check Structure/Save --> Ok
4. Open the same structure in standalone/remote (structure attached [sgroup.zip](https://github.com/epam/ketcher/files/6123493/sgroup.zip))
5. Try to use Layout/Clean Up/Check Structure/Save

**Expected result:** behavior is consistent
**Actual result:** 'xBonds is not defined' error when saving; Layout/Clean up/Check Structure do not work (see below Demo vs Standalone)

https://user-images.githubusercontent.com/79926367/110799212-ffe20680-828b-11eb-9cd7-41905d2acc06.mp4

https://user-images.githubusercontent.com/79926367/110799217-01133380-828c-11eb-8886-061652d7c14a.mp4

**Comment by AndreiMazol** [comment]
Cannot reproduce:  (tested on release/2.2 branch)
cc: @AleksandraTitova
