### ISSUE TITLE
Macro: 'class' field is absent after serialisation to ket

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3846]
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Add any Sugar to canvas
3. Save to ket file

**Actual behavior**
Field class is absent in ket file.

**Expected behavior**
Fields "classHELM" and "class" contain values according to specification https://kb.epam.com/display/EPMLSOP/KET+specification+for+macromolecules 
Field "classHELM" contains value PEPTIDE/RNA/CHEM.
Field "class" contains value AminoAcid/Sugar/Phosphate/Base/Terminator/Linker/Unknown/CHEM.

**Comment by Zhirnoff** [comment]
Tested. No comments.
![2024-01-16_16h02_07](https://github.com/epam/ketcher/assets/62464241/cfa95006-e721-41a3-b1cc-78c396f11829)

**Comment by Zhirnoff** [comment]
Tests added to the automation table.
