### ISSUE TITLE
Macro: UI support import/export sequence 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3862]
**Requirements**

**Import sequence**
1. Add to the modal window 'Open'/'Paste from the clipboard' a dropdown menu for format choosing. 
Available options:
- Ket Format
- MDL Molfile V3000
- Sequence
2. By default Ket format should be chosen 
3. When sequence format is chosen additional options should be displayed:
- RNA
- DNA
- Peptide
4. DNA/RNA supported symbols: A, T, C, G, U (case insensitive)
Peptide supported symbols: A, C, D, E, F, G, H, I, K, L, M, N, P, Q, R, S, T, V, W, Y (case insensitive)
For all other symbols Error should be displayed. 

**Export sequence**
1. Add to the modal window 'Save Structure' an option 'Sequence' to dropdown 'File format'

**UI**
![image](https://github.com/epam/ketcher/assets/141816460/cc335003-842b-402f-8b32-8075a4b72d9f)

![image](https://github.com/epam/ketcher/assets/143799055/d0a73f9b-16c2-4801-a4aa-be7cb5e91a1e)
![image](https://github.com/epam/ketcher/assets/143799055/9b04a29a-4364-4506-87b5-0576984376d1)

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. Added minor bug https://github.com/epam/ketcher/issues/4114
