### ISSUE TITLE
Macro: RNA layout change while switching from sequence to flex and snake modes. 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3870]
**Background**
User should be able to switch between modes (flex, snake, sequence).
This task represents how RNA layout should change after switching from sequence mode to flex mode. 
Nucleotide is made up from sugar, base and phosphate connected with bonds between R2 of sugar and R1 of phosphate, R3 of sugar and R1 of base.

**Requirements**

1. Switching from sequence to flex mode
 - When user switches from sequence mode to flex mode, the layout of the RNA chain in Flex mode should automatically be changed to left-to-right ("snake")
 - The length of the row should be 30 nucleotides.
 - In case of single chain, the position of the first monomer on canvas should be the same as in sequence mode. 
 - In case of multiple chains, the position of the first monomer of the first chain defines the "top left" corner on canvas. Each chain form separate "snake",  which starts from the next row. 
 - By pressing 'Undo' panel button or 'Ctrl'+'Z' the layout should return to unarranged state. 
 2. Switching from sequence to snake mode
 - Snake mode works as usual. 
 - The position of the first monomer is defined the same as described in p.1.

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. No comments.
