### ISSUE TITLE
Some query properties are not stored in Mol V2000

### ISSUE THREAD

**Issue by Nitvex** [epam/ketcher#3872]
Some query properties (namely Implicit H, Connectivity, Ring Membership, Ring Size, Aromaticity, custom query) do not appear in MOL V2000 file when the structure is saved.

**Background**
For now, Mol v2000 file is generated on Ketchers' side, where support for some query properties is absent and is represented by `0` in molv2000, despite the property is set.

**Solution**
It is proposed to move Mol v2000 generation/loading on Indigo conditionally – if a structure contains specific query properties, then perform Indigo call and get MolV2000 from Indigo and do not generate it on Ketchers' side.

Acceptance criteria:
- MolV2000 is generated on Indigo side if molecule has one of the following properties:
  - [x] H count
  - [x] Aromaticity
  - [x] Ring Membership
  - [x] Ring Size
  - [x] Connectivity
  - [ ] Has custom query - https://github.com/epam/ketcher/issues/4013
  
- MolV2000 is generated correctly and all the set properties are properly set in MolV2000 (performed by Indigo)

Issues connected with https://github.com/epam/Indigo/issues/1440

**Comment by AlexeyGirin** [comment]
Closed as agreed with @AlexanderSavelyev 
Custom query problem moved to separate issue
