### ISSUE TITLE
Macro: R2 label is displayed on attachment atom instead of leaving group in monomer preview

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#3874]
**Steps to Reproduce**
1. Go to macromolecules mode
2. Open file [ala.ket.zip](https://github.com/epam/ketcher/files/13918126/ala.ket.zip)
3. Hover on monomer

**Actual behavior**
R2 label displayed on attachment atom
<img width="308" alt="image" src="https://github.com/epam/ketcher/assets/14859362/119032a7-ceef-40d7-a960-bdb8b9a5beb9">

**Expected behavior**
R2 label displayed on leaving group
<img width="290" alt="image" src="https://github.com/epam/ketcher/assets/14859362/edf8117f-8604-42fa-b21c-bce0140a293a">

**Comment by Zhirnoff** [comment]
Tested. No comments.
