### ISSUE TITLE
Macro: Nucleotide preview in sequence representation 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3876]
**Background**
In sequence representation nucleotides are displayed as letters, so it is impossible to see which of which submonomers nucleotides are made up. 

**Requirements**
User should be able to see the compounds of hovered nucleotide. 
Preview should include full names of submonomers. 
Preview tooltip should have adjustable width (depends on the length of the full monomer name).

**UX**
![image](https://github.com/epam/ketcher/assets/143799055/b6b65030-2481-4888-8822-1ba749e349ab)

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. The hover looks very faded on letters. And we need to find out what kind of 'Edit mode' is shown on mockup
