### ISSUE TITLE
'Calculated values' fields are editable

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#388]
**Steps to reproduce**: 
1. Draw a structure
2. Open 'Calculated values'
3. Put the cursor in Chemical Formula field
4. Start typing

**Expected result**: I cannot type in fields of Calculated Values dialog, the fields are read-only
**Actual result*: I can type in Chemical Formula field; other fields are enabled as well but I cannot type in them

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.2. Issue is closed as fixed
