### ISSUE TITLE
Calculated values: old values blink before displaying new ones

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#389]
**Steps to reproduce**: 
1. Draw a structure
2. Open 'Calculated values'
3. Close the modal
4. Change the structure and open 'Calculated values' again

**Expected result**: I see the values for changed structure, fields are empty while new data is loading
**Actual result*: I I keep seeing the previous values until new data is received

**NB**: this happens fast in Remote version but can take several seconds in Standalone, and user keeps seeing wrong information

**Comment by Svetlana-Asinovskaia** [comment]
Issue is verified and closed.
