### ISSUE TITLE
Macro: Paste from clipboard in sequence mode

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#3894]
**Background**
This issue describes the rules for paste of the sequence format in Sequence mode

**Requirements**

1. User should be able to paste sequences from clipboard though 'Ctrl+V'. 
2. The type of pasted sequence (RNA/DAN/Peptide) is defined by the "Type" control in toolbar.  
3. In addition to the issue [#3861](https://github.com/epam/ketcher/issues/3861) "Type" control should be displayed in toolbar in view mode as well as in text-editing mode. 
4. View mode
     -  If canvas is empty, then pasted fragment should be aligned left and centered vertically on visible canvas. 
     - If there is already at least one sequence on canvas, then paste should be performed in the next row. Additionally, the canvas should be moved to make newly added sequence visible.
5. Text-editing mode
    - Paste should be performed where the cursor is located.
    - If cursor is located within the existing chain (before the first symbol, in the middle or at the end) than pasted fragment should be merged with this chain according to the rules described in [#3650](https://github.com/epam/ketcher/issues/3650)
    - If the cursor is located in the first cell of empty row of a grid, then pasted fragment should be considered as new chain. 
6. If unsupported symbols are entered during paste from clipboard then the system should display Error message "Ketcher doesn't support symbols ... . Paste operation failed" and not to perform paste. 

**Alternatives**
System should ignore all other formats except sequence and KET not to perform paste.
The rules for paste of Ket format are described in separate issue [#3916](https://github.com/epam/ketcher/issues/3916)

**UX**
Add printscreen with paste operation
<img width="300" src="https://github.com/epam/ketcher/assets/143799055/0a37ee24-733b-4fa7-93de-113986d80eea">
![image](https://github.com/epam/ketcher/assets/141816460/2ff0f629-8706-4ec4-b6da-278b0d78326d)
![image](https://github.com/epam/ketcher/assets/143799055/75ccb026-c6c8-4f3b-b8ab-da426309cbef)

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by AlexeyGirin** [comment]
Verified.
