### ISSUE TITLE
Macro: Attachment points do not disappear when hover is removed from some monomers.

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3899]
**Steps to Reproduce**
1. Switch to Macro mode
2. Add monomers to canvas
3. Select Bond tool
4. Hover monomers going through one to another
Note: Also reproduced when hovering monomers connected by bonds

**Actual behavior**
Attachment points do not disappear when hover is removed from some monomers.

**Expected behavior**
Attachment points disappear when hover is removed from monomers.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/e0fe9448-f69b-4b54-a044-fe855c4a53e1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.18.0-rc.1]

**Comment by Zhirnoff** [comment]
Bug is still reproducing
![2024-02-09_18h02_03](https://github.com/epam/ketcher/assets/62464241/897a6f1d-a33a-4537-a1eb-224f36d87759)

**Comment by rrodionov91** [comment]
Finally fixed in https://github.com/epam/ketcher/pull/4482

**Comment by NadezhdaPeskun** [comment]
Verified as fixed for CI Version 
2.21.0-rc.1 Build at 2024-04-26
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-dev.1.25-gafde2b35-wasm32-wasm-clang-12.0.0

OS: Windows 11
Browser Chrome
Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by Zhirnoff** [comment]
Tested on release 2.21.0-rc.2
Fixed.

https://github.com/epam/ketcher/assets/62464241/c19993b8-ea75-4683-9679-9d1432e17cb3
