### ISSUE TITLE
Atom Generics (except A) and Special nodes are replaced with R# after saving in Daylight Smile format.

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#39]
**Steps to reproduce**

1. Create any structure, for example, chain.
2. Click Periodic table.
3. Open Extended tab.
4. Click the "A" button in the Atom Generic section, click the OK button and click any structure atom.
5. Repeat steps 3-4 with other Atom Generics and Special nodes.
6. Click "Save as" button. Select Daylight SMILE format. Click OK.
7. Clear the canvas.
8. Open the structure saved at 6th step.

**Actual result**
All Atom Generics and Special nodes are replaced with R#.
![image](https://user-images.githubusercontent.com/7427808/92368048-df2fcd00-f0ff-11ea-9c92-7aefd4fbbf9f.png)

**Expected result**
Atom Generics and Special nodes should stay at the structure after user saves the structure in Daylight SMILE and opens it in Ketcher.
If it's impossible to save such structures in Daylight SMILE the warning message about this should appear in Save window before the saving.

**Comment by Alena-Guznischeva** [comment]
As agreed on the discussion: R-atom should be saved as [*]. Any other generics should be saved to SMILES as *. 
There should be a warning added when saving the Daylight SMILES if there are generics and they will not be saved the same way as they are represented on the canvas

**Comment by ViktoriiaFedotkina** [comment]
#979

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
