### ISSUE TITLE
Display Settings: 'Show hydrogen labels' triggers error

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#391]
**Steps to reproduce:**
1. Open Display Settings
2. Select Atoms menu
3. Select a value in 'Show hydrogen labels' dropdown

**Expected result**: I can select and save a value

**Actual result**: I cannot select any value, i.e. system views it as incorrect:
![image](https://user-images.githubusercontent.com/79926367/111126902-44b7b700-8584-11eb-84fe-8eda797f90c8.png)

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.2. Issue is closed as done
