### ISSUE TITLE
Macro: After pressing Snake mode, attachment points stick out in different directions and not attached to the bonds

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3919]
**Steps to Reproduce**
1. Switch to Macro mode
2. Make monomers sequence connected by bonds
3. Hover over monomer and move away mouse cursor when bonds freezes
4. Press Snake mode

**Actual behavior**
After pressing Snake mode, attachment points stick out in different directions and not attached to the bonds.
**Expected behavior**
After pressing Snake mode, bonds are connected to monomers and attachment points do not stick out in different directions.

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/1a107c96-e30a-4f75-9b89-f579294707c3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.18.0-rc.1]

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by Zhirnoff** [comment]
Bug is still reproducing
![2024-02-09_17h59_15](https://github.com/epam/ketcher/assets/62464241/c1610141-aac3-46b0-b7fe-576284b6a7a7)

**Comment by NadezhdaPeskun** [comment]
Verified as fixed for CI Version
2.21.0-rc.1 Build at 2024-04-26
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-dev.1.25-gafde2b35-wasm32-wasm-clang-12.0.0

OS: Windows 11
Browser Chrome
Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by Zhirnoff** [comment]
Tested on release 2.21.0-rc.2
Fixed.

https://github.com/epam/ketcher/assets/62464241/c4e05701-4c96-4b8c-932a-50a26064c7ad
