### ISSUE TITLE
Macro: It is not possible to select all text by CTRL+A and delete it in 'Paste from Clipboard'

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3920]
**Steps to Reproduce**
1. Switch to Macro mode
2. Press 'Open...' button then 'Paste from Clipboard' menu
3. Paste any text and try to select it all by CTRL+A and delete it

**Actual behavior**
It is not possible to select all text by CTRL+A and delete it in 'Paste from Clipboard'

**Expected behavior**
It is possible to select all text by CTRL+A and delete it in 'Paste from Clipboard'

**Screenshots**
![2024-01-17_17h33_00](https://github.com/epam/ketcher/assets/62464241/c94621e9-e507-40c2-932a-ec039a4ece11)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.18.0-rc.1]

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by AlexeyGirin** [comment]
Not reproducible

- Indigo Toolkit Version 1.21.0-dev.3.0-g6f55c664-wasm32-wasm-clang-12.0.0
- Ketcher Version 2.21.0-rc.2 Build at 2024-05-20; 05:30:45
- Chrome Version 124.0.6367.201 (Official Build) (64-bit)
- Windows 10
