### ISSUE TITLE
SMARTS components are not displayed for S-Groups ( round brackets )

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3931]
**Steps to Reproduce**
1. Open structures from file [s-group structure.zip](https://github.com/epam/Indigo/files/13857806/s-group.structure.zip)
2. Add Query component (left toolbar S-Group button -> Type = Query component)
3. Save as Daylight SMARTS

**Expected behavior**
SMARTS components are displayed for S-Groups

**Actual behavior**
SMARTS components are not displayed for S-Groups ( round brackets )

**Attachments**
![2024-01-05_13h24_24](https://github.com/epam/Indigo/assets/62464241/137dad8b-8987-4aec-9703-0086a30ae5d9)
![2024-01-05_13h25_17](https://github.com/epam/Indigo/assets/62464241/1c391930-6dbd-462e-ac94-4828a24038df)
![2024-01-05_13h30_42](https://github.com/epam/Indigo/assets/62464241/54bf32e8-1f42-417a-b924-7a763e19cc5f)

**Ketcher version**  
Version 2.18.0-rc.2

**Comment by AlexeyGirin** [comment]
As per @AliaksandrDziarkach - this happens because Ketcher stopped generate S-Groups for output file in KET format

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.18.0-rc.3 Build at 2024-01-31; 11:54:11
Indigo Toolkit Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
![image](https://github.com/epam/ketcher/assets/26869421/2c489eb6-96e2-4e22-9581-c44cf4c5ed75)

**Comment by rrodionov91** [comment]
Duplicate of https://github.com/epam/ketcher/issues/3949
