### ISSUE TITLE
Support selection entity selection flag in KET format

### ISSUE THREAD

**Issue by vanoprenko** [epam/ketcher#3934]
When converting a structure to KET format Ketcher should supply selection flag for each atom, bond or any other selectable entity. 

The flag should be specified according to KET specification updated in scope of https://github.com/epam/Indigo/issues/1589 

Notes:
Selection should not be updated on 'add to canvas' action

**Comment by Zhirnoff** [comment]
Tested. The selection remains on the structure.

**Comment by AlexeyGirin** [comment]
Verified.
 - Ketcher Version 2.18.0-rc.4 Build at 2024-02-06; 13:45:28
 - Indigo Toolkit Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1
