### ISSUE TITLE
System allow to create atoms with Charge value out or range

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3943]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.1 Build at 2024-01-11; 13:21:50
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436
 
**Describe the bug**
System allow to create atoms with Charge value out or range
(Former: Unable to load mol file: System throws exception: Cannot set properties of undefined (setting 'charge'))

**Steps to Reproduce**
1. Open any atom and try to set Charge value to -111

**Actual behavior**
System let you to do so
![image](https://github.com/epam/ketcher/assets/26869421/2452f48c-0f91-42a8-9ab9-80ddc4dc7a0f)

**Expected behavior**
System should validate the value and allow to define only values from allowed range
![image](https://github.com/epam/ketcher/assets/26869421/87190893-3826-46c2-a2e4-b72c388c2f39)

**Comment by AlexeyGirin** [comment]
Validation should be added +-15 range allowed only

**Comment by Zhirnoff** [comment]
Test automated.

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since no fix over 3 versions
