### ISSUE TITLE
Atom Query feature export: System lost "Ring membership" values - export to mol file

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3954]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.2.0-g369c82f8c-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.17.0-rc.2 Build at 2024-01-03; 17:17:22
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1440

**Describe the bug**
System lost "Ring membership" values

**Steps to Reproduce**
1. Open from file: [Ring membership.zip](https://github.com/epam/Indigo/files/13884733/Ring.membership.zip)
2. Save it to mol file format
3. Clear canvas
4. Load from mol file format

**Actual behavior**
System lost "Ring membership" values
![image](https://github.com/epam/Indigo/assets/26869421/9410855f-464e-4dab-a78d-842afca24eed)

**Expected behavior**
Works as intended. (system doesn't show some values because of https://github.com/epam/ketcher/issues/3529 issue)
![image](https://github.com/epam/Indigo/assets/26869421/ac6d451c-f126-4549-9bf6-59f0e38f3f19)

**Comment by captain2b** [comment]
fixed in scope of https://github.com/epam/ketcher/issues/3872

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.18.0-rc.6 Build at 2024-02-13; 19:11:17
Indigo Toolkit Version 1.18.0-rc.7.0-g8a5c36802-x86_64-linux-gnu-11.2.1
