### ISSUE TITLE
Atom Query feature export: System lost MOST "Substitution count" values - export to Molfile

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3957]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.2.0-g369c82f8c-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.17.0-rc.2 Build at 2024-01-03; 17:17:22
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1440

**Describe the bug**
System lost MOST "Substitution count" values

**Steps to Reproduce**
1. Open from file: [Substitution count.zip](https://github.com/epam/ketcher/files/13875031/Substitution.count.zip)
2. Save it to Molfile file format
3. Clear canvas
4. Load from Molfile file format

**Actual behavior**
System losts most "Substitution count" features
![image](https://github.com/epam/ketcher/assets/26869421/b25c2a7d-8956-44fd-88be-01f162428df6)

**Expected behavior**
System doesn't lost "Substitution count" features
![image](https://github.com/epam/ketcher/assets/26869421/dd508b6e-de4e-4d2d-9814-f93510a1131d)

**Note**
problem is in v2000.js only first occurrence are set

```
        if (!props.get('substitutionCount')) {
          props.set(
            'substitutionCount',
            sGroup.readKeyValuePairs(propertyData),
          );
        }
```

**Comment by captain2b** [comment]
problem is in v2000.js only first occurrence are set
```
        if (!props.get('substitutionCount')) {
          props.set(
            'substitutionCount',
            sGroup.readKeyValuePairs(propertyData),
          );
        }
```

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/ketcher/assets/26869421/12a58dbb-e56e-41cd-85d6-6f4070510ecf)

Windows 10
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0
