### ISSUE TITLE
Invalid behavior when fusing cycles bond-to-bond

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#396]
**Steps to reproduce**:
1. Draw a cycle, e.g. benzene
2. Select another cycle, e.g. cyclopentane
3. Click on benzene's bond

**Expected result**: cyclopentane fused to benzene
![image](https://user-images.githubusercontent.com/79926367/111292973-d1807480-8659-11eb-8c81-3e96b65a3723.png)
**Actual result**: benzene fused to benzene
![image](https://user-images.githubusercontent.com/79926367/111293052-e3faae00-8659-11eb-8761-1f4203c09aab.png)

Issue reproducible with different types of cycles:

https://user-images.githubusercontent.com/79926367/111293290-28864980-865a-11eb-80ba-dec2cb3071a2.mp4

Issue triggers strange behavior on complicated structures: part of structure gets duplicated

https://user-images.githubusercontent.com/79926367/111293490-61beb980-865a-11eb-821e-941919d525d8.mp4

The structure from the video: [structure-3 (1).zip](https://github.com/epam/ketcher/files/6148039/structure-3.1.zip)

**Comment by Svetlana-Asinovskaia** [comment]
Issue is closed as fixed
