### ISSUE TITLE
Micro: System disorganize molecule and label during loading from ppx file (base64 cdx format)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3961]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-rc.4.0-g84a1f903f-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.18.0-rc.2 Build at 2024-01-17; 16:42:55
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436
 - Issue also related to https://github.com/epam/ketcher/issues/3914

**Describe the bug**
System disorganize molecules and labels during loading from file (base64 cdx format)

**Steps to Reproduce**
1. Load from file: [PPT with chemdraw (1) 2.zip](https://github.com/epam/ketcher/files/14138002/PPT.with.chemdraw.1.2.zip)
2. Select first Structure

**Actual behavior**
System disorganize molecule and label in preview
![image](https://github.com/epam/ketcher/assets/26869421/727d1166-4807-43ef-8256-545df43ce822)

**Expected behavior**
![image](https://github.com/epam/ketcher/assets/26869421/390d7e75-0acf-4c5f-81f0-77758dca2752)

**Comment by rrodionov91** [comment]
Bug on indigo side

**Comment by AlexeyGirin** [comment]
Move to Indigo

**Comment by AlexeyGirin** [comment]
Moved to Indigo - https://github.com/epam/Indigo/issues/1659

**Comment by AlexeyGirin** [comment]
Roman returned back to @captain2b

**Comment by AlexeyGirin** [comment]
Fixed.
 - Ketcher Version 2.18.0-rc.4 Build at 2024-02-06; 13:45:28
 - Indigo Toolkit Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1
 
![image](https://github.com/epam/ketcher/assets/26869421/2040a207-7788-4c52-b3c5-f0dfbc0a47ca)
