### ISSUE TITLE
Clear Canvas hotkey not working on MacOS

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/ketcher#397]
**Steps to reproduce**:
1. Open Ketcher on MacOS
2. Draw something on the canvas
3. Press Command+Delete

**Expected result**: Clear Canvas action triggered

**Actual result**: nothing happens

**NB**: If I hover over the Clear Canvas button, I see the tooltip with this hotkey.

**Comment by karen-sarkisyan** [comment]
Hi!
I was unable to reproduce the issue in Ketcher 2.1 or its latest version, using following environment:

- MacOS 12.0.1 Monterey
- Safari and Google Chrome browsers.

The Cmd+Del combination works as expected, clearing the canvas and selecting lasso tool.

**Comment by AllaZhbanova** [comment]
Not reproducible, tested on v. 2.5
