### ISSUE TITLE
Brackets are displayed incorrectly when a S-Group is added to an atom or an expanded Functional Group or Salt is added to an atom of a structure

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#3970]
**Steps to Reproduce**
1. Add any structure on canvas ( ring or chain)
2. Select S-Group tool and add it to single atom ( Multiple group, SRU Polymer, Superatom ) or select any Functional Group or Salt and add to single atom and expand it

**Actual behavior**
Brackets are displayed incorrectly when a S-Group is added to an atom or an expanded Functional Group or Salt is added to an atom of a structure. The bug can only be reproduced in the Firefox browser.

**Expected behavior**
Brackets are displayed correctly when a S-Group is added to an atom or an expanded Functional Group or Salt is added to an atom of a structure. Brackets frame the atom (see screenshot) 
![2024-01-26_14h36_34](https://github.com/epam/ketcher/assets/62464241/c5d2071a-2397-4405-8134-86d44a486234)

**Screenshots**

![2024-01-26_14h37_00](https://github.com/epam/ketcher/assets/62464241/60a2a8dd-0520-4e90-b478-b052a552f52c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 122.0 (64-bit)

**Ketcher version** 
[Version 2.18.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by ilya-asiyuk-epam** [comment]
Merged into "master" and "release/2.18"
