### ISSUE TITLE
what's wrong with the google chrome?

### ISSUE THREAD

**Issue by DrZhong** [epam/ketcher#4]
there are any labels on chrome,how can I hide these labels in chrome?
![22](https://user-images.githubusercontent.com/8085571/41724130-756d3728-759f-11e8-8f95-b69d7dc46321.png)

**Comment by exaexa** [comment]
+1

**Comment by exaexa** [comment]
This is apparently caused by "minimum font size" in Chromium, the texts are hidden by default by having css `font-size:0px`, but retained in there for accesibility.

Setting minimum font size to 0 in chrome in `chrome://settings/fonts` fixes this issue.
