### ISSUE TITLE
Macro: "Del" hotkey allows removing selection, but after that, selection tool switches to deletion tool

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4020]
**Steps to Reproduce**
1. Switch to Macro mode
2. Add several Monomers on canvas
3. Select them and press 'Del' hotkey

**Actual behavior**
"Del" hotkey allows removing selection, but after that, selection tool switches to deletion tool

**Expected behavior**
"Del" hotkey allows removing selection, but after that, selection tool not switches to deletion tool

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/b208ce0f-1cb4-4461-aff6-69cfd43f7cba

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.18.0-rc.3]

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since no fix over 3 versions

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0
