### ISSUE TITLE
Wrong selection in ketcher

### ISSUE THREAD

**Issue by even1024** [epam/ketcher#406]
Steps to reproduce:

1) Create C3H6
2) Draw reaction arrow
3) Add CH4
4) Draw H2S2
5) Select CH4 & Calculate
![Screen Shot 2021-03-17 at 17 52 46](https://user-images.githubusercontent.com/7814977/111488133-066bf480-874a-11eb-97a8-1fbbd0be175b.png)

Expected result: Chemical formula is displayed as CH4
Actual result: Chemical formula is displayed as HS

**Comment by AndreiMazol** [comment]
Fixed in release/2.2
cc: @Svetlana-Asinovskaia

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.2. Issue is closed as fixed
