### ISSUE TITLE
Right-click context menu protrudes beyond edges of the Ketcher workspace

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4069]
**Steps to Reproduce**
1. Open Ketcher (iFrame)
2. Add style <div style="width: 800px; height: 500px; left: 300px; top: 200px; position: absolute;"
3. Add some structures at the edges of canvas
**Case1**
Point at atom or bond near structure located at edge and right-click and then, without removing the menu, right-click again on the structure located at edge (select closest atom or bond to the edge of canvas)
**Case2**
Open developer console and move it closer to boundaries of the Ketcher. Call right-click menu on structure closest to edge (look attached video)

**Actual behavior**
Right-click context menu protrudes beyond edges of the Ketcher workspace. 
Alignment of letters and numbers in pop-up windows is also broken
**Note:** This problem appears only in the built-in Ketcher(iFrame). On test benches, the algorithm takes into account the distance to the edge of canvas and draws a third menu depending on distance to edge of canvas.
![2024-06-27_16h55_53](https://github.com/epam/ketcher/assets/62464241/faeb4ad7-7be6-4962-a5bc-413e9d0ece89)

**Expected behavior**
The right-click context menu does not protrude beyond the edges of Ketcher workspace. 
Also, after discussion with @vanoprenko @AlexeyGirin @Andrey-Antonov , we came to the conclusion that the third menu requires a redesign. The design will be developed by @Andrey-Antonov (TBD) and provided here.

**Screenshots**

![2024-06-27_16h56_15](https://github.com/epam/ketcher/assets/62464241/44172b96-f379-46c7-abdf-1149d7ec630b)

![2024-02-09_19h16_51](https://github.com/epam/ketcher/assets/62464241/da527495-524b-45ff-9d6c-18b922c4a155)

https://github.com/epam/ketcher/assets/62464241/6ead95d3-26fe-4475-b7d3-9fc2b1585768

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.18.0-rc.5]

#187864465

Updated visuals:
![image](https://github.com/user-attachments/assets/db41b6b4-1f5f-43d2-b9e4-364af8bd3f32)

**Comment by AlexeyGirin** [comment]
@Andrey-Antonov to propose the solution

**Comment by rrodionov91** [comment]
Still need to correct the design

**Comment by KristinaKasyanovskaya** [comment]
> Still need to correct the design

Created a new bug for сorrect the design => https://github.com/epam/ketcher/issues/5202

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. But design will be implemented in scope of issue https://github.com/epam/ketcher/issues/5202

https://github.com/user-attachments/assets/869fca63-230d-4434-90ed-a2c3a200a3f8


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
