### ISSUE TITLE
Canvas preview render work at 14 times faster in Firefox than in Chrome

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4082]
**Steps to Reproduce**
Try both - Chrome and Firefox
1. Click Open... button (Ctrl+O)
2. Select open from file
3. Select file: [50 mols on 1 canvas.pptx](https://github.com/epam/ketcher/files/14270144/50.mols.on.1.canvas.pptx)
4. Click Open
![image](https://github.com/epam/ketcher/assets/26869421/d4fc3dea-0aff-44ab-a030-18c5d6624e67)

**Actual behavior**
Note that it took ~58 seconds to render preview canvas and only 4 seconds in Firefox

**Expected behavior**
Chrome render the same speed as FF

**Environment details:**
- Ketcher Version 2.18.0-rc.5 Build at 2024-02-09; 17:07:18
- Indigo Toolkit Version 1.18.0-rc.6+cdx.0-g99f004a82-x86_64-linux-gnu-11.4.0
- Chrome Version Version 121.0.6167.161 (Official Build) (64-bit)
- Win10
- Issue found while testing https://github.com/epam/ketcher/issues/3914

**Comment by captain2b** [comment]
![Uploading Screenshot 2024-02-15 at 14.09.29.png…]()

**Comment by AlexeyGirin** [comment]
More investigation needed. Seems it is on the Ketcher side.

**Comment by AlexeyGirin** [comment]
Verified.
Ketcher Version 2.18.0-rc.7 Build at 2024-02-21; 12:47:03
Indigo Toolkit Version 1.18.0-rc.7.0-g8a5c36802-wasm32-wasm-clang-12.0.0
