### ISSUE TITLE
System print out subscripted text imperfectly

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4088]
**Steps to Reproduce**
Try on both - Stand Alone version and on Remote version
1. Click Open... button (Ctrl+O)
2. Select open from file
3. Select file: [Bad subscript layout.pptx](https://github.com/epam/ketcher/files/14281276/Bad.subscript.layout.pptx)
4. Click Open
System shows canvas preview
![image](https://github.com/epam/ketcher/assets/26869421/1b4eb208-6c8a-43bf-ac4f-8f9952b58687)
5. Press Open as New Project

**Actual behavior**
System print out subscripted text imperfectly
![image](https://github.com/epam/ketcher/assets/26869421/c8a2f761-0b9d-4173-9215-cea3b278f5ab)

Open that label and re-type subscripted text and Apply button

**Expected behavior**
Subscripted text become really subscripted
![image](https://github.com/epam/ketcher/assets/26869421/3d9c7d14-1cd1-45d4-9b96-9f210a4ad9c6)

**Environment details:**
- Ketcher Version 2.18.0-rc.6 Build at 2024-02-13; 19:05:50
- Indigo Toolkit Version 1.18.0-rc.7.0-g8a5c36802-wasm32-wasm-clang-12.0.0
- Chrome Version 121.0.6167.185 (Official Build) (64-bit)
- Win10
- Issue found while testing https://github.com/epam/ketcher/issues/3914

**Comment by AliaksandrDziarkach** [comment]
Same behavior when edit text in ketcher.

**Comment by AlexeyGirin** [comment]
MOved to Indigo - https://github.com/epam/Indigo/issues/1729

**Comment by AlexeyGirin** [comment]
Moved back to Ketcher from Indigo
As per @AliaksandrDziarkach request

**Comment by Zhirnoff** [comment]
Tested. Fixed.
![2024-03-11_17h29_00](https://github.com/epam/ketcher/assets/62464241/bc6c0229-9f6b-482b-841a-2f595d252985)
