### ISSUE TITLE
Macro: There are no tooltips when hovering over each of the sequence modes

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4108]
**Steps to Reproduce**
1. Switch to Macro mode
2. Hover mouse over 'flex layout button'
3. Press 'flex layout button' and hover over 'snake layout' and 'sequence layout'

**Actual behavior**
No tooltips

**Expected behavior**
There should be tooltips when hovering over a collapsed menu and also in an expanded view when hovering over each of the sequence modes.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.18.0-rc.7]

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/1ff10ae9-ecdb-41ae-969d-65e4e4fd363c)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)
