### ISSUE TITLE
Macro: UI support export sequence

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4109]
**Background**
Add to the modal window 'Save Structure' an option 'Sequence' to dropdown 'File format'

File extension should be .seq

Backend part: 
- https://github.com/epam/Indigo/issues/1466

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by Zhirnoff** [comment]
Tested on build 2.20.0-rc.2 Feature implemented.
