### ISSUE TITLE
Blank page appears after trying to save a structure

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#411]
Affected version: Standalone

Steps to reproduce:
1. Launch Ketcher
2. Draw a structure on the canvas
3. Click 'Save as'

Expected result: 'Save structure' window is opened. It's possible to save structure to file.
Actual result: Blank page and error in console appear:
![image](https://user-images.githubusercontent.com/80695128/111807592-26cfb680-88e4-11eb-9fba-8f1f80badaa1.png)

**Comment by AndreiMazol** [comment]
Waiting for clarification from  Indigo team
cc: @AlexanderSavelyev

**Comment by AndreiMazol** [comment]
Related issue: https://github.com/epam/Indigo/issues/269

**Comment by Svetlana-Asinovskaia** [comment]
release/2.2 Issue is closed as fixed
