### ISSUE TITLE
Adding hydrogens moves molecules to the center of the screen 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4128]
**Describe the bug**
Adding hydrogens moves molecules to the center of the screen 

**Steps to Reproduce**
1. Put benzene ring to the corner of canvas
2. Press Add/Remove hydrogens button
![image](https://github.com/epam/ketcher/assets/26869421/b386cd56-5a9b-4a1d-b234-7d3a93d44d15)

**Actual behavior**
System moves molecule to the center of canvas
![image](https://github.com/epam/ketcher/assets/26869421/883e192c-4caf-48e5-8865-f65fdc10a70a)

**Expected behavior**
Molecule remain in place
![image](https://github.com/epam/ketcher/assets/26869421/fc102b34-0dd5-456b-a95e-aa74b9120408)

**Ketcher version**
 - Indigo Toolkit Version 1.18.0-rc.7.0-g8a5c36802-x86_64-linux-gnu-11.2.1
 - Ketcher Version Version 2.19.0-rc.1 Build at 2024-02-19; 15:33:56
 - Chrome Version 122.0.6261.58 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.18.0-rc.8 Build at 2024-02-22; 17:29:02
Indigo Toolkit Version 1.18.0-rc.8.0-g85a393c7c-wasm32-wasm-clang-12.0.0

![image](https://github.com/epam/ketcher/assets/26869421/85e404aa-f9b6-4032-a274-6fecd15ee54a)

**Comment by Zhirnoff** [comment]
Test automated.
