### ISSUE TITLE
Macro: UI for Open/Save As FASTA

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4146]
**Requirements**

**Open**
- Add option "FASTA" to the format dropdown menu of modal window 'Open'/'Paste from the clipboard' 
- When "FASTA" format is chosen additional options should be displayed (similar like for Sequence):
      - RNA
      - DNA
      - Peptide
      
**Save As**
-  Add option "FASTA" to dropdown 'File format' of modal window 'Save Structure'
- In case of multiple types sequences on canvas, error "Error during sequence type recognition(RNA, DNA or Peptide)" should appear

Content types for FASTA:

chemical/x-rna-fasta, chemical/x-dna-fasta, chemical/x-peptide-fasta

TBD

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. No comments.
