### ISSUE TITLE
Add code example: Embed Ketcher into React SPA

### ISSUE THREAD

**Issue by mohacsizs** [epam/ketcher#415]
Could you implement a code example that shows how to embed a non-full-size ketcher react component into a single page react application?

Please showcase the following:
 - Embed a non-full-size (e.g. 640px*640px) ketcher into a react SPA
 - Import a molecule from a textarea (MOL or SMILES) to ketcher by pressing a button on the page
 - Display the molecule as MOL or SMILES in a div, and update the text when the molecule is changed in the editor

**Comment by AndreiMazol** [comment]
Dear @mohacsizs ,

example of injecting Ketcher into react app  can be found [here](https://github.com/epam/ketcher/blob/master/example/src/App.tsx). If you  want to render it in non-full-size mode you should wrap <Editor> component by additional parent node with fixed size.
For details please look at the picture below:
![image](https://user-images.githubusercontent.com/72735611/111985058-35ed7900-8b1d-11eb-8884-681b71db99bc.png)

Best regards,
Ketcher team
