### ISSUE TITLE
Cannot select bonds when we add molecule with `addFragment`, `setMolecule` or "Paste from clipboard"

### ISSUE THREAD

**Issue by luna215** [epam/ketcher#4154]
**Steps to Reproduce**
First type of scenario:
1. Init ketcher
2. call ketcher.addFragment
3. Try to select bond (only atoms are selectable

Second type of scenario:
1. Init ketcher
2. call ketcher.setMolecule
3. Try to select bond (only atoms are selectable

Third type of scenario:
1. Click "Open..."
2. Select "Paste from clipboard"
3. Put some molecule
4. Click "Open as New Project" 

**Actual behavior**
When we hover over a bond we cannot select it nor is the bond highlighted. When we click on the bond, it also does not select the bond
![Screenshot 2024-02-26 at 5 43 15 PM](https://github.com/epam/ketcher/assets/7971405/b1918c68-48d7-4022-af43-e41d267bd42c)

**Expected behavior**
When we hover over a bond, we should see a highlight of the bond and we should be able to select it:

**Highlight when we hover over a bond:**
![Screenshot 2024-02-26 at 5 43 48 PM](https://github.com/epam/ketcher/assets/7971405/8c701fe0-29ce-4282-89f6-da962f9015ab)

**Selected bond**
![Screenshot 2024-02-26 at 5 44 17 PM](https://github.com/epam/ketcher/assets/7971405/93aa9101-dd2a-4e25-b8ef-af6d95fee620)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS w/ M2 chip 
 -  Chrome: 121.0.6167.184
 - React version: 18.2.0

**Ketcher version** [e.g. v2.4.2]. 
v2.19.0

**Comment by luna215** [comment]
A hacky way I did to get around this was to do the following:

```typescript
ketcher.addFragment(updateLigandData.smiles);
   setTimeout(() => {
   ketcher.editor.selection("all");
   ketcher.editor.selection(null);
}, 1000);
```

**Comment by rrodionov91** [comment]
Hi @luna215 !

Thank you for raising the issue. We reproduced it and planned to fix.

**Comment by luna215** [comment]
@rrodionov91 happy to help wherever I can with this.

**Comment by luna215** [comment]
Greatly appreciate this quick fix! Ya'll 🪨 !

**Comment by Zhirnoff** [comment]
@luna215 You're welcome! Glad the Ketcher team could help! If you have any more questions or need further assistance, feel free to ask. 🚀
