### ISSUE TITLE
Implement "Create Stereo Marks" window

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#417]
1. The ‘Stereochemistry’ button is present at the bottom of the window. 
2. User clicks the ‘Stereochemistry’ button (‘Enhanced Stereochemistry’ dropdown list item), ‘Enhanced Stereochemistry’ window is opened.

When canvas is empty or the created structure without stereocenter or with non-tetrahedral stereochemistry nothing is happened, the ‘Enhanced Stereochemistry’ window doesn’t appear.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects the created structure, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user doesn’t select anything on canvas, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects the correct stereocenter, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects several correct stereocenters, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects the part of the structure without stereocenter, the ‘Enhanced Stereochemistry’ window doesn’t appear.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects several correct stereocenters, the ‘Enhanced Stereochemistry’ window appears.
When several structures with the correct tetrahedral stereochemistry are present on canvas and user selects several correct stereocenters of the different structures or parts with stereocenters of the different structures or several structures, the ‘Enhanced Stereochemistry’ window appears.
3. ‘Enhanced Stereochemistry’ window design:

‘Enhanced Stereochemistry’ title is present at the window header.
The stereochemistry settings are listed in the window:
• ABS
• AND1
• AND2
• AND…
• OR1
• OR2
• OR…
The radiobutton for each setting is present at the left side.
The fields for numbers entering are present at the right side for AND… and OR… settings. Only digital symbols are allowed for this fields!
OK and Cancel buttons are present at the window bottom.
If the selected stereocenter wasn’t marker before, all radiobuttons in the ‘Enhanced Stereochemistry’ window are unchecked.
If the selected stereocenter was marker before, the appropriate radiobutton in the ‘Enhanced Stereochemistry’ window is checked.
If the several stereocenters marked before are selected:
• All selected stereocenters have the same stereo mark, the appropriate radiobutton in the ‘Enhanced Stereochemistry’ window is checked.
• The selected stereocenters have the different stereo marks, all radiobuttons in the ‘Enhanced Stereochemistry’ window are unchecked.

![image](https://user-images.githubusercontent.com/7427808/95728814-a5b12b00-0c84-11eb-9a29-1a0cdf9ab5d5.png)

4. Assign the Stereo marks.

User selects a single structure stereocenter, clicks ‘Stereochemistry’ button, choses any radiobutton (ABS, AND1, AND2, OR1, OR2), for example ABS.
• Clicks Cancel button: ‘Enhanced Stereochemistry’ window is closed. No any stereo mark appears.
• Clicks OK button: ‘Enhanced Stereochemistry’ window is closed. ‘abs’ (&1, &2, or1, or2) stereo mark appears below the selected stereocenter.
User selects a single structure stereocenter, clicks ‘Stereochemistry’ button, choses any radiobutton, for example ABS.
• Clicks Cancel button: ‘Enhanced Stereochemistry’ window is closed. No any stereo mark appears.
• Clicks OK button: ‘Enhanced Stereochemistry’ window is closed. ‘abs’ stereo mark appears below the selected stereocenter.

![image](https://user-images.githubusercontent.com/7427808/95728860-b5c90a80-0c84-11eb-8641-e67024484342.png)

User selects a single structure stereocenter, clicks ‘Stereochemistry’ button, choses AND… or OR… radiobutton.
• Enters or not any number in the entering field and clicks Cancel button: ‘Enhanced Stereochemistry’ window is closed. No any stereo mark appears.
• Enters any digital symbol(s) and clicks OK button: ‘Enhanced Stereochemistry’ window is closed. ‘&N’ or ‘orN’ stereo mark appears below the selected stereocenter. N- is entered number.
• Leaves the field for entering empty and clicks OK button: error message with Cancel button appears. When user clicks the Cancel button in the message window, the message is closed and ‘Enhanced Stereochemistry’ window is opened.
User selects the previously marked stereocenter (for example ‘abs’), clicks ‘Stereochemistry’ button, choses radiobutton for other stereo mark (for our case AND1, AND2, OR1, OR2).
• Clicks Cancel button: ‘Enhanced Stereochemistry’ window is closed. The previously marked stereocenter (for our example ‘abs’) is not changed.
• Clicks OK button: ‘Enhanced Stereochemistry’ window is closed. The previously assigned stereo mark (for our example ‘abs’) is replaced with the selected one.
User selects several previously marked stereocenters, clicks ‘Stereochemistry’ button, choses any radiobutton (ABS, AND1, AND2, OR1, OR2), for example ABS.
• Clicks Cancel button: ‘Enhanced Stereochemistry’ window is closed. All previously marked stereocenters have the initial marks.
• Clicks OK button: ‘Enhanced Stereochemistry’ window is closed. All previously marked stereocenters are replaced with the selected one (‘abs’ for our case).
5. Stereo Flags
• User creates a new structure with correct stereocenters. As soon as he adds the Stereo Bonds to the stereocenter, the &1 stereo mark appears below the stereocenter, the AND Enantiomer stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/7427808/95729127-15bfb100-0c85-11eb-9acf-9191a7f6c4ba.png)

• User selects the &1 stereocenter (or whole structure), clicks ‘Stereochemistry’ button, choses AND2 radiobutton and clicks OK button. &2 stereo mark appears below the stereocenter, the AND Enantiomer stereo flag doesn’t changed.
• User selects the &2 stereocenter (or whole structure), clicks ‘Stereochemistry’ button, choses OR1 radiobutton and clicks OK button. &2 stereo mark is changed with or1 , the OR Enantiomer stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/7427808/95729307-63d4b480-0c85-11eb-8aef-a0c913a142a6.png)

 User selects the ‘or1’ stereocenter, clicks ‘Stereochemistry’ button, clicks the OR… radiobutton, in the field near OR… enters any number, for example ‘11’ and clicks the OK button. ‘or11’ (for our example) stereo mark appears below the stereocenter, the OR Enantiomer stereo flag doesn’t changed.
• User adds a new stereobond. As soon as he adds the Stereo Bonds to the stereocenter, the ‘&1’ stereo mark appears below the newly created stereocenter, the previously marked ‘or11’ stereocenter doesn’t changed, the MIXED stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/7427808/95729500-a8f8e680-0c85-11eb-885f-a2f4a4c8cf1f.png)

If the structure stereocenters have the different stereo marks, the MIXED stereo flag appears above the structure.
• User selects the or11 stereocenter, clicks ‘Stereochemistry’ button (field near OR… button is filled with ‘11’ (for our example), choses &1 radiobutton and clicks OK button. Both stereocenters have the &1 stereo marks. The AND Enantiomer stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/7427808/95729533-b3b37b80-0c85-11eb-9d3b-f2e180e705f0.png)

If all structure stereocenters have the identical stereo marks, the appropriate stereo flag appears above the structure.
• User creates a new structure with the stereocenter(s).
If several structures with the correct stereocenters are present on the canvas, each structure has the separate AND Enantiomer stereo flag.

**Comment by Svetlana-Asinovskaia** [comment]
The button name should be changed from 'Enhanced stereo' to 'Stereochemistry'.

**Comment by Svetlana-Asinovskaia** [comment]
When OR... /AND... options are selected but the value is deleted (it is changed into '0' by default) no error message appear and the wrong stereo marks are set (or1/&1).
Steps to reproduce:
1. Select any structure with stereobonds from the Custom templates (e.g. a-D-Allopyranose)
2. Click the 'Enhanced Stereo' button.
3. Check OR... radiobutton.
4. Delete the value ('3') in the entering field.
5. Click the 'OK' button.
6. Click the 'Enhanced Stereo' button.
7. Check AND... radiobutton.
8. Delete the value ('3') in the entering field.
9. Click the 'OK' button.

![stereo](https://user-images.githubusercontent.com/80695128/117147381-e1951480-adbd-11eb-8a2f-3b033d120043.gif)

**Comment by Svetlana-Asinovskaia** [comment]
Console error after trying to change a stereo mark.

Steps to reproduce:
1. Create a structure, e.g. chain.
2. Add Single Up/Single Down bond.
3. Click the 'Stereochemistry' button.
4. Check any unselected radiobutton (e.g. ABS).

Expected result: The stereo mark is changed from &1 to 'abs'. No console errors appear.
Actual result: The stereo mark is changed from &1 to 'abs'. The console error appear.

![2021-05-14_16h41_38](https://user-images.githubusercontent.com/80695128/118279027-501b5600-b4d3-11eb-874a-38a65f9c1eeb.gif)

**Comment by Svetlana-Asinovskaia** [comment]
The UI of the "Enhanced Stereochemistry" window has been changed. New acceptance criteria are listed in the task #56
