### ISSUE TITLE
Macro: the pop-up window does not appear in fullscreen mode after clicking the “Open” button and the “Save as” button

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4173]
**Case 1: the “Open” button**

**Steps to Reproduce**
1.	Launch “Ketcher” and switch to the Macro mode 
2.	Expand the Macromolecules window 
3.	Click on the “Open” button
4.	Switch to the collapsed mode

**Actual behavior**
The “Open Structure” window does not appear in fullscreen mode, when the “Open” button is pressed. When switching to the collapsed mode, the “Open Structure” window is displayed (so this looks like the window is displayed below the fullscreen mode)

**Expected behavior**
The “Open Structure” window is displayed in fullscreen mode, when the “Open” button is pressed

**Case 2:  the “Save as” button**

**Steps to Reproduce**
1.	Launch “Ketcher” and switch to the Macro mode 
2.	Expand the Macromolecules window 
3.	Click on the “Save as” button
4.	Switch to the collapsed mode

**Actual behavior**
The “Save Structure” window does not appear in fullscreen mode, when the “Save as” button is pressed. When switching to the collapsed mode, the “Save Structure” window is displayed (so this looks like the window is displayed below the fullscreen mode).

**Expected behavior**
The “Save Structure” window is displayed in fullscreen mode, when the “Save as” button is pressed

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/40fc7e51-0932-4d9a-b598-9069d9b0fa72

https://github.com/epam/ketcher/assets/139227567/99097899-2f35-46d9-82ae-4af8b64c4670

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (122.0.6261.94) x64

**Ketcher version** 2.19.0 – rc.1

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. Fixed. But during testing found bug: https://github.com/epam/ketcher/issues/4263
