### ISSUE TITLE
Macro: When zoomed to 175% and more, buttons in Paste from Clipboard window change their position and overlap each other

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4174]
**Steps to Reproduce**
1. Switch to Macro mode
2. Press 'Open...' button -> Paste from Clipboard
3. Zoom browser to 175% and more
4. Select drop-down menu (Ket, molV3000, Sequence) and look at positions of buttons (Open as New, Add to Canvas)

**Actual behavior**
When zoomed to 175% or higher, the buttons in the 'Paste from Clipboard' window change position and overlap each other. Additionally, drop-down menu opens with altered proportions

**Expected behavior**
When zoomed to 175% or higher, the buttons in the 'Paste from Clipboard' window not change position and not overlap each other. Additionally, drop-down menu opens without altered proportions

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/6cf6b16a-8915-4618-86ee-d343b642735c

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.19.0-rc.1]

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by NataliaLoginova** [comment]
Valentin Anoprenko and I have agreed on the following behavior: 

If the distance from the bottom border of the modal window to the border of the browser screen is less than the size of the dropdown lists at the bottom of the modal window, then the dropdown list overlaps the input with the selected dropdown value.

**Comment by Zhirnoff** [comment]
Tested on 2.21.0-rc.1 Fixed.

![2024-04-16_15h49_00](https://github.com/epam/ketcher/assets/62464241/20d390b2-8a9b-4428-a05a-111996b837b5)
