### ISSUE TITLE
'Calculated values' - Data display is different in remote and standalone modes

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#421]
Affected versions:  Standalone

Steps to reproduce:

1. Launch Ketcher (Remote).
2. Draw a cycle, e.g. cyclopropane
3. Draw a reaction arrow
4. Add an element, e.g. carbon (will be added as CH4)
5. Add an element, e.g. sulfur (draw it as H2S2)
6. Select 'CH4' with 'Lasso selection'
7. Click 'Calculated Values'
8. Repeat steps 1-7 in Standalone mode

Expected result: Data is displayed the same way in two modes

Actual result: Remote - All the calculated values ('Chemical Formula', 'Molecular Weight', 'Exact Mass', 'Elemental Analysis') are displayed without brackets
![image](https://user-images.githubusercontent.com/80695128/112140343-f12d1500-8be4-11eb-9c35-3f199afacb96.png)

Standalone - 'Molecular Weight', 'Exact Mass', 'Elemental Analysis' in 'Calculated values' are displayed with brackets
![image](https://user-images.githubusercontent.com/80695128/112140630-4d903480-8be5-11eb-98aa-4980c8b27ed4.png)

**Comment by Svetlana-Asinovskaia** [comment]
Related issue - https://github.com/epam/Indigo/issues/370

**Comment by AndreiMazol** [comment]
With latest commit new output formatting implemented which differs from remote version, but approved by @AlexanderSavelyev

**Comment by AndreiMazol** [comment]
Fixed in release/2.2

**Comment by Svetlana-Asinovskaia** [comment]
release/2.2 Issue is closed as fixed
