### ISSUE TITLE
Macro: Maximum call stack size exceeded error appears during snake layout for large chains

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4231]
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Open chain with 2000 or more rna items
3. Turn on snake mode

**Actual behavior**
Uncaught RangeError: Maximum call stack size exceeded appeared in console. Chain layout did not changed.

**Expected behavior**
There is no errors in console. Chain changed layout to snake.

**Comment by Zhirnoff** [comment]
Tests added to the automation table.
