### ISSUE TITLE
Unable to save explicit (unfolded) hydrogens in InChI format

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4253]
**Steps to Reproduce**
1.	Launch “Ketcher” 
2.	Add any elements from the right panel on the canvas
3.	Click on the “Add/Remove explicit hydrogens” button
4.	Click on the “Save as” button
5.	Select the InChI file format in the drop-down
6.	Click on the “Save” button
7.	Open this saved InChI file via the “Open” button
8.	Click on the “Add to Canvas” button in the “Open structure” window
9.	Compare two structures on the canvas

**Actual behavior**
When saving explicit hydrogens in the InChI format, after opening the file the hydrogens are displayed as implicit

**Expected behavior**
When saving explicit hydrogens in the InChI format, after opening the file the hydrogens are displayed as explicit

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/876351e3-5424-4cdf-ada2-1ca05108ac7c

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (122.0.6261.112) x64

**Ketcher version** 2.19.0-rc.2

**Additional context**
Explicit hydrogens, saved in the InChI file format in Ketcher, are displayed after opening as implicit in both Ketcher and Marvin. But explicit hydrogens, saved in the InChI file format in Marvin, are displayed after opening as explicit in both Ketcher and Marvin

Issue found while testing https://github.com/epam/ketcher/issues/3685

**Comment by AlexeyGirin** [comment]
Not a bug. InChI doesn't save explicit hydrogens as per @AlexanderSavelyev
