### ISSUE TITLE
Part of the buttons in the top toolbar menu is disabled in IE11

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#426]
Affected Version: Standalone
Browser: IE 11

Steps to reproduce:

1. Launch Ketcher in IE11.
2. Check 'Layout', 'Clean up', 'Aromatize', 'Dearomatize', 'Calculate CIP', 'Check Structure', 'Calculated Values' buttons  in the top toolbar menu.

Expected result: 'Layout', 'Clean up', 'Aromatize', 'Dearomatize', 'Calculate CIP', 'Check Structure', 'Calculated Values' buttons  are enabled.
Actual result: 'Layout', 'Clean up', 'Aromatize', 'Dearomatize', 'Calculate CIP', 'Check Structure', 'Calculated Values' buttons  are disabled.
![image](https://user-images.githubusercontent.com/80695128/112613089-c0d9b680-8e30-11eb-8073-2d9a8ead3039.png)

**Comment by AndreiMazol** [comment]
Standalone mode is based on WebAssembly, but IE 11 does not support this feature, so  is it not a bug.
