### ISSUE TITLE
Macro: Not a full names of monomers are previewed in nucleotide sequence representation after paste as sequence or FASTA file

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4268]
**Steps to Reproduce**
**Case1 (Paste FASTA)**
1. Switch to macro
2. Select sequence layout mode
3. Paste FASTA file
```
>BD190087.1 WO 2003008584-A/4: Human antibody against IgE receptor and the antibody fragment thereof
CACGTTATACTGACTCAACCGCCCTCAGTGTCCGTGTCTCCAGGACAGACTGCCAGGATCCCCTGTTCGG
GACAAGACCTGACCAACAAATATGTCTCTTGGTATCAACTGCAGTCAGGCCAGTCACCTGCGCTGGTCAT
CTATGAGGACTCAAAGAGGCCCTCAGGGATCCCTGAGCGCTTCTCTGGCTCCAACTCTGGAGACACAGCC
ACTCTGACCATCACCGGGACCCAGGCTGCGGATGAGGCTGACTTTTTCTGTCAGGCGTACGACACCAACG
GTTGGGTGTTCGGCGCAGGGACCAAGCTGACCGTCCTAGGT
```
4. Hover over any letter in sequence

**Case2 (Paste Sequence)**
1. Switch to macro
2. Select sequence layout mode
3. Paste any sequence for RNA or DNA ( for example ACTGU)
4. Hover over any letter in sequence

**Actual behavior**
Not a full names of monomers are previewed in nucleotide sequence representation
**Note:** When we add sequences on the canvas in editing mode, we see previews of monomers with full names.

**Expected behavior**
Full names of monomers are previewed in nucleotide sequence representation as described in https://github.com/epam/ketcher/issues/3876

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/21cddf6b-8fbd-4645-a3b4-47d118b726bc

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.20.0-rc.1]

**Comment by ViktoriaTkacheva** [comment]
When opening a Ket file [Macro sequence.zip](https://github.com/epam/ketcher/files/14722264/Macro.sequence.zip), incomplete names of nucleotide components are displayed in the preview in Flex mode. When switching to Sequence mode, incomplete names are also displayed
<img width="611" alt="2024-03-22_12h55_14" src="https://github.com/epam/ketcher/assets/139227567/36a64081-3998-4da6-b6df-b3c74d57c1a4">

<img width="698" alt="2024-03-22_12h56_05" src="https://github.com/epam/ketcher/assets/139227567/88d5f4ff-288a-4cea-bcb8-f47b1bc471dd">

<img width="617" alt="2024-03-22_12h56_35" src="https://github.com/epam/ketcher/assets/139227567/5759b3f9-9492-4344-9dee-eee69fa18e9a">

<img width="609" alt="2024-03-22_13h04_04" src="https://github.com/epam/ketcher/assets/139227567/ee8be936-feff-43c8-97bf-02fb85b58598">

**Comment by AlexeyGirin** [comment]
Moved to indigo - https://github.com/epam/Indigo/issues/1801

**Comment by Zhirnoff** [comment]
Bug is fixed on Indigo side https://github.com/epam/Indigo/issues/1801
