### ISSUE TITLE
Macro: The Uncaught TypeError appears in the DevTool Console, when scrolling until it stops, using the Shift+Left arrow, in the Text-editing mode

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4271]
**Steps to Reproduce**
1.	Launch “Ketcher” and switch to the Macro mode
2.	Open the DevTool Console
3.	Open this file [Macro sequence.zip](https://github.com/epam/ketcher/files/14652055/Macro.sequence.zip)

4.	Go to the Sequence mode
5.	Right-click on the row of nucleotides on the canvas and select the “Edit sequence” option
6.	Press the hotkeys Shift+Left arrow until it stops scrolling this nucleotides’ row and a few more times
7.	Verify the DevTool Console

**Actual behavior**
When scrolling until it stops, using the hotkeys Shift+Left arrow, in the Text-editing mode, the Uncaught TypeError appears in the DevTool Console (collapsed and full-screen mode)

**Expected behavior**
When scrolling until it stops, using the hotkeys Shift+Left arrow, in the Text-editing mode, no error in the DevTool Console

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/67acbe52-5900-4708-acde-8fe504ad9917

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (122.0.6261.112) x64

**Ketcher version** 2.20.0-rc.1

Issue found while testing https://github.com/epam/ketcher/issues/3819

**Comment by Zhirnoff** [comment]
Tested on build 2.20.0-rc.2 Bug is fixed.
