### ISSUE TITLE
Macro: When pressing the Enter or the Spacebar, the “Edit mode” drop-down opens and closes randomly in the Text-editing mode

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4296]
**Actual behavior**
When pressing the Enter or the Spacebar, the “Edit mode” drop-down opens and closes randomly in the Text-editing mode, if before you opened the “Edit mode” drop-down at least once (even without selecting anything)

**Expected behavior**
When pressing the Enter or the Spacebar, nothing happens with the “Edit mode” drop-down in the Text-editing mode

**Case 1: when pressing the Spacebar**

**Steps to Reproduce**
1.	Launch “Ketcher” and switch to the Macro mode
2.	Switch to the Sequence mode
3.	Right-click on the canvas and select the “Start new sequence” option
4.	Enter any nucleotide (for example, U)
5.	Open the “Edit mode” drop-down and click on any empty place on the canvas
6.	Press the Spacebar on the keyboard
7.	Verify the condition of the “Edit mode” drop-down
8.	Click on any empty place on the canvas
9.	Press the Spacebar on the keyboard one more time
10.	Verify the condition of the “Edit mode” drop-down 

**Case 2: when pressing the Enter**

**Steps to Reproduce**
1.	Launch “Ketcher” and switch to the Macro mode
2.	Switch to the Sequence mode
3.	Right-click on the canvas and select the “Start new sequence” option
4.	Enter any nucleotide (for example, U)
5.	Open the “Edit mode” drop-down and click on any empty place on the canvas
6.	Press the Enter on the keyboard a few times
7.	Verify the condition of the “Edit mode” drop-down
8.	Enter any nucleotide (for example, U)
9.	Press the Enter on the keyboard
10.	Verify the condition of the “Edit mode” drop-down

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/4dba7319-29de-4507-bf61-dbe557e1e974

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (122.0.6261.112) x64

**Ketcher version** 2.20.0-rc.1

Issue found while testing https://github.com/epam/ketcher/issues/3861

**Comment by Zhirnoff** [comment]
Tested on build 2.20.0-rc.2 Bug is fixed.
