### ISSUE TITLE
Macro: When removing nucleotides from the canvas, the preview of the nucleotide does not disappear, if you leave the cursor over it

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4297]
**Steps to Reproduce**
1.	Launch “Ketcher” and switch to the Macro mode
2.	Switch to the Sequence mode
3.	Right-click on the canvas and select the “Start new sequence” option
4.	Enter any nucleotides (for example, AAAAA)
5.	Hover over any nucleotide in this chain and delete the entire nucleotide chain
6.	Click on the “Clear canvas” button

**Actual behavior**
When removing nucleotides from the canvas, the preview of the nucleotide does not disappear, if you leave the cursor over it. Using the “Undo” and “Clear canvas” buttons the preview is also not removed

**Expected behavior**
When removing nucleotides from the canvas, the preview of the nucleotide disappears, if you leave the cursor over it

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/05d7c326-8c84-4ef4-9656-f7c355e54796

https://github.com/epam/ketcher/assets/139227567/4f79bb41-2106-4769-884e-12f18422cefb

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (122.0.6261.112) x64

**Ketcher version** 2.20.0-rc.1

**Comment by Zhirnoff** [comment]
Tested on build 2.20.0-rc.2 Bug is fixed.
