### ISSUE TITLE
Macro: Migrate Monomer library from MOL V2K to KET format

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4307]
**Background**
Currently monomer library stored as sdf file based on MolV2000. This format does not support features which are planned to be implemented in Ketcher in nearest future (variant monomers, umbiguos connections, storing rna presets, etc ).
It was decided to migrate library to ket format to have ability to support all necessary features in future.

**Solution**
The list of monomers from current library should be converted to list of templates with its definitions. For example:
```
{
  "root": {
    "templates": [
       {
          "$ref": "monomerTemplate-A___Alanine"
       },
       ...
    ]
  },
  "monomerTemplate-A___Alanine": {
    // monomer template content
  },
  ...
}
```
Library should be loaded into ketcher during the build process (as it is done now for current library).
Library internal object model in ketcher should not be changed.

**Additional context**
Current library stored in packages/ketcher-macromolecules/src/data/monomers.sdf file of ketcher repository

**Comment by AlexeyGirin** [comment]
No test cases needed for that particular issue

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.20.0-dev.1.32-gf28bad61-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-13; 05:32:02
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
