### ISSUE TITLE
Macro: Introduce IDT alias for monomers and RNA presets in library and Ketcher model

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4310]
**Background**
To support IDT format import/export it needs to add some relations between monomers in Ketcher library and IDT library.

**Solution**
It needs to introduce IDT alias field to monomer and rna templates in ketcher library according to ket specification. 
IDT alias should be also stored in monomer model to have an access to it during the export/import in future.
One monomer or RNA preset could have multiple IDT aliases. 

**Examples:**
List of monomers/rna presets for which IDT alias should be added in library:
![image](https://github.com/epam/ketcher/assets/143799055/15b4d895-348c-4e27-9602-86e980b64ebf)
![image](https://github.com/epam/ketcher/assets/143799055/387d36ec-ab32-434a-b7f5-574e9b0b9196)
![image](https://github.com/epam/ketcher/assets/143799055/73e9e34a-c615-4275-9873-6b412da6a488)

Ket files - **TBD**

**Comment by AlexeyGirin** [comment]
Test cases are not needed for this particular issue

**Comment by Zhirnoff** [comment]
Tested.
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
