### ISSUE TITLE
Macro: Send monomer library from Ketcher to Indigo upon monomers import/export

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4311]
**Background**
It needs to send monomer library with idt aliases to indigo during import/export of monomers to match monomers/presets from Ketcher library to (mol v3000, sequence, fasta, idt) library.

**Solution**
It needs to add additional field to import/export request parameters which will contain all monomers library from Ketcher. 
Library should be sent entirely, in ket format, with each import/export request.
The name of field to send to indigo is monomerLibrary in payload root.
Changes should affect only those import/export that contain macromolecules. Other formats should not be changed.

**Comment by vanoprenko** [comment]
This should be implemented for all formats supporting macromolecules, not only IDT.

**Comment by ilya-asiyuk-epam** [comment]
Development on Ketcher side is on pause.
Not implemented on Indigo side.
Indigo should allow adding 'monomerLibrary' to 'options'
<img width="412" alt="ml2" src="https://github.com/epam/ketcher/assets/156656634/c34b8c18-1044-4389-ae9d-8ae560d251a7">

**Comment by AlexeyGirin** [comment]
No test cases needed for that particular issue

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
