### ISSUE TITLE
can't get svg with dearomatize using iframe ketcher for a moleculer

### ISSUE THREAD

**Issue by Honllin** [epam/ketcher#4313]
**Steps to Reproduce**
1.i'm using  a  ketcher iframe to get svg for moleculars like the following:
    ![image](https://github.com/epam/ketcher/assets/118966097/cdaefe4e-f64b-4f33-9b87-9d639c89c9ad)
![屏幕截图 2024-03-22 093008](https://github.com/epam/ketcher/assets/118966097/0ae24d54-cacf-4187-a77f-fcd0e6bb00bf)

2.using the setSetting fuction to dearomatize, 
   ketcher.setSettings({'general.dearomatize-on-load': true})
  it doesn't work

 - Browser [e.g. chrome, edge]
 - Version [latest]
-Ketcher version 2.18.0
**Related issue:** https://github.com/epam/ketcher/issues/4320

**Comment by Zhirnoff** [comment]
@Honllin Hello! Thank you for using Ketcher! We will try to fix this problem!
