### ISSUE TITLE
Macro: Cyclic chains disappear from canvas when switching to sequence mode

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4329]
**Steps to Reproduce**
1. Switch to Macro mode
2. Add RNA or DNA to canvas
3. Make chain cyclic by connecting sugars through R2-R1 attachment points,
4. Switch to sequence mode

**Actual behavior**
Cyclic chains disappear from canvas when switching to sequence mode

**Expected behavior**
Cyclic chains not disappear from canvas when switching to sequence mode.
Additional link should be visible.
![image](https://github.com/epam/ketcher/assets/161723514/ad953135-9d79-4b1e-9590-0a861e76084b)

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/3758b673-769b-4289-b6e0-dc605120f675

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.20.0-rc.1]

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/ketcher/assets/26869421/715b5f0e-53fe-44f1-9b6f-5215801da76f)
Ketcher Version 2.20.0-rc.3 Build at 2024-04-26; 16:57:15
Indigo Toolkit Version 1.19.0-rc.3.0-gf2d7689b8-wasm32-wasm-clang-12.0.0

OS: Windows 10
Browser Chrome Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by rrodionov91** [comment]
+ backmerge to 2.21 https://github.com/epam/ketcher/pull/4606
