### ISSUE TITLE
Macro: Bonds detach when moving monomers in a snake mode in Playwright autotests

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4333]
**Steps to Reproduce**
1. Open 'snake-bond-tool.spec.ts' autotests
2. Run two tests with head mode: 
1) test('Check move any peptide from middle of chain above main snake chain';
2) test('Check that you can select part of sequence in snake mode and move to new position';
This will give you the ability to visually see how Playwright interacts with the website.
4. Look at bonds

**Actual behavior**
Bonds detach when moving monomers in a snake mode in Playwright autotests
**Note:** This bug cannot be reproduced manually; it only occurs when running in Playwright. It is also strange that in flex mode, same tests are conducted without separating bonds from monomers. (Please refer to video where snake mode is commented on).

**Expected behavior**
Bonds not detach when moving monomers in a snake mode in Playwright autotests

**Screenshots**
Snake mode:

https://github.com/epam/ketcher/assets/62464241/475584d8-cdc3-40e9-af02-4cfc561fff0b

Same test in Flex mode:

https://github.com/epam/ketcher/assets/62464241/928b900d-5af3-4e97-8d7f-ecf7b2bbbc18

Snake mode:

https://github.com/epam/ketcher/assets/62464241/e6cb3121-54de-4849-b09d-c0fe3a8c7236

Same test in Flex mode:

https://github.com/epam/ketcher/assets/62464241/a302ed5d-ae48-45ca-a32b-cf47c29fc34c

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.20.0-rc.1]

**Comment by AlexeyGirin** [comment]
@rrodionov91 to investigate
@Zhirnoff to minimize

**Comment by AlexeyGirin** [comment]
Moved to Refined backlog as per @vanoprenko decision
