### ISSUE TITLE
After Undo/Redo actions Enter repeats these actions.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4338]
**Steps to Reproduce**
1.Macro mode
2. Sequence mode >> RNA >>add AAATTT >> DNA >> add AAATTT >> Peptides >>add AAATTT
3. Undo several times >> Enter several times.
4. Redo several times >> Enter several times.

https://github.com/epam/ketcher/assets/161723514/46752b31-6e8e-43c3-9d28-a7794c27b152

Sometimes after that duplicate of letters might be appear.

https://github.com/epam/ketcher/assets/161723514/e486629d-0a8c-4e61-a306-439e2719ba2b

**Actual behavior**
 After Undo/Redo actions for editing mode Enter repeats these actions.

**Expected behavior**
After Undo/Redo actions for editing mode Enter should not repeat these actions.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.20.0-rc.1]

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since not fixed over 1 release

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 3.20.0-rc.1 Build at 2024-12-31; 12:50:08
- Indigo Toolkit Version 1.28.0-rc.1.0-gc167e6266-wasm32-wasm-clang-19.0.0
- Chrome Version Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
