### ISSUE TITLE
Macro: When adding new nucleotides to the beginning of a row, the order of the chains changes in the Sequence mode

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4340]
**Steps to Reproduce**
1.	Switch to the Macro mode - Sequence mode
2.	Add any four chains to the canvas (for example, AAA, TTT, UUU, CCC)
![image](https://github.com/epam/ketcher/assets/26869421/5c0f3cc5-9be4-4f05-9970-f4aff3adf33d)
3.	At the very beginning of the second chain, enter U
![image](https://github.com/epam/ketcher/assets/26869421/1fecdae7-d1d3-4c06-801a-7b357696939f)

**Actual behavior**
If you add at least one new nucleotide at the very beginning of the second or any subsequent chain (but not the first or the last), the chains randomly change places (the second takes the place of the third, and the third takes the place of the fourth)
Also, 
The same behavior is observed when at the very beginning of the chain we insert a copied fragment.
![image](https://github.com/epam/ketcher/assets/26869421/18cddb79-efb8-406e-b118-d27a67b5b986)

**Expected behavior**
When adding new nucleotides at the very beginning of any chain, the chains are not swapped
![image](https://github.com/epam/ketcher/assets/26869421/4c05f0bb-9019-42bd-b762-c0821a438fc0)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (122.0.6261.112) x64

**Ketcher version** 2.20.0-rc.1

Issue found while testing https://github.com/epam/ketcher/issues/3650

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/7a34a874-473d-4135-a44b-de0467a74cf5

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by Zhirnoff** [comment]
Test automated.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/b0dde752-b07b-4ee3-84cf-d113e50f9c56)

 - Indigo Toolkit Version 1.21.0-dev.3.0-g6f55c664-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-20; 05:30:45
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
