### ISSUE TITLE
Macro: Selection does not work in sequence editing with Shift+Up/Down arrow combination

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4349]
**Steps to Reproduce**
1. Switch to Macro mode - > Sequence mode
2. Add any sequence to canvas
3. Right click on sequence and select 'Edit sequence'
4. Select sequence with Shift+Up/Down arrow combination

**Actual behavior**
Selection does not work in sequence editing with Shift+Up/Down arrow combination as described in https://github.com/epam/ketcher/issues/3819
At the moment, only the Shift+left/right arrow combinations work, which is not convenient when editing large sequences

**Expected behavior**
Selection works in sequence editing mode with Shift+Up/Down arrow combination

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.20.0-rc.2]

**Video**

https://github.com/epam/ketcher/assets/62464241/2a8446c4-7ac7-4d4f-ad26-d92fe9549d38

**Comment by AlexeyGirin** [comment]
As per @vanoprenko reaction

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since not fixed over 1 release

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/142adb10-fcb0-46a0-84a5-cf4b1fb2236b

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.1.0-rc.2]
**Indigo version** 
[Version 1.29.0-rc.1]
