### ISSUE TITLE
Macro: Selection remains at the ends of created sequences

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4351]
**Steps to Reproduce**
1. Switch to Macro mode - > Sequence mode
2. Add any sequences to canvas ( start each new sequence with the enter button )
3. Select sequences with Rectangle selection and without releasing left mouse button return to starting position

**Actual behavior**
Selection remains at the ends of created sequences
![2024-03-27_19h13_48](https://github.com/epam/ketcher/assets/62464241/fb96b619-1bbe-4bf6-8a42-082201d4c24d)

**Expected behavior**
Selection does not remain at the ends of created sequences

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.20.0-rc.2]

**Comment by Zhirnoff** [comment]
The bug is no longer reproduced on the versions:

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.3]
**Indigo version** 
[Version 1.22.0-rc.3]

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/5f591375-c521-4265-ba1c-47b73e96815d)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)
