### ISSUE TITLE
FASTA: Load FASTA or Sequence file that contains few monomers causes their overlaping on the canvas

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4355]
**Steps to Reproduce**
1. Macromolecules mode
2. Open following FASTA file as RNA: [Load FASTA or Sequence file that contains few monomers causes their overlaping on the canvas.zip](https://github.com/epam/ketcher/files/14780775/Load.FASTA.or.Sequence.file.that.contains.few.monomers.causes.their.overlaping.on.the.canvas.zip)

**Actual behavior**
System put on the canvas sequence elements that overlaps each other
![image](https://github.com/epam/ketcher/assets/26869421/9fbf40f1-24e8-4e48-9981-ebe91ddf6087)

**Expected behavior**
All nucleosides are distributed on the canvas without overlaping
![image](https://github.com/epam/ketcher/assets/26869421/8118ef51-fc4d-48cb-8343-af456fe777ae)

Related
- https://github.com/epam/Indigo/issues/1755
- https://github.com/epam/ketcher/issues/4280

**Environment details:**
[Version 2.20.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-03-27; 08:30:51
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1

Win10
Chrome Version 122.0.6261.129 (Official Build) (64-bit)

**Comment by NataliaLoginova** [comment]
The issue has to be fixed in Indigo.
The issue was created [Indigo incorrectly calculates RNA coordinates with data from FASTA/Sequence file](https://github.com/epam/Indigo/issues/1910)

**Comment by baranovdv** [comment]
Issue fixed in Indigo by this PR:
https://github.com/epam/Indigo/pull/1924

**Comment by AlexeyGirin** [comment]
Moved to Indigo - https://github.com/epam/Indigo/issues/1910

**Comment by NadezhdaPeskun** [comment]
Verified as fixed on RC 
[Version 2.21.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)



[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-rc.2.0-g111a89f35-wasm32-wasm-clang-12.0.0

**Comment by NadezhdaPeskun** [comment]
[Version 2.21.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-05-07; 12:32:44
[Feedback](http://lifescience.opensource.epam.com/ketcher/#feedback)
[EPAM Life Sciences](http://lifescience.opensource.epam.com/)

[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-rc.2.0-g111a89f35-wasm32-wasm-clang-12.0.0
