### ISSUE TITLE
Macro: Clear canvas button doesn't work in Sequence mode

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4356]
**Steps to Reproduce**
1. Switch to Macro
2. Put any monomer on the canvas
![image](https://github.com/epam/ketcher/assets/26869421/6b91df7b-1120-4ae7-a39e-b45f7206f700)
3. Switch to Sequence mode
4. Press Clear Canvas button

**Actual behavior**
Nothing happens
![image](https://github.com/epam/ketcher/assets/26869421/9543fcba-233b-4cb5-a6d6-0e1a7f1b77aa)

**Expected behavior**
System cleans the canvas
![image](https://github.com/epam/ketcher/assets/26869421/973b337a-ccfa-4b9a-ba8c-0b1bec3f9700)

**Versions** [e.g. v2.4.2]. 
 - Indigo Toolkit Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc2 Build at 2024-03-27; 08:30:51
 - Chrome Version 122.0.6261.70 (Official Build) (64-bit)
 - Win10

**Comment by NadezhdaPeskun** [comment]
Verified as fixed for CI Version
2.21.0-rc.1 Build at 2024-04-26
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-dev.1.25-gafde2b35-wasm32-wasm-clang-12.0.0

OS: Windows 11
Browser Chrome
Version 112.0.5615.138 (Official Build) (64-bit)
