### ISSUE TITLE
Macro: RNA builder should be highlighted in Edit mode. Canvas should be disabled. 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4374]
**Background**
When user starts modifying a group nucleotides on canvas using RNA-builder, they should see a clear indication of specific editing mode (different from regular modification of presets in the monomer library) and that other editing operations on canvas are disabled while group editing is in progress.  

**Requirements** 

1. Once RNA builder switches to Edit mode (See [#3824](https://github.com/epam/ketcher/issues/3824) ), the RNA builder iteslf and the selection being edited should be highlighted with a specific color (see mockups). 
2. All monomers on canvas except those being modified should be grayed/faded out to reflect disabled state.
3. Selection and right-click menu operations on canvas should be disabled while editing is in progress.

**UX**
![image](https://github.com/epam/ketcher/assets/143799055/17aa2840-0173-4c83-9388-42073c19f192)
![image](https://github.com/epam/ketcher/assets/143799055/67960bd8-5764-4ab1-bea2-b53dc5562aef)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/b03d91d6-f67a-4f29-931e-c397feb8c721)

**Versions:**
Windows 10
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0
