### ISSUE TITLE
Macro: Pressing Del key should delete selection but not switch Erase tool on

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4376]
**Steps to Reproduce**
1. Switch to the Macro mode
2. Add chains two any monomer and connect them with bond
![image](https://github.com/epam/ketcher/assets/26869421/1aae5b66-107a-4d19-a4c8-0fddac00272a)
3. Select bond and press Del key
![image](https://github.com/epam/ketcher/assets/26869421/3829f062-ab6b-4d96-ad56-16cb371baf20)

**Actual behavior**
System removes bond and switch Erase tool on
![image](https://github.com/epam/ketcher/assets/26869421/ae0f4a01-f0a7-4649-857a-2037c75c954c)

**Expected behavior**
System removes bond and keeps tool selection unchanged
![image](https://github.com/epam/ketcher/assets/26869421/59fa12ac-7175-4c75-adb0-3987be74e488)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome Version: (122.0.6261.112) x64
 - Ketcher version 2.20.0-rc.2 Build at 2024-03-27; 08:25:13
 - Indigo Toolkit Version 1.19.0-rc.2.0-g6c0e3fecf-wasm32-wasm-clang-12.0.0

**Comment by mate-meszaros-epam** [comment]
Can not be reproduced.

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0
