### ISSUE TITLE
Macro: Display IDT aliases in monomer library

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4380]
IDT aliases, where defined, should be displayed in the preview window for RNA monomers, CHEMs and presets in monomer library.

Same elements on canvas are out of scope.

UX 
![image](https://github.com/epam/ketcher/assets/141816460/50a38c57-0119-45a7-856f-f277dd4d4d0d)

**Comment by Zhirnoff** [comment]
Test added to the automation table.

**Comment by NataliaLoginova** [comment]
IDT has to be taken from field idtAliases in monomers.ket
![image](https://github.com/epam/ketcher/assets/13768926/22e261b6-ae14-442f-be7e-2f152ca1e7e0)
Everything that is in the modifications field should be displayed, or if there are no modification field, then display the base field.

**Comment by NataliaLoginova** [comment]
Preview has to be added for Presets in RNA.
It should look like Preview in canvas in sequence mode.
![image](https://github.com/epam/ketcher/assets/13768926/65ace315-554d-4165-afab-a0ca9d62f7cc)

**Comment by NataliaLoginova** [comment]
IDT aliases should be in the root of object for presets
![image](https://github.com/epam/ketcher/assets/13768926/4e185cdc-2328-4f48-941f-3409b325bed6)

**Comment by Zhirnoff** [comment]
Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
