### ISSUE TITLE
Macro: Clear canvas button doesn't work

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4381]
Follow up from - https://github.com/epam/ketcher/issues/4356

**Steps to Reproduce**
1. Switch to Macro

**Actual behavior**
Clear canvas button is enabled but not functional
![image](https://github.com/epam/ketcher/assets/26869421/304a7610-4ba6-4630-b73f-d95737000d21)

**Expected behavior**
Clear canvas button should work as intended in Sequence mode
(As temporary solution - we disable it in 2.20 in the context of https://github.com/epam/ketcher/issues/4356)

**Versions** [e.g. v2.4.2]. 
 - Indigo Toolkit Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc2 Build at 2024-03-27; 08:30:51
 - Chrome Version 122.0.6261.70 (Official Build) (64-bit)
 - Win10

**Comment by Zhirnoff** [comment]
Tested on build 2.21.0-rc.1. No longer reproduces.
https://github.com/epam/ketcher/assets/62464241/e0da0737-9406-4e34-bb0c-e0e94e1b0636

**Comment by AlexeyGirin** [comment]
Verified.
Windows 10
Chrome Version Version 124.0.6367.119 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.2 Build at 2024-05-07; 12:32:44
Indigo Toolkit Version 1.20.0-rc.2.0-g111a89f35-wasm32-wasm-clang-12.0.0
![image](https://github.com/epam/ketcher/assets/26869421/29e4deb1-5a97-41e7-b347-ee54b9490599)
