### ISSUE TITLE
Macro: Support of unsplit nucleotides 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4382]
**Background**
In some cases there is no need to divide modified nucleotides to submonomers (sugar, base, phosphate). Such nucleotides should be supported as single monomers. 

**Requirements**
1. Unsplit nucleotides are nucleotides which have chemical structure, but submonomers (sugar, base, phosphate) are not specified
2. Additional chapter 'Nucleotides' should be introduced in a RNA tab of Ketcher library 
3. Unsplit nucleotides should have base natural analog
4. Unsplit nucleotides should be grouped by natural analog in a library. 
          -   Nucleotides, for which a natural analogue is not specified, should be grouped in a separate section in a library ("No natural analogue")

5. Unsplit nucleotides should not interrupt enumeration of RNA chain in flex mode 
6. Unsplit nucleotides should be displayed: 
      - in flex/snake modes - as a pentagon with name (see mockups)
      - in sequence view - as natural analog symbol if it's specified, otherwise - as '@' symbol
    
7. On preview chemical structure together with name and IDT alias should be displayed. 
8. Establishing connections between unsplit nucleotides should be performed as for peptide monomers (center-to-center, center-to-point , point-to-center, point-to-point).

**Examples**
[Unsplit_nucleotides.zip](https://github.com/user-attachments/files/15570968/Unsplit_nucleotides.zip)
[iAmMC6T.zip](https://github.com/user-attachments/files/15844193/iAmMC6T.zip) - has 4 AP

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">

</head>

<body>

IDT   name | Full   name | Natural   analog
-- | -- | --
/5Super-dG/ | 5' Super G | G
/55Br-dU/ | 5' 5-Bromo dU | U
/5Super-dT/ | 5' Super T | T
/55HydMe-dC/ | 5' 5-Hydroxymethyl dC | C
/55NitInd/ | 5' 5-Nitroindole | X
/5AmdA/ | 5' 2, 6-Diaminopurine | A
/iAmMC6T/| Int Amino Modifier C6 dT| T

</body>

</html>

    
**UX**
![image](https://github.com/epam/ketcher/assets/141816460/89aa7828-ee50-4a12-b237-200c0d16e486)

**Comment by olganaz** [comment]
Attached files with examples suitable for testing

**Comment by olganaz** [comment]
1. Added the requirement
2. separate group in library
3. TBC

**Comment by Zhirnoff** [comment]
Tested.
We have many bugs described above
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]
