### ISSUE TITLE
Macro: Allow Nucleoside of sequence edit in  RNA builder 

### ISSUE THREAD

**Issue by ilya-asiyuk-epam** [epam/ketcher#4388]
**Background**
Nucleotide = RNA preset added on canvas (sugar+phosphate+base)
Nucleoside = sugar+base, connected by the bond between R3 AP of sugar and R1 AP of base.

**Requirements**
In addition to the requirements from [#3824](https://github.com/epam/ketcher/issues/3824)
1. Nucleoside should be editable in RNA builder. 
2. If a single nucleoside is loaded into RNA builder, then the "Phosphate" field in the RNA builder should be empty.
3. If user adds phosphate to the RNA builder, then a nucleoside should become a nucleotide with corresponding phosphate.
4. Bulk modifications of nucleotides and nucleosides simultaneously: 
      - Instead of field 'name your structure',  'N nucleotides selected' should be displayed (N- the number of nucleotides and nucleosides)
      - In the 'phosphate' field - [multiple] should be displayed
      - Phosphate modifications should be applied to both nucleotides and nucleosides. 
5. If nucleoside is selected together with following it phosphate, then this combination should be considered as nucleotide AND   phosphate modifications made in RNA builder should be applied to the selected phosphate. 
Image for better understanding (don't look at color scheme)
![image](https://github.com/epam/ketcher/assets/143799055/b0abb845-a05a-4ed4-988c-e781d64d0537)

6. If among the selected elements on the canvas there is a single phosphate (selected without an adjacent nucleoside to the left), then in this case, editing in the builder should be prohibited.
![image](https://github.com/epam/ketcher/assets/143799055/8817daad-d069-49ad-9587-88fbc9387bd7)

**Comment by Zhirnoff** [comment]
Tests added to automation table.

**Comment by AlexeyGirin** [comment]
Verified.

**Versions**
 - Indigo Toolkit Version 1.20.0-dev.1.32-gf28bad61-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-13; 05:32:02
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
