### ISSUE TITLE
In the Sequence mode, the tooltip “Start new sequence” is shown outside of the canvas

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4394]
**Steps to Reproduce**
1.	Switch to the Macro mode - the Sequence mode
2.	Right-click on the header, the toolbar and the “Library” panel

**Actual behavior**
The tooltip “Start new sequence” is displayed outside the canvas
<img width="194" alt="image" src="https://github.com/epam/ketcher/assets/139227567/4feaab06-9666-4b31-9ad1-25ccdb1dad77">

<img width="130" alt="image" src="https://github.com/epam/ketcher/assets/139227567/0e58596d-f52e-4984-ac60-8693ee3ada12">

<img width="382" alt="image" src="https://github.com/epam/ketcher/assets/139227567/73a428c8-5189-4947-a3cc-279590bfadcf">

**Expected behavior**
The tooltip “Start new sequence” is displayed only when clicking on the canvas

**Screenshots**
![2024-04-02_15h11_56](https://github.com/epam/ketcher/assets/139227567/35f7e3d1-837b-4b7d-acaa-d3b81a6aa6f8)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (123.0.6312.86) x64

**Ketcher version** 2.20.0-rc.2

#188320047

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since not fixed over 1 release
