### ISSUE TITLE
Macro: System shows "p" in sequence mode when it shouldn't 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4398]
**Steps to Reproduce**

1. Switch to Macro
2. Load from file: [No need to show p.zip](https://github.com/epam/ketcher/files/14850068/No.need.to.show.p.zip)
3. Switch to Sequence mode
![image](https://github.com/epam/ketcher/assets/26869421/c57d2047-8b6b-47ee-9a78-5bfc31276398)

**Actual behavior**
System shows "p" for first phosphate in chain but it relates for first nucleotide
![image](https://github.com/epam/ketcher/assets/26869421/1015fb93-102d-45d7-8509-800ac62ec597)

**Expected behavior**
System doesn't shows p
![image](https://github.com/epam/ketcher/assets/26869421/ddd61c1b-bed4-446c-a742-5a8026ce7c5b)

As per [specification](https://github.com/epam/ketcher/issues/3734):

>**If there is a linker that contains multiple sugars or some other combination of modified subunits (non-nucleotide), the entire block can be represented with a '@' symbol.**
>**Image for better understanding:**

![301212531-97da3f28-d642-478a-ab5a-5688b0722ddb](https://github.com/epam/ketcher/assets/26869421/d174ae78-78c4-43c1-a242-4b276be36f8e)

**Versions:**
Windows 10
Chrome Version 112.0.5615.138 (Official Build) (64-bit)
Ketcher Version 2.20.0-rc.2 Build at 2024-04-02; 05:31:05
Indigo Toolkit Version 1.20.0-dev.1.19-gd0224f91-wasm32-wasm-clang-12.0.0

Issue found in the context of testing - https://github.com/epam/ketcher/issues/3734

**Comment by rrodionov91** [comment]
Will be fixed in https://github.com/epam/ketcher/issues/4388

**Comment by AlexeyGirin** [comment]
Fixed.
**Versions**
 - Indigo Toolkit Version 1.20.0-dev.1.32-gf28bad61-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-13; 05:32:02
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
