### ISSUE TITLE
Preview: Different chains shown by the same sequence in sequence mode (system ignores sugar presence)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4399]
**Steps to Reproduce**

1. Switch to Macro
2. Load from file: [Different chains show by the same sequence in sequence mode (system ignores sugar presence).zip](https://github.com/epam/ketcher/files/14851697/Different.chains.show.by.the.same.sequence.in.sequence.mode.system.ignores.sugar.presence.zip)
3. Switch to Sequence mode
![image](https://github.com/epam/ketcher/assets/26869421/c15b2f8d-3fea-470c-863b-ea5b826e5189)

**Actual behavior**
Different chains shown by the same sequence
![image](https://github.com/epam/ketcher/assets/26869421/afecfc76-3db2-42e1-a0e0-931b2e6bae8b)

**Expected behavior**
 - Nucleotide without phosphate = nucleoSide
 - NucleoSide in the middle of the chain should be marked similar to nucleotide with modified phosphate (up-right circle), but with white fill.
 -  Last nucleoSide  shouldn't be marked.

See mockup
![image](https://github.com/epam/ketcher/assets/26869421/c15b2f8d-3fea-470c-863b-ea5b826e5189)  
<img width="130" src="https://github.com/epam/ketcher/assets/143799055/43bce457-404e-43e2-ab4c-c4c53491a7b7">

Approved by @AlexanderSavelyev and @vanoprenko 

**Versions:**
Windows 10
Chrome Version 112.0.5615.138 (Official Build) (64-bit)
Ketcher Version 2.20.0-rc.2 Build at 2024-04-02; 05:31:05
Indigo Toolkit Version 1.20.0-dev.1.19-gd0224f91-wasm32-wasm-clang-12.0.0

Issue found in the context of testing - https://github.com/epam/ketcher/issues/3734

**Comment by AlexeyGirin** [comment]
@olganaz please document decision somewhere

**Comment by olganaz** [comment]
Updated expected behavior, added mockup.

**Comment by AlexeyGirin** [comment]
Verified.
Windows 10
Chrome Version 125.0.6422.113 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.2 Build at 2024-05-31; 10:48:44
Indigo Toolkit Version 1.21.0-dev.5.2-g994bdab98-x86_64-linux-gnu-11.2.1

![image](https://github.com/epam/ketcher/assets/26869421/00a9cac0-0901-45fe-b62f-e7f2c3216a85)
