### ISSUE TITLE
The structure with non-default periodic table atoms rendering incorrectly after saving in inchi format 

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#44]
**Steps to reproduce**

1. Launch application
2. Create any structure, for example, chain.
3. Open Periodic table.
4. Select Calcium, click OK.
5. Click any non-terminal structure atom.
6. Click "Save as" button.
7. In the "Format" field select inchi. Click "Save to file" button.
8. Clear the canvas.
9. Open saved in 7th step file.

**Actual result**
The structure is broken, some atoms are replaced with radicals.
![image](https://user-images.githubusercontent.com/7427808/92369134-469a4c80-f101-11ea-8954-63f1d402b2cf.png)

If there are several non-carbon atoms at the structure, the structure is broken into several structures:
![image](https://user-images.githubusercontent.com/7427808/92369160-4ef28780-f101-11ea-9b06-1980cc6e76b5.png)

**Expected result**
The structure should open after saving in the same form as it was created.

**Comment by AndreiMazol** [comment]
@AlexanderSavelyev  

Current save flow is following:

1. Structure is drawn in editor
2. Structure is passed to the server to  be converted into  inchI format
3. Result file is saved on client side.

Current open flow is following:

1. Saved file is chosen to be uploaded
2. Saved file is transferred to  the server
3. On server side file is converted from inchI to mol
4. Resulted mol file passed to Ketcher to be rendered

Expected result:
mol file is correct.

Actual result:
structure saved in mol file is differ from original one

Based on  above it is necessary to have a look on server side in particular transformation flow.

**Comment by IuriiPuzanov** [comment]
In accordance with InChI technical manual the standard InChI doesn't include bonds with "metal" atoms:

> In an effort to deal with the various different conventions used for drawing organometallic
> compounds, all metal atoms are disconnected in the main layer. In the process, the charges for
> disconnected F, Cl, Br, I, At, O, S, Se, Te, N, P, As, B are adjusted if possible by transferring
> charge to the metal atom.
> The user may request to add a “reconnected” layer that generates an InChI that contains all
> bonds given in the input structures. A disconnected “salt” (step 2 above) cannot be reconnected
> this way.
> At this point rules from Table 2 are applied (second time) to the disconnected structure.

So we need to use non-standard InChI for such cases.

**Comment by AndreiMazol** [comment]
@AlexanderSavelyev  can we close this issue or it should be transferred to Indigo repository?

**Comment by AlexanderSavelyev** [comment]
I guess the issue can be closed, since it is InChi specific format behavior.
