### ISSUE TITLE
Autotests: Displaying modified nucleotide chains in sequence representation

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4406]
**Source task(s):**
 - https://github.com/epam/ketcher/issues/3734

**Description:**
These bunch of tests validates that system correctly display modified nucleotide chains in sequence representation

### Test case 1:
1. Switch to Macromolecules view
2. Load from file (unzip first): [1. All types of modifications.zip](https://github.com/epam/ketcher/files/14858595/1.All.types.of.modifications.zip)
3. Switch to Sequence mode
4. Validate canvas

### Test case 2:
1. Switch to Macromolecules view
2. Load from file (unzip first): [2. All types of connection between CHEM and RNA.zip](https://github.com/epam/ketcher/files/14858610/2.All.types.of.connection.between.CHEM.and.RNA.zip)
3. Switch to Sequence mode
4. Validate canvas

### Test case 3:
1. Switch to Macromolecules view
2. Load from file (unzip first): [3. All types of connection between Sugar and RNA.zip](https://github.com/epam/ketcher/files/14858617/3.All.types.of.connection.between.Sugar.and.RNA.zip)
3. Switch to Sequence mode
4. Validate canvas

### Test case 4:
1. Switch to Macromolecules view
2. Load from file (unzip first): [4. All types of connection between Base and RNA.zip](https://github.com/epam/ketcher/files/14858619/4.All.types.of.connection.between.Base.and.RNA.zip)
3. Switch to Sequence mode
4. Validate canvas

### Test case 5:
1. Switch to Macromolecules view
2. Load from file (unzip first): [5. All types of connection between Phosphate and RNA.zip](https://github.com/epam/ketcher/files/14858621/5.All.types.of.connection.between.Phosphate.and.RNA.zip)
3. Switch to Sequence mode
4. Validate canvas

**Comment by Zhirnoff** [comment]
Automated.
