### ISSUE TITLE
Macro: Store custom presets in browser local cache

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4427]
Custom presets should be stored in browser's local cache and restored in the monomer library on Ketcher restart.

In case certain preset loaded from the cache conflicts with another preset loaded from the library (has the same name), its name should be modified by adding "_Copy" to the end. The new name should be validated again and if still not unique, yet another postfix to be added, etc. Preset with updated name should replace the original one in browser cache.

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.20.0-dev.1.32-gf28bad61-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-13; 05:32:02
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
