### ISSUE TITLE
Inconsistence for nucleotides Letters in the Sequence mode 

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4430]
**Steps to Reproduce**
1. Switch to the Macro mode 
2. Open Sequence mode
3. Open KET file with modified nucleotides 
[ketcher (CCPC).zip](https://github.com/epam/ketcher/files/14885158/ketcher.CCPC.zip)
4. see tooltips

**Actual behavior**
Letters have identical markers ("C") but different links and tooltips.
Without Phosphate in the middle of the chain
![image](https://github.com/epam/ketcher/assets/161723514/6e7d8059-358e-4418-9efe-5d4bd0ea22d5)

With Phosphate in the middle of the chain
![image](https://github.com/epam/ketcher/assets/161723514/81a38fbc-49e9-4d05-af7c-722a99664f28)

With Phosphate in the end of the chain
![image](https://github.com/epam/ketcher/assets/161723514/a950634a-4e0a-42d0-8bb7-01fea0748041)

**Expected behavior**
Letters have identical markers ("C") should have the same links and tooltips.
Nucleotide **without** Phosphate would be nice to mark separately (White point, from BA). 

Related:
- https://github.com/epam/ketcher/issues/3734

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (123.0.6312.86) x64
 
[Version 2.20.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-04-05; 05:31:45

[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-dev.1.20-gfe00419b-wasm32-wasm-clang-12.0.0

**Comment by AlexeyGirin** [comment]
Duplicates https://github.com/epam/ketcher/issues/4399
