### ISSUE TITLE
Support unresolved IDT monomers (no structure, IDT only) 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4431]
**Background**
If user imports modified RNA in IDT notation which contains monomers not found in Monomer library, this should not be interpreted as an error. Such monomers should be displayed inside the sequence, user should be able to do some base operations with them (delete, connect to and disconnect from other monomers). There should be possible to load such monomers from IDT and KET formats and save to these formats.  
User should be able to establish bonds with monomers with unknown structure
AP - attachment point

**Requirements**
1. Display on canvas:
    - in flex/snake modes - as a "black box" (see mockups)
    - in sequence mode - as '?'
2. Preview on hover should contain IDT alias only
3. Attachment points
    - 4 attachment points should be available for this type of monomers: R1/R2 - backbone (default connection), R3/R4 - sidechain
4. Attempt to save macromolecules with unknown monomers to file formats other than IDT and KET should result in error.
"Monomer /.../ couldn't be saved to .... format"
5. Establishing of bonds
       - Modal window for AP selection should be displayed anytime when user establishes bond with unknown monomer.
       - This window should allow to select appropriate attachment point, but no structure should be displayed for unknown monomer (see mockups).

**UX**
![image](https://github.com/epam/ketcher/assets/141816460/fe0ee1b2-19a4-4384-a380-a6a3bf4bbc30)

**Comment by AlexeyGirin** [comment]
Questions to @olganaz 

1. there in sequence mode - these unknown monomers are displayed as a question mark
Does this mean that we can enter a question mark when editing?
or just delete it?
2. here we had an unknown monomer
And than - ka-boom! - it became known
and it has two attachment points
and we - while it was unknown - connected it with all four
What will happen?
3. Can we make the monomer known through RNA builder?

**Comment by Zhirnoff** [comment]
Questions to @olganaz
4. What error message should be displayed when attempting to save macromolecules with unresolved monomers in formats other than IDT and KET?
5. What specific data and fields must be included when saving unresolved monomers in KET (eg, IDT alias, join points, leaving group)?
6. Should position indicators in IDT format be included along with the IDT alias?

**Comment by olganaz** [comment]
1. Currently we are just displaying that kind of monomers. Question mark could be deleted, but couldn't be added in sequence mode. 
2. Ka-boom won't happen, as we don't have such functionality. 
3. Not now.
4. "Monomer /.../ couldn't be saved to .... format. 
5. Better to ask Indigo
6. No, in IDT format we save only a string with IDT names.

**Comment by AlexeyGirin** [comment]
Verified.

![image](https://github.com/epam/Indigo/assets/26869421/9977963b-4b51-421b-b6ce-ad56fb50520e)

Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
Indigo Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
Win 10
Chrome Version 126.0.6478.127 (Official Build) (64-bit)
