### ISSUE TITLE
There is no bond in the Sequence mode.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4439]
**Steps to Reproduce**
1. Switch to the Macro mode 
2. Open KET file with modified nucleotides 
[ketcher (44).zip](https://github.com/epam/ketcher/files/14908610/ketcher.44.zip)
![image](https://github.com/epam/ketcher/assets/161723514/eed78a78-6ecf-4ae7-ad37-13ec61c37067)

3. Open Sequence mode

**Actual behavior**
There is no bond in the Sequence mode.
![image](https://github.com/epam/ketcher/assets/161723514/e44dc5cb-9e11-4699-ad4a-2572b4651ed5)

**Expected behavior**
The bond should be represented in the Sequence mode.
![image](https://github.com/epam/ketcher/assets/161723514/b604ba37-cf8c-48f2-ae8d-c7c9e7319820)

Related:
- https://github.com/epam/ketcher/issues/3734
- https://github.com/epam/ketcher/issues/4438

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (123.0.6312.86) x64
 
[Version 2.20.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-04-08; 05:30:10

[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-dev.1.20-gfe00419b-wasm32-wasm-clang-12.0.0

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since not fixed over 1 release

**Comment by rrodionov91** [comment]
Looks like fixed. @AlexeyGirin  please check

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-12-06_11h51_06](https://github.com/user-attachments/assets/f40633c6-4966-4d2e-bce1-10158585838b)
![2024-12-06_11h52_45](https://github.com/user-attachments/assets/4617db3d-6e8c-4577-8360-bbdb4acf951e)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
