### ISSUE TITLE
'Update sequence' modal window: don't close RNA-builder after pressing 'Cancel' in modal window. 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4454]
**Steps to Reproduce**
1. Go to 'Macromolecules' -> Sequence mode
2. Add any RNA sequence on canvas 
3. Select multiple nucleotides 
4. Rclick- -> modify in RNA builder --> select any phosphate or base or phosphate in RNA-builder 
5. Press 'Apply' -> "Update Sequence" modal window appears
6. Press 'Cancel' in modal window

**Actual behavior**
After clicking 'Cancel' button in 'Update Sequence' modal window 
        - all the changes made in RNA builder do not apply to the selected nucleotides, 
        - RNA builder collapses, 
        - nucleotides remain selected. 
![image](https://github.com/epam/ketcher/assets/143799055/fdeda790-2433-4b30-95a6-74d79d710a3b)
![image](https://github.com/epam/ketcher/assets/143799055/193a9456-5d53-44db-aa7e-4cfd7f058ec8)

**Expected behavior**
After clicking 'Cancel' button in 'Update Sequence' modal window 
        - all the changes made in RNA builder do not apply to the selected nucleotides, 
        - RNA **remains in current state** (with filled fields 'Sugar', "Base', "Phosphate'), 
        - nucleotides remain selected. 
![image](https://github.com/epam/ketcher/assets/143799055/25e98ade-a945-4249-a65f-9c0a92fca129)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 

**Ketcher version** [e.g. v2.4.2]. 
[Version 2.19.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-04-09; 09:32:33

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/ketcher/assets/26869421/70cd9129-da6b-4631-8fb5-d7cf9763ce0c)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0
