### ISSUE TITLE
'Update sequence' modal window: display the number of nucleotides to be changed 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4455]
**Steps to Reproduce**

1. Go to 'Macromolecules' -> Sequence mode
2. Add any RNA sequence on canvas
3. Select multiple nucleotides
4. Rclick- -> modify in RNA builder --> select any phosphate or base or phosphate in RNA-builder
5. Press 'Apply' -> "Update Sequence" modal window appears

**Actual behavior**
Notification: "You are going to make multiple changes in your sequence. Are you sure?" is displayed in modal window. 

**Expected behavior**
Notification should be changed to: "You are going to modify **N** nucleotides. Are you sure?"
Where **N** - the number of nucleotides being modified

**Screenshots**
![image](https://github.com/epam/ketcher/assets/143799055/fe6ffab6-4fa0-4bd6-9d32-43b10ab8f3f6)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version

**Ketcher version** 
[Version 2.19.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-04-09; 09:32:33

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/ketcher/assets/26869421/eef526cc-823c-4bc0-bc4e-cbe9a9251778)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0
