### ISSUE TITLE
Any click on toobar buttons should cause cancel of "Modify in RNA builder" process 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4470]
**Steps to Reproduce**

1. Switch to Macro
2. Open from file: [Sample sequence.zip](https://github.com/epam/ketcher/files/14997916/Sample.sequence.zip)
3. Select few nucleotides and edit them in RNA builder (via context menu)
![image](https://github.com/epam/ketcher/assets/26869421/d81150d2-8b96-4f29-b166-ebc29874919c)
5. Press Clear canvas button

**Actual behavior**
Canvas got empty but RNA builder remain in edit mode
![image](https://github.com/epam/ketcher/assets/26869421/d442d24c-1d7c-468f-b8c8-f797f4cb4e30)

**Expected behavior**

1. System closes "Modify in RNA builder" mode and than process with Clear canvas button

![image](https://github.com/epam/ketcher/assets/26869421/d6dc6a4d-ac84-4c13-8861-b8d34b74355a)

2. System disables "Open..." button, "Type" selector in Top bar while sequence is in 'Edit in RNA Builder' mode

3. Systems does not allow new element via API (ketcher.addFragment, ketcher.setMolecule) while sequence is in 'Edit in RNA Builder' mode

**Versions:**
Windows 10
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0

Issue found while testing https://github.com/epam/ketcher/issues/4374

**Comment by Zhirnoff** [comment]
The issue has been moved from 2.21.0-rc.2 to 2.22.0-rc.1 after discussion with management and in accordance with the testing flow process.

**Comment by ilya-asiyuk-epam** [comment]
I think there are 3 elements that we need to handle in this bug.

<img width="1190" alt="modify in rna builder" src="https://github.com/epam/ketcher/assets/156656634/41d83ad9-de73-446b-a3cf-77aaec171225">

cc: @AlexeyGirin , @rrodionov91

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.21.0-dev.3.0-g6f55c664-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-20; 05:30:45
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
