### ISSUE TITLE
Autotests: RNA builder should be highlighted in Edit mode. Canvas should be disabled

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4472]
**Source task(s):**
 - https://github.com/epam/ketcher/issues/4374

**Case 1**
1. Load from file: [All types of possible modifications.zip](https://github.com/epam/ketcher/files/14998609/All.types.of.possible.modifications.zip)
2. Select nucleotide as shown on the picture:
![image](https://github.com/epam/ketcher/assets/26869421/8c9b84fc-b4d4-4c66-bff2-07ff13a53639)
3. Validate canvas
4. Call Modify in RNA builder for selected nucleotides
5. Validate canvas
![image](https://github.com/epam/ketcher/assets/26869421/52ff2a16-60f1-4070-b0a3-a5f967b818bb)

**Comment by Zhirnoff** [comment]
Automated.

**Comment by Zhirnoff** [comment]
Automated.
