### ISSUE TITLE
Macro: quick double paste operation from clipboard leads to invalid entities on canvas

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4479]
When user pastes structure to canvas twice with a short interval, this may lead to "broken" canvas with invalid entities (cannot be remove, survive canvas clearing, etc.). The problem easier reproduces on big inserted structures -- assumingley when you try to paste new structure before pasting of previous one is completed.

**Steps to Reproduce**

1. Switch to Macro - Sequence mode - Peptide type
2. Copy to clipboard big enough testx, e.g. the following one: `ACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWYACDEFGHIKLMNPQRSTVWY`
3. Start new sequence (via context menu)
4. Paste text from clipboard on the canvas twice but fast (hold Ctrl key and press V key twice very fast).

**Actual behavior**
System put second sequence as phantom object that is not possible to delete even by clearing the canvas
![image](https://github.com/epam/ketcher/assets/26869421/762236aa-6cef-4612-bbea-33787bd67502)

**Expected behavior**
System doesn't allow to past from clipboard while previous operation is not finished
![image](https://github.com/epam/ketcher/assets/26869421/ad9da3c0-f1d5-49de-ae9b-c815b698b80e)

**Versions:**
Windows 10
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0

Issue found while testing https://github.com/epam/ketcher/issues/3894

**Comment by Zhirnoff** [comment]
The issue has been moved from 2.21.0-rc.2 to 2.22.0-rc.1 after discussion with management and in accordance with the testing flow process.

**Comment by ilya-asiyuk-epam** [comment]
Possible to fix in:
SequenceMode.ts -> applyAdditionalPasteOperations

**Comment by ilya-asiyuk-epam** [comment]
Check 'applyAdditionalPasteOperations' function

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.21.0-dev.3.0-g6f55c664-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-20; 05:30:45
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
