### ISSUE TITLE
Macro: UI support for  IDT import/export

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4495]
**Requirements**

**Open**

Add option "IDT" to the format dropdown menu of modal window 'Open'/'Paste from the clipboard'

**Save As**

Add option "IDT" to dropdown 'File format' of modal window 'Save Structure'

In case of peptide monomers are on canvas, error "Peptide monomers are not supported in IDT" should appear

Backend part:
https://github.com/epam/Indigo/issues/1588
https://github.com/epam/Indigo/issues/1654

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by NadezhdaPeskun** [comment]
We can save as IDT format but cannot that open or Open that from clipboard:
a)
rUrA*rUrA
rUrA*rUrA
rUrA*rUrA 

b) 
rA/3Phos/

c)
rA/3Phos/
rU/3Phos/


![Image](https://github.com/epam/ketcher/assets/161723514/1ad68d44-3e84-4429-9dd5-a3bf59568aa1)

![Image](https://github.com/epam/ketcher/assets/161723514/eeb4e327-7ab0-4fb4-939e-3d0a0d6d6442)
