### ISSUE TITLE
Macro: Highlight remains at the ends of created sequences after press Clear canvas button in sequence-editing view

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4499]
**Steps to Reproduce**
1. Switch to Macro mode - > Sequence mode -> Right-click: Start new sequence
2. Add any sequences to canvas ( start each new sequence with the enter button )
3. Press 'Clear canvas' button

**Actual behavior**
Highlight remains at the ends of created sequences after press Clear canvas button in sequence-editing view

**Expected behavior**
All canvas is cleared.

**Screenshots**
![2024-04-19_14h36_04](https://github.com/epam/ketcher/assets/62464241/d72b0cfa-67d8-4ea3-8880-388c4fd7939c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123.0.6312.106 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.21.0-rc.1]
Issue with same behaviour: https://github.com/epam/ketcher/issues/4351

**Comment by Zhirnoff** [comment]
The bug is no longer reproduced on the versions:

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.3]
**Indigo version** 
[Version 1.22.0-rc.3]

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/3e0f761a-891b-420d-8d65-45ae74fc1d41)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)
