### ISSUE TITLE
Validate format conversion (warning messages)

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#45]
Now warning messages like
'ERROR:SMILES data format doesn't support s-groups' warning should appear.'
*'ERROR:InChi data format doesn't support s-groups.'*don't appear. As example you can see defect
It's necessary to decide:
1. Whether to display the warning message that file will not be saved or do not display it.
2. How to realize it
3. How this verification will be implemented: through the client or the server

[Warnings.zip](https://github.com/epam/ketcher/files/5182328/Warnings.zip)

**Note**

See the attached file with warnings and errors for different actions.

**Note2**
When user enters incorrect data in "Isotope" or "Charge" fields in "Atom Properties" menu, the error message "Error: is not of a type(s) integer" is appears.
It will be better if the message is something like that: "There must be integer".

**Comment by ensemenova** [comment]
@Svetlana-Asinovskaia  Please retest and fix test scenarious accordingly.
1. For first two cases currently the messge 'In ${format} the structure will be saved without S-groups'
2. In case with "Isotope" or "Charge" firelds the message was improved at somepoint
