### ISSUE TITLE
Macro: The system allows you to paste on canvas while modifying nucleotides in the RNA builder

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4501]
**Steps to Reproduce**
1. Switch to Macro mode -> Sequence mode
2. Add any RNA/DNA letters
3. Select two and copy by CTRL+C
4. Select any, right-click and select 'Modify in RNA Builder'
5. Press CTRL+V

**Actual behavior**
The system allows you to paste on canvas while modifying nucleotides in the RNA builder

**Expected behavior**
The system should not allow you to paste on canvas while modifying nucleotides in the RNA builder

**Screenshots/Videos**

https://github.com/epam/ketcher/assets/62464241/1d0b0c1b-5676-4daa-9581-4f5c03fbb123

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 123.0.6312.106 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.21.0-rc.1]

Bug registered after testing: https://github.com/epam/ketcher/issues/3824

**Comment by Zhirnoff** [comment]
The issue has been moved from 2.21.0-rc.2 to 2.22.0-rc.1 after discussion with management and in accordance with the testing flow process.

**Comment by ViktoriaTkacheva** [comment]
The system also allows users to launch the Text-editing mode by pressing the Enter key, where new sequences can be added

![2024-05-07_18h08_06](https://github.com/epam/ketcher/assets/139227567/875f49af-a723-4348-8455-017903dd50bb)

**Comment by AlexeyGirin** [comment]
Verified.
Windows 10
Chrome Version 125.0.6422.142 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.2 Build at 2024-06-03; 05:33:52
Indigo Toolkit Version 1.21.0-dev.5.4-gb45d44aa-wasm32-wasm-clang-12.0.0
