### ISSUE TITLE
Macro: Fragment without available AP can be inserted into the Text-editing mode

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4506]
**Steps to Reproduce**
1.	Open two Ketcher browser tabs – the Macro mode 
2.	Open this file (first unzip)  [Peptides without AP.zip](https://github.com/epam/ketcher/files/15053413/Peptides.without.AP.zip)
3.	Switch to the Sequence mode 
4.	Copy this structure and paste it into the Text-editing mode of another Ketcher browser tab between peptides or nucleotides within the sequence

**Actual behavior**
The structure is inserted and new bonds are formed between it and the structure, that was originally on the canvas

**Expected behavior**
The structure is not inserted. An error message (from BA) appears on the canvas:

Error Message:
It is impossible to merge fragments. Attachment point to establish bonds are not available.

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/78be9294-47da-429c-906b-da5af7c816a7

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.60) x64

**Ketcher version** 2.21.0-rc.1, Build at 2024-04-15; 20:06:01

Issue found while testing 
- https://github.com/epam/ketcher/issues/3916
Related with 
- https://github.com/epam/ketcher/issues/4575

**Comment by Zhirnoff** [comment]
The issue has been moved from 2.21.0-rc.2 to 2.22.0-rc.1 after discussion with management and in accordance with the testing flow process.

**Comment by NadezhdaPeskun** [comment]
Should be verified with next Issues: (4708, 4575, 4506,4706) + 4328
Error Message should appear:
Error Message:
It is impossible to merge fragments. Attachment point to establish bonds are not available.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/ec0c2702-a8b7-422f-bc5b-f01640771873)


 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
