### ISSUE TITLE
Macro: In the Text-editing mode, when selecting nucleotides linked through phosphates R2-R2, an error appears in the Console

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4508]
**Steps to Reproduce**
1.	Switch to the Macro mode 
2.	Open this file (first unzip)  [Phosphates R2-R2.zip](https://github.com/epam/ketcher/files/15053449/Phosphates.R2-R2.zip)
3.    Switch to the Sequence mode - the Text-editing mode
4.	Select the structure

**Actual behavior**
The error appears in the Console DevTool (Uncaught RangeError: Maximum call stack size exceeded)
<img width="502" alt="2024-04-21_21h12_02" src="https://github.com/epam/ketcher/assets/139227567/5f086cb3-bb67-4fd4-a2f7-55e2c91f8098">
[rc.test.lifescience.opensource.epam.com-1713726743105.log](https://github.com/epam/ketcher/files/15053454/rc.test.lifescience.opensource.epam.com-1713726743105.log)

**Expected behavior**
There is no error in the Console DevTool 

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/ceec7ff2-92e4-4cdd-99d4-dc1b654b5f13

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.60) x64

**Ketcher version** 2.21.0-rc.1, Build at 2024-04-15; 20:06:01

**Comment by ViktoriaTkacheva** [comment]
Verified.

Indigo Toolkit Version 1.20.0-rc.2.0-g111a89f35-x86_64-linux-gnu-11.2.1
Ketcher Version 2.21.0-rc.2, Build at 2024-05-24; 09:07:47
Сhrome Version: (125.0.6422.61) x64
Windows 10 Pro (version 22H2) x64

<img width="949" alt="image" src="https://github.com/epam/ketcher/assets/139227567/f7b89a4b-ab57-4ab6-a751-5abf32876da4">

**Comment by Zhirnoff** [comment]
Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
