### ISSUE TITLE
In the Text-editing mode, when inserting a fragment after pressing Ctrl+V twice, the cursor is moved to another row

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4509]
**Steps to Reproduce**
1.	Open two Ketcher browser tabs – the Macro mode
2.	Draw three connected nucleotides
3.	Switch to the Sequence mode - the Text-editing mode
      <img width="125" alt="image" src="https://github.com/epam/ketcher/assets/139227567/67832b57-3673-4f69-a6f4-ec74b14cc7c9">

4.	Copy this sequence and paste it several times into the Text-editing mode of another Ketcher browser tab, where there is already some sequence (for example, AAAp or AAA)

**Actual behavior**
Only two fragments are inserted in each row, and after that, the cursor moves to the next row and the next insertion occurs on the new row
<img width="156" alt="image" src="https://github.com/epam/ketcher/assets/139227567/a3758206-a04d-411d-98ce-a08b8c24106e">

**Expected behavior**
Insertion on one row occurs until 30 letters are entered. If the inserted fragment contains a nucleotide that will be 31 on the row, it must be moved to the next row
<img width="493" alt="image" src="https://github.com/epam/ketcher/assets/139227567/c7a1cdb9-a045-4774-9d98-d8e62f051cd1">

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/94f4e94e-8a01-45ab-902d-436e03635cc9

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.60) x64

**Ketcher version** 2.21.0-rc.1, Build at 2024-04-15; 20:06:01

Issue found while testing https://github.com/epam/ketcher/issues/3916

**Comment by Zhirnoff** [comment]
The issue has been moved from 2.21.0-rc.2 to 2.22.0-rc.1 after discussion with management and in accordance with the testing flow process.

**Comment by ViktoriaTkacheva** [comment]
Verified.

Indigo Toolkit Version 1.21.0-dev.4.0-gb15b3f662-wasm32-wasm-clang-12.0.0
Ketcher Version 2.21.0-rc.2, Build at 2024-05-30; 08:32:11
Сhrome Version: (125.0.6422.113) x64
Windows 10 Pro (version 22H2) x64


https://github.com/epam/ketcher/assets/139227567/411f2603-3e3b-40bb-9aec-23219b5f2fe6

**Comment by Zhirnoff** [comment]
Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
