### ISSUE TITLE
In the Text-editing mode, the canvas is not moved to make the newly added sequence visible

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4526]
**Steps to Reproduce**
1.	Switch to the Macro mode - the Text-editing mode
2.	Add sequences to the canvas until they vertically fill the viewport (without using the scroll bar)
 
       <img width="105" alt="image" src="https://github.com/epam/ketcher/assets/139227567/e89aa817-e911-4773-808a-0b5b7157fe25">

3.	Press the “Enter” key, and enter one more sequence by typing it manually or by pasting it via Ctrl+V

**Actual behavior**
The canvas is not moved to make the newly added sequence visible

**Expected behavior**
The canvas should be moved to make the newly added sequence visible

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/ebc0a0b0-8420-49a2-8671-276c79efc08f

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.60) x64

**Ketcher version** 2.21.0-rc.1, Build at 2024-04-15; 20:06:01

Issue found while testing https://github.com/epam/ketcher/issues/3916

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/95547d5b-721e-4321-be1c-7566254f2a53



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
