### ISSUE TITLE
Allow moving and connecting "small" structures in macro mode

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4531]
**Background**
Functionality for movement of "small" molecules in macromolecules mode was disabled during the previous phase of implementation of macromolecules mode. Currently it is possible to move molecules however it does not affect molecule coordinates and after switching back to molecules mode the structure appears to the initial position defined in molecules mode last time.

https://github.com/epam/ketcher/assets/14859362/653909df-a276-4f77-bdc2-41abb756377f

**Solution**
It needs to apply changing of molecule structure coordinates during movement in macromolecules mode.

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by AlexeyGirin** [comment]
Verified.

**Versions** [e.g. v2.4.2]. 
 - Indigo Toolkit Version 1.21.0-dev.3.0-g6f55c664-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-20; 05:30:45
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
