### ISSUE TITLE
Allow connection of molecule with monomer

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4532]
**Background**
Functionality of attachment points addition for molecules will be implemented in ticket: https://github.com/epam/ketcher/issues/4530
After that connections between molecules and monomers in macromolecules mode will be enabled. It needs to implement different serialization rules for such connections.

**Solution**
1) Connections between molecules and monomers should be serialized/deserialized to ket with such structure:
```
// Connection
{
    "connectionType": "single",
    "endpoint1": {
        "monomerId": "monomer14",
        "attachmentPointId": "R2"
    },
    "endpoint2": {
        "moleculeId": "mol0",
        "atomId": "2"
    }
},
```
2) Such connections should be displayed as connection between monomers in macromolecules mode and connection between sgroup and atom of molecule in molecules mode.

Macromolecules mode:
<img width="465" alt="Screenshot 2024-05-27 at 19 15 09" src="https://github.com/epam/ketcher/assets/14859362/f5dfb6d5-5262-41ea-8212-338e16d5a147">

Molecules mode:
<img width="394" alt="Screenshot 2024-05-27 at 19 15 17" src="https://github.com/epam/ketcher/assets/14859362/6a368631-bd2c-4ce7-b909-4e14374b0f7f">

**Comment by AlexeyGirin** [comment]
Rules of Center to Center connection?

**Comment by Zhirnoff** [comment]
Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
