### ISSUE TITLE
After inserting a nucleotide in the Text-editing mode, the cursor blinks in the wrong place

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4533]
**Steps to Reproduce**
1.	Open two Ketcher browser tabs – the Macro mode 
2.	Switch to the Sequence mode - the Text-editing mode
3.	Enter any sequence (for example, UUU)
4.	Copy any nucleotide with phosphate from another browser tab (for example, Tp)
5.	Paste it before the sequence

**Actual behavior**
The cursor is not displayed after the inserted nucleotide, but one nucleotide further
<img width="116" alt="image" src="https://github.com/epam/ketcher/assets/139227567/dc2a7277-08d2-4874-bc3b-57558007b7d1">

**Expected behavior**
The cursor is displayed after the inserted nucleotide
<img width="114" alt="image" src="https://github.com/epam/ketcher/assets/139227567/7ad4f499-c4dd-4727-85cb-5079b7482e7b">

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/f839c18c-dbf0-4dac-937a-29a1435b3a91

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.60) x64

**Ketcher version** 2.21.0-rc.1, Build at 2024-04-15; 20:06:01

Issue found while testing https://github.com/epam/ketcher/issues/3916

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/19673867-dca6-4955-bf50-cd9e6b37a568)
- Ketcher Version 3.20.0-rc.1 Build at 2024-12-31; 12:50:08
- Indigo Toolkit Version 1.28.0-rc.1.0-gc167e6266-wasm32-wasm-clang-19.0.0
- Chrome Version Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
