### ISSUE TITLE
In the Text-editing mode, after inserting a fragment at the end of the sequence, where there is a phosphate, the cursor does not blink

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4534]
**Steps to Reproduce**
1.	Open two Ketcher browser tabs – the Macro mode 
2.	Add any nucleotide on the canvas
3.	Switch to the Sequence mode - the Text-editing mode
       <img width="100" alt="image" src="https://github.com/epam/ketcher/assets/139227567/a0a42673-0f14-45d4-805a-10834a67311c">

4.	Copy any nucleotide with or without phosphate from another browser tab (for example, Tp or T)
5.	Paste it at the end of the sequence

**Actual behavior**
The cursor does not blink at the end of the sequence
<img width="111" alt="image" src="https://github.com/epam/ketcher/assets/139227567/c87aa001-b00a-4691-bb16-6cc52fa578bd">

**Expected behavior**
For consistency, the cursor should blink at the end of the sequence (similar to the case, when the cursor blinks if any fragment is inserted at the end of the sequence, where there is no phosphate)
<img width="123" alt="image" src="https://github.com/epam/ketcher/assets/139227567/6cd0b3ff-a595-409b-9da1-9da3c630624e">

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/23e9557f-4636-4937-b790-95d39ff7d430

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.60) x64

**Ketcher version** 2.21.0-rc.1, Build at 2024-04-15; 20:06:01

Issue found while testing https://github.com/epam/ketcher/issues/3916

**Comment by rrodionov91** [comment]
Look's like accidentally fixed. @ViktoriaTkacheva  could you please check?

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/user-attachments/assets/c2575501-0132-4539-8de4-1b6b7dbfe942


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
