### ISSUE TITLE
Export macromolecules canvas as svg image

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4539]
**Background**
It needs to allow users to export macromolecules canvas as svg image from ketcher ui and api.

**Solution**
1) Export svg from ketcher ui
New option "SVG Document" should appear in "file format" dropdown "Save Structure" dialog.
When option selected system should export all structures drawn on canvas to svg format. Image should be displayed in preview window of dialog.
When "Save" button pressed system should download file with svg image content.

2) [UNDER DISCUSSION]Export svg from ketcher api
Implement new api methods:
- ketcher.exportImage(format, params) - format: ["svg"], params = { margin: number } 
- ketcher.setMode(mode) - flex | sequence | snake
- ketcher.setZoom(zoom) - zoom: number

3) Additional requirements for svg image
Image should be scaled to fit all drawn structures with small offset from image borders.
Elements should not be interactive, so all corresponding styles should not be included in export.
Elements should be displayed in same as they drawn on canvas according selected mode(flex/snake/sequence).
Temporary objects(monomer preview near cursor, css cursor, selectors and e.t.c) should not be included into image.

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.21.0-dev.3.0-g6f55c664-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-20; 05:30:45
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10
