### ISSUE TITLE
'Save Structure' and 'Structure Check' windows are enlarged when trying to save/check a big molecule

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#454]
Affected version: _Standalone_

Steps to reproduce:
1. Launch Ketcher.
2. Open 
[anthracene.zip](https://github.com/epam/ketcher/files/6277313/anthracene.zip)
3. Click on 'Save As' button.
4. Click on 'Close' button in 'Save structure' window.
5. Click on ' Structure Check' button.

Expected result: 
3. The 'Save Structure' window is opened. The amount of atoms in the molecule which is going to be saved doesn't affect the window width. If the warning in the "Save Structure" window is wider than the default window width it is transferred to the next line.
5. The 'Structure Check' window is opened. The amount of atoms in the molecule which is going to be saved doesn't affect the window width. If the warning in the "Save Structure" window is wider than the default window width it is transferred to the next line.

Actual result: 
3. The 'Save Structure' window is opened. It is enlarged. The warning is written in one line. The width of the window depends on the length of the warning (Max width is almost the width of the canvas. In case the warning is longer a scroll appears).

![Save2](https://user-images.githubusercontent.com/80695128/114018481-f2617180-9875-11eb-83d1-5c826bf9553b.jpg)

5. The 'Structure Check' window is opened. It is enlarged. The warning is written in one line. The width of the window depends on the length of the warning (Max width is almost the width of the canvas. In case the warning is longer a scroll appears).

![Check1](https://user-images.githubusercontent.com/80695128/114018493-f5f4f880-9875-11eb-9bde-fc65c3db8e7b.jpg)

**Comment by StartsevDS** [comment]
To be fixed in #452
![StructCheck](https://user-images.githubusercontent.com/81175908/114558148-0d1b5800-9c73-11eb-8513-512c369af1bc.png)
![StructSave](https://user-images.githubusercontent.com/81175908/114558149-0e4c8500-9c73-11eb-83e2-8f607a3d791e.png)

**Comment by Svetlana-Asinovskaia** [comment]
The issue is closed as fixed
