### ISSUE TITLE
The cleared object is not returned by the Undo button in the Macromolecules mode.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4543]
**Steps to Reproduce**

1. Switch to Macro
2. add any object to Canvas (RNA or Peptide)
3. Press Clear icon
4. Press Undo >> _nothing happens_
5. Press Undo again >> _cleared object comes back._

**Actual behavior**
The cleared object is not returned by the Undo button in the Macromolecules mode.
Object is returned only after press on the Undo button secondary time.
<img width="76" alt="image" src="https://github.com/epam/ketcher/assets/161723514/9276bed2-7290-497a-863a-cfdb1ee5ad6a">

**Expected behavior**
The cleared object should be returned by click on the Undo button first time.

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0

**Comment by Zhirnoff** [comment]
Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
