### ISSUE TITLE
Cyclic chains disappear from canvas when try to Edit in the sequence mode

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4548]
**Steps to Reproduce**
1. Switch to Macro mode
2. Open file with Cyclic Chain 
[ketcher.zip](https://github.com/epam/ketcher/files/15146811/ketcher.zip)

3. Switch to sequence mode
<img width="135" alt="image" src="https://github.com/epam/ketcher/assets/161723514/e79864cd-1f38-4335-8bc6-0add6d9c167a">

4. Select any T >> context menu >> Edit 
<img width="237" alt="image" src="https://github.com/epam/ketcher/assets/161723514/22b3f00a-818b-4647-ac78-c62c4a7ca09e">

5. Try to add latest any letter (A) 
<img width="161" alt="image" src="https://github.com/epam/ketcher/assets/161723514/37fc3cd0-ad4f-4fda-864a-a7cb6b20d0ef">

**Actual behavior**
Cyclic bond is moved to the next latest place. 
All chains disappear from canvas when try to add new letter to latest place in the sequence mode

**Expected behavior**
Cyclic chains should not disappear from canvas when Edit in the sequence mode.

Attachment:

https://github.com/epam/ketcher/assets/161723514/ad7c737b-6a7e-4610-b04e-0a4d044dc059

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Version** 
Ketcher Version 2.20.0-rc.3 Build at 2024-04-26; 16:57:15
Indigo Toolkit Version 1.19.0-rc.3.0-gf2d7689b8-wasm32-wasm-clang-12.0.0

**Comment by ViktoriaTkacheva** [comment]
An issue, found while testing this bug fix, was moved to a separate ticket: https://github.com/epam/ketcher/issues/4706

**Comment by NadezhdaPeskun** [comment]
Verified as fixed for CI 2.22 rc1 - new bug is added
- https://github.com/epam/ketcher/issues/4706
