### ISSUE TITLE
Preview for ambiguous monomers

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4555]
**Background**
Ambiguous monomers are used to describe ambiguity in the structure of a macromolecule.
Ambiguous monomers could be classified in two types:
- Alternatives (XOR) - this type of ambiguous monomer is used to describe that at a specific position in the macromolecule, any monomer from a list of options can be present.
- Mixed (AND) - this type of ambiguous monomer is used to specify not only the list of possible monomers that can be used, but also the probabilities (weights) with which these ambiguous may occur at that position.

The scope of this task includes preview for ambiguous monomers (chem structures, ratios, AND/XOR)

**Requirements**

1. For the ambiguous monomer preview, it should contain the list of monomers (full names) that make up the ambiguous monomer.
2. If the ambiguous monomer is "alternatives" (without probabilities) the list should be ordered alphabetically.
3. If the ambiguous monomer is "mixed" (with probabilities) the list should be ordered by probabilities.
3.1. If there are multiple monomers with same probability, they should be ordered alphabetically.
4. The list should be limited to 5 monomers.
5. For mixtures, the weights of each monomer should also be displayed in the preview (see mockups).
6. In the case of `X`, "Any Amino Acid" should be displayed in the preview.
7. In the case of `N` (both RNA and DNA versions), "Any Base" should be displayed in the preview.
8. All the previews (micro mode, flex/snake mode, library) are as described, while the preview in sequence mode for nucleotides/nucleosides with a ambiguous base should have the name written as: sugar(base)phosphate (see mockups).

**UX**
![image](https://github.com/user-attachments/assets/a5c54ed6-939b-46bb-b1bf-48361eef71c7)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/b67359c1-f206-4821-af11-c5af968ec4cf)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10
