### ISSUE TITLE
Support of ambiguous monomers in sequence view 

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4556]
**Background**
Support for ambiguous monomers in sequence mode (X, N, etc.)

**Requirements**
1. Ambiguous monomers with a letter symbol (`R`, `Y`, `M`, `K`, `S`, `W`, `H`, `B`, `V`, `D` and `N` for RNA/DNA, and `B`, `J`, `Z` and `X` for peptides; see: [#2015](https://github.com/epam/Indigo/issues/2015)) should be represented as those symbols in sequence mode.
2. Other ambiguous monomers should be displayed as `%` in sequence mode.
3. Previews for hovering over the monomers in sequence mode are addressed in the related issue: [#4555](https://github.com/epam/ketcher/issues/4555).

**UX**
![image](https://github.com/user-attachments/assets/48dede69-7d49-4baf-be0e-0b6191c74598)

**Comment by AlexeyGirin** [comment]
Test cases added

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/4efb176c-4498-46fe-a432-86cd4d0f165f)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10
