### ISSUE TITLE
Support of ambiguous monomers in small molecules mode

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4557]
**Background**
 Support for ambiguous monomers in small molecules mode (black box).

**Requirements**
1. Ambiguous monomers with a letter symbol (`R`, `Y`, `M`, `K`, `S`, `W`, `H`, `B`, `V`, `D` and `N` for RNA/DNA, and `B`, `J`, `Z` and `X` for peptides; see: [#2015](https://github.com/epam/Indigo/issues/2015) and [#5186](https://github.com/epam/ketcher/issues/5186) ) should be represented as those symbols in micromolecules mode.
2. Other ambiguous  monomers should be displayed as `%` in micromolecules mode.
3. Previews for hovering over the monomers in miromolecules mode is identical to the previews in flex mode (related issue: [#4555](https://github.com/epam/ketcher/issues/4555)).

**UX**
![image](https://github.com/user-attachments/assets/ad92df51-fceb-4688-bdf4-b2f884078e3f)

**Comment by AlexeyGirin** [comment]
Test cases added

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/3a757474-8a0d-4e29-9c26-334cba7baa1e)
**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10
