### ISSUE TITLE
Modified Sequence isn't visible on Sequence mode after paste or open file actions

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4561]
**Steps to Reproduce**

1. Switch to Macro >> snake mode
2. Open file 
[ketcher (modify).zip](https://github.com/epam/ketcher/files/15165637/ketcher.modify.zip)
<img width="486" alt="image" src="https://github.com/epam/ketcher/assets/161723514/757f5927-aaa5-4bc1-bbda-0db874c25635">

3. Go to Sequence mode
<img width="575" alt="image" src="https://github.com/epam/ketcher/assets/161723514/a02d48a9-c788-4d6f-835d-3655ce13f624">

**Actual behavior**
Not all sequences are visible in the Sequence mode. 
Cannot see modified sequences after save to file or copy/paste actions

**Expected behavior**
All sequences should be visible in the all modes of Macromolecules side

Can be related with
- https://github.com/epam/ketcher/pull/4551
- https://github.com/epam/ketcher/issues/4329

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0

**Comment by NadezhdaPeskun** [comment]
https://github.com/epam/ketcher/pull/4551
Should be verified after close this backmerge

**Comment by AlexeyGirin** [comment]
Fix haven't come to master from 2.20
