### ISSUE TITLE
Aromatization of 5-membered, nitrogen-containing aromatic rings results in invalid SMILES

### ISSUE THREAD

**Issue by gio-hlx** [epam/ketcher#4566]
**Steps to Reproduce**
1. Draw a 5-membered, nitrogen-containing aromatic ring (e.g. pyrrole, indole, etc.).
2. Click on the aromatization button
3. Look at the represented molecule structure and especially the generated SMILES string.

**Actual behavior**
The molecule is converted from the kekule to the aromatic representation but the H atom connected to the aromatic N is removed (e.g. pyrrole: “C1NC=CC=1” -> “c1cccn1”)

**Expected behavior**
The molecule is converted from the kekule to the aromatic representation keeping the hydrogen atom connected to the aromatic nitrogen (e.g. pyrrole: “C1NC=CC=1” -> “c1ccc[nH]1”)

**Screenshots**
See screenshot of pyrrole case where the hydrogen atom attached to the aromatic nitrogen is removed generating an invalid SMILES.
<img width="909" alt="pyrrole_kekule" src="https://github.com/epam/ketcher/assets/115071006/5687b7f9-4a0f-481d-8c0d-8d867c7969dd">
<img width="909" alt="pyrrole_aromatic" src="https://github.com/epam/ketcher/assets/115071006/2449b8d4-d94b-4315-baf0-f4104a691edb">

**Ketcher version**
Ketcher 2.7.2

**Additional context**
I’m using Ketcher 2.7.2 integrated in the “Molecule Widget (Labs)” node from KNIME. I’ve noticed this problem during the aromatisation of common heteroaromatic molecules containing 5-membered aromatic rings with N (e.g. pyrrole, indole, etc.). The generated SMILES (and the corresponding molecular structures) are not valid and cannot be parsed by and used in other molecular tools (e.g. RDKit).

**Comment by AlexeyGirin** [comment]
Hi @gio-hlx !
Thanks for your report.

It seems that issue you describe is already fixed in the latest releases.
Please consider Ketcher version update (to 2.21 at least)
![image](https://github.com/epam/ketcher/assets/26869421/defd0d0d-6508-4ed2-8952-30add66e9499)

**Comment by rrodionov91** [comment]
[heart]         Roman Rodionov reacted to your message:
________________________________
