### ISSUE TITLE
Preview: Pasted sequences are not visible in the Snake mode.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4568]
**Steps to Reproduce**

1. Switch to Macro >> Snake mode
2. Open file 
[ketcher (8).zip](https://github.com/epam/ketcher/files/15187711/ketcher.8.zip)
3. Select all >> Copy
<img width="317" alt="image" src="https://github.com/epam/ketcher/assets/161723514/062ee653-6d5a-43a4-b1e4-af2a1896c9a9">

3. Go to Sequence mode 
<img width="65" alt="image" src="https://github.com/epam/ketcher/assets/161723514/1effd49c-70f2-4abf-8efd-d17e580f4a28">

4. Paste
<img width="68" alt="image" src="https://github.com/epam/ketcher/assets/161723514/98f7dd8e-1e10-4726-ab29-ad43fcdf4740">

5. Go to Snake mode  again
<img width="341" alt="image" src="https://github.com/epam/ketcher/assets/161723514/27d388fd-2d99-468b-a3a1-7222652fc888">

6. Try to Paste in the Snake mode

**Actual behavior**
Sequences inserted in Snake mode do not appear in Snake mode.
Sequences inserted in Sequence mode are not displayed in Snake and Flex modes. (see first video file)
If you insert sequences into Snake Mode after Flex Mode > Snake Mode becomes empty. (see second video file)

**Expected behavior**
Pasting sequences to the any mode should be visible in the Snake/Flex mode.

https://github.com/epam/ketcher/assets/161723514/686e5fe5-6fb5-427b-be42-522b0a7a8404

https://github.com/epam/ketcher/assets/161723514/b53c1673-6790-40f4-9057-8bbef1c5352a

**Versions:**
[Version 2.21.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)
    Build at 2024-04-29; 09:29:15

Indigo Toolkit
    Version 1.20.0-rc.1.0-g8e8ffc3c3-x86_64-linux-gnu-11.2.1

**Comment by ViktoriaTkacheva** [comment]
Verified.

Indigo Toolkit Version 1.20.0-rc.2.0-g111a89f35-x86_64-linux-gnu-11.2.1
Ketcher Version 2.21.0-rc.2, Build at 2024-05-24; 09:07:47
Сhrome Version: (125.0.6422.61) x64
Windows 10 Pro (version 22H2) x64

**Comment by Zhirnoff** [comment]
![2024-06-10_14h48_35](https://github.com/epam/ketcher/assets/62464241/9bbb2f3b-42f7-4246-8972-81c89d404ac2)

Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.21.0-rc.3]
**Indigo version** 
[Version 1.20.0-rc.3]
