### ISSUE TITLE
Wrong layout in the Sequence mode while Paste sequences to the Flex mode

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4569]
**Steps to Reproduce**

1. Switch to Macro >> Flex mode
2. Open file 
[ketcher (8).zip](https://github.com/epam/ketcher/files/15187711/ketcher.8.zip)
3. Select all >> Copy
<img width="317" alt="image" src="https://github.com/epam/ketcher/assets/161723514/062ee653-6d5a-43a4-b1e4-af2a1896c9a9">

3. Go to Sequence mode 
<img width="65" alt="image" src="https://github.com/epam/ketcher/assets/161723514/1effd49c-70f2-4abf-8efd-d17e580f4a28">

4. return to Flex mode >> Paste
<img width="344" alt="image" src="https://github.com/epam/ketcher/assets/161723514/c9cdd4bd-662a-4b6d-8b45-c042ebab4d22">

3. See on Sequence mode 

**Actual behavior**
Wrong layout in the Sequence mode while Paste sequences to the Flex mode
<img width="61" alt="image" src="https://github.com/epam/ketcher/assets/161723514/4c9d57da-e1c2-491d-b64a-9a90bf02d4f3">

**Expected behavior**
layout in the Sequence mode should be the same as we Paste sequences to the Sequence mode.

<img width="65" alt="image" src="https://github.com/epam/ketcher/assets/161723514/540aaca5-b7ae-4489-9948-0197f75a7fe0">

**Versions:**
[Version 2.21.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)
    Build at 2024-04-29; 09:29:15

Indigo Toolkit
    Version 1.20.0-rc.1.0-g8e8ffc3c3-x86_64-linux-gnu-11.2.1

**Comment by rrodionov91** [comment]
fixed in https://github.com/epam/ketcher/pull/4616

**Comment by AlexeyGirin** [comment]
Verified but another issues has been created - https://github.com/epam/ketcher/issues/4730
![image](https://github.com/epam/ketcher/assets/26869421/fdf7adca-dd4b-4ace-aa16-67597169a8d7)

Windows 10
Chrome Version 125.0.6422.142 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.2 Build at 2024-06-03; 05:33:52
Indigo Toolkit Version 1.21.0-dev.5.4-gb45d44aa-wasm32-wasm-clang-12.0.0
