### ISSUE TITLE
Notification message of red border of Type (RNA/DNA/Peptides) doesn't appear if user cannot add symbol to Canvas of Sequence mode.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4576]
**Steps to Reproduce**

1. Switch to Macro 
2. go to Sequence mode 
3. Context menu >>Add new sequence
4. Select DNA >> add AAA
5. Select Peptides >> Add QQQ
6. Select DNA >> try to add QQQ

**Actual behavior**
Nothing happens, and the user doesn't receive any notifications.

**Expected behavior**
Notification message of red border of Type (RNA/DNA/Peptides) should appear if user cannot add symbol to Canvas of Sequence mode.

**Versions:**
[Version 2.21.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)
    Build at 2024-04-29; 09:29:15

Indigo Toolkit
    Version 1.20.0-rc.1.0-g8e8ffc3c3-x86_64-linux-gnu-11.2.1

**Comment by olganaz** [comment]
It's not a bug. The system works as expected.
