### ISSUE TITLE
RNA Structure is broken while we Copy from Macro and Paste to Micro canvas.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4590]
*Steps to Reproduce**
1. Switch to Macro
2. Open file with Chem
[ketcher (24).zip](https://github.com/epam/ketcher/files/15248065/ketcher.24.zip)
<img width="254" alt="image" src="https://github.com/epam/ketcher/assets/161723514/a5c9a8d5-4f47-4cb6-8fc2-7ec5ab31738d">

3. Select all structures >> Copy 
4. Go to MICRO
5. Paste 

**Actual behavior**
Structure is broken while we Copy from Macro and Paste to Micro canvas.
<img width="332" alt="image" src="https://github.com/epam/ketcher/assets/161723514/31cafd8a-3181-474a-b92e-b643888deac6">

**Expected behavior**
Structure should no be broken while we Copy from Macro and Paste to Micro canvas.
<img width="223" alt="image" src="https://github.com/epam/ketcher/assets/161723514/713c603f-298e-4267-91a8-da2fb18dcb7f">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.21.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-05-07; 12:32:44

[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-rc.2.0-g111a89f35-wasm32-wasm-clang-12.0.0

**Comment by ilya-asiyuk-epam** [comment]
Root cause:
code added in this task - https://github.com/epam/ketcher/issues/2517

**Comment by ViktoriaTkacheva** [comment]
1. An error appears in the Console in two cases:
    a) when pasting structures onto the canvas
    b) when moving structures beyond the boundaries of the canvas

![2024-05-30_16h20_00](https://github.com/epam/ketcher/assets/139227567/ae2c917d-afc4-4598-beab-2db5996af36b)

<img width="940" alt="image" src="https://github.com/epam/ketcher/assets/139227567/f72fbecf-296b-485c-9349-b63c94ef235a">

https://github.com/epam/ketcher/assets/139227567/1217e488-6bd6-4076-9a5a-400b769d0292

2. Sometimes the structure is distorted when pasting and an error appears in the Console (it is not always reproduced)

<img width="936" alt="image" src="https://github.com/epam/ketcher/assets/139227567/bc974895-9f72-412c-acbd-933f0421b46a">

Indigo Toolkit Version 1.21.0-dev.4.0-gb15b3f662-wasm32-wasm-clang-12.0.0
Ketcher Version 2.21.0-rc.2, Build at 2024-05-30; 08:32:11
Сhrome Version: (125.0.6422.113) x64
Windows 10 Pro (version 22H2) x64

**Comment by Zhirnoff** [comment]
Tested. An error appears in the Console in two cases:
a) when pasting structures onto the canvas
b) when moving structures beyond the boundaries of the canvas
After talking with @rrodionov91 , we realized that we already have a bug for this problem https://github.com/epam/ketcher/issues/4368
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
