### ISSUE TITLE
Recognize special text to structure when save molfile, for example "H2O" or "Boc"

### ISSUE THREAD

**Issue by ForBurning** [epam/ketcher#460]
if I write some special text into editor by Text Tool, for example "H2O" or "Boc",
I hope ketcher can recognize them to real structure but not is simple text.

Is that possible to add a function to realize it?

**Comment by AndreiMazol** [comment]
Dear @ForBurning ,

Thank you for your interest to Ketcher.

Text tool has been created to add text labels with any comments. The functionality to recognize texts should be implemented as a part of 'Open Structure' dialog. We will discuss your idea internally.

Best regards,
Ketcher team
