### ISSUE TITLE
Inconsistent display of a separate phosphate in the sequence representation in the Sequence mode

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4607]
**Steps to Reproduce**
1.	Switch to the Macro mode 
2.	Open this file [Separate p in sequence.zip](https://github.com/epam/ketcher/files/15276737/Separate.p.in.sequence.zip)
        <img width="296" alt="image" src="https://github.com/epam/ketcher/assets/139227567/abca9c3f-9fe4-4beb-9ba2-f91ad2424534">

3.	Switch to the Sequence mode
        <img width="107" alt="image" src="https://github.com/epam/ketcher/assets/139227567/8e496d00-dea0-4738-9027-9087f77f79a4">

4.	Add one more nucleotide at the end of the sequence
        <img width="141" alt="image" src="https://github.com/epam/ketcher/assets/139227567/e5856c25-5896-4d9a-8585-ea6b5aefa1b4">

**Actual behavior**
The phosphate is displayed as “p”

**Expected behavior**
1. Single phosphate that is not a part of nucleotide (in the middle of the chain) or nucleoside (at the end of the chain) should be displayed as 'p' in sequence mode. 
2. A group of multiple (more or equal than two) phosphates should be displayed as '@'. 
Images for better understanding: 
<img width="350" src="https://github.com/epam/ketcher/assets/143799055/02e5fb90-794d-413a-b3bb-efaa8714f115">
<img width="350" src="https://github.com/epam/ketcher/assets/143799055/911a0bcd-6b68-4eae-90ed-e473364f03ea">  

<img width="280"  src="https://github.com/epam/ketcher/assets/143799055/106dc630-7e9e-4d9f-9b41-593f5922f723">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.92) x64

**Ketcher version** 2.21.0-rc.2, Build at 2024-05-10; 05:30:51

Issue found while testing https://github.com/epam/ketcher/issues/3734

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-07-03_14h43_16](https://github.com/epam/ketcher/assets/62464241/1efa3806-3d0b-4812-8fc9-51bebb0070d3)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]
