### ISSUE TITLE
Ambiguous attachment points selection logic

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4613]
This is follow up for https://github.com/epam/ketcher/issues/4530

**Background**
User is able to create molecules (in micro mode) that contains same leaving groups (Rx) for different atoms but same molecule
At that case we have to introduce rule(s) of selection - which attachment point to use in case of bond operation
![image](https://github.com/epam/ketcher/assets/26869421/698246f1-cb38-45bd-a7f2-0ae80b90274e)

**Solution**
Rule: Simply took first valid attachment point for connection. In example above - R7 number 1 and number 3 are valid APs for connection. So one of them should be selected.

**Comment by rrodionov91** [comment]
Requirements of initial task changed https://github.com/epam/ketcher/issues/4530.
Issue describes impossible scenario in current application state.
Closing as not planned
