### ISSUE TITLE
Sorting is absent for RNA builder components (Sugar, Base, Phosphates).

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4615]
**Steps to Reproduce**
1. Switch to Macro
2. see RNA builder
3. Sugar, Base, Phosphates sorting
![image](https://github.com/epam/ketcher/assets/161723514/8d21585d-45f5-48ae-b9c7-723b068f3be2)

**Actual behavior**
Sorting is absent for RNA builder components (Sugar, Base, Phosphates...), Peptides and CHEM.

**Expected behavior**
RNA builder components (Sugar, Base, Phosphates...), Peptides and CHEM
should be sorted alphabetically by short names. (Agreement with BA).
Also, 
Base - first Base of each group should be main Base (A, T, G, C, U).
Peptides - first Peptide of each group should be main peptide (U,G,W...)
Chem should be sorted as well.

• OS: Win 11
• Browser: Сhrome
• Version: (122.0.6261.95) x64

Ketcher:
[Version 2.21.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-05-07; 12:32:44

[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-rc.2.0-g111a89f35-wasm32-wasm-clang-12.0.0

**Comment by ViktoriaTkacheva** [comment]
Verified.

Indigo Toolkit Version  1.20.0-rc.2.0-g111a89f35-x86_64-linux-gnu-11.2.1
Ketcher Version 2.21.0-rc.2, Build at 2024-05-31; 07:23:21
Сhrome Version: (125.0.6422.113) x64
Windows 10 Pro (version 22H2) x64

<img width="194" alt="image" src="https://github.com/epam/ketcher/assets/139227567/0d13fd8f-e9b6-492b-9d52-c69d880f3b51">

<img width="193" alt="image" src="https://github.com/epam/ketcher/assets/139227567/d54480fb-0174-49f8-b6ae-ee814ece2b18">

<img width="195" alt="image" src="https://github.com/epam/ketcher/assets/139227567/ccb0d9c4-04ae-45e7-bd63-2da9ed627529">
