### ISSUE TITLE
Crash Macro and Structures are broken on the Micro while save to KET/mol and open file with Macro and Micro objects.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4624]
**Steps to Reproduce**
1. Micro >> Add Benzene
<img width="113" alt="image" src="https://github.com/epam/ketcher/assets/161723514/f9fa2e4c-2dd8-4811-b21b-fd7f07f9516e">

2. Switch to Macro >> Add Preset 
<img width="235" alt="image" src="https://github.com/epam/ketcher/assets/161723514/dd87b97f-525f-41ec-b276-367a48ab6b0f">

3. Save the next
- save as KET in the Macro mode
-  save as KET in the Micro mode
-  save as mol in the Micro mode
[ketcher (39).zip](https://github.com/epam/ketcher/files/15319308/ketcher.39.zip)
[ketcher (38).zip](https://github.com/epam/ketcher/files/15319309/ketcher.38.zip)
[ketcher (11).zip](https://github.com/epam/ketcher/files/15319311/ketcher.11.zip)

4. Open these files in the Micro
<img width="270" alt="image" src="https://github.com/epam/ketcher/assets/161723514/5414a94a-74ac-4320-a412-c283d9959380">
<img width="326" alt="image" src="https://github.com/epam/ketcher/assets/161723514/809ea37f-4a96-4a25-aa33-3de12231a002">

5. Switch to Macro

**Actual behavior**
Crash Macro and Structures are broken on the Micro while save to KET/mol and open file with Macro and Micro objects.
Opened Structure is different broken while:
- saved as KET in the Macro mode
-  saved as KET in the Micro mode
-  saved as mol in the Micro mode

**Expected behavior**
КЕТ and Mol file should be opened without crash
<img width="269" alt="image" src="https://github.com/epam/ketcher/assets/161723514/206ec6be-d916-44f5-8edb-09d907b57f3b">

- 
- https://github.com/epam/ketcher/issues/4474

Win11
Chrome: Version 123.0.6312.123 (Official Build) (64-bit)

Ketcher
[Version 2.21.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-05-07; 12:32:44
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.20.0-rc.2.0-g111a89f35-wasm32-wasm-clang-12.0.0

**Comment by vitaepam** [comment]
ECT: May of 24th

**Comment by Zhirnoff** [comment]
Tested. We have bug about saved and open in MOL V2000

**Comment by AlexeyGirin** [comment]
Verified.
Follow up issues has been created - https://github.com/epam/ketcher/issues/4747

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
