### ISSUE TITLE
CHEMs that are not a part of nucleotide or nucleoside are not ignored during export

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4626]
**Steps to Reproduce**
1. Open Macro mode
2. Add any RNA sequence and several CHEMs on canvas (see screenshot) or use attached file [ketcher (50).zip](https://github.com/epam/ketcher/files/15321979/ketcher.50.zip)
3. Press 'Save' button and select FASTA format

**Actual behavior**
CHEMs that are not a part of nucleotide or nucleoside are not ignored during export. An error message appears.

**Expected behavior**
CHEMs that are not a part of nucleotide or nucleoside are ignored during export. As described in https://github.com/epam/Indigo/issues/1755

**Screenshots**
![2024-05-15_16h01_20](https://github.com/epam/ketcher/assets/62464241/35523df6-16bc-4f91-8bdc-9b887b399286)

Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.21.0-rc.2]

**Comment by AlexeyGirin** [comment]
After discussion with @olganaz and @vanoprenko desided to NOT delete data and throw an error
![image](https://github.com/user-attachments/assets/aa67cdb2-18f1-4e0d-90fa-78f913417b14)

**Comment by KristinaKasyanovskaya** [comment]
The behavior is correct according to the final solution.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/5616576a-1208-4f18-9479-7f0b516fbd7b)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by Zhirnoff** [comment]
Tested. Final decision: Throw an error message
![2024-08-07_11h52_42](https://github.com/user-attachments/assets/c1948453-3193-4a50-8a88-e13b85652083)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
