### ISSUE TITLE
Preview: Cannot select macro structures after Refresh before clearing the Canvas

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4632]
**Steps to Reproduce**
1. Switch to Macro 
2. RNA Builder add several Presents
3. Try to select structures on the Canvas
<img width="949" alt="image" src="https://github.com/epam/ketcher/assets/161723514/495488f3-08f3-4886-a658-2439aeb6d778">
4. Select Clear and add structures again

**Actual behavior**
Cannot select macro structures after Refresh before clearing Canvas

**Expected behavior**
Saved in the Ketcher IDT file should be opened
<img width="350" alt="Screenshot 2024-05-16 132615" src="https://github.com/epam/ketcher/assets/161723514/c2b342e4-9c75-4b03-a793-2a198aa1a1d1">

Related:
- https://github.com/epam/indigo/issues/1588
- https://github.com/epam/ketcher/issues/4495

Win11
Chrome: Version 123.0.6312.123 (Official Build) (64-bit)

Ketcher
[Version 2.22-rc.1] CI
[Indigo Toolkit] CI
Version 1.21.0-rc.1

**Comment by ilya-asiyuk-epam** [comment]
@NadezhdaPeskun , I cannot reproduce this defect today. Looks like it is not relevant so far.
Please verify from your side.

**Comment by NadezhdaPeskun** [comment]
Verified on CI. It's fixed with Saving RNA Presets.
