### ISSUE TITLE
Preview: In case of peptide monomers are on canvas, error "Cannot save molecule in IDT format - monomer(s) … doesn’t have IDT code." should appear.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4634]
**Steps to Reproduce**
1. Switch to Macro 
2. Open example of KET file with Peptides
[ketcher (end peptide).zip](https://github.com/epam/ketcher/files/15335921/ketcher.end.peptide.zip)
[ketcher (middle Peptide).zip](https://github.com/epam/ketcher/files/15335922/ketcher.middle.Peptide.zip)

3. try to Save as IDT

**Actual behavior**
Incorrect error message about Peptides
<img width="722" alt="peptides to IDT" src="https://github.com/epam/ketcher/assets/161723514/93d97d76-a926-46de-b321-1dbd4beeffed">

**Expected behavior**
According to 
- https://github.com/epam/ketcher/issues/4495
In case of peptide monomers are on canvas, error "Cannot save molecule in IDT format - monomer(s) … doesn’t have IDT code." should appear.

Win11
Chrome: Version 123.0.6312.123 (Official Build) (64-bit)

Ketcher
[Version 2.22-rc.1] CI
[Indigo Toolkit] CI
Version 1.21.0-rc.1

**Comment by olganaz** [comment]
Desired Error message: 
"Cannot save molecule in IDT format - monomer… doesn’t have IDT code."

**Comment by NadezhdaPeskun** [comment]
Should be moved to INDIGO

**Comment by NadezhdaPeskun** [comment]
Moved to Indigo https://github.com/epam/Indigo/issues/1957
