### ISSUE TITLE
When selecting a nucleotide or nucleoside together with a separate sugar/base/peptide/CHEM, the option “Modify in RNA builder” in the Right-click menu should be inactive

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4635]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Sequence mode
2.	Open this file [Nucleotides and nucleosides.zip](https://github.com/epam/ketcher/files/15338846/Nucleotides.and.nucleosides.zip)
3.	Select a nucleotide or nucleoside together with any separate sugar (or base, or peptide, or CHEM)
4.	Right-click on selected elements

**Actual behavior**
The option “Modify in RNA builder” in the Right-click menu is active
<img width="187" alt="image" src="https://github.com/epam/ketcher/assets/139227567/acb08b05-6d3f-491c-892c-34f0c7f7c35b">

**Expected behavior**
The option “Modify in RNA builder” in the Right-click menu is inactive
<img width="188" alt="image" src="https://github.com/epam/ketcher/assets/139227567/3d2f9afc-b32c-4956-8d54-c7af13afe3a7">

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/5f565366-ea4e-4fc8-9be1-54a7edfd487f

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.201 ) x64

**Ketcher version** 2.21.0-rc.2, Build at 2024-05-16; 12:32:02

Issue found while testing https://github.com/epam/ketcher/issues/3824, https://github.com/epam/ketcher/issues/4388

**Comment by Guch1g0v** [comment]
Possibly already fixed

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/423b92a9-a3ae-4118-87f9-17c4d3eec1c6)

Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
Indigo Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
Win 10
Chrome Version 126.0.6478.127 (Official Build) (64-bit)
