### ISSUE TITLE
In the Sequence mode, when selecting elements on the canvas, the total number of elements is not displayed in the Right-click menu

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4636]
**Steps to Reproduce**
1.	Switch to the Macro mode 
2.	Add this structure to the canvas
        <img width="218" alt="image" src="https://github.com/epam/ketcher/assets/139227567/97df6092-c517-4fd4-8279-ea36b04776f6">
3.	Switch to the Sequence mode
        <img width="99" alt="image" src="https://github.com/epam/ketcher/assets/139227567/d82b92ec-fe77-4e95-97e8-53bdc398dd89">
4.	Select the entire sequence and Right-click on it

**Actual behavior**
In the Right-click menu, the total number of nucleotides is displayed
<img width="219" alt="image" src="https://github.com/epam/ketcher/assets/139227567/6f4d15f1-6605-4d81-ac69-45678c704140">

**Expected behavior**
In the Right-click menu, the total number of elements is displayed
<img width="204" alt="image" src="https://github.com/epam/ketcher/assets/139227567/dfdfd971-25c2-4c65-ba36-31751cf5b682">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.201 ) x64

**Ketcher version** 2.21.0-rc.2, Build at 2024-05-16; 12:32:02

Issue found while testing https://github.com/epam/ketcher/issues/3824

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-03_09h49_07](https://github.com/epam/ketcher/assets/62464241/9c370e19-7f9c-4303-b866-142b1106303e)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]
