### ISSUE TITLE
Preview: Presets saved to local storage appear on canvas after switching Macro/Micro modes

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4640]
**Steps to Reproduce**
1. Switch to Macro mode
2. Add any preset to 'Presets' section using RNA Builder
3. Switch to Micro mode and back to Macro
4. The preset is not visible on the canvas, but it is there (if you click Save, you can see in preview that there are monomers on canvas)
5. Switch any of 'Snake' or 'Sequence' layout modes and presets will appear on canvas

**Actual behavior**
Presets saved to local storage appear on canvas after switching layout modes

**Expected behavior**
Presets saved to local storage not appear on canvas after switching layout modes

**Screenshots**

![2024-05-17_13h16_35](https://github.com/epam/ketcher/assets/62464241/05ceadbd-5d87-44df-bc6b-f04104a96897)

https://github.com/epam/ketcher/assets/62464241/e2e4988a-50d5-4857-81b5-2fc1504fdce6

Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.1] local master build

**Comment by ilya-asiyuk-epam** [comment]
TODO:
simplify/update code from this PR - https://github.com/epam/ketcher/pull/4512

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
