### ISSUE TITLE
Some bonds remain selected on export to SVG in Snake mode

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4658]
**Steps to Reproduce**
1. Switch to Macro
2. Load from file: [Some bonds remain selected.zip](https://github.com/epam/ketcher/files/15375542/Some.bonds.remain.selected.zip)
3. Switch to Flex mode
4. Select all elements on the canvas (press CTRL+A)
5. Export canvas to SVG

**Actual behavior**
Some bonds remain selected:
![image](https://github.com/epam/ketcher/assets/26869421/66f1eb1f-9ebe-44f1-bf98-c22851f70512)

**Expected behavior**
All selection is removed
![image](https://github.com/epam/ketcher/assets/26869421/697dd01b-3f94-4c79-bb24-c246d6b5b46e)

As per requirements:

> Temporary objects(monomer preview near cursor, css cursor, **selectors** and e.t.c) should not be included into image.

**Versions** [e.g. v2.4.2]. 
 - Indigo Toolkit Version 1.21.0-dev.3.0-g6f55c664-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.21.0-rc.2 Build at 2024-05-20; 05:30:45
 - Chrome Version 124.0.6367.201 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4539

**Comment by KristinaKasyanovskaya** [comment]
> Not fixed.
> Bonds remain slightly selected

Fix https://github.com/epam/ketcher/pull/5219

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-09-05_11h26_12](https://github.com/user-attachments/assets/e10f72b0-2d99-449a-9715-185b81b0c459)
![2024-09-05_11h26_51](https://github.com/user-attachments/assets/6e089347-98dc-464a-90f5-c2db40d5e855)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
