### ISSUE TITLE
Zero charge shows explicit 0 instead of blank after using A+/A- Tools

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4660]
**Steps to Reproduce**
1. Open Ketcher
2. Add any atom on canvas
3. Select Charge plus (A+) and click on atom
4. Select Charge minus (A-) and click on atom

**Actual behavior**
Zero charge shows explicit 0 instead of blank after using A+/A- Tools

**Expected behavior**
Zero charge shows blank after using A+/A- Tools

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/7e9a5a4a-4fd7-4691-a3bf-b6e7bf625722

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.21.0-rc.2]

#187636068

**Comment by AnnaKosol** [comment]
Verified

https://github.com/epam/ketcher/assets/174325443/23783c00-6abd-45b4-b146-f8fa2c5d712e


**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-07-11_14h56_51](https://github.com/epam/ketcher/assets/62464241/bc9e9e95-5453-49bc-bfaa-2003996b5c2e)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.2]
**Indigo version** 
[Version 1.22.0-rc.2]
