### ISSUE TITLE
Preview: When zooming via the Ketcher API, the program reacts to input of values, not from a valid range

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4670]
**Steps to Reproduce**
1.	Switch to the Macro mode 
2.	Add any nucleotide on the canvas
        <img width="135" alt="image" src="https://github.com/epam/ketcher/assets/139227567/49c185ee-c08a-4f79-9e8f-ba1c0d3e50aa">
3.	In the Console enter ketcher.setZoom(20) (instead of 20 you can substitute any value greater than 4) and press the “Enter” key
4.	In the Console enter ketcher.setZoom(-20) (instead of -20 you can substitute any value less than -4) and press the “Enter” key

**Actual behavior**
The program reacts to input of values, not from a valid range 

<img width="914" alt="image" src="https://github.com/epam/ketcher/assets/139227567/beba5393-bcd3-4da8-a00b-bb34df9d86bd">
<img width="920" alt="image" src="https://github.com/epam/ketcher/assets/139227567/6e6d0866-1a3d-4635-bbd9-098236269433">

**Expected behavior**
The program reacts to input values only from a valid range (-4, -3, -2, -1, 0, 1, 2, 3, 4)

As per requirements:
•	ketcher.setZoom(zoom) - zoom: number (-4, -3, -2, -1, 0, 1, 2, 3, 4)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (124.0.6367.201) x64

**Ketcher version** 2.21.0-rc.2, Build at 2024-05-20; 11:00:53

Issue found while testing https://github.com/epam/ketcher/issues/4539

**Comment by AlexeyGirin** [comment]
Not a bug - requirements has been clarified - valid range for zoom parameter: [0.2 ... 4]
If value is out of range - system tooks closed value from range
