### ISSUE TITLE
Wrong sequence if sequence with cycle is saved to FASTA or Sequence file.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4679]
**Steps to Reproduce**
1. Switch to Macro 
2. Open file
[ketcher (modify (1)).zip](https://github.com/epam/ketcher/files/15413934/ketcher.modify.1.zip)

3. Try to save to FASTA of Sequence file

**Actual behavior**
Wrong sequence (GCG) is saved to FASTA or Sequence file  instead of GGC.
![wrong sequence](https://github.com/epam/ketcher/assets/161723514/74b33a78-f5a8-4ce9-bf47-890d9a135182)

![wrong sequence2](https://github.com/epam/ketcher/assets/161723514/c56187b1-8dea-4075-ba09-e5f54c787d19)

**Expected behavior**
Sequence should be GGC as on the Canvas

please see
- https://github.com/epam/ketcher/issues/4575
- https://github.com/epam/ketcher/issues/4690

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0

**Comment by Guch1g0v** [comment]
Perhaps the bug has already been fixed
![Screenshot from 2024-06-28 10-16-18](https://github.com/epam/ketcher/assets/117785539/d9e6046d-6431-4fa0-98ed-296e8cebae59)
![Screenshot from 2024-06-28 10-15-33](https://github.com/epam/ketcher/assets/117785539/0bd86366-7341-4093-a8f8-20d6dffeaf61)
[ketcher_4679.zip](https://github.com/user-attachments/files/16024579/ketcher_4679.zip)

**Comment by Guch1g0v** [comment]
Fasta and sequence converts indigo, we also need to decide whether it is necessary to somehow select the first element in the case of a cyclic sequence, if necessary, then in what way?

**Comment by AlexeyGirin** [comment]
MOved to indigo - https://github.com/epam/Indigo/issues/2042
