### ISSUE TITLE
Preview: After moving the structure in the Macro mode, in the Micro mode the S-group value is displayed separately from the structure

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4686]
**Steps to Reproduce**
1.	Draw any Templates with an S-group of type “Data” (it can be applied to a specific bond or the entire structure)
 
<img width="721" alt="image" src="https://github.com/epam/ketcher/assets/139227567/413570a9-f94c-45c2-8466-8759a37c061a">

2.	Switch to the Macro mode 
3.	Move the structures to the opposite side of the canvas
4.	Switch to the Micro mode again

**Actual behavior**
The S-group value is displayed separately from the structure (the value does not move with the structure)

<img width="724" alt="image" src="https://github.com/epam/ketcher/assets/139227567/d1734ba4-0882-4091-9156-8e347d4c99b6">

**Expected behavior**
The S-group value is displayed together with the structure (the value moves together with the structure)

<img width="729" alt="image" src="https://github.com/epam/ketcher/assets/139227567/0bfee4db-4bd6-4ea0-9c34-523a1f56d036">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (125.0.6422.61) x64

**Ketcher version** 2.21.0-rc.2, Build at 2024-05-20; 11:00:53

Issue found while testing https://github.com/epam/ketcher/issues/4531

**Comment by Zhirnoff** [comment]
Tested.
![2024-07-03_11h06_33](https://github.com/epam/ketcher/assets/62464241/ac16bcb8-dedf-4dd8-82b6-26e6387c0e8e)
![2024-07-03_11h07_08](https://github.com/epam/ketcher/assets/62464241/bc3a04a5-e9e1-495d-89e9-7002e0d25f8c)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]
