### ISSUE TITLE
Undo problem while layout is changed on the Snack of Flex modes and switch through modes.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/ketcher#4690]
**Steps to Reproduce**

1. Switch to Macro 
2. go to Sequence mode 
3. Open File 
[ketcher (51).zip](https://github.com/epam/ketcher/files/15433411/ketcher.51.zip)
4. Snack of Flex modes
5. change layout of cycling second sequence
6. Switch to Sequence mode

**Actual behavior**
Undo problem while layout is changed on the Snack of Flex modes and switch through modes.
Several steps of UNDU actions have broken peptide Bonds or Bonds are lost.
Kindly see video file.

https://github.com/epam/ketcher/assets/161723514/b2ca6194-39dc-43fe-bc98-7f3340d3b611

**Expected behavior**
Undo should correspond Redo actions without broken bonds.

Possible related with 
- https://github.com/epam/ketcher/issues/4679
- https://github.com/epam/ketcher/issues/4575

**Versions:**
[Version 2.21.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)
    Build at 2024-04-29; 09:29:15

Indigo Toolkit
    Version 1.20.0-rc.1.0-g8e8ffc3c3-x86_64-linux-gnu-11.2.1

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/f9d3325b-7af3-422e-b8a2-f1d18cd00593)
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.3 Build at 2024-06-10; 12:34:49
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
