### ISSUE TITLE
Macro: Cursors should be copied from small mode

### ISSUE THREAD

**Issue by ilya-asiyuk-epam** [epam/ketcher#4692]
**Background**
Cursors in Micro and Macro are different.

**Solution**
Cursors should we unified.
Namely:
1. Replace '[crosshair](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/crosshair.gif)' cursor to '[default](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/default.gif)' for the whole canvas
2. Set '[move](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/move.gif)' cursor for structures if they can be moved.
3.  Use '[default](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/default.gif)' cursor for structures if they cannot be moved

**Comment by Zhirnoff** [comment]
Tested. We have two open bugs.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
