### ISSUE TITLE
Need to create the warning message in the case if user tries to save incorrect structure in non-Mol format

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#47]
It was decided to implement the next logic:

When user creates any structure that contains any incorrect properties, settings etc., when "Check Structure" contains any warnings or errors and then user tries to save such structure,  the warning message should appear and warn user that this structure contains errors or incorrectness and user can lose some properties or the whole structure after saving in this format. 

New saving format will possibly able to solve these problems. 

[SavedDifferentTypesStructuresDifFormats_Edited052018.zip](https://github.com/epam/ketcher/files/5182336/SavedDifferentTypesStructuresDifFormats_Edited052018.zip)

**Comment by AndreiMazol** [comment]
The issue is done (see #80 )
