### ISSUE TITLE
Unify toolbars with small molecules mode

### ISSUE THREAD

**Issue by ilya-asiyuk-epam** [epam/ketcher#4701]
**Solution**
Update left and top bars in Macro mode according to buttons positions in Micro.
3 zoom buttons (+, -, reset) of Macro mode replace to a selector (like in Micro mode)

**Comment by Zhirnoff** [comment]
Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
