### ISSUE TITLE
Preview: A new nucleotide should not be added to the end of a cyclic sequence, if the last nucleotide of the sequence does not have a free AP R1 or R2

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4706]
**Steps to Reproduce**
1.	Switch to the Macro mode 
2.	Draw a cyclic sequence, consisting of any 4 nucleotides, for example:
 
       <img width="332" alt="image" src="https://github.com/epam/ketcher/assets/139227567/250063a6-1f60-4468-aebf-c3e11eb6d895">

3.	Switch to the Sequence mode - the Text-editing mode
 
       <img width="115" alt="image" src="https://github.com/epam/ketcher/assets/139227567/34c4e7ac-eae7-4653-994a-501d4ac502b8">

4.	Add any nucleotide to the end of this sequence
5.	Switch to the Flex mode and move all nucleotides apart from each other so that all bonds are visible

**Actual behavior**
A new nucleotide is added to the end of a cyclic sequence. The bond, that provided and displayed cyclicity, disappears in the Sequence mode and the Flex mode
<img width="126" alt="image" src="https://github.com/epam/ketcher/assets/139227567/0a93735c-dd8c-49f1-953b-0bc92567a439">
<img width="417" alt="image" src="https://github.com/epam/ketcher/assets/139227567/8d207bb6-dbd9-4447-bf4c-a513ad6405a7">

**Expected behavior**
A new nucleotide should not be added to the end of a cyclic sequence, if the last nucleotide of the sequence does not have a free AP R1 or R2. An error message appears on the canvas (From BA):

Error Message:
It is impossible to merge fragments. Attachment point to establish bonds are not available. 

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/a8d29b43-c951-4a10-9e64-3676a8d50006

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (125.0.6422.61) x64

**Ketcher version** 2.21.0-rc.2, Build at 2024-05-28; 14:29:04

related with 
- https://github.com/epam/ketcher/issues/4548

**Comment by NadezhdaPeskun** [comment]
Should be verified with next Issues: (4708, 4575, 4506,4706) + 4328
Error Message should appear:
Error Message:
It is impossible to merge fragments. Attachment point to establish bonds are not available.

**Comment by NadezhdaPeskun** [comment]
Should be verified with next Issues: (4708, 4575, 4506,4706) + 4328
Error Message should appear:
Error Message:
It is impossible to merge fragments. Attachment point to establish bonds are not available.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/ec0c2702-a8b7-422f-bc5b-f01640771873)


 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

**Comment by Zhirnoff** [comment]
Automated.
