### ISSUE TITLE
When merging two cyclic sequences in the Sequence mode, they disappear from the canvas

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4708]
**Steps to Reproduce**
1.	Switch to the Macro mode 
2.	Draw two cyclic sequences, consisting of any 4 nucleotides, for example:
 
       <img width="344" alt="image" src="https://github.com/epam/ketcher/assets/139227567/c4d7a489-6d89-47ec-a99b-700f0f84732a">

3.	Switch to the Sequence mode – the Text-editing mode
 
       <img width="120" alt="image" src="https://github.com/epam/ketcher/assets/139227567/ed69e658-ac72-42a8-8ba4-3115d454051f">

4.	Try to merge these two sequences
 
      <img width="183" alt="image" src="https://github.com/epam/ketcher/assets/139227567/b931094b-7d6a-428f-a846-16983b258138">

5.	Switch to the Flex mode and move all nucleotides apart from each other so that all bonds are visible

**Actual behavior**
In the Sequence mode, the cyclic sequences disappear from the canvas. But in the Flex mode, a new bond between two cyclic sequences is displayed, although there are no free APs in these two sequences

<img width="337" alt="image" src="https://github.com/epam/ketcher/assets/139227567/20731115-804f-4119-bd0d-acb6f6f4a19f">

<img width="407" alt="image" src="https://github.com/epam/ketcher/assets/139227567/efd60408-6c29-476e-85ac-36c4c3b3b229">

<img width="393" alt="image" src="https://github.com/epam/ketcher/assets/139227567/35cfb228-ef58-4bdb-916e-2cc3dca52089">

**Expected behavior**
If the nucleotides on the ends of sequences do not have a free AP R1 or R2 at the place, where they merge, an error message appears on the canvas

Error Message:
It is impossible to merge fragments. Attachment point to establish bonds are not available. 

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/3c377939-5203-43d3-879f-6468b1350f1a

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (125.0.6422.113) x64

**Ketcher version** 2.21.0-rc.2, Build at 2024-05-28; 14:29:04

Can be related https://github.com/epam/ketcher/issues/4548, https://github.com/epam/ketcher/issues/4706

**Comment by NadezhdaPeskun** [comment]
Should be verified with next Issues: (4708, 4575, 4506,4706) + 4328
Error Message should appear:
Error Message:
It is impossible to merge fragments. Attachment point to establish bonds are not available.

**Comment by AlexeyGirin** [comment]
Not fixed.
Both sequences simply disappears from the canvas.

0. Switch to Macro
1. Load from file: [two cycles.zip](https://github.com/user-attachments/files/15546142/two.cycles.zip)
2. Go to Sequence mode
3. Edit top sequence
4. Put cursor at the end of the line
5. Press Del button

**Actual behavior:**
Both sequences simply disappears from the canvas.
![image](https://github.com/epam/ketcher/assets/26869421/2d6bd7e4-50c4-4da6-b2a9-4a498e7a9a44)

**Expected behavior:**
Error message appears:
![336392272-ec0c2702-a8b7-422f-bc5b-f01640771873](https://github.com/epam/ketcher/assets/26869421/606e4b44-63b0-47da-8cac-60473654eb0b)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/826d6a2a-148a-4ec9-8b23-23a6782662bf)

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.3 Build at 2024-06-10; 12:34:49
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
