### ISSUE TITLE
Separate selenocysteine from cysteine and pyrrolysine from lysine

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4722]
Selenocysteine is a separate amino acid from cysteine. 
It should have its own section in the library under the symbol U containing the following monomers:
seC (new symbol U) and  dSec (new symbol dU)

Pyrrolysine is a separate amino acid from lysine. 
It should have its own section in the library under the symbol O containing the following monomers:
Pyl (new symbol O) and dPyl( new symbol dO)

**Comment by AlexeyGirin** [comment]
Verified.
![Image](https://github.com/user-attachments/assets/0fa49543-5f5c-4500-aef0-c0f20af75187)

- Ketcher Version 3.1.0-rc.2 Build at 2025-02-07; 15:09:23
- Indigo Version 1.29.0-rc.1.0-g2e30df8f7-wasm32-wasm-clang-19.0.0
- Chrome Version 133.0.6943.54 (Official Build) (64-bit)
- Win10
