### ISSUE TITLE
Pasting IDT structures via clipboard does not work 

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4739]
**Steps to Reproduce**
1. Open Macro mode
2. Copy to clipboard IDT `/32MOErA/`
3. Paste to canvas

**Actual behavior**
Pasting IDT structures via clipboard does not work

**Expected behavior**
Structure pasted on canvas

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.1]

**Comment by rrodionov91** [comment]
Changed ketcher behaviour to send string from clipboard to indigo and rely on it's format autodetection algorithm in case if ketcher didn't recognize format.
Indigo ticket for IDT format autodetection https://github.com/epam/Indigo/issues/1989
