### ISSUE TITLE
When changing zoom level in macro mode, there is no percentage indication

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4744]
**Steps to Reproduce**
1. Switch to Macro mode
2. Add any monomer on canvas
3. Change zoom by buttons or hotkeys
4. Switch to Micro mode and back to Macro
5. Change zoom by buttons or hotkeys

**Actual behavior**
When changing zoom level in macro mode, there is no percentage indication

**Expected behavior**
When changing zoom level in macro mode, a percentage indication should be displayed like in Micro mode

**Screenshots**

![2024-06-04_15h39_44](https://github.com/epam/ketcher/assets/62464241/d7450239-8b31-4f89-adc7-222944d5d05b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]

Bug found during testing: https://github.com/epam/ketcher/issues/4701

**Comment by rrodionov91** [comment]
Does not reproduce

**Comment by Zhirnoff** [comment]
Reproduced after switch between micro/macro mode

**Comment by Zhirnoff** [comment]
![2024-06-10_16h22_59](https://github.com/epam/ketcher/assets/62464241/9fddcd5b-86dc-4199-b0f1-57980db6f32a)

Tested. Bug fixed.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.3]
**Indigo version** 
[Version 1.21.0-rc.1]
