### ISSUE TITLE
Incorrect stereo-label placement for (E) and (Z)

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4757]
**Steps to Reproduce**
1. Go to Ketcher micromolecules mode.
2. Draw any structure containing cis/trans isomerism. For example:
![image](https://github.com/epam/ketcher/assets/169887211/375a5999-edf5-48c8-8a62-4005ce6e708e)
3. Select Calculate CIP.

**Actual behavior**
Ketcher displays the stereo-label towards the end of the bond.
![image](https://github.com/epam/ketcher/assets/169887211/bf72b802-be3b-46ac-b604-aa480a9ab005)

**Expected behavior**
Ketcher should display the label in the center of the double bond, overlapping with it.

Ketcher version v2.22.0

**Comment by AlexeyGirin** [comment]
Rose the priority since Ljubica found it is common problem and in many places we put label in unusual place

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/d8b1cb71-0ae6-417e-a4a4-3e9400649bb3)

**Versions**
- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10
