### ISSUE TITLE
It is impossible to apply R-group to atom with attachment point attached

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4773]
**Steps to Reproduce**
1. Load from file: [It is impossible to apply R-group to atom with attachment point attached.zip](https://github.com/user-attachments/files/15613771/It.is.impossible.to.apply.R-group.to.atom.with.attachment.point.attached.zip)
OR manually create following configuration on the canvas:
![image](https://github.com/epam/ketcher/assets/26869421/547621c2-8020-4725-bbbb-5d12ba8b1760)
2. Select R-Group label tool
![image](https://github.com/epam/ketcher/assets/26869421/550b8fa7-8a82-459f-a954-32fadd004a31)
3. Click on atom R1 attachment point connected to
![image](https://github.com/epam/ketcher/assets/26869421/46887f9b-a6c8-4141-a756-bf43b346d0c9)

**Actual behavior**
System rises Edit Abbreviation dialog but it doesn't work - it is not possible to add atom to r-group in any option (Remove Abbreviation or Exit) selected
![image](https://github.com/epam/ketcher/assets/26869421/13610a34-618b-4dd1-91ec-89fefdf2156c)

**Expected behavior**
1. System shouldn't open Edit Abbreviation dialog
2. R-group selection dialog should appear (and it should be possible to set r-group)
![image](https://github.com/epam/ketcher/assets/26869421/975676ad-0191-4e97-899e-b58754d760d5)

As per [requirements](https://github.com/epam/ketcher/issues/4530):

> What happens if I apply R-Group on AP label?
> No, since AP is not an atom - its a label connected to atom by bond (we can do that with atom AP label connected to)

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by AnnaKosol** [comment]
Verified

https://github.com/epam/ketcher/assets/174325443/2e44605c-8425-413f-bf6b-94a291000617

**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
