### ISSUE TITLE
It is not possible to wrap molecule into R-Group if it has attachment point (at least one)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4775]
**Steps to Reproduce**
1. Load from file: [It is impossible to apply R-group to atom with attachment point attached.zip](https://github.com/user-attachments/files/15613771/It.is.impossible.to.apply.R-group.to.atom.with.attachment.point.attached.zip)
OR manually create following configuration on the canvas:
![image](https://github.com/epam/ketcher/assets/26869421/547621c2-8020-4725-bbbb-5d12ba8b1760)
2. Select R-Group Fragment Tool
![image](https://github.com/epam/ketcher/assets/26869421/8a06d8f2-1229-4048-9015-aa0bbea35924)
3. Click on molecule
![image](https://github.com/epam/ketcher/assets/26869421/bb0ea28e-aa91-4b21-a6e9-005a6f311852)

**Actual behavior**
System rises Edit Abbreviation dialog but it doesn't work - it is not possible to wrap molecule to r-group in any option (Remove Abbreviation or Exit) selected
![image](https://github.com/epam/ketcher/assets/26869421/ce5d5e18-aecf-407e-8cec-233b19895faa)

**Expected behavior**
1. System shouldn't open Edit Abbreviation dialog
2. R-group selection dialog should appear (and it should be possible to wrap molecule to r-group)
![image](https://github.com/epam/ketcher/assets/26869421/975676ad-0191-4e97-899e-b58754d760d5)

As per [requirements](https://github.com/epam/ketcher/issues/4530):

> Can I wrap atom/molecule with AP to R-Group fragment tool?
> No, since AP is not an atom - its a label connected to atom by bond (we can do that with atom AP label connected to)

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-03_10h21_48](https://github.com/epam/ketcher/assets/62464241/9f95a845-2639-4b41-ba52-de52c4315889)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]
