### ISSUE TITLE
System rises Edit Abbreviation dialog if we click on AP label with Attachment Point  Tool

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4776]
**Steps to Reproduce**
1. Load from file: [It is impossible to apply R-group to atom with attachment point attached.zip](https://github.com/user-attachments/files/15613771/It.is.impossible.to.apply.R-group.to.atom.with.attachment.point.attached.zip)
OR manually create following configuration on the canvas:
![image](https://github.com/epam/ketcher/assets/26869421/547621c2-8020-4725-bbbb-5d12ba8b1760)
2. Select Attachment Point Tool tool
![image](https://github.com/epam/ketcher/assets/26869421/b0e6f058-5cf1-4e41-8cac-544e2f54b6a4)
3. Click on attachment point R1 label
![image](https://github.com/epam/ketcher/assets/26869421/a1f1e174-c241-4579-994f-648b9f43b840)

**Actual behavior**
System rises Edit Abbreviation dialog
![image](https://github.com/epam/ketcher/assets/26869421/13610a34-618b-4dd1-91ec-89fefdf2156c)

**Expected behavior**
1. System shouldn't open Edit Abbreviation dialog
2. It is not possible add 'old' attachment point to 'new' attachment point (i.e. its label), nothing should happen in that case

As per [requirements](https://github.com/epam/ketcher/issues/4530):

> Can I attach "old" AP to new AP?
> No, since AP is not an atom - its a label connected to atom by bond (we can do that with atom AP label connected to)

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by Zhirnoff** [comment]
Tested. Bug fixed but we have another one https://github.com/epam/ketcher/issues/4969

https://github.com/epam/ketcher/assets/62464241/14ec1120-35e5-4c75-ac9e-22e1167df4d7



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]
