### ISSUE TITLE
Charge tools (i.e. A+/A- buttons) doesn't work on any atom of molecule if it has at least one attachment point connected to any atom

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4779]
**Steps to Reproduce**
1. Load from file: [It is impossible to apply R-group to atom with attachment point attached.zip](https://github.com/user-attachments/files/15613771/It.is.impossible.to.apply.R-group.to.atom.with.attachment.point.attached.zip)
OR manually create following configuration on the canvas:
![image](https://github.com/epam/ketcher/assets/26869421/547621c2-8020-4725-bbbb-5d12ba8b1760)
2. Select any charge button A+ or A-
![image](https://github.com/epam/ketcher/assets/26869421/b0e6f058-5cf1-4e41-8cac-544e2f54b6a4)
3. Click on atom attachment point R1 label connected to
![image](https://github.com/epam/ketcher/assets/26869421/0c99617d-3137-41a1-970e-d9bb879b2070)

**Actual behavior**
System rises Edit Abbreviation dialog
![image](https://github.com/epam/ketcher/assets/26869421/13610a34-618b-4dd1-91ec-89fefdf2156c)

**Expected behavior**
1. System shouldn't open Edit Abbreviation dialog
2. System add (or decrease) charge of atom:
![image](https://github.com/epam/ketcher/assets/26869421/84d94d4e-9186-4acf-a0dd-371966ba7a29)

As per [requirements](https://github.com/epam/ketcher/issues/4530):

> Can I charge (A+/A-) AP?
> No, since AP is not an atom - its a label connected to atom by bond (we can do that with atom AP label connected to)

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by AnnaKosol** [comment]
Verified

https://github.com/epam/ketcher/assets/174325443/bf88e02e-9140-4251-979e-0f1f306fc4c2

**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
