### ISSUE TITLE
Remove monomers from the library (Peptides and CHEMs)

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4780]
Remove following peptides and CHEMs from the library:

- [x] Glp, pyroglutamic acid
- [x] Hyl5xi, (2S)-2-6-diamino-5-hydorxyhexanoic acid
- [x] Hiv, 2-hydroxyisovaleric acid
- [x] Maa, mercaptoacetic acid
- [x] Nty, nitrotyrosine

**Comment by AlexeyGirin** [comment]
No test cases needed in that particular case

**Comment by AlexeyGirin** [comment]
Fixed.
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
No test cases needed for that particular case
