### ISSUE TITLE
Change names of monomers (Peptides and CHEMs)

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4781]
Change the names of following peptides and CHEMs in the library (symbol, (new symbol), old name -> new name):

- [x] Az, Azide -> 4-azidobutyric acid
- [x] hxy, Hexynyl alcohol -> 5-hexyn-1-ol
- [x] SMCC, SMCC linker from Pierce -> SMCC 
- [x] SMPEG2, SM(PEG)2 linker from Pierce -> SM(PEG)2
- [x] Ala-ol, (2S)-2-aminopropan-1-ol -> L-Alaninol
- [x] Cya, 3-sulfoalanine -> Cysteic acid
- [x] D-2Nal, D-3-naphthylalanine -> D-3-(2-naphtyl)-alanine
- [x] D-2Thi, D-3-thienylalanine -> 3-(2-thienyl)-D-alanine
- [x] D-Cha, D-2-Amino-3-cyclohexyl-propionic acid -> 3-cyclohexyl-D-alanine
- [x] D-OAla, (2R)-2-hydroxypropanoic acid -> D-Lactic acid
- [x] DAlaol, (2R)-2-aminopropan-1-ol -> D-alaninol
- [x] Dha, 2-aminoprop-2-enoic acid -> Dehydroalanine
- [x] Nal, 2Nal, 3-naphthylalanine -> 3-(2-naphthyl)-alanine
- [x] Thi, 3-thienylalanine -> 3-(2-thienyl)-alanine
- [x] Tza, 3-thiazolyalanine -> 3-(4-Thiazolyl)-alanine
- [x] seC, U, SelenoCysteine -> Selenocysteine
- [x] Cys_Bn, (2R)-2-amino-3-(benyulsulfanyl)propanoic acid -> S-benzylcysteine
- [x] Cys_Me, (2R)-2-amino-3-(methylsulfanyl)propanoic acid -> S-methylcysteine
- [x] dSec, dU, D-SelenoCysteine -> D-selenocysteine
- [x] AspOH, D*, Aspartic acid (OH) -> Aspartic acid*
- [x] AspOh2, Kyn, (2S)-2-amino-4-(2-aminophenyl)-4-oxobutanoic acid -> Kynurenine
- [x] aMePhe, (2S)-2-amino-2-methyl-3-phenylpropanoic acid -> alpha-methyl-L-phenylalanine
- [x] DAPhe, PhLA, Deamino-Phenylalanine -> 3-phenyllactic acid
- [x] DPhe4F, (2R)-2-amino-3-(4-fluorophenyl)propanoic acid -> 4-fluoro-D-phenylalanine
- [x] Phe_2F, (2S)-2-amino-3-(2-fluorophenyl)propanoic acid -> 2-fluoro-L-phenylalanine
- [x] Phe_3F, (2S)-2-amino-3-(3-fluorophenyl)propanoic acid -> 3-fluoro-L-phenylalanine
- [x] Phe_4F, (2S)-2-amino-3-(4-fluorophenyl)propanoic acid -> 4-fluoro-L-phenylalanine
- [x] Phe_4I, (2S)-2-amino-3-(4-iodophenyl)propanoic acid -> 4-iodo-L-phenylalanine
- [x] Phe-ol, (2S)-2-amino-3-phenylpropan-1-ol -> L-phenylalaninol
- [x] Phe2Me, (2S)-2-amino-3-(2-methylphenyl)propanoic acid -> 2-methyl-L-phenylalanine
- [x] Phe34d, (2S)-2-amino-3-(3,4-dichlorophenyl)propanoic acid -> 3,4-dichloro-L-phenylalanine
- [x] Phe4Br, (2S)-2-amino-3-(4-bromophenyl)propanoic acid -> 4-bromo-L-phenylalanine
- [x] Phe4NO, (2S)-2-amino-3-(4-nitrophenyl)propanoic acid -> 4-nitro-L-phenylalanine
- [x] PheaDH, 2-amino-3-phenylprop-2-enoic acid -> Dehydrophenylalanine
- [x] D-Phg, D-2-phenylglycine -> D-phenylglycine
- [x] DAGlyT, 2-(thiophen-2-yl)aceti acid -> 2-thiopheneacetic acid
- [x] DAPhg4, 2-(4-chlorophenyl)acetic acid -> 4-chlorophenylacetic acid
- [x] DPhgol, 2-amino-2-methylpropan-1-ol -> D-phenylglycinol
- [x] Phg, 2-phenylglycine -> L-phenylglycine
- [x] Phg-ol, (2S)-2-amino-phenylethan-1-ol -> L-phenylglycinol
- [x] Sar, meG, sarcosine (N-methylglycine -> Sarcosine 
- [x] His1Me, (2S)-2-amino-3-(1-methyl-1H-imidazol-4-yl)propanoic acid -> 1-methyl-L-histidine
- [x] His3Me, (2S)-2-amino-3-(1-methyl-1H-imidazol-5-yl)propanoic acid -> 3-methyl-L-histidine
- [x] DALys, Deamino-Lysine -> 6-amino-2-hydroxyhexanoic acid
- [x] dPyl, dO, DPyl -> D-pyrrolysine
- [x] Lys_Ac, (2S)-2-amino-6-acetamidohexanoic acid -> N-epsilon-acetyl-L-lysine
- [x] Pyl, O, Pyl -> Pyrrolysine
- [x] DALeu, Deamino-Leucine -> 4-methylpentanoic acid
- [x] Leu-ol, (2S)-2-amino-4-methylpentan-1-ol -> L-leucinol
- [x] OLeu, (2S)-2-hydroxy-4-methylpentanoic acid -> L-leucic acid
- [x] DMetSO, (2R)-2-amino-4-[(S)-metanesulfinyl]butanoic acid  -> L-methionine (S)-S-oxide
- [x] Met_O, (2S)-2-amino-4-methanesulfinylbutanoic acid -> L-methionine sulfoxide
- [x] Met_O2, (2S)-2-amino-4-methanesulfonylbutanoic acid -> L-methionine sulfone
- [x] aHyp, L-allo-4-hydroxyproline -> cis-4-hydroxy-L-proline
- [x] aMePro, (2S)-2-methylpyrrolidine-2-carboxylic acid -> alpha-methyl-L-proline
- [x] D-aHyp, D-allo-4-hydroxyproline -> cis-4-hydroxy-D-proline
- [x] D-Hyp, D-4-hydroxyproline -> trans-4-hydroxy-D-proline
- [x] DProol, [(2R)-pyrrolidin-2-yl]methanol -> D-prolinol
- [x] Hyp, 4-hydroxyproline -> trans-4-hydroxy-L-proline
- [x] Mhp, 4-methyl-3-hydroxyproline -> 3-hydroxy-4-methylproline
- [x] Pro-ol, [(2S)-pyrrolidin-2-yl]methanol -> L-prolinol
- [x] xiHyp, (2S)-4-hydroxypyrrolidine-2-carboxylic acid -> 4-hydroxy-L-proline
- [x] Arg-al, N"-[(4S)-4-amino-5-oxopentyl]guanidine -> Argininal
- [x] D-hArg, (2R)-2-amino-6-[(diaminomethylidene)amino]hexanoic acid -> D-homoarginine
- [x] SerPO3, (2S)-2-amino-3-(phosphonooxy)propanoic acid -> O-phospho-L-serine
- [x] DThrol, (2R,3R)-2-aminobutane-1,3-diol -> L-threoninol
- [x] Thr-ol, (2S,3S)-2-aminobutane-1,3-diol -> D-threoninol
- [x] ThrPO3, (2S,3R)-2-amino-3-(phosphonooxy)butanoic acid -> O-phospho-L-threonine
- [x] D-OVal, (2R)-2-hydroxy-3-methylbutanoic acid -> D-2-hydroxyisovaleric acid
- [x] D-Pen, D-penicillamine (3-mercaptovaline) -> D-penicillamine
- [x] L-OVal, (2S)-2-hydroxy-3-methylbutanoic acid -> 2-hydroxyisovaleric acid
- [x] Pen, penicillamine (3-mercaptovaline) -> Penicillamine
- [x] Tle, tLeu, 3-methylvaline -> L-tert-leucine
- [x] Val-ol, (2S)-2-amino-3-methylbutan-1-ol -> L-valinol
- [x] Val3OH, (2S)-2-amino-3-hydroxy-3-methylbutanoic acid -> 3-hydroxy-L-valine
- [x] DTrp2M, (2R)-2-amino-3-(2-methyl-1H-indol-3-yl)propanoic acid -> 2-methyl-D-tryptophan
- [x] DTrpFo, (2R)-2-amino-3-(1-formyl-1H-indol-3-yl)propanoic acid -> 1-formyl-D-tryptophan
- [x] Trp_Me, (2S)-2-amino-3-(1-methyl-1H-indol-3-yl)propanoic acid -> 1-methyl-L-tryptophan
- [x] Trp5OH, (2S)-2-amino-3-(5-hydroxy-1H-indol-3-yl)propanoic acid -> 5-hydroxy-L-tryptophan
- [x] -Bn, C-Terminal toluene -> C-Terminal benzyl
- [x] -NHBn, C-Terminal 1-phenylmethaneamine -> C-Terminal benzylamino
- [x] 2Abz, 2-Aminobenzoic acid -> Anthranilic acid
- [x] Aad, 2-aminoadipic acid -> L-2-aminoadipic acid
- [x] Abu, 2-aminobutanoic acid -> L-2-aminobutyric acid
- [x] Abu23D, 2-aminobut-2-enoic acid -> (2Z)-2-aminobut-2-enoic acid
- [x] ac, Ac-, N-Terminal Acetic Acid -> N-Terminal acetyl
- [x] Ac6c, 1-aminocyclohexane-1-carboxylic acid -> Homocycloleucine
- [x] Aca, 2-aminocapric acid -> L-decyline
- [x] Aib, alpha-aminoisobutyric acid (2-aminoalanine) -> 2-aminoisobutyric acid
- [x] am, Am-, C-Terminal amine -> C-Terminal amino
- [x] Amp, 2-aminopimelic acid -> L-2-aminopimelic acid
- [x] App, gamma-amino-beta-hydroxybenzeneptanoic acid -> (3R,4S)-4-amino-3-hydroxy-5-phenylpentanoic acid
- [x] Asu, 2-aminosuberic acid -> (R)-2-aminooctanedioic acid
- [x] Aze, 2-carboxyazetidine -> L-azetidine-2-carboxylic acid
- [x] Bip, (2S)-2-amino-3-{[1,1'-biphenyl]-4-yl}propanoic acid -> Biphenylalanine
- [x] Bmt, (2S,3R,4R)-2-amino-3-hydroxy-4-methyloct-6-enoic acid -> (2S,3R,4R,6E)-2-amino-3-hydroxy-4-methyloct-6-enoic acid
- [x] Bn-, N-Terminal toluene -> N-Terminal benzyl
- [x] Boc, Boc-, Tert-butyloxycarbonyl -> N-Terminal tert-butyloxycarbonyl
- [x] Bpa, (2S)-2-amino-3-(4-benzoylphenyl)propanoic acid -> 4-benzoylphenylalanine
- [x] Bua, Bua-, butanoic acid -> N-Terminal butanoyl
- [x] Bux, 4-amino-3-hydroxybutanoic acid -> (3S)-4-amino-3-hydroxybutanoic acid
- [x] Bz, Bz-, Benzaldehyde -> N-Terminal benzoyl
- [x] Cap, gamma-amino-beta-hydroxycyclohexanepentanoic acid -> (2R,3S)-3-amino-2-hydroxy-5-cyclohexylpentanoic acid
- [x] Cbz, Cbz-, Carboxybenzyl -> N-Terminal carboxybenzyl
- [x] Cit, citrullin -> Citrulline
- [x] D-3-Pal, D-3-(2-pyridyl)-alanine -> D-3-(3-pyridyl)-alanine
- [x] D-Bmt, (2R,3S,4S)-2-amino-3-hydroxy-4-methyloct-6-enoic acid -> (2R,3S,4S,6E)-2-amino-3-hydroxy-4-methyloct-6-enoic acid
- [x] D-Cit, D-Citrullin -> D-citrulline
- [x] D-Dap, D-2,3-diaminopropanoic acid -> 3-amino-D-alanine
- [x] D-Dip, (2R)-2-amino-3,3-diphenylpropanoic acid -> 3,3-diphenyl-D-alanine
- [x] D-Thz, (4S)-1,3-thiazolidine-4-carboxylic acid -> D-thioproline
- [x] Dab, 2,4-diaminobutanoic acid -> L-2,4-diaminobutanoic acid
- [x] DANcy, 2-sulfanylacetic acid -> Thioglycolic acid
- [x] Dip, (2S)-2-amino-3,3-diphenylpropanoic acid -> 3,3-diphenylalanine
- [x] Dpr, Dap, 2,3-diaminopropanoic acid -> 3-aminoalanine
- [x] Dsu, 2,7-diaminosuberic acid (2,7-diaminooctanedioic acid) -> 2,7-diaminosuberic acid
- [x] fmoc, fmoc-, fmoc N-Terminal Protection Group -> N-Terminal fluorenylmethoxycarbonyl 
- [x] Hsl, (3S)-3-aminooxolan-2-one -> L-homoserine lactone
- [x] Hva, 2-hydroxypentanoic acid -> (2S)-2-hydroxypentanoic acid
- [x] Mba, mercaptobutanoic acid (GMBA) -> (2S)-2-mercaptobutyric acid
- [x] Mpa, mercaptopropanoic acid -> Thiolactic acid
- [x] MsO, MsO-, Mesylate -> N-Terminal methanesulfonyl
- [x] NHBn-, N-Terminal 1-phenylmethanamine -> N-Terminal benzylamino
- [x] NHEt, -NHEt, Ethaneamine -> C-Terminal ethylamino
- [x] NMe, -NMe, C-Termial NMe -> C-Terminal methylamino
- [x] OBn-, N-Terminal phenylmethanol -> N-Terminal benzyloxy
- [x] OBz, -OBn, C-Terminal OBz -> C-Terminal benzyloxy
- [x] OEt,  -OEt, Ethanol -> C-terminal ethoxy
- [x] Oic, 2-carboxyocthydroindole -> (2S)-perhydroindolic acid
- [x] Oic3aR, (2S,3aR,7aS)-octaxydro-1H-indole-2-carboxylic acid -> (2S,3aR,7aS)-perhydroindolic acid
- [x] Oic3aS, Perhydroindolic acid -> (2S,3aS,7aS)-perhydroindolic acid
- [x] OMe, -OMe, C-Terminal OMe -> C-Terminal methoxy
- [x] OMe-, N-Terminal methanol -> N-Terminal methoxy
- [x] OtBu, -OtBu, C-Terminal OtBu -> C-Terminal tert-butoxy
- [x] Oxa, C-Terminal Oxa -> 2‑oxazoline
- [x] Ph, -Ph, Phenyl -> C-terminal phenyl
- [x] Pqa, Piperazine quinazolinone acetic acid, 2-(4-oxo-6-piperazin-1-yl-quinazolin-3-yl)acetic acid -> 2-(4-xxo-6-(piperazin-1-yl)quinazolin-3(4H)-yl)acetic acid
- [x] Spg, Ar5c, 1-amino-1-carboxycyclopentane -> Cycloleucine
- [x] Sta, statin (4-amino-3-hydroxy-6-methylheptanoic acid) -> Statine
- [x] Thz, (4R)-1,3-thiazolidine-4-carboxylic acid -> L-thioproline
- [x] Tos, Tos-, Tosyl -> N-Terminal tosyl
- [x] Wil, alpha-amino-2,4-dioxopyrimidenepropanoic acid -> Willardiine
- [x] aMeTy3, (2S)-2-amino-3-(3,4-dihydroxyphenyl)-2-methylpropanoic acid -> L-methyldopa
- [x] aMeTyr, (2S)-2-amino-3-(4-hydroxyphenyl)-2-methylpropanoic acid -> L-metyrosine
- [x] D-nTyr, (2R)-2-amino-2-(4-hydroxyphenyl)acetic acid -> D-4-Hydroxyphenylglycine
- [x] DAnTyr, 2-(4-methoxyphenyl)acetic acid -> 4-methoxyphenylacetic acid
- [x] DTyr3O, (2R)-2-amino-3-(3,4-dihydroxyphenyl)propanoic acid -> D-methyldopa
- [x] DTyrEt, (2R)-2-amino-3-(4-ethoxyphenyl)propanoic acid -> O-ethyl-D-tyrosine
- [x] DTyrMe, (2R)-2-amino-3-(4-methoxyphenyl)propanoic acid -> O-methyl-D-tyrosine
- [x] nTyr, (2S)-2-amino-2-(4-hydroxyphenyl)acetic acid -> L-4-Hydroxyphenylglycine
- [x] Tyr_3I, (2S)-2-amino-3-(4-hydroxy-3-iodophenyl)propanoic acid -> 3-iodo-L-tyrosin
- [x] Tyr_Me, (2S)-2-amino-3-(4-methoxyphenyl)propanoic acid -> O-methyl-L-tyrosine
- [x] Tyr26d, (2S)-2-amino-3-(4-hydroxy-2,6-dimethylphenyl)propanoic acid -> 2,6-dimethyl-L-tyrosine
- [x] Tyr35d, (2S)-2-amino-3-(4-hydroxy-3,5-diiodophenyl)propanoic acid -> 3,5-diiodo-L-tyrosine
- [x] Try3NO, (2S)-2-amino-3-(4-hydroxy-3-nitrophenyl)propanoic acid -> 3-nitro-L-tyrosine
- [x] Tyr3OH, (2S)-2-amino-3-(3,4-dihydroxyphenyl)propanoic acid -> 3-hydroxy-L-tyrosine
- [x] TyrabD, 2-amino-3-(4-methoxyphenyl)-prop-2-enoic acid -> (2E)-2-amino-3-(4-methoxyphenyl)-prop-2-enoic acid
- [x] TyrPO3, (2S)-2-amino-3-[4-(phosphonooxy)phenyl]propanoic acid -> O-phospho-L-tyrosine
- [x] TyrSO3, (2S)-2-amino-3-[4-(sulfooxy)phenyl]propanoic acid -> O-sulfo-L-tyrosine

**Comment by AlexeyGirin** [comment]
Fixed.
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
Test cases are not needed for that issue
