### ISSUE TITLE
Attachment point enumeration logic works wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4784]
**Steps to Reproduce**
1. Load from file: [Attachment point enumeration logic works wrong.zip](https://github.com/user-attachments/files/15615912/Attachment.point.enumeration.logic.works.wrong.zip)
OR manually create following configuration on the canvas:
![image](https://github.com/epam/ketcher/assets/26869421/afd64c34-b2b0-4f19-865f-b176ff18f38d)
2. Add attachment point (via context menu) to any atom
![image](https://github.com/epam/ketcher/assets/26869421/06c0c13d-bafe-4681-8d2a-3e1429cce05e)

**Actual behavior**
System adds R9 labeled attachment point
![image](https://github.com/epam/ketcher/assets/26869421/b24a2b06-b9e3-479b-a277-d185bab66317)

**Expected behavior**
System adds R2 labeled attachment point
![image](https://github.com/epam/ketcher/assets/26869421/49c65499-b30a-4087-bf01-bb2a55a4e910)
As per [requirements](https://github.com/epam/ketcher/issues/4530):

> Erase logic (since system enumerate AP automatically). What if we have R1, R2, R3 and I delete R2 and add NEW AP? What if we 
> have R1-R8 in place and I delete R2 and try to add new AP?
> Gaps should start be filled if we rich the R8 (later this will be changed to let user choose AP name himself)

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by AnnaKosol** [comment]
Verified

https://github.com/epam/ketcher/assets/174325443/58c7a501-2b93-4068-86b0-69c4a4ed722d

**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
