### ISSUE TITLE
Structure appears distorted after saving and reopening in MOL V2000 format

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4785]
**Description:**
When saving a chemical structure in MOL V2000 format and then reopening file, structure appears distorted. The carbon atom in the ring with attachment point is highlighted in red, and additional annotations or modifications appear incorrectly.

**Steps to Reproduce**
1. Open Ketcher.
2. Draw a benzene ring
3. Add an attachment point to the benzene ring via right click menu
4. Switch to Macro mode and connect attachment point to a macro structure
5. Switch to Micro mode
6. Save structure in MOLV2000 format
7. Reopen saved file in micro mode

**Actual behavior**
Upon reopening, structure appears distorted, as shown in attached screenshots. The carbon atom is highlighted in red, and the structure includes unexpected annotations and modifications.
![2024-06-06_14h59_06](https://github.com/epam/ketcher/assets/62464241/370ab6ba-5def-4e60-a9ce-33962c9f1cd2)

https://github.com/epam/ketcher/assets/62464241/e24fde4e-6079-49a6-9f86-a0cc87a8e146

**Expected behavior**
The structure should appear same as it was before saving, without any distortions or unexpected modifications.
![2024-06-06_14h02_50](https://github.com/epam/ketcher/assets/62464241/0fdb7bb9-286b-4b5c-908a-5cf6446b8964)

**Attached saved file:**

[ketcherv2000.zip](https://github.com/user-attachments/files/15617077/ketcherv2000.zip)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]

**Refers to feature:** https://github.com/epam/ketcher/issues/4530

**Comment by rrodionov91** [comment]
fixed in https://github.com/epam/ketcher/issues/4973

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/36c92cad-617e-40bc-a584-7ff1003e8974)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)
