### ISSUE TITLE
Change structure of monomers (Peptides and CHEMs)

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4787]
Change the structures of following peptides and CHEMs in the library (name, (new name) -> new structure, attachment points ()attachment atom number - leaving group atom number):

- 4-Arm PEG-Maleimide -> [4-Arm PEG-Maleimide.zip](https://github.com/user-attachments/files/16372263/4-Arm.PEG-Maleimide.zip), R1 = H (51-73), R2 = H (58-74), R3 = H (63-76), R4 = H (54-75)
Covered in the ticket: [#5108](https://github.com/epam/ketcher/issues/5108)
- 4-Formylbenzamide -> [4-Formylbenzamide.zip](https://github.com/user-attachments/files/16372320/4-Formylbenzamide.zip), R1 = NH2 (6-7), R2 = CHO (5-9&10) 
Covered in the ticket: [#4954](https://github.com/epam/ketcher/issues/4954)
- Tetraxetan -> [Tetraxetan.zip](https://github.com/user-attachments/files/16378345/Tetraxetan.zip), R1 = OH (22-23), R2 = OH (16-17), R3 = OH (19-20), R4 = OH (25-26)
Covered in the ticket: [#5108](https://github.com/epam/ketcher/issues/5108)

- [x] (2R)-2-aminopropan-1-ol, D-alaninol -> [D-alaninol.zip](https://github.com/user-attachments/files/16378394/D-alaninol.zip), R2 = OH (2-3)
- [x] 2-aminoprop-2-enoic acid, Dehydroalanine -> [Dehydroalanine.zip](https://github.com/user-attachments/files/16378419/Dehydroalanine.zip), R1 = H (4-6), R2 = OH (1-3)
- [x] SelenoCysteine, Selenocysteine -> [Selenocysteine.zip](https://github.com/user-attachments/files/16378455/Selenocysteine.zip), R1 = H (0-5), R2 = OH (2-3), R3 = H (7-8)
- [x] (2S)-2-amino-2-methyl-3-phenylpropanoic acid, alpha-methyl-L-phenylalanine -> [alpha-methyl-L-phenylalanine.zip](https://github.com/user-attachments/files/16378493/alpha-methyl-L-phenylalanine.zip), R1 = H (3-5), R2 = OH (0-1)
- [x] 2-amino-3-phenylprop-2-enoic acid, Dehydrophenylalanine -> [Dehydrophenylalanine.zip](https://github.com/user-attachments/files/16378530/Dehydrophenylalanine.zip), R1 = H (3-5), R2 = OH (0-1)
- [x] 2-amino-2-methylpropan-1-ol, D-phenylglycinol -> [D-phenylglycinol.zip](https://github.com/user-attachments/files/16378562/D-phenylglycinol.zip), R1 = H (8-9)
- [x] homohistidine -> [homohistidine.zip](https://github.com/user-attachments/files/16378595/homohistidine.zip), R1 = H (3-4), R2 = OH (0-1), R3 = H (9-13)
- [x] (2S)-2-methylpyrrolidine-2-carboxylic acid, alpha-methyl-L-proline -> [alpha-methyl-L-proline.zip](https://github.com/user-attachments/files/16378654/alpha-methyl-L-proline.zip), R1 = H (3-9), R2 = OH (5-7)
- [x] (2R)-2-amino-3-(2-methyl-1H-indol-3-yl)propanoic acid, 2-methyl-D-tryptophan -> [2-methyl-D-tryptophan.zip](https://github.com/user-attachments/files/16378693/2-methyl-D-tryptophan.zip), R1 = H (1-0), R2 = OH (3-4)
- [x] 2-aminobut-2-enoic acid, (2Z)-2-aminobut-2-enoic acid -> [(2Z)-2-aminobut-2-enoic acid.zip](https://github.com/user-attachments/files/16378737/2Z.-2-aminobut-2-enoic.acid.zip), R1 = H (1-0), R2 = OH (3-4)
- [x] N-Terminal toluene, N-Terminal benzyl -> [N-Terminal benzyl.zip](https://github.com/user-attachments/files/16378774/N-Terminal.benzyl.zip), R2 = H (6-7)
- [x] D-isovaline -> [D-isovaline.zip](https://github.com/user-attachments/files/16378808/D-isovaline.zip), R1 = H (0-4), R2 = OH (2-3)
- [x] diaminopimelic acid -> [diaminopimelic acid.zip](https://github.com/user-attachments/files/16378844/diaminopimelic.acid.zip), R1 = H (0-5), R2 = OH (2-3)
- [x] N-Terminal phenylmethanol, N-Terminal benzyloxy  -> [N-Terminal benzyloxy .zip](https://github.com/user-attachments/files/16378962/N-Terminal.benzyloxy.zip), R2 = H (7-8)
- [x] N-Terminal methanol, N-Terminal methoxy -> [N-Terminal methoxy.zip](https://github.com/user-attachments/files/16378983/N-Terminal.methoxy.zip), R2 = H (1-2)
- [x] 1-amino-1-carboxycyclopentane, Cycloleucine -> [Cycloleucine.zip](https://github.com/user-attachments/files/16379017/Cycloleucine.zip), R1 = H (6-9), R2 = OH (5-8)
- [x] (2S)-2-amino-3-(3,4-dihydroxyphenyl)-2-methylpropanoic acid, L-methyldopa -> [L-methyldopa.zip](https://github.com/user-attachments/files/16379055/L-methyldopa.zip), R1 = H (1-0), R2 = OH (3-4)
- [x] (2S)-2-amino-3-(4-hydroxyphenyl)-2-methylpropanoic acid, L-metyrosine -> [L-metyrosine.zip](https://github.com/user-attachments/files/16379091/L-metyrosine.zip), R1 = H (1-0), R2 = OH (3-4)

**Comment by AlexeyGirin** [comment]
No test cases needed in that particular case

**Comment by AlexeyGirin** [comment]
Fixed.
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)
