### ISSUE TITLE
System saves selection states of attachment point labels to KET file (it should not)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4791]
**Steps to Reproduce**
1. Load from file: [System saves selection states of attachment point labels to KET file (it should not).zip](https://github.com/user-attachments/files/15623817/System.saves.selection.states.of.attachment.point.labels.to.KET.file.it.should.not.zip)
OR manually create following configuration on the canvas:
![image](https://github.com/epam/ketcher/assets/26869421/afd64c34-b2b0-4f19-865f-b176ff18f38d)
2. Select one or few attachment points
![image](https://github.com/epam/ketcher/assets/26869421/5662600d-ed56-4187-b0e3-eb6627dda894)
3. Save canvas to KET file
4. Load it back using New project way

**Actual behavior**
System adds R9 labeled attachment point
![image](https://github.com/epam/ketcher/assets/26869421/b24a2b06-b9e3-479b-a277-d185bab66317)

**Expected behavior**
System recovers selection state of attachment point labels. It should not.
![image](https://github.com/epam/ketcher/assets/26869421/66c3481b-ed57-48a3-ba49-fa2d0ed1b001)

As per [requirements](https://github.com/epam/ketcher/issues/4530):

> Selection logic? Partial selection? Should selection be saved in KET?
> Selection should work the same as for atoms but without saving selection state in KET file

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-03_10h44_28](https://github.com/epam/ketcher/assets/62464241/820a0450-e235-4baf-865b-f6c1684cf410)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]
