### ISSUE TITLE
Context menu for attachment point labels should contain only Delete option

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4793]
**Steps to Reproduce**
1. Load from file: [Context menu for attachment point labels should contain only Delete option.zip](https://github.com/user-attachments/files/15624729/Context.menu.for.attachment.point.labels.should.contain.only.Delete.option.zip)
OR manually create following configuration on the canvas:
![image](https://github.com/epam/ketcher/assets/26869421/afd64c34-b2b0-4f19-865f-b176ff18f38d)
2. Open context menu for any attachment point label

**Actual behavior**
Not that it contains many different options that are working and able to create invalid objects on the canvas
![image](https://github.com/epam/ketcher/assets/26869421/020d0f14-3d82-4ba5-a511-212c846c43e3)

**Expected behavior**
Context menu for attachment point labels should contain only Delete option

As per [requirements](https://github.com/epam/ketcher/issues/4530):

> Items in context menu? Context menu if selected together with bond and atom?
> Only Delete item should be remain in the context menu for now

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by AnnaKosol** [comment]
Verified
<img width="1512" alt="Снимок экрана 2024-07-02 в 16 08 36" src="https://github.com/epam/ketcher/assets/174325443/ae7fd8f3-c54d-4715-bf1b-163aae6d646e">
**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
