### ISSUE TITLE
Cut operation for attachment points makes canvas inaccessible/inoperational and delete entire molecule

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4801]
**Steps to Reproduce**
1. Load from file: [Cut operation for attachment points makes canvas inaccessible and delete entire molecule2.zip](https://github.com/user-attachments/files/15635923/Cut.operation.for.attachment.points.makes.canvas.inaccessible.and.delete.entire.molecule2.zip)
OR manually create following configuration on the canvas: 
![image](https://github.com/epam/ketcher/assets/26869421/636af8db-d050-44bd-b820-095988f97a5c)
2. Select few atoms and at least one attachment point
![image](https://github.com/epam/ketcher/assets/26869421/11c1fdb5-c5fa-42e8-a4a7-6e9f7d03c907)
3. Press CTRL+X key

**Actual behavior**
Entire molecule disappears
![image](https://github.com/epam/ketcher/assets/26869421/2e72747c-a897-42c7-9853-90ffd0bc0e16)
Canvas become inaccessible and inoperational (try to select the rest molecule)

**Expected behavior**
Only selected elements disappears
![image](https://github.com/epam/ketcher/assets/26869421/2a58f460-22e0-4d73-82e4-0127eac69bda)
Canvas remain accessible and operational for user

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by Zhirnoff** [comment]
By Erase Tool

https://github.com/epam/ketcher/assets/62464241/a81770ff-ccde-474b-a3a2-6142fa771171

By CTRL+X

https://github.com/epam/ketcher/assets/62464241/0420cd68-492f-4732-87a3-c1942ed26411


Tested. Bug fixed.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.3]
**Indigo version** 
[Version 1.21.0-rc.1]
