### ISSUE TITLE
It is allowed to change bond type between micro and macro

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4806]
**Steps to Reproduce**
1. Load from file: [We can change bond type between micro and macro.zip](https://github.com/user-attachments/files/15644042/We.can.change.bond.type.between.micro.and.macro.zip)
OR manually create following configuration on the canvas: 
![image](https://github.com/epam/ketcher/assets/26869421/8c338755-7846-476a-847e-b80b09340b52)
2. Open context menu for bond between micro and macro
![image](https://github.com/epam/ketcher/assets/26869421/108d53fa-cdb0-4413-a736-9005ea24ae4c)
3. Select any bond type except single one

**Actual behavior**
System changes bond type to selected
![image](https://github.com/epam/ketcher/assets/26869421/e6544c38-6e02-40e1-bbd3-4ea06507f59c)

**Expected behavior**
It should be not allowed to change bond type between micro and macro

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by AlexeyGirin** [comment]
Not fully fixed.
It is possible to change bond type via Bond properties edit 
![image](https://github.com/user-attachments/assets/2de57f09-3892-4390-b231-479d004ae055)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)

**Comment by KristinaKasyanovskaya** [comment]
Fix https://github.com/epam/ketcher/pull/5191

> Not fully fixed. It is possible to change bond type via Bond properties edit ![image](https://private-user-images.githubusercontent.com/26869421/352101187-2de57f09-3892-4390-b231-479d004ae055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDAwNDMsIm5iZiI6MTcyMjMzOTc0MywicGF0aCI6Ii8yNjg2OTQyMS8zNTIxMDExODctMmRlNTdmMDktMzg5Mi00MzkwLWIyMzEtNDc5ZDAwNGFlMDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDExNDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMjVlZWI0YTJkNTBlZDExZjZhMzI5MWNhZTM4MDczNmVkZTBjODdkYmMzZTQxMzUzNDEzZjBlODE2YTE1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sIXTE5LfyI1k8zEQ6UOvZZaRtt4ZSrWN_t9oDbL_TSU)
> 
> * Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
> * Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
> * Windows 10 Pro
> * Chrome Version 127.0.6533.73 (Official Build) (64-bit)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-08-07_14h00_38](https://github.com/user-attachments/assets/3c80f60d-d3c2-4ba7-872b-4d06d9f5c74e)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
