### ISSUE TITLE
In sequence mode, each press adds two characters and when deleted, also removes two

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4823]
**Steps to Reproduce**
1. Switch to Macro mode -> Sequence mode
2. Start new sequence and press any letter
3. Press Backspace to delete letter.

**Actual behavior**
In sequence mode, each press adds two characters and when deleted, also removes two

**Expected behavior**
In sequence mode, each press adds one character and when deleted, also removes one

**Screenshots**

https://github.com/epam/ketcher/assets/62464241/0bc3a671-e4fc-4490-b488-a1b9ee035245

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.3]
**Indigo version** 
[Version 1.21.0-rc.1]

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.4 Build at 2024-06-10; 17:29:31
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

**Comment by Zhirnoff** [comment]
https://github.com/epam/ketcher/assets/62464241/4f3cf696-6c13-4970-acf7-716ae4a597ec


Tested. Bug fixed.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.4]
**Indigo version** 
[Version 1.21.0-rc.1]
