### ISSUE TITLE
Support rendering multiple ketcher editors on a page without an iframe

### ISSUE THREAD

**Issue by ihuang8** [epam/ketcher#4833]
**Background**
Add the ability to render multiple ketcher editors on a page without an iframe. The iframe makes it more difficult to access the ketcher instance (e.g. https://github.com/epam/ketcher/issues/3693).

**Solution**

Instead of binding the ketcher instance to the window of an iframe, each instance could be stored in the React state instead.

**Comment by AlexeyGirin** [comment]
Impossible to verify since it require non-trivial development of Demo app
Will be done in the context of https://github.com/epam/ketcher/issues/4145
