### ISSUE TITLE
Molecule changes position after saving and opening from file

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4836]
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Open file [molecule-move.zip](https://github.com/user-attachments/files/15821452/molecule-move.zip) or draw molecule connected to chain of monomers, save to file and open.

**Actual behavior**
Molecule changes position

<img width="1355" alt="image" src="https://github.com/epam/ketcher/assets/14859362/c4875f49-4268-49fa-8aaf-b796bb9d7071">

**Expected behavior**
Molecule does not change position

<img width="1404" alt="image" src="https://github.com/epam/ketcher/assets/14859362/b1598423-4839-4ea1-a9ac-8745e17cb6d9">

**Ketcher version** 
v2.22.0-rc.4

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/2c14d81e-3160-443c-be55-44cf1ebc65ee)

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.6 Build at 2024-06-13; 19:10:09
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
