### ISSUE TITLE
System loses connections to molecule R2 if there is no R1 attachment point

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4839]
**Steps to Reproduce**
1. Go to Macromolecules mode
2. Open file [connection-issue.ket.zip](https://github.com/user-attachments/files/15822123/connection-issue.ket.zip) or create molecule with R2 only attachment point and connect it to monomer, then save to file and open.

**Actual behavior**
System does not create connection between molecule and monomer.
<img width="970" alt="image" src="https://github.com/epam/ketcher/assets/14859362/5bd737e3-1721-42d8-811b-55c833ce34c3">

**Expected behavior**
System creates connection between molecule and monomer.

**Ketcher version** [e.g. v2.4.2]. 
v2.22.0-rc.4

**Comment by Zhirnoff** [comment]
Tested. The connection is not lost.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.5]
**Indigo version** 
[Version 1.21.0-rc.1]

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/b2d8ed9c-6be6-4ce8-815c-c4a74d1cc229)

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.6 Build at 2024-06-13; 19:10:09
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
