### ISSUE TITLE
Paste from clipboard does not work for molecules in macro mode

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4840]
**Steps to Reproduce**
1. Go to Molecules mode
2. Draw Benzene 
3. Go to Macromolecules mode
4. Select Benzene
5. Press Ctrl+C
6. Press Ctrl+V
 
**Actual behavior**
Structure is not pasted to canvas

**Expected behavior**
Structure is pasted to canvas

**Ketcher version** [e.g. v2.4.2]. 
v2.22.0-rc.4

**Comment by Zhirnoff** [comment]
https://github.com/epam/ketcher/assets/62464241/1ebd022a-eb18-4317-84fe-b49baef6c5e7


Tested.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.5]
**Indigo version** 
[Version 1.21.0-rc.1]
