### ISSUE TITLE
Errors occur when trying to save a macro structure connected to a micro structure in MOL V2000 format

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4842]
**Steps to Reproduce**
1. Open prepared test file [file-for-test.zip](https://github.com/user-attachments/files/15826249/file-for-test.zip)
2. Switch to Macro mode and connect macro structure to micro
3. Press save in Micro mode (an error appears immediately) The system cannot save in the format MOL V2000
![2024-06-13_20h41_05](https://github.com/epam/ketcher/assets/62464241/b9726080-6d31-43d5-8d5b-20496aa688b2)

**Actual behavior**
Errors occur when trying to save a macro structure connected to a micro structure in MOL v2000

**Expected behavior**
Errors do not occur when trying to save a macro structure connected to a micro structure in MOL v2000

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.5]
**Indigo version** 
[Version 1.21.0-rc.1]

**Comment by Zhirnoff** [comment]
Moved to 2.23 after discussing with team and @AlexanderSavelyev

**Comment by rrodionov91** [comment]
Error appears because in mol v2000 atom id length can NOT be more than 3 symbols in bond section. Specification - https://www.daylight.com/meetings/mug05/Kappler/ctfile.pdf
It is limitation of format.
Closing the ticket.
