### ISSUE TITLE
Make Sequence view default in Macromolecules mode

### ISSUE THREAD

**Issue by svvald** [epam/ketcher#4846]
Currently Flex view is opened by default when switching to Macromolecules mode. There was a request from CDD to make the Sequence mode the default one as it's more convenient from their standpoint.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/2c2d1a29-d1ba-4211-b318-738b324a803e)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
