### ISSUE TITLE
If you remove attachment point bond and try to add a new one to structure, it disappears

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4848]
**Steps to Reproduce**
1. Add Benzene ring on canvas and add on it attachment point by right click menu
2. Select 'Erase tool' and delete attachment point bond
3. Add new attachment point by right click menu

**Actual behavior**
If you remove attachment point bond and try to add a new one to structure, it disappears. Errors in DevTool Console

**Expected behavior**
After removing attachment point bond, a new one can be added without errors.

**Video**

https://github.com/epam/ketcher/assets/62464241/2337f106-acf7-48e2-bf11-15fd746ae120

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.6]
**Indigo version** 
[Version 1.21.0-rc.1]
Bug finded when tested: https://github.com/epam/ketcher/issues/4530

**Comment by Guch1g0v** [comment]
Perhaps already fixed

**Comment by Zhirnoff** [comment]
Pretested on local build 2.23 Bug is not reproduced.
![2024-06-24_12h10_04](https://github.com/epam/ketcher/assets/62464241/35b228f4-dddc-48a7-8cb9-675b690ce4a5)
