### ISSUE TITLE
UX support for HELM import/export

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4852]
**Requirements**

- **Open**
Add option 'HELM' to the format dropdown menu of modal window 'Open'/'Paste from the clipboard'

- **Save As**
Add option 'HELM' to dropdown 'File format' of modal window 'Save Structure'

**Backend part:**
[#1188](https://github.com/epam/Indigo/issues/1188)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/87e0237e-3419-44d7-8c3a-5d8c50afcc36)
![image](https://github.com/epam/ketcher/assets/26869421/effe60bc-7c2e-4bfd-ab87-5854562f566b)

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
