### ISSUE TITLE
Add new monomers to the library

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4856]
- [ ] **Maleimide**
Location in the library: CHEM
Name in the library: Maleimide
Abbreviation in the library: Mal
Attachment points/leaving groups: R1=H, R2=H
Structure: [Maleimide.zip](https://github.com/user-attachments/files/15871472/Maleimide.zip)

- [ ] **Tetraxetan**
Location in the library: CHEM
Name in the library: Tetraxetan
Abbreviation in the library: DOTA
Attachment points/leaving groups: R1=OH, R2=OH, R3=OH, R4=OH
Structure: [Tetraxetan.zip](https://github.com/user-attachments/files/15871487/Tetraxetan.zip)

- [ ] **Tetraethylene glycol**
Location in the library: CHEM
Name in the library: Tetraethylene glycol
Abbreviation in the library: PEG-4
Attachment points/leaving groups: R1=H, R2=OH
Structure: [Tetraethylene glycol.zip](https://github.com/user-attachments/files/15871492/Tetraethylene.glycol.zip)

- [ ] **Hexaethylene glycol**
Location in the library: CHEM
Name in the library: Hexaethylene glycol
Abbreviation in the library: PEG-6
Attachment points/leaving groups: R1=H, R2=OH
Structure: [Hexaethylene glycol.zip](https://github.com/user-attachments/files/15871501/Hexaethylene.glycol.zip)

- [ ] **4-formylbenzamide**
Location in the library: CHEM
Name in the library: 4-Formylbenzamide
Abbreviation in the library: 4FB
Attachment points/leaving groups: R1=NH2, R2=O
Structure: [4-formylbenzamide.zip](https://github.com/user-attachments/files/15871609/4-formylbenzamide.zip)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/620a1ee4-9817-431f-a63c-53f8785d6f78)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
