### ISSUE TITLE
Add new monomer in the library 

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4857]
- [ ] **4-Arm PEG-Maleimide**
Location in the library: CHEM
Name in the library: 4-Arm PEG-Maleimide
Abbreviation in the library: 4aPEGMal
Attachment points/leaving groups: R1=H, R2=H, R3=H, R4=H
Structure: [4-Arm PEG-Maleimide .zip](https://github.com/user-attachments/files/15871700/4-Arm.PEG-Maleimide.zip)

**Comment by AlexeyGirin** [comment]
Verified.

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
