### ISSUE TITLE
Introducing multi-tail arrows

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4861]
**Background**

Multi-tail arrows are a useful tool for drawing synthesis trees. Reactants are placed at the arrow tails, and the product is placed at the arrow head.
The example is **not chemically accurate**:
![image](https://github.com/epam/ketcher/assets/169887211/ca0de8bb-c9f5-4581-8782-f2b537424e61)

![image](https://github.com/epam/ketcher/assets/169887211/edae576c-8c66-4a38-b4a3-2e690fd9da55)

**Sub-tasks:**

Part 1
- [ ] #5055
- [ ] #4898
- [ ] #5104

Part 2
- [ ] #5056 
- [ ] #5057 
- [ ] #5058
- [ ] #5056 
- [ ] #4902
- [ ] #4903

**Requirements for Part 1**

1. The multi tail arrow should be able to be added to the canvas from the arrows menu.
![image](https://github.com/epam/ketcher/assets/169887211/f6979d2d-a307-434b-8f47-eac774fa062e)
.....1.1. When the user hovers over the image of the arrow in the arrows menu the arrow should change color, and the text: "Multi-Tail Arrow" should be displayed.
![image](https://github.com/epam/ketcher/assets/169887211/5b8e5baa-e12c-4123-8cda-fea41ec3df00)
.....1.2. When the user clicks (left click) the image of the arrow in the arrows menu the arrow should change color, and the arrows menu should close.
![image](https://github.com/epam/ketcher/assets/169887211/a4f7086d-80f5-45ef-855a-50f5cfb0f5aa)
.....1.3. Selecting the multi tail arrow from the arrows menu and clicking on the canvas (Left click) should give the default size arrow (total height: 100px, total width: 46px, tail width: 14px, head width: 30px, radius of the corner curve: TBD) with the default configuration (horizontal upper and lower tail (2 tails), horizontal arrow head and vertical spine).
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/d4b3517d-e89e-4d9a-84c2-d981f8412222)
..........1.3.1. Bottom left point of the arrow should be the point on the canvas that the user clicked.

2. Highlighting the arrow is covered bellow.
.....2.1. Selecting any part of the arrow with select tools (Rectangle selection, Lasso Selection, Fragment Selection) or the arrow tools should highlight the whole arrow similar to this:
![Image](https://github.com/user-attachments/assets/1bd08228-df6f-41ec-bee5-414202cbeccc)
.....2.2. Hovering over any part of the arrow with select tools, arrow tools or the erase tool should highlight the whole arrow similar to this:
![Image](https://github.com/user-attachments/assets/a1b5c0b1-2999-4085-8fe2-a35d62810b5a)
..........2.2.1. If the user hovers over the arrow with select or arrow tools (not erase tool), the cursor should change accordingly: hover on spine - four way arrow; hover on head or tail middle - up/down arrow; hover on left corners of tails or right corner of head - left/right arrow.
(Will be implement in scope of tails and a the head arrow)
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/07b1678e-397c-491c-9313-b02196b36459)

3. When the cursor is a four way arrow (hover on spine) clicking and dragging moves the whole object.
.....3.1. During and after moving, the whole arrow should be highlighted like in 2.1.

**Requirements for Part 2**
.....1.4. When the user selects the multi tail arrow from the arrows menu, left clicks on the canvas (at point A) and drags (to line B) before releasing the click, the arrow should appear blue, the height of the arrow should be default, the width should be the closest distance between point A and line B (tail and head width adjusted proportionally).
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/84b914bf-a014-4678-b412-76d82c34e162)
..........1.4.1. When the cursor is released, the arrow is placed on the canvas and the color should turn back to black.

4.  When the user is hovering on the left corner of one of the tails, clicking and dragging to the left or right changes the widths of all tails.
.....4.1. During and after moving, the whole arrow should be highlighted like in 2.1.
.....4.2. Dragging to the left is not limited.
.....4.3. Dragging to the right is limited to [minimum tail length>=radius of the corner curve]
.
.
5.  When the user is hovering on the right corner of the head, clicking and dragging to the left or right changes the width of the head.
.....5.1. During and after moving, the whole arrow should be highlighted like in 2.1.
.....5.2. Dragging to the right is not limited.
.....5.3. Dragging to the left is limited to [minimum head length]
.
.
6.  When the user is hovering over the center of a tail (not the left corner), clicking and dragging up and down changes the position of the tail, and (if applicable) changes the length of the spine and the corner curvature.
.....6.1. During and after moving, the whole arrow should be highlighted like in 2.1.
.....6.2. Behavior for the upper tail is covered bellow.
..........6.2.1. The upper tail can be moved up with no limitation.
...............6.2.1.1. The spine is adjusted accordingly.
..........6.2.2. The upper tail can be moved down until one radius of the corner curve above the head or another tail 
(whichever comes first).
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/2f490acd-4345-4efa-a530-b99db9a260c3)
...............6.2.2.1. The spine is adjusted accordingly.
...............6.2.2.2. Any dragging bellow this point results in no movement.
.....6.3. The behavior for the lower tail is identical to the behavior for the upper tail, just with reversed directions.
.....6.4. The middle tail(s) can be moved anywhere along the spine with a radius of the corner curve as the limitation on both sides. (same as for the head, see req. 7.2.)
..........6.4.1. If the user drags the tail closer than one radius of the corner curve to another tail, after releasing the cursor, the tail position is automatically adjusted to the closest position to where the user dragged the tail, that is at least one radius of the corner curve away form other tails.
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/d360f95d-f5e7-49a4-8a18-4bc2028b3ce8)
.
.
7. When the user is hovering over the center of the head (not the right corner), clicking and dragging up and down changes the position of the head.
.....7.1. During and after moving, the whole arrow should be highlighted like in 2.1.
.....7.2. The head can be moved along the spine, with one radius of the corner curve being the limitation on both sides.
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/2e454ce6-ed43-4ab5-8ed3-1981d1cbf5df)
..........7.2.1. Any movement above/bellow these lines results in no movement.
.
.
8.  Right clicking on the tail should give the user a context menu with the option to "Remove tail".
.....8.1. The cursor should be changed to standard arrow.
.....8.2. After clicking the multi-tail arrow it should be highlighted like in 2.1.
.....8.3. If the selected tail is the upper or lower tail, the option to "Remove tail" should be disabled.
.
.
9.  Right clicking on the multi-tail arrow should give the user a context menu with the option to "Add tail".
.....9.1. The cursor should be changed to standard arrow.
.....9.2. After clicking the multi-tail arrow it should be highlighted like in 2.1.
.....9.3. If the space between two tails that the user clicked is less then 2 * [minimal tail distance] + tail thickness, the option to "Add tail" should be disabled.
.....9.4. If the user selects the option to "Add tail", the new tail should be added exactly in the middle between the first two tails with the biggest distance.
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/accca0c1-8afa-44bd-8a84-8813c550f2c2)
.
.
.
.
.
**To be clarified (not up to date)**
- Color of the arrow - Black (like all other elements), teal when selected
- Rounded or not - Not rounded
- Minimal tail length - 14px
- Minimal heal length - 30px
- Minimal spine length - 100px
- Default size of the whole object (minimal or not)? -?
- Minimal tail distance - no minimal tail distance
- If there is no space for a new tail (disallow it/extend the spine) - no limitations
- Should dragging the head above/bellow the spine extend the spine (and move the tail), or should it be prohibited? - no dragging above the spine
- Should we allow tails to drag over each other (sometimes extending the spine)? - we can but not above/bellow the spine
- Rotation? - no rotation
- Can the head be deleted? -no
- How many tails can be deleted (min 2 left)? - minimum 2 left

**Comment by yauhen-karmyzau** [comment]
#4902 and #4903 are out of scope!

**Comment by ivanmaslow** [comment]
These two feature aren't done:
- https://github.com/epam/ketcher/issues/4902
- https://github.com/epam/ketcher/issues/4903

Testing on RC was completed for tasks below, all details can be found there including updated requirements:
- https://github.com/epam/ketcher/issues/5104;
- https://github.com/epam/ketcher/issues/5055;
- https://github.com/epam/ketcher/issues/4898;
- https://github.com/epam/ketcher/issues/5056;
- https://github.com/epam/ketcher/issues/5058;
- https://github.com/epam/ketcher/issues/5107;
- https://github.com/epam/ketcher/issues/5057;
