### ISSUE TITLE
New approach and UI for switching between types in sequence mode 

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4872]
**Background**

Currently, if the user wants to switch a type in sequence mode they have to stop typing, click once to open the drop down menu, select from the menu, and then continue typing.

**Solution**

1. Introduce keyboard commands for switching between types of typing:
Ctrl+Alt+R switches to RNA type
Ctrl+Alt+D switches to DNA type
Ctrl+Alt+P switches to peptide type 
> On macOS instead of "Alt", "Option" is used.

2. The current drop-down menu should be changed to:
![image](https://github.com/epam/ketcher/assets/169887211/723273e9-68d7-4541-8954-ed27381d2794)
2.1. When hovering over RNA the user should see "RNA (Ctrl+Alt+R)", when hovering over DNA the user should see "DNA (Ctrl+Alt+D)", when hovering over PEP the user should see "Peptides (Ctrl+Alt+P)".
2.2. The default mode for typing is RNA.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/e9f91f6c-f57e-4687-a244-dbfe9355fc6c)
Ketcher - Version 2.24.0-rc.1 Build at 2024-09-02; 05:32:40
Version 1.24.0-dev.7.0-g59089022-wasm32-wasm-clang-12.0.0
Chrome 128.0.6613.114 (Official Build) (64-bit)
Win10

**Comment by Zhirnoff** [comment]
Tested.
![2024-09-04_18h02_27](https://github.com/user-attachments/assets/3710a4d3-0441-4a9d-b435-389c54c31ba6)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
