### ISSUE TITLE
Ketcher part: Save to mol for micro and macro structures connected through attachment points works wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4879]
Original issue was created in Indigo - https://github.com/epam/Indigo/issues/1993
@even1024 told that he did his part and now it require Ketcher side change to be done.

**Summary**
Save to mol for micro and macro structures connected through attachment points works wrong

**Steps to Reproduce**
1. Open Ketcher.
2. Draw a benzene ring
3. Add an attachment point to the benzene ring via right click menu
4. Switch to Macro mode and connect attachment point to a macro structure
5. Switch to Micro mode
6. Save structure in MOL V2000 format
7. Open saved file in micro mode

If it is not possible to draw the structure, then you can open the prepared file (you just need to open it in macro mode and then switch to micro mode): 
[ketcher (53).zip](https://github.com/user-attachments/files/15620336/ketcher.53.zip)

**Actual behavior**
Resulted file is incorrect:
![image](https://github.com/epam/ketcher/assets/26869421/0d05da19-997a-4da5-9eca-bfb02fd70656)

**Expected behavior**
![image](https://github.com/epam/ketcher/assets/26869421/c36bccd5-51bc-4c2b-94f3-ae709e4aecb9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
**Indigo version** 
[Version 1.21.0-rc.1]

**Refers to feature:** https://github.com/epam/ketcher/issues/4530
**Issue on Indigo side:** https://github.com/epam/Indigo/issues/1991
**Attached saved files:**

[ketcherCDXML (1).zip](https://github.com/user-attachments/files/15627521/ketcherCDXML.1.zip)

**Comment by AnnaKosol** [comment]
Verified (title AND Enantiomer is verified too)
<img width="308" alt="Снимок экрана 2024-07-05 в 14 42 46" src="https://github.com/epam/ketcher/assets/174325443/645a1607-0d6e-4a2c-aed8-2fd06c37901c">

**Versions:**
Ketcher Version 2.22.0-rc.9 https://lifescience.opensource.epam.com/ketcher/index.html Build at 2024-07-04; 15:58:14
Indigo Version 1.21.0-rc.3.0-g1570d3f9f-wasm32-wasm-clang-19.0.0
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
