### ISSUE TITLE
Change previews for hovering over the monomer in the library and on the canvas

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4880]
**Background**

- Currently, the user can see the same preview when hovering over the monomer in the library and on the canvas, but that preview doesn't contain the atoms within leaving groups/attachment points.
.
.
- There should be a preview when hovering over a monomer in the library. That preview should contain the name, the structure, the atoms contained within the attachment points and the ITD alias if the monomer has one.
- There should be a preview when hovering over a monomer on the canvas. That preview should contain all of the same information, with occupied attachment point marked in gray (without atoms for leaving group), and IDT aliases for the current position of the monomer.

**Requirements**

1.1. Preview for hovering over a monomer (not a preset) in the library should appear with a delay of 0,5 seconds.
1.2. The preview should contain:
the name of the monomer,
the structure of the monomer,
the atoms contained within the attachment points,
and if the monomer has an IDT alias, the text "IDT:" followed by:
..........1.2.1. All IDT aliases with position indicators in brackets if the monomer is not defined at all three positions and/or the part of the IDT alias excluding the position indicator ("base") is not the same for for all positions.
...............1.2.1.1. If the "base" is the same for two positions, they should be represented as ([pos1],[pos2])base.
examples for better understanding:
(actual example) Phosphate is defined at positions 5 and 3 -> (5,3)Phos
(actual example) Unsplit nucleotide is defined at all positions (5AmdA, i6diPr, 3AmdA) -> (5,3)AmdA, (i)6diPr
Some monomer is defined at only one position -> (5)base
Some monomer is defined at all positions -> (5)base1, (i)base2, (3)base3
![image](https://github.com/user-attachments/assets/9c0cb05d-f467-4981-a85a-63b156140be4)
..........1.2.2.  The base of IDT alias is the monomer is defined at all three positions and the part of the IDT alias excluding the position indicator ("base") is the same for for all positions.
![image](https://github.com/user-attachments/assets/7775291a-7967-4d0d-9231-0f1bbd4795d7)
.
.
2.1. Preview for hovering over a monomer (not a nucleotide/nuzleozide in sequence mode and not phosphate) on the canvas should appear with a delay of 0,5 seconds.
2.2. The preview should contain:
the name of the monomer,
the structure of the monomer,
and the atoms contained within the attachment points.
.
.
.....2.2.1. If the monomer has an occupied Rn:
attachment point Rn should be gray on structure and bellow, 
and should contain no atoms bellow.
.
.
.
.....2.2.2. If the monomer has an occupied R1 and a non occupied R2 (monomer is in the end of the chain): 
..........2.2.2.1. If the monomer has an IDT alias for 3' position, show the text "IDT:" followed by the alias for that position (with the position indicator - 3).
..........2.2.2.2. If the monomer doesn't have an IDT alias for 3' position, but does have an IDT alias for internal position, show the text "IDT:" followed the alias for that position (with the position indicator - i).
..........2.2.2.3. If the monomer doesn't have IDT aliases for 3' and i position, don't show any IDT alias on preview.
.
.
.....2.2.3.  If the monomer has an occupied R2 and a non occupied R1 (monomer is in the beginning of the chain): 
..........2.2.3.1. If the monomer has an IDT alias for 5' position, show the text "IDT:" followed by the alias for that position (with the position indicator - 5).
..........2.2.3.2. If the monomer doesn't have an IDT alias for 5' position, but does have an IDT alias for internal position, show the text "IDT:" followed the alias for that position (with the position indicator - i).
..........2.2.3.3. If the monomer doesn't have IDT aliases for 5' and i position, don't show any IDT alias on preview.
.
.
.....2.2.4. If the monomer has occupied both R1 and R2 (monomer is in the middle of the chain):
..........2.2.4.1. If the monomer has an IDT alias for internal position, show the text "IDT:" followed by the alias for that position (with the position indicator - i).
..........2.2.4.2. If the monomer doesn't have an IDT alias for internal position, but does have an IDT alias for 5' position, show the text "IDT:" followed the alias for that position (with the position indicator - 5).
..........2.2.4.3. If the monomer only has an IDT alias for 3' position, show the text "IDT:" followed the alias for that position (with the position indicator - 3).
.
.
.....2.2.5. If the monomer doesn't have occupied R1 and R2 (monomer is the only one in the chain):
..........2.2.5.1. If the monomer has and IDT alias for 5' position, show the text "IDT:" followed by the alias for that position (with the position indicator - 5).
..........2.2.5.2. If the monomer doesn't have an IDT alias for 5' position, but does have an IDT alias for internal position, show the text "IDT:" followed by the alias for that position (with the position indicator - i).
..........2.2.5.3. If the monomer doesn't have aliases for 5' and i positions, but does have an IDT alias for 3' position, show the text "IDT:" followed the alias for that position (with the position indicator - 3).
.
.
(Image for better understanding)
![image](https://github.com/user-attachments/assets/8c218fd9-4a66-4a72-b0c3-60be69573b16)
.
.
![image](https://github.com/user-attachments/assets/54b675b7-5673-47fc-95a7-1e2fcbdce61c)
![image](https://github.com/user-attachments/assets/32de4634-8f09-4c16-a88f-80ae8907ab8f)
.
.
3.1. Preview for hovering over a preset in the library or on the canvas in sequence mode should appear with the delay of 0,5 seconds.
3.2. IDT aliases show on previews for all current presets (Ketcher version 2.23.0)
.....3.2.1. For A in the library and on the canvas in sequence mode: rA, 
.....3.2.2. For C in the library and on the canvas in sequence mode: rC,
.....3.2.3. For G in the library and on the canvas in sequence mode: rG,
.....3.2.4. For T in the library and on the canvas in sequence mode: rT,
.....3.2.5. For U in the library and on the canvas in sequence mode: rU,
.....3.2.6. For MOE(A)P in the library: 52MOErA and i2MOErA, 
in sequence mode, first symbol: 52MOErA,
in sequence mode, middle symbol: i2MOErA,
in sequence mode, last symbol: 32MOErA.
.....3.2.7. For MOE(5meC)P in the library: 52MOErC and i2MOErC,
in sequence mode, first symbol: 52MOErC,
in sequence mode, middle symbol: i2MOErC,
in sequence mode, last symbol: 32MOErC.
.....3.2.8. For MOE(G)P in the library: 52MOErG and i2MOErG,
in sequence mode, first symbol: 52MOErG,
in sequence mode, middle symbol: i2MOErG,
in sequence mode, last symbol: 32MOErG.
.....3.2.9. For MOE(T)P in the library: 52MOErT and i2MOErT,
in sequence mode, first symbol: 52MOErT,
in sequence mode, middle symbol: i2MOErT,
in sequence mode, last symbol: 32MOErT.
.....3.2.10. For dR(U)P in the library and on the canvas in sequence mode: U.
.
.
4.1. Hovering over a phosphate in the canvas (including sequence mode) should appear with a delay of 0,5 seconds.
4.2. The preview for phosphate differs form other non-preset previews on canvas only in IDT alias:
.....4.2.1. If the phosphate is the only monomer in the chain, the alias should be: 5Phos,
.....4.2.2. If the phosphate is the first monomer in the chain the alias should be: 5Phos,
.....4.2.3. If the phosphate is the last monomer in the chain, but the second to last is not a sugar/nucleozide, the alias should be: 3Phos.
.....4.2.4. All other cases (phosphate in the middle of the chain and sugar/nucleozide then phosphate as the last monomer in the chain), no IDT alias on preview for phosphate.
(Image for better understanding)
![image](https://github.com/user-attachments/assets/cac01930-35b5-45ba-af03-40bceeb97bf9)
.
.
5.1 Preview of rna preset should contain the name of preset instead of name of rna base(current implementation)

**Comment by Zhirnoff** [comment]
Tested.

![2024-08-07_12h52_56](https://github.com/user-attachments/assets/b7d9252e-1eeb-45e4-808a-7eadf302eb91)
![2024-08-07_12h53_04](https://github.com/user-attachments/assets/3fa68040-404e-4b5e-8ee1-6cbebd6560a6)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
