### ISSUE TITLE
Starting new sequences with "Plus" icon on canvas

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4887]
**Background**
The current method of starting a new sequence with a right-click in sequence mode is not intuitive for users. An explicit UX approach that clearly indicates how to start a new chain should be implemented.

**Requirements**
1. If the canvas is empty in sequence mode the "plus" icon should be displayed in top left corner of the visual area. 
![image](https://github.com/epam/ketcher/assets/169887211/a3adce55-e861-41f0-be4f-315efaf1df19)
2. When hovering on the "plus" button it should change the color.
![image](https://github.com/epam/ketcher/assets/169887211/532e3dcd-abee-4d83-8122-f64ed119e2cc)
3. (In both view and edit modes) Hovering above the first sequence, between two sequences and bellow the last sequence (32 px), should give the user the following visual element:
![image](https://github.com/epam/ketcher/assets/169887211/1fa1a268-6e6c-4247-a054-0e23a8e1d770)
4.  Clicking on the "plus" buttons should result in turning on of editing mode (if the user was in view mode) and displaying of a grid. The grid should start at the same location as the plus button, with the cursor automatically placed in the first cell of that line.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/4446948b-9cbf-4640-ac48-67283396b436)
- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
