### ISSUE TITLE
Enable editing sequences by click between symbols or double click on symbol

### ISSUE THREAD

**Issue by olganaz** [epam/ketcher#4888]
**Background**
The current approach of editing existed sequence with a right-click is not intuitive for users. Additionally to rClick option an approach to edit sequence by clicking between symbols and double-clicking a symbol should be implemented.

**Requirements**

View mode: 
1.  While user hovers along the sequence, the cursor should be displayed as a arrow. 
2. If user hovers between the symbols (4 pixel space), the cursor should become a caret. 
3. If user clicks between two symbols (when cursor becomes a caret) the edit mode should be turned on and the cursor should be placed between those two symbols.
4. Double-click on the symbol should turn on the edit mode AND cursor (blinking line) should be placed in corresponding cell of the grid before the symbol AND that symbol should be highlighted. 
![image](https://github.com/epam/ketcher/assets/169887211/6f711e5e-ffa8-4b26-914d-9f7fdcec547b)

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/bbf645eb-dd9e-4d62-a8cc-288e78db9b63)
- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
