### ISSUE TITLE
After using "Clear Canvas" in the Sequence mode and entering new sequence, extra structures are shown in Flex and Snake modes

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#4889]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Sequence mode
2.	Enter any letters on the canvas
3.	Click on the "Clear Canvas" button 
4.	Enter any letters on the canvas again
 
       <img width="144" alt="image" src="https://github.com/epam/ketcher/assets/139227567/0c32264f-016d-460e-b475-fee378eaac85">
5.	Switch to the Flex or the Snake mode

**Actual behavior**
Extra sugar, phosphate and base are displayed on the canvas

<img width="431" alt="image" src="https://github.com/epam/ketcher/assets/139227567/b8bff1a4-e48e-403a-8392-f3dca9a306e7">

<img width="443" alt="image" src="https://github.com/epam/ketcher/assets/139227567/62a761d8-3a50-4eff-b32f-d512ee510431">

**Expected behavior**
Extra sugar, phosphate and base are not displayed on the canvas

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (125.0.6422.142) x64

**Ketcher version** 2.22.0-rc.7, Build at 2024-06-20; 18:42:41

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/770556e6-cf8b-4c4c-8f90-a4cc32d4c952)

Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
Indigo Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
Win 10
Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by Zhirnoff** [comment]
Bug reproduced.

https://github.com/epam/ketcher/assets/62464241/d320a314-d35d-46a8-9f51-59bab3ebce79

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/epam/ketcher/assets/62464241/323988fd-da50-4db5-9433-c0b15e86ef14


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.2]
**Indigo version** 
[Version 1.22.0-rc.2]
