### ISSUE TITLE
Insert image to canvas via "Add image" tool, Select, Move and Scale the image

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#4897]
As a **User**, I want to be able **to insert, select, scale and move images** on the canvas so that I can enhance my chemical structure diagrams with relevant visuals and adjust them to fit my needs.

**Acceptance Criteria:**

1. A user should be able to add an image using a dedicated 'Add Image' button located at the side panel with the static tools. The application should support at least the PNG image format and, if feasible, other commonly used image formats like JPEG, GIF, and SVG.

![Image](https://github.com/epam/ketcher/assets/173041434/2397d260-a5ec-4db1-9eda-362cf49b3f8b)

2. An image should be placed on the canvas on the click event under the mouse pointer.
3. A user should be able to select an image by clicking on it with the selection and "Add Image" tools. The selected image should be visibly highlighted or outlined and the Scale functionality must be visible.
4. A user should be able to scale (enlarge or reduce) a selected image using a dedicated 'Scale' option. The application should provide real-time feedback as the user scales an image.
5. A user should be able to move a selected image around the canvas.
6. After the image is inserted, moved or scaled, the user should be able to undo/redo his actions. The new size and position of the image must be saveable to supported formats (KET).
7. If a user tries to upload an unsupported image format, they should be shown an error message. Moving and rotating images are out of scope for this user story.

TBD: Design of the image selection and UI elements for scaling.
 
https://github.com/epam/ketcher/issues/4897#issuecomment-2215065068
> Ketcher is not support file insert from the system clipboard. This functionality may be implemented in scope of separate issue.

**Comment by yauhen-karmyzau** [comment]
Drag-n-Drop is out of scope! New feature need to be created.

**Comment by vanoprenko** [comment]
It doesn't make a lot of sense to deal with SVG as with raster. Let's either exclude it from scope (add with a separate ticket) or support as a vector.

**Comment by daniil-sloboda** [comment]
In case some images are not working due to size\format they are out of scope

**Comment by yauhen-karmyzau** [comment]
Team Agreement:
We can implement the same behaviour as for other "static tools:

1. A User selects Insert image tool, the tool in the sidebar becomes active.
2. A User clicks on the canvas and the system "select a file" window appears.
3. When an image is uploaded , it appears at the place of the click.

**Comment by yauhen-karmyzau** [comment]
Missed AC:

- A User should be able to switch to Macro mode and back.
- Images shouldn’t be visible in Micro.

**Comment by ivanmaslow** [comment]
Missed AC:
- User can zoom in and zoom out the view with an inserted image:
![image](https://github.com/epam/ketcher/assets/165396466/f3c092b9-354d-4923-b42e-dabe21f07e79)

**Comment by ivanmaslow** [comment]
Some points are discovered during exploratory testing on 08.07.24:
- User can't add the same picture several times using 'Add image' option
- Need to update tooltip from 'Add image' to 'Add Image';
- We are going to add white list for allowed formats (bmp, gif, jpeg, jpg, png, svg, webp);

**Comment by yauhen-karmyzau** [comment]
Ketcher is not support file insert from the system clipboard. This functionality may be implemented in scope of separate issue.

**Comment by ivanmaslow** [comment]
Points from the previous comment are fixed.
Points below are detected during exploratory testing on the nightly environment, need to be fixed:
- When images are loaded from .ket file they can't be selected;
- Can't delete the image;
- Problem with selection on the intersection of 2 images.

**Comment by ivanmaslow** [comment]
Points from the previous comment are fixed.
Points below are detected during exploratory testing on the nightly environment, need to be fixed:
- Images change level layers after Undo/Redo:
-- Load images with overlapping from .ket file
![image](https://github.com/user-attachments/assets/0299aab5-c023-435d-a86b-b8e4b4f6ed7d)
--Click on Undo
--Click on Redo - Pictures changed the layer
![image](https://github.com/user-attachments/assets/6db07f8b-df10-49f2-b0bb-4677afa365a6)
- Copy/Paste actions don't work for Images
- Selection frame is displayed not proper for overlapped images will be fixed separately - https://github.com/epam/ketcher/issues/5097

**Comment by yauhen-karmyzau** [comment]
Change requests:

1. Images should be displayed not in front, however, in back.
2. Due to Indigo limitations, currently, we can save static image with PNG and SVG only, so the list of supported formats should be limited to this ones.

**Comment by Zhirnoff** [comment]
Tested.

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
