### ISSUE TITLE
Select and move Multi-tail arrow

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#4898]
As a **User**, I want to **select and move a multi-tail arrow** so that I can modify my pathway reaction.

**Acceptance Criteria:**

1. When the user hovers over with select or arrow tools a multi-tail arrow, mouse pointer should be displayed
it should be highlighted (**OUT OF SCOPE**, highlighting will be added in - https://github.com/epam/ketcher/issues/5057).
![Image](https://github.com/user-attachments/assets/a1b5c0b1-2999-4085-8fe2-a35d62810b5a)
2. Mose pointer must represent the movement possibility on hovering a spine and while moving the element.
![Image](https://github.com/user-attachments/assets/30e7c130-317e-4fde-9708-a11a304f2b17)
3. Clicking on a multi-tail arrow (hover area) should select it and highlight it (**OUT OF SCOPE**, arrow can be selected without visual highlighting, highlighting will be added in - https://github.com/epam/ketcher/issues/5057). 
![Image](https://github.com/user-attachments/assets/1bd08228-df6f-41ec-bee5-414202cbeccc)
4. User can move the multi-tail arrow on the canvas, clicking and dragging its spine (for current implementation not only spine, but the whole multi-tail arrow is available for dragging the whole arrow).
5. During the movement, the multi-tail arrow must be selected (**OUT OF SCOPE**, selection will be added in scope of - https://github.com/epam/ketcher/issues/5057).
6. User can perform basic actions with Multi-Tail Arrows:
- User can zoom in and zoom out the canvas with multi-tail arrows, while multi-tails are displayed according to the zoom and don't change their positions;
- Multi-Tailed Arrows can be selected using selection tools: rectangle, lasso, fragment;
- Multi-Tailed Arrows can be deleted using "Erase", "Clear Canvas" (Ctrl + Del) tools and buttons - Delete and Backspace;
- User can Undo (Ctrl + Z)/Redo (Ctrl+ Shift + Z) actions (adding, movement, deletion) with Multi-Tailed Arrows;

**Comment by vanoprenko** [comment]
Sec. 3 is to be implemented in scope of #4911 , not as part of this task

**Comment by ivanmaslow** [comment]
Point to fix is discovered during exploratory testing:
- When the user saves pictures to .ket file with elements and/or structures, pictures multiply in .ket file (the size of file is increased);

**Comment by ivanmaslow** [comment]
Exploratory testing is completed on the RC Remote environment:
- Ketcher [Version 2.25.0-rc.1] Build at 2024-09-03; 15:37:29
- Indigo Version 1.24.0-rc.1.0-gb8f099851-x86_64-linux-gnu-11.2.1
- Windows 11 Enterprise
- Chrome Version 128.0.6613.120 (Official Build) (64-bit)

The following checks were performed, and tests are updated:
- Added from the KET file or by Tool different Multi-Tailed Arrows can be selected and moved with the correct position of the spine, tails, and head on Canvas with/without chemical elements;
- Different Multi-Tailed Arrows can be selected and moved separately or together with chemical elements;
- Moving actions for Multi-Tailed actions can be Undo/Redo;
