### ISSUE TITLE
Open Edit Connection Points dialog via right click on bond

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#4905]
**Background**
Currently if the user wants to change connection points that participate in a bond, they would have to delete that bond, and establish a new one.
This feature would allow the user to change connection points more easily and provide bond details in a user-friendly way.
.
.
**Requirements**
1. When the user right clicks on a bond, the context menu with "Edit Connection Points..." option should appear.
.
.
2. Clicking on the "Edit Connection Points..." option opens the "Edit Connection Points" dialog.
.....2.1. That dialog is identical to the "Select Connection points" dialog, just with a different title, and a different button label ("Reconnect" instead of "Connect")
..........2.1.1. The dialog contains appropriately marked connection points: gray if they participate in other bonds, white if they participate in no bonds, and teal if they participate in **this** bond (just like "Select Connection points" dialog).
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/c5f86d9e-47c2-44d5-a534-5b7825aea4c5)
..........2.1.2. The user is able to interact teal and white attachment points (just like "Select Connection points" dialog).
.....2.2. If there are no available (white) connection points on both monomers, button "Reconnect" should be disabled.
.
.
3. The user can change the attachment points that participate in the selected bond.
.....3.1. Clicking "Reconnect" in the dialog (if different attachment points were chosen) results in deletion of the previous bond and establishment of the new one (with new attachment points).
.....3.2. Clicking "Reconnect" in the dialog (if different attachment points were not chosen) results in no change of connection points of the bond. 
.....3.3. Clicking "Cancel" in the dialog results in no change of connection points of the bond.

**Comment by Zhirnoff** [comment]
Tests added to the automation table.

**Comment by Zhirnoff** [comment]
Tested. We have 5 bugs connected to ticket.
![2024-08-07_11h35_37](https://github.com/user-attachments/assets/334eb6cf-a132-4c5d-8303-e60c36fb4807)
![2024-08-07_11h35_52](https://github.com/user-attachments/assets/f2a2227f-becd-4ec5-a27d-4a7440b6f789)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
