### ISSUE TITLE
Unble to save to micro-macro molecult to MOL V2000, system throws an error: number does not fit

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4906]
**Steps to Reproduce**
1. Load from file: [Unble to save to micro-macro molecult to MOL V2000, system throws an error number does not fit.zip](https://github.com/user-attachments/files/15992300/Unble.to.save.to.micro-macro.molecult.to.MOL.V2000.system.throws.an.error.number.does.not.fit.zip)
OR manually create following configuration on the canvas: 
![image](https://github.com/epam/ketcher/assets/26869421/9363f182-cbf5-4476-b60b-f46ec6ede9ac)
![image](https://github.com/epam/ketcher/assets/26869421/c6bfb5fa-8068-4dec-acdd-5020da2e4f9d)
2. Go to micro mode
3. Press Save button

**Actual behavior**
System throws an error: number does not fit
![image](https://github.com/epam/ketcher/assets/26869421/e02239c7-5c9e-41aa-91f2-cbbe40f5288b)

**Expected behavior**
No error. Save should be possible

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.2.0-g1eba70228-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.7 Build at 2024-06-20; 18:42:41
 - Chrome Version 126.0.6478.115 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/ketcher/issues/4532

**Comment by rrodionov91** [comment]
Fixed by https://github.com/epam/ketcher/pull/4971

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/1057f0be-4db5-4464-9489-b3dccb813ee5)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)
