### ISSUE TITLE
Load image from KET file to canvas

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#4911]
As a **User**, I want the ability **to load images from a KET file** so that I can retrieve my image-enhanced chemical structures in a consistent and reusable format.

**Acceptance Criteria:**
1. A KET structure should be defined to save image data. This structure should accommodate all necessary image details:
  - Image in base64 format;
  - The X and Y positions of an image on the canvas;
  - Scaling is out of scope;
  - Z-order must be included to object properties, however, Z-positioning is out of scope.
2. The application should be able to draw an image on the canvas if image data exists in the loaded KET file.
3. The application should be able to handle multiple images in a single KET file, allowing for complex diagrams with multiple visual aids.
4. If the same image is used multiple times in a diagram, each instance of the image should be saved separately in the KET file.
5. Image scaling is out of scope for this user story. The application should preserve the original size of the image as it was at the time of saving.
6. The X and Y positions of an image on the canvas should be saved in the KET file and used to position the image correctly when loading from the KET file.
7. All images should be placed at the top layer on the canvas when loaded from a KET file.

**Comment by ivanmaslow** [comment]
Some points to fix are discovered during exploratory testing:
- Position of the image should be represented in .ket file using coordinates of center, height and width of image, now we have the different approach:
![image](https://github.com/epam/ketcher/assets/165396466/64eefea5-fa1a-498e-b39b-865d9cde1da6)
- Newly added shapes and arrows are on the top layer, not the picture:
![image](https://github.com/epam/ketcher/assets/165396466/22dc19da-4040-489a-9607-624a7c1c2c43)
- SVG images can be added too as a raster, we can remove this functionality as for DM comment.

**Comment by ivanmaslow** [comment]
Exploratory testing on the nightly environment is finished, points below are covered, tests are prepared:
- Images position on canvas is defined in .ket format using coordinates of the center, height and width of image:
![image](https://github.com/user-attachments/assets/4e850aa3-5127-464c-a50f-781fc8c794d5);
- Only images from allowed list can be added: **BMP, GIF, ICO, JPEG, JPG, PNG, WEBP, SVG**
- Images of all allowed formats with/without different entities (elements, structures, bonds, chains, groups, reactions, shapes, text) can be saved together to .ket file with the correct coordinates of images and sizes of files, after that loaded from .ket file and added to Canvas with the correct positions and layer levels (images are on the top layer in order of adding):
![image](https://github.com/user-attachments/assets/0ba728a2-a0e7-4e41-9401-9c96e677ea68)
- Images of all allowed formats can be copied from .ket format and added to Canvas  with the correct positions and layer levels by "Add to Canvas", "Open as New Project" and clipboard options;
- Added to Canvas Images of all allowed formats are not presented on the Canvas after switching to Macro mode and presented after returning to Micro
- Images of all allowed formats can be zoomed in/out (20, 400, 100) before/after adding to Canvas
-  Action of adding to Canvas images of all allowed formats together (BMP, GIF, ICO, JPEG, JPG, PNG, WEBP, SVG) can be Undo/Redo
- The .ket file with corrupted image can't be added to Canvas, error message is displayed:
![image](https://github.com/user-attachments/assets/199e495f-6f92-457e-bcdc-bce34427312b)

Some open points are remained

**Comment by yauhen-karmyzau** [comment]
>Warning when the user tries to save to inappropriate formats will be implemented later - task number TBD;

[#5105](https://github.com/epam/ketcher/issues/5105) was created

**Comment by ivanmaslow** [comment]
Change requests:
- Images should be displayed not in front, however, in back.
- Due to Indigo limitations, currently, we can save static image with PNG and SVG only, so the list of supported formats should be limited to these ones.

**Comment by haditariq** [comment]
[ket2-image.txt](https://github.com/user-attachments/files/16280633/ket2-image.txt)

I try to use attached file in (.ket) format. It passes the validation but doesn't display any image on the canvas.

**Comment by yauhen-karmyzau** [comment]
> [ket2-image.txt](https://github.com/user-attachments/files/16280633/ket2-image.txt)
> 
> I try to use attached file in (.ket) format. It passes the validation but doesn't display any image on the canvas.
This feature will be released in scope of [Ketcher 2.24.0-rc.1](https://github.com/epam/ketcher/milestone/124) and it has some dependencies to [#5055](https://github.com/epam/ketcher/issues/5055)

**Comment by ivanmaslow** [comment]
New exploratory testing iteration on the Nightly env (4902 [Version 2.23.0-rc.1] Build at 2024-07-12; 10:06:35) is completed, points below are covered, tests are updated:
- Images position on canvas is defined in .ket format using coordinates of the center, half size of image (must be > 0):
![image](https://github.com/user-attachments/assets/685ff50c-db28-4933-8a93-5f2a28e03c85)
- Only images from the allowed list can be added: PNG, SVG
- Images of allowed formats with/without different entities (elements, structures, bonds, chains, groups, reactions, shapes, text) can be saved together to .ket file with the correct coordinates of images and sizes of files, after that loaded from .ket file and added to Canvas with the correct positions and layer levels (images are at the **top** layer in order of adding to other images and at the **bottom** layer to other elements):
![image](https://github.com/user-attachments/assets/d8af5281-444c-46fd-8608-390a5755c543)
- Images of allowed formats can be copied from .ket format and added to Canvas with the correct positions and layer levels by "Add to Canvas", "Open as New Project" and clipboard options;
- Added to Canvas Images of allowed formats are not presented on the Canvas after switching to Macro mode and are presented after returning to Micro;
- Images of allowed formats can be zoomed in/out (20, 400, 100) before/after adding to Canvas;
- The action of adding to Canvas images of allowed formats together can be Undo/Redo;
- The .ket file with a corrupted data (wrong field name, wrong image type, not issues with base64, empty image) can't be added to Canvas, and an error message is displayed:
![image](https://github.com/user-attachments/assets/955a9101-c48c-444d-b3cd-bd43151d62cd);
- Appropriate error messages are updated: When the user tries to add not allowed format - "Unsupported image type", when the user tries to add image less than 16 px - "Image should be at least 16x16 pixels";

Remaining open defects have low priority and will be fixed later:
- https://github.com/epam/ketcher/issues/5146
- https://github.com/epam/ketcher/issues/5147

**Comment by ivanmaslow** [comment]
The data structure of the image in .ket will be changed - https://github.com/epam/ketcher/issues/5172

**Comment by Zhirnoff** [comment]
Tested.

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
