### ISSUE TITLE
Load Support for RDF Format in Ketcher

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#4914]
As a **User**, I want to have the ability to load and save my data in RDF format, So that I can easily exchange data with other applications that use the same format.

**Acceptance Criteria:**
1. When I choose to load data, the application should provide an option to load RDF files.
2. The application should be able to load RDF files from a specified location.
3. Upon loading an RDF file, the application should convert the RDF data back into the application's native format and represent the data on the canvas.
4. The application should properly handle any errors during the load process and display an appropriate error message.

**Comment by yauhen-karmyzau** [comment]
RDF can be Open with Ketcher and the content will be displayed on the canvas.
RDF parsing is/will be covered in scope Indigo: [Position pathway reaction on canvas](https://github.com/epam/Indigo/issues/2052), [Add Multi-tail Arrows to Pathway Reactions Loaded from RDF](https://github.com/epam/Indigo/issues/2128), [Position single elements and reactions, not included to the first cascade reaction](https://github.com/epam/Indigo/issues/2102).

**Comment by ivanmaslow** [comment]
Tested in scope of https://github.com/epam/Indigo/issues/2128, all details are provided there
