### ISSUE TITLE
Preview: Unsplit nucleotides could be adjasted (centered) better than it is now

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4919]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Put on the canvas few unsplit nucleotides from the library (nucleotides section in RNA tab)

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/9915bceb-336b-46a7-99f4-f9b13d12bcb9)
![image](https://github.com/epam/ketcher/assets/26869421/3323d9d5-2169-486e-9e64-b73843f4d3fc)

Nucleotide labels are not centered well and shifted to the left and up

**Expected behavior**
Labels should be centered better
![image](https://github.com/epam/ketcher/assets/26869421/73c809f7-5828-403a-a9a1-3b13f5836c6d)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Verified
<img width="1010" alt="Снимок экрана 2024-07-02 в 16 20 41" src="https://github.com/epam/ketcher/assets/174325443/e59327fe-a761-4b6c-ab02-cbbeb8c91025">
**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
