### ISSUE TITLE
Preview: Unable to load IDT codes for unsplit monomers we have in the library

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4920]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from IDT file: [Unable to load IDT codes for unsplit monomers we have in the library.zip](https://github.com/user-attachments/files/16027074/Unable.to.load.IDT.codes.for.unsplit.monomers.we.have.in.the.library.zip)
or paste from clipboard the following monomers:
```
/5Super-dG/
/55Br-dU/
/5Super-dT/
/55HydMe-dC/
/55NitInd/
/5AmdA/
/iAmMC6T/
```

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/4f77a6aa-8fb5-458b-b75b-ec55f64ef1f7)
Nucleotides recognized as unknown monomers

**Expected behavior**
Nucleotides recognized as monomers from the library
![image](https://github.com/epam/ketcher/assets/26869421/2f867343-482f-4cac-916f-d7749f600c49)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Verified
![Image](https://github.com/epam/ketcher/assets/174325443/d73ad29b-a10e-4adf-a49e-a4ced8f79cc9)
**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
