### ISSUE TITLE
RNA Preset without Base causes constant crash after switching to Macromolecules mode

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4924]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Go to RNA tab at Library
3. Press New Preset button and create preset without Base
![image](https://github.com/epam/ketcher/assets/26869421/a10dd681-7ca4-4987-a63e-6a18c60f1d99)
4. Press Add to Presets button
5. Reload Ketcher
6. Switch to Macromolecules mode

**Actual behavior**
System crashes into white screen forever and even reload of the page (including with Ctrl+F5) doesn't help
![image](https://github.com/epam/ketcher/assets/26869421/4b8d1aed-9f3e-4a5d-9a0c-aa250b652e63)
[ci.test.lifescience.opensource.epam.com-1719582442844.log](https://github.com/user-attachments/files/16030719/ci.test.lifescience.opensource.epam.com-1719582442844.log)
[ci.test.lifescience.opensource.epam.com-1719582447509.log](https://github.com/user-attachments/files/16030720/ci.test.lifescience.opensource.epam.com-1719582447509.log)

**Expected behavior**
No crash happens

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Tested, ok
https://github.com/epam/ketcher/assets/174325443/28522a83-6073-4681-ad68-1b0a2a3a3f49
**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
