### ISSUE TITLE
Unable to change atom to another if molecule has attachment point

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4925]
**Steps to Reproduce**
1. Load from file: [Unable to change atom to another if molecule has attachment point.zip](https://github.com/user-attachments/files/16031227/Unable.to.change.atom.to.another.if.molecule.has.attachment.point.zip)
OR manually create following configuration on the canvas: 
![image](https://github.com/epam/ketcher/assets/26869421/38f09074-8640-4eac-950c-1a70c7e22e87)
2. Go to rightside toolbar and select N-atom
3. Click on any atom of the benzene ring
![image](https://github.com/epam/ketcher/assets/26869421/6c710e81-1734-40da-b39b-f15731b1a9df)

**Actual behavior**
Nothing happens, all atoms remain unchanged
![image](https://github.com/epam/ketcher/assets/26869421/d0bcbc8f-fa8c-41b7-9871-8c93668186e3)

**Expected behavior**
System changes clicked atom to N
![image](https://github.com/epam/ketcher/assets/26869421/ed199c31-a882-479d-9b9a-1cc01aeba87a)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing https://github.com/epam/ketcher/issues/4530

**Comment by AnnaKosol** [comment]
Verified.
<img width="1512" alt="Снимок экрана 2024-07-02 в 13 17 18" src="https://github.com/epam/ketcher/assets/174325443/a640eb27-28ac-4791-8557-6d125622833a">
**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
