### ISSUE TITLE
System should show full set of IDT aliases at preview tooltip

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4928]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Go to the Library - RNA tab
3. Open presets section
4. Hover mouse over dR(U)P preset
5. Open Phosphates section
6. Hover mouse over P phosphate

**Actual behavior**
In case of dR(U)P it shows "Base" field value (deoxyU) because it has no modifications
![image](https://github.com/epam/ketcher/assets/26869421/ce0f9dd5-0c13-4093-8291-88a58f4619dd)
![image](https://github.com/epam/ketcher/assets/26869421/4634ebae-1401-41d7-bc3c-0ba32fc49f6f)

In case of P is shows list of modifications (3Phos, 5Phos) because it has it
![image](https://github.com/epam/ketcher/assets/26869421/71ba2ed3-400f-4d19-b9ec-e5ef0bc170d8)
![image](https://github.com/epam/ketcher/assets/26869421/416b6631-84aa-4b44-a7db-0406b2054f9f)

**Expected behavior**
@ljubica-milovic propose to show full list of modifications even if monomer doesn't have it
For dR(U)P it should be:
5deoxyU, ideoxyU, 3deoxyU

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Related issue - https://github.com/epam/ketcher/issues/4380

**Comment by Zhirnoff** [comment]
Test added to automation table.

**Comment by svvald** [comment]
There is a new logic for IDT aliases displaying described in https://github.com/epam/ketcher/issues/4880

**Comment by AlexeyGirin** [comment]
Verified.
System shows IDT aliases for presets from the library only
![image](https://github.com/user-attachments/assets/96f6f93d-59c6-45c7-87df-810807f736e3)

- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
