### ISSUE TITLE
System allow to change atoms inside S-group without removing abbreviation

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4929]
**Steps to Reproduce**
1. Load from file: [System allow to change atoms inside S-group without removing abbreviation.zip](https://github.com/user-attachments/files/16041984/System.allow.to.change.atoms.inside.S-group.without.removing.abbreviation.zip)
OR manually create following configuration on the canvas: 
![image](https://github.com/epam/ketcher/assets/26869421/391f1bbf-c137-4ef4-b2e1-69cfaf925a75)
2. Select atoms inside s-group (click on it)
![image](https://github.com/epam/ketcher/assets/26869421/277a1b69-54ba-40d6-b8cc-e00e82c9ecbd)
3. Press N button in the right side tool bar
![image](https://github.com/epam/ketcher/assets/26869421/c445d956-f57c-40b2-9f4a-d57bfdbaeffd)

**Actual behavior**
Atoms have been changed
![image](https://github.com/epam/ketcher/assets/26869421/37f41f1f-6809-4f70-80df-b7478143fe56)

**Expected behavior**
Remove abbreviation appears
![image](https://github.com/epam/ketcher/assets/26869421/b9f4916f-fe4d-45de-9aa9-c0ef5cfbe984)
(if user accepts - it applies proposed changes)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Related issue: https://github.com/epam/ketcher/issues/4925

**Comment by Zhirnoff** [comment]
Moved to 2.23.0-rc.2 after discussion with developer @Guch1g0v because he has a pull request ready

**Comment by AlexeyGirin** [comment]
Verified.
![Image](https://github.com/user-attachments/assets/d9bce1d4-5e83-4b86-8856-6c110ce07bde)

- Ketcher Version 3.0.0-rc.1 Build at 2025-01-28; 05:37:00
- Indigo Version 1.29.0-dev.2.0-g4960b8ef-wasm32-wasm-clang-19.0.0
- Chrome Version 132.0.6834.111 (Official Build) (64-bit)
- Win10
