### ISSUE TITLE
Preview: IDT aliases are missed for unsplit nucleotides in the library

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4930]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Go to RNA tab at library and open Nucliotides section
3. Hover mouse over any nucleotide to get preview tooltip

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/5a083ff1-648a-4dcd-9314-b2d9499a1118)
Nucleotide has no IDT alias associated

**Expected behavior**
Every nucleotide at the libtrary should have IDT alias assigned
Full   name | IDT   alias
-- | --
5' Super G | 5Super-dG
5' 5-Bromo dU | 55Br-dU
5' Super T | 5Super-dT
5' 5-Hydroxymethyl dC | 55HydMe-dC
5' 5-Nitroindole | 55NitInd
5' 2,6-Diaminopurine | 5AmdA
Int Amino Modifier C6 dT | iAmMC6T

As per [requirements](https://github.com/epam/ketcher/issues/4382):
> 7. On preview chemical structure together with name and IDT alias should be displayed. 

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Verified
<img width="1512" alt="Снимок экрана 2024-07-02 в 12 27 28" src="https://github.com/epam/ketcher/assets/174325443/61869017-85dc-4366-9161-7f30ab88c90a">

**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)
