### ISSUE TITLE
Preview: Unsplit nucleotide without natural analog should be displayed as '@' symbol

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4932]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Put to the canvas 55NitInd nucleotide (it has no natural analog) from the library (Nucleotides section)
![image](https://github.com/epam/ketcher/assets/26869421/841d4008-8769-4973-b4a5-9d8bf67930bc)
3. Switch to Sequence mode

**Actual behavior**
Nucleotide displayed as 'X' symbol
![image](https://github.com/epam/ketcher/assets/26869421/1202bdfa-a5d5-4fc1-82f9-47f488bb6d3d)

**Expected behavior**
Nucleotide displayed as '@' symbol
![image](https://github.com/epam/ketcher/assets/26869421/02779fb6-188d-4752-8168-fa4efa313f4e)

As per [requirements](https://github.com/epam/ketcher/issues/4382):

> 6. Unsplit nucleotides should be displayed: 
>       - in flex/snake modes - as a pentagon with name (see mockups)
>       - in sequence view - as natural analog symbol if it's specified, otherwise - as '@' symbol
> 

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Verified
![Image](https://github.com/epam/ketcher/assets/174325443/73d8235d-8f9c-454b-9d77-0950333e0464)
**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
