### ISSUE TITLE
Preview: Enumeration works wrong for single unsplit nucleotide

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4933]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Go to RNA tab at library and open Nucliotides section
3. Put any unsplit monomer on the canvas
![image](https://github.com/epam/ketcher/assets/26869421/f8bc9e33-9e1f-4b46-b670-1feecd6e12dc)

**Actual behavior**
No enumeration for single unsplit nucleotide
![image](https://github.com/epam/ketcher/assets/26869421/1c251edf-2566-4ebe-bec4-5131f510d523)

**Expected behavior**
Enumeration should be started even for single unsplit nucliotide
![image](https://github.com/epam/ketcher/assets/26869421/f8a18e56-9908-41a7-95b1-3ebe29b38e6b)

As per [requirements](https://github.com/epam/ketcher/issues/3222):

> 1.3 Enumeration should start even single RNA (added as result of [conversation](https://github.com/epam/ketcher/issues/3222#issuecomment-2198104307) with @olganaz)

Confirmed by @olganaz for unsplit nucleotide:
![image](https://github.com/epam/ketcher/assets/26869421/c65cfeaa-73d8-4769-9be2-b9f697c032f0)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Verified
![Image](https://github.com/epam/ketcher/assets/174325443/40cd3ad5-7c1d-493e-9f11-4debf10921a5)
**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
