### ISSUE TITLE
Preview: Enumeration counters remain unchanged after bond being deleted

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4934]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from file: [Enumeration counters remain unchanged after bond being deleted.zip](https://github.com/user-attachments/files/16039782/Enumeration.counters.remain.unchanged.after.bond.being.deleted.zip)
OR manually create the following configuration:
![image](https://github.com/epam/ketcher/assets/26869421/d38451c3-e905-4feb-8789-d6b52eb6cd52)
3. Delete bond between nucleotides

**Actual behavior**
Enumeration counter is wrong (remain 2 - should be 1)
![image](https://github.com/epam/ketcher/assets/26869421/67728e9a-d1bc-458b-bb08-3f0ac0700890)

**Expected behavior**
Enumeration counter should be 1
![image](https://github.com/epam/ketcher/assets/26869421/4650ffd6-2e13-4b77-8734-2daf15dbc039)

As per [requirements](https://github.com/epam/ketcher/issues/3222):

> 1.3 Enumeration should start even single RNA (added as result of [conversation](https://github.com/epam/ketcher/issues/3222#issuecomment-2198104307) with @olganaz)

Confirmed by @olganaz for unsplit nucleotide:
![image](https://github.com/epam/ketcher/assets/26869421/c65cfeaa-73d8-4769-9be2-b9f697c032f0)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Tested, ok
![Image](https://github.com/epam/ketcher/assets/174325443/6571e5d9-9d55-4655-84a2-8806e3eea108)
**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
