### ISSUE TITLE
Applying Enhanced Stereochemistry to monomers causes its disappear from the canvas (and exception in console)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4936]
**Steps to Reproduce**
1. Go to Molecules mode
2. Load from file: [Two nucleotides.zip](https://github.com/user-attachments/files/16041155/Two.nucleotides.zip)
OR manually create the following configuration:
![image](https://github.com/epam/ketcher/assets/26869421/521ab3f6-6337-4207-9548-c1fe25eeedca)
3. Press Stereochemistry button and press Apply button in appeared dialog

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/fbaaa766-1497-4aed-8345-244d363eb86a)
![image](https://github.com/epam/ketcher/assets/26869421/5ca57c32-d20a-49e4-a7af-00c6dc02be85)
[ci.test.lifescience.opensource.epam.com-1719675261084.log](https://github.com/user-attachments/files/16041159/ci.test.lifescience.opensource.epam.com-1719675261084.log)

**Expected behavior**
No exception, No Stereochemistry applied
![image](https://github.com/epam/ketcher/assets/26869421/521ab3f6-6337-4207-9548-c1fe25eeedca)
If only monomers on the canvas and no other stereo molecules - Stereochemistry button should disabled

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AlexeyGirin** [comment]
Not fixed.
Currently - it simply disable Stereochemistry button if monomers present on the canvas
![image](https://github.com/user-attachments/assets/c6c0922e-ccaf-4bb6-8bc4-fd1c17179c37)

**Versions**
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by SashaGraves** [comment]
Label does not change after changing stereometry, if molecule was placed at starting point of canvas.
Steps to reproduce:
1) Choose in upper menu 'Open...' => 'Open from file' => Choose file => press 'Add to Canvas'. DO NOT MOVE MOLECULE. Tap mouse button and let molecule be placed where it appeared initially.
2) Change stereometry. Observe: label did not changed.

If you move molecule before placing to canvas, label changes successfully.

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-11-07_13h37_24](https://github.com/user-attachments/assets/02e08d80-5e6b-4fa2-acdd-a1051a785f42)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
