### ISSUE TITLE
Preview: Save to MOL v2000 works wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4937]
**Steps to Reproduce**
1. Go to Molecules mode
2. Load from file: [Two nucleotides.zip](https://github.com/user-attachments/files/16041155/Two.nucleotides.zip)
OR manually create the following configuration:
![image](https://github.com/epam/ketcher/assets/26869421/521ab3f6-6337-4207-9548-c1fe25eeedca)
3. Save canvas to MOL 2000
4. Load it back as New project

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/82c183f7-8b1e-4863-965a-f226a1cd607c)

**Expected behavior**
![image](https://github.com/epam/ketcher/assets/26869421/521ab3f6-6337-4207-9548-c1fe25eeedca)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by rrodionov91** [comment]
Does not reproduce. Fixed in https://github.com/epam/ketcher/issues/4973
Monomers save in molv2000 as sgroups

**Comment by AlexeyGirin** [comment]
Fixed.
