### ISSUE TITLE
Preview: Select Connection Points dialog preview frame shouldn't be blank for unknown monomer

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4949]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `/i2AmPr/`
![image](https://github.com/epam/ketcher/assets/26869421/fbc222f8-0ed5-450b-8db7-8e11418896d5)
3. Put any CHEM on the canvas
4. Connect them by bond (center-to-center)

**Actual behavior**
System opens Select Connection Points dialog having preview frame blank for unknown monomer
![image](https://github.com/epam/ketcher/assets/26869421/2badf2c0-c916-428f-80e6-ac51b5818b0a)

**Expected behavior**
System opens Select Connection Points dialog having preview frame with question mark (taken from preview tooltip)
![image](https://github.com/epam/ketcher/assets/26869421/451bd652-1163-4c14-a256-fd2fc8996991)

As agreed with @AlexanderSavelyev and @vanoprenko 

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4431

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/51046e0b-c8ba-48bd-9df7-d1d21169babb)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by Zhirnoff** [comment]
Tested.
![2024-08-07_14h09_59](https://github.com/user-attachments/assets/c5f69a65-5d7a-4c65-87bb-30c1abc9265f)
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
