### ISSUE TITLE
Preview: Unable to copy/paste unresolved monomer - nothing happens

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4951]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `/i2AmPr/`
![image](https://github.com/epam/ketcher/assets/26869421/fbc222f8-0ed5-450b-8db7-8e11418896d5)
3. Select it and press Ctrl+C and than Ctrl+V
![image](https://github.com/epam/ketcher/assets/26869421/0adb48d4-0759-437a-810c-69c5a6e4f4d5)

**Actual behavior**
Nothing happens
![image](https://github.com/epam/ketcher/assets/26869421/36ae807f-eacf-4eff-8900-3130dae9e8e3)

**Expected behavior**
System put copy of `i2AmPr` monomer to the canvas
![image](https://github.com/epam/ketcher/assets/26869421/fbc38db8-8ad8-42b2-8d55-de10385b1e13)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4431

**Comment by AnnaKosol** [comment]
Tested, ok
![Image](https://github.com/epam/ketcher/assets/174325443/c8bf65d2-3436-40e4-a807-076624c1ebd7)
Versions:
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
