### ISSUE TITLE
Disabled query features in extended table not disabled in right-click menu

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#4957]
**Steps to Reproduce**
1. Disable some query feature via Console ( for example `ketcher.setSettings({
      disableQueryElements: ['Pol', 'MH', 'AH'],
    })`

![2024-07-08_15h18_43](https://github.com/epam/ketcher/assets/62464241/6a42f104-44b0-44af-86e4-062a10fc0f37)
2. Add Benzene ring on canvas
3. Click on atom of Benzene ring by right-click -> Edit...
4. Set Atom Type to Special
5. Type any disabled element from Extended table into Special field

**Actual behavior**
Disabled query features in extended table not disabled in right-click menu. If user have Atom Type set to 'Special' and they enter disabled element in the 'Special' field, Ketcher allow to apply this change.
![2024-07-08_15h40_39](https://github.com/epam/ketcher/assets/62464241/8126af75-f0bd-45cc-a8fc-a8a24ab2f83c)

**Expected behavior**
Disabled query features in Extended table should also be disabled in the right-click menu. If user have Atom Type set to 'Special' and they enter disabled element in the 'Special' field, Ketcher doesn't allow to apply this change.
![2024-07-08_15h41_14](https://github.com/epam/ketcher/assets/62464241/7f6e4cc9-8c43-49e7-bc24-00980c628268)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.7]
**Indigo version** 
[Version 1.21.0-rc.2]

#187864458

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/e2ba0518-7088-4b20-bbea-16929b42936b)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-08-07_14h05_05](https://github.com/user-attachments/assets/ed9c0ee5-7b0a-421b-b4db-9ff63a21d052)
![2024-08-07_14h05_16](https://github.com/user-attachments/assets/37ac8cbe-3577-4192-a800-30360f56ce61)
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
