### ISSUE TITLE
Connection between molecule and monomer lost after opening and saving to ket

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#4973]
**Steps to Reproduce**

1. Open Ketcher.
2. Draw a benzene ring
3. Add an attachment point to the benzene ring via right click menu
4. Switch to Macro mode and connect attachment point to a macro structure
5. Switch to Micro mode
6. Save structure in KET format
7. Open saved file in micro mode using Add to canvas button
8. Move mouse with paste preview over the canvas
9. Click on canvas
10. Save structure in KET format

**Actual behavior**
Connection between molecule and monomer is NOT saved in ket file

**Expected behavior**
Connection between molecule and monomer is saved in ket file

**Ketcher version** [e.g. v2.4.2]. 
v2.22.0-rc.8

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/ketcher/assets/26869421/0a78dfa4-0592-478a-93d7-35d6f04d3cc4)

Ketcher Version 2.22.0-rc.9 Build at 2024-07-04; 15:58:14
Indigo Version 1.21.0-rc.3.0-g1570d3f9f-wasm32-wasm-clang-19.0.0
Win 10
Chrome Version 126.0.6478.127 (Official Build) (64-bit)
