### ISSUE TITLE
System doesn't show side chain bonds if chain loaded directly to Snake-mode canvas

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#4977]
**Steps to Reproduce**
1. Go to Macromolecules mode - Snake mode **<-- IMPORTANT!**
2. Load using paste from clipboard IDT type: `PEPTIDE1{C.[Apm].D.[dC].E}|PEPTIDE2{F.[D-gGlu].G.[D-Orn].I}$PEPTIDE1,PEPTIDE2,2:R3-2:R3|PEPTIDE2,PEPTIDE1,4:R3-4:R3$$$V2.0`
![image](https://github.com/epam/ketcher/assets/26869421/ddab5fc0-8de5-4bd0-ba1c-714329f5257f)

**Actual behavior**
Side chain bonds are missed
![image](https://github.com/epam/ketcher/assets/26869421/27d05564-7943-4d7f-a28b-94a56f948029)

**Expected behavior**
Side chain bonds are in place
![image](https://github.com/epam/ketcher/assets/26869421/e2fc773e-dd27-4d88-b090-5fbeb93549c5)

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AnnaKosol** [comment]
Verified
![Image](https://github.com/epam/ketcher/assets/174325443/2cfbd837-dc9a-4478-aa35-dc1920734d1a)
**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
