### ISSUE TITLE
Support for Strict mode

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/ketcher#4979]
Support for Strict mode

**Comment by AlexeyGirin** [comment]
No test cases needed for that issue

**Comment by AlexeyGirin** [comment]
Verified verbally.
Strict mode doesn't affect on the release version of application, only dev builds affected

**Comment by AlexeyGirin** [comment]
Verified verbally.
Strict mode doesn't affect on the release version of application, only dev builds affected

- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
