### ISSUE TITLE
Support for SSR

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/ketcher#4981]
**Background**
It is impossible to use ketcher in SSR applications because of errors. The reason is that ketcher uses browser APIs, such a "window" object, which are not supported on server side.

**Solution**
Create example of SSR application which uses ketcher (similar what we have in /example folder). Wrap all usages of unsupported APIs into conditions to exclude it from execution on server side. Probably better option is to wrap the initialisation code to have this check in one place only.

**Additional context**
It was found that Raphaeljs library(used for render in molecules mode) uses window object.

**Comment by AlexeyGirin** [comment]
No test cases needed for that issue

**Comment by AlexeyGirin** [comment]
Verified verbally.

- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
