### ISSUE TITLE
Choose both directions of wedged/hashed bonds from right-clicking the bond 

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/ketcher#4982]
User should be able to change the direction of a directed bond on canvas via bond context menu. For this purpose a new menu item 'Change direction' should be added to the bond context menu. The new item should appear above 'Attach S-Group...'.  

The new menu item should appear for the following types of bond only:
- Dative
- Single Up
- Single Down
- Single Up/Down

The new menu item should change bond direction to the opposite.

![image](https://github.com/user-attachments/assets/e281df6f-0f76-49c8-a07a-daf59723016e)

(?) Related Indigo task - [#2069](https://github.com/epam/Indigo/issues/2069)

**Comment by AnnaKosol** [comment]
Verified
<img width="381" alt="Снимок экрана 2024-09-20 в 13 01 05" src="https://github.com/user-attachments/assets/a3c498ad-bccc-47d3-ae0b-4e7c086649e8">

**Environment**:
Ketcher Version 2.25.0-rc.2 Build at 2024-09-20; 05:37:02
Indigo Version 1.25.0-dev.1.23-gb97a4a6d-wasm32-wasm-clang-12.0.0
Chrome 128.0.6613.138
MacOs 14.6

**Comment by AnnaKosol** [comment]
Verified - there is a new section in the menu and direction is changed.
<img width="334" alt="Screenshot 2024-10-08 at 12 14 57" src="https://github.com/user-attachments/assets/1ba92138-3a05-42d1-8945-4014eca6300f">

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
