### ISSUE TITLE
Settings for the "attachment point tool" don't update with changed pixel settings 

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/ketcher#4983]
T-shape attachment points created with the Attachment Point Tool (or loaded from an external file) do not respect 'Bond thickness' global setting and are always drawn with default thickness. 

Steps to reproduce:
1. Add a single bond and an attachment point to a drawing.
2. Go to Settings->Bonds and change the 'Bond thickness' parameter (e.g. increase up to 6)
3. See that line width of the single bond has been updated accordingly while line width of the attachment point remain the same.

![image](https://github.com/user-attachments/assets/654df1f2-50ec-4366-8eb8-c0cd570f407e)

'Bond thickness' setting should apply to attachment points, similarly to bonds. 

(?) Related Indigo task - [#2070](https://github.com/epam/Indigo/issues/2070)

**Comment by AnnaKosol** [comment]
**Steps:**
1. create benzine ring with attachment points
![Image](https://github.com/user-attachments/assets/3edf5059-2f55-4e5f-a7b9-e2558c1c1918)
2. change Bond thickness to 0.2 cm
3. click on Apply button

**Actual result:**
![Image](https://github.com/user-attachments/assets/d2f2af4a-622b-448a-a74a-00f31b73b779)
attachment point isn't changed thickness

**Expected result:**
attachment point is changed thickness

**Comment by AnnaKosol** [comment]
**Steps:**
1. create molecule with primary attachment point
![Снимок экрана 2024-09-18 в 15 29 47](https://github.com/user-attachments/assets/484d7a4b-c659-421f-b5ca-84616a46fee2)
2. change setting Bond thickness to 0.2 px
3. click on Apply button

**Actual result:**
primary attachment point isn't displayed
![Снимок экрана 2024-09-18 в 15 34 16](https://github.com/user-attachments/assets/776d71d3-0133-4191-9f6c-5f4a1e9464cd)

![Снимок экрана 2024-09-18 в 15 31 27](https://github.com/user-attachments/assets/0b41bde5-42c2-4d4f-9e6f-d4d6d8a5c052)

**Expected result:**
all parts of molecule are displayed regarding settings

**Comment by AnnaKosol** [comment]
Verified
<img width="185" alt="Снимок экрана 2024-09-19 в 14 22 29" src="https://github.com/user-attachments/assets/569adc9a-6622-491a-8397-e0c1df74a60d">

**Environment**
Ketcher Version 2.25.0-rc.1 Build at 2024-09-18; 05:33:09
Indigo Version 1.25.0-dev.1.19-ge314cdb7-wasm32-wasm-clang-12.0.0
Chrome 128.0.6613.138 (arm64)
MacOs 14.6

**Comment by AnnaKosol** [comment]
<img width="572" alt="Screenshot 2024-10-08 at 14 53 08" src="https://github.com/user-attachments/assets/24c6504f-8b74-4ea5-9f5c-3cc7b4e8d55b">

Verified - attachment point updates by thickness

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
