### ISSUE TITLE
Highlight atoms and bonds

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/ketcher#4984]
Ketcher API includes functions that allow highlighting atoms and bonds of the drawing with a colored background. This feature is not available from within Ketcher UI, so regular users cannot do the highlighting. 

Introduce new 'Highlight' item in the atom/bond context menu that would allow user to highlight selected atoms and bonds. User should be able to select one of eight predefined highlight colors or clear the highlighting. 

The new menu item should be added to the following menu positions:
- In the atom context menu -- below 'Add attachment point';
- In the bond context menu -- below 'Attach S-Group...';
- In the context menu for a selection of atoms and bonds -- below 'Enhanced stereochemistry...', separated by a horizontal _delimiter line_.

Specific colors are highlighted in the mockup below. Please note that the new menu item is drawn on a _wrong position_.
  
![color-change-min](https://github.com/user-attachments/assets/08da1818-68aa-4010-98c0-c51f3239c4d4)

**Comment by AnnaKosol** [comment]
<img width="868" alt="Screenshot 2024-10-08 at 12 38 06" src="https://github.com/user-attachments/assets/8ebd8a71-f8f4-40e5-a1d3-cd9a0163ff41">

Verified 

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
