### ISSUE TITLE
Support retrosynthetic arrows

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/ketcher#4985]
**Background**
The retrosynthetic arrow is meant to depict the process of breaking down a complex molecule to simpler starting materials. This is useful as a planning device to highlight a key strategy used for building a molecule.

**Solution**

* Add new mode "retrosynthetic" for type "arrow" into KET specification to be able save/load such reactions
* Add new icon with "Retrosynthetic" tooltip for the bonds menu (after "Failed Arrow Tool")
![image](https://github.com/epam/ketcher/assets/7427808/e732d552-2af4-4c65-a2d7-a38de9dc55cb)
* Add new type of bond (resizable, rotatable) 
![image](https://github.com/epam/ketcher/assets/7427808/22dc1881-f1e8-4824-be74-b97b1bf1fdcc)

For Import/Export into RXN (2000/3000), SMILES, SMARTS, CML formats warning should appear that some information can be lost.

Related Indigo task - [#2071](https://github.com/epam/Indigo/issues/2071)

**Comment by AleksandrParamonoff** [comment]
[ket_files_with_retrosynthetic_arrow.zip](https://github.com/user-attachments/files/16494610/ket_files_with_retrosynthetic_arrow.zip)
Input data in .ket format for testing purposes

**Comment by AnnaKosol** [comment]
Verified by manually and autotests
![Image](https://github.com/user-attachments/assets/6d09a4cd-be3a-4661-96ea-8d1f6e87f358)

**Environment details:**
Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.6
