### ISSUE TITLE
Ctrl+move for copy

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/ketcher#4986]
User should be able to create and move a duplicate of selected fragment by holding Ctrl key (Cmd for Mac) and moving the mouse cursor.

The new function should be activated if there is a selected fragment on the canvas, user holds Ctrl key and starts moving the mouse cursor. A copy of selected fragment should be created and start following the cursor movement -- the behavior should be similar to pasting from the clipboard. 

Once the movement starts, the selection should be removed from the original fragment. The structure being moved should have the selection applied.

![image](https://github.com/user-attachments/assets/e9897cdb-93a9-4cc8-b2c8-0f3ad9d3e174)

**Comment by AnnaKosol** [comment]
Verified on https://nightly.test.lifescience.opensource.epam.com/KetcherDemoSA/4986-ctr-move-copy/index.html
**Environment**
Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 11:28:33
Indigo Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
MacOs 15.0
Chrome Version 129.0.6668.71 (Official Build) (arm64)
![Image](https://github.com/user-attachments/assets/327bb194-8a46-4d60-b99f-98beaa388bf2)

**Comment by AnnaKosol** [comment]
Verified

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
