### ISSUE TITLE
Wrong modal window, a blank page and an error in console after trying to add the Attachment points/R-sites to a structure

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#499]
_Affected versions:_ Remote, Standalone.
Tested on Ketcher v2.2.1-92-ge17451e1.

_Steps to reproduce:_
1. Launch Ketcher.
2. Draw a structure (e.g. chain).
3. Select the 'R-Group Label Tool'.
4. Click any atom.
5. Click the 'OK' button.

_Expected result:_
4. The 'R-Group' window opens. It's possible to add an R-Site to the structure.

_Actual result:_ 
4. The 'Periodic Table' window opens. 
5. A blank page and an error in console appear.

![PT](https://user-images.githubusercontent.com/80695128/116254200-d157b680-a779-11eb-9347-ed5705a2b250.gif)

The issue with wrong modal window can be reproduced with the 'Attachment Point Tool'. A blank page doesn't appear in this case.

![PT_2](https://user-images.githubusercontent.com/80695128/116254525-15e35200-a77a-11eb-9e85-31828e3f4db1.gif)

**Comment by MagomedGasanov** [comment]
This problem was caused by PR https://github.com/epam/ketcher/pull/477: 
After ``

**Comment by Svetlana-Asinovskaia** [comment]
The issue is closed as fixed.
