### ISSUE TITLE
Preview: Save of unknown monomer to KET gives invalid ket file

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5001]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `/i2AmPr/`
![image](https://github.com/epam/ketcher/assets/26869421/fbc222f8-0ed5-450b-8db7-8e11418896d5)
![image](https://github.com/epam/Indigo/assets/26869421/c30393b4-11e9-4d3d-b8cb-f0aa9aab974f)
3. Save canvas to KET file
4. Load it back

**Actual behavior**
System throws exception: Convert error! Error during file parsing.
![image](https://github.com/epam/Indigo/assets/26869421/4aa0aff9-4c8e-4bb5-84ca-524452f8abc9)

**Expected behavior**
System saves and load ket file correct:
![image](https://github.com/epam/Indigo/assets/26869421/c30393b4-11e9-4d3d-b8cb-f0aa9aab974f)

As per [requirements](https://github.com/epam/ketcher/issues/4431):
```
There should be possible to load such monomers from IDT and KET formats and save to these formats.
```

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4431

**Comment by AnnaKosol** [comment]
Verified
![Image](https://github.com/epam/ketcher/assets/174325443/2cbc1d73-3b0e-431a-bf6f-b8f4e57a498d)
Versions:
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
