### ISSUE TITLE
Preview: Unable to save mix of unresolved nucleotides and nucleotides to Sequence (and FASTA)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5030]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Open from file: [Unable to save mix of unresolved nucleotides and nucleotides to sequence.zip](https://github.com/user-attachments/files/16032141/Unable.to.save.mix.of.unresolved.nucleotides.and.nucleotides.to.sequence.zip)
OR create manually the following canvas:
![image](https://github.com/epam/Indigo/assets/26869421/bf6f6935-6ab6-4725-9aa2-e3320fcaeb53)
3. Save canvas to Sequence format file (or FASTA)

**Actual behavior**
System throws an exception: Convert error! Error during sequence type recognition(RNA, DNA or Peptide)
Sequence:
![image](https://github.com/epam/Indigo/assets/26869421/8fef3c4c-2bf7-48a0-b025-2442ddddd0c8)
FASTA:
![image](https://github.com/epam/Indigo/assets/26869421/bdfd3ea8-3927-4049-9f3b-7ef892dab0df)

**Expected behavior**
Since unresolved nucleotide is nucleotide - it should be recognized as DNA

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AnnaKosol** [comment]
Issue is still reproduced
Sequence:
![Image](https://github.com/epam/ketcher/assets/174325443/5e2819b4-4aa7-41c8-a00d-6c59eb113696)
FASTA:
![Image](https://github.com/epam/ketcher/assets/174325443/53333e01-96af-4450-bd88-062be32a5832)
**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/15140ee9-35c5-4cdd-8d25-0132b711f50f)

- Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
- Indigo Toolkit Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
