### ISSUE TITLE
Selection of monomers should disappear when the user moves the cursor

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5032]
**Steps to Reproduce**
1. Go to Ketcher macromolecules mode
2. Enter any sequence with at least 2 symbols.
3. Enter edit mode.
4. Select a monomer.
5. Pres left on the keyboard.

**Actual behavior**
The user is able to move the cursor, and monomers stay selected.
![image](https://github.com/epam/ketcher/assets/169887211/11743782-0990-447f-83c3-ec490673e04d)

**Expected behavior**
When the user selects monomer(s), and moves the cursor, the selection should dissapear.

**Ketcher version [v2.23.0]**

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/7f37f5e3-a99b-4a67-bf90-8b762f22d404



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
