### ISSUE TITLE
When dragging the side chain connections between CHEM, all these connections pass exclusively from the left, and not the shortest path

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5034]
**Case 1: The vertical side chain connections**

**Steps to Reproduce**
1.	Switch to the Macro mode – the Snake mode
2.	Open this file [CHEM many APs.zip](https://github.com/user-attachments/files/16130415/CHEM.many.APs.zip)
3.	Drag several vertical side-chain connections 

**Case 2: The horizontal side chain connections**

**Steps to Reproduce**
1.	Switch to the Macro mode – the Snake mode
2.	Open this file [CHEM many APs.zip](https://github.com/user-attachments/files/16130409/CHEM.many.APs.zip)
3.	Drag several horizontal side-chain connections 

**Actual behavior**
All these side-chain connections pass exclusively from the left, and not the shortest path

<img width="497" alt="image" src="https://github.com/epam/ketcher/assets/139227567/540e4070-2e03-4085-b815-785920d93e3d">

<img width="480" alt="image" src="https://github.com/epam/ketcher/assets/139227567/3c62db5f-14a2-4c11-bef1-205e0dfaacbd">

**Expected behavior**
The vertical and horizontal side-chain connections pass by the shortest path when possible. The horizontal connections should be drawn horizontally above the monomers

**Screenshots**

https://github.com/epam/ketcher/assets/139227567/5f625d03-aa95-4b04-8238-ca59819f8c5d

https://github.com/epam/ketcher/assets/139227567/ccb7aeab-34b9-4334-98ec-a43480920886

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (126.0.6478.127) x64

**Ketcher version** 2.23.0-rc.1, Build at 2024-07-02; 09:03:38

Issue found while testing https://github.com/epam/ketcher/issues/3532

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-11_17h41_40](https://github.com/epam/ketcher/assets/62464241/401974d4-5fbe-4116-82bf-b2a630e02b61)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.2]
**Indigo version** 
[Version 1.22.0-rc.2]
