### ISSUE TITLE
[Regress] Preview tooltip is wrong for sugar monomer

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5042]
**Steps to Reproduce**
1. Load from mol file: 
[10 - (R2,R3,R4).zip](https://github.com/user-attachments/files/16141374/10.-.R2.R3.R4.zip)
![image](https://github.com/epam/ketcher/assets/26869421/1a55436e-0669-4334-8d07-e29fe821e474)
2. Hover mouse over and check preview tooltip

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/85cf4a7c-1d52-4c8b-bfa5-30126ce56402)
R4 ap is missing

**Expected behavior**
![image](https://github.com/epam/ketcher/assets/26869421/71f94270-c38f-403e-9943-597cb4ab146c)
R4 ap is in place

**Environment details:**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
- Indigo Toolkit Version 1.21.0-rc.3.0-g1570d3f9f-x86_64-linux-gnu-11.2.1
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by rrodionov91** [comment]
Can't reproduce

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/d11ee0c9-c7f3-4f91-9644-180f4358d98a)
- Ketcher Version 2.24.0-rc.2 Build at 2024-08-14; 19:00:14
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10
