### ISSUE TITLE
The structure changes when saved in SVG/PNG formats 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5043]
**Summary**
The structure changes when saved in SVG/PNG formats 

**Steps to Reproduce**
1. Open Ketcher.
2. Draw a benzene ring
3. Add an attachment point to the benzene ring via right click menu
4. Switch to Macro mode and connect attachment point to a macro structure
5. Switch to Micro mode
6. Save structure in SVG/PNG formats 

If it is not possible to draw the structure, then you can open the prepared file (you just need to open it in macro mode and then switch to micro mode): 
[ketcher (53).zip](https://github.com/user-attachments/files/15620336/ketcher.53.zip)

**Expected behavior**
The structure not changes when saved in SVG/PNG formats 
![2024-06-06_14h02_50](https://github.com/epam/Indigo/assets/62464241/5e242819-89d6-40a3-888a-8a73a99611b1)

**Actual behavior**
The structure changes when saved in SVG/PNG formats 
![2024-06-06_15h44_44](https://github.com/epam/Indigo/assets/62464241/76b504ca-db3d-41d6-8133-9dfbe25d20ee)
![2024-06-06_15h59_43](https://github.com/epam/Indigo/assets/62464241/310ec1b7-79f1-4645-b7bb-0fb09d167905)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
**Indigo version** 
[Version 1.21.0-rc.1]

**Refers to feature:** https://github.com/epam/ketcher/issues/4530
**Issue on Ketcher side:** https://github.com/epam/ketcher/issues/4879

**Comment by rrodionov91** [comment]
Hydrogen bond removed after serialisation here https://github.com/epam/ketcher/issues/4973

**Comment by AlexeyGirin** [comment]
Moved to Indigo - https://github.com/epam/Indigo/issues/2110
