### ISSUE TITLE
Layout for some chains in snake mode is wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5047]
**NOTE:** Probably the same root cause with https://github.com/epam/ketcher/issues/5048 and https://github.com/epam/ketcher/issues/5049

**Steps to Reproduce**
1. Go to Macromolecules - Flex mode <---Important!
2. Load from file: [Layout for some chains in snake mode is wrong.zip](https://github.com/user-attachments/files/16146065/Layout.for.some.chains.in.snake.mode.is.wrong.zip)
![image](https://github.com/epam/ketcher/assets/26869421/7fd2a0f7-4596-4bd2-855f-4d420fafa030)
3. Switch view to Snake mode

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/8c6734b8-da9b-4004-85d7-cc4d222cdd69)
Molecule layout is wrong

**Expected behavior**
![image](https://github.com/epam/ketcher/assets/26869421/ee5643dd-013b-493c-9357-121d0e6ef5f4)

**Environment details:**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
- Indigo Toolkit Version 1.21.0-rc.3.0-g1570d3f9f-x86_64-linux-gnu-11.2.1
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/3532

**Comment by rrodionov91** [comment]
Does not reproduced
