### ISSUE TITLE
Switching mode from Sequence mode to Flex mode left undeletable artifacts on the canvas

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5048]
**NOTE:** Probably the same root cause with https://github.com/epam/ketcher/issues/5047 and https://github.com/epam/ketcher/issues/5049

**Steps to Reproduce**
1. Go to Macromolecules (sequence mode)
2. Load from file: [Switching mode from Sequence mode to Flex mode left undeletable artifacts on the canvas.zip](https://github.com/user-attachments/files/16146572/Switching.mode.from.Sequence.mode.to.Flex.mode.left.undeletable.artifacts.on.the.canvas.zip)
![image](https://github.com/epam/ketcher/assets/26869421/46ad6a26-6114-4575-91cf-0c1d9f5e346c)
3. Switch view to Flex mode

**Actual behavior**
![image](https://github.com/epam/ketcher/assets/26869421/ae7793c5-f891-451f-ab07-71f670ff26a9)
Artifact ('@') is left on the canvas
If you try to clean canvas - artifact remains

**Expected behavior**
![image](https://github.com/epam/ketcher/assets/26869421/ff444824-fe73-4d9b-9c06-0dddf0a04d0b)

**Environment details:**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
- Indigo Toolkit Version 1.21.0-rc.3.0-g1570d3f9f-x86_64-linux-gnu-11.2.1
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/3532

**Comment by rrodionov91** [comment]
Does not reproduce

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/f0fb2b82-5bd5-4dcb-89f2-1ce616c5ac16)
- Ketcher Version 2.24.0-rc.2 Build at 2024-08-14; 19:00:14
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10
