### ISSUE TITLE
Errors in console on app load

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5053]
**Steps to Reproduce**
1. Load release version of Ketcher
2. Go to browser console

**Actual behavior**
5 Errors in console just on app load
![image](https://github.com/epam/ketcher/assets/26869421/7f5bbe47-1dc6-445a-86e7-7776ebf2cc7e)
[rc.test.lifescience.opensource.epam.com-1720558441342.log](https://github.com/user-attachments/files/16150420/rc.test.lifescience.opensource.epam.com-1720558441342.log)

**Expected behavior**
No crash

**Environment details:**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
- Indigo Toolkit Version 1.21.0-rc.3.0-g1570d3f9f-x86_64-linux-gnu-11.2.1
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

**Comment by rrodionov91** [comment]
Does not reproduce
