### ISSUE TITLE
Add and remove Multi-tail Arrow to the Canvas (Default)

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#5055]
As a **User**, I want **to add a multi-tail arrow to the canvas** with a default size so that I can quickly start building my synthesis tree.

**Acceptance Criteria:**

1. The arrow menu should include a multi-tail arrow tool.
![image](https://github.com/epam/ketcher/assets/169887211/f6979d2d-a307-434b-8f47-eac774fa062e)
2. When the user hovers over the multi-tail arrow tool, it should change color and display the text "Multi-Tail Arrow".
![image](https://github.com/epam/ketcher/assets/169887211/5b8e5baa-e12c-4123-8cda-fea41ec3df00)
3. When the user clicks (left click) the image of the arrow in the arrows menu the arrow should change color, and the arrows menu should close.
![image](https://github.com/epam/ketcher/assets/169887211/a4f7086d-80f5-45ef-855a-50f5cfb0f5aa)
4. **Updated in comments** - Selecting the multi tail arrow from the arrows menu and clicking on the canvas (Left click) should give the default size arrow (total height: 100px, total width: 46px, tail width: 14px, head width: 30px) with the default configuration (horizontal upper and lower tail (2 tails), horizontal arrow head and vertical spine).
![image](https://github.com/epam/ketcher/assets/169887211/d4b3517d-e89e-4d9a-84c2-d981f8412222)
5. The bottom left point of the arrow should be the point on the canvas that the user clicked.
6. A User should be able to switch from Micro to Macro mode and back. Multi-tail arrows shouldn’t be visible in Macro and shouldn't be lost after switching to Macro.
7. User can perform basic actions with Multi-Tail Arrows:
- User can zoom in and zoom out the canvas with multi-tail arrows, while multi-tails are displayed according to the zoom and don't change their positions;
- Multi-Tailed Arrow can be selected using selection tools: rectangle, lasso, fragment:
- Multi-Tailed Arrow can be deleted using "Erase", "Clear Canvas" (Ctrl + Del) tools and buttons - Delete and Backspace;
- User can Undo (Ctrl + Z)/Redo (Ctrl+ Shift + Z) actions (adding, movement, deletion) with Multi-Tailed Arrows;

**Comment by ivanmaslow** [comment]
The first iteration of exploratory testing is completed on nightly environment (5055-add-remove-multitail-arrow), detected points to fix:
- Name of new button should be "Multi-Tail Arrow" instead of "Multitail Arrow";
- Hover area for Multi-Tail Arrow isn't consistent (the area is bigger than for other arrows, especially near the left side of head arrow);
- Design should be updated as on mock-up (mock-up is on right side, not sure about line width - TBD):
![image](https://github.com/user-attachments/assets/b2e9380c-9199-42aa-bdde-6da05418c2f7)

**Comment by ivanmaslow** [comment]
The points above are fixed.
During the second iteration of exploratory preview testing on polymer env (5104-save-load-multitail-arrow), some inconsistency issues are detected and should be fixed - https://github.com/epam/ketcher/issues/5334

**Comment by ivanmaslow** [comment]
Points above are fixed including the defect - https://github.com/epam/ketcher/issues/5334
