### ISSUE TITLE
Add/remove a tail to a multi-tail arrow

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#5056]
As a **User**, I want to **add or remove a tail to/from a multi-tail arrow** so that I can accurately represent the number of reactants in my synthesis tree.

**Acceptance Criteria:**

1. Right-clicking on the multi-arrow element with **select or arrow tools** should open a context menu with the option to "Add tail".
![Image](https://github.com/epam/ketcher/assets/173041434/35207f20-31b2-41bf-a4ed-74d05b935f2d)

2. **If the user clicks the "Add tail" option, a new tail should be added exactly in the middle between the first two tails with the biggest distance.**
3. Right-clicking on a tail should open a context menu with the option to "Remove tail". This option should be disabled for the upper and lower tails.
![Image](https://github.com/epam/ketcher/assets/173041434/28880870-fa13-42dd-985a-bafe98018d15)

4. If the user selects the "Remove tail" option, the selected tail should be removed from the arrow.
5. History events should be supported - User can Undo (Ctrl + Z)/Redo (Ctrl+ Shift + Z) actions with tails (adding, removing);
6. Erase tool removing the whole element, not the tail.
7.  **OUT OF SCOPE** - Selection style will be implemented in a separate story - https://github.com/epam/ketcher/issues/5057
8. **OUT OF SCOPE** - The new tail must have hover and selection highlights together with the whole arrow element - https://github.com/epam/ketcher/issues/5057.

**Comment by ivanmaslow** [comment]
Exploratory testing is completed on the RC Remote environment:
- Ketcher [Version 2.25.0-rc.1] Build at 2024-09-03; 15:37:29
- Indigo Version 1.24.0-rc.1.0-gb8f099851-x86_64-linux-gnu-11.2.1
- Windows 11 Enterprise
- Chrome Version 128.0.6613.120 (Official Build) (64-bit)

The following checks were performed, and tests are updated:
- Tails can be added/removed using right-click menu for added from the KET file Multi-Tailed Arrows according to spine lengths on Canvas with/without chemical elements:
![image](https://github.com/user-attachments/assets/aa0ac3b3-a668-467d-896e-942821142315)
- Undo/Redo actions for adding/removing of tails for Multi-Tailed Arrows added by Tool or from KET file;
- Copy-Paste and Cut-Paste actions for Multi-Tailed Arrows added by Tool or from KET file after adding/removing of tails;
- Movement of Multi-Tailed Arrows added by Tool or from KET file after adding/removing of tails;

Two issues related to this feature were detected and fixed:
- https://github.com/epam/ketcher/issues/5309
- https://github.com/epam/ketcher/issues/5310
