### ISSUE TITLE
Mouse Over and Selection style for a multi-tail arrow

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#5057]
As a **User**, I want visual feedback when I **hover over a multi-tail arrow or select it** so that I can easily identify the parts of the arrow that I can interact with.

**Acceptance Criteria:**

1. When the user hovers over with select or arrow tools a multi-tail arrow, it should be highlighted.
![Image](https://github.com/user-attachments/assets/a1b5c0b1-2999-4085-8fe2-a35d62810b5a)

2. When the user clicks to any point of multi-tail arrow with select or arrow tools a multi-tail arrow, selects multi-tail arrow, it should be highlighted
![Image](https://github.com/user-attachments/assets/1bd08228-df6f-41ec-bee5-414202cbeccc)

3. When the user moves whole multi-tail arrow or makes any other operations on the multi-tail arrow, the multi-tail arrow should be selected.

**Comment by ivanmaslow** [comment]
Exploratory testing is completed on the RC Remote environment:
- Ketcher [Version 2.25.0-rc.1] Build at 2024-09-03; 15:37:29
- Indigo Version 1.24.0-rc.1.0-gb8f099851-x86_64-linux-gnu-11.2.1
- Windows 11 Enterprise
- Chrome Version 128.0.6613.120 (Official Build) (64-bit)

The following checks were performed, and tests are updated:
- Added from KET file or using Tool Multi Tailed Arrow can be selected:
![image](https://github.com/user-attachments/assets/a9c7323b-b921-4d8a-b82f-3531352f6e84)
-  Added from KET file or using Tool the whole Multi-Tailed Arrow is highlighted with a blue outline when hovering on tails  when Multi-Tailed arrow is unselected:
![image](https://github.com/user-attachments/assets/40c999ec-6651-4237-99b3-cb3d292211eb)
-  Added from KET file or using Tool the whole Multi-Tailed Arrow is highlighted with a blue outline when hovering on tails  when Multi-Tailed arrow is selected:
![image](https://github.com/user-attachments/assets/4834a9d8-fc95-47c4-84cc-d2419231b8ce)
- Added from KET or using Tool Multi-Tailed Arrow will be highlighted in green when actions are performed using "Multi-Tailed Arrow Tool", "Arrow Open Angle Tool", "Rectangle Selection", "Lasso Selection", "Fragment Selection" or any other Arrow Tool: selection, movement of arrow itself, changing of size and position of head, changing positions of top and bottom tails, changing size and positions of added tails:

https://github.com/user-attachments/assets/030cd6cc-bb18-40ac-9641-f50275f5f186


4 issues related to this feature were detected:
- https://github.com/epam/ketcher/issues/5383;
- https://github.com/epam/ketcher/issues/5389;
- https://github.com/epam/ketcher/issues/5428;
- https://github.com/epam/ketcher/issues/5468;

Also some issues not related to this feature were detected:
- https://github.com/epam/ketcher/issues/5429;
- https://github.com/epam/ketcher/issues/5422;
- https://github.com/epam/ketcher/issues/4309;
- https://github.com/epam/ketcher/issues/5439;
- https://github.com/epam/ketcher/issues/5448;
- https://github.com/epam/ketcher/issues/5476;
