### ISSUE TITLE
Move and Size Head Arrow of a multi-tail arrow

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#5058]
As a **User**, I want to **move and resize the head** of a multi-tail arrow so that I can accurately represent the product in my synthesis tree.

**Acceptance Criteria:**

1. When the user hovers over the arrow with select or arrow tools (not erase tool), the cursor should change accordingly: hover on head line - up/down arrow; hover on right point of head - left/right arrow.
![Image](https://github.com/epam/ketcher/assets/173041434/e6ae0179-be47-4d82-a3ba-f3296830f2d2)

2. When the user is hovering on the right corner of the head, clicking and dragging to the left or right changes the width of the head.
  _2.1. During and after moving, the whole arrow should be highlighted._
  2.2. Dragging to the right is not limited.
  2.3. Dragging to the left is limited to [minimum head length]
3. When the user is hovering over the line of the head (not the right corner), clicking and dragging up and down changes the position of the head.
  _3.1. During and after moving, the whole arrow should be highlighted._
  3.2. The head can be moved along the spine, with one radius of the corner curve being the limitation on both sides.
  ![image](https://github.com/epam/ketcher/assets/169887211/2e454ce6-ed43-4ab5-8ed3-1981d1cbf5df)
  3.3. Any movement above/bellow these lines results in no movement.

**Selection and hover highlighting of the whole Multi-Tailed Arrow is out of scope for this task** - it will be implemented here - https://github.com/epam/ketcher/issues/5057

**Comment by ivanmaslow** [comment]
Exploratory testing is completed on the RC Remote environment:
- Ketcher [Version 2.25.0-rc.1] Build at 2024-09-03; 15:37:29
- Indigo Version 1.24.0-rc.1.0-gb8f099851-x86_64-linux-gnu-11.2.1
- Windows 11 Enterprise
- Chrome Version 128.0.6613.120 (Official Build) (64-bit)

The following checks were performed, and tests are updated:
- The head arrow of Multi-Tailed Arrow added from KET file or added by Tool can be moved up and down, but not closer than 0.15 from top and bottom tails:
![image](https://github.com/user-attachments/assets/fe5f469b-5792-4bef-8059-119e163a7669)
- The size of head arrow of Multi-Tailed Arrow added from KET file or added by Tool can be increased to right and decreased to left (0.4 from spine):
![image](https://github.com/user-attachments/assets/46da7d84-7b30-4be5-8011-32221f1493ed)
- Checks above were performed for one/several Multi-Tailed Arrows on Canvas with/without chemical elements;
- Undo/Redo actions for moving/resizing of head arrow of Multi-Tailed Arrows added by Tool or from KET file;
- Copy-Paste and Cut-Paste actions for Multi-Tailed Arrows added by Tool or from KET file after moving/resizing of head;
Movement of Multi-Tailed Arrows added by Tool or from KET file after moving/resizing of head;
