### ISSUE TITLE
Back bone bond (R1-R2) between peptide and phosphate on different levels has no round elbows

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5060]
**Steps to Reproduce**
1. Go to Macromolecules - Flex mode
2. Load from file: [Back bone bond (R1-R2) between peptide and phosphate on different levels has no round elbows.zip](https://github.com/user-attachments/files/16157195/Back.bone.bond.R1-R2.between.peptide.and.phosphate.on.different.levels.has.no.round.elbows.zip)
3. Switch to Snake mode

**Actual behavior**
Bond between peptide and phosphate on different levels has no round elbows
![image](https://github.com/epam/ketcher/assets/26869421/5a140f21-75fc-4ee1-a274-3bbf6a840915)

**Expected behavior**
Round elbows
![image](https://github.com/epam/ketcher/assets/26869421/cead34fb-443b-4e36-854c-c3b1792173ed)

**Environment details:**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
- Indigo Toolkit Version 1.21.0-rc.3.0-g1570d3f9f-x86_64-linux-gnu-11.2.1
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/3532

**Comment by rrodionov91** [comment]
Does not reproduce

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/1226b07a-e71c-4408-a682-f7871abc4fdc)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)
