### ISSUE TITLE
Switching from Sequence mode to Snake mode and back shifts visible area of canvas beyond visible frame. Forever.

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5074]
**Steps to Reproduce**
1. Go to Macromolecules - Flex mode <---Important!
2. Load from file: 
[Switching from Sequence mode to Snake mode and back shifts visible area of canvas beyond visible frame.zip](https://github.com/user-attachments/files/16174165/Switching.from.Sequence.mode.to.Snake.mode.and.back.shifts.visible.area.of.canvas.beyond.visible.frame.zip)
![image](https://github.com/epam/ketcher/assets/26869421/86f62df1-93cd-43d8-971d-57b334c5cf68)
3. Switch view to Sequence mode
4. Switch back to Snake mode

**Actual behavior**
Canvas forever shifted to the left and down partially beyond visisbility frame
![image](https://github.com/epam/ketcher/assets/26869421/ac93bb43-a8c2-4c5d-bf35-81838791867b)

**Expected behavior**
No shifting
![image](https://github.com/epam/ketcher/assets/26869421/86f62df1-93cd-43d8-971d-57b334c5cf68)

**Environment details:**
- Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
- Indigo Toolkit Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/3532

**Comment by Zhirnoff** [comment]
Maybe this will help developers understand the cause of bug: when I pressed zoom 100%, structure was centered.

https://github.com/epam/ketcher/assets/62464241/4185e12a-2f9c-43fe-9380-5d54b3eaccfb

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/c9271ca5-82e5-4894-9cca-a9550e906387)

- Ketcher Version 2.23.0-rc.3 Build at 2024-07-14; 20:34:10
- Indigo Toolkit Version 1.22.0-rc.3.0-gbb5c51fc2-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
