### ISSUE TITLE
IDT alias is displayed outside the information window in the library after viewing on the main diagram

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5078]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type `/55HydMe-dC/`
3. Hover mouse over nucleotide to get preview tooltip on main screen
4. Go to RNA tab at library and open Nucliotides section
5. Hover mouse over these nucleotide which was passed before to get preview tooltip

**Actual behavior**
IDT alias is displayed outside the information window
![Снимок экрана 2024-07-11 в 17 49 45](https://github.com/epam/ketcher/assets/174325443/a5e7cc3b-a866-4711-869d-24aaaceca32f)

**Expected behavior**
IDT alias is displayed in the information window
![Снимок экрана 2024-07-11 в 17 52 50](https://github.com/epam/ketcher/assets/174325443/ab938be9-f128-4f6b-b5f9-23b17fe0eb14)

**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

**Comment by Zhirnoff** [comment]
![2024-08-07_11h08_08](https://github.com/user-attachments/assets/ca527dbb-ba32-4f2f-9292-b819ba9a8537)
![2024-08-07_11h08_47](https://github.com/user-attachments/assets/bab1f426-ea99-46ce-badf-8719526b602d)
![2024-08-07_11h10_24](https://github.com/user-attachments/assets/c094a3ae-3f3d-4621-bf20-e9276e4faf64)
Bug fixed. But we have another bug https://github.com/epam/ketcher/issues/5225

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
