### ISSUE TITLE
Export the structure for nucleotides 5-Bromo dU does not work correctly

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5079]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type `/55Br-dU//i5Br-dU//i5Br-dU//i5Br-dU//i5Br-dU/`
![Снимок экрана 2024-07-12 в 12 56 19](https://github.com/user-attachments/assets/d1de2c94-c0e9-4d6c-bbae-7bef853c7967) 
or create manually the following canvas:
![Снимок экрана 2024-07-12 в 12 57 00](https://github.com/user-attachments/assets/f70529e5-a3ce-45cc-a9b3-efb4a717e3d8)
3. Save canvas in the IDT format

**Actual behavior**
![Снимок экрана 2024-07-12 в 12 57 48](https://github.com/user-attachments/assets/317458eb-b1e9-40c6-9f7c-861d57bfdd41)

**Expected behavior**
Export should be `/55Br-dU//i5Br-dU//i5Br-dU//i5Br-dU//i5Br-dU/`

**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AlexeyGirin** [comment]
Moved to indigo - https://github.com/epam/Indigo/issues/2119
