### ISSUE TITLE
IDT alias for Presets is not displayed

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5087]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Open section RNA and after Presets
3. Hover mouse over preset to get preview tooltip

**Actual behavior**
IDT alias is not displayed for preset
![Снимок экрана 2024-07-12 в 15 44 46](https://github.com/user-attachments/assets/11f2d4ef-526a-44c1-a699-1bbd52659d11)

**Expected behavior**
IDT alias should be displayed for presets

**Versions:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-08-07_11h03_05](https://github.com/user-attachments/assets/360fbc97-9305-46cd-919a-fbee12163889)
![2024-08-07_11h03_16](https://github.com/user-attachments/assets/51e9d646-f430-43fd-959c-cb85f1846252)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
