### ISSUE TITLE
The “Favorites” icon overlaps unsplit nucleotide names in the RNA and Favorites tab

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5090]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Flex mode
2.	In the RNA tab in the Nucleotides subsection click on the “Favorites” icon on the unsplit nucleotides

**Actual behavior**
The “Favorites” icon overlaps unsplit nucleotide names, because the name comes in two lines

<img width="108" alt="image" src="https://github.com/user-attachments/assets/b045eec0-674a-4b23-bd3e-cd18eefcc00d">

<img width="113" alt="image" src="https://github.com/user-attachments/assets/03685773-bcb2-441b-96a4-369a27da8afb">

**Expected behavior**
The “Favorites” icon does not overlap unsplit nucleotide names

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (126.0.6478.127) x64

**Ketcher version** 2.23.0-rc.2, Build at 2024-07-10; 19:45:41

Issue found while testing https://github.com/epam/ketcher/issues/4382

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/33cf0f3d-b121-4adc-8df9-ac1d150b67f2)

- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)
