### ISSUE TITLE
Selection frame is displayed improperly for overlapped images

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5097]
**Steps to Reproduce**
1. Click on "Add Image"
2. Select the image and add the first image to the canvas
3. Click on "Add Image" again and add the second image to canvas to overlap the first image
4. Select the second image

**Actual behavior**
The second image is on the top layer, but only part of the selection frame (or mouse over frame) is displayed
![image](https://github.com/user-attachments/assets/6b6814c0-0c36-43de-b204-8f1d145120b0)
![image](https://github.com/user-attachments/assets/3cf482ed-d42b-4173-8575-39ae32c2e7e3)

**Expected behavior**
The second image is on the top layer and the selection frame (or mouse over frame) is fully displayed 

**Desktop:**
 - OS: Windows 11 Enterprise
 - Browser: Chrome 126.0.6478.127 (Official Build) (64-bit)

**Ketcher version**: Nightly 4902 [Version 2.23.0-rc.1] Build at 2024-07-12; 10:06:35. 

**Additional Context:**
- It also looks not proper when image and element are intersected:
![image](https://github.com/user-attachments/assets/47c7cb4b-1e37-46e3-b9b6-0a983918e8ff)
- Found during preview testing of https://github.com/epam/ketcher/issues/4897

**Comment by ivanmaslow** [comment]
Discussed with DM - no plans to fix in 2.24.0-rc.1, added to Refined Backlog

**Comment by AlexeyGirin** [comment]
Verified.
![Uploading image.png…]()
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
