### ISSUE TITLE
Move and Size Tails of a multi-tail arrow

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#5107]
As a **User**, I want to **move and resize the tails** of a multi-tail arrow so that I can accurately represent the reactants in my synthesis tree.

**Acceptance Criteria:**

1. When the user is hovering on the left corner of one of the tails, clicking and dragging to the left or right changes the widths of all tails.
  1.1. During and after moving, the whole arrow should be highlighted/selected.
  1.2. Dragging to the left is not limited.
  1.3. Dragging to the right is limited to [minimum tail length>=radius of the corner curve]
2. When the user is hovering over the center of a tail (not the left corner), clicking and dragging up and down changes the position of the tail, and (if applicable) changes the length of the spine and the corner curvature.
  2.1. During and after moving, the whole arrow should be highlighted.
  2.2. Behaviour for the upper tail is covered bellow.
    2.2.1. The upper tail can be moved up with no limitation.
        2.2.1.1. The spine is adjusted accordingly.
    2.2.2. The upper tail can be moved down until one radius of the corner curve above the head or another tail 
(whichever comes first).
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/2f490acd-4345-4efa-a530-b99db9a260c3)
        2.2.2.1. The spine is adjusted accordingly.
        2.2.2.2. Any dragging bellow this point results in no movement.
    2.3. The behavior for the lower tail is identical to the behavior for the upper tail, just with reversed directions.
    2.4. The middle tail(s) can be moved anywhere along the spine with a radius of the corner curve as the limitation on both sides.
      2.4.1. If the user drags the tail closer than one radius of the corner curve to another tail, after releasing the cursor, the tail position is automatically adjusted to the closest position to where the user dragged the tail, that is at least one radius of the corner curve away form other tails.
(Image for better understanding)
![image](https://github.com/epam/ketcher/assets/169887211/d360f95d-f5e7-49a4-8a18-4bc2028b3ce8)

3. Pointer must represent possible actions.
![Image](https://github.com/user-attachments/assets/81e67aa2-abce-4d23-848b-1605f47f7988)

![Image](https://github.com/user-attachments/assets/400bb9f4-b456-4dbd-991b-553a440c2429)

Selection and hover highlighting of the whole Multi-Tailed Arrow is **out of scope** for this task - it will be implemented here - https://github.com/epam/ketcher/issues/5057

**Comment by ivanmaslow** [comment]
During exploratory preview testing on the nightly environment (5107-move-size-head-tails) some issues are found, need to be fixed:
- Can't remove middle tail;
- Can move tail to any place on spine if selection tool is used;

**Comment by ivanmaslow** [comment]
Points above are fixed and verified on Nightly environment (5057-hover-selection):
- Middle tail can be removed:
![image](https://github.com/user-attachments/assets/8a159d0c-aca6-4cd7-818a-12f4560d86a7)
- Tails can be moved when the selection tool is used:
![image](https://github.com/user-attachments/assets/2fdb3a5a-f19c-4871-860c-19d0e98599cc)
- When moving down the top tail, it stops 0.15 before head:
![image](https://github.com/user-attachments/assets/07b97eb5-0e28-47db-a540-b689dc8caa12)
- Issues for cases when there are no free spaces for moving tail related to rounding - fixed, no errors are in console;
- Tail can be put to 0.35 before the bottom tail:
![image](https://github.com/user-attachments/assets/3615eabd-7868-4c1a-bea6-710bf4015fdd)
- Console issue when image is added to Canvas - fixed, no error are in console;
