### ISSUE TITLE
Change structure of monomers

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5111]
## Peptides

- [x] D-Pyroglutamic acid
- [x] alpha-methyl-L-phenylalanine
- [x] 3-phenyllactic acid
- [x] 2-hydroxyacetic acid
- [x] (2S)-6-amino-2-hydroxyhexanoic acid

| Symbol | Name | Structure | Leaving group (attachment atom-leaving group atom) |
| --- | --- | --- | --- |
| D-Pyr | D-Pyroglutamic acid | [D-Pyroglutamic acid.zip](https://github.com/user-attachments/files/16675433/D-Pyroglutamic.acid.zip) | R1=H (0-9), R2=OH (6-8) |
| aMePhe | alpha-methyl-L-phenylalanine | [Alpha-methyl-L-phenylalanine.zip](https://github.com/user-attachments/files/16675453/Alpha-methyl-L-phenylalanine.zip) | R1=H (0-5), R2=OH (2-3) |
| PhLA | 3-phenyllactic acid | [3-phenyllactic acid.zip](https://github.com/user-attachments/files/16675498/3-phenyllactic.acid.zip) | R2=OH (8-9) |
| DAGlyO | 2-hydroxyacetic acid | [2-hydroxyacetic acid.zip](https://github.com/user-attachments/files/16675522/2-hydroxyacetic.acid.zip) | R1=H (4-5), R2=OH (1-2) |
| DALys | (2S)-6-amino-2-hydroxyhexanoic acid (old name: 6-amino-2-hydroxyhexanoic acid) | [6-amino-2-hydroxyhexanoic acid.zip](https://github.com/user-attachments/files/16675559/6-amino-2-hydroxyhexanoic.acid.zip) | R1=H (0-11), R2=OH (2-3), R3=H (9-10) |

## Nucleotides

- [x] 5-Nitroindole
- [x] 5-Bromo-deoxyridine
- [x] 5-hydroxybutynl-2’-deoxyuridine
- [x] Amino Modifier C6 dT
- [x] 8-aza-7-deazaguanosine
- [x] Hydroxymethyl dC
- [x] 2,6-Diaminopurine

| Symbol | Name | Structure | Leaving group (attachment atom-leaving group atom) |
| --- | --- | --- | --- |
| 5NitInd | 5-Nitroindole | [5-Nitroindole.zip](https://github.com/user-attachments/files/16674816/5-Nitroindole.zip) | R1=H (18-19), R2=OH (21-22) |
| 5-Bromo dU (new symbol: 5Br-dU) | 5-Bromo-deoxyridine | [5-Bromo-deoxyridine.zip](https://github.com/user-attachments/files/16674841/5-Bromo-deoxyridine.zip) | R1=H (7-8), R2=OH (10-11) |
| Super T | 5-hydroxybutynl-2’-deoxyuridine | [5-hydroxybutynl-2-deoxyuridine.zip](https://github.com/user-attachments/files/16674935/5-hydroxybutynl-2-deoxyuridine.zip) | R1=H (7-8), R2=OH (10-11) |
| AmMC6T | Amino Modifier C6 dT | [Amino Modifier C6 dT.zip](https://github.com/user-attachments/files/16675026/Amino.Modifier.C6.dT.zip) | R1=H (7-8), R2=OH (10-11), R3=H (32-34), R4=H (32-33) |
| Super G | 8-aza-7-deazaguanosine | [8-aza-7-deazaguanosine.zip](https://github.com/user-attachments/files/16675155/8-aza-7-deazaguanosine.zip) | R1=H (7-8), R2=OH (10-11) |
| 5HydMe-dC (new symbol: 5hMedC) | Hydroxymethyl dC | [Hydroxymethyl dC.zip](https://github.com/user-attachments/files/16675271/Hydroxymethyl.dC.zip) | R1=H (6-7), R2=OH (9-10) |
| 2-Amino-dA (new symbol: 2-damdA) | 2,6-Diaminopurine | [2,6-Diaminopurine.zip](https://github.com/user-attachments/files/16675337/2.6-Diaminopurine.zip) | R1=H (6-7), R2=OH (9-10) |

## Phosphates

- [x] Phosphorodiamidate 
- [x] Phosphothioate 

| Symbol | Name | Structure | Leaving group (attachment atom-leaving group atom) |
| --- | --- | --- | --- |
| m2np | Phosphorodiamidate | [Phosphorodiamidate.zip](https://github.com/user-attachments/files/16942921/Phosphorodiamidate.zip) | R1=OH (0-1), R2=NH2 (0-2) |
| sP | Phosphothioate | [Phosphothioate.zip](https://github.com/user-attachments/files/16941050/Phosphothioate.zip) | R1=OH (1-0), R2=OH (1-4) |

## Bases

- [x] 3-Methyluracil
- [x] N7-methylguanine

| Symbol | Name | Structure | Leaving group (attachment atom-leaving group atom) |
| --- | --- | --- | --- |
| m3U | 3-Methyluracil | [3-Methyluracil.zip](https://github.com/user-attachments/files/17174149/3-Methyluracil.zip) | R1=H (3-6) |
| m7G | N7-methylguanine (old name: 7-Methylguanine) | [N7-methylguanine.zip](https://github.com/user-attachments/files/17174252/N7-methylguanine.zip) | R1=H (6-12) |

## Sugars

- [x] 5-(R)-Methyl-(R)-cEt BNA
- [x] 5-(R)-Methyl-(S)-cEt BNA
- [x] 5-(S)-Methyl-(R)-cEt BNA
- [x] 5-(S)-Methyl-(S)-cEt BNA

| Symbol | Name | Structure | Leaving group (attachment atom-leaving group atom) |
| --- | --- | --- | --- |
| 5R6Rm5 | 5-(R)-Methyl-(R)-cEt BNA | [5-(R)-Methyl-(R)-cEt BNA.zip](https://github.com/user-attachments/files/17201394/5-.R.-Methyl-.R.-cEt.BNA.zip) | R1=H (6-8), R2=H (10-11), R3=OH (1-9) |
| 5R6Sm5 | 5-(R)-Methyl-(S)-cEt BNA | [5-(R)-Methyl-(S)-cEt BNA.zip](https://github.com/user-attachments/files/17201412/5-.R.-Methyl-.S.-cEt.BNA.zip) | R1=H (6-8), R2=H (10-11), R3=OH (1-9) |
| 5S6Rm5 | 5-(S)-Methyl-(R)-cEt BNA | [5-(S)-Methyl-(R)-cEt BNA.zip](https://github.com/user-attachments/files/17201421/5-.S.-Methyl-.R.-cEt.BNA.zip) | R1=H (6-8), R2=H (10-11), R3=OH (1-9) |
| 5S6Sm5 | 5-(S)-Methyl-(S)-cEt BNA | [5-(S)-Methyl-(S)-cEt BNA.zip](https://github.com/user-attachments/files/17201443/5-.S.-Methyl-.S.-cEt.BNA.zip) | R1=H (6-8), R2=H (10-11), R3=OH (1-9) |

**Comment by AlexeyGirin** [comment]
Verified.

- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10
