### ISSUE TITLE
Loaded images change level layers after Undo/Redo

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5118]
**Steps to Reproduce**
1. Load images from .ket file and add to Canvas: 
[images-png-svg.zip](https://github.com/user-attachments/files/16459171/images-png-svg.zip)
![image](https://github.com/user-attachments/assets/14139169-bcc5-4101-8731-6b65beaa7f67)
2. Click on Undo - loaded images disappear
3. Click on Redo

**Actual behavior**
Layer levels of Images are reversed
![image](https://github.com/user-attachments/assets/01173f72-d796-4875-855a-9246ff707350)

**Expected behavior**
Layer levels of Images are the initial
![image](https://github.com/user-attachments/assets/14139169-bcc5-4101-8731-6b65beaa7f67)

**Desktop:**
- OS: Windows 11 Enterprise
- Browser: Chrome 126.0.6478.127 (Official Build) (64-bit)

**Ketcher version** [2.23.0-rc.1 Build at 2024-07-16; 10:35:24] - nightly: 4902-image-selection-and-movement

**Additional Context:**
- Issue can be also reproduced using 'Add Image":
1. Add two images with overlapping - the second is on top layer
2. Delete the first one
3. Delete the second one
4. Make redo to see the both images - the first is on top layer (the second should be on top layer)
- Detected during preview testing of https://github.com/epam/ketcher/issues/4911

**Comment by ivanmaslow** [comment]
Discussed with DM - added to Refined Backlog

**Comment by yauhen-karmyzau** [comment]
This issue requires huge changes in canvas items rendering and can affect other functionality. Project backlog already has a feature to change rendering engine and this defect will be fixed in scope of such refactoring.
