### ISSUE TITLE
The error appears in the Console, when connecting two unsplit nucleotides in Snake mode

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5126]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Snake mode
2.	Open the Console
3.	Open any structure on the canvas, for example, this [long nucleotides 4R.zip](https://github.com/user-attachments/files/16266765/long.nucleotides.4R.zip)
4.	Draw two unsplit nucleotides on the canvas and connect them

**Actual behavior**
The error appears in the Console: Uncaught TypeError: Cannot read properties of undefined (reading 'length')

<img width="351" alt="image" src="https://github.com/user-attachments/assets/517ddaa9-1d6e-4cd8-a584-bc9b094e33e6">

[rc.test.lifescience.opensource.epam.com-1721224527187.log](https://github.com/user-attachments/files/16266791/rc.test.lifescience.opensource.epam.com-1721224527187.log)

**Expected behavior**
There are no errors in the Console

**Screenshots**

https://github.com/user-attachments/assets/d58652cc-0fed-4252-90a9-b5eed15beb13

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (126.0.6478.127) x64

**Ketcher version** 2.23.0-rc.3, Build at 2024-07-14; 20:34:10

Issue found while testing https://github.com/epam/ketcher/issues/4382

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/d59151f2-b180-46c8-8212-ca85dc9389d2)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)
