### ISSUE TITLE
Refactor: Split logic of `PolymerBondRenderer` by several classes

### ISSUE THREAD

**Issue by DmitriiP-EPAM** [epam/ketcher#5128]
# Problem

`PolymerBondRenderer` class is responsible for three responsibilities:
- <s>Sequence mode</s>
- Flex mode
- Snake mode

or more because it handles:
- backbone chain connections
- side chain connections
- UPD: RNABase and Sugar

# Solution

Create several classes and split logic.

**Comment by AlexeyGirin** [comment]
Verified after conversation

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10
