### ISSUE TITLE
It should be impossible to add attachment point(s) to an atom with R-Group Label and vice versa

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#513]
_Description:_ It's possible now to add attachment point(s) to an atom with R-Group Label and vice versa.

_Steps to reproduce:_
1. Launch Ketcher.
2. Create a structure (e.g. chain).
3. With R-Group Label Tool add any R-Group label to any atom.
4. With Attachment Point Tool add attachment points to the same atom.

Expected result: It's not possible to add attachment point(s) to an atom with R-Group Label.
Actual result: Attachment points are added.
![image](https://user-images.githubusercontent.com/80695128/118126917-a4ee9c00-b401-11eb-8a81-350695c4e8f3.png)

The issue was discussed with @AlexanderSavelyev

**Comment by AllaZhbanova** [comment]
Fixed, tested v. 2.4
