### ISSUE TITLE
In the Snake mode, the structure in the HELM format does not open via Paste from clipboard

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5132]
**Steps to Reproduce**
1.	Switch to the Macro mode (Remote mode) – the Snake mode
2.	Open the Console
3.	Load via the Paste from clipboard, selecting HELM type: PEPTIDE1{C.[Apm].D.[dC].E}|PEPTIDE2{F.[D-gGlu].G.[D-Orn].I}$PEPTIDE1,PEPTIDE2,2:R3-2:R3|PEPTIDE2,PEPTIDE1,4:R3-4:R3$$$V2.0
4.	Click on the “Add to Canvas” button 

**Actual behavior**
The error appears on the canvas and in the Console: POST https://rc.test.lifescience.opensource.epam.com/v2/indigo/convert 400 (Bad Request)
The structure in the HELM format does not open. It is reproduced only in the Remote mode, in the Standalone mode this structure opens  

<img width="950" alt="image" src="https://github.com/user-attachments/assets/aea169d5-e5dc-40d4-8118-ee0f829f6f3e">

<img width="202" alt="image" src="https://github.com/user-attachments/assets/71c334c0-017a-4a09-89f8-00f759e20135">

[rc.test.lifescience.opensource.epam.com-1721302089851.log](https://github.com/user-attachments/files/16284722/rc.test.lifescience.opensource.epam.com-1721302089851.log)

**Expected behavior**
There are no errors on the canvas and in the Console. The structure in the HELM format opens in the Remote mode

**Screenshots**

https://github.com/user-attachments/assets/17144d5e-ac8b-4a27-86b9-93174aafa77e

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (126.0.6478.127) x64

**Ketcher version** 2.23.0-rc.3, Build at 2024-07-14; 20:40:06

Issue found while testing https://github.com/epam/ketcher/issues/4977

**Comment by AlexeyGirin** [comment]
Not repro at
Ketcher Version 2.24.0-rc.3 Build at 2024-08-20; 13:16:59
Indigo Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0

**Comment by ViktoriaTkacheva** [comment]
The bug is reproduced with a new error, which appears after clicking the "Close" button: 
Blocked aria-hidden on a <button> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. <button class=​"MuiButtonBase-root e1oaegu30 ejign8b1 css-i5kpl3" tabindex=​"0" type=​"button" title=​"Structure will be loaded as fragment and added to Clipboard" role=​"button" data-testid=​"add-to-canvas-button">​…​</button>​flex

<img width="343" alt="image" src="https://github.com/user-attachments/assets/e9c4175f-2db5-491f-a53a-e8eaac0817d7">

[localhost-1724424078470.log](https://github.com/user-attachments/files/16730305/localhost-1724424078470.log)

https://github.com/user-attachments/assets/3dfd00a7-d4b5-4008-a9c0-0264b4299ff5

**Comment by rrodionov91** [comment]
@ViktoriaTkacheva please create separate ticket for new issue
