### ISSUE TITLE
Starting new sequence by typing in sequence mode

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5136]
**Background**
Currently, if the user is in "view only" mode in sequence mode and types something on the keyboard, nothing happens.
To make starting a new sequence for the user easier, the ability to enter "text editing" mode via typing from keyboard should be added.

**Requirements**
1. If the canvas is empty (there are no sequences on the canvas), and the user types an appropriate symbol from the keyboard that should result in adding the monomer represented by that symbol as the first (and only) monomer in the sequence, turning on "text edit" mode and placing of the caret after the first monomer. (same logic for requirement 5 from issue [#4878](https://github.com/epam/ketcher/issues/4878)).
2. If RNA is selected as a type of sequence,
![image](https://github.com/user-attachments/assets/61306914-07ab-4f1d-a618-f7797cba38b6)
appropriate symbols are: A, C, G, U, T
3. If DNA is selected as a type of sequence, appropriate symbols are: A, C, G, U, T
4. If Peptide is selected as a type of sequence, appropriate symbols are: A, C, D, E, F, G, H, I, K, L, M, N, P, Q, R, S, T, V, W, Y

Monomers that are represented by appropriate letters are covered by [#1426](https://github.com/epam/Indigo/issues/1426)

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-31; 05:31:01
- Indigo Toolkit Version 1.23.0-dev.2.1-gd93b8ec4-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/5627937c-756e-473c-b20e-8d8706fa9fcb)
- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
