### ISSUE TITLE
Image changes the layer to top after scaling actions

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5148]
**Steps to Reproduce:**
1. Click on "Add Image"
2. Select the image and add the first image to the canvas
3. Click on "Add Image" again and add the second image to canvas to overlap the first image - the second image is on top layer
![image](https://github.com/user-attachments/assets/843e493b-0296-4424-9bb5-8cb4632e23b3)
4. Select the first image and change the scale

**Actual behavior:**
The first image is displayed on the top layer:
![image](https://github.com/user-attachments/assets/8abaaa4a-f378-4148-a247-b3218a61ad25)

**Expected behavior**
- The first image is displayed on the bottom layer, scaling doesn't change the image layer

**Desktop (please complete the following information):**
- OS: Windows 11 Enterprise
- Browser: Chrome 126.0.6478.128 (Official Build) (64-bit)

**Ketcher version:**
- [Version 2.23.0-rc.1] Build at 2024-07-18; 15:00:20 - nightly env SA 20images-lowest-render-z

**Additional context**
- Found during preview testing for https://github.com/epam/ketcher/issues/4897;
- If user saves to .ket file and loads from .ket file this change of layer will be lost, the first image should be on top if we decide to support changes of layers on scaling and other actions:
![image](https://github.com/user-attachments/assets/f314ae1c-1973-4e47-87fa-ad55cd1b2ac1)
- Recording is attached: 

https://github.com/user-attachments/assets/1e53511b-8a7c-4c27-90bb-b5164d20091c

**Comment by ivanmaslow** [comment]
Discussed with DM: It would be nice to consider possible ability of changing z-order

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/a20d2059-c8f2-4f55-be65-fae656ec9688)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
