### ISSUE TITLE
Add new settings for ACS style

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5152]
**Background**

To fully comply with the ACS style, certain settings need to be added: 

**Bond length** - length of one bond and the length of the default arrows (related issue: [#5153](https://github.com/epam/ketcher/issues/5153));

**Margin size** - upon clicking layout, reactants, products, and other reaction elements get arranged in a grid with the height of a tallest element, and all others arranged in the middle; this margin defines the margins in that grid;
![image](https://github.com/user-attachments/assets/de04c0e5-6933-4a31-806d-a196d6f8ce6f)

**Hash spacing** - the distance between lines of a Single Down Bond (only applies to this bond);
![image](https://github.com/user-attachments/assets/69684f62-bf70-49e2-9b46-ff96046db2c0)

**Image resolution** - low/high (Related issue: [#5140](https://github.com/epam/Indigo/issues/2175)); low being the current low resolution (72ppi) and high being a resolution preferred by ACS (600ppi).

**Requrements**
1. New setting - "Bond  length" - should be added to "Bonds" section in settings. 
1.1. The setting should be placed above "Double bond width" (or after changing "Bond spacing", related issue [#5154 ](https://github.com/epam/ketcher/issues/5154)), and bellow "Aromatic Bonds as circle".
1.2. Similarly to other setting, the user should be able to choose values in cm/pt/px/in with up to 1 decimal places.
1.3. The current default size for bond length should be determined.
1.4 Should be applied after clicking on layout
1.5 Add to JSON of the Setting file:
`bondLengthUnit: "px"`
`bondLength: 2.1`

2. New setting - "Reaction component margin size" - should be added to "General" section in settings.
1.2. The setting should be placed bellow "Sub font size".
2.2. Similarly to other setting, the user should be able to choose values in cm/pt/px/in with up to 1 decimal places.
2.3.  The current default size for bond length should be determined.
2.4 Should be applied after clicking on layout
2.5 Add to JSON of the Setting file:
`reactionComponentMarginSizeUnit: "px"`
`reactionComponentMarginSize: 2.3`

3. New setting - "Hash spacing" - should be added to "Bonds" section in settings.
3.1. The setting should be placed bellow the "Stereo (Wedge) bond width".
3.2. Similarly to other setting, the user should be able to choose values in cm/pt/px/in with up to 1 decimal places.
3.3. The current default size for bond length should be determined.
3.4 Add to JSON of the Setting file:
`hashSpacingUnit: "px"`
`hashSpacing: 2.2`

4. New setting "Image resolution" - should be added to "General" section in settings.
4.1. The setting should be placed bellow "Reaction component margin size".
4.2. This setting is read-only (user not able to choose a value)
4.3 Displays only the values of 72 or 600 with the unit being ppi and high or low
4.4. The current resolution is 72ppi.
4.5 Add to JSON of the Setting file:
`imageResolution: 72`
to Indigo should send only number, not high or low as parameter

**Comment by accmeboot** [comment]
3

**Comment by accmeboot** [comment]
Default values:

bondLength: 40
hashSpacing: 1.2
reactionComponentMarginSize: 20 // half of the bondLength

**Comment by AlexeyGirin** [comment]
[ACS-StyleGuide.pdf](https://github.com/user-attachments/files/16849103/ACS-StyleGuide.pdf)

**Comment by AnnaKosol** [comment]
Verified
default values, entering values with up to 1 decimal places, applying in the Canvas - it will be implemented by others tasks.
![Image](https://github.com/user-attachments/assets/43c5ac59-2b2c-464d-b8a5-9a9bc09233c1)

**Environment details:**
Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
