### ISSUE TITLE
Change the default size of a plus and the arrows

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5153]
**Background**
To better comply with ACS standard, default sizes of plus and arrows should be changed. 
The preferred values are not explicitly stated in any ACS style guides, but from examples it can be inferred that the default arrow size is supposed to be the length of a single bond and that the default plus size should be significantly smaller.

**Solution**
1. Change default sizes of all arrows to be equal to the size on one bond (related issue: [#5152](https://github.com/epam/ketcher/issues/5152))
The length of the arrows are still able to be changed by the user, only the default size if different.
2. Change the default plus size to better reflect ACS style guide examples:
![image](https://github.com/user-attachments/assets/363b910c-bca8-44d3-95a7-dd4c35f4eb66)

**Comment by AnnaKosol** [comment]
Verified on https://nightly.test.lifescience.opensource.epam.com/KetcherDemoSA/5153-change-the-default-size-of-a-plus-and-the-arrows/index.html
**Environment:**
Ketcher Version 2.25.0-rc.2 Build at 2024-09-27; 09:11:38
Indigo Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
MacOs 15.0
Chrome Version 129.0.6668.71 (Official Build) (arm64)

![Image](https://github.com/user-attachments/assets/4b511f79-abaa-42c1-a3b5-9ac247e387fc)
![Image](https://github.com/user-attachments/assets/86c68c61-2ef8-4806-a49a-6c358979fa76)

**Comment by AnnaKosol** [comment]
Verified - the default size of arrows is 1 bond
![Image](https://github.com/user-attachments/assets/7db40340-04a3-430a-bcfa-49cddfd4ea00)

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
