### ISSUE TITLE
Change "Double bond width" setting

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5154]
**Background**
Currently the setting "Double bond width" is similar to others (user can choose cm/px/pt/in):
![image](https://github.com/user-attachments/assets/123f6b94-e898-41d9-bc20-d1b7e3284bd8)

**Requirements**
1. To better reflect ACS style the setting should be renamed to "Bond spacing", because it impacts not only the double bond.
2. The user shouldn't be able to choose  cm/px/pt/in but a percentage of the bond length -
added here: [5152](https://github.com/orgs/epam/projects/28/views/7?sliceBy%5Bvalue%5D=epam%2Fketcher&pane=issue&itemId=72186890)
ACS standard:
![image](https://github.com/user-attachments/assets/1563afab-e6db-4951-9ff1-64761834fdef)
3. Current value as a percentage of bond width should be determined.

field in the Setting should be `bondSpacing`

**UX**
![Image](https://github.com/user-attachments/assets/4dd45f3e-3c30-439d-9a9d-79d8beb51d0c)

**Comment by accmeboot** [comment]
The default bond length is 40 so the bondSpacing should be the half of it (15%).
