### ISSUE TITLE
Bond properties change when auto-mapping is applied 

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#516]
_Affected versions:_ remote, standalone
Tested on Ketcher v2.2.1-104-gc7896113

_Steps to reproduce:_

1. Launch Ketcher.
2. Open the reaction 
[reaction_3.zip](https://github.com/epam/ketcher/files/6491694/reaction_3.zip)
4. Select the 'Reaction Auto-mapping Tool'.
5. Select any mode except 'Clear'.
6. Click the 'OK' button
7. Select the 'Reaction Auto-mapping Tool' again.
8. Select another mode except 'Clear'.
9. Click the 'OK' button.

_Expected result:_ 
9. Auto-mapping is applied. The mapping of atoms may change after selecting different modes.

_Actual result:_
9. Bond properties have been changed, "made/broken" and "order changes" reacting centers appear.
![2021-05-17_10h01_35](https://user-images.githubusercontent.com/80695128/118445295-ed0a0900-b6f6-11eb-94a5-276bcb4bc736.gif)

**Comment by AlexanderSavelyev** [comment]
it is not a bug. AAM will use existing atom mapping and due to existing mapping the modes are different (clear, keep, alter)

**Comment by ElenaOdnoshivkina** [comment]
This is behaviour is correct (approved by @AlexanderSavelyev )
