### ISSUE TITLE
Change symbols of monomers (Peptides and CHEMs)

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5166]
Change the symbols of following peptides and CHEMs in the library (name, (new name), old symbol-> new symbol):

- [x] beta-Alanine, Bal -> bAla
- [x] 3-naphthylalanine, 3-(2-naphthyl)-alanine, Nal -> 2Nal
- [x] SelenoCysteine, Selenocysteine, seC -> U
- [x] D-SelenoCysteine, D-selenocysteine, dSec -> dU
- [x] Aspartic acid (OH), Aspartic acid*, AspOH -> D*
- [x] (2S)-2-amino-4-(2-aminophenyl)-4-oxobutanoic acid, Kynurenine, AspOh2 -> Kyn
- [x] gamma-glutamic acid, Ggu -> gGlu
- [x] Deamino-Phenylalanine, 3-phenyllactic acid, DAPhe -> PhLA
- [x] sarcosine (N-methylglycine), Sarcosine, Sar -> meG
- [x] DPyl, D-pyrrolysine, dPyl -> dO
- [x] 5-hydroxylysine, Hyl -> Hyl5xi
- [x] Pyl, Pyrrolysine, Pyl -> O
- [x] epsilon-N-trimethyllysine, Tml -> LysMe3
- [x] 3-methylvaline, L-tert-leucine, Tle -> tLeu
- [x] 	N-Terminal Acetic Acid, N-Terminal acetyl, ac -> Ac-
- [x] C-Terminal amine, C-Terminal amino, am -> Am-
- [x] Tert-butyloxycarbonyl, N-Terminal tert-butyloxycarbonyl, Boc -> Boc-
- [x] butanoic acid, N-Terminal butanoyl, Bua -> Bua-
- [x] Benzaldehyde, N-Terminal benzoyl, Bz -> Bz-
- [x] Carboxybenzyl, N-Terminal carboxybenzyl, Cbz -> Cbz-
- [x] 2,3-diaminopropanoic acid, 3-aminoalanine, Dpr -> Dap
- [x] fmoc N-Terminal Protection Group, N-Terminal fluorenylmethoxycarbonyl, fmoc -> fmoc-
- [x] lactic acid, Lac -> L-OAla
- [x] Mesylate, N-Terminal methanesulfonyl, MsO ->MsO-
- [x] Ethaneamine, C-Terminal ethylamino, NHEt -> -NHEt
- [x] C-Termial NMe, C-Terminal methylamino, NMe -> -NMe
- [x] C-Terminal OBz, C-Terminal benzyloxy , OBz -> -OBn
- [x] Ethanol, C-terminal ethoxy, OEt -> -OEt
- [x] C-Terminal OMe, C-Terminal methoxy, OMe -> -OMe
- [x] C-Terminal OtBu, C-Terminal tert-butoxy, OtBu -> -OtBu
- [x] Phenyl, C-terminal phenyl, Ph -> -Ph
- [x] 1-amino-1-carboxycyclopentane, Cycloleucine, Spg -> Ar5c
- [x] Tosyl, N-Terminal tosyl, Tos -> Tos-

**Comment by AlexeyGirin** [comment]
No test cases needed for that particular case
