### ISSUE TITLE
Change natural analogue of monomers Peptides and CHEMs)

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5167]
Change the natural analogue of following peptides and CHEMs in the library (name, (new name), old natural analogue -> newnatural analogue):

- [x] SelenoCysteine, Selenocysteine, C -> U
- [x] D-SelenoCysteine, D-selenocysteine, C -> U
- [x] (2S)-2-amino-4-(2-aminophenyl)-4-oxobutanoic acid, Kynurenine, D -> W
- [x] DPyl, D-pyrrolysine, K -> O
- [x] Pyl, Pyrrolysine, K -> O
- [x] 3-methylvaline, L-tert-leucine, V -> L
- [x] 3-(2-pyridyl)-alanine, X -> A
- [x] 3-(4-Pyridyl)-alanine, X -> A
- [x] 2-aminoadipic acid, L-2-aminoadipic acid, X -> K
- [x] 2-aminobutanoic acid, L-2-aminobutyric acid, X -> A
- [x] 2-carboxyazetidine, L-azetidine-2-carboxylic acid, X -> P
- [x] (2S)-2-amino-3-{[1,1'-biphenyl]-4-yl}propanoic acid, Biphenylalanine, X -> F
- [x] (2S)-2-amino-3-(4-benzoylphenyl)propanoic acid, 4-benzoylphenylalanine, X -> F
- [x] Alpha-cyclohexylglycine, X -> G
- [x] citrullin, Citrulline, X -> R
- [x] D-3-(2-Pyridyl)-alanine, X -> A
- [x] D-3-(2-pyridyl)-alanine, D-3-(3-pyridyl)-alanine, X -> A
- [x] D-2-aminobutanoic acid, X -> A
- [x] D-Alpha-cyclohexylglycine, X -> G
- [x] D-Citrullin, D-citrulline, X -> R
- [x] D-2,3-diaminopropanoic acid, 3-amino-D-alanine, X -> S
- [x] (4S)-1,3-thiazolidine-4-carboxylic acid, D-thioproline, X -> P
- [x] D-isovaline, X -> V
- [x] diaminopimelic acid, X -> K
- [x] 2,3-diaminopropanoic acid, 3-aminoalanine, X -> S
- [x] lactic acid, X -> A
- [x] 3-(methylamino)propanoic acid, X -> A
- [x] 1-amino-1-carboxycyclopentane, Cycloleucine, X -> L
- [x] (4R)-1,3-thiazolidine-4-carboxylic acid, L-thioproline, X -> P

**Comment by AlexeyGirin** [comment]
No test cases needed it that particular case
