### ISSUE TITLE
Preview: Update Image object in KET file to support CDX/CDXML format

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/ketcher#5172]
"type": "image",
"format": "image MIME type",
"boundingBox": {
    "x": x, "y": y, // left top
    "z": z,           // optional z
    "width": WIDTH,
    "height": HEIGHT
},
"data": "base64-encoded-string"

[images.zip](https://github.com/user-attachments/files/16437564/images.zip)

**Comment by ivanmaslow** [comment]
Preview exploratory testing is completed on env with 5172-update-ket-image branch:
- Ketcher version: [Version 2.23.0-rc.3] Build at 2024-08-01; 08:58:34
- Indigo version: Version 1.23.0-dev.4.0-gb71e441d7-wasm32-wasm-clang-19.0.0
Points below are covered:
- Json structure for images in .ket file was changed (example for .svg):

{
    "root": {
        "nodes": [
            {
                "type": "image",
                "format": "image/svg+xml",
                "boundingBox": {
                    "x": 18.424999999999997,
                    "y": -9.774999999999997,
                    "z": 0,
                    "width": 4.900000000000002,
                    "height": 4.775000000000006
                },
                "data": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IS0tIFVwbG9hZGVkIHRvOiBTVkcgUmVwbywgd3d3LnN2Z3JlcG8uY29tLCBHZW5lcmF0b3I6IFNWRyBSZXBvIE1peGVyIFRvb2xzIC0tPg0KPHN2ZyB3aWR0aD0iODAwcHgiIGhlaWdodD0iODAwcHgiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4NCjxwYXRoIGQ9Ik0zIDEzLjY0OTNDMyAxNi42MDQ0IDUuNDE3NjYgMTkgOC40IDE5TDE2LjUgMTlDMTguOTg1MyAxOSAyMSAxNi45ODM5IDIxIDE0LjQ5NjlDMjEgMTIuNjUwMyAxOS44ODkzIDEwLjk0NDkgMTguMyAxMC4yNUMxOC4xMzE3IDcuMzIyNTEgMTUuNjg0IDUgMTIuNjg5MyA1QzEwLjM1MTQgNSA4LjM0Njk0IDYuNDg2MzcgNy41IDguNUM0LjggOC45Mzc1IDMgMTEuMjAwMSAzIDEzLjY0OTNaIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIi8+DQo8L3N2Zz4="
            }
        ],
        "connections": [],
        "templates": []
    }
}
- All scope of checks from previous tasks were retested successfully:
https://github.com/epam/ketcher/issues/4911
https://github.com/epam/ketcher/issues/4897

**Comment by Zhirnoff** [comment]
Tested.

![2024-08-09_11h46_19](https://github.com/user-attachments/assets/c15c4937-f21b-4454-9120-94e17328efe6)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
