### ISSUE TITLE
Preview: Undo/Redo actions don't work for last deleted image (SVG or PNG) after Undo its deletion

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#5174]
**Steps to Reproduce:**
1. Refresh the page;
2. Add images on canvas (PNG or SVG) Image files: 
[image-png.zip](https://github.com/user-attachments/files/16390082/image-png.zip)
[image-svg.zip](https://github.com/user-attachments/files/16390083/image-svg.zip)
3. Move image to another place
4. Delete image using erase
5. Undo action - Deleting is canceled, image is on Canvas
6. Make Undo again (or Redo) 

**Actual behavior:**
- In case of Undo - Movement action from step 2 isn't canceled and image is still displayed on the place
- In case of Redo - Deleting isn't repeated and image is still displayed 

**Expected behavior:**
- In case of Undo - Movement action from step 2 is canceled and image is changed position accordingly 
- In case of Redo - Deleting is repeated and image isn't displayed

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version:** 
- [Version 2.23.0-rc.3]

**Indigo version:** 
- [Version 1.22.0-rc.3]

**Additional Details:**
- Found during testing of https://github.com/epam/ketcher/issues/4897
- Recording is attached for the case of Undo and one Image: 

https://github.com/user-attachments/assets/20ad67cb-410e-435e-813a-847fdefc32f9

- The issue is like that delete "resets" history of Undo/Redo of the last deleted image, you can see it on recording for two images - Undo/Redo doesn't work only for the last deleted image:

https://github.com/user-attachments/assets/9c7beaeb-2a0b-4a47-9eca-b8a9ed820827

- Example of issue for two images and Redo:

https://github.com/user-attachments/assets/edf7c678-a465-4c5d-87d0-e568b51e1e40

**Comment by ivanmaslow** [comment]
The fix is verified on env with 5172-update-ket-image branch.
- Ketcher version: [Version 2.23.0-rc.3] Build at 2024-08-01; 08:58:34
- Indigo version: Version 1.23.0-dev.4.0-gb71e441d7-wasm32-wasm-clang-19.0.0
It works as expected for all cases above.
Undo/Redo actions work for the last deleted image (SVG or PNG) after Undo its deletion.

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/d56f0641-f58e-4a37-9d77-e00c35fc0f7d


https://github.com/user-attachments/assets/7a7e67b8-0d7c-42d8-a6e0-5dbece603edc

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
