### ISSUE TITLE
Add ambiguous monomers to the library and allow their addition to the canvas

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5186]
**Background**
In addition to importing/exporting ambiguous monomers and supporting them on the canvas, some standard ambiguous monomers should be added to the library and the users should be able to add them to the canvas form the library.

**Requirements**
1. In the peptides section of the library a new subsection should be added with the title "Ambiguous Amino Acids"
1.1. The subsection should be placed on the bottom of all the other subsections (bellow tyrosine).
1.2. The ambiguous monomers from the table bellow should be be added.
1.3. The first monomer is `X`, and the others are arranged alphabetically.
1.4. Class of these monomers is "AminoAcid"
1.5. These monomers are "Alternatives".

| Symbol | Monomers that make up the ambiguous monomer| 
| --- | --- | 
| **B** | **D** (aspartic acid), **N** (asparagine) |
| **J** | **L** (leucine), **I** (isoleucine) |
| **Z** | **E** (glutamic acid), **Q** (glutamine) |
| **X** | **Any Amino Acid**, **A** (Alanine), **C** (cysteine), **D** (aspartic acid), **E** (glutamic acid), **F** (phenylalanine), **G** (glycine), **H** (histidine), **I** (isoleucine), **K** (lysine), **L** (leucine), **M** (methionine), **N** (asparagine), **O** (pyrrolysine), **P** (proline), **Q** (glutamine), **R** (arginine), **S** (serine), **T** (threonine), **U** (selenocysteine), **V** (valine), **W** (tryptophan), **Y** (tyrosine) |

2. In the bases section of the library (under RNA tab) a new subsections should be added with the title "Ambiguous Bases", "Ambiguous DNA Bases" and "Ambiguous RNA Bases" (in that order).
2.1. The subsections should be placed on the bottom of all the other subsections (bellow bases with natural analogue X).
2.2. The ambiguous monomers from the table bellow should be be added to appropriate sections (DNA bases to "Ambiguous DNA Bases", RNA bases to "Ambiguous RNA Bases", and Both bases to "Ambiguous Bases").
2.3. The first monomer in RNA and DNA sections is `N`, every other monomer should be arranged alphabetically.
2.4. Class of these monomers is "Base"
2.5. These monomers are "Alternatives".

| Symbol | Monomers that make up the ambiguous | DNA/RNA/Both |
| --- | --- | --- |
| **R** | **A** (adenine), **G** (guanine) | Both |
| **Y** | **C** (cytosine), **T** (thymine) | DNA |
| **Y** | **C** (cytosine), **U** (uracil) | RNA |
| **S** | **G** (guanine), **C** (cytosine) | Both |
| **W** | **A** (adenine), **T** (thymine) | DNA |
| **W** | **A** (adenine), **U** (uracil) | RNA |
| **K** | **G** (guanine), **T** (thymine) | DNA |
| **K** | **G** (guanine), **U** (uracil) | RNA |
| **M** | **A** (adenine), **C** (cytosine) | Both |
| **B** | **C** (cytosine), **G** (guanine), **T** (thymine) | DNA |
| **B** | **C** (cytosine), **G** (guanine), **U** (uracil) | RNA |
| **D** | **A** (adenine), **G** (guanine), **T** (thymine) | DNA |
| **D** | **A** (adenine), **G** (guanine), **U** (uracil) | RNA |
| **H** | **A** (adenine), **C** (cytosine), **T** (thymine) | DNA |
| **H** | **A** (adenine), **C** (cytosine), **U** (uracil) | RNA |
| **V** | **A** (adenine), **C** (cytosine), **G** (guanine) | Both |
| **N** | **Any base**, **A** (adenine), **C** (cytosine), **G** (guanine), **T** (thymine) | DNA |
| **N** | **Any base**, **A** (adenine), **C** (cytosine), **G** (guanine), **U** (uracil) | RNA |

3. The user should be able to add the ambiguous monomers to the canvas just like all other monomers in the library, and preform all canvas operations (Related issue: [#4554](https://github.com/epam/ketcher/issues/4554))

**UX**
![355820472-b11d6e03-148e-460e-a3d2-9918f1988c4e](https://github.com/user-attachments/assets/e5167ec8-4c86-4cfe-be94-9cc69827fa03)

**Comment by Zhirnoff** [comment]
Tested.
![2024-09-06_11h24_11](https://github.com/user-attachments/assets/8dd446ec-62a0-4076-8f02-2a4cc302d3a1)
![2024-09-06_11h24_41](https://github.com/user-attachments/assets/ace2bc4f-2a4b-480c-a3e1-58baf6225660)
![2024-09-06_11h25_29](https://github.com/user-attachments/assets/efa676f4-d009-4165-8d02-a098d5be2247)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
