### ISSUE TITLE
Introduce new amino-acid colours

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5187]
**Background**

The logic of the current colour scheme for amino acids is not as good as it can be. The colours should be changed, for them to be more intuitive and useful to the user.

The chosen logic for amino acid colouring is the colours of litmus paper - where acidic solutions colour the paper red, basic ones colour the paper blue and neutral ones colour the paper purple. Green and yellow are chosen to be colours for non-polar amino acids because they will be different enough visualy from red, purple and blue.

**Requirements**

1. All **polar, acidic** amino acids (**two AAs:** aspartic acid (D) and glutamic acid (E) and all amino acids with the same natural analogue) should be represented by **shades of red**.
2. All **polar, basic** amino acids (**four AAs:** lysine (K), arginine (R), histidine (H), pyrrolysine (O) and all amino acids with the same natural analogue) should be represented by **shades of blue**.
3. All **polar, neutral** amino acids (**seven AAs:** serine (S), threonine (T), cysteine (C), tyrosine (Y), asparagine (N), glutamine (Q), selenocysteine (U) and all amino acids with the same natural analogue) should be represented by **shades of purple**.
4. All **non-polar** amino acids (**nine AAs:** glycine (G), alanine (A), valine (V), leucine (L), isoleucine (I), methionine (M), tryptophan (W), phenylalanine (F), proline (P) and all amino acids with the same natural analogue) should be represented by **shades of green and yellow**.
5. Amino acids with the natural analogue X should stay the same colour (grey).

**UX**
![image](https://github.com/user-attachments/assets/4c5a370d-34eb-4ef4-a567-a088e139c919)

**Comment by AlexeyGirin** [comment]
Test cases are not needed for that issues
