### ISSUE TITLE
[EPIC] Bond tool 

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#519]
PART 1
Add support for hydrogen and dative bonds.

A separate block for new types of bonds is added to the 'Bond' tool menu. In full screen format a button for new types of bonds appears on the Tools palette. 

1. User can draw a hydrogen bond:
![image](https://user-images.githubusercontent.com/80695128/119514974-22a99480-bd7e-11eb-953f-e25ed0a9022c.png)
- New item appears in the bonds menu. 
![image](https://user-images.githubusercontent.com/80695128/118479944-4cc5db80-b71a-11eb-9221-2251b698e2ac.png)

- It is drawn the same way as the other types of bonds:
To draw a hydrogen bond - click the Hydrogen Bond tool, and drag at the desired angle.
To sprout a hydrogen bond - click the Hydrogen Bond tool, click an atom.
To change a bond to a hydrogen bond - click a bond with the Hydrogen Bond tool.
To change atom or bond properties - select an atom or bond and double-click.
To change bond length - select an atom and drag it at the desired length.

- The type of the bond in molfile is 10.
http://help.accelrysonline.com/ulm/onelab/1.0/content/ulm_pdfs/direct/reference/ctfileformats2016.pdf

- No other verification is performed for the bond type.

2. User can draw a dative bond:
![image](https://user-images.githubusercontent.com/80695128/119515047-335a0a80-bd7e-11eb-95f3-5d185b8e9cd1.png)

- New item appears in the bonds menu.
![image](https://user-images.githubusercontent.com/80695128/118480297-b7771700-b71a-11eb-826f-ac75af95332f.png)

- It is drawn the same way as the other types of bonds:
To draw a dative bond - click the Dative Bond tool, and drag at the desired angle.
To sprout a dative bond - click the Dative Bond tool, click an atom.
To change a bond to a dative bond - click a bond with the Dative Bond tool.
To change atom or bond properties - select an atom or bond and double-click.
To change bond length - select an atom and drag it at the desired length.

- Dative bond has a direction from first point to the second point (e.g. CH4->NH3). Arrow changes the direction when clicked.
![image](https://user-images.githubusercontent.com/80695128/118480337-c4940600-b71a-11eb-8781-4b6e4fc4173f.png)

- The type of the bond in molfile is 9.

- No other verification is performed for the bond type.

PART 2 
Save and open the structures with dative/hydrogen bonds.

1. User can save the structures with dative/hydrogen bonds in MDL Molfile V2000, MDL Molfile V3000, CML and ket formats.

**Comment by AndreiMazol** [comment]
@Svetlana-Asinovskaia  please update PART 2: all supported formats should be listed.
