### ISSUE TITLE
Include indigo without render module into ketcher-standalone build process

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#5190]
**Background**
Indigo implemented additional module without render part. It should be included in ketcher-standalone package.

**Solution**
Adjust ketcher-standalone build process to include indigo without render. Similar changes was introduced in https://github.com/epam/ketcher/issues/2654 for indigo with separated wasm file.
Provide an ability to load ketcher with indigo without render module, and then load full indigo in background.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/f053ed18-ab78-4d2d-a08d-53830cc96cd2)

- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
