### ISSUE TITLE
Preview: An error appears in the Console when opening any section in the RNA tab

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5196]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Flex or Snake mode
2.	Open the Console
3.	In the RNA tab open any section

**Actual behavior**
An error appears in the Console: Uncaught TypeError: Cannot read properties of null (reading 'phosphate') 

<img width="242" alt="image" src="https://github.com/user-attachments/assets/9300ea9f-e897-412a-a53a-69da0ca6f74d">

<img width="958" alt="image" src="https://github.com/user-attachments/assets/76f0456a-9fd4-40be-829a-35831370ceea">

<img width="692" alt="image" src="https://github.com/user-attachments/assets/6abc01bc-a9a1-44a0-9383-5cffb62c5216">

[localhost-1722429061712.log](https://github.com/user-attachments/files/16443809/localhost-1722429061712.log)

**Expected behavior**
There are no errors in the Console

**Screenshots**

https://github.com/user-attachments/assets/dafb9a84-47c6-4b92-96f8-4c06b0e38bba

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (127.0.6533.74) x64

**Ketcher version** 2.23.0-rc.3, Build at 2024-07-30; 14:02:09

**Indigo version** 1.22.0-rc.3

Issue found while testing https://github.com/epam/ketcher/issues/4888

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 127.0.6533.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.2]
**Indigo version** 
[Version 1.23.0-rc.2]
