### ISSUE TITLE
The user's choice is not saved in the settings, but is recalculated in px

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5200]
**Steps to Reproduce**
1. Go to the Settings
2. Choose pt in the dropdown
![Снимок экрана 2024-08-01 в 11 09 21](https://github.com/user-attachments/assets/daa4587e-3a04-41b4-8968-373eced18b89)
3. Click on Apply button
4. Open the Settings again

**Actual behavior**
The parameters that we edited are specified in px.
![Снимок экрана 2024-08-01 в 11 15 57](https://github.com/user-attachments/assets/dd968bd2-bd40-4d77-9cb9-f2de51707443)

**Expected behavior**
The parameters that we edited are recalculated and indicated as we entered
![Снимок экрана 2024-08-01 в 11 09 21](https://github.com/user-attachments/assets/daa4587e-3a04-41b4-8968-373eced18b89)

****
Need to add new fields to the JSON for the Settings
`"fontszUnit": "px"`
`"fontszsubUnit": "px"`
`"bondThicknessUnit": "px"`
`"stereoBondWidthUnit": "px"`

 
**Environment details:**
Ketcher Version 2.23.0-rc.3 Build at 2024-07-14; 20:34:10
Indigo Version 1.22.0-rc.3.0-gbb5c51fc2-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

**Comment by split-ends** [comment]
Successfully tested using different combinations of units: pt, cm, inch, px,


![Image](https://github.com/user-attachments/assets/8378928f-aed0-4fef-9f5f-f55c6f85a358)


**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-04; 09:15:28
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
Windows 11 Enterprise
