### ISSUE TITLE
"Select/Edit Connection Points" dialogues for ambiguous monomers

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5224]
**Background**
Ambiguous monomers will have the functionality of any other monomer on canvas, thus "Select Connection Points" and "Edit Connection Points" dialogues will need to be opened sometimes. 
Because ambiguous monomers do not have a structure as such, a new UX for these dialogues is needed.

**Requirements**
1. If an ambiguous monomer has a type, instead of a monomer name there should be "Ambiguous  [type]"
> All monomers that make up the ambiguous monomer are amino acids -> The ambiguous monomer is an amino acid -> The "name" should be "Ambiguous Amino Acid"

2. If a ambiguous monomer has no type, instead of a monomer name there should be "Ambiguous Monomer"
> Ambiguous monomer is made up from one amino acid and one CHEM -> The ambiguous monomer has no type -> The "name" should be "Ambiguous Monomer"

| Type | Text instead of monomer name |
| --- | --- | 
| CHEM | Ambiguous CHEM |
| Sugar | Ambiguous Sugar |
| Base | Ambiguous Base |
| Phosphate | Ambiguous Phosphate |
| Nucleotide | Ambiguous Nucleotide |
| Amino acid | Ambiguous Amino Acid |
| None | Ambiguous Monomer |

3. A ambiguous monomer has an attachments point Rn only of all the monomers have attachment point Rn (as described in related issue [#4554](https://github.com/epam/ketcher/issues/4554)).
3.1. If all monomers that make up the ambiguous monomer have the same atom as a leaving group for the attachment point Rn, then those atoms should be displayed bellow the Rn button.
3.2. If at least one monomer that makes up the ambiguous monomer has a different atom as a leaving group for the attachment point Rn, the space bellow the Rn button should be empty.

4. Instead of the structure, the representation of that ambiguous monomer on canvas should be shown (see mockups).

5. All the other functionality of "Select Connection Points" and "Edit Connection Points" dialogues remains unchanged.

**UX**
![image](https://github.com/user-attachments/assets/1f050888-dbb7-444a-8e2d-a70e2820a90d)

**Comment by AlexeyGirin** [comment]
Test cases added

**Comment by Zhirnoff** [comment]
Tested.
![2024-09-09_17h26_17](https://github.com/user-attachments/assets/33ee1e1c-7069-40d3-8b7e-987da26da7f2)
![2024-09-09_17h26_40](https://github.com/user-attachments/assets/85a435e9-e334-40b1-ba13-0c4433cb0a3d)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
