### ISSUE TITLE
Canvas should remain in edit mode if we insert monomer from the library

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5231]
**Steps to Reproduce**
1. Go to Macromolecules mode - Sequence mode
2. Go to the Library - Peptide tab
3. Click on `A` peptide

**Actual behavior**
System adds `A` peptide and switches canvas to view mode
![image](https://github.com/user-attachments/assets/70f43570-a0a8-4977-9478-399d58a263c2)

**Expected behavior**
1. System adds `A` peptide and canvas remains in edit mode
![image](https://github.com/user-attachments/assets/56a0f024-3656-49c8-b03b-572d625c6785)
As per [requirement](https://github.com/epam/ketcher/issues/4878): 

> .....2.3. If the sequence is empty, and the user clicks on the monomer in the library, no checks are performed, and the monomer is added as the only monomer in the sequence (and canvas remains in edit mode).

2. Cursor should be places at the end of added symbol
As per [requirement](https://github.com/epam/ketcher/issues/4878): 

> 5. If the canvas is empty, and the "view only" mode is active, clicking on a monomer is the library adds a monomer as the first (and only) monomer in a first sequence and turns on "text edit mode" placing the caret after the new monomer (similar to requirement 2.3.)

**Versions**
- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)

Related issue - https://github.com/epam/ketcher/issues/4878

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/1f1d39f7-678d-4e6a-93bc-6ea750c3f580



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
