### ISSUE TITLE
Vertical/Horizontal flip hot keys don't work correctly

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#524]
Tested on Ketcher v2.2.1-104-gc7896113

_Steps to reproduce:_

1. Launch Ketcher.
2. Open the structure from file 
[struct.zip](https://github.com/epam/ketcher/files/6509959/struct.zip)
4. Click the 'Horizontal Flip' button.
5. Click 'Alt+H' hot key.

_Expected result:_ It's possible to make the horizontal flip using the 'Alt+H' hot key.

_Actual result:_ The structure is not flipped with the 'Alt+H' hot key.
![2021-05-19_18h32_05](https://user-images.githubusercontent.com/80695128/118841210-c8698900-b8d0-11eb-8ece-d7afea80d780.gif)

The issue is reproduced with 'Vertical Flip' tool.

**Comment by AleksandrPokrovskii** [comment]
In the course of the work, there were problems associated with the architecture. The task is suspended until the architecture is updated
