### ISSUE TITLE
Replacement of peptide at the end of sequence on preset w/out base works wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5245]
**Steps to Reproduce**
1. Go to Macromolecules mode - Sequence mode
2. Load from file: [Replacement of peptide at the end on preset w_out phosphate works wrong.zip](https://github.com/user-attachments/files/16540632/Replacement.of.peptide.at.the.end.on.preset.w_out.phosphate.works.wrong.zip)
![image](https://github.com/user-attachments/assets/4602e91a-d65a-4284-89cd-2a9f2606def2)
3. Create custom preset without base and name it "No base"
![image](https://github.com/user-attachments/assets/63484765-aed0-4319-84d5-728f689887ff)
4. Select last monomer (in view mode)
![image](https://github.com/user-attachments/assets/fcde6c65-3c5c-447a-911f-fc37a9223737)
5. Click on "No base" preset in the library

**Actual behavior**
"Confirm Your Actions" dialog appears
![image](https://github.com/user-attachments/assets/d3fd9d22-ab73-4685-8736-ed22d272b0d7)
Click YES
System removes last peptide from the sequence
![image](https://github.com/user-attachments/assets/087351d9-4d24-4643-8fcb-69dbc0959829)

**Expected behavior**
No dialog appears
System replace `A` peptide with `@` symbol
![image](https://github.com/user-attachments/assets/c8fe1a52-1281-4b37-a217-12c891b67b7d)

As per [requirement](https://github.com/epam/ketcher/issues/4878): 

> 4. If the user selects any number of monomers in view mode, and clicks on the monomer card in the library, all selected monomer on the canvas are replaced by chosen monomer from the library each

**Versions**
- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)

Related issue - https://github.com/epam/ketcher/issues/4878

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/user-attachments/assets/df868c37-14d2-4049-a84f-845538508e47


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 127.0.6533.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.2]
**Indigo version** 
[Version 1.23.0-rc.2]
