### ISSUE TITLE
Add amino acids to the library

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5264]
| Name | Symbol | Natural analogue | Structure | Leaving group (attachment atom-leaving group atom) |
| --- | --- | --- | --- | --- |
| N-Methyl-Pyrrolysine | meO | O | [N-Methyl-Pyrrolysine.zip](https://github.com/user-attachments/files/16561286/N-Methyl-Pyrrolysine.zip) | R1=H (0-4), R2=OH (2-3) |
| N-Methyl-Proline | meP | P | [N-Methyl-Proline.zip](https://github.com/user-attachments/files/16561462/N-Methyl-Proline.zip) | R2=OH (0-1) |
| N-Methyl-Selenocysteine | meU | U | [N-Methyl-Selenocysteine.zip](https://github.com/user-attachments/files/16624454/N-Methyl-Selenocysteine.zip) | R1=H (0-4), R2=OH (2-3), R3=H (8-9) |

**Comment by Zhirnoff** [comment]
I noticed that the N-Methyl-Proline has been added to the amino acids library, but it seems that the leaving group is assigned to R1. However, based on the ticket, should the leaving group actually be R2.
![2024-08-27_18h16_26](https://github.com/user-attachments/assets/aa2cf503-ea66-4e4b-85cf-a03a6349f481)
![2024-08-27_18h17_26](https://github.com/user-attachments/assets/b8383918-2390-430f-9936-3f7570181fe0)

**Comment by KristinaKasyanovskaya** [comment]
> I noticed that the N-Methyl-Proline has been added to the amino acids library, but it seems that the leaving group is assigned to R1. However, based on the ticket, the leaving group should actually be R2. ![2024-08-27_18h16_26](https://private-user-images.githubusercontent.com/62464241/361892884-aa2cf503-ea66-4e4b-85cf-a03a6349f481.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTMyMjYsIm5iZiI6MTcyNDkxMjkyNiwicGF0aCI6Ii82MjQ2NDI0MS8zNjE4OTI4ODQtYWEyY2Y1MDMtZWE2Ni00ZTRiLTg1Y2YtYTAzYTYzNDlmNDgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA2Mjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZTY2NjFjYTk5MzYwNDRiMWRlMjRkNjJlMTE0MDhkNGEyMmFlODBkZGEzZTdlZWU4YmMwOTFjMDZiMjFkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7fEkLzlDhXthKjblyIEktBvU7ELLWLaANhaHw9dKgOU) ![2024-08-27_18h17_26](https://private-user-images.githubusercontent.com/62464241/361892890-b8383918-2390-430f-9936-3f7570181fe0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTMyMjYsIm5iZiI6MTcyNDkxMjkyNiwicGF0aCI6Ii82MjQ2NDI0MS8zNjE4OTI4OTAtYjgzODM5MTgtMjM5MC00MzBmLTk5MzYtM2Y3NTcwMTgxZmUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA2Mjg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OGI5NmI1NDllMGQwMDg4ZTUyMjZiY2M5MmE4MjdlOGM5MGRmZmU4YzdhNzFmOWU3MmI4ZDdkOGNkOTljM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfhnTn_yy36S19x_aZsBQ3TWJ8HdketqWXrtkmQMCzI)

Fixed => https://github.com/epam/ketcher/pull/5385
