### ISSUE TITLE
Warning should not displayed for importing CDXML, base64 CDX, CDX formats

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5270]
**Steps to Reproduce**
1. Open ketcher
2. Add the reaction with retrosynthetic arrow from file 
[easy reaction with etrosynthetic arrow.ket.zip](https://github.com/user-attachments/files/16559245/easy.reaction.with.etrosynthetic.arrow.ket.zip)
or create manually
<img width="339" alt="Снимок экрана 2024-08-09 в 11 33 30" src="https://github.com/user-attachments/assets/40fdf7c5-c787-463d-b6d7-9640b4a97479">

3. Open the window for saving in CDXML (or base64 CDX, CDX) format

**Actual behavior**
Warning is displayed
<img width="441" alt="Снимок экрана 2024-08-09 в 11 25 20" src="https://github.com/user-attachments/assets/e1167edb-566c-4737-bfb6-e87630a80112">

**Expected behavior**
Warning should not displayed

**Environment details:**
Ketcher Version 2.23.0-rc.3 Build at 2024-08-08; 13:17:49
Indigo Version 1.24.0-dev.1.0-g5561a82a1-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

Issue found while testing https://github.com/epam/ketcher/issues/4985

**Comment by AlexeyGirin** [comment]
Verified.
![Image](https://github.com/user-attachments/assets/db0966f2-eb92-44a9-847e-ba1cc559d26f)
- Ketcher Version 3.0.0-rc.1 Build at 2025-01-28; 05:37:00
- Indigo Version 1.29.0-dev.2.0-g4960b8ef-wasm32-wasm-clang-19.0.0
- Chrome Version 132.0.6834.111 (Official Build) (64-bit)
- Win10
