### ISSUE TITLE
Attempt to insert inpropper monomer from the library to the sequence causes wrong error

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5300]
**Steps to Reproduce**
1. Go to Macromolecules mode - Sequence mode
2. Go to the Library - Peptide tab
3. Click on `A` peptide twice to put two `A`s on the canvas
![image](https://github.com/user-attachments/assets/2ec50731-900b-400c-b1b0-a47d2fed194b)
4. Click on `DACys` peptide (C section, it has no R1 connection point)

**Actual behavior**
System shows error message: `It is impossible to merge fragments. Attachment point to establish bonds are not available.`
![image](https://github.com/user-attachments/assets/f34fa1ae-8914-44dd-9da4-b83d49fb87f6)

**Expected behavior**
Error message text should be `The monomer lacks R1 connection point and cannot be inserted at current position`
![image](https://github.com/user-attachments/assets/13ffdb1b-932d-4e85-b545-964415eb75fa)

As per [requirement](https://github.com/epam/ketcher/issues/4878): 

> 3. Error message text should be `The monomer lacks R1 connection point and cannot be inserted at current position`

**Versions**
- Ketcher Version 2.24.0-rc.2 Build at 2024-08-14; 19:00:14
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10

Related issue - https://github.com/epam/ketcher/issues/4878

**Comment by svvald** [comment]
Error message fixed when inserting a new monomer into sequence. For replacing the existing monomer the different approach is used hence the default error message is remained. Agreed with @AlexeyGirin to close for now and create a follow-up ticket for this specific case

**Comment by AlexeyGirin** [comment]
Partially fixed for adding monomer case, for replacement mode - follow up bug created: https://github.com/epam/ketcher/issues/5331
![image](https://github.com/user-attachments/assets/f9e99ec4-bfbe-4e38-a4aa-2bd39fb07b2b)
- Ketcher Version 2.24.0-rc.3 Build at 2024-08-20; 13:16:59
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10
