### ISSUE TITLE
Preview: When user copies any element on Canvas and Multi-Tail arrow is on Canvas, Multi-Tail arrow is copied too

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5308]
**Steps to Reproduce**
1. Add a multi-tail arrow on the canvas
2. Add any other element
3. Select and copy element from step 2
![image](https://github.com/user-attachments/assets/c8e56d74-ebb3-42e6-8461-1246a26c3079)
4. Paste to Canvas

**Actual behavior**
Multi-tail and element are copied:
![image](https://github.com/user-attachments/assets/a6d72fb1-b409-41fd-955c-0ac9340e001b)

**Expected behavior**
Only element is copied
![image](https://github.com/user-attachments/assets/25b8db6d-34e9-4b1f-9638-19b8eca8dd88)

**Environment details:**
- Nightly environment /5104-save-load-multitail-arrow/ 
- OS: Windows 11 Enterprise
- Browser: Chrome, Version 127.0.6533.120 (Official Build) (64-bit)

**Additional context**
- Defect is detected during exploratory testing of https://github.com/epam/ketcher/issues/5104

**Comment by ivanmaslow** [comment]
The issue is fixed and verified on nightly environment (5057-hover-selection) - only the selected element is copied.

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/user-attachments/assets/36b09c0e-4020-4937-9a8f-d55ac475b5ad




**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
