### ISSUE TITLE
Preview: Undo action using Ctrl+Z doesn't work after adding/removing tail

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5310]
**Steps to Reproduce**
1. Add multi-tail arrow
2. Add any element
3. Add a tail to multi-tail arrow
![image](https://github.com/user-attachments/assets/5233834c-0ed8-41de-91f9-84077b023b4a)
4. Click Ctrl+Z

**Actual behavior**
- Can't undo actions by Ctrl + Z buttons

**Expected behavior**
- The tail is removed on the first undo by Ctrl + Z, the element is removed on the second redo and etc.

**Environment Details**
- Nightly environment /5104-save-load-multitail-arrow/
- OS: Windows 11 Enterprise
- Browser: Chrome, Version 127.0.6533.120 (Official Build) (64-bit)

**Additional context**
- Undo button works correctly, the issue is only with keyboard Ctrl + Z
- The issue is detected during exploratory testing of https://github.com/epam/ketcher/issues/5056

**Comment by split-ends** [comment]
Successfully verified; Undo/Redo actions work fine.
![2024-09-06_10h57_23](https://github.com/user-attachments/assets/9ebcc474-884e-4197-94ff-918bbfb5a197)


**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
Windows 11 Enterprise
