### ISSUE TITLE
Preview: Can't delete the first multi-tail arrow if the first is added as a new project and second by any another option

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5311]
**Steps to Reproduce**
1. Open .ket file with a multi-tail arrow in Notepad and copy .ket Json:
[two-tail-arrow.zip](https://github.com/user-attachments/files/16639058/two-tail-arrow.zip)
2. Click on Open... in the Ketcher
3. Click on PASTE FROM CLIPBOARD
4. Paste copied Json to Open Structure
5. Click "Open as a New Project" - the first multi-tail arrow is added to the center of Canvas
6. Paste copied Json to Canvas to add the second multi-tail arrow (you can add it by button on left toolbar or open from file)
![image](https://github.com/user-attachments/assets/c766c908-fcd7-4523-bb68-0429974106c2)
7. Select both multi-tail arrows using the selection tool and click on Erase (or Delete) or click on Clear Canvas

**Actual behavior**
Only the second arrow is deleted. The first arrow which is opened as a New Project isn't deleted
![image](https://github.com/user-attachments/assets/01d1220e-5617-47e7-ac25-a7596d05fa97)

**Expected behavior**
Both arrows are deleted

**Environment Details**
- Nightly environment /5104-save-load-multitail-arrow/
- OS: Windows 11 Enterprise
- Browser: Chrome, Version 127.0.6533.120 (Official Build) (64-bit)

**Additional context**
- Issue is detected during exploratory testing of https://github.com/epam/ketcher/issues/4898

**Comment by ivanmaslow** [comment]
The issue is fixed and verified on nightly environment (5057-hover-selection) - both arrows can be deleted.

**Comment by split-ends** [comment]
Successfully verified, both arrows can be deleted.

**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-04; 09:15:28
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
