### ISSUE TITLE
Creation preset without phosphate causes R3less sugars disabled in the library FOREVER

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5313]
**Steps to Reproduce**
1. Go to Macromolecules mode - Sequence mode
2. Go to Library and click New preset
3. Go to Sugars section and click any sugar (R - in my cases)
4. Go to Bases section and click any base (A - in my case)
5. Click Add to Presets button
6. Open Sugars section

**Actual behavior**
Sugars without R3 are disabled
![image](https://github.com/user-attachments/assets/a45f4ede-9549-40e5-8354-ecf576bb3cb9)

**Expected behavior**
All sugars are enabled.
![image](https://github.com/user-attachments/assets/075520ef-7957-4a4e-b17d-f395e7121302)

**Versions**
- Ketcher Version 2.24.0-rc.2 Build at 2024-08-14; 19:06:32
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-x86_64-linux-gnu-11.2.1
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10

Related issue - https://github.com/epam/ketcher/issues/4878

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-09-16_15h53_29](https://github.com/user-attachments/assets/32d25b78-803b-4da2-a44e-f0751bf85ee6)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.2]
**Indigo version** 
[Version 1.24.0-rc.2]
