### ISSUE TITLE
Some side chain bonds are not shown in Sequence mode for bases, CHEMs, phosphates and sugars

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5317]
NOTE: Same problem with CHEMs, phosphates and sugars

**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from file: [two sequences of bases (nC6n5U).zip](https://github.com/user-attachments/files/16670267/two.sequences.of.bases.nC6n5U.zip)
![image](https://github.com/user-attachments/assets/aa12f7f8-24fa-4375-b136-bb9ab44c75a6)
3. Switch to Sequence mode

**Actual behavior**
Some side chain bonds are not shown
![image](https://github.com/user-attachments/assets/71f58a43-2e72-4b2c-b460-cb45e02fe789)

**Expected behavior**
All bonds are shown
![image](https://github.com/user-attachments/assets/d3271a36-6d7b-4500-b099-a5e2373489a2)

**Versions**
- Ketcher Version 2.24.0-rc.2 Build at 2024-08-14; 19:06:32
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-x86_64-linux-gnu-11.2.1
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10

Related issue - https://github.com/epam/ketcher/issues/4878

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2025-01-06_14h25_45](https://github.com/user-attachments/assets/483830ab-e756-4eef-b176-ac66ea085ebf)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
