### ISSUE TITLE
Change names of monomers

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5323]
## Peptides

- [x] 3-(3-pyridyl)-alanine
- [x] D-3-(2-naphthyl)-alanine
- [x] N-methyl-beta-alanine
- [x] (2S)-6-amino-2-hydroxyhexanoic acid
- [x] alpha-methyl-tyrosine
- [x] D-Lactic acid [#5195](https://github.com/epam/ketcher/issues/5195)

| Symbol | Old name | New name |
| --- | --- | --- |
| 3Pal | 3-(2-pyridyl)-alanine | 3-(3-pyridyl)-alanine |
| D-2Nal | D-3-(2-naphtyl)-alanine | D-3-(2-naphthyl)-alanine |
| NMebAl | 3-(methylamino)propanoic acid | N-methyl-beta-alanine |
| DALys | 6-amino-2-hydroxyhexanoic acid | (2S)-6-amino-2-hydroxyhexanoic acid |
| aMeTyr | L-metyrosine | alpha-methyl-tyrosine |
| D-OAla | D-lactic acid | D-Lactic acid | 

## Phosphates

- [x] N1,N1-dimethylethane-1,2-diamine
- [x] Hydroxymethylphosphonic acid
- [x] Methylphosphonothioic acid
- [x] Dihydrogen phosphate
- [x] Dihydrogen phosphorothioate
- [x] Ethylenediamine
- [x] Oxy

| Symbol | Old name | New name |
| --- | --- | --- |
| m2nen | (Dimethylaminoethyl)amino | N1,N1-dimethylethane-1,2-diamine |
| mepo2 | Methylenephosphonate | Hydroxymethylphosphonic acid |
| msp | Methylthiophosphonate | Methylphosphonothioic acid |
| P- (old symbol: naP) | Sodium Phospate | Dihydrogen phosphate |
| sP- (old symbol: nasP) | Sodium Phosphothiotate | Dihydrogen phosphorothioate |
| nen | (Aminoethyl)amino | Ethylenediamine |
| oxy | Oxy (ether) | Oxy | 

## Bases

- [x] 6-Mercaptopurine
- [x] (E)-5-(2-bromovinyl)uracil
- [x] 2-hydroxypyrimidine
- [x] 5-DBCO-U
- [x] 5-[(methylamino)methyl]uracil
- [x] 5-Thiazoleuracil
- [x] 6,7-dihydro-1H-cyclopenta[d]pyrimidine-2,4(3H,5H)-dione
- [x] tetrahydro-4-hydroxy-1H-pyrimidin-2-one
- [x] (4R)-tetrahydro-4-hydroxy-1H-pyrimidin-2-one
- [x] N1-methyl-pseudouracil
- [x] 4-Cyanoethylthiothymine
- [x] N9-allyl-8-oxoguanine
- [x] N1-methylguanine
- [x] N2,N2-dimethylguanine
- [x] N2-methylguanine
- [x] 6-O-methylguanine
- [x] N7-methylguanine
- [x] N7-methyl-8-dihydroguanine
- [x] 5-methylcytosine
- [x] N4-acetylcytosine
- [x] G-clamp
- [x] guanidino-G-clamp
- [x] 4N-Hydroxycytosine
- [x] 8-azidoadenine
- [x] N6-benzyladenine
- [x] N6-cyclopropylmethyladenine
- [x] N6-cyclohexyladenine
- [x] N6-cyclopentyladenine
- [x] N6,N6-dimethyladenine
- [x] N6-ethyladenine
- [x] N6-ethyladenine
- [x] 2-(1-(3-aminopropyl)imidazole)adenine
- [x] N1-methyladenine
- [x] N3-(dimethylamino)propylaminoadenine
- [x] N6-methyladenine

| Symbol | Old name | New name |
| --- | --- | --- |
| s6puri | 6-Thiopurine | 6-Mercaptopurine |
| brviny | 5-(2-Bromovinyl)uracil | (E)-5-(2-bromovinyl)uracil | 
| d4U | 4-Deoxouracil | 2-hydroxypyrimidine |
| DBCOnC | 5-DBCO-U (ethylene carbamoyl hexylamino linker) | 5-DBCO-U |
| mnm5U | 5-[(Methylamino)methyl]uridine | 5-[(methylamino)methyl]uracil |
| thiz5U | 5-Thiazoleuridine | 5-Thiazoleuracil |
| pr56U | 5,6-Propylene uracil | 6,7-dihydro-1H-cyclopenta[d]pyrimidine-2,4(3H,5H)-dione | 
| h456U | 4,5,6-trihydrouracil | tetrahydro-4-hydroxy-1H-pyrimidin-2-one |
| h456UR | (R)-4,5,6-trihydrouracil | (4R)-tetrahydro-4-hydroxy-1H-pyrimidin-2-one |
| m1Yra | 1-Methyl-pseudouracil | N1-methyl-pseudouracil |
| cnes4T | 4-Cyanoethylthiothymidine | 4-Cyanoethylthiothymine |
| allyl9 | 9-Allylguanine | N9-allyl-8-oxoguanine |
| m1G | 1-Methylguanine | N1-methylguanine |
| m22G | 2,2-Dimethylguanine | N2,N2-dimethylguanine |
| m2G | 2-Methylguanine | N2-methylguanine |
| m6G | 6-Methylguanine | 6-O-methylguanine | 
| m7G | 7-Methylguanine | N7-methylguanine |
| m7h8G | 7-Methyl 8-dihydroguanine | N7-methyl-8-dihydroguanine |
| 5meC | 5-methyl-cytidine | 5-methylcytosine |
| ac4C | 4-Acetylcytosine | N4-acetylcytosine |
| gclamp | G-clamp (9-(aminoetoxy)phenoxazine) | G-clamp |
| ggclam | G-clamp (9-(guanylethoxy)phonoxazine | guanidino-G-clamp |
| oh4C | 4-N-Hydroxycytosine | 4N-Hydroxycytosine |
| az8A | Azidoadenine | 8-azidoadenine |
| baA | N-benzyl-adenine | N6-benzyladenine |
| cmpA | N-cyclopropylmethyl-adenine | N6-cyclopropylmethyladenine |
| cyh6A | 6-Cyclohexyladenine | N6-cyclohexyladenine |
| cyp6A | 6-Cyclopentyladenine | N6-cyclopentyladenine |
| daA | N,N-dimethyl-Adenine | N6,N6-dimethyladenine |
| e6A | 6-Ethyladenine | N6-ethyladenine |
| eaA | N-ethyl-adenine | N6-ethyladenine |
| imprn2 | N-(Aminopropyl)imidazoleadenine | 2-(1-(3-aminopropyl)imidazole)adenine |
| m1A | 1-Methyladenine | N1-methyladenine |
| m2nprn | 3-(Dimethylamino)propylaminoadenine | N3-(dimethylamino)propylaminoadenine | 
| meA | N-Methyl-Adenine | N6-methyladenine |

## Sugars

- [x] 1',2'-dideoxyribose
- [x] Ribose (2,5 connectivity)
- [x] 6-FAM (3' end)
- [x] Thiol Modifier 6 S-S (3' end)
- [x] 2-(methylamino)acetamidate (5' end)
- [x] 6-FAM (5' end)
- [x] N-acetyl-2-deoxyazaribose
- [x] 2-ethyl-2-deoxyribose
- [x] Ara-FHNA

| Symbol | Old name | New name |
| --- | --- | --- |
| 12ddR | 1',2'-Di-Deoxy-Ribose | 1',2'-dideoxyribose |
| 25R | 2,5-Ribose | Ribose (2,5 connectivity) |
| 3FAM | 3-FAM | 6-FAM (3' end) | 
| 3SS6 | 3'-Thiol-Modifier 6 S-S from Glen Research | Thiol Modifier 6 S-S (3' end) | 
| 5cGT | 2-(methylamino)acetamidate (GeneTools 5'-cap for PMO) | 2-(methylamino)acetamidate (5' end) |
| 5FAM | 5'-6FAM (6-carboxyflurescein) | 6-FAM (5' end) |
| acn4d | 4-Acetylamino-2-deoxyribose | N-acetyl-2-deoxyazaribose |
| Ae2d | 2-alpha-C-ethyl-2-deoxyribose | 2-ethyl-2-deoxyribose |
| afhna | 3-ara FHNA | Ara-FHNA |

**Comment by AlexeyGirin** [comment]
Verified.

**Versions**
- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10
