### ISSUE TITLE
Change symbols of monomers

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5324]
## Peptides

- [x] L-threoninol
- [x] D-threoninol

| Old symbol | New symbol | Name |
| --- | --- | --- |
| dThrol | Thr-ol | L-threoninol |
| Thr-ol | dThrol | D-threoninol |

## Nucleotides

- [x] 2,6-Diaminopurine
- [x] Hydroxymethyl dC
- [x] 5-Bromo-deoxyridine

| Old symbol | New symbol | Name |
| --- | --- | --- |
| 2-Amino-dA | 2-damdA | 2,6-Diaminopurine |
| 5HydMe-dC | 5hMedC | Hydroxymethyl dC |
| 5-Bromo dU | 5Br-dU | 5-Bromo-deoxyridine |

## Phosphates

- [x] Dihydrogen phosphate
- [x] Dihydrogen phosphorothioate

| Old symbol | New symbol | Name |
| --- | --- | --- |
| naP | P- | Dihydrogen phosphate (old name: Sodium Phosphate) |
| nasP | sP- | Dihydrogen phosphorothioate (old name: Sodium Phosphothiotate) |

**Comment by AlexeyGirin** [comment]
Verified.

**Versions**
- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10
