### ISSUE TITLE
Change natural analogue of monomers

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5325]
## Peptides

- [x] D-Pyroglutamic acid
- [x] Pyroglutamic acid

| Symbol | Name | Old natural analogue | New natural analogue |
| --- | --- | --- | --- |
| D-Pyr | D-Pyroglutamic acid | E | G |
| Pyr | Pyroglutamic acid | E | G |

## Bases

- [x] Orotic Acid

| Symbol | Name | Old natural analogue | New natural analogue |
| --- | --- | --- | --- |
| Oro | Orotic Acid | X | U |

**Comment by Zhirnoff** [comment]
Tested.
![2024-10-08_14h39_05](https://github.com/user-attachments/assets/f7a98068-8d77-4a81-900b-08791f85f2e5)
![2024-10-08_14h39_10](https://github.com/user-attachments/assets/3694464f-eca4-47e1-99f1-55f22b2245d3)
![2024-10-08_14h40_08](https://github.com/user-attachments/assets/2ff1acdc-cd57-4acc-86c1-748cd80d0b0d)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]
