### ISSUE TITLE
Some ChemDraw arrows causes Ketcher to crash

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5330]
**Steps to Reproduce**
1. Open Micro mode
2. Load from file: [ARROWS2.zip](https://github.com/user-attachments/files/16679042/ARROWS2.zip)

**Actual behavior**
System crashes to white screen
![image](https://github.com/user-attachments/assets/ab360cef-02d2-4daf-bd33-89577845fb07)
[ci.test.lifescience.opensource.epam.com-1724172159477.log](https://github.com/user-attachments/files/16679108/ci.test.lifescience.opensource.epam.com-1724172159477.log)
[ci.test.lifescience.opensource.epam.com-1724172154701.log](https://github.com/user-attachments/files/16679109/ci.test.lifescience.opensource.epam.com-1724172154701.log)

**Expected behavior**
No crash

**Versions**
- Ketcher Version 2.24.0-rc.1 Build at 2024-08-20; 05:34:03
- Indigo Toolkit Version 1.24.0-dev.3.0-gcd4fbcf8-wasm32-wasm-clang-12.0.0
- Chrome Version 127.0.6533.120 (Official Build) (64-bit)
- Win10

CDX: [CrashCDX.zip](https://github.com/user-attachments/files/16679080/CrashCDX.zip)
CDXML: [CrashCDXML.zip](https://github.com/user-attachments/files/16679085/CrashCDXML.zip)

**Comment by rrodionov91** [comment]
Can't reproduce. Verified with @AlexeyGirin
