### ISSUE TITLE
Replacing all monomers (or part of them) in edit mode - works wrong - system cuts sequence on two

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5341]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from file: [Replacing all monomers (or part of them) in edit mode - works wrong - system cuts sequence on two.zip](https://github.com/user-attachments/files/16708345/Replacing.all.monomers.or.part.of.them.in.edit.mode.-.works.wrong.-.system.cuts.sequence.on.two.zip)
![image](https://github.com/user-attachments/assets/9bc0f33d-9bc1-4e2f-85ac-506715becc39)
3. Select three @ symbols in edit mode (having blinking cursor somewhere in the middle of sequence - this is important!
![image](https://github.com/user-attachments/assets/e56ef800-d93e-4d77-af85-9e8e347a8233)
4. Click any monomer from the library (`C` peptide in my case) - click Yes in appeared Confirm Your Action dialog

**Actual behavior**
System cuts sequence on two
![image](https://github.com/user-attachments/assets/26980d32-76a1-4674-bd04-3bef6e95fe05)

**Expected behavior**
Sequence remain solid, replacement is done
![image](https://github.com/user-attachments/assets/56affaf8-a2e4-47be-83fc-5f30b58b1936)

**Versions**
- Ketcher Version 2.24.0-rc.2 Build at 2024-08-14; 19:06:32
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-x86_64-linux-gnu-11.2.1
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10

Related issue - https://github.com/epam/ketcher/issues/4878

**Comment by tanas80** [comment]
It is enough to replace the first monomer only with the caret placed after the second monomer or farther.
![Ketcher-5341 2024-12-26](https://github.com/user-attachments/assets/4b6c9a03-e24e-48fa-8772-4afe5a6c63aa)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2025-01-03_12h26_29](https://github.com/user-attachments/assets/02dc02e7-128c-46c0-92c7-fed8caa951cd)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
