### ISSUE TITLE
Inform User to Apply Layout after Settings Adjustment

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5351]
**Background**
Related task https://github.com/epam/ketcher/issues/5152 the new setting Reaction component margin size were implemented.

**Solution**
When the user adjusts the "Reaction component margin size" settings and clicks the "Apply" button, an informational message should be displayed, informing the user that these changes require applying the layout to take full effect. 

The message: "To fully apply these changes, you need to apply the layout."

The informational window  should include an "OK" button for the user to acknowledge the message and close the notification.

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10
