### ISSUE TITLE
Apply new hash spacing setting to canvas

### ISSUE THREAD

**Issue by accmeboot** [epam/ketcher#5354]
Apply the new hash spacing setting to ketcher canvas.

Background
To fully comply with the ACS style, the "Hash spacing" setting need to be added (done in [Related task](https://github.com/orgs/epam/projects/28/views/7?pane=issue&itemId=72186890)) 

Solution
Adjust the the distance between lines of a Single Down Bond (only applies to this bond);
![Image](https://github.com/user-attachments/assets/e2e3be3e-6765-49a3-a0f8-89d7d9365fc9)

Update: The bond should contain at least four hashes. If the hash spacing does not allow for four hashes, the setting can be ignored.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/81598385-f4c0-464d-8133-6256e1f10341)
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10
