### ISSUE TITLE
Display molecules in macro mode: basic structures with atoms and bonds

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#5359]
**Background**
Currently molecules are displayed same as chems in macromolecules mode. Structure of molecule is not clear until user hover it to see preview.

**Solution**
It needs to display molecules in macro mode in similar view as in molecules mode. Task covers basic structures only to simplify the first iteration. It includes next list of features:

- **Bonds.** All types of bonds should be implemented. Lines of double/triple bonds should not overlap each other on any angle (same as implemented for double bond in molecules mode now).
- **Atoms.** Only single atoms are in scope. Carbon atom should not be displayed. Hydrogen label should be placed after/before atom label with number subscript which in case if atom has valence more than connections. Valence validation errors are out of scope. Charge is out of scope.
- **Connections.** It should be possible to establish connection between monomer and molecule in macromolecules mode by drawing the bond between monomer and molecule's attachment point, created in molecules mode.
- **User settings.** Applying user settings are out of scope.
- All other entities( sgroups, rgroups, rgroup attachment points, e.t.c) are out of scope.

**Comment by AlexeyGirin** [comment]
Verified with issues.

- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10
