### ISSUE TITLE
Send ACS parameters for layout and convert backend functions

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#5365]
Background
Related issue: https://github.com/epam/ketcher/issues/5152, https://github.com/epam/Indigo/issues/2176

Solution
the following parameters should be sent when requesting `layout` and `convert` backend functions :

`bond-length-unit`
`bond-length`
`reaction-component-margin-size-unit`
`reaction-component-margin-size`
`image-resolution`

**Comment by AlexeyGirin** [comment]
[ACS-StyleGuide.pdf](https://github.com/user-attachments/files/16849103/ACS-StyleGuide.pdf)

**Comment by AnnaKosol** [comment]
![Image](https://github.com/user-attachments/assets/50fa700a-130f-4baf-a80b-685a165f8af4)

![Image](https://github.com/user-attachments/assets/3e53882b-0f2b-4274-a748-06963a87a205)

Verified

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
