### ISSUE TITLE
Preview: UI inconsistencies for hover and selection of Multi-Tailed Arrows

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5383]
**Steps to Reproduce**
1. Add Multi-Tailed Arrow to Canvas
2. Add arrow and element as on the screenshot below and observe:
![image](https://github.com/user-attachments/assets/7302e4c0-f7d8-43f7-8f10-3e002cf495b5)

**Actual behavior**
Can't hover on top and bottom tails, looks like they are under the element and the usual arrow

**Expected behavior**
TBD - they should be available for hover as in cases when two arrows or two elements are overlapped

3. Add arrow to compare hover area for spine and arrow
![image](https://github.com/user-attachments/assets/b71b3a52-3188-498d-8a74-e957fbd830fa)

**Actual behavior**
Hover area for arrow is greater than for spine

**Expected behavior**
TBD - they should be the same

4. Add an image and put Multi-Tailed arrow at an image
**Actual behavior**
Issue with the small hover region when Multi-Tailed Arrow is above the image on Canvas:
![image](https://github.com/user-attachments/assets/52cb21af-c400-461d-94a0-e51b55551d93)

**Expected behavior**
Hover area for Multi-Tailed arrow is the same as for usual arrow when it is on image:
![image](https://github.com/user-attachments/assets/ee078a46-2eb3-4f82-89f8-156a23371ff3)

Environmental Details:
- Nightly environment (5057-hover-selection)
- Desktop, Windows 11 Enterprise
- Chrome Version 128.0.6613.84 (Official Build) (64-bit)

**Additional context**
- Issue is found during exploratory testing of https://github.com/epam/ketcher/issues/5057

**Comment by ivanmaslow** [comment]
The issue is fixed and verified on nightly environment (5057-hover-selection):
- Multi-Tailed arrow works correctly in case of overlapping;
- Displaying of the hover are is still slightly greater than for Multi-Tailed arrow, but we confirmed that we can leave as it is;
- It works correctly as for usual arrow when Multi-Tailed Arrow is on image;

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-09-06_15h19_22](https://github.com/user-attachments/assets/7ef8d5a5-b35c-4335-9be2-af68875b30b8)
![2024-09-06_15h19_29](https://github.com/user-attachments/assets/fca781b7-c521-4c6f-a5f5-cac979f42f10)
![2024-09-06_15h22_56](https://github.com/user-attachments/assets/a8bbf927-f357-4c99-b165-965b28dfef5d)
![2024-09-06_15h23_03](https://github.com/user-attachments/assets/0a2193c7-8c4a-482c-b122-8182f3747610)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
