### ISSUE TITLE
Preview: Saved to KET Multi-Tailed Arrow can't be loaded from KET file

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5389]
**Steps to Reproduce**
1. Add a Multi-Tailed Arrow to Canvas:
![image](https://github.com/user-attachments/assets/b186a9ca-c8f5-48a7-822f-5b7116d31e1e)
2. Save to KET format
3. Load saved KET file

**Actual behavior**
- Error is displayed:
![image](https://github.com/user-attachments/assets/28f9d20e-666e-49c2-bc84-39ca733fded5)

**Expected behavior**
- Multi-Tailed Arrow is added to Canvas

**Note**
- Issue also can be reproduced when you copy/paste the Multi-Tailed Arrow

Environmental Details:
- Nightly environment (5057-hover-selection)
- Desktop, Windows 11 Enterprise
- Chrome Version 128.0.6613.84 (Official Build) (64-bit)

**Additional context**
- Issue is found during exploratory testing of https://github.com/epam/ketcher/issues/5057

**Comment by ivanmaslow** [comment]
The issue is reproduced on nightly environment (5057-hover-selection) for Multi-Tailed Arrow with 4 tails:
![image](https://github.com/user-attachments/assets/4b9ded2c-22fd-4f12-973a-40bd5a688741)
Steps to reproduce:
1. Add  Multi-Tailed Arrow 
2. Add two additional tails
3. Copy
4. Paste

**Comment by split-ends** [comment]
Successfully verified: no errors occurred when saving-importing and copying-pasting:
![2024-09-06_11h40_12](https://github.com/user-attachments/assets/dece9841-0795-45e8-9f21-e9df5d96f527)

**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
Windows 11 Enterprise
