### ISSUE TITLE
Elliptic arrow icons order is wrong at arrow toolbar 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5398]
**Steps to Reproduce**
1. Toggle to Molecules mode
2. Open arrow menu in toobar
![image](https://github.com/user-attachments/assets/93536492-c7b6-45a5-8ffd-fda5115b7eac)

**Actual behavior**
Elliptic arrow icons order is wrong

**Expected behavior**
![image](https://github.com/user-attachments/assets/f18245f1-2c37-471a-beeb-81fd7f4622fe)

**Versions**
- Ketcher Version 2.24.0-rc.3 Build at 2024-08-20; 13:23:13
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-x86_64-linux-gnu-11.2.1
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

**Comment by AnnaKosol** [comment]
in the environment https://nightly.test.lifescience.opensource.epam.com/KetcherDemoSA/5153-change-the-default-size-of-a-plus-and-the-arrows/index.html 
branch 5153-change-the-default-size-of-a-plus-and-the-arrows

Elliptic arrow icons order is wrong
<img width="289" alt="Снимок экрана 2024-09-27 в 14 59 45" src="https://github.com/user-attachments/assets/ac5a1454-fc2b-4a9e-bc71-f00dc31715a2">

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/07a1909b-25e2-4b32-a749-27649c19785b)
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10
