### ISSUE TITLE
Fire custom event on structure change

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#54]
When user changes structure on canvas would be good to fire "change" event with information about performed operation (e.g. `{ op: "AtomMove", from: { x: 10, y: 10 }, to: { x: 20, y: 20 }`).
Now Ketcher is already firing empty "change" event. #3 
Needs to investigate possibility to pass information about performed action to fired event.
Create format of custom event and apply it on all operations if previous right.

**Comment by AnastasiiaMiagkikh** [comment]
https://github.com/epam/ketcher/pull/205
