### ISSUE TITLE
Expand macromolecules in micro mode

### ISSUE THREAD

**Issue by svvald** [epam/ketcher#5400]
Currently upon switching from polymer editor to micromolecules mode while having some monomers on the canvas leads to the quite limited user experience – monomers are displayed as their aliases, their structure can only be seen in the preview while hovering over it.

The purpose of this feature is to allow user to expand macromolecules in micromolecules mode similar to functional groups in order to have the exact structure on the canvas and manipulate it.
1. "Expand monomer" option should be present in the context menu on right-click over the monomer:
<img width="192" alt="image" src="https://github.com/user-attachments/assets/2e10f946-9afd-4ed1-b387-ffad639997ea">

2. Clicking on expand option should replace monomer abbreviation with its structure atoms and bonds grouped together. Monomer's structure bounding box should be centered by the previously collapsed monomer position. Editing is forbidden for the expanded monomer – no atoms or bonds can be added/removed to the expanded monomer structure. Square brackets shouldn't be present for expanded monomers as there is another scientific meaning but monomer label should persist (similar to data s-groups now).
<img width="272" alt="image" src="https://github.com/user-attachments/assets/af5b4890-fef1-4b85-850b-63a1b3ee06f6">

3. While expanding a monomer positioned within a chain, all atoms which are connected directly or via other atoms to the monomer going to be expanded have to be moved along their direction by the half-size of the expanded monomer's bounding box.
Expanding multiple monomers should be possible – the aforementioned algorithm should be applied for the rest of the chain as well as for the already expanded monomers. While expanding multiple monomers, top-most and left-most monomer should be processed first during adjacent structures repositionig and then every monomer consequently in left-to-right, top-to-bottom order. Calculations have to be accumulated and all expansions rendered only once.

4. "Collapse monomer" option should be present in the right-click context menu over the expanded monomer structure.
While clicked, the monomer contracts back to its label on the canvas, contracted label position should be placed in the center of structure's bounding box and then all atoms which are connected to it should be moved back to their initial positions if needed by reversing the previously mentioned algorithm of chain movement.

As a side note – also make macromolecules abbreviations and their bonds in micromolecules mode movable as now they're static and can only be viewed or deleted. Expanded monomers are able to be moved across canvas as well.

**Comment by Zhirnoff** [comment]
Tested. There are many bugs introduced.


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]
