### ISSUE TITLE
Side-chain connections are not displayed in Snake mode

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5401]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Snake mode
2.	Draw any monomers (peptides, nucleotides, CHEMs) on the canvas
3.	Drag side-chain connections between these monomers

**Actual behavior**
Side-chain connections can be dragged, but they are not displayed on the canvas

<img width="230" alt="image" src="https://github.com/user-attachments/assets/19dc3631-5a00-44e3-8b6b-8804a4049e1f">

<img width="219" alt="image" src="https://github.com/user-attachments/assets/fb34ae9a-c34e-4252-a896-13f74888cec4">

<img width="255" alt="image" src="https://github.com/user-attachments/assets/c04fe04b-68b9-4b1d-b755-bd8494fc59fa">

**Expected behavior**
Side-chain connections are displayed on the canvas

**Screenshots**

https://github.com/user-attachments/assets/525c8ae3-c3b8-440c-b412-3a574a045825

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (version 22H2) 
 - Browser: Сhrome
 - Version: (127.0.6533.122) x64

**Ketcher version** 2.24.0-rc.1, Build at 2024-08-23; 12:23:08

**Indigo version** 1.24.0-rc.4

Issue found while testing https://github.com/epam/ketcher/issues/3532

**Comment by Zhirnoff** [comment]
Tested. Bug not fixed.

https://github.com/user-attachments/assets/4d610f81-c2ab-4858-933c-81075112b9a2



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/user-attachments/assets/70e73144-ec65-44ae-b807-0b846ccaeccb


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.3]
**Indigo version** 
[Version 1.25.0-rc.2]
