### ISSUE TITLE
Can't add specific SVG image to Canvas in Mozilla Firefox

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5413]
**Steps to Reproduce**
1. Open the Ketcher in Mozilla Firefox
2. Click "Add Image" button
3. Click on Canvas
4. Select this SVG image:
[SVG_Logo 1.zip](https://github.com/user-attachments/files/16836933/SVG_Logo.1.zip)

**Actual behavior**
- Error message is displayed:
![image](https://github.com/user-attachments/assets/65bd9c5a-9730-4eda-bd7c-23a859947703)

**Expected behavior**
- Image is added to selected place to Canvas as it work in Google Chrome:
![image](https://github.com/user-attachments/assets/429fba42-60f7-4a53-8b92-47de5c650827)

**Environment Details:**
- Ketcher [Version 2.24.0-rc.3] Build at 2024-08-20; 13:16:59
- Indigo Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0
- OS: Windows 11 Enterprise
- Browser: Mozilla Firefox Version 129.0.2 (64-Bit)

**Additional context**
- Detected during the investigation of https://github.com/epam/Indigo/issues/2162
- It works for some other SVG images in Mozilla Firefox

**Comment by rrodionov91** [comment]
Need to be merged in 2.26

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-10-26_13h03_18](https://github.com/user-attachments/assets/c06c55a2-2e80-44ee-a404-1b0be7a45d36)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.6]
**Indigo version** 
[Version 1.25.0-rc.4]
