### ISSUE TITLE
Update Coordinate Storage to Fixed-Point Precision for Multi-Tailed Arrows and other elements in Ketcher Project

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5414]
**Background**
In the Ketcher project, the coordinates for multi-tailed arrows are currently stored in a floating-point format (e.g., 10.325000000000001). This precision can lead to inconsistencies and potential issues during the saving and loading of files. To improve reliability and accuracy, we propose changing the approach to use fixed-point precision for counting coordinates and distances.
Issue for multi-tailed arrow - https://github.com/epam/ketcher/issues/5447

**Solution (TBD)**
We intend to modify the coordinate and distance calculation methods for multi-tailed arrows in the Ketcher project to use fixed-point precision instead of floating-point.

**Point to clarify (TBD - need to confirm with Valentin and Aleksandr)**:
- Should this update apply only to multi-tailed arrows, or should it be extended to other elements as well?
- What level of fixed-point precision should be used (e.g., 4 decimal places)?

**Acceptance Criteria (TBD)**
- All calculations and storage of coordinates and distances for multi-tailed arrows are converted to fixed-point precision.

**Comment by yauhen-karmyzau** [comment]
No issues with KET.

**Comment by ivanmaslow** [comment]
As discussed with @AlexanderSavelyev and @vanoprenko, it makes no sense to fix it for other elements as we don't have issues with them.
It's just fixed for Multi-Tailed Arrow (fixed-point precision = 5 decimal places) - https://github.com/epam/ketcher/issues/5447
