### ISSUE TITLE
Undo-Redo operations over ambiguous monomer causes broken canvas

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5425]
**Steps to Reproduce**
1. Toggle to Macro - Sequence mode
2. Load from file: [Undo-Redo operations over ambiguous monomer causes broken canvas.zip](https://github.com/user-attachments/files/16868223/Undo-Redo.operations.over.ambiguous.monomer.causes.broken.canvas.zip)
![image](https://github.com/user-attachments/assets/0e72b318-b4bc-4e90-a2e7-cc1da4491abe)
3. Select monomer
![image](https://github.com/user-attachments/assets/0a424cf1-3204-494e-b7de-0cdb9a4a474c)
4. Copy it to clipboard (press Copy+C)
5. Press Copy+V
![image](https://github.com/user-attachments/assets/99029567-9d6d-4a00-8177-f411df5706c4)
6. Press Undo button

**Actual behavior**
Nothing happens
![image](https://github.com/user-attachments/assets/562b8624-666d-4e34-83f0-231950b7de2a)
More over - games with Undo-redo can cause unremovable elements on the canvas

**Expected behavior**
Pasted monomer disappears
![image](https://github.com/user-attachments/assets/0e72b318-b4bc-4e90-a2e7-cc1da4491abe)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/ketcher/issues/4556

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/6326a222-2ed0-433b-a0bc-c5574367bc81



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.2]
**Indigo version** 
[Version 1.24.0-rc.2]
