### ISSUE TITLE
Add a warning when saving a reaction equilibrium arrow in a format that does not support it

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#543]
The only format that supports Reaction equilibrium arrow on save/load is the "ket" format. If user selects another format, then the warning message "The ${Selected_format} does not support drawn elements: the reaction equilibrium arrow will be replaced with the reaction arrow" appears.

**Comment by AleksandrPokrovskii** [comment]
The application crashes when the structure is saved

_Steps to reproduce:_

1. Launch Ketcher.
2. Add Reaction equilibrium arrow
3. Delete Reaction equilibrium arrow
4. Add Reaction equilibrium arrow
5. Click Save button

_Expected result_: It's possible to save with warning

_Actual result_: TypeError: Cannot read property 'mode' of undefined
