### ISSUE TITLE
Change bond length for ACS styles settings 

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#5435]
**Background**
Bond length is not changed visually on canvas

**Solution**
Bond length should be changed according to the specified value and unit. The image resolution should be taken as default 

Additional information
1 inch = 72 pt
1 inch = 2.54 cm
length in pixels = ppi * length in inch

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 3.4.0-rc.2 Build at 2025-05-09; 17:40:29
- Indigo Version 1.32.0-rc.1.0-g65e26e370-wasm32-wasm-clang-19.0.0
- Chrome Version 136.0.7103.93 (Official Build) (64-bit)
- Win10
