### ISSUE TITLE
Copy/Cut and Paste using Ctrl+C/X  and Ctrl+V doesn't work for static elements in Mozilla Firefox

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5476]
**Steps to Reproduce**
1. Add different elements to Canvas: bond, chain, plus, arrows, shape, text, image, benzene ring:
2. Select all elements using Rectangle Selection:
![image](https://github.com/user-attachments/assets/68a8c979-e392-4dee-ad6d-fb5c1d44e674)
3. Click Ctrl+C
4. Click Ctrl+V

**Actual behavior**
- Only chemical elements are copied:
![image](https://github.com/user-attachments/assets/3c07ef17-b276-42f9-9075-8cde9cd69a11)

**Expected behavior**
- All elements are copied

**Environment Details**
- Ketcher [Version 2.25.0-rc.1] Build at 2024-09-03; 15:37:29
- Indigo Version 1.24.0-rc.1.0-gb8f099851-x86_64-linux-gnu-11.2.1
- Windows 11 Enterprise
- Mozilla Firefox Version 130.0 (64-bit)

**Additional context**
- Issue is found during RC testing of Multi-Tailed Arrows - https://github.com/epam/ketcher/issues/5057, but it's not related to this feature;
- It can be related to existing defect - https://github.com/epam/ketcher/issues/1321

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/user-attachments/assets/1d2335c3-ecbe-45c7-87d0-d93b863b43be


**Desktop:**
 - OS: Windows 11
 - Browser Mozilla
 - Version 133.0.3 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
