### ISSUE TITLE
System saves mixture ambiguous monomers as alternatives ambiguous monomers

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5512]
**Steps to Reproduce**
1. Toggle to Macro - Flex
2. Load from clipboard way: `PEPTIDE1{(D,N,I)}$$$$V2.0`
3. Load from clipboard way: `PEPTIDE1{(D+N+I)}$$$$V2.0`
![image](https://github.com/user-attachments/assets/c4ca900c-bc3d-41df-bddc-d302bb120582)
4. Save canvas to HELM

**Actual behavior**
System saves both monomer as alternatives
![image](https://github.com/user-attachments/assets/526f0f5b-313d-49b4-a70b-9c98d48b607a)

**Expected behavior**
Resulted HELM should be `PEPTIDE1{(D,N,I)}|PEPTIDE2{(D+N+I)}$$$$V2.0`

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2188

**Comment by AliaksandrDziarkach** [comment]
Ketcher generate ket with only one tenplate:
```
{
    "root": {
        "nodes": [
            {
                "$ref": "monomer89"
            },
            {
                "$ref": "monomer90"
            }
        ],
        "connections": [],
        "templates": [
            {
                "$ref": "ambiguousMonomerTemplate-_D___Aspartic acid_N___Asparagine_I___Isoleucine"
            },
            {
                "$ref": "monomerTemplate-D___Aspartic acid"
            },
            {
                "$ref": "monomerTemplate-N___Asparagine"
            },
            {
                "$ref": "monomerTemplate-I___Isoleucine"
            }
        ]
    },
    "monomer89": {
        "type": "ambiguousMonomer",
        "id": "89",
        "position": {
            "x": 9.52500000000001,
            "y": -8.9
        },
        "alias": "%",
        "templateId": "_D___Aspartic acid_N___Asparagine_I___Isoleucine"
    },
    "ambiguousMonomerTemplate-_D___Aspartic acid_N___Asparagine_I___Isoleucine": {
        "type": "ambiguousMonomerTemplate",
        "id": "_D___Aspartic acid_N___Asparagine_I___Isoleucine",
        "alias": "%",
        "subtype": "alternatives",
        "options": [
            {
                "templateId": "D___Aspartic acid"
            },
            {
                "templateId": "N___Asparagine"
            },
            {
                "templateId": "I___Isoleucine"
            }
        ]
    },
```

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/0340c5fd-7795-486d-8d26-2897cec0e269)
**Versions**
- Ketcher Version 2.25.0-rc.3 Build at 2024-09-18; 16:24:03
- Indigo Toolkit Version 1.24.0-rc.3.0-g692080c62-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.59 (Official Build) (64-bit)
- Win10
