### ISSUE TITLE
After opening a saved HELM file, microstructure F1 turns into Base (Mod0)

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#5513]
**Summary**
After opening a saved HELM file, microstructure F1 turns into Base (Mod0)

**Steps to Reproduce**
1. Open file in Macro [Unable.to.save.micro-molecule.connected.to.CHEM.to.HELM.zip](https://github.com/user-attachments/files/16887687/Unable.to.save.micro-molecule.connected.to.CHEM.to.HELM.zip)
2. Save as HELM
3. Open saved file

**Expected behavior**
The structures look the same as before saving.
![2024-09-05_13h13_02](https://github.com/user-attachments/assets/3d03cae6-cf36-4321-8cff-e4f55bc28f4b)

**Actual behavior**
After opening a saved HELM file, microstructure F1 turns into Base (Mod0)
![2024-09-05_11h42_19](https://github.com/user-attachments/assets/e71e7404-ab22-4985-a3f4-1ca088bd5c88)
Saved HELM file [ketcher (2).zip](https://github.com/user-attachments/files/16887696/ketcher.2.zip)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]

**Additional context**
Bug found during testing: 
https://github.com/epam/Indigo/issues/2189 
https://github.com/epam/Indigo/issues/2073

**Comment by AliaksandrDziarkach** [comment]
This monomer has class CHEM:
```
        "class": "CHEM",
        "id": "Mod0",
        "fullName": "Mod0",
        "alias": "Mod0",
        "attachmentPoints": [
```

**Comment by AliaksandrDziarkach** [comment]
Correct - it should be displayed as a sqiare as other chems, but it displayed as base.
It is ketcher issue.

**Comment by Zhirnoff** [comment]
And name on it should be F1 but we have Mod0

**Comment by Zhirnoff** [comment]
Tested. The bug has been fixed only for visual display of the microstructure as CHEM instead of Base, but instead of F1, the name Mod0 is displayed on the structure. A separate bug has been created for this on the Indigo side https://github.com/epam/Indigo/issues/2387

![2024-09-16_16h21_11](https://github.com/user-attachments/assets/c677d99d-4090-4d17-b14a-0f41719fd72e)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.2]
**Indigo version** 
[Version 1.24.0-rc.2]
