### ISSUE TITLE
After uploading a multi-character monomer in HELM format, abbreviations in sequence mode are cluttered together

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#5545]
**Steps to Reproduce**
1. Toggle to Macro - Sequence mode
2. Load from Paste from Clipboard way: `RNA1{R([5eU],[Xan],[psiU])P}$$$$V2.0`
3. Look at abbreviations

**Actual behavior**
After uploading a multi-character monomer in HELM format, the abbreviations in sequence mode are cluttered together

**Expected behavior**
After uploading a multi-character monomer in HELM format, abbreviations in sequence mode should be displayed clearly and spaced appropriately, without being compressed or cluttered together. Each abbreviation should be distinct and easily readable to ensure accurate interpretation of the sequence

**Screenshots**
![2024-09-19_13h18_06](https://github.com/user-attachments/assets/c99cd85c-6d08-428d-8a2c-3bb1ceae8968)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.3]
**Indigo version** 
[Version 1.24.0-rc.3]

Bug found during testing: https://github.com/epam/Indigo/issues/2321

**Comment by nourakhy** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-09-24_10h07_34](https://github.com/user-attachments/assets/15ce06a2-57ea-46a0-b6b5-701e43c2cc30)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.4]
**Indigo version** 
[Version 1.24.0-rc.3]
