### ISSUE TITLE
The tail of Multi-Tailed Arrow is added to not the proper place on the Spine after the Redo action of removing the tail if the length of the spine were changed

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5548]
**Steps to Reproduce**
1. Add default Multi-Tailed Arrow to Canvas:
![image](https://github.com/user-attachments/assets/783d47fe-754d-4122-9c5a-25ed916fc373)
2. Add a new tail by right-click
3. Change the length of the spine by pulling the bottom tail down:
![image](https://github.com/user-attachments/assets/1f03b69a-c98d-4966-bcb3-4828c476e6b8)
4. Right-click on the middle tail
5. Click on Remove tail - tail is removed
6. Click on Undo

**Actual behavior**
- Tail is added to the middle of the spine:
![image](https://github.com/user-attachments/assets/067e2ca0-d525-4ab7-a385-7a990e5fd803)

**Expected behavior**
- Tail is added to the initial place

**Environment details**
- Tested on RC SA environment
- Ketcher [Version 2.25.0-rc.3] Build at 2024-09-18; 16:24:03
- Indigo Version 1.24.0-rc.3.0-g692080c62-wasm32-wasm-clang-19.0.0
- Windows 11 Enterprise 
- Chrome Version 128.0.6613.138 (Official Build) (64-bit) 

**Notes**
- Issue is detected during the implementation of automation tests - https://github.com/epam/ketcher/issues/5463 and it's related to https://github.com/epam/ketcher/issues/5056

**Comment by ivanmaslow** [comment]
Preview testing is completed on the nightly environment 5581-mmpk-issues:
- Ketcher [Version 2.26.0-rc.1] Build at 2024-10-14; 08:25:46;
- Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Desktop, Windows 11 Enterprise
- Chrome, Version 129.0.6668.101 (Official Build) (64-bit)

Undo/Redo actions work correctly for the Multi-Tailed arrow added by Tool or from KET, including the case of Undo of removing of a tail:

https://github.com/user-attachments/assets/504242dd-a590-49d5-8ac8-7b2345cb5547

**Comment by yauhen-karmyzau** [comment]
Merged to [Ketcher 2.26.0-rc.2](https://github.com/epam/ketcher/milestone/145)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/785684e3-a901-4a31-a2de-f30eed0f9271)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
