### ISSUE TITLE
R3less sugars are disabled in the “Sugars” section, when trying to create a new preset for the second time

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5550]
**Steps to Reproduce**
1.	Switch to Macro mode - the Fullscreen mode
2.	Create a new preset in the RNA tab
 
      <img width="198" alt="image" src="https://github.com/user-attachments/assets/b5e786cb-345a-4b60-8a35-796ec8a5279c">

3.	Click on the “New preset” button in the “Presets” section again
4.	Open “Sugars” section

**Actual behavior**
In the “Sugars” section, R3less sugars are disabled

<img width="203" alt="image" src="https://github.com/user-attachments/assets/29a16d97-092a-4ab0-8631-165b0aa8f205">
<img width="204" alt="image" src="https://github.com/user-attachments/assets/e94770fb-dd17-4501-9476-3963e6b15d2b">

**Expected behavior**
In the “Sugars” section, R3less sugars are turned on

**Screenshots**

https://github.com/user-attachments/assets/5c6868fb-2764-4db9-927a-9e37573e26b0

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (version 22H2) 
 - Browser: Сhrome
 - Version: (128.0.6613.138) x64

**Ketcher version** 2.25.0-rc.3, Build at 2024-09-18; 16:24:03

**Indigo version** 1.24.0-rc.3.0

Related to  https://github.com/epam/ketcher/issues/5313

**Comment by rrodionov91** [comment]
Duplicate https://github.com/epam/ketcher/issues/5313

**Comment by AlexeyGirin** [comment]
Verified.
