### ISSUE TITLE
When saving in SVG format, unsplit nucleotides, whose names consist of several rows, are left without part of the name

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/ketcher#5552]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Flex mode 
2.	In the RNA tab in the “Nucleotides” section, select 5HydMe-dC, 2-Amino-dA, 5-Bromo dU and add them to the canvas
 
      <img width="230" alt="image" src="https://github.com/user-attachments/assets/971e4400-1f53-4dd4-a174-b8ad32f65119">

3.	Save them in the SVG file format

**Actual behavior**
Names of the unsplit nucleotides are shown not fully

<img width="533" alt="image" src="https://github.com/user-attachments/assets/e122584b-34b7-4188-8966-441482d5e194">

**Expected behavior**
Names of the unsplit nucleotides are shown fully

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (version 22H2) 
 - Browser: Сhrome
 - Version: (128.0.6613.138) x64

**Ketcher version** 2.25.0-rc.3, Build at 2024-09-18; 16:24:03

**Indigo version** 1.24.0-rc.3.0

Issue found while testing https://github.com/epam/ketcher/issues/4382

**Comment by Zhirnoff** [comment]
Tested.
![2024-12-06_11h17_36](https://github.com/user-attachments/assets/96cc207c-ef2c-426f-89c6-735d52683928)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
