### ISSUE TITLE
Set a new name for the button ACS style

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5561]
**Background**
related https://github.com/epam/ketcher/issues/5156 the button has been added

**Solution**
by agreement with @vanoprenko a new name for button should be "Set ACS Settings"

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-10-21_19h23_25](https://github.com/user-attachments/assets/56ae25d4-2856-4d3b-af0e-d625d3e00d8c)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.5]
**Indigo version** 
[Version 1.25.0-rc.3]
