### ISSUE TITLE
Search of ambiguous monomers doesn't work

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5564]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Open Library, go to Peptides tab
3. Search `J`
4. Search `Isoleucine`

**Actual behavior**
No `J` amiguous monomer in search result
![image](https://github.com/user-attachments/assets/3493eb7a-8149-40e7-90fd-3808a2033f81)

**Expected behavior**
`J` amiguous monomer in search result 
![image](https://github.com/user-attachments/assets/aed18d27-bb89-4dd7-8c57-a7e34ed33d6e)

System should allow to search ambiguous monomers by name or by its components
As per @ljubica-milovic 

**Versions**
- Ketcher Version 2.25.0-rc.4 Build at 2024-09-23; 17:24:38
- Indigo Toolkit Version 1.24.0-rc.3.0-g692080c62-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.59 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/ketcher/issues/5186

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-11-07_15h26_46](https://github.com/user-attachments/assets/9d5f8798-4a8c-487c-b09a-7dcbbc5a28eb)
![2024-11-07_15h27_13](https://github.com/user-attachments/assets/39bfcd2a-eb82-4524-85da-ac782d474c8a)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
