### ISSUE TITLE
Introduce the hand tool in macromolecules mode

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5579]
**Background**
Canvas navigation in macromolecules mode is significantly less user-friendly than it is in molecules mode. This ticket is one of the tickets aiming to address that issue.

**Requirements**

1. The "Hand tool" should be able to be chosen from the top of the left sidebar (same placement as in micromolecules mode).

2. The hand tool should look the same in both modes:
> ![image](https://github.com/user-attachments/assets/5199041b-c5fd-4a54-a5ef-83184d784176) (in the sidebar)
> ![image](https://github.com/user-attachments/assets/af61bfe2-e8c0-4a72-b7a6-79299cb39fa4) (hover over)
> ![image](https://github.com/user-attachments/assets/ab669cde-10cc-4952-a649-2229c0ead403) (selected)
> ![image](https://github.com/user-attachments/assets/d9d53e66-61f1-4b34-9f46-c40002619525) (on canvas, not dragging)
> ![image](https://github.com/user-attachments/assets/8d2a65f3-d769-4721-827e-b6d421b30528) (on canvas, dragging)

3. The same shortcut should be used (Ctrl+Alt+H)*, and the shortcut should be visible on hover in the sidebar.
> .* For MacOS users, instead of Alt Option is used, and instead of Ctrl Command is used.

4. When selected, the hand tool disables any interaction with the elements on screen.
> Even when the hand tool is over a monomer (for example), the monomer will not be highlighted in any way.
> Clicking with the hand tool does not allow selection of any elements on the canvas.

5. The functionality of the hand tool is the same in both modes:
> AC3: GIVEN Ketcher user working with the canvas content with scrolls presented with Hand tool enabled WHEN clicking on the left mouse button over the canvas AND moving the mouse THEN Ketcher canvas content should be moved like the canvas was dragged by the hand to the direction of the mouse move AND canvas content should be presented as if scrolls were moved AND scrolls position should be updated and scrolls should hide if the move has resulted in displaying all canvas content in the window
> AC4: GIVEN Ketcher user working with the canvas content without scrolls presented with Hand tool enabled WHEN clicking on the left mouse button over the canvas AND moving the mouse THEN Ketcher canvas content should be moved like the canvas was dragged by the hand to the direction of the mouse move AND srolls may appear if the move results in hiding part of the canvas content
> The explanation from the ticket introducing the hand tool in molecules mode [#1306](https://github.com/epam/ketcher/issues/1306)

**Comment by Zhirnoff** [comment]
Tested
![2024-11-06_16h00_36](https://github.com/user-attachments/assets/10a42caf-a40e-4846-98b1-01658271b1d9)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
