### ISSUE TITLE
Add the ability to save information about the coordinates of the Stereo flags in * .ket

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#559]
1. User creates a structure on the canvas, adds a stereobond (stereo flag appears next to the structure), saves the structure in ket.
_Result:_ As user hasn't moved the stereo flag the information about the coordinates is not present in ket file and their values are set by default.

2. User creates a structure on the canvas, adds a stereobond (stereo flag appears next to the structure), moves the stereo flag (to a new position or it is returned to the initial position after being moved), saves the structure in ket.
_Result:_ Stereo flag coordinates are present in ket file. After opening the saved file the stereo flag appears at the position in which it was before saving.

**Comment by Svetlana-Asinovskaia** [comment]
Check the following scenario of overlapping the Stereo flag with a structure:

1. Launch Ketcher.
2. Create a benzene molecule using the Templates tool.
3. Add a stereo bond (e.g. Single Up bond) to the following carbon atom:
![image](https://user-images.githubusercontent.com/80695128/120810866-14186580-c554-11eb-8a7f-7f1c49580f2a.png)
4. Add another stereo bond to the following carbon atom:
![image](https://user-images.githubusercontent.com/80695128/120811054-432ed700-c554-11eb-8dc1-6fe8ba505330.png)

Expected result: Stereo flag is not overlapped with a structure.
Actual result: Stereo flag is overlapped with a structure.

**Comment by AleksandrPokrovskii** [comment]
Stereo flag is overlapped with a structure.

1) Launch Ketcher.
2) Create a benzene molecule using the Templates tool.
3) Add a stereo bond (e.g. Single Up bond) to the following carbon atom:
![image](https://user-images.githubusercontent.com/85170103/123426372-02af0000-d5cc-11eb-9d4e-789dd8458fe9.png)

3)Add a single bond to the following carbon atom:
![image](https://user-images.githubusercontent.com/85170103/123426503-2a9e6380-d5cc-11eb-94f5-42d189255fdc.png)


Expected result: Stereo flag is not overlapped with a structure.
Actual result: Stereo flag is overlapped with a structure.

**Comment by AndreiMazol** [comment]
It will be fixed in scope of a separate issue: https://github.com/epam/ketcher/issues/602
cc: @AleksandrPokrovskii
