### ISSUE TITLE
Zoom in macromolecules mode should be in relation to the top left corner of the structures

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5590]
**Background**
Currently, if the user zooms in (not using the hotkeys) the zooming in happens in the relation to the center of the canvas/screen, and that sometimes results in the disappearance of the sequence from the view. This ticket addresses that issue by zooming in the relation of the top left corner of the sequence(s).

**Requirement**

- When the user zooms in (using the Ctrl+,Ctrl- hotkeys or via buttons on top toolbar), the zooming in should be in relation to the most top and most left monomer on canvas.

**Examples**

![image](https://github.com/user-attachments/assets/c739633a-898a-4e51-ad8f-9a63cda4b493)
![image](https://github.com/user-attachments/assets/d6eae6f8-87aa-4cb4-80c3-87c277d645ce)
![image](https://github.com/user-attachments/assets/541e2fcc-77a9-44a4-af99-4c6b553f07e9)

**Comment by Zhirnoff** [comment]
Tested

https://github.com/user-attachments/assets/33bd06e6-91cd-4aaf-9c5c-0cf7d82ba295



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
