### ISSUE TITLE
The atom is not completely colored

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5597]
**Steps to Reproduce**
1. highlight an atom
2. choose highlight in the menu
3. click to one color

**Actual behavior**
<img width="115" alt="Снимок экрана 2024-09-27 в 16 06 06" src="https://github.com/user-attachments/assets/26ac03e2-e4b5-4fb0-89c6-4f9b8deef1f0">

**Expected behavior**
<img width="60" alt="Снимок экрана 2024-09-27 в 16 06 21" src="https://github.com/user-attachments/assets/154b2e73-d51e-406c-9c71-929e3670b36e">

**Desktop (please complete the following information):**
 - https://nightly.test.lifescience.opensource.epam.com/KetcherDemoSA/4984-highlight-atoms-and-bonds/index.html
 - Indigo Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-26; 16:27:32
 - MacOs

Issues found while testing https://github.com/epam/ketcher/issues/4984

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/ea0a3e30-1214-4bde-bf27-34ae2905f564)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
