### ISSUE TITLE
The double bond is not colored

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5598]
**Steps to Reproduce**
1. highlight double bound
2. choose highlight in the menu
3. click to one color

**Actual behavior**
<img width="125" alt="Снимок экрана 2024-09-27 в 16 14 45" src="https://github.com/user-attachments/assets/ff9269b3-5e9c-4018-a12a-84664e0ab2f3">

**Expected behavior**
Double bond should be completely colored

**Desktop (please complete the following information):**
 - https://nightly.test.lifescience.opensource.epam.com/KetcherDemoSA/4984-highlight-atoms-and-bonds/index.html
 - Indigo Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-26; 16:27:32
 - MacOs

Issues found while testing https://github.com/epam/ketcher/issues/4984

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/30d111a4-f6fb-414c-b3c4-d435dee1d637)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
