### ISSUE TITLE
[EPIC] Enhanced Stereochemistry

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#56]
**PART 1**
CREATE STEREO MARKS

1. The ‘Stereochemistry’ button is present at the Atom toolbar. 

2. User clicks the ‘Stereochemistry’ button, ‘Enhanced Stereochemistry’ window is opened.

When canvas is empty or the created structure is without a stereocenter or with non-tetrahedral stereochemistry nothing is happened, the ‘Enhanced Stereochemistry’ window doesn’t appear.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects the created structure, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user doesn’t select anything on canvas, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects the correct stereocenter, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects several correct stereocenters, the ‘Enhanced Stereochemistry’ window appears.
When the structure with the correct tetrahedral stereochemistry is present on canvas and user selects the part of the structure without stereocenter, the ‘Enhanced Stereochemistry’ window doesn’t appear.
When several structures with the correct tetrahedral stereochemistry are present on canvas and user selects several correct stereocenters of the different structures or parts with stereocenters of the different structures or several structures, the ‘Enhanced Stereochemistry’ window appears.

3. ‘Enhanced Stereochemistry’ window design:

‘Enhanced Stereochemistry’ title is present at the window header.
The stereochemistry settings are listed in the window:
• ABS
• Add to AND [  ] Group
• Add to OR [  ] Group
• Create new AND Group
• Create new OR Group

The radiobutton for each setting is present at the left side.
The fields for numbers entering are present for 'Add to AND [  ] Group' and 'Add to OR [  ] Group' settings. 'Add to AND [  ] Group' setting becomes available when at least one AND group has been created on the canvas. 'Add to OR [  ] Group' setting becomes available when at least one OR group has been created on the canvas. Only digital symbols are allowed for this fields!
'OK' and 'Cancel' buttons are present at the window bottom.

If one correct stereocenter is selected the appropriate radiobutton in the ‘Enhanced Stereochemistry’ window is checked (ABS/ Add to AND [N] Group/Add to OR [N] Group, where N is the number of a group)
If several stereocenters marked before are selected:
• All selected stereocenters have the same stereo mark, the appropriate radiobutton in the ‘Enhanced Stereochemistry’ window is checked.
• The selected stereocenters have different stereo marks, all radiobuttons in the ‘Enhanced Stereochemistry’ window are unchecked.

![image](https://user-images.githubusercontent.com/80695128/118953769-cb628900-b965-11eb-9a32-8b75124b2e02.png)

4. Assign the Stereo marks.
(Preconditions – IUPAC style of stereo labels display is selected. A structure with an absolute stereo configuration has been loaded or a new structure with the correct tetrahedral stereochemistry has been created. The structure has at least 3 stereocenters).

User selects one of the structure stereocenters, clicks ‘Stereochemistry’ button, 'ABS' radiobutton is checked by default. User chooses any unchecked radiobutton (e.g. 'Create new AND Group').
• Clicks the 'Cancel' button: ‘Enhanced Stereochemistry’ window is closed. No any stereo mark appears.
• Clicks the 'OK' button: ‘Enhanced Stereochemistry’ window is closed. &1 stereo mark appears below the selected stereocenter.
User selects another structure stereocenter, clicks ‘Stereochemistry’ button, chooses any unselected radiobutton, e.g. Add to AND [  ] Group, enters the number of a group ('1' in our example).
• Clicks the 'Cancel' button: ‘Enhanced Stereochemistry’ window is closed. No any stereo mark appears.
• Clicks the 'OK' button: ‘Enhanced Stereochemistry’ window is closed. ‘&1’ stereo mark appears below the selected stereocenter.

![image](https://user-images.githubusercontent.com/80695128/118662978-190db300-b7f9-11eb-8a84-2ae675199b68.png)

If several AND Groups/OR Groups have been already created user can assign a stereo mark by entering the number of one of the groups in the input field.
User selects a structure stereocenter, clicks ‘Stereochemistry’ button, chooses 'Add to AND [  ] Group' or 'Add to OR [  ] Group radiobutton.
• Enters or not the number of one of the created groups in the input field and clicks the 'Cancel' button: ‘Enhanced Stereochemistry’ window is closed. No any stereo mark appears.
• Enters the number of one of the created groups and clicks the 'OK' button: ‘Enhanced Stereochemistry’ window is closed. ‘&N’ or ‘orN’ stereo mark appears below the selected stereocenter (Where N is the number of the created group).
• Leaves the input field without changes. The 'OK' button is disabled. 
User selects the previously marked stereocenter (for example ‘&1’), clicks the ‘Stereochemistry’ button, chooses radiobutton for another stereo mark (e.g. 'ABS').
• Clicks the 'Cancel' button: the ‘Enhanced Stereochemistry’ window is closed. The previously marked stereocenter (for our example ‘&1’) is not changed.
• Clicks the 'OK' button: the ‘Enhanced Stereochemistry’ window is closed. The previously assigned stereo mark (for our example ‘&1’) disappear (as 'abs' stereo marks are not shown when IUPAC style of stereo labels display is selected).
User selects several previously marked stereocenters, clicks ‘Stereochemistry’ button, chooses any radiobutton, e.g. 'Create new OR Group'.
• Clicks the 'Cancel' button: ‘Enhanced Stereochemistry’ window is closed. All previously marked stereocenters have the initial marks.
• Clicks the 'OK' button: ‘Enhanced Stereochemistry’ window is closed. All previously marked stereocenters are replaced with the selected one (‘orN’ for our case).

5. Stereo Flags
• User creates a new structure with correct stereocenter. As soon as he adds the Stereo Bond to the stereocenter, no stereo mark appears below the stereocenter and no stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/80695128/118663088-32aefa80-b7f9-11eb-8e82-5c2747bea69b.png)

• User selects the stereocenter (or whole structure), clicks ‘Stereochemistry’ button - 'ABS' radiobutton is selected, chooses 'Create new AND Group' radiobutton and clicks the 'OK' button. No stereo mark appears below the stereocenter, the AND Enantiomer stereo flag appears above the structure at the right side.
• User selects the stereocenter (or whole structure), clicks ‘Stereochemistry’ button, chooses 'Create new OR Group' radiobutton and clicks the 'OK' button. No stereo mark appears below the stereocenter, the OR Enantiomer stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/80695128/118663613-7f92d100-b7f9-11eb-95ea-5706fb4e9cf9.png)

If the structure stereocenters have the different stereo marks, the MIXED stereo flag appears above the structure.
• User adds a new stereobond. As soon as he adds the Stereo Bond to the stereocenter, the ‘or1’ stereo mark appears below the previously created stereocenter, the MIXED stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/80695128/118663903-bbc63180-b7f9-11eb-98c2-fcc52fd76fd5.png)

If all structure stereocenters have the identical stereo marks, the appropriate stereo flag appears above the structure.
• User selects the newly created stereocenter, clicks the ‘Stereochemistry’ button, chooses 'Add to OR [1] radiobutton and clicks the 'OK' button. The stereo marks have disappeared, the OR Enantiomer stereo flag appears above the structure at the right side:

![image](https://user-images.githubusercontent.com/80695128/118664139-e6b08580-b7f9-11eb-960d-7bd65e45af56.png)

If several structures with the correct stereocenters are present on the canvas, each structure has the separate stereo flag (ABS (Chiral) flag is not shown).

![image](https://user-images.githubusercontent.com/80695128/118664268-0051cd00-b7fa-11eb-9e86-883187e3add2.png)

**PART 2**

SAVE and OPEN STRUCTURE with STEREO MARKS

1. Structure with Chiral Stereo flag

Structure with Chiral Stereo flag can be saved in both V2000 and V3000 file format.
• Mol file in V2000 format has the '1' in second string at the CTAB block:
Ketcher 10121612192D 1 1.00000 0.00000 0
9 8 0 1 0 999 V2000
• Mol file in V3000 format has the CFG value(s) near atom(s) (stereocenter) and near stereobond(s).

2. Structure with AND Enantiomer Stereo flag

Structure with AND Enantiomer Stereo flag can be saved in both V2000 and V3000 file format.
• Mol file in V2000 format has the '0' in second string at the CTAB block:
Ketcher 10121612192D 1 1.00000 0.00000 0
9 8 0 0 0 999 V2000
• Mol file in V3000 format has the CFG value(s) near atom(s) (stereocenter) and near stereobond(s).

3. Structure with OR Enantiomer Stereo flag

Structure with OR Enantiomer Stereo flag can be saved in V3000 file format only.
Mol file has
• the CFG value(s) near atom(s) (stereocenter) and near stereobond(s)and
• 'collection' at the CTAB end:
M V30 BEGIN COLLECTIONM V30 MDLV30/STEREL1 ATOMS=(1 9)
M V30 END COLLECTIONM V30 END CTAB

4. Structure with MIXED Stereo flag

Structure with MIXED Stereo flag can be saved in V3000 file format only.
Mol file has
• the CFG value(s) near atom(s) (stereocenter) and near stereobond(s)and
• 'collection' at the CTAB end:
M V30 BEGIN COLLECTIONM V30 MDLV30/STEABS ATOMS=(1 3)
M V30 MDLV30/STEREL1 ATOMS=(1 9)
M V30 MDLV30/STERAC1 ATOMS=(1 6)
M V30 END COLLECTIONM V30 END CTAB

Note
About the V3000 file format for the stereo structures you can read in the attached ctfile_2007.pdf file.

5. Open file with structure with Stereo flags

Any mol-file (V2000 or V3000) with structure(s) with Chiral (Absolute)/ AND Enantiomer/ OR Enantiomer/ Mixed Stereo flags and abs/&/or stereo marks should be opened without any problems.
All stereo marks and Stereo flags should be rendered correctly.

Molecule with some stereocenters, with no enhanced stereochemical labels but with Chiral flag (read from Molfile V2000) is equivalent (in terms of exact structure match) to molecule where all valid tetrahedral stereocenters belong to ABS stereogroup.
Molecule with some stereocenters, with no enhanced stereochemical labels and without Chiral flag (read from molfile V2000) is equivalent (in terms of exact structure match) to molecule where all valid tetrahedral stereocenters belong to the same AND stereogroup.
6. Open the saved in Ketcher file with structure with Stereo flags in other structure editors

Any saved in Ketcher mol-file (V2000 or V3000) with structure(s) with Chiral / AND Enantiomer/ OR Enantiomer/ Mixed Stereo flags and abs/&/or stereo marks should be opened in other structure editors (Marvin, ChemDraw, Biovia Draw) without any problems.
All stereo marks and Stereo flags should be rendered correctly.

**PART 3**

SETTINGS for the STEREO FLAGS and STEREO MARKS

In the ‘Settings’ user is able to specify the preferences for the rendering of the stereochemistry flags and labels.
• Colors:
• Color of Absolute Centers - Specifies the color in which the stereo bonds, stereogroup labels, or both are displayed at absolute stereogenic centers.
• Color of AND Centers - Specifies the color in which the stereo bonds, stereogroup labels, or both are displayed at AND stereogenic centers.
• Color of OR Centers - Specifies the color in which the stereo bonds, stereogroup labels, or both are displayed at OR stereogenic centers.
• Color stereogenic centers - Specifies how color is used with one of the following values:
• Labels only

![image](https://user-images.githubusercontent.com/7427808/95729701-e78ea100-0c85-11eb-808e-8b0110e2ccd4.png)

Note: in BIOVIA Draw the default colors for stereocenters are:

Absolute – Red;
AND – MediumBlue
OR – ForestGreen
The color for the next label (AND1, AND2, AND3 or OR1, OR2, OR3…) is a little lighter then for previous one.

![image](https://user-images.githubusercontent.com/7427808/95729749-faa17100-0c85-11eb-83e5-4e1d95fd1403.png)

• Label Display At Stereogenic Centers - Specifies how labels for stereogroups are displayed at individual tetrahedral stereogenic centers.

IUPAC Style (should be selected by default)
Classic
On
Off
The following table shows the four options:

![image](https://user-images.githubusercontent.com/7427808/95729817-1573e580-0c86-11eb-9cc3-aad9272bd744.png)

• User can change the text of the four Stereo flags as follows:

Text of Absolute flag – Set text of absolute chirality flag
Text of AND flag – Set text of AND chirality flag
Text of OR flag – Set text of OR chirality flag
Text of Mixed flag – Set text of Mixed chirality flag.
Note to hide the chirality flags, delete the text of the chirality flags.

• User can change the Font styles for the Stereo label and Stereo Flag texts.

**Comment by Svetlana-Asinovskaia** [comment]
The requirements have been partly changed. The new version of acceptance criteria №3, 4 is as follows:

3. ‘Enhanced Stereochemistry’ window design:
![2021-06-07_14h59_48](https://user-images.githubusercontent.com/80695128/121013667-cf820980-c7a1-11eb-8cd1-fc0e1e2bf565.png)
…The drop-down list fields with the numbers of the created groups are present for 'Add to AND [ ] Group' and 'Add to OR [ ] Group' settings. 'Add to AND [ ] Group' setting becomes available when at least one AND group has been created on the canvas. 'Add to OR [ ] Group' setting becomes available when at least one OR group has been created on the canvas….

4. ...User selects another structure stereocenter, clicks ‘Stereochemistry’ button, chooses any unselected radiobutton, e.g. Add to AND [ ] Group, selects the number of a group ('1' in our example)...
...If several AND Groups/OR Groups have been already created user can assign a stereo mark by selecting the number of one of the groups in the drop-down list fields...
...Selects the number of one of the created groups in the drop-down list field and clicks the 'Cancel' button: ‘Enhanced Stereochemistry’ window is closed. No any stereo mark appears.
• Selects the number of one of the created groups and clicks the 'OK' button: ‘Enhanced Stereochemistry’ window is closed. ‘&N’ or ‘orN’ stereo mark appears below the selected stereocenter (Where N is the number of the created group)…
