### ISSUE TITLE
Zoom in automatically upon import of small sequences

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5600]
**Background**

This ticket covers common user problem of loading a small sequence and having to zoom in every time in macromolecules mode. 

**Terms used**

Available space - The surface of the canvas where monomers get placed:
![image](https://github.com/user-attachments/assets/8c6c8137-2482-42d9-9970-4592afe0bd66)

**Requirement**

- When the canvas is empty (only in flex and snake modes), and the user imports any number of sequences/monomers that do not take up more than half of the available space, simultaneously with the layoting of the monomers zoom should be adjusted to 100% + n*10% (n=1,2,3,4,5,6,7,8,9,10) so that the sequence(s) take up at least half of the available space, or if that is not possible until zoom of 200%.

**Examples**

[Example 1](https://github.com/user-attachments/files/17164540/Example.1.zip) on 100% zoom:
![image](https://github.com/user-attachments/assets/287b033d-604a-44e9-9428-7b92fa3e8a21)
Example 1 on 110% zoom:
![image](https://github.com/user-attachments/assets/3cd0725d-47e2-4903-9951-40027bcc9a0e)

[Example 2](https://github.com/user-attachments/files/17164755/Example.2.zip) on 100% zoom:
![image](https://github.com/user-attachments/assets/87dff352-3330-47b0-b50e-cdc436c0b281)
Example 2 on 150% zoom:
![image](https://github.com/user-attachments/assets/dcdde784-5d03-4984-a45e-8cce25041727)

[Example 3](https://github.com/user-attachments/files/17164810/Example.3.zip) on 100% zoom:
![image](https://github.com/user-attachments/assets/8dfe3e4c-1227-4413-8993-09baff3b55cc)
Example 3 on 200% zoom (maximum zoom):
![image](https://github.com/user-attachments/assets/f204bf7a-5634-410e-a529-68f4778f7a79)

[Example 4](https://github.com/user-attachments/files/17166149/Example.4.zip) on 100% zoom (flex mode):
![image](https://github.com/user-attachments/assets/8c31ee68-6e45-41bb-96ab-2ab6a286597a)
No zooming in because even thought the sequences are small, collectively they take up more than half of the available space.

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10
