### ISSUE TITLE
The attachment points aren't colored

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5605]
**Steps to Reproduce**
1. add ring to the Canvas
2. add attachment point by left panel

<img width="340" alt="Снимок экрана 2024-09-30 в 11 07 32" src="https://github.com/user-attachments/assets/2a273913-a5c5-4b4f-967a-4c859078c9e9">

<img width="241" alt="Снимок экрана 2024-09-30 в 11 08 03" src="https://github.com/user-attachments/assets/69845851-dca9-4fa4-86cc-c4f958c02774">

3. click on right mouse button

**Actual behavior**
there is no Highlight option
<img width="258" alt="Снимок экрана 2024-09-30 в 11 09 03" src="https://github.com/user-attachments/assets/e8a2da69-c34b-43c4-95cb-fb5ff3db9130">
___________________________________________________________________________________
1. add attachment point
<img width="142" alt="Screenshot 2024-10-02 at 12 07 48" src="https://github.com/user-attachments/assets/c2827486-347f-4bdc-9362-f6c625119fe5">

2. click on right mouse button

**Actual behavior**
there is no Highlight option
<img width="337" alt="Screenshot 2024-10-02 at 12 08 24" src="https://github.com/user-attachments/assets/cf9939d5-4910-457c-ab68-e84c7eb5f5f2">

**Expected behavior**
there is Highlight option

**Desktop (please complete the following information):**
 - https://nightly.test.lifescience.opensource.epam.com/KetcherDemoSA/4984-highlight-atoms-and-bonds/index.html
 - Indigo Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-26; 16:27:32
 - MacOs

Issues found while testing https://github.com/epam/ketcher/issues/4984

**Comment by AnnaKosol** [comment]
It is necessary to clarify the requirements

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/69359f2f-5ad4-4408-bdd3-59bc042149dc)
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10
