### ISSUE TITLE
Single up bond is being painted over incorrectly

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5606]
**Steps to Reproduce**
1. click on a single up bond
2. choose highlight in the menu
3. click to one color

**Actual behavior**
single up bond is not completely painted over
<img width="134" alt="Снимок экрана 2024-09-30 в 11 15 32" src="https://github.com/user-attachments/assets/36eab81b-1d89-4dcc-84e0-5958b11df3a3">

**Expected behavior**
single up bond is completely painted over

**Desktop (please complete the following information):**
 - https://nightly.test.lifescience.opensource.epam.com/KetcherDemoSA/4984-highlight-atoms-and-bonds/index.html
 - Indigo Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-26; 16:27:32
 - MacOs

Issues found while testing https://github.com/epam/ketcher/issues/4984

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/7573fbed-86dc-4d2c-a545-ed5707e080b7)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
