### ISSUE TITLE
The file size is the same when saved to png

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5612]
**Steps to Reproduce**
1. add a benzene ring
2. set low resolution in the Settings
3. save to png (svg)
4. set high resolution in the Settings
5. save to png (svg)

**Expected behavior**
the file size should be different depending on the low and high resolution

**Actual behavior**
the file size is the same
<img width="574" alt="Screenshot 2024-09-30 at 17 15 08" src="https://github.com/user-attachments/assets/0ab4d1af-42a2-4253-9424-7337ad30b9bd">

**Environment details:**
 - https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
 - Indigo branch 2175-acs-style-rendering
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AlexeyGirin** [comment]
Not fixed.
Put on the canvas following 4k png wallpaper.
Save to PNG with low and with high resolution - both files are identical

**Comment by AlexeyGirin** [comment]
Fixed.
