### ISSUE TITLE
Ketcher doesn't trigger change event in macromolecule mode

### ISSUE THREAD

**Issue by MariaDolotova** [epam/ketcher#5618]
How can I subscribe to Ketcher change event when using macromolecule mode.
I have used the demo stand, tried to subscribe to 'change', but it didn't work. 
Please see the gif below.

![ketcher_macromolecule_mode_change_event](https://github.com/user-attachments/assets/03ddc795-fd0a-40bb-97ae-fd4ac2c117fb)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/c6285c1e-6f4f-4b43-995c-50fed95ad5fb



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
