### ISSUE TITLE
O and U sumbols are not supported in sequence mode

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5621]
**Steps to Reproduce**
1. Toggle to Macro - Sequence mode
2. Start new sequence
3. Type `OU`

**Actual behavior**
Canvas is empty
![image](https://github.com/user-attachments/assets/c444bb47-5b67-45d0-ad0c-58b614e101c4)

**Expected behavior**
`OU` appeared on the canvas
![image](https://github.com/user-attachments/assets/f14e25bb-f25d-407c-8154-b051b8712c88)

Investigation:
1. Where was no task for peptide support in sequence mode (in road map - no ticket id)
2. O and U symbols haven't been supported because we didn't have such peptides in the Library
3.  Others symbols have been supported in the context of import/export to FASTA/Sequence
4. And O symbol was missed even there - https://github.com/epam/Indigo/issues/1755#issuecomment-1972978475

**Versions**
- Ketcher Version 2.25.0-rc.4 Build at 2024-09-23; 17:24:38
- Indigo Toolkit Version 1.24.0-rc.3.0-g692080c62-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.59 (Official Build) (64-bit)
- Win10

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-10-15_17h51_48](https://github.com/user-attachments/assets/243e64b4-b941-4b47-b28b-f741b60db0e2)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.2]
**Indigo version** 
[Version 1.25.0-rc.2]
