### ISSUE TITLE
Bond spacing is incorrect after saving in PNG (svg)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5628]
**Steps to Reproduce**
1. add benzene ring
2. set bond length 50 px in the Settings on the Bond section
3. set bond spacing 50%
4. click on Apply button
5. save to the png
6. open saving file

**Expected behavior**
the picture should be as on the Canvas and saving preview
![Screenshot 2024-09-30 at 17 21 59](https://github.com/user-attachments/assets/ff188ce4-bd07-40ab-8882-cf32934b5e36)

**Actual behavior**
![png low](https://github.com/user-attachments/assets/d5e1be42-9feb-4fb6-8e0f-d35cda68a582)

**Environment details:**
 - https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
 - Indigo branch 2175-acs-style-rendering
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AliaksandrDziarkach** [comment]
Ketcher send ACS options to generate preview but not send when  "Save" pressed:
For preview:
![image](https://github.com/user-attachments/assets/92e04610-f897-43ca-834d-3ed934e3aae7)
After "Save" pressed:
![image](https://github.com/user-attachments/assets/bfd3ada6-a678-426f-a380-1c1e5d280939)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/e3761f7b-a172-4982-a07f-f3cb296de9b3)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
