### ISSUE TITLE
Mark modified amino acids on canvas in sequence mode

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5629]
**Background**
In sequence mode, nucleotides with modified sugars/bases and phosphates are marked in some way (issue introducing this functionality: [#3734](https://github.com/epam/ketcher/issues/3734)). Modified amino acids are not marked in any way.

**Requirement**
- Bellow is a list of `non-modified` amino acids. Any other amino acid in sequence mode should be marked (see mockup)

| Name (Symbol) | Note | Name (Symbol) | Note | 
| --- | --- | --- | --- |
| Alanine (A) | | Asparagine (N) | |
| (B) | Ambiguous amino acid from the library | Pyrrolysine (O) | |
| Cysteine (C) | | Proline (P) | |
| Aspartic acid (D) | | Glutamine (Q) | |
| Aspartic acid* (D*) | Same monomer, different R3 | Arginine (R) | |
| Glutamic acid (E) | | Serine (S) | |
| Phenylalanine (F) | | Threonine (T) | |
| Glycine (G) | | Selenocysteine (U) | |
| Histidine (H) | | Valine (V) | |
| Isoleucine (I) | | Tryptophan (W) | |
| (J) | Ambiguous amino acid from the library | (X) | Ambiguous amino acid from the library | 
| Lysine (K) | | Tyrosine (Y) | |
| Leucine (L) | | (Z) | Ambiguous amino acid from the library | 
Methionine (M) | | | |

**UX**
![image](https://github.com/user-attachments/assets/a9de26ef-a5cd-45fe-beb5-b0c5fd6b0282)

**Comment by Zhirnoff** [comment]
Tested. All non-modified amino acids not marked except D* We have bug https://github.com/epam/ketcher/issues/6053

![2024-12-06_15h41_16](https://github.com/user-attachments/assets/40aff2b6-18c4-452c-a0a5-ecfd3d283ded)
![2024-12-06_15h43_06](https://github.com/user-attachments/assets/eee58f67-9b53-43e0-888f-67f6270f0f20)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
