### ISSUE TITLE
Mark all modified monomers on canvas (flex and snake modes)

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5630]
**Background**
Especially on a crowded canvas, modified monomers are not that easy to find. Introducing marked monomers on canvas can more easily draw the attention of the user to them. 

**Requirement**
- Every modified amino acid, sugar, base and phosphate on canvas (flex and snake modes) should be marked as modified (see mockup).
> Only amino acids, sugars, phosphates and bases can be considered modified. That means that there is no need for marking CHEMs, (unsplit) nucleotides, and unresolved nucleotides.
> The list of non-modified amino acids can be found here: [#5629](https://github.com/epam/ketcher/issues/5629), and the list of non-modified bases, sugars and phosphates here: [#3734](https://github.com/epam/ketcher/issues/3734)

**UX**
![image](https://github.com/user-attachments/assets/027dceaf-57c2-476c-ada7-26f55278981b)

![image](https://github.com/user-attachments/assets/b093e685-de28-400c-8fc3-008ab9846e7b)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/6eb144d6-651a-4e17-ad76-d749770c1fe6)
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10
