### ISSUE TITLE
ketcher.getMolfile() stopped working for macro canvas with peptides

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5634]
**Steps to Reproduce**
1. Go to Macro - Snake mode
2. Load from file: [snake-mode-peptides.zip](https://github.com/user-attachments/files/17245579/snake-mode-peptides.zip)
![image](https://github.com/user-attachments/assets/75bcfabb-7b34-488b-805e-cafcc8df35ac)
3. Open console and run: `ketcher.getMolfile()`

**Actual behavior**
System throws exception
![image](https://github.com/user-attachments/assets/0c4ec199-2424-44a5-aa34-f85cb617098d)
[localhost-1727965119555.log](https://github.com/user-attachments/files/17245604/localhost-1727965119555.log)

**Expected behavior**
No exception.
[snake-mode-peptides-expected.zip](https://github.com/user-attachments/files/17245614/snake-mode-peptides-expected.zip)

**Versions**
- Ketcher Version 2.25.0-rc.2 Build at 2024-10-03; 12:06:08
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-10-15_15h54_58](https://github.com/user-attachments/assets/6dcb23f7-e3f9-450b-906c-a2c6c5ebe454)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.2]
**Indigo version** 
[Version 1.25.0-rc.2]
