### ISSUE TITLE
The options for layout about smart-layout, aromatize-skip-superatoms and etc is sent as undefined

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5635]
**Steps to Reproduce**
1. Add to the Canvas
C1CC=CC=CC=CCC=CC=CC=CCC=CC=C1 |c:2,11,16,t:4,6,9,13,18|
(file is from auto test File-Management/Smile-Files/smile-files.spec.ts:237)

**Actual behavior**
![Screenshot 2024-10-03 at 15 36 59](https://github.com/user-attachments/assets/ddd3f94e-ef46-4b4a-9395-1793b9e78db2)

**Expected behavior**
![Screenshot 2024-10-03 at 15 36 49](https://github.com/user-attachments/assets/2efecba9-c8d3-459b-bb5d-f1181cc6aef5)

It happened because of Ketcher send options as undefined
![Screenshot 2024-10-03 at 16 19 49](https://github.com/user-attachments/assets/e6852ddb-07e3-41c6-a2d0-f17d46aad567)

Before it was
![Screenshot 2024-10-03 at 16 21 28](https://github.com/user-attachments/assets/d28be279-22c6-4690-be3b-4c8e123723ab)

The same situation with Aromatize.

(the file is from auto test File-Management/Smile-Files/smile-files.spec.ts:183)

**Actual behavior**
![Screenshot 2024-10-03 at 15 32 17](https://github.com/user-attachments/assets/083b1b33-e97d-4c0f-a7b7-02d24d8fe0e5)

**Expected behavior**
![Screenshot 2024-10-03 at 15 32 30](https://github.com/user-attachments/assets/d2e26f92-b7f2-467d-a2d4-c6740ad16248)

**Environment details:**
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- MacOs 15
- Version 129.0.6668.71 (Official Build) (arm64)

**Comment by AlexeyGirin** [comment]
Fixed.
Test at smile-files.spec.ts:183 passes now

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/046b240c-0346-48d6-aba5-87439c94badc)

- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10
