### ISSUE TITLE
Display hydrogen in atom label for molecules in macromolecules mode

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#5637]
**Background**
Currently labels for molecules atoms do not contain hydrogens as it is done in molecules mode.

Molecules mode: 
<img width="507" alt="image" src="https://github.com/user-attachments/assets/a500acb5-729a-4696-96f6-4447709c2ab3">

Macromolecules mode:
<img width="409" alt="image" src="https://github.com/user-attachments/assets/65456ddb-871f-4b84-97a9-885fed250c58">

**Solution**
It needs to apply same rules for hydrogens in atom labels as in molecules mode.
Rules:
TBD

**Comment by Zhirnoff** [comment]
Tested.

![2024-11-06_15h53_15](https://github.com/user-attachments/assets/ca6ae321-0f6f-4317-be11-84fcd1596626)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
