### ISSUE TITLE
Expand multiple monomers in micromolecules mode

### ISSUE THREAD

**Issue by svvald** [epam/ketcher#5640]
**Background**

**Solution**

**Alternatives**

**Additional context**

**Comment by Zhirnoff** [comment]
Tested. In Chain structures, after expand and collapse, the monomers are shifted. There is a bug for this https://github.com/epam/ketcher/issues/5670

https://github.com/user-attachments/assets/436ab7da-2292-4294-806e-4daeef29ee10



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
