### ISSUE TITLE
Default values for bond settings (at least for bond) got corrupted and become wrong after ver 2.26 version installed

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5649]
**Steps to Reproduce**
1. Go to Micromolecules mode
2. Go to Setting - Bond section

**Actual behavior**
Values for bond settings (at least for bond) are frong
![image](https://github.com/user-attachments/assets/f11acb56-658c-467b-9806-4cc068a40fdc)

**Expected behavior**
Values are correct
![image](https://github.com/user-attachments/assets/a3bd9519-8065-487d-b198-dd98f789847e)

**Versions**
- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-10-21_19h47_44](https://github.com/user-attachments/assets/e76b1822-7aaa-436e-a0e5-0a0b38bf4e75)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.5]
**Indigo version** 
[Version 1.25.0-rc.3]
