### ISSUE TITLE
The reaction can't save to MDL RXN V3000 (returns RXN V2000 instead)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5651]
Reproduced on 2.26
As per @AliaksandrDziarkach this is because Ketcher doesn't pass version to Indigo

**Steps to Reproduce**
1. Add reaction to the Canvas
[The reaction can't save to MDL RXN V3000 .ket.zip](https://github.com/user-attachments/files/17243981/The.reaction.can.t.save.to.MDL.RXN.V3000.ket.zip)
<img width="549" alt="Screenshot 2024-10-03 at 14 18 59" src="https://github.com/user-attachments/assets/5b204018-7b74-4e63-9c8a-c867949ccffb">

2. save to MDL RXN V3000 

**Actual behavior**
file is saved as V2000
<img width="654" alt="Screenshot 2024-10-03 at 14 21 29" src="https://github.com/user-attachments/assets/2ef4e729-86e7-459c-af2c-bc7d563d29d7">
[RXNActualResult.zip](https://github.com/user-attachments/files/17244650/RXNActualResult.zip)

**Expected behavior**
file is saved as V3000
![image](https://github.com/user-attachments/assets/6822f545-72e1-400f-b699-a47729832b79)
[RXNExpectedResult.zip](https://github.com/user-attachments/files/17244632/RXNExpectedResult.zip)

**Environment details:**
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
 - MacOs 15
 - Version 129.0.6668.71 (Official Build) (arm64)

**Comment by ivanmaslow** [comment]
Please, pay attention, that we have the same problem for RDF V3000, it should be fixed as well:
![image](https://github.com/user-attachments/assets/87843720-1ebe-4971-853d-60d2c22469d4)

**Environment Details:**
- Ketcher [Version 2.26.0-rc.1] Build at 2024-10-04; 18:45:04
- Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/c231ea9d-e2f9-4347-9a3a-8525bcff86d8)
![image](https://github.com/user-attachments/assets/3e0cd7f3-63c7-4fb3-b727-3434a3d356c0)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
