### ISSUE TITLE
Export to SDF V3000 returns SDF V2000

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5652]
Reproduced on 2.26
As per @AliaksandrDziarkach this is because Ketcher doesn't pass version to Indigo

**Steps to Reproduce**
1. Toggle to Macro - Flex
2. Load from file: [one-attachment-point-added-in-micro-mode.zip](https://github.com/user-attachments/files/17244364/one-attachment-point-added-in-micro-mode.zip)
![image](https://github.com/user-attachments/assets/3b51e173-846a-44b7-a6eb-dcce3f6bd8a3)
3. Export canvas to SDF V3000

**Actual behavior**
System returns content in SDF V2000 format
![image](https://github.com/user-attachments/assets/fe8335a5-1810-4991-b91c-59a6f8eebb40)
[ActualResult.zip](https://github.com/user-attachments/files/17244432/ActualResult.zip)

**Expected behavior**
System returns content in SDF V3000 format
![image](https://github.com/user-attachments/assets/6a2981cf-db19-4d18-b330-04432400e201)
[ExpectedResult.zip](https://github.com/user-attachments/files/17244431/ExpectedResult.zip)

**Versions**
- Ketcher Version 2.25.0-rc.2 Build at 2024-10-03; 12:06:08
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10

**Comment by ivanmaslow** [comment]
Please, pay attention, that we have the same problem for RDF V3000:
![image](https://github.com/user-attachments/assets/87843720-1ebe-4971-853d-60d2c22469d4)

**Environment Details:**
- Ketcher [Version 2.26.0-rc.1] Build at 2024-10-04; 18:45:04
- Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/6640721b-1845-43a7-8afb-ba8b7d28bb21)

- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
