### ISSUE TITLE
The reaction can't save to MOL V3000 (returns MOL V2000 instead)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5653]
Reproduced on 2.26
As per @AliaksandrDziarkach this is because Ketcher doesn't pass version to Indigo

**Steps to Reproduce**
1. Add to the Canvas a molecule
`CC(=O)O[C@@H](C)[C@H](O)Cn1cnc2c1ncnc2N`
2. save to MOL V3000

**Actual behavior**
returns MOL V2000 instead
<img width="529" alt="Screenshot 2024-10-04 at 08 25 06" src="https://github.com/user-attachments/assets/cc77f25d-6db1-413b-9a73-0ef558d24306">
[The reaction can't save to MOL V3000 actual.mol.zip](https://github.com/user-attachments/files/17254264/The.reaction.can.t.save.to.MOL.V3000.actual.mol.zip)

**Expected behavior**
The file saves to MOL V3000 format
[The reaction can't save to MOL V3000 expected.mol.zip](https://github.com/user-attachments/files/17254265/The.reaction.can.t.save.to.MOL.V3000.expected.mol.zip)
<img width="495" alt="Screenshot 2024-10-04 at 08 27 02" src="https://github.com/user-attachments/assets/133eec70-4e23-4857-b65d-ba211aabb31f">

**Environment details:**
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- MacOs 15
- Version 129.0.6668.71 (Official Build) (arm64)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/404589be-d9fe-4f6a-a81f-dc89b83f0218)

- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
