### ISSUE TITLE
Only bonds is highlighted when the whole molecule with atoms is choosen

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5668]
**Steps to Reproduce**
1. add the molecule to the Canvas
<img width="128" alt="Screenshot 2024-10-07 at 15 34 21" src="https://github.com/user-attachments/assets/a5243d8f-4acb-47a1-b034-cdb6c85c46e6">

2. choose the whole molecule
<img width="157" alt="Screenshot 2024-10-07 at 15 41 21" src="https://github.com/user-attachments/assets/2f00014e-91f3-4a56-bd8b-f8745de90412">

3. open highlight menu and choose color
<img width="605" alt="Screenshot 2024-10-07 at 15 42 26" src="https://github.com/user-attachments/assets/17302ded-2827-4286-8582-869bea216d45">

**Actual behavior**
only bonds are highlighted
<img width="130" alt="Screenshot 2024-10-07 at 15 43 13" src="https://github.com/user-attachments/assets/83818507-e4b5-41fa-87ec-686722e230e1">

**Expected behavior**
the whole molecule is highlighted

**Environment**
 - Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- MacOs
- Chrome 129.0.6668.71 (Official Build) (arm64)

Issue found while testing https://github.com/epam/ketcher/issues/4984

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-10-21_19h11_05](https://github.com/user-attachments/assets/cf16f812-2189-4039-8708-afadf1f70805)
![2024-10-21_19h11_25](https://github.com/user-attachments/assets/aeca9167-765e-4756-96d4-68e8541d61de)
![2024-10-21_19h11_57](https://github.com/user-attachments/assets/5fec90c4-f4a4-4918-ac16-bd7a285a53ca)
![2024-10-21_19h12_11](https://github.com/user-attachments/assets/4e1022d8-c4b6-4b6e-8246-634181a681cf)
![2024-10-21_19h12_36](https://github.com/user-attachments/assets/aad22108-417b-4b74-85b0-f6e57f35234f)
![2024-10-21_19h13_02](https://github.com/user-attachments/assets/be1471ec-eca4-4ab8-bbd9-dab0dc5fddac)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.5]
**Indigo version** 
[Version 1.25.0-rc.3]
