### ISSUE TITLE
Holding CTRL and clicking on an atom or bond creates multiple duplicated structures until clicking on canvas, with console errors

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#5672]
**Steps to Reproduce**
1. Open Ketcher and draw a chemical structure on canvas ( e.g. Benzene ring and Chain )
2. Hold down the "Ctrl" key and click on any atom or bond
3. Release left mouse button and without releasing "CTRL," continue moving mouse
4. Observe the behavior of structures on canvas

**Actual behavior**
Holding CTRL and clicking on an atom or bond creates multiple duplicated structures until clicking on canvas, with console errors

https://github.com/user-attachments/assets/46d590ea-d061-4cc9-bff4-f47f3d98a427

**Expected behavior**
On Prod, when CTRL was pressed, the entire structure was highlighted on hover and when clicking on an atom or bond, it was all structure selected

https://github.com/user-attachments/assets/1a3bf9a0-e880-43e2-8d2a-46edb26c7cd6

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]

Bug related to: https://github.com/epam/ketcher/issues/4986

**Comment by aproskurnov** [comment]
Regarding the second part of issue, because of new functionality for "ctrl" + click event, previous functionality has been moved to "alt" button.
First part would be fixed in PR

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/c900c6db-2e92-4fdd-8d43-ba683cb7a971



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.2]
**Indigo version** 
[Version 1.25.0-rc.2]
