### ISSUE TITLE
Introduce creating antisense chains

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5678]
## Theoretical background - What are antisense chains?

The central dogma of molecular biology states that the genetic information inside the cell flows in one direction: information stored within DNA gets transcribed to (messenger)RNA, and then the information within RNA gets translated to proteins.

DNA is technically two molecules (two chains) who wind around each other making the double helix shape DNA is known for. Every adenine on one chain will have a thymine "neighbor" on the other chain, and they will be strongly connected via hydrogen bonds. Same goes for cytosine and guanine. These two DNA chains are complementary - knowing the structure of one chain tells us the structure of the other; AND they are very tightly bond to each other.

During the process of transcription (making RNA from DNA), only one side/chain of DNA carries the information relevant for that particular gene. The information stored on it "makes sense" - the chain is `sense`. The other chain, the one whose information "does not make sense", is called `antisense`. The antisense chain is a template for creation of RNA - the created RNA will be identical to the sense DNA (with the known exceptions - deoxyribose will be replaced with ribose and thymine will be replaced with uracil).  And just like the antisense chain is complementary to the sense chain, it is also complementary to the new RNA.

So, why in this ticked are our antisense chains RNA and not DNA? And what is the usefulness of RNA antisense chains?
RNA is chosen over DNA for many reasons, main ones being RNAs versatility - you can modify RNA more/more easily; and the fact that RNA/RNA is bound stronger than RNA/DNA.
As mentioned before, the information stored on the (messenger)RNA goes on to produce proteins. If those proteins are harmful to the organism (genetic mutation/hereditary disease), antisense oligonucleotides (ASOs) can be used to bind to the RNA and stop it from making the harmful proteins. Some diseases where ASOs can be used are: cystic fibrosis, Huntington's disease, sickle cell anemia, Alzheimer's disease, etc.

## Complementary bases
| Sense base | Antisense base |
| --- | --- |
| Adenine, and all other bases with natural analogue A | T (thymine) |
| Cytosine, and all other bases with natural analogue C | G (guanine) |
| Guanine, and all other bases with natural analogue G | C (cytosine) |
| Thymine, and all other bases with natural analogue T | A (adenine) |
| Uracil, and all other bases with natural analogue U | A (adenine) |
| N (ambiguous DNA base) and N (ambiguous RNA base) | N (ambiguous RNA base) |
| B (ambiguous DNA base) and B (ambiguous RNA base) | V (ambiguous base) |
| D (ambiguous DNA base) and D (ambiguous RNA base) | H (ambiguous RNA base) |
| H (ambiguous DNA base) and H (ambiguous RNA base) | D (ambiguous RNA base) |
| K (ambiguous DNA base) and K (ambiguous RNA base) | M (ambiguous base) |
| W (ambiguous DNA base) and W (ambiguous RNA base) | W (ambiguous RNA base) |
| Y (ambiguous DNA base) and Y (ambiguous RNA base) | R (ambiguous base) |
| M (ambiguous base) | K (ambiguous RNA base) |
| R (ambiguous base) | Y (ambiguous RNA base) |
| S (ambiguous base) | S (ambiguous base) |
| V (ambiguous base) | B (ambiguous RNA base) |

## Requirements

1. When the user selects (flex and snake modes) any backbone chain (only R1-R2 connections) or any part of the backbone chain, right clicking anywhere on the selected monomers should give a drop-down menu with to option to "Create Antisense Strand", as long as one of the monomers in the backbone is a sugar connected to a "sense base" (R3-R1) (see table above).

> Valid selection (includes three sugars connected via a R3-R1 to a base - a nucleoside and two nucleotides):
> ![image](https://github.com/user-attachments/assets/5fcc401a-432f-43fc-8be4-eb501e4f41a9)
> Next two selections are equivalent to the first (the only important thing for the selection is the backbone):
> ![image](https://github.com/user-attachments/assets/9e13e120-6183-4c77-b614-81e936a7a8f6)
> ![image](https://github.com/user-attachments/assets/4943e0f1-0855-4824-aaef-64b2c3087a82)
> Valid selection (contains one nucleoside):
> ![image](https://github.com/user-attachments/assets/72257009-f053-439b-a1b5-6dd2508638d0)
> Invalid selection:
> ![image](https://github.com/user-attachments/assets/1c90e160-abfb-4af7-8d83-bb42f02c640c)

1.1. If there is a sugar in the backbone and it is connected to the a base via R3-R1, but the base is not a "sense base" form the table above, the "Create Antisense Strand" option should appear, but be disabled.
> For example, bases with natural analogue X from the library, or ambiguous bases not in the library.

1.2. If any of the bases connected to the sugars via R3-R1 have more bonds (hydrogen or covalent), the "Create Antisense Strand" option should appear, but be disabled.
> If a base has a bond with something in addition to the sugar, it will not be able to form hydrogen bonds with the antisense strand.
> Bases with more than one AP: nC6n8A, nC6n5C, oC64m5, nC6n2G, nC65U, nC6n5U

1.3. If multiple chains are selected and more than one satisfies the previous requirements, the "Create Antisense Strand" option should appear, and if clicked, multiple antisense chains are created.
> This is a selection of one chain (only one chain has R3-R1 sugar-base, the peptides from the chain above should be ignored when the antisense chain gets made):
> ![image](https://github.com/user-attachments/assets/1036b767-cfba-4644-a560-9d1ae06b6ea3)
> This is a selection of two chains (both chains contain R3-R1 sugar-base, peptides should be copied into the first antisense chain because they are the part of the backbone of the first chain):
> ![image](https://github.com/user-attachments/assets/649c37d4-f3cc-4efb-acee-374855d961e2)

2. When "Create Antisense Strand" is selected, an antisense strand is created following the logic:

2.1. All non R1-R2 connections of backbone monomers (except R3-R1 for sugar and base!!!) are ignored.
> ![image](https://github.com/user-attachments/assets/a0b5d7c8-7a3d-4cba-b3e5-9da39e1154c5)
> Only sugar with more than 3 APs: nC62r, and only phosphate with more than 2 APs: Test-6-Ph

2.2. Every nucleotide (sugar and phosphate are part of the backbone and connected via R2(s)-R1(p), and the sugar is connected to a "sense base" via R3(s)-R1(b)) should transform into a nucleotide on the antisense chain that contains ribose (R), phosphate (P), and the appropriate "antisense base".

2.3. Every nucleoside (not a nucleotide, sugar is connected through R2 to something that is not phosphate, or has a free R2, but is connected to a "sense base" through R3) should transform into a nucleoside on the antisense chain that contains ribose (R) and the appropriate "antisense base".

2.4. All other monomers in the backbone that are not a part of the nucleotide or a nucleoside should be directly copied to the antisense strand.

2.5. Every "sense base" that is connected to a sugar via R3-R1 from the original chain should have a hydrogen bond with the appropriate "antisense base" from the antisense chain.

2.6. Upon the creation of the antisense chain, both the sense and antisense chains get layouted.
> Layouting logic described in ticket: [#5712](https://github.com/epam/ketcher/issues/5712)

2.7. The antisense chain should be "flipped" in relation to the sense chain (see mockups) - bases of the new chain should be oriented in the opposite way, terminal indicators of the left-most sugar (associated with the base of a highest number) should be changed from `5'` to `3'` (or opposite) and/or of the left most amino acid from `N` to `C` (or opposite), and the numbering should go in the opposite direction.
> If the sense chain was oriented bases down, the antisense chain should be oriented bases up.
> If the sense chain was oriented bases up, the antisense chain should be oriented bases down.
> If the left most sugar/amino acid of the sense chain has a terminal indicator of `5'`/`N`, then the left most sugar/amino acid of the antisense chain should have a terminal indicator of `3'`/`C`.
> If the left most sugar/amino acid of the sense chain has a terminal indicator of `3'`/`C`, then the left most sugar/amino acid of the antisense chain should have a terminal indicator of `5'`/`N`.
> If the numbering of the sense chain increases from left to right, the numbering of the antisense chain should increase right to left.
> If the numbering of the sense chain increases from right to left, the numbering of the antisense chain should increase left to right.

3. Options "Delete" and "Copy" should also be added to the r-click menu.
3.1. Option "Delete" deletes the selected monomers and all the bonds of those monomers.
3.2. Option "Copy" copies the selected monomers and any bonds between them as the  default format (KET files in macromolecules mode, Mol V3000 is molecules mode).

## UX
![image](https://github.com/user-attachments/assets/32f8af64-729d-4ad4-bfd8-87d6f2651871)
![sequence mode](https://github.com/user-attachments/assets/f9538601-e7b1-4fe9-b041-0cbfd22d91f1)

More covered in the related issue: [#5712](https://github.com/epam/ketcher/issues/5712)

### Example 1:
![image](https://github.com/user-attachments/assets/abd5e553-876a-49da-b5ef-e30a2721cee4)

### Example 2:
Original chain:
![image](https://github.com/user-attachments/assets/f5c2a955-05f9-4379-b801-d39a377c1ef0)
After selecting the whole chain and creating the antisense:
![image](https://github.com/user-attachments/assets/654d25e9-608f-4ad0-abdf-615ba110e134)
**Note: for A in a sense chain, T should be added, not U**

**Comment by Zhirnoff** [comment]
@rrodionov91 Please add a test-id to new right-click buttons during the development phase, if possible. This will make automation easier for us.

**Comment by AlexeyGirin** [comment]
Verified with issues.
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10
