### ISSUE TITLE
Representation of Stereo Flags

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#57]
**The following behavior should be implemented to Stereo Flags:**

1. As soon as correct stereocenter appears on canvas, Stereo Flag should appear above the structure at the right side. 
![StereoFlags1](https://user-images.githubusercontent.com/14963002/95749436-3fd49b80-0ca4-11eb-9b3e-ea6715aa191e.jpg)
2. ~~Stereo Flags should't appear for structures without correct stereocenters, for example~~:
![StereoFlags2](https://user-images.githubusercontent.com/14963002/95749451-4531e600-0ca4-11eb-928a-98b71e16390d.jpg)
3. ~~User should be able to move Stereo Flag to any place on canvas, using any Selection Tool.~~
4. Stereo Flag shouldn’t be overlapped with the structure.
5. User should not be able to delete Stereo Flags, using 'Erase' button or 'Delete' button on keyboard.
6. Stereo Flags for reactions. When reagents and products have stereocenters, Stereo Flags should appear above the corresponding structures at the right side of each structure having stereocenter. See the example:  
![StereoFlags3](https://user-images.githubusercontent.com/14963002/95749468-495e0380-0ca4-11eb-9f78-c6bc11798506.jpg)
7. Stereo Flags that were saved in reactions should be rendered correctly. See the example of incorrect rendering Stereo Flags.
![StereoFlags4](https://user-images.githubusercontent.com/14963002/95749482-4e22b780-0ca4-11eb-809f-4dff29ced793.jpg)
Epic link: #56

**Comment by ensemenova** [comment]
After discussion with @AlexanderSavelyev point 2 was separated to new issue https://github.com/epam/ketcher/issues/418

**Comment by Svetlana-Asinovskaia** [comment]
1. The problem with incorrect rendering of Stereo Flags in reactions is still reproduced and it was described in the comments for the issue #58. 
2. User is not able to delete Stereo Flags, using the 'Erase' tool or the 'Delete' button on a keyboard.
![2021-05-13_16h13_47](https://user-images.githubusercontent.com/80695128/118130650-47108300-b406-11eb-96e1-13552f32fecf.gif)

**Comment by AndreiMazol** [comment]
AC #2 will be implemented in scope of another issue with detailed description.

**Comment by AndreiMazol** [comment]
All ACs have been implemented in  scope of other issues.

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is verified and closed. The problem with overlapping the stereo flags in the cyclic structures is OOS and will be fixed in https://github.com/epam/ketcher/issues/559
![image](https://user-images.githubusercontent.com/80695128/121356058-30901580-c939-11eb-920f-b4fe7c58d829.png)
