### ISSUE TITLE
The picture is incorrect when image resolution high and bond thickness changing

### ISSUE THREAD

**Issue by AnnaKosol** [epam/ketcher#5703]
**Summary**
Regarding https://github.com/epam/ketcher/issues/5610 the options were deleted from request Render on Ketcher site.
<img width="722" alt="Screenshot 2024-10-08 at 11 35 44" src="https://github.com/user-attachments/assets/3d7db449-cab1-4481-a76c-456881d7b79d">

However, the issue is reproduced soon.

**Steps to Reproduce**
1. add benzene ring to the Canvas
2. set image resolution High in the Settings
3. set bond thickness 2.6 pt in the Settings in the Bond section
4. click on Apply button
5. save to png (or svg)

**Actual behavior**
<img width="574" alt="Screenshot 2024-10-08 at 11 44 10" src="https://github.com/user-attachments/assets/f39f8104-6827-4150-97bd-e9af005922af">

**Expected behavior**
<img width="124" alt="Screenshot 2024-10-08 at 11 44 57" src="https://github.com/user-attachments/assets/117a5d0b-bb1c-46fd-a444-520a58f00e47">

**Environment details:**
 - Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
 - Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
 - MacOs
 - Chrome 129.0.6668.71 (Official Build) (arm64)

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AlexeyGirin** [comment]
Add hover tooltip (i) with comment that that option applicable to PNG pictures renderer

**Comment by AlexeyGirin** [comment]
Not fixed.
( i ) tooltop button was not found

- Ketcher Version 2.26.0-rc.4 Build at 2024-10-18; 17:00:39
- Indigo Toolkit Version 1.25.0-rc.3.0-g795119115-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.59 (Official Build) (64-bit)
- Win10

**Comment by AlexeyGirin** [comment]
Closed. Follow up feature has been created

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.26.0-rc.6 Build at 2024-10-25; 09:57:12
- Indigo Toolkit Version 1.25.0-rc.4.0-g8862ccb7e-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.59 (Official Build) (64-bit)
- Win10
