### ISSUE TITLE
Update snake layout logic taking into account hydrogen bonds

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5712]
## Background
- Out of scope are non-linear structures (hairpins, loops, etc.)
- This ticket is related to the antisense chain creation ticket: [#5678](https://github.com/epam/ketcher/issues/5678) and the hydrogen bond in macromolecules ticket [#5403](https://github.com/epam/ketcher/issues/5403), and deals with snake mode layout.

## Requirements

1. If hydrogen bonds connect monomers inside one chain, those hydrogen bonds should be considered as side chain connections for layout purposes.
> For the purpose of these requirements a chain is any connection of monomers connected exclusively by R1-R2 backbone connections (ignoring all side connections except sugar-base R3-R1).

2. If two chains are connected via hydrogen bonds and do not satisfy conditions form requirement 3, then:

2.1. Monomers who participate in those H-bonds should be oriented towards each other (one of the chains should be "flipped"); 
> Bases of the non-"flipped" chain should go bellow the sugars, and the bases of the "flipped" chain should go above the sugars.

2.2. Shorter chain (fewer monomers) should get "flipped", and if they are of the same size, the chain whose center is lower on the canvas;

2.3. All other side chain connections (except R3-R1 sugar-base) should be placed above or bellow the chain backbones;
> For non-"flipped" chains the all side-chain-connected monomer(s) should go above the backbone, and for the "flipped" chains all side-chain-connected monomer(s) should go bellow the backbone.

2.4. For R3-R1 sugar-base side connections (when the base does not have hydrogen bonds), that base should be oriented like other bases in the chain (or if there is a tie, bellow the sugar);

2.5. Backbones should be placed parallel to each other,

2.6. The chains should be placed in such a way that the left-most monomer that has a hydrogen bond from the non-"flipped" chain has the monomer that is connected to it via a hydrogen bond from the other chain bellow it.

2.7. Distance between all monomers should be minimum one bond length.

2.8. Multiple backbones/chains can be placed in on a line if they are both connected via H-bonds to the same chain (but not to each other!!!).

2.9. The left-most sugar/amino acid of the chain that changed its orientation should have the terminal indicator changed from 5' to 3' (or opposite) / from N to C (or opposite).
> If a chain gets "flipped" after layout its terminal indicators can only be `C` and `3'`.

2.10. The numbering of the "flipped" chain should go in the opposite direction to the non-"flipped" one.

**Note:** When there are two chains (who do not satisfy requirement 3) who are connected via at least one H-bond but no bases (connected to a sugar via R1-R3) participate in those H-bonds, than no chain can be considered to be "flipped" and requirements 2.1., 2.2., 2.9, and 2.10. do not apply to them. 
When there are two chains who have at least one hydrogen bond between a base (connected to a sugar via R1-R3) and some other monomer (who can be a base with the same conditions but can also be anything else) connecting them (and do not satisfy requirement 3) upon layout one of them is to be considered "flipped" and one non-"flipped". The one with bases bellow the sugar is considered as non-"flipped", while the other is "flipped" AND/OR The one with bases above the sugar is considered as "flipped" while the other is non-"flipped".

3. If there is a circular hydrogen bond connection between three or more chains, those hydrogen bonds should be considered as side chain connection for layout purposes.
> For example, we have three chains A, B, and C. A is connected via hydrogen bonds to both B and C, and B is connected via hydrogen bonds to C.

## UX
![double-stranded chain with side-chain connections](https://github.com/user-attachments/assets/d431151e-d617-43f8-a49c-00afb5d92737)
![double-stranded chain layout](https://github.com/user-attachments/assets/fae54130-dc2d-4fdb-85b2-5d8a009b66c4)

## Examples
**Note: These are just examples to get the idea across, there are some non-layout related mistakes**

### Example 1
Original chain:
![image](https://github.com/user-attachments/assets/af553378-90dc-492c-8488-8b0d45c26bf7)
Create the antisense chain for the selected monomers (automatic layout):
![image](https://github.com/user-attachments/assets/4a9066bf-3978-425e-85c5-e1a4acac83a8)
Create antisense chain for new selected monomers (automatic layout):
![image](https://github.com/user-attachments/assets/9c7b4225-0ae0-4300-8d11-64c36650c5f3)
Connect two highlighted monomers via backbone connection:
![image](https://github.com/user-attachments/assets/9fb9a8e9-22e0-4ed1-935c-2940ce38318e)
Layout:
![image](https://github.com/user-attachments/assets/28443f28-59e2-4032-8d2d-214ac27560be)
> The left-most monomers are aligned (requirement 2.6.)

### Example 2
Sense and antisense chains, and two nucleotides:
![image](https://github.com/user-attachments/assets/65d64bdd-2ea2-4c2f-a21c-c6731880f479)
Connect one nucleotide to each chain:
![image](https://github.com/user-attachments/assets/638eb985-5f62-42ef-a473-386ca60acf91)
Layout: 
![image](https://github.com/user-attachments/assets/b1050e46-eb4c-440b-9203-b32be5748012)
> Even though base h56T does not have any hydrogen bonds it is still oriented above the sugar, because all the other side bases are oriented above the sugar (requirement 2.4.)

### Example 3
Original canvas:
![image](https://github.com/user-attachments/assets/2d381000-fa84-41a1-a43c-e3d1a68e41a4)
Layout:
![image](https://github.com/user-attachments/assets/06e10ca8-fc69-43fd-9d4f-3c2d790249e4)
> The chain of U is the longest, so its bases are oriented in the standard way (requirement 2.2.); nucleotide T is placed on the same line as chain U because they are both connected to chain C (requirement 2.8.). 

### Example 4
Original canvas:
![image](https://github.com/user-attachments/assets/c2e1d7ec-9df5-4832-9069-2b141bda511f)
Layout:
![image](https://github.com/user-attachments/assets/a542609f-f6f6-49bc-ac87-317c4e3b52ad)
> Both chains have the same number of monomers (6), but the nucleotides are lower on the canvas, so the bases will be "flipped" (requirement 2.2.)

![image](https://github.com/user-attachments/assets/d111d8a7-550f-42a3-9ef2-6b9465206e7e)

### Example 5
Original chain (and a single phosphate):
![image](https://github.com/user-attachments/assets/331f160d-4fbf-403e-b1bf-2c535a65a152)
Create antisense strand by selecting the whole chain (automatic layout):
![image](https://github.com/user-attachments/assets/25d7ff5b-e1f4-4b29-aa2d-6ab20313e267)
Connect the CHEM from the antisense chain to the phosphate:
![image](https://github.com/user-attachments/assets/54d48c80-b737-4ae5-b94a-ade8c883f127)
Layout:
![image](https://github.com/user-attachments/assets/afcd7fbd-b593-4ce7-9143-3f2ed051a31c)

**Comment by AlexeyGirin** [comment]
Verified with issues
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10
