### ISSUE TITLE
"Help" module doesn't display correctly in IE11

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/ketcher#572]
Tested on Ketcher v.2.2.1-136-gf081b9ce

_Steps to reproduce:_
1. Launch Ketcher in IE11.
2. Click the 'Help' button.

_Expected result:_ The "Help" module is displayed correctly in the modal window.
![image](https://user-images.githubusercontent.com/80695128/120975187-9e8dde80-c779-11eb-91d6-0709fe01d5d2.png)

_Actual result:_ The "Help" module is displayed outside the modal window.
![image](https://user-images.githubusercontent.com/80695128/120975637-2247cb00-c77a-11eb-9d99-d5c26b9c31da.png)

**Comment by AleksandrPokrovskii** [comment]
Can not reproduce. Fixed in other tasks

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is closed as fixed.
