### ISSUE TITLE
Issue with moving of tail of Multi-Tailed arrow with several tails when user needs to move the tail close to another one

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5753]
**Steps to Reproduce**
1. Add Multi-Tailed Arrow (MTA) to Canvas:
![image](https://github.com/user-attachments/assets/f2062f51-d709-4627-a3ac-62ebfbcfa739)

2. Right-click on MTA, add two tails:
![image](https://github.com/user-attachments/assets/37932888-e3da-4a42-b2b2-34d166faef86)

3. Move up top tail to increase the length of the spine:
![image](https://github.com/user-attachments/assets/7958ee3a-7b6c-4d43-97ee-389fb9666bca)

4. Try to put the third tail a little bit upper then the second tail:
![image](https://github.com/user-attachments/assets/28132ee9-ebe0-46de-8d05-1409ae918e9e)

**Actual behavior**
- The third tail isn't positioned upper, it comes back in the minimal distance (0.35) under the second tail:
![image](https://github.com/user-attachments/assets/09b4b818-6f09-4fce-9016-be2fb55674d0)

**Expected behavior**
- The third tail is positioned upper then the second tail
- It is in the minimal distance (0.35) above the second tail if it is moved closer than the minimal distance to the second tail
![image](https://github.com/user-attachments/assets/1be4e83c-9440-456f-8686-76f38531e37f)

**Environment Details**
 - Ketcher [Version 2.26.0-rc.1] Build at 2024-10-04; 18:45:04
 - Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
 - Desktop, Windows 11 Enterprise
 - Chrome Version 129.0.6668.101 (Official Build) (64-bit)

**Notes**
- Issue is found during testing of https://github.com/epam/ketcher/issues/5548, but it didn't introduce this defect. This issue was introduced during development of https://github.com/epam/ketcher/issues/5057
- Recording is attached:

https://github.com/user-attachments/assets/39c95cdb-ca4a-4367-a318-ed857c994df8

**Comment by rrodionov91** [comment]
Need merge into 2.26

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/3fec995c-bb70-4870-a4d9-d9ed1ca3f8e0



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.6]
**Indigo version** 
[Version 1.25.0-rc.4]
