### ISSUE TITLE
Fix minimal distances for mult-tail validation in KET format

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#5761]
**Steps to Reproduce**
1. Insert structure from smiles "CC"
2. Insert default multi-tail arrow
3. Increase the bond length twice
4. Select all
5. Save as Ket, copy the ket file into clipboard buffer
6. Paste the ket file

**Actual behavior**
Error message appears - cannot deserialize input JSON

**Expected behavior**
No errors, Structure is pasted but with a smaller size
The following validation rules should be changed for KET file (only for KET, the UI behavior should not be changed)

MIN_TAIL_DISTANCE - 0.01.
MIN_HEAD_LENGTH - 0.01.
MIN_TAIL_LENGTH - 0.01
MIN_TOP_BOTTOM_OFFSET -  0.01
MIN_HEIGHT - 0.01

**Desktop (please complete the following information):**
 - Version 2.26rc2

**Note**
- Issue is related to this task - https://github.com/epam/ketcher/issues/5104, tests should be updated

**Comment by ivanmaslow** [comment]
12 manual tests and files are updated, minimal sizes are retested on UI and for loading from KET.
- Minimal sizes on UI are still working as it was:
    - Minimal length of spine without tails = 0.5:
    ![image](https://github.com/user-attachments/assets/d7423036-b3d8-4362-9577-6d43cefe9c71)
    - Minimal distance between tails = 0.35
    - Minimal length of tail = 0.4
    - Minimal length of head = 0.5
    - Minimal X distance between head and top/bottom tails = 0.15:
    ![image](https://github.com/user-attachments/assets/947bc3ed-0230-4b71-9396-0ef1397d2dc4)
- As for minimal sizes for loading from KET, they equal 0.01, but there is no chance to verify validation for MIN_HEIGHT - 0.01 as we have the same MIN_TOP_BOTTOM_OFFSET - 0.01, this is part of MIN_HEIGHT.
    - After loading of Multi-Tailed arrow with minimal sizes, it looks like that, but it can be adjusted to normal size using resizing of head, tails and spine:
    ![image](https://github.com/user-attachments/assets/e4af1ecf-4a55-46b2-9e90-7b8bd2f83fd3)
    ![image](https://github.com/user-attachments/assets/49ddcc1a-4eb4-4a20-b774-24c8ca005677)
- One defect is detected related to changes of minimal sizes - https://github.com/epam/ketcher/issues/5786

**Comment by rrodionov91** [comment]
Need merge into 2.26

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-10-25_15h11_36](https://github.com/user-attachments/assets/8097e39c-8309-46f4-a661-9b4834f771ea)
![2024-10-25_15h11_51](https://github.com/user-attachments/assets/2304bbbe-6751-4841-ab54-f215b779ef1e)
![2024-10-25_15h12_25](https://github.com/user-attachments/assets/0f1665d9-1cd7-44f3-9330-60cb5bcb9d98)

https://github.com/user-attachments/assets/5cfb571c-7b1b-4687-afe1-87e155056ffa



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.6]
**Indigo version** 
[Version 1.25.0-rc.4]
