### ISSUE TITLE
Add API Method getRdf for retrieving RDF representation of structures

### ISSUE THREAD

**Issue by Zhirnoff** [epam/ketcher#5776]
**Summary**
Request to add a getRdf API method to Ketcher for retrieving the RDF representation of chemical structures, with support for specifying V2000 and V3000 formats similar to how it is done in SDF
**Solution**
Introduce a getRdf method in the Ketcher API that allows users to:
- Retrieve the RDF representation of the current structure on the canvas.
- Specify the desired format (V2000 or V3000) for the RDF output, similar to how it's done in SDF export.

**Comment by rrodionov91** [comment]
Need merge into 2.26

**Comment by Zhirnoff** [comment]
Tested.
![2024-10-25_14h25_23](https://github.com/user-attachments/assets/efc3f0f8-fbd1-4e5d-8b73-ba628b8d6a6d)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.6]
**Indigo version** 
[Version 1.25.0-rc.4]
