### ISSUE TITLE
Uncaught TypeError is in console when trying to move tail of Multi-Tailed Arrow added from KET with small size between tails

### ISSUE THREAD

**Issue by ivanmaslow** [epam/ketcher#5786]
**Steps to Reproduce**
1. Load Multi-Tailed Arrow from KET
[multi-tailed-arrow-4-tails-minimal-distance.zip](https://github.com/user-attachments/files/17399850/multi-tailed-arrow-4-tails-minimal-distance.zip)
![image](https://github.com/user-attachments/assets/b1c40e21-efb1-4619-ad5c-10d1fc97fb37)
2. Try to move the middle tails which are intersected with the top and bottom tails because of the distance = 0.01

**Actual behavior**
- Tail is moved to the nearest available place, "TypeError Cannot read properties of undefined (reading 'center')" appears in the console:
![image](https://github.com/user-attachments/assets/94ba9586-e301-43a8-8384-b581c2671107)

**Expected behavior**
No issues in console, MTA should be automatically expanded to a minimal size on the UI
TBD - Confirm with PO

**Environment Details**
 - Tested on Nightly env
 - Ketcher [Version 2.26.0-rc.1] Build at 2024-10-16; 06:55:14
 - Indigo Version 1.26.0-dev.1.0-g2edd615c1-wasm32-wasm-clang-19.0.0
 - Desktop, Windows 11 Enterprise
 - Chrome Version 129.0.6668.101 (Official Build) (64-bit)

**Additional context**
- Issue is introduced during testing of changes for minimal sizes - https://github.com/epam/ketcher/issues/5761 and related to https://github.com/epam/ketcher/issues/5104

**Comment by rrodionov91** [comment]
Need merge into 2.26

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/79e6304a-0f8e-4d95-9ccc-040794d866ba



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.6]
**Indigo version** 
[Version 1.25.0-rc.4]
