### ISSUE TITLE
Preview tooltip doesn't work for monomers at Molecules mode

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5793]
**Steps to Reproduce**
1. Toggle to Molecules mode
2. Load from file any ambiguous monomer using Add to Canvas way: [1. Peptide X (ambiguouse, alternatives, from library).zip](https://github.com/user-attachments/files/17396425/1.Peptide.X.ambiguouse.alternatives.from.library.zip)
![image](https://github.com/user-attachments/assets/5f998b73-fc32-44a3-98ca-42c023bc3d25)
3. Hover mouse over label

**Actual behavior**
Nothing happens (preview tooltip doesn't appear)

**Expected behavior**
Tooltip appears
![image](https://github.com/user-attachments/assets/8976380d-26d2-4607-862a-c15b111e8ab1)

**Versions**
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/ketcher/issues/4557

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-11-07_11h36_04](https://github.com/user-attachments/assets/05ab94af-00e7-4f35-ad1e-35190ca88a92)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
