### ISSUE TITLE
Incorrect rendering of Stereo Flags in reactions

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#58]
**Steps to Reproduce:**

1) Create any reaction with multiple reagents and products. Reagents and products should contain Stereo Labels and Stereo Flags.
2) Click 'Save as' button and save the created reaction in Graph Format.
3) Open saved in .ket file in Ketcher.

**Actual Result:**
![Reaction_opened](https://user-images.githubusercontent.com/14963002/95750068-46174780-0ca5-11eb-80ad-65a12f913dc5.jpg)
All Stereo Flags were moved to the right top corner. 

**Expected Result:**
![StereoFlags_reaction_saved](https://user-images.githubusercontent.com/14963002/95750089-4b749200-0ca5-11eb-97c5-407535d4dcfd.jpg)

All Stereo Flags should appear at the right top corner.

Epic link: #56 
Relates to: #57

**Comment by StartsevDS** [comment]
Cannot reproduce.

**Comment by Svetlana-Asinovskaia** [comment]
Labels don't render correctly initially if there is a reaction arrow or a reaction plus sign on the canvas. 

 1. Create several structures on the canvas.
 2. Add a reaction arrow and the reaction plus signs.
 3. Add several stereobonds to the created structures. 

Expected result: Each stereo flag is located next to the added stereobond.
Actual result: Several stereo flags are grouped in one area of the canvas.
![image](https://user-images.githubusercontent.com/80695128/116198058-2a095e00-a73e-11eb-853e-e1b2a51b5b52.png)

**Comment by Svetlana-Asinovskaia** [comment]
Labels don't render correctly initially if there is a reaction arrow or a reaction plus sign on the canvas.

1. Create several structures on the canvas.
2. Add a reaction arrow and the reaction plus signs.
3. Add several stereobonds to the created structures.

Expected result: Each stereo flag is located next to the added stereobond.
Actual result: Several stereo flags are grouped in one area of the canvas.

![bonds](https://user-images.githubusercontent.com/80695128/116305153-10066480-a7ac-11eb-87db-97c8b2ab98ae.png)

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is closed as fixed.
