### ISSUE TITLE
Importing functional groups (e.g. Boc, Bn, CF3) ignores drawing settings (e.g. ACS style)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5833]
**Steps to Reproduce**
1. Add any functional group on the canvas
(or load from file: [Importing functional groups (e.g. Boc, Bn, CF3) ignores drawing settings (e.g. ACS style) and is bolded.zip](https://github.com/user-attachments/files/17472729/Importing.functional.groups.e.g.Boc.Bn.CF3.ignores.drawing.settings.e.g.ACS.style.and.is.bolded.zip) )
![image](https://github.com/user-attachments/assets/7999d5ba-3484-4c7d-acfc-027d74706d21)
2. Go to Settings - General tab
3. Set Font size to 30 pt and Font to Symbol
![image](https://github.com/user-attachments/assets/c4e5ce83-28b2-4197-adf5-a39ed23d2e54)
4. Click on layout Apply

**Actual behavior**
Functional group label remain unchanged
![image](https://github.com/user-attachments/assets/99fb3752-0072-44dd-8225-6ac4a91cac69)

**Expected behavior**
Functional group label font and font size got changed
![image](https://github.com/user-attachments/assets/4ef39f7a-5bb2-47f7-8b1c-294edc57bb31)

**Versions**
- Ketcher Version 2.26.0-rc.3 Build at 2024-10-16; 14:35:25
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/ketcher/issues/4987

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/0a05e2ff-679d-4135-9890-56149f14931a)
- Ketcher Version 2.26.0-rc.7 Build at 2024-11-04; 15:18:23
- Indigo Toolkit Version 1.25.0-rc.4.0-g8862ccb7e-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.92 (Official Build) (64-bit)
- Win10

**Comment by rrodionov91** [comment]
Need backmerge to 2.27

**Comment by NataliaLoginova** [comment]
Changes were merged into release/2.27 branch in PR #5944
