### ISSUE TITLE
Add "Copy to Clipboard" to the export window

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5854]
**Background**
Many times, especially for "simpler" and linear formats like SMILES, FASTA, and HELM, the user does not need a file to be created, but rather the information to be copied to the clipboard so that they can paste it somewhere.

**Requirements**
1. In both molecules mode and macromolecules mode, an icon should be added to the export window - "Copy to Clipboard".
2. The icon should appear in the top right corner of the preview section of the export windows (see mockups).
3. When the user clicks on the preview section the icon should disappear.
4. When the user hovers over the are where the icon should be (after they've clicked somewhere in the preview area), the button should appear again.
5. Tooltip should appear on hover over the icon "Copy to Clipboard".
6. When clicked, all the information that would get exported to a file gets copied to the clipboard.

**UX**
TBD
![for dev](https://github.com/user-attachments/assets/dc1ba2bd-e5f1-4488-a3b7-2d27e9ab95af)

**Comment by Zhirnoff** [comment]
@NataliaLoginova @mnmsvlw Please add a test-id to this button during the development phase, if possible. This will make automation easier for us.

**Comment by Zhirnoff** [comment]
Tested.
![2024-12-06_11h44_58](https://github.com/user-attachments/assets/92b149f4-7443-47e0-bcfe-88d2bd9e2f2d)
![2024-12-06_11h46_30](https://github.com/user-attachments/assets/c519263d-5b5d-4580-9148-e31c116a45dd)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
