### ISSUE TITLE
System reset micromolecule canvas settings to default if switched to Macro mode and back

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5855]
**Steps to Reproduce**
1. Go to Micro
2. Open Settings, Bond section
3. Set Bond length to 80 and click Apply
![image](https://github.com/user-attachments/assets/a68eefa6-2a55-4fcd-b1f1-a6de6358ceb1)
4. Switch to Macro mode
5. Switch back to Micro mode again
6. Open Settings, Bond section again

**Actual behavior**
Settings got reset to default
![image](https://github.com/user-attachments/assets/9b8aa404-7d14-42f4-9662-2027beda8188)

**Expected behavior**
Settings remain the same
![image](https://github.com/user-attachments/assets/a68eefa6-2a55-4fcd-b1f1-a6de6358ceb1)

**Versions**
- Ketcher Version 2.26.0-rc.5 Build at 2024-10-21; 15:27:55
- Indigo Toolkit Version 1.25.0-rc.3.0-g795119115-wasm32-wasm-clang-19.0.0
- Chrome Version Version 130.0.6723.59 (Official Build) (64-bit)
- Win10

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/a225c3d4-8857-40b3-b4cb-9649b4145c01



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
