### ISSUE TITLE
Export to ket (and getKET function) change incrementally internal IDs every call

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5873]
**Steps to Reproduce**
1. Go to Micro
2. Load from file: [1. Petide D (from library).zip](https://github.com/user-attachments/files/17503927/1.Petide.D.from.library.zip)
3. Press Save button and choose Ket format 
![image](https://github.com/user-attachments/assets/9a033e78-ba2a-4b1a-ae25-23dd6a5dd2c2)
4. Close save dialog
4. Press Save button and choose Ket format one more time

**Actual behavior**
Internal IDs got incremented by 2
![image](https://github.com/user-attachments/assets/cc7d22b4-5fe0-45ad-a12f-6fed5ab6e5dc)

**Expected behavior**
Internal IDs remain the same every call
![image](https://github.com/user-attachments/assets/9a033e78-ba2a-4b1a-ae25-23dd6a5dd2c2)

**Versions**
- Ketcher Version 2.26.0-rc.6 Build at 2024-10-25; 09:57:12
- Indigo Toolkit Version 1.25.0-rc.4.0-g8862ccb7e-wasm32-wasm-clang-19.0.0
- Chrome Version Version 130.0.6723.59 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/ketcher/issues/5400

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
First save
![2024-12-06_18h37_58](https://github.com/user-attachments/assets/83660dd0-cb96-4010-a73c-8c1069f8298c)


Second save
![2024-12-06_18h38_10](https://github.com/user-attachments/assets/44be1a71-c0bf-460c-8731-2e30961f4c4a)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
