### ISSUE TITLE
Autotests: Replace Copy/Cut/Paste keyboard operations with valid helper functions

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5903]
Identify all `Control+A`, `Control+X`, `Control+C`, `Control+V` operations made by keyboard and replace them with
`Control+C` ==> `copyToClipboardByKeyboard(page)`
`Control+X` ==> `cutToClipboardByKeyboard(page)`
`Control+V` ==> `pasteFromClipboardByKeyboard(page)`
`Control+A` ==> `selectAllStructuresOnCanvas(page)`
methods

Recommendation: Try to search "page.keyboard.press(" in code
That could be `page.keyboard.press('Control+v');`
or `page.keyboard.press('${modifier}+KeyC');`  or similar

**Comment by knadonenko** [comment]
In progress
