### ISSUE TITLE
Inability to focus on the drawing entity within expanded S-group/monomer bounding box

### ISSUE THREAD

**Issue by svvald** [epam/ketcher#5910]
Once monomer is expanded in micromolecules mode, it's impossible to focus on the other monomer/s-group which is placed within expanded monomer's bounding box unless expanded monomer is moved which makes it unconvenient to use.
<img width="331" alt="image" src="https://github.com/user-attachments/assets/e325b7aa-35d2-4d2c-af51-933b891ff00d">
Hovering over such monomers/s-groups has to be prioritized so they will be highlighted/focused first even being placed within expanded monomer bounding box

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/de35d8be-b496-40df-a3bd-f09eeb01b49e)
- Ketcher Version 2.27.0-rc.3 Build at 2024-12-25; 10:08:04
- Indigo Version 1.26.0-rc.5.0-g42ee8510b-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
