### ISSUE TITLE
Browser crash when copy and paste a sgroup structure

### ISSUE THREAD

**Issue by hayabusa2009** [epam/ketcher#592]
**Steps to Reproduce**
1. run `master` branch
2. create a structure on canvas and surround with `SGroupTool`
3. press `Ctrl+a` to copy the structure
4. press `Ctrl+v` and move over canvas

_Actual result:_ Browser crash and some errors occur at `Console`

**Additional context**
if revert `ketcher-react\src\script\editor\shared\action.ts` file to prev version, this problem is resloved

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is closed as fixed.
