### ISSUE TITLE
Layout for antisense chains in sequence mode

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#5925]
**Background**

This is the first version of representation of sense and antisense chains in sequence mode, and will be amended shortly.

**Requirements**

1. Sense and antisense chains should be treated as completely separate chains in sequence mode, without any hydrogen bonds connecting them.
> In snake mode:
> ![image](https://github.com/user-attachments/assets/dc915577-6060-4227-a60c-1eb82a51c8d5)
> In sequence mode:
> ![image](https://github.com/user-attachments/assets/f293abcd-e670-49c9-a699-a3a1bba1a847)

2. Right-clicking on the sequence (without selecting monomers) should give the option to: "Create Antisense Strand".

3. When multiple monomers are selected, the user should have the option to "Create Antisense Strand" in the r-click menu.

4. For requirements 2 and 3 the same conditions for the chain/selected monomers have to be met as for selected monomers in this ticket: [#5678](https://github.com/epam/ketcher/issues/5678)

5. The logic for creating antisense chains is identical to the logic for snake and flex modes.

6. The new antisense chain should be placed in the line bellow the sense chain.
> In snake mode:
> ![image](https://github.com/user-attachments/assets/a73c6e7a-0914-4729-8176-d7c71166c007)
> In sequence mode:
> ![image](https://github.com/user-attachments/assets/f235fb4d-a0c6-4c56-91f2-cb3946b493b5)
> Selection:
> ![image](https://github.com/user-attachments/assets/12f2570c-0364-4407-a6fb-86dd75b3319e)
> "Create Antisense Strand":
> ![image](https://github.com/user-attachments/assets/923383fb-9561-421f-bfef-7ffcb5821fbc)
> Snake mode:
> ![image](https://github.com/user-attachments/assets/8bc5e420-0fc8-4e71-a7d0-6ae8aa3ac704)

**Comment by Zhirnoff** [comment]
Tested.
![2024-12-04_14h05_59](https://github.com/user-attachments/assets/c11b3ecd-a2d7-48df-8d66-52633fc6ea46)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
