### ISSUE TITLE
Undo/Redo operation for bonds and molecules (multi-select) works wrong (doesn't work)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5966]
**Steps to Reproduce**
1. Go to Macro - Flex
2. Load from file: [Undo_Redo operation for bonds and molecules (multi-select) works wrong (doesn't work).zip](https://github.com/user-attachments/files/17730355/Undo_Redo.operation.for.bonds.and.molecules.multi-select.works.wrong.doesn.t.work.zip)
![image](https://github.com/user-attachments/assets/1fa8d07b-2960-401a-b1c3-a47402775904)
3. Select bonds and atoms in the center of chain (using area selection tool)
![image](https://github.com/user-attachments/assets/cef7a2c9-ef34-48ab-8f62-0713e9c40be3)
4. Click Erase button
![image](https://github.com/user-attachments/assets/5a2b2fd3-a6ba-4d7a-a4b8-08b56108680f)
5. Press Undo button

**Actual behavior**
Only atoms appeared back
![image](https://github.com/user-attachments/assets/34849fd1-b9f5-48f3-85e5-0ec76c20fa57)

**Expected behavior**
Atoms and bonds recovered
![image](https://github.com/user-attachments/assets/1037164c-9633-4b36-b329-32bb64f34825)

**Versions**
- Ketcher Version 2.27.0-rc.2 Build at 2024-11-12; 19:26:10
- Indigo Toolkit Version 1.26.0-rc.2.0-gfec30ecd8-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.70 (Official Build) (64-bit)
- Win10

Issue found while testing: https://github.com/epam/ketcher/issues/5359

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/bf22c67b-145d-4d40-81a4-81caa638ed1b



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
