### ISSUE TITLE
System should not change monomer position after switching from Molecules to Macromolecules - Sequence

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5967]
**Steps to Reproduce**
1. Toggle to Macromolecules mode - Flex mode
2. Load from file: [System should not change monomer position after switching from Molecules to Macromolecules - Sequence.zip](https://github.com/user-attachments/files/17732656/System.should.not.change.monomer.position.after.switching.from.Molecules.to.Macromolecules.-.Sequence.zip)
![image](https://github.com/user-attachments/assets/5cef491c-9e71-40d7-807d-ecd0bd636d14)
3. Toggle to Sequence mode
![image](https://github.com/user-attachments/assets/8186b859-0c62-4ac8-a58a-7ced07d9b6b1)
4. Toggle back to Molecules mode
![image](https://github.com/user-attachments/assets/df184034-c1f7-4641-bd88-ebcc9b3cb2fc)
5. Toggle to Sequence mode

**Actual behavior**
Monomer positions has been changed
![image](https://github.com/user-attachments/assets/27979a00-3f67-4621-8a8c-793557e4a1dd)

**Expected behavior**
Monomer positions remain the same
![image](https://github.com/user-attachments/assets/8186b859-0c62-4ac8-a58a-7ced07d9b6b1)

**Versions**
- Ketcher Version 2.27.0-rc.2 Build at 2024-11-12; 19:26:10
- Indigo Toolkit Version 1.26.0-rc.2.0-gfec30ecd8-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.70 (Official Build) (64-bit)
- Win10

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-12-25_14h59_36](https://github.com/user-attachments/assets/87a54ab5-a368-4fec-b09d-b84e5c80e9a3)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.3]
**Indigo version** 
[Version 1.26.0-rc.3]
