### ISSUE TITLE
Entire element bounding box should be clickable, not only black dots

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#5978]
**Steps to Reproduce**
1. Go to Macro - Flex mode
2. Load from file: [Entire element bounding box should be clickable, not only black dots.zip](https://github.com/user-attachments/files/17775562/Entire.element.bounding.box.should.be.clickable.not.only.black.dots.zip)
![image](https://github.com/user-attachments/assets/73c41a6c-8f42-4f92-bb8e-ed3a87d4000a)
3. Click on the center of double bond (e.g. between two black lines)

**Actual behavior**
Nothing happens

**Expected behavior**
Double bond got selected
![image](https://github.com/user-attachments/assets/af2bd493-8e11-4fd1-a122-7a6dd0cd96f3)

**Versions**
- Ketcher Version 2.27.0-rc.2 Build at 2024-11-12; 19:26:10
- Indigo Toolkit Version 1.26.0-rc.2.0-gfec30ecd8-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.70 (Official Build) (64-bit)
- Win10

Issue found while testing: https://github.com/epam/ketcher/issues/5359

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2025-01-03_12h04_32](https://github.com/user-attachments/assets/856f69d3-424b-4476-a228-91e07a2ae61b)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
