### ISSUE TITLE
It's impossible to open Ketcher with already entered molecule

### ISSUE THREAD

**Issue by EugenReentovich** [epam/ketcher#601]
If open Ketcher in some popup, it takes time to load. At the same time, it's impossible to set any molecule in Ketcher, because it does not exist yet. 

I'd like, e.g., to have some event to know when loading is finished and it's possible to send a structure to Ketcher.

**Comment by AndreiMazol** [comment]
In scope of this task a new property has been added to <Editor /> component:
onInit: (ketcher: Ketcher) => void
example of usage:
`onInit={ketcher => {
        setTimeout(() => {
          ketcher.setMolecule('CCCCCCCCCC>>CCCCCCCCC')
        }, 5000)
      }}`
