### ISSUE TITLE
Connection between molecule and monomer does not affect an amount of implicit hydrogens 

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#6021]
**Steps to Reproduce**
1. Go to Molecules mode
2. Create any molecule with implicit hydrogen in any atom label
3. Go to Macromolecules mode
4. Add any monomer to canvas
5. Connect monomer to molecule's atom with implicit hydrogen in label
![image](https://github.com/user-attachments/assets/3e7ec29c-6163-44c3-82e3-40700daecd58)

**Actual behavior**
Amount of hydrogens does not change when connect to monomer

**Expected behavior**
Amount of hydrogens should be reduced by one for each connection to monomer

**Ketcher version** [e.g. v2.4.2]. 
v2.27.0-rc.2

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/41c8ee5b-a309-4872-83ca-2efa599e4fce



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
