### ISSUE TITLE
Support for single atom properties in macromolecules mode

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#6027]
**Background**

This is a continuation of a larger "Molecules in Macromolecules mode" issue.

**Single atom properties**

- Label (already supported)
- Number (editing disabled)
- Alias
- Charge
- Isotope
- Valence
- Radical

![image](https://github.com/user-attachments/assets/7184fe63-74f7-4f94-ad7a-9dce72c0f41f)

**Requirements**

1. When the user in molecules mode draws a structure containing atoms with single atom properties assigned, upon entry of macromolecules mode representation of such atoms should not change.

2. Structures with such atoms (with single atom properties assigned) should be able to be saved (and loaded back) as a part of monomer-molecule structures.

**Comment by Zhirnoff** [comment]
Tested.


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
