### ISSUE TITLE
Support for all bond types in macromolecules mode

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/ketcher#6028]
**Background**

This is a continuation of a larger "Molecules in Macromolecules mode" issue.

**Bond types**

There are 14(+2) bond types supported in molecules mode:
![image](https://github.com/user-attachments/assets/10d40eb8-f823-45a2-8199-e1dccf28ddc8)

1 - Single Bond (supported in macromolecules mode already);
2 - Double Bond (supported in macromolecules mode already);
3 - Triple Bond;
4 - Any Bond;
5 - Aromatic Bond (one representation);
6 - Single/Double Bond;
7 - Single/Aromatic Bond;
8 - Double/Aromatic Bond;
9 - Dative Bond;
10 - Hydrogen Bond;
11 - Single Up Bond (supported in macromolecules mode already);
12 - Single Down Bond (supported in macromolecules mode already);
13 - Single Up/Down Bond (supported in macromolecules mode, but incorrectly - as a simple single bond);
14 - Double Cis/Trans Bond (supported in macromolecules mode, but incorrectly - as a simple double bond);
15 - Aromatic Bond (one representation);
16 - Thick foreground bond (an up bond surrounded by wide ends of other up bonds).

**Requirements**

1. Small molecules form molecules mode with any bond type should not change their representation when user switcher to macromolecules mode.

2. Structures with all kinds of bond types should be properly exported and imported as part of monomer-molecule structures.

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 3.20.0-rc.1 Build at 2024-12-31; 12:50:08
- Indigo Toolkit Version 1.28.0-rc.1.0-gc167e6266-wasm32-wasm-clang-19.0.0
- Chrome Version Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
