### ISSUE TITLE
RNA chain remain flipped after hydrogen bond removal

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#6061]
**Steps to Reproduce**
1. Go to Macro - Flex mode <--IMPORTANT!
2. Load from HELM using paste from clipboard: `RNA1{R(A)P.R(C)P.R(G)P.R(G)P.R(A)P}|RNA2{R(A)P.R(C)P}|RNA3{R(A)P.R(G)P.R(T)P}$RNA1,RNA2,5:pair-2:pair$$$V2.0`
![image](https://github.com/user-attachments/assets/742d468a-5461-4e0b-a30b-a31f59d98b74)
3. Delete hydrogen bond
4. Switch to Snake mode

**Actual behavior**
Short chain remain in place and doesn't ordered by Snake mode
![image](https://github.com/user-attachments/assets/30764ded-bda8-445e-9544-29ffb8a1b2de)

**Expected behavior**
All chain ordered by snake mode
![image](https://github.com/user-attachments/assets/34a3bbb6-75f3-45b1-ae55-2eed5902e7e8)

**Versions**
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5712

**Comment by rrodionov91** [comment]
Ffixed in 6099. Not linked because github does not allow to link more than 10 issues to PR

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/7d649341-4f5e-48b7-a395-8b557667325e)
- Ketcher Version 2.28.0-rc.2 Build at 2024-12-10; 18:40:08
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.140 (Official Build) (64-bit)
- Win10
