### ISSUE TITLE
Hydrogen bond between bases doesn't shown in Sequence mode

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#6103]
**Steps to Reproduce**
1. Go to Macro - Snake mode
2. Load from HELM using paste from clipboard: `RNA1{[nC62r](T)P.[nC62r](G)P.[nC62r](C)P}|RNA2{R(A)P.R(C)P.R(G)P}$RNA1,RNA2,9:pair-9:pair|RNA1,RNA2,4:pair-7:pair|RNA1,RNA2,2:pair-2:pair$$$V2.0`
![image](https://github.com/user-attachments/assets/0eb9076e-217c-413d-9673-e24640bb0e16)
3. Toggle to Sequence mode

**Actual behavior**
Hydrogen bond between bases doesn't shown in Sequence mode
![image](https://github.com/user-attachments/assets/61888dd9-c955-43a6-9e86-aad3f5203ac2)

**Expected behavior**
Hydrogen bond between bases shown in Sequence mode
![image](https://github.com/user-attachments/assets/ca106943-d0e9-4a71-8585-94410c4c5462)

**Versions**
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5678

**Comment by rrodionov91** [comment]
Works as expected per requirement from https://github.com/epam/ketcher/issues/5925:
> Sense and antisense chains should be treated as completely separate chains in sequence mode, without any hydrogen bonds connecting them.
