### ISSUE TITLE
Layout works wrong if bases of the same chain connected by H-bonds

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#6105]
**Steps to Reproduce**
1. Go to Macro - Snake mode
2. Load from HELM using paste from clipboard: `RNA1{R(A)P.R(C)P.R(G)P.R(G)P.R(T)P.R(C)P.R(C)P}$RNA1,RNA1,2:pair-14:pair$$$V2.0`

**Actual behavior**
Layout goes wrong
![image](https://github.com/user-attachments/assets/cc16e84e-703f-4efa-b762-6f7d12d699e7)

**Expected behavior**
Layout goes correct
![image](https://github.com/user-attachments/assets/dccd5ec4-ce1f-4825-bfb0-688059de830c)

**Versions**
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5712

**Comment by rrodionov91** [comment]
Fixed in https://github.com/epam/ketcher/pull/6099. Backmerged in https://github.com/epam/ketcher/pull/6111. Not linked because github does not allow to link more than 10 issues to PR

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/7c9cf4d6-0ea8-4a31-9139-c9a6e7d27a8b)
**Versions**
- Ketcher Version 2.28.0-rc.2 Build at 2024-12-10; 18:40:08
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.140 (Official Build) (64-bit)
- Win10
