### ISSUE TITLE
Left toolbar is not visible in Firefox

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#612]
**Steps to Reproduce**
1. Open Ketcher in  Firefox
2. Set window height to <900 px

**Expected behavior**
Left toolbar has a scroll and it does not cover control elements.

**Actual behavior**
Control elements are partially visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/72735611/124765736-efdaea80-df3e-11eb-8def-da0a93b1ac45.png)

**Desktop (please complete the following information):**
 - Window
 - Browser Firefox
 - Version 86.0.1

**Comment by nseufulina** [comment]
Release/2.3 The issue is closed as fixed.
![image](https://user-images.githubusercontent.com/87320094/126335189-2391a08e-cbcd-4b98-8aab-a689e4656870.png)
