### ISSUE TITLE
The application doesn't work after "Undo"

### ISSUE THREAD

**Issue by AleksandrPokrovskii** [epam/ketcher#615]
**Steps to Reproduce**
1. Launch Ketcher
2. Add chain on the canvas
3. Add chain from the following atom
![image](https://user-images.githubusercontent.com/85170103/124891670-e060ad80-dfe1-11eb-984d-3a80fb9f5c88.png)
4. Click "Undo"

**Expected behavior**
Everything is working correctly.

**Actual behavior**
"Undo" works incorrect. The application does not respond to actions.

**Comment by AleksandrPokrovskii** [comment]
If you change the priority of operations to the next.

- CalcImplicitH priority - 2
- BondAttr priority - 4
- BondDelete priority - 4 
- AtomDelete priority  - 5

Steps to Reproduce: 

1. Launch Ketcher
2. Create a benzene molecule using the Templates tool.
3. Add chain
![image](https://user-images.githubusercontent.com/85170103/125254319-05fff680-e303-11eb-8d83-c28ed10aaf1e.png)
4. select part of chain
5. Click "Rotate tool"
6. Rotate selected part of chain to merge with benzene molecule
![image](https://user-images.githubusercontent.com/85170103/125254768-7444b900-e303-11eb-8035-176b73e5cb13.png)
7. Click "Undo/Redo" several times

**Expected behavior**
Everything is working correctly.

**Actual behavior**
Undo, redo after chain merge works correctly. 
TypeError: Cannot read property 'begin' of undefined after flip single up bond. 
TypeError: Cannot read property 'pp' of undefined after merging structure with rotation tool.

**Comment by nseufulina** [comment]
Release/2.3 The issue is closed as fixed.
