### ISSUE TITLE
IE: An additional border is rendered inside Text modal 

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#616]
**Steps to Reproduce**
1. Open Ketcher.
2. Select Text tool
3. Click on canvas
4. Start typing

**Expected behavior**
Text field is updating. There are no additional borders

**Actual behavior**
An additional border is rendered around text field.

**Screenshots**
![image](https://user-images.githubusercontent.com/72735611/124899269-9f1fcc00-dfe8-11eb-80d6-2a59f061505f.png)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: IE 11
 - Version: 1903

**Comment by r1z3rISGOD** [comment]
Not reproducible on system version 20H2 (build 19042.1165).
The text field works as expected.
