### ISSUE TITLE
IE: copying of simple objects/texts does not work

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#618]
**Steps to Reproduce**
1. Open Ketcher
2. Add any simple objects or texts objects
3. Select added objects
4. Click on 'copy' button  or press 'ctrl+c'
5. Click on canvas and press 'ctrl+v'

**Expected behavior**
Copied objects are pasted on canvas

**Actual behavior**
Paste functionality does not work

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: IE 11
 - Version: 1903

**Comment by aleksandrgordeev1** [comment]
This issue can not be fixed as the only type that can be set in clipboardData for IE is 'text'.
Instead, following issue need to be done: https://github.com/epam/ketcher/issues/707
