### ISSUE TITLE
Modal windows don't close when pressing the esc button

### ISSUE THREAD

**Issue by AleksandrRyakhov** [epam/ketcher#626]
**Steps to Reproduce**
1. Launch Ketcher
2. Click on "Settings"/"Help"/"About" button
3. Click the Esc hot key button

**Expected behavior**
The modal window is closed
<img width="1440" alt="Screenshot 2021-07-13 at 13 08 01" src="https://user-images.githubusercontent.com/86657714/125434060-36f80f83-9c3a-41bd-97a8-7f76ce6c89f5.png">

**Actual behavior**
The modal window remains open
<img width="1440" alt="Screenshot 2021-07-13 at 13 08 29" src="https://user-images.githubusercontent.com/86657714/125434106-37379e9b-7dd2-43d6-b7d5-7861779b938a.png">

**Desktop:**
 - OS: MacOS
 - Browsers: 
    - Safari: 14.1.1
    - Chrome: 91.0.4472.114
    - Firefox: 89.0.2
    - Edge: 91.0.864.67

**Comment by nseufulina** [comment]
Release/2.3 The issue is closed as fixed.
