### ISSUE TITLE
When marks "Load as fragment and copy to the Clipboard" structure don't save to clipboard

### ISSUE THREAD

**Issue by AleksandrPokrovskii** [epam/ketcher#634]
**Steps to Reproduce**
1. Launch Ketcher
2. Click the 'Open' button.
3. Click the 'Open From File' button.
4. Choose any correct mol-file (e.g. [cyclopentyl.zip](https://github.com/epam/ketcher/files/6821750/cyclopentyl.zip)).
5. Check the mark "Load as fragment" and click the 'OK' button.
6. Click on the canvas to paste the structure
7. Clear the canvas. Click 'Ctrl+V' hotkey

**Expected behavior**
The correct structure is pasted on the canvas.
![image](https://user-images.githubusercontent.com/85170103/125764063-9a4ad450-02e9-4bbd-8d20-1ccbf836029d.png)

**Actual behavior**
Error: Convert error
[object Object]
![image](https://user-images.githubusercontent.com/85170103/125763818-471bdc34-7a7a-452b-b4f6-3ca3fd5d9db1.png)

**Comment by AleksandrPokrovskii** [comment]
https://github.com/epam/ketcher/issues/626

**Comment by nseufulina** [comment]
Release/2.3 The issue is closed as fixed.
