### ISSUE TITLE
SAVE and OPEN STRUCTURE with STEREO MARKS

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#64]
As a Ketcher collaborator I'd like to verify saving stereo flags to MOL file and implement missed functionality. 

**1. Structure with Chiral Stereo flag**
Structure with Chiral Stereo flag can be saved in both V2000 and V3000 file format.
• Mol file in V2000 format has the '1' in second string at the CTAB block:
Ketcher 10121612192D 1 1.00000 0.00000 0
9 8 0 1 0 999 V2000
• Mol file in V3000 format has the CFG value(s) near atom(s) (stereocenter) and near stereobond(s).

**2. Structure with AND Enantiomer Stereo flag**
Structure with AND Enantiomer Stereo flag can be saved in both V2000 and V3000 file format.
• Mol file in V2000 format has the '0' in second string at the CTAB block:
Ketcher 10121612192D 1 1.00000 0.00000 0
9 8 0 0 0 999 V2000
• Mol file in V3000 format has the CFG value(s) near atom(s) (stereocenter) and near stereobond(s).

**3. Structure with OR Enantiomer Stereo flag**
Structure with OR Enantiomer Stereo flag can be saved in V3000 file format only.
Mol file has
• the CFG value(s) near atom(s) (stereocenter) and near stereobond(s)and
• 'collection' at the CTAB end:
M V30 BEGIN COLLECTIONM V30 MDLV30/STEREL1 ATOMS=(1 9)
M V30 END COLLECTIONM V30 END CTAB

**4. Structure with MIXED Stereo flag**
Structure with MIXED Stereo flag can be saved in V3000 file format only.
Mol file has
• the CFG value(s) near atom(s) (stereocenter) and near stereobond(s)and
• 'collection' at the CTAB end:
M V30 BEGIN COLLECTIONM V30 MDLV30/STEABS ATOMS=(1 3)
M V30 MDLV30/STEREL1 ATOMS=(1 9)
M V30 MDLV30/STERAC1 ATOMS=(1 6)
M V30 END COLLECTIONM V30 END CTAB

Epic link: #56

**Comment by irinatelnova** [comment]
Structures with an OR Enantiomer Stereo flag or with a MIXED Stereo flag can only be saved in a Graph file format. Saving structures in V3000 format functionality is not planned to be implemented on the client side.
Structures with a Chiral Stereo flag and with an AND Enantiomer Stereo flag can be saved in V2000 and in Graph file formats.

**Comment by Svetlana-Asinovskaia** [comment]
The issue is verified and partly closed.
It was discussed with Alexander Savelyev. AND OR stereocenters are not supported in V2000 format. They are only supported in V3000 (The possibility of saving the structures in V3000 is blocked until the moment The Internal format milestone will be implemented). Structures with an OR Enantiomer Stereo flag, with a MIXED Stereo flag and with an AND Enantiomer Stereo flag can be saved in Graph file format. Structures with a Chiral Stereo flag can be saved in V2000 and in Graph file formats.
