### ISSUE TITLE
onChange property on the ketcher-react

### ISSUE THREAD

**Issue by mustafacanp** [epam/ketcher#645]
### Problem
It's not possible to store molecule data on the state in the current version. `getMolfileAsync` shows the current data but you need to call it every time.

### Suggestion
It can pass parameters `value` and `onChange` to the `Editor` component. We need to update the value property whenever the user interacts with the editor.

```
<Editor
    staticResourcesUrl={staticResourcesUrl}
    structServiceProvider={structServiceProvider}
    value={value}
    onChange={onChange}
/>
```

**Comment by AndreiMazol** [comment]
Hi @mustafacanp ,

please provide more details about your case. 
Originally, we do not plan to pass the whole structure to redux, our goal is to  split kethcer app into different modules: core is responsible for business logic and manipulations with  structure, ketcher-react is just a presentation layer.  

I hope the following steps can help you:
1. add onInit handler
2. subscribe on 'change' event

See code example bellow:

```
<Editor 
      staticResourcesUrl={process.env.PUBLIC_URL}
      structServiceProvider={structServiceProvider}
      onInit={ketcher => {
        ketcher.setMolecule({your init data here})
ketcher.editor.subscribe('change',  operations => { 'you can base your logic on the list of operations, handler will be started after every change' })
      }}
    />
```

**Comment by mustafacanp** [comment]
Okay, the `subscribe` event worked thanks.

**Comment by dmoskalenko-datagrok** [comment]
@AndreiMazol  Thank you this subscription would be useful, 
but there are in version 2.4.2 on these members:
```
export interface Editor {
    isDitrty: () => boolean;
    setOrigin: () => void;
    struct: (struct?: Struct) => Struct;
}
```
Is it possible that the subscription on change is moved somewhere?

**Comment by twall** [comment]
@dmoskalenko-datagrok the `subscribe` function is on the ketcher object, not the editor object.
