### ISSUE TITLE
is there any limitation of S-Group count?

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#646]
### Discussed in https://github.com/epam/ketcher/discussions/629

<div type='discussions-op-text'>

<sup>Originally posted by **CLLPCH** July 14, 2021</sup>
Hi, I followed the [instruction](https://github.com/epam/ketcher/discussions/481#discussioncomment-630626) (which is very useful) and got Ketcher embedded in our project.

- Ketcher v2.2.1 (fetch from GitHub)
- standalone

When I tried to draw something with S-Group, e.g. 796, and press the "Save As..." button, I got the message "number does not fit". In case I did something wrong in my environment, I tried on Ketcher 2.2 Standalone demo site and got the same result (see image).

I would like to know if I miss any or this is not the case supported by Ketcher 2 ? Thank you.

![image](https://user-images.githubusercontent.com/87416818/125595791-59ff88d5-e0f9-4c2e-8f61-01566158d5b0.png)
</div>

**Comment by nseufulina** [comment]
Release/2.4 Works are required, except feature that is blocked by realization of internal format #702
