### ISSUE TITLE
Calculated Values tool: When calculating reaction, there is different behavior in different modes

### ISSUE THREAD

**Issue by nseufulina** [epam/ketcher#650]
**Steps to Reproduce**
1. Launch Ketcher
2. Open [reaction_2.zip](https://github.com/epam/ketcher/files/6829086/reaction_2.zip)
3. Select reaction components as:
A + B;
B -> C;
A and D;
B -> C + D.
4. Click Calculated Values

**Expected behavior**
Information in the Calculated Values window displayed identical in both modes

**Actual behavior**
**Standalone** mode:
brackets and signs of reactions are displayed in the Calculated Values window
![image](https://user-images.githubusercontent.com/87320094/125918339-5a5b8cb1-6424-4c02-a798-4e7aa7caddf2.png)
![image](https://user-images.githubusercontent.com/87320094/125918504-b4c335a0-5f9b-4642-99cf-6e8b814c4fa0.png)
![image](https://user-images.githubusercontent.com/87320094/125918632-e36a5e98-b995-4edb-8d4b-100b7f94cc8f.png)
![image](https://user-images.githubusercontent.com/87320094/125918766-cb93297d-959d-4f2d-bc0c-c7e5f7a43739.png)

**Remote** mode:
![image](https://user-images.githubusercontent.com/87320094/125918307-6aababcd-6f12-4bf1-89f6-01f192191a12.png)
![image](https://user-images.githubusercontent.com/87320094/125918564-cf59b2c0-1026-4399-8c4c-9cb433fdf605.png)
![image](https://user-images.githubusercontent.com/87320094/125918710-281b64d9-4f5d-441b-8a27-71974fca07bd.png)
![image](https://user-images.githubusercontent.com/87320094/125918807-5b001844-e456-4b11-a74b-9e6fc5814c93.png)

**Desktop**
 - OS: W10

**Comment by MagomedGasanov** [comment]
Related issue: https://github.com/epam/Indigo/issues/465

**Comment by AllaZhbanova** [comment]
fixed, tested v.2.4
