### ISSUE TITLE
When saving file in InChi format atom's alias is taken as query

### ISSUE THREAD

**Issue by nseufulina** [epam/ketcher#656]
**Steps to Reproduce**
1. Launch Ketcher
2. Create chain on the canvas
3. Double-click any atom
4. Type any text in the 'Alias' field (for example, 'alias123').
5. Click OK
6. Click “Save As” button
7. Choose InChi format

**Expected behavior**
File can be saved in InChi format. No alert message appears. 

**Actual behavior**
Message while saving file: Structure contains query features.
Alert with error message appears:
![image](https://user-images.githubusercontent.com/87320094/126132938-d923c801-c61b-43f9-85ae-c66445e31bb7.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10

**Comment by AleksandraIvleva** [comment]
The problem is on Indigo side. New bug was created: https://github.com/epam/Indigo/issues/477

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
