### ISSUE TITLE
Add drawing tool for simple objects

### ISSUE THREAD

**Issue by Vesdet** [epam/ketcher#66]
As a Ketcher collaborator I'd like to implement drawing tool in Ketcher to add capability for user to draw following elements on canvas:
1. Circle,
2. Rectangle

**Comment by AndreiMazol** [comment]
In scope of this task are:

- dragging created objects
- saving objects as .ket file
- initializing canvas by simple objects while reading .ket file
- scaling of every standalone object with keeping aspect ratio
- showing bounds of new object as dotted-line while users are scaling/moving/etc it
- informing users about losing simple objects while users try to save results not in .ket file

*.ket- internal Ketcher format

**Comment by AndreiMazol** [comment]
Dear @benabel ,

Thank you for you interest in  Ketcher.
As I can see mentioned functionality is related to reaction tool but in scope of this ticket we are working on simple objects. 
If you'd like you can open separate issue for enhancement and we will review it and potentially include it into our roadmap.

Best regards,
Andrei
