### ISSUE TITLE
Error message is hidden under the S-Group modal window

### ISSUE THREAD

**Issue by AleksandrRyakhov** [epam/ketcher#665]
**Steps to Reproduce**
1. Create chain structure
2. Click 'S-Group' button and select part of created chain
3. Choose 'Multiple group' in 'Type' input
4. Delete default value in 'Repeat count' input
5. Hover cursor on 'Repeat count' input

**Expected behavior**
The error message is fully visible

**Actual behavior**
The error message is hidden under the modal window
<img width="306" alt="Screenshot 2021-07-20 at 17 02 11" src="https://user-images.githubusercontent.com/86657714/126337569-89b2105b-60dc-43c6-9abb-571d3bfb872e.png">

**Desktop:**
 - OS: MacOS
 - All browsers

**Comment by nseufulina** [comment]
Release/2.3 The issue is verified and closed.
