### ISSUE TITLE
Can not open InChi AuxInfo file in Standalone mode

### ISSUE THREAD

**Issue by nseufulina** [epam/ketcher#667]
**Steps to Reproduce**
1. Launch Ketcher in standalone mode
2. Create some structures
3. Click 'Save As'
4. Choose InChi AuxInfo format in 'Format' drop-down list
5. Click 'Save To File'
6. Click 'Open'
7. Click 'Open From File' and choose saved file

**Expected behavior**
File opens

**Actual behavior**
File is not opened, convert error when parsing from InChi AuxInfo format.
The same issue if file opens from InChi AuxInfo code.

![image](https://user-images.githubusercontent.com/87320094/126472694-1d48d66f-0baa-4fc5-9eeb-9feb5e988e4b.png)

**Desktop (please complete the following information):**
 - OS: W10

**Comment by nseufulina** [comment]
related indigo issue: https://github.com/epam/Indigo/issues/454

**Comment by vitalgerko** [comment]
Release/2.4 Closed as fixed.
