### ISSUE TITLE
Server functions do not work with structures with dative/hydrogen bonds

### ISSUE THREAD

**Issue by nseufulina** [epam/ketcher#668]
**Steps to Reproduce**

1. Launch Ketcher.
2. Create any structure.
3. Sprout dative or hydrogen from any structure atom.
4. Click on the server functions - Indigo Tools (eg. Clean Up, Layout Aromatize, Dearomatize, Calculate CIP, Calculated Values, Auto-mapping, for Copy Image - select structure first)

**Expected behavior**
Function works on the structure.

**Actual behavior**
Nothing happens on the canvas. Bad request error when request was send to server.

**Comment by AndreiMazol** [comment]
Related issue epam/Indigo#413

**Comment by AllaZhbanova** [comment]
fixed, tested v.2.4
