### ISSUE TITLE
Layout action do not work with structures with dative/hydrogen bonds

### ISSUE THREAD

**Issue by nseufulina** [epam/ketcher#669]
**Steps to Reproduce**

1. Launch Ketcher.
2. Create any structure.
3. Sprout dative or hydrogen from any structure atom.
4. Click the 'Layout' button.

**Expected behavior**
After the Layout action the structure moves to the upper left corner of the canvas. The sprouted bond is perpendicular (normal) to the structure.

**Actual behavior**
After Layout action nothing happens on the canvas. Bad request error, IndigoException.
![image](https://user-images.githubusercontent.com/87320094/126349147-d00466ed-3127-4a4e-9cf2-b0356ea85990.png)

**Desktop:**
 - OS: W10

**Comment by AndreiMazol** [comment]
Related issue epam/Indigo#413

**Comment by nseufulina** [comment]
Closed as dublicated by #668
