### ISSUE TITLE
Not all atom properties are shown if an Alias was set

### ISSUE THREAD

**Issue by nseufulina** [epam/ketcher#674]
**Steps to Reproduce**
1. Launch Ketcher
2. Create any structure (e.g. chain)
3. Double-click any atom and set all possible atom properties, except Alias.
4. Check that properties are shown
5. Double-click any atom and set alias (e. g. 'alias')

**Expected behavior**
All properties are shown.

**Actual behavior**
Only Inversion property is shown. 

**Screenshots**
![image](https://user-images.githubusercontent.com/87320094/126445770-76f77db7-3e90-4576-815c-82fa117b9874.png)

**Desktop:**
 - OS: W10

**Comment by AleksandrRyakhov** [comment]
Waiting for confirmation from @AlexanderSavelyev that this is a bug

**Comment by AlexanderSavelyev** [comment]
alias should replace only atom label. All other properties should be kept

**Comment by nseufulina** [comment]
Release/2.4 This bug is closed as fixed.
