### ISSUE TITLE
Support for dative bonds

### ISSUE THREAD

**Issue by skearnes** [epam/ketcher#68]
Hi, it would be great if Ketcher supported [dative bonds](https://en.wikipedia.org/wiki/Coordinate_covalent_bond). These are especially common for metal complexes used as e.g. catalysts. Note that RDKit SMILES supports dative bonds via `<-` and `->`; see https://www.rdkit.org/docs/RDKit_Book.html#dative-bonds.

Background: We are using Ketcher as the interactive structure editor for the [Open Reaction Database](https://open-reaction-database.org) and several of our alpha testing submissions involve organometallic catalysts. See the discussion on https://github.com/Open-Reaction-Database/ord-data/pull/14. Support for dative bonds would significantly reduce the burden for users to encode these catalysts when using our web-based [reaction editor](https://editor.open-reaction-database.org).

cc: @connorcoley

**Comment by skearnes** [comment]
Note: it seems that dative bonds are encoded as type 9 in v3000 molfiles: https://sourceforge.net/p/rdkit/mailman/message/34538029/

**Comment by AlexanderSavelyev** [comment]
Technical description: add new dative bond type
1. User can draw a dative bond by choosing new item from the bonds menu
![image](https://user-images.githubusercontent.com/7427808/97152712-5984e100-1782-11eb-9b4a-70a4fa49ab05.png)
2. User can draw a dative bond the same way as with other types of bonds (the only difference is that bond has a direction from first point to the second point) e.g. C->N
![image](https://user-images.githubusercontent.com/7427808/97153045-e92a8f80-1782-11eb-838a-72faf5bf0977.png)
3. The type of the bond in molfile is 9. 
4. No other verification are performed for the bond type

**Comment by AlexanderSavelyev** [comment]
added similar task for hydrogen bonds #72  (type 10) because usually it comes together

**Comment by AndreiMazol** [comment]
Dependencies: #21

**Comment by AndreiMazol** [comment]
Hi @skearnes ,

to support server functions (clean up, layout & etc.) after adding new bond types it is necessary to implement https://github.com/epam/ketcher/issues/258, but this moment it is blocked by Indigo side.
We plan to start work on it in the nearest future.

**Comment by Svetlana-Asinovskaia** [comment]
The current representation of dative bonds is incorrect.

Expected result:
![image](https://user-images.githubusercontent.com/80695128/118467575-90b1e400-b70c-11eb-982b-b93344f8fae7.png)

Actual result:
![image](https://user-images.githubusercontent.com/80695128/118467689-ae7f4900-b70c-11eb-988b-4ab098263d97.png)

**Comment by Svetlana-Asinovskaia** [comment]
The length of dative bonds should be equal to the length of simple single bonds.
Expected result: 
![image](https://user-images.githubusercontent.com/80695128/118505746-5f014300-b735-11eb-939d-d76a54740821.png)

Actual result: 
![image](https://user-images.githubusercontent.com/80695128/118506150-bb646280-b735-11eb-8d4b-ae770ac859b4.png)

**Comment by Svetlana-Asinovskaia** [comment]
Comment about the length of dative bonds is invalid.

**Comment by Svetlana-Asinovskaia** [comment]
A bond is removed when trying to replace it with the dative bond and the console error after the Undo action appears.
_Steps to reproduce:_
1. Create a structure on the canvas (e.g. draw benzene with the 'Templates' tool)
2. With 'Dative bond' tool replace one of the bonds in benzene.
3. Click the 'Undo' button.
Expected result: The bond is replaced with the dative bond.
Actual result: The bond is deleted. the console error after the Undo action appears.
![dative bond](https://user-images.githubusercontent.com/80695128/119499277-40233200-bd6f-11eb-84fc-8b0c18555b7c.gif)

**Comment by Svetlana-Asinovskaia** [comment]
Stereo flag does't disappear after replacing the sterebond with the dative bond. It's possible to open the "Enhanced Stereochemistry" window and set the stereo mark.
![image](https://user-images.githubusercontent.com/80695128/119972890-7228d400-bfbb-11eb-95ab-a20da52660d5.png)

**Comment by Svetlana-Asinovskaia** [comment]
Release/2.3 The issue is verified and closed. 
The problem with stereocenters remaining after replacing the stereobonds with the dative bonds will be solved within https://github.com/epam/ketcher/issues/554
