### ISSUE TITLE
Stereo doesn't update after two bonds merge

### ISSUE THREAD

**Issue by MagomedGasanov** [epam/ketcher#684]
**Steps to Reproduce**
1. Add on canvas benzene structure and stereo bond
2. Try to merge benzene struct and bond like on pic below
![image](https://user-images.githubusercontent.com/57804693/126618706-8da4c93f-0e7c-46d9-b6b7-32241224274e.png)

**Expected behavior**
The stereo disappears after stereo bond turns into a double

**Actual behavior**
The stereo flag and stereo label at the same positions

**Comment by nseufulina** [comment]
Release/2.4 This issue is closed as fixed.
