### ISSUE TITLE
[EPIC] Functional Groups

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#692]
Glossary
--------------------------------------------

- FG - functional group
- Abbreviation - both 1) a shortened textual form of part of a molecule, 2) grouping of atoms and bonds
- Remove Abbreviation - Ungroup, which means removing the inclusion of atoms and bonds in an FG, without removing the atoms and bonds.
- Contract Abbreviation - Show only abbreviation, don't show the FG's atoms and bonds
- Expand Abbreviation - Show the FG's atoms and bonds

1\. As a user, I can place an FG on the canvas by importing it from an external file or by writing the FG's textual description.
================================================================================================================================

The feature must be available via the Open Structure window.
Whether the imported FG appears contracted or expanded must be controlled by the SDS parameter. If SDS parameter has value EXP, the FG must appear expanded. If not, then contracted. If there is no SDS parameter in the textual description of the FG, the FG must appear contracted.

Contracted abbreviation looks as follows:
<img src="https://user-images.githubusercontent.com/88779036/130265008-860d06ea-fd1b-45fd-9872-107f90ff1a50.png" width="100" height=auto>

Expanded abbreviation looks as follows:
<img src="https://user-images.githubusercontent.com/88779036/130265044-159d952e-97fe-4a03-8883-1db15aa12597.png" width="200" height=auto>

The supported file formats for FG import are MOL V2000, MOL V3000, KET.

The behavior of FGs in general
--------------------------------------------

The FG must attach to the molecule via the connection atom(s) specified in the FG textual description.
For instance, PO3 attaches via the phosphorus atom.
<img src="https://user-images.githubusercontent.com/88779036/130265386-7e983dca-9c10-4856-8709-f6c2e10302a9.png" width="200" height=auto>
<img src="https://user-images.githubusercontent.com/88779036/130265367-55c3ebd9-69f7-4c8e-8762-3e5f7e897a87.png" width="200" height=auto>

In the moment of placing the FG, the application must calculate the rotation angle of the FG relative to the molecule so that there is no overlap with existing atoms and bonds.
For instance, attaching PO3:
<img src="https://user-images.githubusercontent.com/88779036/130265571-bc5d47cb-f8b6-4c2c-bd48-cf5c19a2941f.png" width="200" height=auto>
<img src="https://user-images.githubusercontent.com/88779036/130265527-cbdcc148-7fd0-4a7e-957e-87155b28a3fc.png" width="200" height=auto>

A collapsed abbreviation (i.e. grouping) must be bold. As for an expanded abbreviation (i.e. grouping): when the user hovers over any of its atom or bond, the whole group must be highlighted and surrounded with a square (similar to s-group).
<img src="https://user-images.githubusercontent.com/88779036/130265931-eeaa7c16-4e56-4de3-9271-0e2960e6fa00.png" width="200" height=auto>

2\. As a user, I can place an FG on the canvas by loading it from Ketcher's library.
====================================================================================

A button (named 'Functional Groups') invoking the 'Functional Groups' window must be placed next to the 'Custom Templates' button. Icon design: TO BE DEFINED
A user must be able to choose an FG in the window. 

The window's UI should be similar to the UI of the 'Custom Templates' window.

The window must contain:
-   'Filter' field
-   'Save to SDF' button
-   'Cancel' button
-   'OK' button
-   Each FG's title (which is also the abbreviation) and image
-   No 'Edit' button in this version
-   Only the 'Functional Groups' tab in this version

The user must be able to add FGs to the library by changing the SDF file.
An FG added from the library must initially appear contracted.

3\. As a user, I can expand, contract and remove an FG abbreviation (i.e. grouping).
====================================================================================

3.1. Features for contracting, expanding, removing abbreviations (i.e. groupings) must be available under one group of buttons.
------------------------------------------------------------------------------------------------------------------------------

The group of buttons should be similar to the Reactions group of buttons.
Icons design: TO BE DEFINED

The group of buttons must include:
1.  Expand / Contract Abbreviation Tool
2.  Remove Abbreviation Tool

3.2. The user must be able to expand and contract an abbreviation (i.e. grouping).
----------------------------------------------------------------------------------
The Expand / Contract Abbreviation Tool:
When the user uses the Expand / Contract Abbreviation Tool:
1.  Hovering over a contracted abbreviation (i.e. grouping) must highlight it.
2.  Hovering over any atom or bond in the expanded group must highlight and surround with a square the group, similar to s-group:
<img src="https://user-images.githubusercontent.com/88779036/130265931-eeaa7c16-4e56-4de3-9271-0e2960e6fa00.png" width="200" height=auto>

3.  Left-clicking a contracted abbreviation (i.e. grouping) must expand it.
<img src="https://user-images.githubusercontent.com/88779036/130265044-159d952e-97fe-4a03-8883-1db15aa12597.png" width="200" height=auto>

4.  Left-clicking any atom or bond in the expanded group must contract the group to its abbreviation (i.e. grouping). 
<img src="https://user-images.githubusercontent.com/88779036/130265008-860d06ea-fd1b-45fd-9872-107f90ff1a50.png" width="100" height=auto>

3.3. The user must be able to remove an abbreviation (i.e. ungroup).
--------------------------------------------------------------------

The Remove Abbreviation Tool:
When the user uses the Remove Abbreviation Tool:
1. Hovering over a contracted abbreviation (i.e. grouping) must highlight it.

2. Hovering over any atom or bond in the expanded group must highlight and surround with a square the group, similar to s-group:
<img src="https://user-images.githubusercontent.com/88779036/130265931-eeaa7c16-4e56-4de3-9271-0e2960e6fa00.png" width="200" height=auto>
3.  Left-clicking (1) the contracted abbreviation or (2) any atom or bond in the expanded group - must remove the abbreviation (i.e. ungroup). After removing the abbreviation, the FG must become expanded.
The Remove Abbreviation Tool does not removes the atoms and bonds. It only removes the inclusion of atoms and bonds in an FG.

4\. As a user, I can do certain actions with an FG only after removing abbreviation (i.e. ungrouping).
====================================================================================================

The interaction of FGs with other Ketcher's features
--------------------------------------------

Rotate Tool, Horizontal Flip, Vertical Flip, Lasso Selection, Rectangle Selection: allowed to be applied to individual atoms and bonds of the FG.
<img src="https://user-images.githubusercontent.com/88779036/130266997-1f7626a3-74af-4dd0-b120-b637c207062a.png" width="200" height=auto>

Fragment Selection: the whole FG must get selected.
<img src="https://user-images.githubusercontent.com/88779036/130267042-e00308c4-3abb-4eaa-a685-177d916aeaa4.png" width="200" height=auto>
Erase: individual atoms (bonds) and adjacent bonds (atoms) must get removed (similar to templates). Removing one atom or bond from and FG does not remove the whole FG. 
<img src="https://user-images.githubusercontent.com/88779036/130267161-fce10c9b-8ceb-4b28-a9f4-9d51048351b3.png" width="200" height=auto>
Dragging one atom or bond does not cause dragging of the whole FG.
<img src="https://user-images.githubusercontent.com/88779036/130267122-9b9ed5fa-2603-4d75-9336-21a57aa21d3a.png" width="250" height=auto>
Aromatize, Dearomatize, R-Group Label Tool, R-Group Fragment Tool, Attachment Point Tool, Stereochemistry, S-Group, Data S-Group: TO BE DEFINED
Bonds, Chain, organic compound toolbar, chemical elements toolbar, Custom Templates, Charge Plus. Charge Minus: application to an FG must be forbidden. These features must be allowed for the FG's atoms and bonds only after removing abbreviation (i.e. ungrouping).
Other tools: allowed 

When the user tries to apply the forbidden tools to an FG
--------------------------------------------

When the user tries to apply the forbidden tools to an FG, s/he must be given a choice in a modal window to either (1) remove the abbreviation (i.e. ungroup), or (2) keep the abbreviation.
The window's text: "Do you want to remove the abbreviation? It is required for adding atoms and bonds to the group."
The buttons: Yes (default), No.
If the group was contracted, in the moment of removing abbreviation it expands.

5\. As a user, I can export an FG to a MOL file.
================================================

The supported file formats for the FG export must be MOL V2000, MOL V3000, KET.

**Comment by MuratSafarov1** [comment]
@AndreiMazol @nseufulina 
**20 August BA update**
1. **Glossary**: changed to "Remove Abbreviation - Ungroup, which means removing the **inclusion** of atoms and bonds in an FG, **without removing** the atoms and bonds."
2. **User story 1:** changed to "Whether the imported FG appears **contracted or expanded** must be controlled by the **SDS** parameter. If SDS parameter has value EXP, the FG must appear expanded. If not, then contracted. If there is no SDS parameter in the textual description of the FG, the FG must appear contracted."
3. **User story 1:** merged here "The behavior of FGs in general" from the user story 2
4. **Requirement 3.3:** added "The Remove Abbreviation Tool **does not removes** the atoms and bonds. It only removes the **inclusion** of atoms and bonds in an FG"
5. **User story 4:** added "**The interaction of FGs with other Ketcher's features**"

**Comment by PavelSnadin** [comment]
BA Update 29/09/21
**User story 1:**  The description of the ability to open a FG by pressing a combination of hot keys has been added.

**Comment by Alena-Guznischeva** [comment]
User Story no.2 updated for the FG window requirements:

~~Only the 'Functional Groups' tab in this version~~ _No tabs should be presented.
All Functional groups must be displayed when the window is opened.
When entering the text to the Filter field the list of Functional groups should be filtered so that only FGs with the name containing the row entered into the field will remain. If there is no FGs satisfying the text entered, the window should be displayed as empty with OK button disabled_
