### ISSUE TITLE
Implement resizing of arrows

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#698]
This moment all arrows have fixed direction and size. 
It is necessary to allow users to change these parameters while adding/updating arrows. 

For more details please look at Point 3 in #695 .

**Comment by nseufulina** [comment]
**Arrow is displayed incorrectly when file is opened.** 

The same with all formats, except .ket. (molv2000, molv3000, daylight smiles, extended smiles, cml, smarts formats)

Scenario1

1. Open 
[reaction_dif_prop.zip](https://github.com/epam/ketcher/files/6945228/reaction_dif_prop.zip)

Expected result:

Arrow is displayed correctly (default size, position and type)

Actual result:

Arrow is displayed incorrectly.


Scenario2

1. Create two structures

2. Choose Arrow Open Angle Tool

3. Click on the canvas between structures

4. Save the reaction as in MolV2000 format.

5. Open saved reaction.

Arrow is displayed correctly (default size, position and type)

Actual result:

Arrow is displayed incorrectly.


Scenario3

1. Click Open File and paste

C1=CC=CC=C1>>C1=CC=CC=C1 

Arrow is displayed correctly (default size, position and type)

Actual result:

Arrow is displayed incorrectly.


**Arrow is displayed incorrectly when indigo tools are applied** 

1. Create reaction (structures and arrow)
2. Click Auto-mapping button
Arrow is displayed correctly (default size, position and type)

Actual result:

Arrow is displayed incorrectly.

The same with other tools: dearomatize, aromatize, clear, lauout, calculate CIP.

**Comment by nseufulina** [comment]
Reaction is opened incorrectly when loaded as fragment.

1. Open reaction file as load as fragment 
2. Click "ok" on the modal window
3. Click on the canvas
Expected result:
No alert in the modal window. Reaction is pasted with arrow
Actual result:
step 2 - alert "TypeError: Cannot read property 'add' of undefined". Reaction is pasted without arrow. Reaction is copied as .mol in the Clipboard.
