### ISSUE TITLE
Styles are not component based

### ISSUE THREAD

**Issue by mustafacanp** [epam/ketcher#699]
**Steps to Reproduce**
1. Create a new react project.
2. Import `ketcher-react` and styles from the library (`ketcher-react/dist/index.css`).
3. Open dev tools on the browser and check global element styles.

**Expected behavior**
Styles should be component-level. Styles should be scoped by the main class that has a specific name.

**Actual behavior**
Styles overwriting global styles.

**Screenshots**
![Screenshot 2021-07-28 112250](https://user-images.githubusercontent.com/16281650/127290869-dd9c7104-9932-4d5f-af84-11523770d3ff.png)

**Desktop:**
 - All OSs and all browsers

**Smartphone:**
 - All OSs and all browsers

I want to use the `ketcher-react` plugin as a component in a page with other contents but it's overwriting global styles and that breaks the page.

**Comment by AndreiMazol** [comment]
It is not a bug. All changes related to isolation of component styles will be done in scope [epic: modularity](https://github.com/epam/ketcher/labels/epic%3A%20modularity) . Issue has been converted to enhancement.

**Comment by mustafacanp** [comment]
Okay cool. Looks like we'll have this in version 2.4.0.
