### ISSUE TITLE
Add warning message when saving structure with QUERY in Smiles format

### ISSUE THREAD

**Issue by MagomedGasanov** [epam/ketcher#712]
- The SMILES format does not support query attributes (neither bonds nor atoms)
- Now when we are trying to save structure with query in SMILES the only message that appears is:

    ![image](https://user-images.githubusercontent.com/57804693/129026042-0830e07f-6e6e-4742-aeac-f993908ed42d.png)

**TODO**: 
Needs to add a warning message that the QUERY attributes will be lost

**Additional**
To select a query attribute for an atom/bond, double-click on them using the select tool

**Comment by Alena-Guznischeva** [comment]
The message should be: "Structure contains query properties of atoms and bonds that are not supported in the SMILES and SMART. Query properties will not be reflected in the file saved."

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
