### ISSUE TITLE
Add support for hydrogen bonds

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/ketcher#72]
Add new hydrogen bond type

1. User can draw a hydrogen bond by choosing new item from the bonds menu
![image](https://user-images.githubusercontent.com/7427808/97155791-eb8ee880-1786-11eb-97eb-8b059bc146c2.png)
2. User can draw a hydrogen bond the same way as with other types of bonds
![image](https://user-images.githubusercontent.com/7427808/97155931-11b48880-1787-11eb-9dc1-39c4b4dad807.png)
3. The type of the bond in molfile is 10
http://help.accelrysonline.com/ulm/onelab/1.0/content/ulm_pdfs/direct/reference/ctfileformats2016.pdf
4. No other verification are performed for the bond type

**Comment by AndreiMazol** [comment]
Dependencies: #21

**Comment by Svetlana-Asinovskaia** [comment]
The current representation of dative bonds is incorrect.

Expected result:
![image](https://user-images.githubusercontent.com/80695128/118468205-3402f900-b70d-11eb-9599-2c307f202a2d.png)

Actual result:
![image](https://user-images.githubusercontent.com/80695128/118468400-657bc480-b70d-11eb-8b0b-3967f1a0bd2c.png)

**Comment by Svetlana-Asinovskaia** [comment]
The length of hydrogen bonds should be equal to the length of simple single bonds.

Expected result:
![image](https://user-images.githubusercontent.com/80695128/118506658-2f066f80-b736-11eb-9781-f33ae7625205.png)

Actual result:
![image](https://user-images.githubusercontent.com/80695128/118506855-5bba8700-b736-11eb-9fec-753bac9ac11a.png)

**Comment by Svetlana-Asinovskaia** [comment]
Comment about the length of hydrogen bonds is invalid.

**Comment by Svetlana-Asinovskaia** [comment]
Console error after deleting the bond.

_Steps to reproduce:_
1. Create a structure (e.g. select cyclohexane from the Templates).
2. Sprout the Single Up bond from any atom.
3. Replace the Single Up bond with the hydrogen bond.
4. Delete the structure with the 'Erase' tool.
_Expected result:_ The structure is deleted without errors.
_Actual result:_ Console error appears.
![2021-05-25_11h14_32](https://user-images.githubusercontent.com/80695128/119494333-deac9480-bd69-11eb-8891-4c069d744d2e.gif)

**Comment by Svetlana-Asinovskaia** [comment]
Release/ 2.3 The issue is verified and closed. Currently it's not possible to use the Calculated values option for the structures with the hydrogen bonds (It will be solved within https://github.com/epam/ketcher/issues/540)
