### ISSUE TITLE
Prepare functional groups list

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#757]
FGs should be delivered as a fg.sdf file. This file should include all FGs provided in biovia.

The structure of sdf is the following:

...
$$$
{FG name}
  {mol}
>  <group>
{group name} 

>  <atomid>
{attachment point id}

$$$
...

**Comment by vitalgerko** [comment]
Reopen.
Need to be updated 'Bn' FG parameters 
![2021-09-29_10h18_44](https://user-images.githubusercontent.com/90637536/135229627-612f092e-8da3-44b3-b8ca-8b3b9b487a25.png)

**Comment by vitalgerko** [comment]
Reopen
FGs 'CO2Et, CO2Pr, indole, ster'  are prepared in Expanded abbreviation.
All FGs should be in Contracted abbreviation (see #692  point 2: "An FG added from the library must initially appear contracted.")
