### ISSUE TITLE
Questions about the Indigo service

### ISSUE THREAD

**Issue by Doidel** [epam/ketcher#76]
From the docs, it seems like Ketcher 2.0 requires [a running service](https://lifescience.opensource.epam.com/indigo/service/index.html). However, the download link leads nowhere. Also, the "download ketcher" link on your website doesn't provide this service, yet [the source](https://github.com/epam/ketcher/blob/master/src/script/api.js) seems to indicate that such a service is needed. 

So my questions concerning the service are:

- Does Ketcher 2.0 still require a service?
- Can I access the source, or is it only available as standalone Docker package?

Thanks!

**Comment by AndreiMazol** [comment]
Dear @Doidel, 

Thank  you so much for your questions and your interest in Kecher.

The list of features provided by Ketcher can  be found by [the link](https://github.com/epam/ketcher). Unfortunately, some of them are required a running indigo service as you mentioned above. The link to  Indigo API can be provided as an additional  query parameter, for example: ...?api_path={link-to-indigo-service}. 

As we received multiple requests about providing Ketcher as a standalone solution we have already include it into  our roadmap. Please follow us and you will  see it in the one of the upcoming releases.

Regarding your second question, please find the link to  Indigo Service repository bellow:
[GitHub repository](https://github.com/epam/Indigo/tree/master/utils/indigo-service)

Please contact us if you  have any additional questions.

Best regards,
Ketcher development team

**Comment by Doidel** [comment]
Got it, thanks for all the info!
