### ISSUE TITLE
Slider (width) is visible in the left toolbar (Firefox browser)

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#762]
**Steps to Reproduce**

1. Open Ketcher in Firefox browser.

**Expected behavior**
There's no slider (width) in the left toolbar

**Actual behavior**
Slider (width) is visible in the left toolbar **(see atach. screen video).**

https://user-images.githubusercontent.com/90637536/133423130-2028538e-6880-4952-8bcd-630718829aee.mp4

![Slider (width) is visible in the left toolbar (Firefox browser)](https://user-images.githubusercontent.com/90637536/133423201-c964116a-6e5b-4f14-82f0-1cadaa1f0021.png)

**Desktop:**

OS: Windows
Browser: Firefox Version 92.0

**Additional context**
The slider disappears when browser window is moved to a larger screen (in video: on the right - a small screen, on the left: a large screen)

**Comment by vitalgerko** [comment]
@r1z3rISGOD  Kirill, 
Left window: Firefox
Right window: Chrome
Buttons size is smaller in Firefox and the right edge of buttons is cropped

![2021-09-16_17h03_15](https://user-images.githubusercontent.com/90637536/133626683-20fd361a-d4e8-43f5-a52b-3551d7777735.png)

**Comment by r1z3rISGOD** [comment]
@vitalgerko This problem cannot be solved in normal ways due to the fact that the problem is related to bug in Firefox

**Comment by vitalgerko** [comment]
Release/2.4 Closed as fixed.
