### ISSUE TITLE
'Help (?)' and 'About' buttons disappear when the browser window is narrowed 

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#765]
**Steps to Reproduce**
1. Open Ketcher.
2. Narrow your browser window.

**Expected behavior**
'Help (?)' and 'About' buttons are displayed in a narrow browser window.  

**Actual behavior**
'Help (?)' and 'About' buttons do not appear in a narrow browser window **(see atach. screen video).**

https://user-images.githubusercontent.com/90637536/133461779-94e885d2-1c83-425d-ac4f-21ad8dba9888.mp4

**Desktop:**
OS: Windows
Browser: Chrome Version 93.0.4577.63, IE Version 20H2 (build 19042.1165), Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by AndreiMazol** [comment]
It is expected behavior.
