### ISSUE TITLE
Overlaping label values when select structure using 'S-Group' button

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#775]
**Steps to Reproduce**

1. Launch Ketcher.
2. Chose 'Cyclooactane' and click on canvas.
3. Click the 'S-Group' button and select 'Cyclooactane'.
4. Chose Type 'Multiple Groupe' and click 'Ok' button.
5. Select structure, Chose Type 'SRU Polymer', click 'Ok' button.
6. Select structure, Chose Type 'Superatom', click 'Ok' button.

**Expected result:**
Old label values are deleted, only the new value is displayed

**Actual behavior:**
Old label values ​​are not deleted. The values ​​overlap each other.

https://user-images.githubusercontent.com/90637536/133800876-a3f44e70-ea4b-496d-b842-5e662dc1390e.mp4

**Desktop:**

OS: Windows
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by aleksandrgordeev1** [comment]
Discussed with @AlexanderSavelyev. The reason of overlapping is creating new S-Group with the old one inside, so there are labels of two and more groups.
This should be fixed in https://github.com/epam/ketcher/issues/784
