### ISSUE TITLE
'Horizontal flip' and 'Vertical flip' buttons are not highlighted in black when you click on them

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#776]
**Steps to Reproduce**

1. Launch Ketcher.
2. Open any reaction.
3. Click the 'Horizontal flip' button.
4. Click the 'Vertical flip' button.

**Expected behavior**
Buttons highlighted in black when you click on them. 
All buttons should have the same click behavior, i.e. should be highlighted by black.

**Actual behavior**
'Horizontal flip' and 'Vertical flip' buttons are not highlighted in black when you click on them.

https://user-images.githubusercontent.com/90637536/133802713-2595868f-fd3e-4a88-b7b1-4feafa362d20.mp4

**Desktop:**

OS: Windows
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by Alena-Guznischeva** [comment]
Seems to be the correct system behavior: clicking on those icons immediately leads to applying the action for the canvas content. The rest of the operations should be highlighted as they require additional clicking or other actions on the canvas.
