### ISSUE TITLE
S-Group: incorrect rendering when using structures from Template pallete and different options from S-Group Properties window

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#797]
**Steps to Reproduce**
1. Launch Ketcher.
2. Chose 'Cyclooactane' (or another structure from Template pallete) and click on canvas.
2. Click the 'Data S-Group' button and select Cyclooactane on canvas. 
3. Choose 'Fragment' option from 'Context' drop-down list and click the 'OK' button.
4. Select Cyclooactane on canvas, Choose 'Bond' option from 'Context' drop-down list and click the 'OK' button.
5. Select Cyclooactane on canvas, Choose other options from 'Context' drop-down list and click the 'OK' button.

**Expected behavior**
Correct rendering (like in case when using Chain structure and different options from S-Group Properties window).

**Actual behavior**
Incorrect rendering.
https://user-images.githubusercontent.com/90637536/134645600-f0febf0b-6950-46a3-896e-6986901ce98b.mp4

**Desktop:**

OS: Windows
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Additional context**
Reproduce in version 2.3
https://lifescience.opensource.epam.com/ketcher/demo/ketcher_2_3_remote.html
https://lifescience.opensource.epam.com/ketcher/demo/ketcher_2_3_standalone.html

**Comment by AllaZhbanova** [comment]
fixed, tested v.2.4
