### ISSUE TITLE
Template Library: there is no limit for input symbols when editing structure name or add new template in library

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#799]
**Steps to Reproduce**

**1st case**
1. Open Ketcher.
2. Create any structure on canvas.
3. Click the 'Save as' button.
4. Click the 'Save to Templates' button
5. Input enormous value in 'Template name' field.
6. Click the 'OK' button.
7. Click the 'Customs Templates' button.
8. Go to 'User templates'

**2nd case**
1. Open Ketcher.
2. Click to 'Edit' button on any template card.
3. Input enormous value in 'Template name' field.
4. Click the 'OK' button.

**Expected behavior**
The field 'Template name' has a limit on the number of entered/copied characters.
Alena G: Field should be limited to 128 characters. Pasting text with more than 128 characters should result in having only the first 128 characters in the field. Spaces in the beginning and end of the string entered should be trimmed when saving is confirmed. User should not be able to save template with name only having spaces. 

**Actual behavior**
There is no limit for input symbols when editing structure names or add a new template in library.
Large text overlaps other templates.

https://user-images.githubusercontent.com/90637536/134677165-1ba5ea59-1ffe-4873-8aa9-6db3aea31cd0.mp4

**Desktop:**

OS: Windows
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by Alena-Guznischeva** [comment]
Added the requirements for expected result: 
_Alena G: Field should be limited to 128 characters. Pasting text with more than 128 characters should result in having only the first 128 characters in the field. Spaces in the beginning and end of the string entered should be trimmed when saving is confirmed. User should not be able to save template with name only having spaces._

**Comment by vitalgerko** [comment]
Release/2.4 Closed as fixed.
