### ISSUE TITLE
Setting initial molecule

### ISSUE THREAD

**Issue by onoufriosm** [epam/ketcher#806]
**Steps to Reproduce**
See example on https://codesandbox.io/s/twilight-snow-2gzqv?file=/src/App.tsx

I'm trying to use `setMolecule` to initialise the editor (using `StandaloneStructServiceProvider`)

The string passed to `setMolecule` was a copy paste from `ketcher.getMolfileAsync()` of a previous drawing. (Even passing an empty string fails though).

**Expected behavior**
To setMolecule without breaking (or maybe there is another way to do that?)

**Actual behavior**
`.setMolecule` breaks -> `struct.sgroups.some is not a function`

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 93

**Comment by japhill** [comment]
I have the same issue on my system.  I tested and added Array.from() around struct.sgroups ... like this Array.from(struct.sgroups).some and it worked.
it looks like if there are no sgroups, it is a Map and some doesn't seem to work on a Map

**Comment by AndreiMazol** [comment]
Hi @onoufriosm ,

thank you  for your interest to Ketcher. 
The issue has been included to release 2.4 so it will be delivered approximately at the end of October.

Best regards,
Ketcher team

**Comment by onoufriosm** [comment]
Thanks for the replies! Is there a way to get around this for now until the next release?

@japhill , @AndreiMazol Can you point me where in the code to do this? I can then fork the repo and fix it myself until the next release.

**Comment by AndreiMazol** [comment]
I do  not see any workarounds right away. In case workaround is identified we let you know.

**Comment by AndreiMazol** [comment]
Dear @onoufriosm , @japhill ,

The issue has been analyzed and we decided that it is really critical that is blocked work with Ketcher. So as a result it is delivering as a part of hotfix 2.3.2 on Tuesday, 5 Oct, 2021.

Please inform us if you  have any other critical problems to include them into the nearest hotfix release.

Thank  you  so much for your engagement.

Best regards,
Ketcher team

**Comment by vitalgerko** [comment]
Release/2.3.2 Closed as fixed.
