### ISSUE TITLE
Generate structure from InChI String - Incorrect structure rendering in Remote mode

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#824]
**Steps to Reproduce**
1. Launch Ketcher in Remote mode.
2. Click the Open button.
3. Type "InChI=1/C11H12/c1-3-5-7-9-11-10-8-6-4-2/h1H,5,7-8,10H2,2H3" into dialog field.
4. Click OK.

**Expected behavior**
The correct structure - chain string that contains some triple bonds - appears on canvas. 

![image](https://user-images.githubusercontent.com/90637536/136027612-7bba8e66-8e71-4cfc-9ba6-d120a5eda26e.png)

**Actual behavior**

![Actual behavior](https://user-images.githubusercontent.com/90637536/136028360-ae482552-1bb8-483a-8735-0911d9d9c6ff.png)

**Desktop:**

OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Additional context**
Not reproduce in 3.2 version.

**Comment by AllaZhbanova** [comment]
fixed, tested 2.4
