### ISSUE TITLE
surpressing window.alert popups

### ISSUE THREAD

**Issue by jaohbib** [epam/ketcher#83]
I would like to surpress any window.alert calls from Ketcher currently i recive the following  when i load ketcher 
![sllert](https://user-images.githubusercontent.com/72259105/98367962-d0e62a80-2036-11eb-80cc-f43f91f4bad3.PNG)

**Comment by AndreiMazol** [comment]
Dear @jaohbib ,

thank  you for your interest to Ketcher.

This issue has been marked as Bug and it will be fixed in the nearest release.

Best regards,
Ketcher team
