### ISSUE TITLE
Benzene ring loses circle when exporting

### ISSUE THREAD

**Issue by RichardABurton** [epam/ketcher#838]
When saving a benzene ring or benzene ring containing structure as a PNG image the conversion to an image removes the inner ring and puts a tiny curle in its place. See attached images.

![image](https://user-images.githubusercontent.com/92362029/136917091-77ef3a09-c8f3-4d3b-8def-fe48cb540c15.png)

![image](https://user-images.githubusercontent.com/92362029/136917131-cde1709b-fb4b-4213-bb15-a835be739983.png)

**Comment by ViktoriiaFedotkina** [comment]
Related issue https://github.com/epam/Indigo/issues/523

**Comment by AllaZhbanova** [comment]
Fixed, tested in standalone mode ketcher v.2.4
