### ISSUE TITLE
Add ellipse simple object

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#85]
As a Ketcher collaborator I'd like to implement drawing tool in Ketcher to add capability for user to draw ellipse elements on canvas.

**Comment by AndreiMazol** [comment]
In scope of this task are:

dragging created objects
saving objects as .ket file
initializing canvas by simple objects while reading .ket file
scaling of every standalone object with keeping aspect ratio
showing bounds of new object as dotted-line while users are scaling/moving/etc it
informing users about losing simple objects while users try to save results not in .ket file
*.ket - internal Ketcher format

**Comment by KseniiaSemenishcheva** [comment]
Issue is verified.
