### ISSUE TITLE
Getting static files from ketcher-react package itself

### ISSUE THREAD

**Issue by mustafacanp** [epam/ketcher#857]
Can you get static files from the build folder of ketcher-react instead of using `staticResourcesUrl` and getting files with `prefetchStatic`? All the static files belong to this package in the end.

`library.sdf` file might be an exception since it may include project-specific custom molecule templates, and you can get the `library.sdf` file as a property for `Editor` instance if you get rid of `staticResourcesUrl` logic and you can import all other files in the usual way.

**Comment by r1z3rISGOD** [comment]
In scope of release 2.4 'staticResourcesUrl' will be used only for sdf files. But in scope of release 2.5 we are plan to change work logic with external files.
cc: @mustafacanp

**Comment by AllaZhbanova** [comment]
Reopened: Help links leads to page with 404 error. Tested on 2.4
