### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'pp') 

### ISSUE THREAD

**Issue by Pandaaaa906** [epam/ketcher#859]
**Steps to Reproduce**
1. using ketcher react
2. ketcher.loadMolecule(moltext) // in attachment

**Expected behavior**
![image](https://user-images.githubusercontent.com/18494105/138393854-f0772ed4-9eb4-43ab-be49-cb3796d03c5d.png)

**Actual behavior**

SGroup.ts:178 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pp')
    at Function.getOffset (SGroup.ts:178)
    at index.modern.js:8327
    at Map.forEach (<anonymous>)
    at index.modern.js:8326

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Chrome
 - Version 79
    "ketcher-core": "^1.1.2",
    "ketcher-react": "^2.3.2",
    "react": "^17.0.1",

**Additional context**
[moltext.txt](https://github.com/epam/ketcher/files/7394267/moltext.txt)

**Comment by r1z3rISGOD** [comment]
It was decided to fix the problem in the hot fix, since the 2.4 release is delayed
cc: @Pandaaaa906

**Comment by AllaZhbanova** [comment]
Fixed, tested 2.3, 2.4

**Comment by ForumT** [comment]
This same issue is coming in ketcher-react even in the latest version
