### ISSUE TITLE
Add possibility to hide elements by passing query parameter

### ISSUE THREAD

**Issue by AndreiMazol** [epam/ketcher#862]
This moment it is necessary to  pass 'buttons' property into <Editor> component to  hide controls. It would be great if ready-to-run app provides an ability to  update this property by passing 'editorButtons' query parameter:

`https://localhost:3000?editorButtons={}`

**Comment by IliaVeselov** [comment]
https://kb.epam.com/display/EPMLSOP/Hiding+items+on+the+control+panel+and+left+tool+bar

**Comment by AllaZhbanova** [comment]
https://github.com/epam/ketcher/issues/928
