### ISSUE TITLE
'S-Group Properties' window - 'Absolute' radio button checked in all case 

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#866]
**Steps to Reproduce**

1. Launch Ketcher.
2. Create chain structure on canvas.
3. Click the 'Data S-Group' button.
4. Click the canvas, press and highlighter all previously created structure.
5. Chouse 'abs' value (or another) in 'S-Group Properties' window and chouse 'Relative' options in the bottom of window.
6. Click the 'OK' button.
7. Click the 'abs' symbols. 
8. Repeat steps 4-7 with 'Attached' options in the bottom of window.

**Expected behavior**
There is an actual radio button checked  (Relative/ Attached). 

**Actual behavior**
'Absolute' radio button checked. 

https://user-images.githubusercontent.com/90637536/138726885-045751b1-2cea-4834-b947-c4c366681a32.mp4

**Desktop:**
OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
fixed, tested v. 2.4
