### ISSUE TITLE
Functional groups - When opening file (V3000 format) with Contracted and Expanded FG's all FG's displayed in Contracted Abbreviation

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#876]
**Steps to Reproduce**
1. Launch Ketcher.
2. Create two FG's (first in Contracted, second in Expanded Abbreviation)
3. Save as V3000 Molfile.
4. Open previously saved file. 

**Expected behavior**
One of FG's displayed in Contracted Abbreviation, the second one in Expanded Abbreviation.

**Actual behavior**
Both FG displayed in Contracted Abbreviation.

**Desktop:**
OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
