### ISSUE TITLE
Functional Groups - replacement by atom and adding a bond to contracted FG

### ISSUE THREAD

**Issue by r1z3rISGOD** [epam/ketcher#878]
It would be nice to add the ability to replace contracted FG by another atoms and adding a bond to contracted FG.

AG: 
1. Forbid starting bond from the FG to make sure they are list elements. 
2. There can be only 1 bond to FG, linking to the zero atom in the group. 

The following scenario should work: add template to the canvas, separately add FG to the canvas. It should be able to add bond from the template node to the FG on the canvas, if there is no other bonds to this FG.

**Comment by Alena-Guznischeva** [comment]
Added the part with business rules for bonding.

**Comment by AllaZhbanova** [comment]
Tested v.2.4
