### ISSUE TITLE
Custom Templates - Templates duplicated when user saving templates with the same name

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#889]
**Steps to Reproduce**

1. Launch Ketcher.
2. Save to User Templates two structures with the same name and one structure with another name.
3. Click the 'Custom Templates' button and try to choose the user template.

**Expected behavior**
Correct behavior templates library.
Users can not create two templates with the same name.

**Actual behavior**
Templates duplicated

https://user-images.githubusercontent.com/90637536/139261421-29e51f8d-09c8-48f5-a41f-1412b1b7ffc7.mp4

**Desktop:**
OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by AWeiJie** [comment]
Excuse me, how do you run the project? Can you share the next steps

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
