### ISSUE TITLE
User Templates - Wrong displaying functional groups ( Expanded / Contracted)

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#890]
**Steps to Reproduce**

1. Launch Ketcher.
2. Add on canvas any structure from Custom Templates ('D-Ribulose' for example).
3. Add to 'D-Ribulose' any FG ('Bn' for example).
4. Expand FG.
5. Save to User Templates.
6. Save to User Templates structure with Contracted FG. 
7. Open User Templates  

**Expected behavior**
First structure displayed with Expanded FG, second with Contracted FG.

**Actual behavior**
First structure displayed with Contracted FG, second with Expanded FG.

https://user-images.githubusercontent.com/90637536/139264710-c780dd36-6253-47bb-bcb2-50350d716231.mp4

**Desktop:**
OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by r1z3rISGOD** [comment]
Unrepeatable on version 181-gcf690d63

**Comment by AllaZhbanova** [comment]
Not reproducible
Tested on v. 2.4
