### ISSUE TITLE
Functional Groups - Incorrect behavior when copying and pasting FG's

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#892]
**Steps to Reproduce**
1. Launch Ketcher.
2. Add on canvas some FG's from library.
3. Select FG's using 'Lasso Selection' Tool or 'Rectangle Selection' Toll.
4. Copy selected structures (ctrl+C).
5. Paste copied structures (ctrl+V).

**Expected behavior**
Copy / Paste options work correctly. All selected FG's pasted on canvas.

**Actual behavior**
Error 'Cannot read of properties of undefined (reding 'data')" appears on the front.
When the user selects two FG's three structures are pasted on canvas.  

https://user-images.githubusercontent.com/90637536/139411216-4f321cd6-b504-4845-9206-b4ca87ae7b9c.mp4

**Desktop:**
OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
Fixed, tested v. 2.4
