### ISSUE TITLE
New design of modal windows

### ISSUE THREAD

**Issue by r1z3rISGOD** [epam/ketcher#894]
It is required to redesign all modal windows of the application

OOS: error window

This issue if for mild modal windows change for 2.4. General redesign will be conducted later. 
Acceptance criteria: GIVEN Ketcher user WHEN looking at all the Ketcher modal windows THEN I see rounded corners and blue buttons aligned on the right side of the windows just like in Functional Group confirmation windows. 

Modal windows in scope:
1) File opening, FIle save, 
2) Templates library, Template edit (save as Template)
3) Settings, Help, About
4) R Group Labe & Fragment tools, Attachment Pints tool, S Group, S Group Tool
5) Periodic table + Extended table
6) Structure check, Calculated Values
7) Bond properties, Atom properties

**Comment by AllaZhbanova** [comment]
Tested v. 2.4
