### ISSUE TITLE
Functional Group - Errors appear when added FG's to the same location on canvas

### ISSUE THREAD

**Issue by vitalgerko** [epam/ketcher#901]
**Steps to Reproduce**
1. Launch Ketcher.
2. Add multiple FG's on canvas at the same location from the library.

**Expected behavior**
Multiple FG's are displayed on canvas.

**Actual behavior**
Errors appear in the browser console.

https://user-images.githubusercontent.com/90637536/139630674-d6b83af0-32fe-492a-a5a4-1173b5960223.mp4

**Desktop:**
OS: Windows 10
Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
