### ISSUE TITLE
Functional Groups - Error appears when we try to draw FG inside other structures 

### ISSUE THREAD

**Issue by r1z3rISGOD** [epam/ketcher#904]
**Steps to Reproduce**
1. Draw any struct (Cyclooctane ring for example)
2. Attach FG in contracted form to any atom of this struct
3. Drag mouse inside the struct

**Expected behavior**
FG is drawn on top of other structures

**Actual behavior**
Structures merged and when we try to use Undo button - app crashed

**Comment by AllaZhbanova** [comment]
Fixed, tested v. 2.4
