### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by MichelML** [epam/ketcher#91]
Lots of active development recently, I was wondering when the next release is planned and which new features will be included.

Thanks

**Comment by AndreiMazol** [comment]
Dear @MichelML ,

You absolutely right. Ketcher team is working towards new release. That release will be mostly  dedicated to increase usability of Ketcher and moving it to modern rails.

Stay turned and soon you'll see notes about new version.

Best regards,
Ketcher team

**Comment by MichelML** [comment]
Thanks @AndreiMazol , will leave open in case someone else have the same question, but feel free to close
