### ISSUE TITLE
Error is shown when try to save structure with added text

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#911]
**Steps to Reproduce**
1. Open Ketcher
2. Add any structure
3. Select "Add Text" tool
4. Insert any text
5. Add text
6. Click Save icon

**Expected behavior**
Save window is shown without error

**Actual behavior**
Error is shown

**Screenshots**
![Error](https://user-images.githubusercontent.com/93334478/139834589-978cea54-2b62-4da8-afd2-aa45ea4be562.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by AWeiJie** [comment]
> **重现步骤**
> 
> 1. 打开 Ketcher
> 2. 添加任何结构
> 3. 选择“添加文本”工具
> 4. 插入任何文本
> 5. 添加文字
> 6. 单击保存图标
> 
> **预期行为** 保存窗口显示没有错误
> 
> **显示实际行为** 错误
> 
> **截图** ![错误](https://user-images.githubusercontent.com/93334478/139834589-978cea54-2b62-4da8-afd2-aa45ea4be562.png)
> 
> **桌面：**
> 
> * 操作系统：Windows 10
> * 浏览器：Chrome 93.0.4577.63 版、Firefox 92.0 版、Microsoft Edge 93.0.961.47 版

Excuse me, how do you run the project? Can you share the next steps

**Comment by AndreiMazol** [comment]
Hi @AWeiJie ,

the detailed instruction how to build App can be found here https://github.com/epam/ketcher/blob/master/DEVNOTES.md

**Comment by ElenaOdnoshivkina** [comment]
Related issue: https://github.com/epam/Indigo/issues/530

**Comment by AllaZhbanova** [comment]
Fixed, tested on 2.4
