### ISSUE TITLE
Dependency installation failure

### ISSUE THREAD

**Issue by ptourlas** [epam/ketcher#926]
**Steps to Reproduce**
1. `git clone git@github.com:epam/ketcher.git`
2. Open in VSCode.
3. `node --version ---> v16.13.0`
4. `yarn --version ---> v3.1.0`
5. `yarn install`

**Expected behavior:** Install dependencies described in `package.json`.

**Actual behavior:** Yarn runs for a few minutes, downloads a ton of zip files in `.yarn/cache` and fails when trying to build `node-sass`.

**Screenshots**
![yarn-cache](https://user-images.githubusercontent.com/46487703/140758461-a778c9ee-058c-417a-b740-1523d2df3307.png)
![yarn-output-1](https://user-images.githubusercontent.com/46487703/140758488-44ddd199-0131-4c5a-9049-37d9b7f0db42.png)
![yarn-output-2](https://user-images.githubusercontent.com/46487703/140758507-0cd25828-2d3f-4ad9-a097-466fb66ac08a.png)

**OS:**
 Ubuntu 20.04.3 LTS

**Additional context:** Outside the project folder, `yarn --version` gives `1.22.17`

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
