### ISSUE TITLE
Hide elements. select-lasso hides all select group

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#930]
**Steps to Reproduce**
1. Insert select-lasso to the query (http://localhost:4001/?hiddenControls=select-lasso)
2. Click Enter

**Expected behavior**
Select lasso is hidden
**Actual behavior**
All select group is hidden

**Screenshots**

![select lasso](https://user-images.githubusercontent.com/93334478/140770434-fb366044-3853-433e-86db-ce5c3895486d.png)
**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47
 -

**Comment by r1z3rISGOD** [comment]
By agreement with Andrei, we decided to remove the ability to hide select and select-lasso

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
The ability to hide select and select-lasso is removed
