### ISSUE TITLE
Remake select and rotate tools for FGs

### ISSUE THREAD

**Issue by r1z3rISGOD** [epam/ketcher#934]
Improving 2 moments for 2.4 release of Functional Groups:

1. Select tool should select all FG if any element of FG is touched by it
AC:
1.1. GIVEN Ketcher user looking on the expanded Functional group on the canvas AND having any Selection tool selected WHEN selecting any bond or atom of this expanded Functional Group THEN Ketcher selects all the Functional Group elements and highlights all FG on the canvas 

2. Provide the ability to rotate FG:
AC:
2.1. GIVEN Ketcher user looking on the expanded Functional group on the canvas AND having it selected (_we can only have all FG selected_) WHEN clicking on the Rotate tool and moving the selected fragment THEN FG is rotating on the canvas in accordance with the general rules and FG is acting like the S-Group rotated

2.2. GIVEN Ketcher user looking on the expanded Functional group on the canvas AND having nothing selected on the canvas WHEN clicking on the Rotate tool and moving the canvas content THEN all canvas content including FG is rotating on the canvas in accordance with the general rules and FG is acting like the S-Group rotated

2.3. GIVEN Ketcher user looking on the expanded Functional group on the canvas AND having it selected (_we can only have all FG selected_) WHEN clicking on the Horizontal flip OR Vertical Flip THEN selected content including FG is flipped on the canvas in accordance with the general rules and FG is acting as the S-Group flipped

2.4. GIVEN Ketcher user looking on the expanded Functional group on the canvas AND having nothing selected on the canvas WHEN clicking on the Horizontal flip OR Vertical Flip THEN all canvas content including FG is flipped on the canvas in accordance with the general rules and FG is acting as the S-Group flipped

**Comment by Alena-Guznischeva** [comment]
AC added for both abilities. Please, pay attention to Flips - not sure they were considered when fix was applied.

**Comment by AllaZhbanova** [comment]
https://github.com/epam/ketcher/issues/952
Tested on 2.4
