### ISSUE TITLE
Remake "Remove Functional Groups" modal's text

### ISSUE THREAD

**Issue by r1z3rISGOD** [epam/ketcher#936]
Please, change the text for the modal window Ketcher is displaying when forbidden tools are applied to the single atoms & bonds inside expanded Functional Group. The text should be:
EDIT ABBREVIATION
A change was detected for the abbreviation. Do you want to remove the abbreviation information from the structure and continue work with separate atoms and bonds?

Buttons should be called _Remove Abbreviation_ and _Cancel_

**Comment by Alena-Guznischeva** [comment]
Text added

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
![edit](https://user-images.githubusercontent.com/93334478/141125248-49edb76a-48be-4887-9ec0-6696786f2a36.png)
