### ISSUE TITLE
Redesign the floating windows - Structure check

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#940]
Change the visual representation of the floating windows appearing for the Structure Check operations. 

GIVEN Ketcher user having something on the canvas WHEN clicking on the Structure Check operation THEN 
Ketcher displays a floating window with settings displayed on the left panel with the ability to mark and unmark the settings AND 
Warnings displayed on the right part of the window AND 
Warnings are displayed in accordance with the Settings marked and the list of warnings is updated immediately when the list of marked settings is updated AND
I can close window with the cross icon or using the Esc hotkey

Use the designs below: 

![image](https://user-images.githubusercontent.com/90251323/141073051-309168fc-ee13-477d-8a3f-5506d2f6081a.png)
![image](https://user-images.githubusercontent.com/90251323/141073077-d90559fa-001e-400c-9155-647edbb5b0c8.png)

**Comment by AllaZhbanova** [comment]
Implemented, tested on v. 2.5
