### ISSUE TITLE
Redesign the floating windows - R-Groups

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#953]
Change the visual representation of the R-Group window 

GIVEN Ketcher user having something or nothing on the canvas having R-Group tool selected WHEN clicking on the canvas  THEN
Ketcher displays a floating R-Group window with the list of all R-Groups as available and a button to confirm adding the R-Group to the canvas AND
I can select only one R-Group from the presented and confirm adding to the canvas by clicking OK button AND
I can't confirm adding to the canvas if the R-Group is not selected AND
I can close the window with the cross icon or by using the Esc hotkey 

GIVEN Ketcher user having R-Group on the canvas and having R-Group tool selected WHEN clicking on the R-Group on the canvas THEN
Ketcher displays a floating R-Group window with the same behavior as for adding new R-Group on the canvas

GIVEN Ketcher user having something on the canvas and having R-Group Fragment tool selected WHEN selecting fragment on the canvas THEN
Ketcher displays a floating R-Group window with the same behavior as for adding new R-Group on the canvas AND list of available R-Groups the items that are included in the selected fragment should be disabled

GIVEN Ketcher user having something R-Group Fragment on the canvas and having R-Group Fragment tool selected WHEN selecting R-Group Fragment on the canvas THEN
Ketcher displays a floating R-Group Logic window with the ability to change Occurrence, RestH flag, and Condition AND
confirm new R-Group Fragment settings by clicking on OK AND
close the window without change with cross icon or by using the Esc hotkey 

Use the design: 

![image](https://user-images.githubusercontent.com/90251323/141265807-c88a2ab4-3116-4017-8b20-d2cff3d2f202.png)

**Comment by Alena-Guznischeva** [comment]
Need design for one more window - R-Group Logic

**Comment by AnaMoskvina** [comment]
Latest designs:
![r_group](https://user-images.githubusercontent.com/77681522/143881716-99efe5e2-0a99-4153-b268-c112735d5c6d.PNG)
![logic_condition](https://user-images.githubusercontent.com/77681522/143881710-b5a3559a-3217-436f-94fa-f9fbbf18e082.PNG)
![attachment_points](https://user-images.githubusercontent.com/77681522/143881714-14ffd313-98c6-476e-88d9-7560a3c9202f.PNG)

**Comment by AnaMoskvina** [comment]
RestH and Condition fields should be separate
Final design for R-group logic condition dialog:
![logic_new](https://user-images.githubusercontent.com/77681522/144059858-b35954d0-91a1-4351-9dfe-02e72b0943ba.png)

**Comment by AnaMoskvina** [comment]
**R-group logic form behaves differently in Demo and in master (release 2.4. behaves like master):**

WHEN there're few R-Group members on canvas, user can choose some other then 'always' option(s) in "Option" select in format "IF R__ THEN R__", AND
when user chooses any option different from "always":

**Demo:**
- "Occurrence" value changes automatically;
- "RestH" checkbox is set selected automatically;
I.e. other form fields depend on "Option" value

**Master / Release 2.4.**
- "Occurrence" value does not change;
- "RestH" checkbox status does not change;
I.e. other form fields does not depend on "Option" value

**TODO:** 
Behavior in demo is correct, thus changes in Master / Release 2.4. should be made.
Note: there're errors occurring in demo after submitting form

**Comment by ViktorMakarov-EPAM** [comment]
Discussed with Alena. Current behaviour is correct. **Behaviour  in demo is wrong**

**Comment by ZhannaNovikova** [comment]
Changes in the requirements: 
"I can select only one R-Group from the presented and confirm adding to the canvas by clicking OK button" **have been changed to**  "I can select **one or multiple** R-Groups from the presented and confirm adding to the canvas by clicking OK button". Approved by @Alena-Guznischeva
