### ISSUE TITLE
Redesign the floating windows - Attachment Point Tool

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#954]
Change the visual representation of the window for Attachment Point Tool

GIVEN Ketcher user having something on the canvas and having Attachment Point Tool selected WHEN clicking on the atom on the canvas THEN
Ketcher displays a floating window displaying current settings of the attachment points with the ability to mark and unmark the Primary & Secondary attachment points as visible AND
confirm the new settings by clicking on the OK button AND
close the window without saving by using cross icon or by using Esc hotkey

Use the design:

![image](https://user-images.githubusercontent.com/90251323/141267330-792464b2-3740-499a-8cb3-3bb9c7fe0eeb.png)

**Comment by AllaZhbanova** [comment]
Implemented, tested v.2.5
