### ISSUE TITLE
Redesign the floating windows - Settings window

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#964]
Change the visual representation of the Settings window.

GIVEN Ketcher user WHEN clicking on Settings icon THEN I see the window with the settings AND
there is a sidebar on the left representing the settings categories on the left with General category selected by default when the window is opened AND
I can select different categories by clicking on the item in the sidebar and Ketcher will represent the settings for this category AND
I can change the settings and save new values by clicking on Save and Ketcher immediately applies the new settings value for the canvas content AND
I can close the window without saving the settings by clicking on the cross icon or by using Esc hotkey AND
I can save my settings to the file AND
I can open settings from the file AND
I can reset settings to the default ones

Use the design: 

![image](https://user-images.githubusercontent.com/90251323/141754555-1ce53c06-ee5f-46ad-a559-dd3a75acc84a.png)

**Comment by Alena-Guznischeva** [comment]
Please, note that new icons have appeared for the Settings categories. Please, use them for categories design.

**Comment by ViktoriiaFedotkina** [comment]
Select component will be redesigned in the issue https://github.com/epam/ketcher/issues/1056

**Comment by AllaZhbanova** [comment]
Tested v.2.5

**Comment by AndreiMazol** [comment]
Need to  retest

cc:  @AllaZhbanova

**Comment by AllaZhbanova** [comment]
retested v.2.5
