### ISSUE TITLE
Peptide mode/General mode switch 

### ISSUE THREAD

**Issue by Alena-Guznischeva** [epam/ketcher#972]
Implement the ability to switch the mode Ketcher editor is represented on the screen. 
We don't have visual representation right now. 

The following rules should be applied:
1. From the general Ketcher mode (the only mode in the current Ketcher) user should be able to initiate switching to the Peptide mode
2. From the new Peptide mode use should be able to initiate switching to the General mode
3. Canvas position & content should not be changed right now
4. There is no additional conditions on when the switches should work
5. There is no need to confirm switching right now

**Comment by AllaZhbanova** [comment]
Tested v.2.5
