### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by jaohbib** [epam/ketcher#99]
npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@2.1.2: Please update to latest version
npm WARN deprecated eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @types/testing-library__dom@7.5.0: This is a stub types definition. testing-library__dom provides its own type definitions, so you do not need this installed.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> husky@4.3.0 install /home/jaoh/git/ketcher_neu/ketcher/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> node-sass@5.0.0 install /home/jaoh/git/ketcher_neu/ketcher/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/jaoh/.npm/node-sass/5.0.0/linux-x64-72_binding.node

> core-js@2.6.11 postinstall /home/jaoh/git/ketcher_neu/ketcher/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.7.0 postinstall /home/jaoh/git/ketcher_neu/ketcher/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.7.0 postinstall /home/jaoh/git/ketcher_neu/ketcher/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

> husky@4.3.0 postinstall /home/jaoh/git/ketcher_neu/ketcher/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

> node-sass@5.0.0 postinstall /home/jaoh/git/ketcher_neu/ketcher/node_modules/node-sass
> node scripts/build.js

Binary found at /home/jaoh/git/ketcher_neu/ketcher/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint@^7.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-flowtype@^5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@6.0.0 requires a peer of eslint-plugin-react@^7.20.3 but none is installed. You must install peer dependencies yourself.

added 2286 packages from 983 contributors and audited 2294 packages in 46.226s

173 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

jaoh@pubpharm:~/git/ketcher_neu/ketcher$ npm run build

> @ketcher/react@2.0.0-RC build /home/jaoh/git/ketcher_neu/ketcher
> rollup -c -m inline

src/index.tsx → dist/index.js, dist/index.modern.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
query-string (imported by src/script/index.js)
[!] Error: Could not resolve './files/transform-flip-V.svg' from src/icons/index.tsx
Error: Could not resolve './files/transform-flip-V.svg' from src/icons/index.tsx
    at error (/home/jaoh/git/ketcher_neu/ketcher/node_modules/rollup/dist/shared/rollup.js:5252:30)
    at ModuleLoader.handleResolveId (/home/jaoh/git/ketcher_neu/ketcher/node_modules/rollup/dist/shared/rollup.js:18393:24)
    at /home/jaoh/git/ketcher_neu/ketcher/node_modules/rollup/dist/shared/rollup.js:18362:22
    at async Promise.all (index 64)
    at ModuleLoader.fetchStaticDependencies (/home/jaoh/git/ketcher_neu/ketcher/node_modules/rollup/dist/shared/rollup.js:18360:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/home/jaoh/git/ketcher_neu/ketcher/node_modules/rollup/dist/shared/rollup.js:18337:9)
    at async Promise.all (index 2)
    at ModuleLoader.fetchStaticDependencies (/home/jaoh/git/ketcher_neu/ketcher/node_modules/rollup/dist/shared/rollup.js:18360:34)
    at async Promise.all (index 0)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ketcher/react@2.0.0-RC build: `rollup -c -m inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ketcher/react@2.0.0-RC build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jaoh/.npm/_logs/2020-11-13T13_08_10_025Z-debug.log

**Comment by AndreiMazol** [comment]
Dear @jaohbib ,

the issue has been fixed in scope of #101.  Please inform us if it is reproduced again.

Best regards,
Ketcher team
