### ISSUE TITLE
IndigoException: element: can not calculate valence on C, charge 0, connectivity 6

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/ketcher#995]
**Steps to Reproduce**
1. Place chain on the canvas
2. Change some bonds to triple
3. Click Layout

**Expected behavior**
The structure is changed their position

**Actual behavior**
Error is shown

**Screenshots**
![error](https://user-images.githubusercontent.com/93334478/142842892-7a25370f-5d33-47a0-a788-b7e801556ff9.png)

**Desktop (please complete the following information):**
 - OS: Chrome Version 93.0.4577.63, Firefox Version 92.0, Microsoft Edge Version 93.0.961.47

**Comment by ElenaOdnoshivkina** [comment]
Related issue: https://github.com/epam/Indigo/issues/533

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
